fix: removes calendar also from SelectedCalendar once deleted
calcom/cal.com pull request #10012
Opened 2023-07-08 11:30 UTC by Pradumn27

## What does this PR do?

Fixes the database inconsistency caused when a calendar is being deleted, as even after being deleted it was still present in the SelectedCalendars table.

Fixes #9988 

https://github.com/calcom/cal.com/assets/47187878/61f9f865-41ef-4753-82de-7a89b94efde1

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- Connect a calendar
- Check that it is present in the database's SelectedCalendar table
- delete it
- See that it is also removed from the SelectedCalendar table

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

2023-07-20 23:36 UTC, joeauyeung requested changes, later dismissed
@Pradumn27 thank you for you contribution.

Testing this, only the primary calendar is deleted from the `SelectedCalendars` table. The expected behaviour is all calendars associated with that calendar integration should be deleted.

2023-07-21 14:20 UTC, Pradumn27 commented
Thanks for the review @joeauyeung , have done the changes accordingly and now all the selected calendars associated with that account are getting deleted.

2023-08-02 06:06 UTC, keithwillcode commented
Curious if this fixes #10066

2023-08-09 14:22 UTC, joeauyeung approved these changes
LGTM. Thanks for your contribution @Pradumn27

2023-08-09 14:22 UTC, joeauyeung commented on packages/trpc/server/routers/loggedInViewer/deleteCredential.handler.ts
> +    const calendars = await calendar?.listCalendars();
I like this approach for our current selected calendars, but I think we can improve this. I'm going to approve for now as this is a great solution.

2023-08-09 14:22 UTC, merged