Feat/embed detection test
calcom/cal.com pull request #10014
Opened 2023-07-08 21:15 UTC by Pradumn27

## What does this PR do?

This PR adds e2e tests to check for the styling of the embed page of eventType and also to check whether isEmbed becomes true once we change the window.name property

Fixes #9386 
/claim #9386 

## Type of change

- Chore (refactoring code, technical debt, workflow improvements)

## How should this be tested?

- [x] Run automated e2e tests

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

2023-07-13 14:20 UTC, hariombalhara commented on apps/web/playwright/embed-pages.e2e.ts
@Pradumn27 Let's move this file along with this file in the same folder https://github.com/calcom/cal.com/blob/3f93e6000d9285486a62f9d55bdb3d726d9f5882/packages/embeds/embed-core/playwright/tests/action-based.e2e.ts#L17

2023-07-13 14:22 UTC, hariombalhara requested changes
Requested one change @Pradumn27 . If tests pass after that it will be good to merge.

2023-07-13 16:23 UTC, Pradumn27 commented
> Requested one change @Pradumn27 . If tests pass after that it will be good to merge.

Thanks for the review @hariombalhara , have changed the file location and the tests are also passing!

2023-07-14 07:20 UTC, Pradumn27 commented
> Requested one change @Pradumn27 . If tests pass after that it will be good to merge.

Thanks for the review @hariombalhara ,I have done the requested changes and the tests are passing!

2023-07-17 03:15 UTC, hariombalhara approved these changes

2023-07-17 03:16 UTC, merged