chore: cron workflow tidying
calcom/cal.com pull request #10127
Opened 2023-07-13 08:44 UTC by nicktrn

## What does this PR do?

Did some cron + curl tidying while reading through the codebase. Pasted crontab.guru output for easy read and verify. The curl flags will reduce unecessary progress meter output in the logs, while retaining previous --fail functionality.

Before:
![pre](https://github.com/calcom/cal.com/assets/55853254/69ff0207-1b77-4516-9ac2-6af47c79b385)

After:
![post](https://github.com/calcom/cal.com/assets/55853254/7bcad3d7-6adb-4e0f-8379-5422b2a676f4)

## Requirement/Documentation

N/A

## Type of change

  - [x] Chore (refactoring code, technical debt, workflow improvements)

## How should this be tested?

Cron schedule step values are [supported by Github](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule:~:text=/-,Step%20values,-20/15%20*%20*%20*%20*) and the curl flags are standard.

## Mandatory Tasks

  - [ ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist

- I have read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code follows the style guidelines of this project
- I have commented my code, particularly in hard-to-understand areas
- I have checked if my PR needs changes to the documentation

2023-07-13 08:51 UTC, nicktrn reviewed
Ready for review

2023-07-13 08:51 UTC, nicktrn commented on .github/workflows/cron-bookingReminder.yml
> +    - cron: "0/15 * * * *"
Simpler and easier to edit in the future

2023-07-13 08:51 UTC, nicktrn commented on .github/workflows/cron-bookingReminder.yml
> +            -sSf
--silent --show-error --fail

Hide progress while showing and failing on errors

2023-07-13 08:51 UTC, nicktrn commented on .github/workflows/cron-downgradeUsers.yml
> +    # Runs “At 00:00 on day-of-month 1.” (see https://crontab.guru)
Be explicit for people unfamiliar with cron

2023-08-19 10:03 UTC, nicktrn commented
Just rebased. Very minor but still relevant change.

2023-08-21 07:58 UTC, hariombalhara commented on .github/workflows/cron-scheduleEmailReminders.yml
> +    - cron: "0/15 * * * *"
Same here

2023-08-21 07:58 UTC, hariombalhara commented on .github/workflows/cron-scheduleWhatsappReminders.yml
> +    - cron: "0/15 * * * *"
Here too

2023-08-21 07:58 UTC, hariombalhara commented on .github/workflows/cron-stale-issue.yml
> +    # Runs “At 00:00.” (see https://crontab.guru)
```suggestion
    # Runs “At 00:00.” everyday (see https://crontab.guru)
```

2023-08-21 07:59 UTC, hariombalhara commented on .github/workflows/submodule-sync.yml
> +    # Runs “At minute 15 past every 4th hour.” (see https://crontab.guru)
```suggestion
    # Runs "At minute 15 past every 4th hour." (see https://crontab.guru)
```

2023-08-21 08:00 UTC, hariombalhara requested changes
Thanks @nicktrn 🙏 I have left some comments.

2023-08-21 09:52 UTC, nicktrn commented
Thanks for reviewing. I have changed it to `*/15` which is of course equivalent.

On a side note:
Unsure which cron this wouldn't work with. Definitely works with Github cron. The [example for step values](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule:~:text=/-,Step%20values,-20/15%20*%20*%20*%20*) even uses this syntax, i.e. `20/15`, which crontab.guru also complains about. Maybe the guru is wrong here. (It happily accepts `0-0/15`)

2023-08-23 12:12 UTC, hariombalhara approved these changes

2023-08-23 12:13 UTC, hariombalhara commented
> Thanks for reviewing. I have changed it to `*/15` which is of course equivalent.
> 
> On a side note: Unsure which cron this wouldn't work with. Definitely works with Github cron. The [example for step values](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule:~:text=/-,Step%20values,-20/15%20*%20*%20*%20*) even uses this syntax, i.e. `20/15`, which crontab.guru also complains about. Maybe the guru is wrong here. (It happily accepts `0-0/15`)

Frankly, I have no idea. I just saw the problem there. I asked ChatGPT too and it too mentioned that it's not recommended to use 0/15

2023-08-23 12:13 UTC, merged

2023-08-23 13:30 UTC, nicktrn commented
Certainly a surprising result. Good practice to verify in any case, keeps everyone on their toes. Thanks again :pray: