fix: Improve continue button on org-add-team and validations
calcom/cal.com pull request #10122
Opened 2023-07-13 04:01 UTC by alannnc

## What does this PR do?

- disables button if no team name it's entered
- validates all inputs have team names and no duplicates
- Fixes some validations on the server before creating new team

Fixes #10112 

https://www.loom.com/share/c5ed930f84924e569d4f00a2c1d9fad8

## Requirement/Documentation

  - If there is a requirement document, please, share it here.
  - If there is ab UI/UX design document, please, share it here.

## Type of change

  - [X] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

  - Are there environment variables that should be set? No
  - What are the minimal test data to have? A newly created org team on the onboarding page step 5
  - What is expected (happy path) to have (input and output)? Any team name should be valid
  - Any other important info that could help to test that PR. No

## Mandatory Tasks

  - [ ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist

- I haven't added tests that prove my fix is effective or that my feature works

2023-07-13 04:02 UTC, alannnc commented on packages/features/ee/organizations/components/AddNewTeamsForm.tsx
> +import { Plus, X, ArrowRight } from "@calcom/ui/components/icon";
Can be imported from calcom lib

2023-07-13 04:02 UTC, alannnc commented on packages/features/ee/organizations/components/AddNewTeamsForm.tsx
> +  const [inputValues, setInputValues] = useState<string[]>([]);
Can be initialized as empty array

2023-07-13 04:03 UTC, alannnc commented on packages/features/ee/organizations/components/AddNewTeamsForm.tsx
> +        // before pushing to next page
Comment to help understand the flow of submit

2023-07-13 04:03 UTC, alannnc commented on packages/features/ee/organizations/components/AddNewTeamsForm.tsx
> +  };
Frontend validations

2023-07-13 04:03 UTC, alannnc commented on packages/features/ee/organizations/components/AddNewTeamsForm.tsx
> +            value={inputValues[index] || ""}
As inputValues can be undefined we set value on textField to empty string so react doesn't complain about
controlled/uncontrolled inputs.

2023-07-13 04:04 UTC, alannnc commented on packages/features/ee/organizations/components/AddNewTeamsForm.tsx
> +            placeholder={index === 0 ? t("org_team_names_example") : ""}
Only displaying placeholder on first input

2023-07-13 04:05 UTC, alannnc commented on packages/features/ee/organizations/components/AddNewTeamsForm.tsx
> +                  aria-label="Remove Team">
should change to translation string

2023-07-13 04:05 UTC, alannnc commented on packages/features/ee/organizations/components/AddNewTeamsForm.tsx
> -        }}>
Moved function to own declaration

2023-07-13 04:05 UTC, alannnc commented on packages/trpc/server/routers/viewer/organizations/createTeams.handler.ts
> +  }
return early

2023-07-13 04:06 UTC, alannnc commented on packages/trpc/server/routers/viewer/organizations/createTeams.handler.ts
> +  if (orgId !== user.organizationId) {
we using orgId from input so we should validate input.orgId matches with user in ctx

2023-07-13 04:06 UTC, alannnc commented on packages/trpc/server/routers/viewer/organizations/createTeams.handler.ts
> +      // accepted: true,
Validating team creation to specific membership.role

2023-07-13 04:06 UTC, alannnc commented on packages/trpc/server/routers/viewer/organizations/createTeams.handler.ts
> +  const parseTeams = teamMetadataSchema.safeParse(organization?.metadata);
safeParse so we can throw custom error and not 500

2023-07-13 04:07 UTC, alannnc commented on packages/trpc/server/routers/viewer/organizations/createTeams.handler.ts
> +    teamNames.map((item) => slugify(item)).includes(slug)
was validating ["Teams"] with ["teams'] so this validation wasn't case sensitive

2023-07-13 04:08 UTC, alannnc commented on packages/trpc/server/routers/viewer/organizations/createTeams.handler.ts
> +  }
When input teamNames has the same length that deplicatedSlugs that means every input it's duplicated so we should return duplicatedSlugs w/o creating any team.

2023-07-13 04:08 UTC, alannnc commented on packages/trpc/server/routers/viewer/organizations/createTeams.handler.ts
> +      if (!duplicatedSlugs.includes(slugify(name))) {
Case sensitive matching

2023-07-13 04:08 UTC, alannnc commented on packages/trpc/server/routers/viewer/organizations/createTeams.handler.ts
> +}
Custom Handler Errors

2023-07-13 04:09 UTC, alannnc commented on packages/ui/components/form/inputs/Input.tsx
> +type InputProps = JSX.IntrinsicElements["input"] & { isFullWidth?: boolean };
This an extra, was receiving error on console, it looks like it doesn't have any use.

2023-07-13 04:09 UTC, alannnc commented on packages/ui/components/form/inputs/Input.tsx
> -            isStandaloneField={false}
declared as false an optional on type, no other use found in entire codebase.

2023-07-13 20:26 UTC, ericrommel requested changes
If you delete the text written, turning it to empty again, the button should go back to disable status.

https://www.loom.com/share/9edd483ae2dd47a19097b6a147256f24

**Note 1**: If you add a new team, without filling out anything, the button is turned to enabled. If there is no text, the button should remain disabled. In case of at least one field is filled out, then the button should be turned to enable but a notification should be shown in case any other field is empty.
**Note 2**: Would it be good to have placeholders for new fields?

2023-07-13 21:20 UTC, alannnc commented
> **Note 1**: If you add a new team, without filling out anything, the button is turned to enabled. If there is no text, the button should remain disabled. In case of at least one field is filled out, then the button should be turned to enable but a notification should be shown in case any other field is empty. **Note 2**: Would it be good to have placeholders for new fields?
Note 1: I leaved it like this because it felt more adequate. But sure I can make this change.
Note 2: To me it felt noisy having the same placeholder on everything. What we can do here it's having probably different team names for every input, having 10 and then repeat. 
Also now that I'm thinking we should put a limit on this form. Does 10 teams sounds reasonable? You can still add them later in other page.
@ericrommel

2023-07-13 21:34 UTC, ericrommel commented
> > **Note 1**: If you add a new team, without filling out anything, the button is turned to enabled. If there is no text, the button should remain disabled. In case of at least one field is filled out, then the button should be turned to enable but a notification should be shown in case any other field is empty. **Note 2**: Would it be good to have placeholders for new fields?
> 
> Note 1: I leaved it like this because it felt more adequate. But sure I can make this change. Note 2: To me it felt noisy having the same placeholder on everything. What we can do here it's having probably different team names for every input, having 10 and then repeat. Also now that I'm thinking we should put a limit on this form. Does 10 teams sounds reasonable? You can still add them later in other page. @ericrommel

About Note 1, we end up to back to the original problem. That's why IMAO we should have better control here.
About Note 2, I'm okay with not having placeholders for additional team fields.

Definitely, we should limit. I would go with 5 instead of 10 and have a notification to inform that more can be added later. Good catch ;)

![image](https://github.com/calcom/cal.com/assets/10250819/8a8d2d62-7be5-49d6-a503-18110fcfbb8e)

2023-07-13 22:02 UTC, alannnc commented
@ericrommel Just updated with latest suggestions

2023-07-13 22:17 UTC, ericrommel commented
> @ericrommel Just updated with latest suggestions

Hey @alannnc,

Sorry about that but I'm still finding issues. Please, check the video to better understand:

https://www.loom.com/share/1b689d304b844dcfb258f37d89f710ec

2023-07-13 23:22 UTC, alannnc commented
> > @ericrommel Just updated with latest suggestions
> 
> Hey @alannnc,
> 
> Sorry about that but I'm still finding issues. Please, check the video to better understand:
> 
> https://www.loom.com/share/1b689d304b844dcfb258f37d89f710ec

For the change, I opted for a secure way, if you added a new team input Continue button goes back to disabled till you fill a value there. Or does it makes more sense allowing input blanks but ignoring them?
@ericrommel

2023-07-13 23:29 UTC, ericrommel commented
> > > @ericrommel Just updated with latest suggestions
> > 
> > 
> > Hey @alannnc,
> > Sorry about that but I'm still finding issues. Please, check the video to better understand:
> > https://www.loom.com/share/1b689d304b844dcfb258f37d89f710ec
> 
> For the change, I opted for a secure way, if you added a new team input Continue button goes back to disabled till you fill a value there. Or does it makes more sense allowing input blanks but ignoring them? @ericrommel

@alannnc, you have opted very correctly but the issue is, if you check the Loom if I add all possible fields (5 in our new case) when I fill out the third one (2 are still missing), the button goes to be enabled. If the Loom is not good enough, we can connect and I can show you step by step.

2023-07-13 23:30 UTC, alannnc commented
> > > > @ericrommel Just updated with latest suggestions
> > > 
> > > 
> > > Hey @alannnc,
> > > Sorry about that but I'm still finding issues. Please, check the video to better understand:
> > > https://www.loom.com/share/1b689d304b844dcfb258f37d89f710ec
> > 
> > 
> > For the change, I opted for a secure way, if you added a new team input Continue button goes back to disabled till you fill a value there. Or does it makes more sense allowing input blanks but ignoring them? @ericrommel
> 
> @alannnc, you have opted very correctly but the issue is, if you check the Loom if I add all possible fields (5 in our new case) when I fill out the third one (2 are still missing), the button goes to be enabled. If the Loom is not good enough, we can connect and I can show you step by step.

Ahh alright, I watched it several times and got confused. But yeah now that you pointed it I can try to replicate it. Thanks a lot @ericrommel.

2023-07-13 23:33 UTC, ericrommel commented
> > > > > @ericrommel Just updated with latest suggestions
> > > > 
> > > > 
> > > > Hey @alannnc,
> > > > Sorry about that but I'm still finding issues. Please, check the video to better understand:
> > > > https://www.loom.com/share/1b689d304b844dcfb258f37d89f710ec
> > > 
> > > 
> > > For the change, I opted for a secure way, if you added a new team input Continue button goes back to disabled till you fill a value there. Or does it makes more sense allowing input blanks but ignoring them? @ericrommel
> > 
> > 
> > @alannnc, you have opted very correctly but the issue is, if you check the Loom if I add all possible fields (5 in our new case) when I fill out the third one (2 are still missing), the button goes to be enabled. If the Loom is not good enough, we can connect and I can show you step by step.
> 
> Ahh alright, I watched it several times and got confused. But yeah now that you pointed it I can try to replicate it. Thanks a lot @ericrommel.

Sorry if I couldn't be clear enough. ;)

2023-07-13 23:38 UTC, alannnc commented
> Sorry if I couldn't be clear enough. ;)

Don't worry! I found the issue, was missing some initial state so was validating against -1 input every time thats why 4 input filled worked there.

2023-07-14 22:11 UTC, zomars commented on packages/features/ee/organizations/components/AddNewTeamsForm.tsx
> +  console.log({ inputValues });
```suggestion
```

2023-07-14 22:14 UTC, zomars requested changes
Overall code LGTM. But app store tests are failing. Will approve once checks and @ericrommel feedback is addressed. 🙏🏽

2023-07-14 22:14 UTC, zomars submitted a review, later dismissed
Overall code LGTM. But app store tests are failing. Will approve once checks and @ericrommel feedback is addressed. 🙏🏽

2023-07-17 20:34 UTC, alannnc commented
@ericrommel I think every issue has been handled already and test are passing now. Can we get an approve for merge?

2023-07-17 21:14 UTC, ericrommel commented
> @ericrommel I think every issue has been handled already and test are passing now. Can we get an approve for merge?

@alannnc LGTM. Everything worked fine.

2023-07-17 21:16 UTC, ericrommel approved these changes
@alannnc @zomars the findings for `org-add-team` were fixed. From my side, this is okay.

2023-07-18 00:17 UTC, merged