9985 cal 2122 possible to have same slug for team and user in an organization
calcom/cal.com pull request #10170
Opened 2023-07-15 02:47 UTC by alannnc

## What does this PR do?

- Moves invite token validation before user creation
- If token has teamId we collect every team.slug in the org or just use that team.slug so a username cannot have same team.slug.

Fixes #9985 

## Requirement/Documentation

  - If there is a requirement document, please, share it here.
  - If there is ab UI/UX design document, please, share it here.

## Type of change

  - [X] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

  - Are there environment variables that should be set? No
  - What are the minimal test data to have? A newly created orgs with a couple teams already created
  - What is expected (happy path) to have (input and output)? When inviting a user via link and he ends up on signup page, the username is validated against team slugs in the entire org or just that simple team. If username has the same name as the team he should see an error that says Username is taken.
  - Any other important info that could help to test that PR

## Mandatory Tasks

  - [ ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist

- I haven't added tests that prove my fix is effective or that my feature works

2023-07-15 02:48 UTC, alannnc commented on apps/web/pages/api/auth/signup.ts
> +      }
This code was running before user creation I think we can save a little if moved up here.

2023-07-15 02:48 UTC, alannnc commented on apps/web/pages/api/auth/signup.ts
> +      const isValidUsername = await validateUsernameInOrg(username, foundToken?.teamId);
Additionally running this function created on this PR.

2023-07-15 02:49 UTC, alannnc commented on apps/web/pages/api/auth/signup.ts
> +        });
Removed a unnecessary conditional so all of this code moved up.

2023-07-15 02:49 UTC, alannnc commented on packages/lib/validateUsernameInOrg.ts
> +        OR: [{ id: teamId }, { parentId: teamId }],
Find every team that has parentId as teamId or just a single team.

2023-07-15 02:50 UTC, alannnc commented on packages/lib/validateUsernameInOrg.ts
> +        OR: [{ id: teamId }, { parentId: teamId }],
TODO: What if org has only one team?

2023-07-15 02:56 UTC, alannnc commented on packages/trpc/server/routers/viewer/teams/inviteMember/inviteMember.handler.ts
> +         * Here we want to redirect to a different place if onboarding has been completed or not. This prevents the flash of going to teams -> Then to onboarding - also show a different email templat
typos

2023-07-15 03:05 UTC, leog requested changes
Changes look good. I think we could also take care of updating username as well, which I think relies on the domain and that’s not accurate, as the app works under “app” not the org subdomain.

2023-07-17 15:00 UTC, alannnc commented
> Changes look good. I think we could also take care of updating username as well, which I think relies on the domain and that’s not accurate, as the app works under “app” not the org subdomain.

Can we do name update on other PR? @leog

2023-07-17 15:09 UTC, leog commented
> Can we do name update on other PR? @leog

Of course @alannnc makes sense. Approving.

2023-07-17 15:10 UTC, leog approved these changes
LGTM, follow-up PR to tackle updating username is expected.

2023-07-17 15:35 UTC, alannnc commented
> LGTM, follow-up PR to tackle updating username is expected.
Here you go:
https://github.com/calcom/cal.com/issues/10196
@leog

2023-07-17 15:36 UTC, merged