Stripe webhook integration
calcom/cal.com pull request #10186
Opened 2023-07-17 02:56 UTC by zodman

- update
- Integration with stripe webhooks

## What does this PR do?

Fixes # (issue)

## Requirement/Documentation

  - If there is a requirement document, please, share it here.
  - If there is ab UI/UX design document, please, share it here.

## Type of change

  - [ ] Bug fix (non-breaking change which fixes an issue)
  - [ ] Chore (refactoring code, technical debt, workflow improvements)
  - [ ] New feature (non-breaking change which adds functionality)
  - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
  - [ ] This change requires a documentation update

## How should this be tested?

  - Are there environment variables that should be set?
  - What are the minimal test data to have?
  - What is expected (happy path) to have (input and output)?
  - Any other important info that could help to test that PR

## Mandatory Tasks

  - [ ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist

- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my PR needs changes to the documentation
- I haven't checked if my changes generate no new warnings
- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

2023-07-17 06:46 UTC, ologbonowiwi commented
Is there only one way to make the webhook work with the CLI? It is what I'm struggling with on my attempt for #9370.

The current approach could work locally but still needs manual handling for webhooks, which isn't the best approach for automated pipelines that won't run with human intervention. You'll be able to see it on my PR (which I wish I could open a draft now, but I'm unable to access my PC unfortunately)

2023-07-17 06:48 UTC, ologbonowiwi commented
We should search for another way to trigger the webhook on Stripe integration; this is what I'm struggling with on my attempt for #9370.

The current approach could work locally but still needs manual handling for webhooks, which isn't the best approach for automated pipelines that won't run with human intervention. You'll be able to see it on my PR (which I wish I could open a draft now, but I'm unable to access my PC, unfortunately)

2023-07-17 06:52 UTC, ologbonowiwi commented on yarn.lock
These changes are necessary in the context of these new e2e tests?

2023-07-17 16:22 UTC, zodman commented
> We should search for another way to trigger the webhook on Stripe integration; this is what I'm struggling with on my attempt for #9370.
> 
> The current approach could work locally but still needs manual handling for webhooks, which isn't the best approach for automated pipelines that won't run with human intervention. You'll be able to see it on my PR (which I wish I could open a draft now, but I'm unable to access my PC, unfortunately)

No manual interactions needed. If you take a look `e2e.yaml` I have  automated it.

in resume, you need download the stripe-cli, update the STRIPE_WEBHOOK_SECRET and run the e2e in parallel.

```
# you need to update the webhook_secret for getting redirected to localhost (valid for 90 days)
export STRIPE_WEBHOOK_SECRET=$(stripe listen --api-key $STRIPE_PRIVATE_KEY  --print-secret)
npx -y  npm-run-all -r -p -y -l  "stripe:listen" "e2e stripe"
```

the npm-rull-all will fire in parallel with the stripe listen to forward the webhooks to localhost and execute the e2e for stripe.

this was the easiest approach to use and it should work on the GitHub actions without manual interaction.

2023-07-17 17:20 UTC, ologbonowiwi commented
> No manual interactions needed. If you take a look e2e.yaml I have automated it.
>
> in resume, you need download the stripe-cli, update the STRIPE_WEBHOOK_SECRET and run the e2e in parallel.
>
> ```
> # you need to update the webhook_secret for getting redirected to localhost (valid for 90 days)
> export STRIPE_WEBHOOK_SECRET=$(stripe listen --api-key $STRIPE_PRIVATE_KEY  --print-secret)
> npx -y  npm-run-all -r -p -y -l  "stripe:listen" "e2e stripe"
> ```
> the npm-rull-all will fire in parallel with the stripe listen to forward the webhooks to localhost and execute the e2e for stripe.
>
> this was the easiest approach to use and it should work on the GitHub actions without manual interaction.

But where are we doing the trigger to the paid event? Didn't found it on the PR

2023-07-17 17:32 UTC, zodman commented
> But where are we doing the trigger to the paid event? Didn't found it on the PR
> > No manual interactions needed. If you take a look e2e.yaml I have automated it.
> > in resume, you need download the stripe-cli, update the STRIPE_WEBHOOK_SECRET and run the e2e in parallel.
> > ```
> > # you need to update the webhook_secret for getting redirected to localhost (valid for 90 days)
> > export STRIPE_WEBHOOK_SECRET=$(stripe listen --api-key $STRIPE_PRIVATE_KEY  --print-secret)
> > npx -y  npm-run-all -r -p -y -l  "stripe:listen" "e2e stripe"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > the npm-rull-all will fire in parallel with the stripe listen to forward the webhooks to localhost and execute the e2e for stripe.
> > this was the easiest approach to use and it should work on the GitHub actions without manual interaction.
> 
> But where are we doing the trigger to the paid event? Didn't found it on the PR

after the user introduces the CC and clicks pay. In the stripes servers send a webhook to the device registered by the `stripe listen`  what is received forwarded to  `$NEXT_PUBLIC_WEBAPP_URL/api/integrations/stripepayment/webhook` without this `stripe listen` you will never receive the webhook.

2023-07-17 18:55 UTC, ologbonowiwi commented
> after the user introduces the CC and clicks pay. In the stripes servers send a webhook to the device registered by the stripe listen what is received is forwarded to $NEXT_PUBLIC_WEBAPP_URL/api/integrations/stripepayment/webhook without this stripe listen, you will never receive the webhook.

You're right, but your code still doesn't hit the webhook with the booking paid event. For example, in the "Paid booking should be able to be cancelled and refunded" test case, you should be validating the message "This booking payment has been refunded." on the screen, which probably does not appear since the paid trigger was never hit.

I successfully fixed this, if you agree to split the bounties I can help you on the implementation

2023-07-19 06:05 UTC, ologbonowiwi commented
Hey @zodman, the `BOOKING_PAID` webhook it's already implemented on the project; but your test case doesn't validate it 👀

2023-08-18 02:12 UTC, joeauyeung requested changes
Thanks for your contribution @zodman. I left a comment about using the `stripe.webhooks.generateTestHeaderString` method.

2023-08-28 09:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/calcom/cal.com?pullRequest=10186) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/calcom/cal.com?pullRequest=10186) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: shivamklr<br/>:x: zodman<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/calcom/cal.com?pullRequest=10186) it.</sub>

2023-09-19 00:15 UTC, closed without merging