chor: fixing some inital re-renders
calcom/cal.com pull request #10185
Opened 2023-07-16 21:57 UTC by sean-brydon

Fixes inital re-renders in event-types pages. 

Will carry on adding to this PR/a new PR with additional fixes changes

2023-07-16 21:58 UTC, sean-brydon commented on apps/web/components/eventtype/EventAvailabilityTab.tsx
> +const EventTypeScheduleDetails = memo(
Just wrapped this in a memo - was only being re-rendered by the parent component and not any props that would cause a re-render

2023-07-16 21:59 UTC, sean-brydon commented on packages/features/shell/Shell.tsx
> +
Refactored to use memo for this - we didnt need to calculate each time + re-render if there wasnt a org. 

(default should be no org imho so i made these changes to default to no org value)

2023-07-16 22:00 UTC, sean-brydon commented on packages/features/shell/Shell.tsx
> -                    : undefined
Can't be current with the options 

view_public_page -> opens in a new tab
copy_public_page_link -> copies and isnt a page
settings -> layout changes and so no point doing this calc

2023-07-16 22:00 UTC, sean-brydon commented on packages/features/tips/Tips.tsx
> +export default memo(Tips);
This just renders from internal data - no point re-rendering on every parent change (since this was in shell it was re-rendering a lot)

2023-07-17 10:21 UTC, keithwillcode requested changes
Looks good. 

There’s some type fixes failing though.

2023-07-17 12:12 UTC, sean-brydon commented on apps/web/components/I18nLanguageHandler.tsx
> +    if (Object.keys(i18n).length === 0) return;
No need for lodash here

2023-07-17 12:12 UTC, sean-brydon commented on apps/web/components/PageWrapper.tsx
> +  useI18nLanguageHandler();
Converted to a hook - it was a component always returning null

2023-07-17 12:13 UTC, sean-brydon commented on packages/features/insights/filters/EventTypeList.tsx
> +export const EventTypeList = memo(() => {
Parents were causing this to re-render on prop change - we didnt need this as all state is internal here

2023-07-17 12:14 UTC, sean-brydon commented on packages/lib/hooks/useTraceUpdate.tsx
> +export function useTraceUpdate(props: { [s: string]: unknown } | ArrayLike<unknown>) {
Helper to be used while debugging - call it in any component and see why it it updated/ how many times it re-rendered

2023-07-17 13:02 UTC, keithwillcode submitted a review, later dismissed

2023-07-17 16:56 UTC, zomars submitted a review, later dismissed
Definitively a step in the right direction. Awesome work @sean-brydon 

![Ship it](https://media.giphy.com/media/CEIHJK4ympvVe0fAdU/giphy.gif)

2023-07-19 09:09 UTC, PeerRich approved these changes

2023-07-19 09:19 UTC, merged