feat: Add full names in the description
calcom/cal.com pull request #10239
Opened 2023-07-18 21:52 UTC by imrishabh18

## What does this PR do?

Fixes #10194 
/claim #10194 

<img width="312" alt="Screenshot 2023-07-19 at 3 18 36 AM" src="https://github.com/calcom/cal.com/assets/38923768/a7a85bcb-86ce-4854-a534-5909a5a675ed">

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

2023-07-18 21:57 UTC, imrishabh18 commented
@PeerRich Can you take a look at my approach to solve this please?

2023-07-19 09:57 UTC, jyellapu requested changes
Please check the comments.

2023-07-19 09:57 UTC, jyellapu commented on packages/features/bookings/Booker/components/EventMeta.tsx
> +              {defaultEvents.find((defaultEvent) => defaultEvent.description === event.description) ? (
Please check , if you can use "isDynamic" flag present in the event to determine which path to take than relying on defaultEvent description.

2023-07-19 09:57 UTC, jyellapu commented on packages/features/bookings/Booker/utils/layout.ts
> +    for (let i = 0; i < numberOfUsers - 1; i++) {
Please check the ticket description, it's mentioned
"if its more, it's "Firstname 1, Firstname2 & more"

2023-07-19 09:57 UTC, jyellapu commented on packages/features/bookings/Booker/utils/layout.ts
> +  if (numberOfUsers === 1) {
Please handle numUsers == 0 case also.

2023-07-19 11:59 UTC, PeerRich requested changes
the initial ticket was meant for only "dynamic booking links" only, not for all events

2023-07-19 13:15 UTC, PeerRich commented
this is the correct implementation: https://github.com/calcom/cal.com/pull/10251 thank you for trying tho @imrishabh18

2023-07-19 13:15 UTC, closed without merging