fix: including parentId when filter by eventTypeId happens
calcom/cal.com pull request #10262
Opened 2023-07-19 23:49 UTC by alannnc

## What does this PR do?

- When as admin/owner filters and select a eventTypeId that it's currently managed event type, count fails since using eventType filter will only look for specific id, now we add OR lookup for eventTypeId OR parentId.

Fixes #10261 

## Requirement/Documentation

- If there is a requirement document, please, share it here.
- If there is ab UI/UX design document, please, share it here.

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- Are there environment variables that should be set? No.
- What are the minimal test data to have? Having yarn seed-insights could help.
- What is expected (happy path) to have (input and output)? Managed event type bookings should be count when viewing team insights with a specific eventTypeId selected.
- Any other important info that could help to test that PR

## Mandatory Tasks

- [ ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist

- I haven't added tests that prove my fix is effective or that my feature works

2023-07-19 23:50 UTC, alannnc commented on packages/features/insights/server/events.ts
> +  };
This functions it's not related to this problem but found out some irregularities when counting.

2023-07-19 23:51 UTC, alannnc commented on packages/features/insights/server/trpc-router.ts
> +          },
New conditional so we can get bookings that comes from a managed event Type.

2023-07-19 23:51 UTC, alannnc commented on packages/features/insights/server/trpc-router.ts
> +          count: totalCompleted,
This is the fix for the irregularity found earlier.

2023-07-19 23:51 UTC, alannnc commented on packages/prisma/migrations/20230719214513_update_booking_time_status_fields_event_parent_id/migration.sql
> +-- View: public.BookingsTimeStatus
New migration, views can only be created or replaced.

2023-07-19 23:52 UTC, alannnc commented on packages/prisma/schema.prisma
> +  eventParentId Int?
Just added a field but changed everything.

2023-07-20 00:07 UTC, zomars approved these changes

2023-07-20 00:08 UTC, zomars requested changes
Migration failed to apply cleanly to the testing DB

![Uploading image.png…]()

2023-07-20 18:35 UTC, alannnc commented
> Migration failed to apply cleanly to the testing DB
> 
> <img alt="image" width="742" src="https://user-images.githubusercontent.com/3504472/254738309-437eba4f-c8cd-488a-a46e-1b4a3b5201c1.png">

Just uploaded some changes, should be valid now.

2023-07-20 19:19 UTC, zomars approved these changes
![LGTM](https://media3.giphy.com/media/NytMLKyiaIh6VH9SPm/200.gif)

2023-07-20 19:19 UTC, merged