feat: choose the email you want to be displayed (CALCOM-5774-2)
calcom/cal.com pull request #10348
Opened 2023-07-24 21:20 UTC by gitstart-calcom

Here is the GitStart Ticket for this pull request: [CALCOM-5774](https://developers.gitstart.com/client/calcom/ticket/CALCOM-5774)

This PR implements these feedback from client

<img width="930" alt="image" src="https://github.com/GitStartHQ/client-cal.com/assets/26940294/6a4f8de3-d20c-40c6-907d-c9c84b33bfd9">

<img width="921" alt="image" src="https://github.com/GitStartHQ/client-cal.com/assets/26940294/1a01ca02-ead1-4d48-8a0d-6175f96d355a">

### Demo

Google Calendar Email:
https://www.loom.com/share/dc8c439a316f448ca2a84c497651554b

Apple Calendar:
https://www.loom.com/share/053f9a3f5fd54a98abfe4159f39a4b02

2023-08-18 02:22 UTC, joeauyeung requested changes
Looking back at the issue. I noticed one of the desired outcomes was having a dropdown of available emails to display on the booking. I think we can add this, especially since not all calendars are associated with an email.

2023-08-21 18:18 UTC, gitstart-calcom commented
Hi @joeauyeung Peer updated on the task https://github.com/calcom/cal.com/issues/5774#issuecomment-1505729370. From Peer's response, we thought we wouldn't need to create an additional dropdown, we did a dropdown before to select emails but we were asked to remove it

2023-08-23 14:04 UTC, joeauyeung commented
@gitstart-calcom I talked with @ciaranha about this, and we think it's best to include a dropdown for the user to choose which email to display on the booking. It would also be nice to have a toggle similar to the video below that says that shows we are automatically choosing the email.

This should help handle calendars without emails associated with them and prevent any bugs in the future.

[

https://github.com/calcom/cal.com/assets/65426560/7c88c607-aa72-4bdb-b32f-abf95558494d

](url)

2023-08-23 15:29 UTC, joeauyeung commented
Here are the designs as well: https://www.figma.com/file/UajFu4M1APhn2AywAEJkJr/New-Features?type=design&node-id=4549-409104&mode=design

2023-08-28 09:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/calcom/cal.com?pullRequest=10348) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/calcom/cal.com?pullRequest=10348) before we can accept your contribution.<br/>**0** out of **4** committers have signed the CLA.<br/><br/>:x: gitstart<br/>:x: keithwillcode<br/>:x: joeauyeung<br/>:x: gitstart-calcom<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/calcom/cal.com?pullRequest=10348) it.</sub>

2023-08-30 12:08 UTC, gitstart-calcom commented
Hi @joeauyeung we made the requested changes, please take a look 😄

2023-09-01 16:03 UTC, joeauyeung requested changes
Awesome work with implementing the design I've tested this with the following calendars:
- GCal
- Outlook
- Radicale (CalDAV)
- Zoho (CalDAV)

I do have some feedback.
![image](https://github.com/calcom/cal.com/assets/65426560/41f6646f-c13e-4ea5-88b2-5e931929c5f4)
- This option should be opt in
- When it is selected it's still showing the account email

![image](https://github.com/calcom/cal.com/assets/65426560/6a553840-a4b1-4846-9f1f-31eab302393f)
- The account email should be an option here

2023-09-04 21:27 UTC, gitstart-calcom commented
Hey @joeauyeung We need some clarifications on the feedback:

- "This option should be opt in":
Does this mean the toggle should not be automatically selected ?

- "When it is selected it's still showing the account email":
The emails are blurred out, so it’s difficult to decipher what we should do here.

2023-10-12 10:29 UTC, ThyMinimalDev commented on packages/trpc/server/routers/viewer/availability/calendarOverlay.handler.ts
> +import { prisma } from "@calcom/prisma";
formatted by pre commit hook

2023-10-12 10:30 UTC, ThyMinimalDev commented on project.inlang.json
>  }
formatting done by pre-commit hook

2023-10-12 10:30 UTC, ThyMinimalDev commented on packages/features/embed/lib/EmbedTabs.tsx
> +      const iframeSrc = `${EMBED_PREVIEW_HTML_URL}?embedType=${embedType}&calLink=${calLink}&embedLibUrl=${embedLibUrl}&bookerUrl=${bookerUrl}`;
formatting done by pre commit hook

2023-10-12 12:03 UTC, ThyMinimalDev commented
not sure what is wrong with the commit tree of this branch, using git rebase to fix conflicts is not working

2023-10-12 12:56 UTC, PeerRich commented
i dont think this PR is implemented correctly and not worth fixing

2023-10-12 12:56 UTC, closed without merging