fix: link escaping in booking page
calcom/cal.com pull request #10360
Opened 2023-07-25 09:03 UTC by G3root

## What does this PR do?

Fixes #10352

## Requirement/Documentation

before:
![Screenshot 2023-07-25 at 14-31-42 test Admin Example Cal com](https://github.com/calcom/cal.com/assets/84864519/3c56cb45-767e-4ceb-94af-73090b6d7a16)

after:

![Screenshot 2023-07-25 at 14-30-35 test Admin Example Cal com](https://github.com/calcom/cal.com/assets/84864519/3a54ab39-de50-410a-8c4c-fe470fd0d73d)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

2023-07-25 10:59 UTC, hariombalhara commented on packages/features/bookings/lib/getLocationOptionsForSelect.ts
> +        inputPlaceholder: t(eventLocation?.attendeeInputPlaceholder || "", {
@G3root Does` t` fn remove http: ?

2023-07-25 11:07 UTC, hariombalhara requested changes
Thanks @G3root 🙏 Left some comments

2023-07-27 08:11 UTC, G3root commented
@hariombalhara pushed some changes to make it typesafe. tried `interpolation: {escapeValue:false}` but it didn't work out

2023-08-11 08:05 UTC, hariombalhara approved these changes
Fixed the root cause @G3root . Left a comment in the code as it was super weird.

2023-08-12 21:31 UTC, merged