Refactors video integrations
calcom/cal.com pull request #1037
Opened 2021-10-24 22:15 UTC by zomars

fixes #1034

## WARNING

We need might need to run a migration in the `BookingReference` table to update all values in the `type` column from `daily` to `daily_video`:

![image](https://user-images.githubusercontent.com/3504472/138615173-3128c38b-9417-49b2-966a-ae2b39cd45bf.png)

- [x] Run this query in DB before merging:
```sql
UPDATE "BookingReference" SET "type"='daily_video' WHERE "type"='daily';
```

This is big one but it was necessary

- Refactors the way we handle video integrations
- Moved away Zoom and Daily logic away from videoClient.ts
- Try to keeps integration specific logic as encapsulated as possible
- Tons of type fixes
- Fixed opt-in bookings for Daily

2021-10-25 22:07 UTC, zomars reviewed
Tested locally and self-reviewed. Ready for review

2021-10-26 08:47 UTC, KATT requested changes
Please remove the `@ts-ignore`s - it's better to have them visible until we fix them - I think it's ok that not all PRs pass the type check one as long as they are steps in the right direction

2021-10-26 09:39 UTC, pumfleet approved these changes
I only had a brief look, but it looks good. Great work @zomars :)

2021-10-26 13:10 UTC, mihaic195 approved these changes

2021-10-26 15:59 UTC, KATT approved these changes

2021-10-26 16:17 UTC, merged