9982 cal 2120 org owneradmin cant see the teams created by other owneradmin
calcom/cal.com pull request #10430
Opened 2023-07-27 22:39 UTC by alannnc

## What does this PR do?

Fixes # (issue)

## Requirement/Documentation

- If there is a requirement document, please, share it here.
- If there is ab UI/UX design document, please, share it here.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

- Are there environment variables that should be set?
- What are the minimal test data to have?
- What is expected (happy path) to have (input and output)?
- Any other important info that could help to test that PR

## Mandatory Tasks

- [ ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist

- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my PR needs changes to the documentation
- I haven't checked if my changes generate no new warnings
- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

2023-07-27 22:40 UTC, alannnc commented on packages/features/ee/teams/components/MemberListItem.tsx
>      });
Undo changes on this file.

2023-07-27 22:41 UTC, alannnc commented on packages/features/ee/teams/components/TeamInviteListItem.tsx
> +  console.log("team invite list", team);
Undo changes on this file.

2023-07-27 22:41 UTC, alannnc commented on packages/features/ee/teams/pages/team-listing-view.tsx
> +const TeamListingView = () => {
Getting the right name for the component.

2023-07-28 09:32 UTC, alannnc commented on packages/features/ee/organizations/pages/settings/other-team-members-view.tsx
> +  // const [query, setQuery] = useState<string | undefined>("");
There will some code commented on this file until I make it work.

2023-07-28 09:33 UTC, alannnc commented on packages/features/ee/organizations/pages/settings/other-team-members-view.tsx
> +  const limit = 100;
Limiting temporarily, till paginate works.

2023-07-28 09:40 UTC, alannnc commented on packages/trpc/server/routers/viewer/teams/update.handler.ts
> +      throw new TRPCError({ code: "UNAUTHORIZED" });
First we validate if !orgAdmin then we validate if !isTeamAdmin.

2023-07-28 09:46 UTC, alannnc reviewed
Created new components/trpc calls since I didn't want to reuse teams logic since future updates on those could affect our new ones. It's also a good thing to keep code on it's own domain.

- Partially hide member search function and team appearance edit.

2023-07-28 09:50 UTC, sean-brydon requested changes, later dismissed
Hey - i know this is in draft but i don't see why we can't re-use the pages/components we currently use for teams. They are gonna be displaying the exact same data.

2023-07-28 10:01 UTC, alannnc commented
> Hey - i know this is in draft but i don't see why we can't re-use the pages/components we currently use for teams. They are gonna be displaying the exact same data.
@sean-brydon 

Tried but didn't like the solution since I felt I was juggling on the server to get the data for 2 scenarios, this means components there are highly tied up to teams trpcs data. Domain wise orgs feature shouldn't import directly from teams, this can lead to bad things.
Probably moving some components from there to a generic and then reusing them.

2023-07-28 15:30 UTC, zomars submitted a review, later dismissed

2023-07-28 15:30 UTC, zomars commented on packages/features/ee/organizations/pages/components/OtherTeamsListing.tsx
> +import { useRouter } from "next/router";
Same here

2023-07-28 17:49 UTC, alannnc commented on packages/features/ee/organizations/pages/settings/other-team-members-view.tsx
> +import { useRouter } from "next/router";
I'm getting teamId from the url param, seems like useSearchParams only works for queries and not from paths?
https://nextjs.org/docs/app/api-reference/functions/use-search-params
@zomars

2023-07-28 18:03 UTC, alannnc commented on packages/features/ee/organizations/pages/settings/other-team-members-view.tsx
> +import { useRouter } from "next/router";
nvm figured it out

2023-07-28 18:36 UTC, alannnc reviewed
@zomars Changes for useRouter are done.

2023-08-01 12:56 UTC, leog submitted a review, later dismissed
Code LGTM 👍

2023-08-02 19:08 UTC, PeerRich approved these changes
reapproving on behalf of leo's past review

2023-08-02 19:09 UTC, merged