fix: signup password hint validation
calcom/cal.com pull request #10454
Opened 2023-07-28 18:58 UTC by MehulZR

## What does this PR do?

Fixes #10379 (issue)

https://github.com/calcom/cal.com/assets/86384652/34994639-ba82-4ebf-9772-79c5b3ed4ebb

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

2023-07-28 19:00 UTC, MehulZR commented on packages/ui/components/form/inputs/HintOrErrors.tsx
> +  // no hints passed, field errors exist and they are custom ones
Was not able to figure out how this scenario happens.
Some information regarding this will be helpful in inspecting it further.

2023-08-01 10:03 UTC, Udit-takkar requested changes
@MehulZR Awesome work but we already have common function that validate password that we use in other parts of the codebase.

you should do something like

```
const passwordSchema = z.string().superRefine((data, ctx) => {
  const isStrict = false;
  const result = isPasswordValid(data, true, isStrict);

  Object.keys(result).map((key: string) => {
    if (!result[key as keyof typeof result]) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        path: [key],
        message: key,
      });
    }
  });
});

```

check out apps/web/components/setup/AdminUser.tsx file. I don't think you would require to make changes in HintOrErrors or Input file. the only difference would be that AdminUser.tsx uses isStrict = true because it requires password of length of 15.

you can have a look at isPasswordValid function you might have to change the condition to >=7 from > 7 to allow 7 characters length.

Also this signup page make a request to /api/auth/singup which uses z.string().min(7) so you should create a common schema and use it on both pages/signup and api/auth/signup

2023-08-02 18:49 UTC, MehulZR commented on packages/features/auth/lib/isPasswordValid.ts
> -      if (password[i] === password[i].toLowerCase()) low = true;
These conditions passes if the given input is a symbol (< > , ? /).

2023-08-11 12:16 UTC, Udit-takkar commented on apps/web/pages/api/auth/signup.ts
> +import { apiSignupSchema as signupSchema } from "pages/signup";
NIT: We can move apiSignupSchema to zod-utils

2023-08-11 12:17 UTC, Udit-takkar submitted a review, later dismissed
LGTM. Great work @MehulZR

2023-08-26 08:06 UTC, Udit-takkar commented
TODO -

- [ ]  fix conflicts

2023-08-28 08:28 UTC, Udit-takkar approved these changes
LGTM. Fixed conflicts

2023-08-28 09:19 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/calcom/cal.com?pullRequest=10454) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/calcom/cal.com?pullRequest=10454) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: Udit-takkar<br/>:x: MehulZR<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/calcom/cal.com?pullRequest=10454) it.</sub>

2023-08-29 11:56 UTC, merged