fix: {ATTENDEE} workflow variable always uses first attendee for for seated event
calcom/cal.com pull request #10468
Opened 2023-07-30 11:22 UTC by rkreddy99

## What does this PR do?

Fixes an issue where {ATTENDEE} workflow variable always uses first attendee for for seated event.

Fixes #10451 

## Requirement/Documentation

- `scheduleEmailReminder` function doesnt use `sendTo` param for scheduling workflow reminders, instead always takes the first attendee from the event.
- so now check if sendTo attendee is present in evt.attendees, if yes use that otherwise fallback to evt.attendees[0].

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- Schedule a workflow for seated event and check whether {ATTENDEE} variable is getting correctly replaced/

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist

- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

2023-07-30 11:24 UTC, rkreddy99 commented
@CarinaWolli can you check whether this is the intended change, will make changes in the flow as per suggestions.

2023-08-02 14:24 UTC, CarinaWolli requested changes
Works for emails, but we have the same issue SMS as well. Could you add that fix there too? 🙏

2023-08-02 14:24 UTC, CarinaWolli commented on packages/features/ee/workflows/lib/reminders/emailReminderManager.ts
> +      }
```suggestion
```
Can be removed

2023-08-03 04:29 UTC, rkreddy99 commented
@CarinaWolli made changes for sms

and some refactor in https://github.com/calcom/cal.com/pull/10468/commits/548f120f286c15a65000aeebec3164d2a92dbe5e, can you check this out.

2023-08-03 14:46 UTC, CarinaWolli reviewed
Thank you for addressing my feedback, I left you one more comment 🙏

2023-08-03 17:15 UTC, rkreddy99 commented on packages/features/ee/workflows/lib/reminders/smsReminderManager.ts
> +      evt.attendees.find((attendee) => attendee.email === evt.responses?.email?.value);
Hey yup it should be enough, removing the redundant check

2023-08-04 13:39 UTC, CarinaWolli approved these changes
Great work, looks good now 🙌🏻 Thank you!

2023-08-04 13:53 UTC, merged