fix: auth redirect
calcom/cal.com pull request #10556
Opened 2023-08-03 09:21 UTC by Udit-takkar

## What does this PR do?

Fixes https://github.com/calcom/cal.com/issues/10495

https://github.com/calcom/cal.com/assets/53316345/b47f9965-316b-4397-9f5f-42fdd497dc61

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)

2023-08-03 09:21 UTC, Udit-takkar commented on apps/web/next.config.js
> +      },
https://github.com/calcom/cal.com/issues/10495#issuecomment-1663574950

2023-08-03 10:54 UTC, hariombalhara commented on apps/web/next.config.js
> +        permanent: true,
```suggestion
        permanent: false,
```

This is a temporary thing so we shouldn't make it permanent. Once a permanent redirect is done on browser, it is cached forever and can't be changed

2023-08-03 10:55 UTC, hariombalhara requested changes
Left a blocking comment, otherwise it's good

2023-08-07 11:20 UTC, hariombalhara approved these changes

2023-08-07 11:21 UTC, merged