feat: 2fa backup codes
calcom/cal.com pull request #10600
Opened 2023-08-04 16:03 UTC by nicktrn

## What does this PR do?

- generate and display backup codes during 2fa setup
- enable their use during 2fa login flow

![backup-codes-1](https://github.com/calcom/cal.com/assets/55853254/d139236b-1c5e-4b98-b82e-b4681a8d0f2f)
![backup-codes-2](https://github.com/calcom/cal.com/assets/55853254/94f35e94-ab55-429c-9849-efd3c4409cf2)
![backup-codes-3](https://github.com/calcom/cal.com/assets/55853254/887e3a92-b5a0-4569-94a5-de56bdd1558b)

Fixes #9910
/claim #9910

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## How should this be tested?

1. Setup 2fa to see the generated backup codes
2. Try to login with them by clicking on "Lost access"

## Mandatory Tasks

- [ ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist

- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

2023-08-04 17:10 UTC, nicktrn reviewed
Ready for review

2023-08-04 17:10 UTC, nicktrn commented on apps/web/components/settings/EnableTwoFactorModal.tsx
> -        onEnable();
we need to call this later as we added an extra step

2023-08-04 17:10 UTC, nicktrn commented on apps/web/components/settings/EnableTwoFactorModal.tsx
> +            <div className="mt-5 grid grid-cols-2 gap-1 text-center font-mono md:pl-10 md:pr-10">
open to suggestions re proper spacing and display of the codes

2023-08-04 17:10 UTC, nicktrn commented on apps/web/pages/api/auth/two-factor/totp/setup.ts
> +      backupCodes: symmetricEncrypt(JSON.stringify(backupCodes), process.env.CALENDSO_ENCRYPTION_KEY),
encrypt instead of hash, so we can display them in the future

2023-08-04 17:10 UTC, nicktrn commented on apps/web/pages/auth/login.tsx
> +    else if (res.error === ErrorCode.MissingBackupCodes) setErrorMessage(t("missing_backup_codes"));
new error codes to display useful messages

2023-08-04 17:10 UTC, nicktrn commented on packages/features/auth/lib/next-auth-options.ts
> +        const index = backupCodes.indexOf(credentials.backupCode.replaceAll("-", ""));
accept backup codes with dashes (stored without)

2023-08-07 13:47 UTC, CarinaWolli commented
@nicktrn Could you take a look at the failed type check? (https://github.com/calcom/cal.com/actions/runs/5764434728/job/15628390445?pr=10600)

2023-08-07 21:28 UTC, nicktrn commented
> Could you take a look at the failed type check?

Not sure how I missed that. Fixed now.

2023-08-08 11:11 UTC, Udit-takkar requested changes
1) Backup codes are not deleted from DB when i disable two factor auth after disabling it

2) I should be able to disable two factor auth using backup code. current it requires two factor code.

<img width="737" alt="Screenshot 2023-08-08 at 4 39 56 PM" src="https://github.com/calcom/cal.com/assets/53316345/8283433c-6254-4daa-83fe-ae8f2a67ef77">

3) we should use password field here with show password button. ( We can do this later in a follow up PR)

<img width="637" alt="Screenshot 2023-08-08 at 4 05 07 PM" src="https://github.com/calcom/cal.com/assets/53316345/b03d9427-2a84-42ef-9bb8-6f90abe51dd6">

5) download button should be replaced with close button position ( Can be done later in a follow up PR)

<img width="650" alt="Screenshot 2023-08-08 at 4 37 41 PM" src="https://github.com/calcom/cal.com/assets/53316345/c68cbec3-2bf7-489f-b3b1-05945f458f7c">

2023-08-08 14:17 UTC, Udit-takkar commented
> Swap the buttons or get rid of the close button completely? Should clicking download then also close? Would be great if you could clarify.

I mean just the position of button should be swapped. it should be Close, copy and download (right most) and download should have black background something like

<img width="559" alt="Screenshot 2023-08-08 at 7 46 18 PM" src="https://github.com/calcom/cal.com/assets/53316345/c70e5163-8769-4015-9006-da29b7535bc7">

2023-08-08 19:19 UTC, nicktrn commented
Fixed a few things. Hopefully didn't extend the scope too far.

2FA Disable:
- allow using backup codes instead of totp
- remove backup codes with 2fa
- use correct password input
- disable totp autofocus (password input comes first)

Misc:
- make password visibility toggle non-tabbable (can revert this but was getting increasingly annoying while testing)
- re-arranged close, copy, and download buttons
- set min and max lengths for backup code inputs
- fix and extend 2fa tests

Another thing I got working locally but will add in a follow-up PR:
- auto-submit during login for both OTP and backup codes (I don't think we should add this for disabling 2FA)

One last thing to discuss would be the backup codes storage scheme as it would be painful to change retroactively I imagine.

2023-08-09 07:55 UTC, nicktrn commented
Demo scenario: PR has just been merged and user who already has 2FA enabled wants to try the new feature

[backup-codes-fixes.webm](https://github.com/calcom/cal.com/assets/55853254/8323c23f-7ec4-4d6e-aeb2-3d54f8c4ffb9)

00:10 - New "Lost access" button during 2FA login
00:14 - Message: User has no backup codes yet
00:36 - New "Lost access" button during 2FA disable
01:03 - 2FA setup: Re-arranged "Close", "Copy", and "Download" buttons
01:28 - User can log in using newly generated backup code
01:48 - User can't use the same backup code twice

Also discovered TOTP codes currently don't have any grace period. Submit even just 1 second over the limit and it won't be accepted. Will fix this in a separate PR.

2023-08-09 08:57 UTC, sean-brydon commented
@Jaibles can you review this from a design side when you get a min?

2023-08-22 22:02 UTC, nicktrn commented
Rebased as merge conflicts were building up. Any chance we could finish getting this reviewed?

I think the only design additions are the new "Lost access" buttons during 2fa login / disable, and the display of backup codes. The only thing I'm sure about there is that monospace is needed.

Please only check the video in https://github.com/calcom/cal.com/pull/10600#issuecomment-1670848635 as the rest is outdated.

2023-08-23 07:34 UTC, Udit-takkar approved these changes, later dismissed
LGTM

2023-08-28 09:19 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/calcom/cal.com?pullRequest=10600) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/calcom/cal.com?pullRequest=10600) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/calcom/cal.com?pullRequest=10600) it.</sub>

2023-08-29 11:57 UTC, PeerRich approved these changes

2023-08-30 07:33 UTC, merged

2026-04-10 00:44 UTC, mfeuerstein reviewed
## PR Review — approved

Reviewed 16 files. 0 high-severity issues found. Verdict: approved.

### `apps/web/components/auth/TwoFactor.tsx` (low)

- Reviewed apps/web/components/auth/TwoFactor.tsx — looks good

### `apps/web/components/settings/DisableTwoFactorModal.tsx` (low)

- Reviewed apps/web/components/settings/DisableTwoFactorModal.tsx — looks good

### `apps/web/pages/auth/login.tsx` (low)

- Reviewed apps/web/pages/auth/login.tsx — looks good

### `apps/web/components/settings/TwoFactorAuthAPI.ts` (low)

- Reviewed apps/web/components/settings/TwoFactorAuthAPI.ts — looks good

### `apps/web/playwright/login.2fa.e2e.ts` (medium)

- Reviewed apps/web/playwright/login.2fa.e2e.ts — looks good

### `apps/web/components/auth/BackupCode.tsx` (low)

- Reviewed apps/web/components/auth/BackupCode.tsx — looks good

### `apps/web/public/static/locales/en/common.json` (low)

- Reviewed apps/web/public/static/locales/en/common.json — looks good

### `apps/web/pages/api/auth/two-factor/totp/disable.ts` (low)

- Reviewed apps/web/pages/api/auth/two-factor/totp/disable.ts — looks good

### `packages/features/auth/lib/ErrorCode.ts` (low)

- Reviewed packages/features/auth/lib/ErrorCode.ts — looks good

### `packages/features/auth/lib/next-auth-options.ts` (low)

- Reviewed packages/features/auth/lib/next-auth-options.ts — looks good

### `apps/web/pages/api/auth/two-factor/totp/setup.ts` (low)

- Reviewed apps/web/pages/api/auth/two-factor/totp/setup.ts — looks good

### `apps/web/components/settings/EnableTwoFactorModal.tsx` (low)

- Reviewed apps/web/components/settings/EnableTwoFactorModal.tsx — looks good

### `packages/prisma/schema.prisma` (low)

- Reviewed packages/prisma/schema.prisma — looks good

### `packages/prisma/migrations/20230804153419_add_backup_codes/migration.sql` (low)

- Reviewed packages/prisma/migrations/20230804153419_add_backup_codes/migration.sql — looks good

### `packages/ui/components/form/inputs/Input.tsx` (low)

- Reviewed packages/ui/components/form/inputs/Input.tsx — looks good

### `packages/lib/test/builder.ts` (low)

- Reviewed packages/lib/test/builder.ts — looks good

2026-04-10 00:48 UTC, mfeuerstein reviewed
## PR Review — approved

Reviewed 16 files. 0 high-severity issues found. Verdict: approved.

### `apps/web/components/auth/BackupCode.tsx` (low)

- Reviewed apps/web/components/auth/BackupCode.tsx — looks good

### `apps/web/components/settings/DisableTwoFactorModal.tsx` (low)

- Reviewed apps/web/components/settings/DisableTwoFactorModal.tsx — looks good

### `apps/web/components/auth/TwoFactor.tsx` (low)

- Reviewed apps/web/components/auth/TwoFactor.tsx — looks good

### `apps/web/pages/api/auth/two-factor/totp/setup.ts` (low)

- Reviewed apps/web/pages/api/auth/two-factor/totp/setup.ts — looks good

### `apps/web/components/settings/EnableTwoFactorModal.tsx` (low)

- Reviewed apps/web/components/settings/EnableTwoFactorModal.tsx — looks good

### `apps/web/pages/api/auth/two-factor/totp/disable.ts` (low)

- Reviewed apps/web/pages/api/auth/two-factor/totp/disable.ts — looks good

### `apps/web/playwright/login.2fa.e2e.ts` (medium)

- Reviewed apps/web/playwright/login.2fa.e2e.ts — looks good

### `apps/web/pages/auth/login.tsx` (low)

- Reviewed apps/web/pages/auth/login.tsx — looks good

### `packages/features/auth/lib/ErrorCode.ts` (low)

- Reviewed packages/features/auth/lib/ErrorCode.ts — looks good

### `apps/web/components/settings/TwoFactorAuthAPI.ts` (low)

- Reviewed apps/web/components/settings/TwoFactorAuthAPI.ts — looks good

### `apps/web/public/static/locales/en/common.json` (low)

- Reviewed apps/web/public/static/locales/en/common.json — looks good

### `packages/prisma/schema.prisma` (low)

- Reviewed packages/prisma/schema.prisma — looks good

### `packages/lib/test/builder.ts` (low)

- Reviewed packages/lib/test/builder.ts — looks good

### `packages/features/auth/lib/next-auth-options.ts` (low)

- Reviewed packages/features/auth/lib/next-auth-options.ts — looks good

### `packages/prisma/migrations/20230804153419_add_backup_codes/migration.sql` (low)

- Reviewed packages/prisma/migrations/20230804153419_add_backup_codes/migration.sql — looks good

### `packages/ui/components/form/inputs/Input.tsx` (low)

- Reviewed packages/ui/components/form/inputs/Input.tsx — looks good

2026-08-12 18:17 UTC, ron-x5labs requested changes
## Code Review: Generate and display 2FA backup codes

### Problem
This PR adds backup code generation/display during 2FA setup and enables their use during 2FA login and 2FA disable flows, fixing #9910.

### Solution Reviewed
Generates 10 backup codes (`crypto.randomBytes(5)` each) at 2FA setup, stores them encrypted in a new `backupCodes` column, displays them in a new `DisplayBackupCodes` setup step with copy/download/close actions, and adds a backup-code verification path alongside the existing TOTP path in both `next-auth-options.ts` (login) and `disable.ts` (disable). Existing 2FA users get a `MissingBackupCodes` error since they have no codes.

### Summary
The feature is well-structured and addresses prior review feedback (codes now wiped on disable, disable-with-backup-code supported, password field added). However, there are **two blocking security issues**: a password-verification bypass in the login backup-code path, and a non-atomic read-modify-write race that breaks single-use enforcement. Several non-blocking issues around entropy, timing-safe comparison, error handling, and DOM validity should also be addressed.

### Files Reviewed
- `apps/web/components/auth/BackupCode.tsx` — deeply reviewed
- `apps/web/components/auth/TwoFactor.tsx` — deeply reviewed
- `apps/web/components/settings/DisableTwoFactorModal.tsx` — deeply reviewed
- `apps/web/components/settings/EnableTwoFactorModal.tsx` — deeply reviewed
- `apps/web/components/settings/TwoFactorAuthAPI.ts` — deeply reviewed
- `apps/web/pages/api/auth/two-factor/totp/disable.ts` — deeply reviewed
- `apps/web/pages/api/auth/two-factor/totp/setup.ts` — deeply reviewed
- `apps/web/pages/auth/login.tsx` — deeply reviewed
- `apps/web/playwright/login.2fa.e2e.ts` — deeply reviewed
- `apps/web/public/static/locales/en/common.json` — lightly reviewed (i18n keys)
- `packages/features/auth/lib/ErrorCode.ts` — deeply reviewed
- `packages/features/auth/lib/next-auth-options.ts` — deeply reviewed
- `packages/lib/test/builder.ts` — lightly reviewed (test fixture)
- `packages/prisma/migrations/20230804153419_add_backup_codes/migration.sql` — lightly reviewed (migration)
- `packages/prisma/schema.prisma` — lightly reviewed (schema)
- `packages/ui/components/form/inputs/Input.tsx` — lightly reviewed (unrelated tabIndex fix)

### Verification
- Typecheck/lint/tests — **skipped**: no `node_modules` installed in the local clone; installing the pnpm monorepo is infeasible for this review. All findings are from static analysis of the diff and surrounding source.

### Test Coverage Gaps
The Playwright test exercises the backup-code UI (download/copy/close buttons) but has **no test** for the backup-code login flow, the backup-code disable-2FA flow, or verification that a consumed backup code cannot be reused. Given the single-use security contract, at minimum the replay-prevention path should be covered.

### Verdict
**Request changes** — the password bypass and single-use race condition are security-critical and must be fixed before merge.

<!-- pr-local-code-review:v1 -->

2026-08-12 18:17 UTC, ron-x5labs commented on packages/features/auth/lib/next-auth-options.ts
> +      if (user.twoFactorEnabled && credentials.backupCode) {
🔴 **Blocking — password verification bypass.** The password check at line 121 is gated on `!credentials.totpCode`:

```js
if (user.password && !credentials.totpCode) { /* verify password */ }
```

This guard was designed to skip password re-verification on the second-factor step (TOTP is sent on the second attempt after `SecondFactorRequired`). But with the new backup-code path, an attacker who calls the credentials endpoint directly with `{ email, totpCode: "x", backupCode: "guess" }` skips the entire password block (totpCode is truthy) and lands here — authentication is reduced from **password + backup code** to **backup code only**. The attacker needs only the victim's email to brute-force backup codes.

Fix: always verify the password before entering the backup-code path, e.g. remove the `!credentials.totpCode` condition or restructure so the backup-code path also requires a verified password.

2026-08-12 18:17 UTC, ron-x5labs commented on packages/features/auth/lib/next-auth-options.ts
> +        await prisma.user.update({
🔴 **Blocking — non-atomic backup code consumption (race condition).** The read-modify-write cycle (decrypt → `indexOf` → set `null` → re-encrypt → `prisma.user.update`) runs with no transaction or optimistic lock. Two concurrent logins with the **same** backup code can both pass `indexOf` before either write commits, allowing a single-use code to authenticate multiple sessions (replay). Two concurrent logins with **different** codes cause lost writes — request B's write resurrects the code request A just consumed.

Fix: wrap in a Prisma interactive transaction (`prisma.$transaction`) or use a conditional update with a `WHERE backupCodes = <old encrypted value>` clause to detect concurrent modification.

2026-08-12 18:17 UTC, ron-x5labs commented on apps/web/pages/api/auth/two-factor/totp/setup.ts
> +  const backupCodes = Array.from(Array(10), () => crypto.randomBytes(5).toString("hex"));
🟡 **Low entropy.** `crypto.randomBytes(5)` yields 40 bits per code (10 hex chars). This is below the 64–80 bits typically recommended for authentication tokens. Given the password-bypass issue above (where backup codes become the sole authentication barrier), the lower entropy is more exploitable. Consider `crypto.randomBytes(8)` (64 bits) or `randomBytes(10)` (80 bits). Note that `formatBackupCode` in `EnableTwoFactorModal.tsx` and `BackupCode.tsx`'s `minLength`/`maxLength` would need updating if the length changes.

2026-08-12 18:17 UTC, ron-x5labs commented on packages/features/auth/lib/next-auth-options.ts
> +        const index = backupCodes.indexOf(credentials.backupCode.replaceAll("-", ""));
🟡 **Non-constant-time comparison.** `indexOf` uses JavaScript `===` which short-circuits on the first differing character. A timing side-channel could theoretically narrow down matching codes. For security-critical token comparison, use `crypto.timingSafeEqual` with a constant-time scan over all codes. The same pattern exists at `disable.ts:61`.

2026-08-12 18:17 UTC, ron-x5labs commented on packages/features/auth/lib/next-auth-options.ts
> +        if (!user.backupCodes) throw new Error(ErrorCode.MissingBackupCodes);
🟡 **Information disclosure via distinct error codes.** `MissingBackupCodes` (line 137, backup codes never set up) vs `IncorrectBackupCode` (line 145, codes exist but don't match) lets an attacker determine whether a user has ever configured backup codes. Consider collapsing both into a single generic 'invalid backup code' error. The same distinction exists in `disable.ts` at lines 55/63.

2026-08-12 18:17 UTC, ron-x5labs commented on apps/web/pages/api/auth/two-factor/totp/disable.ts
> +      throw new Error(ErrorCode.InternalServerError);
🟡 **`throw` instead of `return res.status(500).json(...)`.** An unhandled throw in a Next.js API route produces an HTML 500 page, not JSON. The client (`DisableTwoFactorModal`) calls `response.json()` which then throws, and the user sees a generic 'something went wrong'. The sibling `setup.ts:48` uses the correct `return res.status(500).json(...)` pattern. (The pre-existing TOTP path at lines 77/82 has the same bug, but the new backup-code code should follow the correct pattern.)

2026-08-12 18:17 UTC, ron-x5labs commented on apps/web/pages/api/auth/two-factor/totp/disable.ts
> +    const backupCodes = JSON.parse(symmetricDecrypt(user.backupCodes, process.env.CALENDSO_ENCRYPTION_KEY));
🟡 **No try/catch around `JSON.parse(symmetricDecrypt(...))`.** If `backupCodes` is corrupted (key rotation, truncation, migration issue), `symmetricDecrypt` can throw a crypto error and `JSON.parse` can throw a `SyntaxError` — both unhandled → HTML 500. The existing TOTP path validates `secret.length === 32` after decrypt as a corruption guard; the backup-code path has no equivalent. Consider wrapping in try/catch and returning `ErrorCode.InternalServerError`.

2026-08-12 18:17 UTC, ron-x5labs commented on apps/web/components/settings/EnableTwoFactorModal.tsx
> +                <a download="cal-backup-codes.txt" href={backupCodesUrl}>
🟡 **Invalid HTML: `<button>` nested inside `<a>`.** `<a download href={...}><Button>...</Button></a>` nests a `<button>` (what `Button` renders) inside an anchor element, which is invalid per the HTML spec (interactive content cannot nest in anchors). Browsers may restructure the DOM unpredictably and the download may not fire. Replace with a standalone `<a>` styled as a button, or keep the `<Button>` and trigger the download programmatically via a click handler that creates and clicks a temporary link.

2026-08-12 18:17 UTC, ron-x5labs commented on apps/web/components/settings/EnableTwoFactorModal.tsx
> +                    navigator.clipboard.writeText(backupCodes.map(formatBackupCode).join("\n"));
🟡 **Clipboard write not awaited / no error handling.** `navigator.clipboard.writeText(...)` returns a Promise that is neither awaited nor caught. The success toast (`showToast`) fires unconditionally even if the clipboard write fails (permission denied, insecure context, older browser). The codebase has a `useCopy` hook (`packages/lib/hooks/useCopy.ts`) that properly guards and handles errors — consider using it here.

2026-08-12 18:17 UTC, ron-x5labs commented on apps/web/components/settings/EnableTwoFactorModal.tsx
> +  const resetState = () => {
🟡 **`resetState()` doesn't clear all state.** It clears `password`, `errorMessage`, and `step`, but not `backupCodes`, `backupCodesUrl`, `dataUri`, or `secret`. If the `Dialog` component reuses the mounted component across open/close cycles, stale backup codes and QR data from a prior attempt persist and may be re-displayed. Additionally, the blob URL (`backupCodesUrl`) is never revoked on unmount or close — it's only revoked when a new one is created (line 98) — causing a minor memory leak. Add a `useEffect` cleanup that calls `URL.revokeObjectURL`.

2026-08-12 18:17 UTC, ron-x5labs commented on packages/features/auth/lib/next-auth-options.ts
> +        backupCodes[index] = null;
💡 **Consumed codes set to `null` rather than removed; exhausted state unclear.** After all 10 codes are consumed, the stored array is `[null, null, ..., null]` — which decrypts and parses fine, so `indexOf` returns -1 and the user gets `IncorrectBackupCode` ('Backup code is incorrect') rather than a meaningful 'no codes remaining' message. Consider setting `backupCodes` to `null` in the DB when no non-null entries remain, so `MissingBackupCodes` correctly fires and stale encrypted data isn't retained.

2026-08-12 18:17 UTC, ron-x5labs commented on apps/web/components/auth/BackupCode.tsx
> +export default function TwoFactor({ center = true }) {
💡 **Function named `TwoFactor` instead of `BackupCode`** (copy-paste from `TwoFactor.tsx`). Both components export a default function named `TwoFactor`, making React DevTools and stack traces ambiguous. Rename to `BackupCode`.

2026-08-12 18:17 UTC, ron-x5labs commented on apps/web/pages/api/auth/two-factor/totp/disable.ts
> +      console.error("Missing encryption key; cannot proceed with backup code login.");
💡 **Copy-paste error in log message.** The `console.error` says 'cannot proceed with backup code **login**' but this is the 2FA **disable** endpoint. Minor, but misleading when debugging production misconfiguration.

2026-08-15 08:30 UTC, ron-x5labs requested changes
## Code Review: Generate and display 2FA backup codes

### Problem
Adds backup-code generation/display during 2FA setup and enables their use during 2FA login and disable flows (fixes #9910).

### Solution Reviewed
Generates 10 backup codes (`crypto.randomBytes(5).toString("hex")`) at 2FA setup, stores them AES-256-encrypted in a new nullable `backupCodes` column, displays them in a new `DisplayBackupCodes` setup step with copy/download/close actions, and adds a backup-code verification path alongside the existing TOTP path in both `next-auth-options.ts` (login) and `disable.ts` (disable). Consumed codes are set to `null` and re-encrypted on login; all codes are wiped on disable.

### Summary
The feature is well-structured and the UI flow is clean, but there are **two blocking security issues**: a password-verification bypass in the login backup-code path (authentication reduced from password+backup to backup-only), and a non-atomic read-modify-write race that breaks single-use enforcement. Several non-blocking issues around entropy, timing-safe comparison, error handling, invalid HTML, a non-functional password show/hide toggle, and stale component state should also be addressed. Test coverage exists only for the setup UI buttons — the backup-code login, disable, and replay-prevention paths are untested.

### Verification
- Typecheck/lint/tests — skipped: no `node_modules` in the local clone; installing the pnpm monorepo is infeasible. All findings are from static analysis of the diff and surrounding source, cross-checked by parallel specialist passes.

### Verdict
**Request changes** — the password bypass and single-use race condition are security-critical and must be fixed before merge.

<!-- pr-local-code-review:v1 -->

2026-08-15 08:30 UTC, ron-x5labs commented on packages/features/auth/lib/next-auth-options.ts
> +      if (user.twoFactorEnabled && credentials.backupCode) {
🔴 **Blocking — password verification bypass.** The password check is gated on `!credentials.totpCode`:

```js
if (user.password && !credentials.totpCode) { /* verify password */ }
```

This guard was designed to skip password re-verification on the second-factor step (TOTP is sent on the second attempt after `SecondFactorRequired`). But with the new backup-code path at this line, an attacker who calls the credentials endpoint directly with `{ email, totpCode: "x", backupCode: "guess" }` skips the entire password block (totpCode is truthy) and lands in the backup-code branch — authentication is reduced from **password + backup code** to **backup code only**. The attacker needs only the victim's email to brute-force 40-bit backup codes (no password, no TOTP). Note `disable.ts` does NOT have this bug — it verifies the password unconditionally (line 40) before the backup-code check.

Fix: always verify the password for CAL-identity users regardless of `totpCode`, e.g. move the password check outside the `!credentials.totpCode` guard or add an explicit password verification step inside the backup-code branch.

2026-08-15 08:30 UTC, ron-x5labs commented on packages/features/auth/lib/next-auth-options.ts
> +        await prisma.user.update({
🔴 **Blocking — non-atomic backup code consumption (race condition).** The read-modify-write cycle (decrypt → `indexOf` → set `null` → re-encrypt → `prisma.user.update`) runs with no transaction or optimistic lock. Two concurrent logins with the **same** backup code can both pass `indexOf` before either write commits, allowing a single-use code to authenticate multiple sessions (replay). Two concurrent logins with **different** codes cause lost writes — request B's write resurrects the code request A just consumed. The `User` model has no `@version`/optimistic-lock field.

Fix: wrap in a Prisma interactive transaction (`prisma.$transaction`) with a row lock (`SELECT ... FOR UPDATE`), or use a conditional update (`updateMany` with `where: { id, backupCodes: <old encrypted value> }`) and retry/abort when `count === 0`.

2026-08-15 08:30 UTC, ron-x5labs commented on apps/web/pages/api/auth/two-factor/totp/setup.ts
> +  const backupCodes = Array.from(Array(10), () => crypto.randomBytes(5).toString("hex"));
🟡 **Low entropy.** `crypto.randomBytes(5)` yields 40 bits per code (10 hex chars). This is below the 64–80 bits typically recommended for authentication tokens. Given the password-bypass issue above (where backup codes can become the sole authentication barrier), the lower entropy is more exploitable. Consider `crypto.randomBytes(8)` (64 bits) or `randomBytes(10)` (80 bits). Note that `formatBackupCode` in `EnableTwoFactorModal.tsx` and `BackupCode.tsx`'s `minLength`/`maxLength` would need updating if the length changes.

2026-08-15 08:30 UTC, ron-x5labs commented on packages/features/auth/lib/next-auth-options.ts
> +        const index = backupCodes.indexOf(credentials.backupCode.replaceAll("-", ""));
🟡 **Non-constant-time comparison.** `indexOf` uses JavaScript `===` which short-circuits on the first differing character. A timing side-channel could theoretically narrow down matching codes. For security-critical token comparison, use `crypto.timingSafeEqual` with a constant-time scan over all codes. The same pattern exists at `disable.ts:61`.

2026-08-15 08:30 UTC, ron-x5labs commented on packages/features/auth/lib/next-auth-options.ts
> +        if (!user.backupCodes) throw new Error(ErrorCode.MissingBackupCodes);
🟡 **Information disclosure + unactionable recovery message.** `MissingBackupCodes` (line 137, codes never set up) vs `IncorrectBackupCode` (line 145, codes exist but don't match) lets an attacker determine whether a user has ever configured backup codes. Consider collapsing both into a single generic 'invalid backup code' error. The same distinction exists in `disable.ts` at lines 55/63.

Additionally, the `missing_backup_codes` locale string ("No backup codes found. Please generate them in your settings.") is surfaced in the login lost-access flow (login.tsx:155) — but a locked-out user cannot reach settings to generate codes, and there is no regenerate-backup-codes endpoint (setup.ts rejects already-enabled users with `TwoFactorAlreadyEnabled`). This particularly affects pre-existing 2FA users whose `backupCodes` column is `null` after the migration. Reword the message to direct them to recovery/contact-admin.

2026-08-15 08:30 UTC, ron-x5labs commented on apps/web/pages/api/auth/two-factor/totp/disable.ts
> +      throw new Error(ErrorCode.InternalServerError);
🟡 **`throw` instead of `return res.status(500).json(...)`.** An unhandled throw in a Next.js API route produces an HTML 500 page, not JSON. The client (`DisableTwoFactorModal`) calls `response.json()` which then throws, and the user sees a generic 'something went wrong'. The sibling `setup.ts:48` uses the correct `return res.status(500).json(...)` pattern. (The pre-existing TOTP path at lines 77/82 has the same bug, but the new backup-code code should follow the correct pattern.) Also, the `console.error` at line 50 says 'cannot proceed with backup code **login**' but this is the 2FA **disable** endpoint — misleading when debugging production misconfiguration.

2026-08-15 08:30 UTC, ron-x5labs commented on apps/web/pages/api/auth/two-factor/totp/disable.ts
> +    const backupCodes = JSON.parse(symmetricDecrypt(user.backupCodes, process.env.CALENDSO_ENCRYPTION_KEY));
🟡 **No try/catch around `JSON.parse(symmetricDecrypt(...))`.** If `backupCodes` is corrupted (key rotation, truncation, migration issue), `symmetricDecrypt` can throw a crypto error and `JSON.parse` can throw a `SyntaxError` — both unhandled → HTML 500. The existing TOTP path validates `secret.length === 32` after decrypt as a corruption guard; the backup-code path has no equivalent. The same unguarded pattern exists at `next-auth-options.ts:140`. Consider wrapping in try/catch and returning `ErrorCode.InternalServerError`.

2026-08-15 08:30 UTC, ron-x5labs commented on apps/web/components/settings/EnableTwoFactorModal.tsx
> +                <a download="cal-backup-codes.txt" href={backupCodesUrl}>
🟡 **Invalid HTML: `<button>` nested inside `<a>`.** `<a download href={...}><Button>...</Button></a>` nests a `<button>` (what `Button` renders) inside an anchor element, which is invalid per the HTML spec (interactive content cannot nest in anchors). Browsers may restructure the DOM unpredictably and the download may not fire reliably. Replace with a standalone `<a>` styled as a button, or pass `href` to `<Button>` (which renders an `<a>` when `href` is set).

2026-08-15 08:30 UTC, ron-x5labs commented on apps/web/components/settings/EnableTwoFactorModal.tsx
> +                    navigator.clipboard.writeText(backupCodes.map(formatBackupCode).join("\n"));
🟡 **Clipboard write not awaited / no error handling.** `navigator.clipboard.writeText(...)` returns a Promise that is neither awaited nor caught. The success toast (`showToast`) fires unconditionally even if the clipboard write fails (permission denied, insecure context, older browser where `navigator.clipboard` is undefined → TypeError). The codebase has a `useCopy` hook (`packages/lib/hooks/useCopy.ts`) that properly guards and handles errors — consider using it here.

```js
try {
  await navigator.clipboard.writeText(backupCodes.map(formatBackupCode).join("\n"));
  showToast(t("backup_codes_copied"), "success");
} catch {
  showToast(t("something_went_wrong"), "error");
}
```

2026-08-15 08:30 UTC, ron-x5labs commented on apps/web/components/settings/EnableTwoFactorModal.tsx
> +  const resetState = () => {
🟡 **`resetState()` doesn't clear all state; Blob URL leaked.** It clears `password`, `errorMessage`, and `step`, but not `backupCodes`, `backupCodesUrl`, `dataUri`, or `secret`. If the `Dialog` reuses the mounted component across open/close cycles, stale backup codes and QR data from a prior attempt persist and may be re-displayed. Additionally, the blob URL (`backupCodesUrl`) is only revoked when a new one is created (line 98) — never on close or unmount — causing a memory leak. Add a `useEffect` cleanup that calls `URL.revokeObjectURL` and clear the remaining state in `resetState`.

2026-08-15 08:30 UTC, ron-x5labs commented on apps/web/components/settings/EnableTwoFactorModal.tsx
>                  type="password"
🟡 **`PasswordField` passed `type="password"` breaks the show/hide toggle.** `PasswordField` (Input.tsx:36-39) computes `type={isPasswordVisible ? "text" : "password"}` then spreads `{...props}` *afterward*, so `props.type="password"` overrides the computed type on every render. The eye/eye-off icon toggles but the field never reveals the password — a non-functional control introduced by this PR. `PasswordField` owns the `type` contract; callers must not pass it. Remove `type="password"` from this `<PasswordField>`.

2026-08-15 08:30 UTC, ron-x5labs commented on apps/web/components/settings/DisableTwoFactorModal.tsx
> +  const [twoFactorLostAccess, setTwoFactorLostAccess] = useState(false);
🟡 **Stale state when dialog closes via overlay/Cancel.** `twoFactorLostAccess`, `errorMessage`, and the form field values are reset only inside the success path (lines 60-61). The Cancel button calls only `onCancel()` with no reset, and `onOpenChange` (X/Escape/overlay) performs no reset at all. Reopening the modal after clicking 'Lost access' and entering a wrong code shows the stale BackupCode input and the prior error message. Add a `useEffect` keyed on `open` going false that calls `resetForm()` and `setTwoFactorLostAccess(false)`.

2026-08-15 08:30 UTC, ron-x5labs commented on apps/web/pages/auth/login.tsx
> +              {twoFactorRequired ? !twoFactorLostAccess ? <TwoFactor center /> : <BackupCode center /> : null}
🟡 **Backup-code validation inert in the login form (silent no-op).** `BackupCode.tsx` sets `required`/`minLength`/`maxLength`, but the login `<form>` uses `noValidate` and the zod schema only validates email+password, so these constraints are disabled. `register("backupCode")` is called with no validation options. An empty backup code submits → next-auth treats it as falsy → routes to the TOTP branch → throws `SecondFactorRequired` → the handler sets `twoFactorRequired` (already true) with no error message. The user clicks Submit and nothing happens. Add a `backupCode` validation rule (zod or `register` options) and surface an error, or set an explicit `errorMessage` when the submit falls through while `twoFactorLostAccess` is true.

2026-08-15 08:30 UTC, ron-x5labs commented on apps/web/playwright/login.2fa.e2e.ts
> +      // backup codes are now showing, so run a few tests
🟡 **Test coverage gap — security-critical paths untested.** The test exercises only the backup-code UI buttons (download filename, copy toast, close) with TODOs to check file/clipboard content. There is **no test** for the backup-code login flow, the backup-code disable-2FA flow, or verification that a consumed backup code cannot be reused (replay prevention). Given single-use is the stated security contract (locale: 'Each backup code can be used exactly once...'), at minimum the replay-prevention path should be covered. The `TODO: add more backup code tests` at line 12 acknowledges this.

2026-08-15 08:30 UTC, ron-x5labs commented on apps/web/components/auth/BackupCode.tsx
> +export default function TwoFactor({ center = true }) {
💡 **Function named `TwoFactor` instead of `BackupCode`** (copy-paste from `TwoFactor.tsx`). Both components export a default function named `TwoFactor`, making React DevTools and stack traces ambiguous. Rename to `BackupCode`.

2026-08-15 08:30 UTC, ron-x5labs commented on packages/features/auth/lib/next-auth-options.ts
> +        backupCodes[index] = null;
💡 **Consumed codes set to `null` rather than removed; exhausted state unclear.** After all 10 codes are consumed, the stored array is `[null, null, ..., null]` — which decrypts and parses fine, so `indexOf` returns -1 and the user gets `IncorrectBackupCode` ('Backup code is incorrect') rather than a meaningful 'no codes remaining' message. Consider setting `backupCodes` to `null` in the DB when no non-null entries remain, so `MissingBackupCodes` correctly fires and stale encrypted data isn't retained.

2026-08-21 20:44 UTC, ron-x5labs requested changes
## Code Review: feat: 2fa backup codes

### Problem
This PR adds 2FA backup codes to Cal.com, addressing issue #9910. Users generate 10 single-use backup codes during 2FA setup, use one to log in when they lose access to their authenticator, or use one to disable 2FA. This is a critical security feature — backup codes are the recovery path when the primary second factor (TOTP) is unavailable.

### Solution Reviewed
The PR adds: (1) a `backupCodes` TEXT column to the User model (encrypted via `symmetricEncrypt`), (2) code generation in `setup.ts` using `crypto.randomBytes(5).toString("hex")`, (3) a backup-code login path in `next-auth-options.ts` authorize (decrypt → indexOf → null consumed code → re-encrypt), (4) a backup-code disable path in `disable.ts`, (5) UI components (`BackupCode.tsx`, `DisplayBackupCodes` step in `EnableTwoFactorModal`, lost-access toggle in `login.tsx` and `DisableTwoFactorModal`), and (6) new error codes + locale strings.

### Summary
The feature is well-structured and addresses a real gap in 2FA recovery. However, there is one **blocking security vulnerability**: the backup-code login path can be reached without password verification, allowing an attacker with a stolen backup code to authenticate without knowing the user's password. Several non-blocking issues (TOCTOU race on code consumption, case-sensitive comparison, unguarded JSON.parse, reversible encryption of backup codes) also need attention before merge.

### Files Reviewed
- `packages/features/auth/lib/next-auth-options.ts` — deeply reviewed (auth bypass, TOCTOU, case sensitivity, JSON.parse)
- `apps/web/pages/api/auth/two-factor/totp/setup.ts` — deeply reviewed (code generation, reversible encryption)
- `apps/web/pages/api/auth/two-factor/totp/disable.ts` — deeply reviewed (same JSON.parse/case-sensitivity patterns as login)
- `apps/web/components/settings/EnableTwoFactorModal.tsx` — deeply reviewed (object URL lifecycle, state reset)
- `apps/web/components/auth/BackupCode.tsx` — deeply reviewed (input constraints, placeholder)
- `apps/web/pages/auth/login.tsx` — deeply reviewed (2FA flow, lost-access toggle)
- `apps/web/components/settings/DisableTwoFactorModal.tsx` — lightly reviewed (mirrors login patterns)
- `apps/web/playwright/login.2fa.e2e.ts` — lightly reviewed (test coverage gaps; vacuous `isChecked()` assertion noted with FIXME by author)
- `packages/prisma/schema.prisma` — lightly reviewed (nullable column, appropriate)
- `packages/prisma/migrations/20230804153419_add_backup_codes/migration.sql` — lightly reviewed (safe ALTER TABLE)
- `packages/features/auth/lib/ErrorCode.ts` — lightly reviewed (new error codes wired correctly)
- `apps/web/public/static/locales/en/common.json` — lightly reviewed (7 new keys, English fallback expected per Crowdin workflow)
- `packages/lib/test/builder.ts` — lightly reviewed (backupCodes: null default in test builder)

### Verification
- Typecheck/lint — skipped: monorepo-scale build too expensive for review; findings verified by direct code reading and cross-referencing diff hunks against worktree source
- Auth-bypass trace — manually verified: line 121 (`if (user.password && !credentials.totpCode)`) skips password check when `totpCode` is non-empty; line 131 backup-code branch is reachable without password verification; confirmed attacker can authenticate with stolen backup code + dummy totpCode, no password needed
- All inline comment line numbers — verified against worktree source

### Issues Found

#### 🔴 Blocking
- **next-auth-options.ts:131** — Auth bypass: backup-code login path skips password verification

#### 🟡 Non-blocking
- **next-auth-options.ts:148** — TOCTOU race: non-atomic backup code consumption breaks single-use guarantee
- **next-auth-options.ts:144** — Case-sensitive comparison rejects valid uppercase hex codes
- **next-auth-options.ts:139** — Unguarded `JSON.parse`/`symmetricDecrypt` crashes on corrupted data
- **setup.ts:68** — Backup codes stored with reversible AES encryption instead of one-way hashing

#### 💡 Suggestions
- Pre-existing 2FA users (backupCodes=NULL after migration) cannot generate codes without disabling+re-enabling 2FA — consider a regenerate-backup-codes endpoint gated by password+TOTP
- Test coverage: backup-code login/disable/consumption/error paths are entirely untested (author's TODO at `login.2fa.e2e.ts:10`); download/copy assertions verify only filename and toast, not actual code content

### Verdict
Recommend changes before merge — the auth-bypass vulnerability is blocking: an attacker with a stolen backup code can authenticate without a password. Fix the password-verification gap first, then address the TOCTOU race and input handling.

<!-- pr-local-code-review:v1 -->

2026-08-21 20:44 UTC, ron-x5labs commented on packages/features/auth/lib/next-auth-options.ts
> +      if (user.twoFactorEnabled && credentials.backupCode) {
🔴 **Blocking: Auth bypass — password verification skipped**

The password check at line 121 (`if (user.password && !credentials.totpCode)`) only runs when `totpCode` is **empty**. This new backup-code branch (line 131) is reachable when `totpCode` is any non-empty string — but it never validates that `totpCode` is a real TOTP code or that the password was checked.

An attacker with a stolen backup code can authenticate **without knowing the password** by sending `totpCode="x"` (any non-empty dummy) + `backupCode=stolen_code`:

1. Line 121: `!credentials.totpCode` is false → password check **skipped**
2. Line 131: `user.twoFactorEnabled && credentials.backupCode` → enters backup-code branch
3. Line 144: stolen code found via `indexOf` → authenticated

The normal UI flow is safe (clicking "Lost access" sets `totpCode=""` at `login.tsx:125`, so the password IS checked), but the credentials provider endpoint is a public API — any direct POST to `/api/auth/callback/credentials` with these fields bypasses the password.

**Fix:** Always verify the password before the 2FA factor check, regardless of `totpCode`:

```ts
// Always verify password first (remove the !credentials.totpCode condition)
if (user.password) {
  const isCorrectPassword = await verifyPassword(credentials.password, user.password);
  if (!isCorrectPassword) {
    throw new Error(ErrorCode.IncorrectEmailPassword);
  }
}
```

Then check the 2FA factor (TOTP or backup code) as an additional step.

2026-08-21 20:44 UTC, ron-x5labs commented on packages/features/auth/lib/next-auth-options.ts
> +        backupCodes[index] = null;
**TOCTOU race: non-atomic backup code consumption**

The backup-code consumption is a read-modify-write with no transaction or row lock: `findUnique` (line 73) → decrypt → `indexOf` → `backupCodes[index] = null` → `prisma.user.update` (line 149). Two concurrent requests submitting the **same** backup code both read the pre-mutation array, both find the code at `indexOf`, and both succeed — defeating the single-use guarantee.

Impact is bounded (the attacker already possesses a valid code), but the one-time-use contract ("Each backup code can be used exactly once") is a security boundary that should hold.

**Fix:** Wrap in a Prisma interactive transaction with `SELECT ... FOR UPDATE`:

```ts
await prisma.$transaction(async (tx) => {
  const [row] = await tx.$queryRaw`SELECT "backupCodes" FROM "users" WHERE id = ${user.id} FOR UPDATE`;
  if (!row?.backupCodes) throw new Error(ErrorCode.MissingBackupCodes);
  const codes = JSON.parse(symmetricDecrypt(row.backupCodes, process.env.CALENDSO_ENCRYPTION_KEY!));
  const idx = codes.indexOf(credentials.backupCode.replaceAll("-", ""));
  if (idx === -1) throw new Error(ErrorCode.IncorrectBackupCode);
  codes[idx] = null;
  await tx.user.update({ where: { id: user.id }, data: { backupCodes: symmetricEncrypt(JSON.stringify(codes), process.env.CALENDSO_ENCRYPTION_KEY!) } });
});
```

2026-08-21 20:44 UTC, ron-x5labs commented on packages/features/auth/lib/next-auth-options.ts
> +        const index = backupCodes.indexOf(credentials.backupCode.replaceAll("-", ""));
**Case-sensitive comparison rejects valid uppercase hex**

Codes are lowercase (`crypto.randomBytes(5).toString("hex")` → `[0-9a-f]`), but `credentials.backupCode.replaceAll("-", "")` is **not** lowercased before `indexOf`. The `BackupCode.tsx` placeholder `"XXXXX-XXXXX"` visually invites uppercase input. A user who hand-types a code in uppercase is rejected with `IncorrectBackupCode` even though the code is valid.

The same issue exists in `disable.ts:61`.

**Fix:** Normalize input before comparison:

```ts
const index = backupCodes.indexOf(credentials.backupCode.replaceAll("-", "").toLowerCase());
```

2026-08-21 20:44 UTC, ron-x5labs commented on packages/features/auth/lib/next-auth-options.ts
> +        const backupCodes = JSON.parse(
**Unguarded `JSON.parse`/`symmetricDecrypt` crashes on corrupted data**

`JSON.parse(symmetricDecrypt(user.backupCodes, ...))` has no try/catch or `Array.isArray` guard. If the encrypted blob is corrupted, the encryption key was rotated, or a future writer stores non-array JSON, this throws uncaught — crashing the authorize function with an internal server error instead of a clean `IncorrectBackupCode`.

The same pattern exists in `disable.ts:58`.

**Fix:**

```ts
let backupCodes: string[];
try {
  const decrypted = symmetricDecrypt(user.backupCodes, process.env.CALENDSO_ENCRYPTION_KEY);
  backupCodes = JSON.parse(decrypted);
} catch {
  throw new Error(ErrorCode.InternalServerError);
}
if (!Array.isArray(backupCodes)) throw new Error(ErrorCode.IncorrectBackupCode);
```

2026-08-21 20:44 UTC, ron-x5labs commented on apps/web/pages/api/auth/two-factor/totp/setup.ts
> +      backupCodes: symmetricEncrypt(JSON.stringify(backupCodes), process.env.CALENDSO_ENCRYPTION_KEY),
**Backup codes stored with reversible encryption instead of one-way hashing**

Backup codes are stored via `symmetricEncrypt` (AES-256-CBC), meaning a database leak combined with `CALENDSO_ENCRYPTION_KEY` exposure reveals all unused backup codes in plaintext. The same key also protects all TOTP secrets, so a single key compromise is catastrophic.

Unlike TOTP secrets (which the server must decrypt to generate expected codes), backup codes only need **verification** — the server never uses them after generation. One-way hashing (bcrypt/argon2) would eliminate the key-exposure risk: a DB leak alone would not reveal usable codes.

**Fix:** Hash each code individually before storing, then verify by hashing the submitted code and comparing:

```ts
import { hash, compare } from "bcryptjs";

// at generation (setup.ts):
const backupCodes = Array.from(Array(10), () => crypto.randomBytes(5).toString("hex"));
const hashedCodes = await Promise.all(backupCodes.map(c => hash(c, 10)));
// store JSON.stringify(hashedCodes) instead of symmetricEncrypt

// at verification (next-auth-options.ts / disable.ts):
const hashedCodes = JSON.parse(user.backupCodes);
const index = (await Promise.all(
  hashedCodes.map(c => c ? compare(submittedCode, c) : Promise.resolve(false))
)).indexOf(true);
```