chore: fix all `@typescript-eslint/no-non-null-assertion` warnings
calcom/cal.com pull request #10635
Opened 2023-08-07 17:25 UTC by gitstart-calcom

Here is the GitStart Ticket for this pull request: [fix-ts-warnings-2](https://developers.gitstart.com/client/calcom/ticket/fix-ts-warnings-2)

- Please mark your PR as "ready for review" when you have completed all requirements.
- Please ensure that your PR is reviewed by at least 2 people after you have completed it.
- Comments for review or requested changes from the upstream client will be notified to you by email and will also show on the [ticket page](https://developers.gitstart.com/client/calcom/ticket/fix-ts-warnings-2).
- After the PR is merged on the upstream, please merge this PR.
- If there exist merge conflicts on your current PR and you have to close the PR instead of merging it, please go to the [ticket page](https://developers.gitstart.com/client/calcom/ticket/fix-ts-warnings-2) to manually finish the task that is related to this PR.

Happy hacking! 🎉

2023-08-11 06:24 UTC, hariombalhara requested changes, later dismissed
Left a comment, apart from that it's good. Thanks @gitstart-calcom

2023-08-11 09:21 UTC, gitstart-calcom commented
Thank you for the review @hariombalhara. PR has been updated, please re-review

2023-08-14 06:35 UTC, PeerRich approved these changes, later dismissed

2023-08-21 09:08 UTC, keithwillcode requested changes
Blocking to get @sean-brydon feedback before merging.

2023-08-21 09:08 UTC, keithwillcode commented on apps/web/components/getting-started/steps-views/SetupAvailability.tsx
> +    { scheduleId: defaultScheduleId ?? undefined },
@sean-brydon Is this what we want? Or should this throw an error if defaultScheduleId is null/undefined?

2023-08-25 11:39 UTC, keithwillcode commented on apps/web/components/getting-started/steps-views/SetupAvailability.tsx
> +    { scheduleId: defaultScheduleId ?? undefined },
Talked to Sean. All good.

2023-08-25 11:39 UTC, keithwillcode approved these changes, later dismissed

2023-08-25 11:42 UTC, keithwillcode approved these changes

2023-08-25 11:56 UTC, merged