Avoid unmounting of Shell on navigation and thus reduces number of paints
calcom/cal.com pull request #10646
Opened 2023-08-08 11:18 UTC by hariombalhara

## What does this PR do?

- Avoid state reset for Shell Sidebar on navigation. See [comparison b/w production and this PR
](https://www.loom.com/share/6b6b58ac11d24942b9a725345e8c4fd5)

Followup:
- Handle Routing Forms Navigation as well without state reset
- Handle sub navigations like /event-types/[id]

## Requirement/Documentation

- If there is a requirement document, please, share it here.
- If there is ab UI/UX design document, please, share it here.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?
- Browse through all the main navigations and see that they are working

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist
- I haven't added tests that prove my fix is effective or that my feature works

2023-08-08 11:20 UTC, hariombalhara commented on apps/web/components/apps/layouts/AppsLayout.tsx
> +    <ShellMain {...rest} actions={actions?.("block")} hideHeadingOnMobile>
Have been using this strategy for Routing Forms navigations. Using `ShellMain` here allows configuring shell on per route basis. `MainLayout` renders `Shell` without main content

2023-08-08 11:26 UTC, hariombalhara commented on packages/features/bookings/layout/BookingLayout.tsx
It was imported in just one route. So, I moved it there itself.

2023-08-08 11:27 UTC, hariombalhara commented on apps/web/pages/event-types/index.tsx
> -        CTA={<CTA data={data} />}>
These properties being specific to this route are now moved to `ShellMain`

2023-08-08 11:29 UTC, hariombalhara commented on apps/web/lib/hooks/usePublicPage.ts
> +  const isPublicPage = ["/[user]", "/booking/", "/cancel", "/reschedule"].find((route) =>
It was causing bookings/upcoming page to be considered public page and thus was removing Intercom Provider from there which was causing the DOM to be reconstructed for entire page.

2023-08-09 22:00 UTC, zomars requested changes
Locally works as expected. nice job @hariombalhara Can we check why e2e is failing?

2023-08-09 22:54 UTC, zomars approved these changes
Tests are passing now!

2023-08-09 22:54 UTC, merged