fix/ Messaging app cateogry not being respected
calcom/cal.com pull request #10653
Opened 2023-08-09 02:56 UTC by joeauyeung

## What does this PR do?

This app fixes bugs caused by the introduction of the "Messaging" app category.
    - On the installed apps page, messaging apps were not being properly rendered in the right category
    - Messaging apps were not being displayed as an option in event type locations

Fixes # (issue)

## Requirement/Documentation

- If there is a requirement document, please, share it here.
- If there is ab UI/UX design document, please, share it here.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

## Mandatory Tasks

- [ ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist

- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

2023-08-09 03:06 UTC, joeauyeung commented on packages/app-store/server.ts
> +          hasSome: [AppCategories.conferencing, AppCategories.video, AppCategories.messaging],
Messaging apps will now be included in location options

2023-08-09 03:06 UTC, joeauyeung commented on packages/types/App.d.ts
> +import type { AppCategories } from "@calcom/prisma/enums";
The AppCategories enum should be our single source of truth for all app categories available. The `variant` property didn't follow this enum.

2023-08-14 13:21 UTC, hariombalhara commented on apps/web/components/apps/AppPage.tsx
> +  categories: AppCategories[];
Making more type safe.

2023-08-14 13:22 UTC, hariombalhara commented on apps/web/pages/apps/installed/[category].tsx
> -  variant?: IntegrationsContainerProps["variant"];
Removed category as well as it wasn't used cc @joeauyeung

2023-08-14 13:24 UTC, hariombalhara commented on packages/app-store/server.ts
> +          hasSome: defaultVideoAppCategories,
Reused `defaultVideoAppCategories` here so that we can change it at one place and it would automatically handle querying and client side filtering.

2023-08-14 13:24 UTC, hariombalhara commented on packages/app-store/server.ts
> +      let groupByCategory =
Changed the variable name to `groupByCategory` to clearly convey the meaning of category here.

2023-08-14 13:25 UTC, hariombalhara commented on packages/app-store/utils.ts
> +  "video",
Added video as well to `defaultVideoAppCategories` for handling legacy name in a consistent manner.

2023-08-14 13:27 UTC, hariombalhara commented on packages/app-store/zapier/pages/setup/index.tsx
> +  const integrations = trpc.viewer.integrations.useQuery({ categories: ["automation"] });
@joeauyeung Have you carefully checked that in every config.json or meta.ts, categories had the variant set in it.

2023-08-14 13:37 UTC, hariombalhara commented
Including [this](https://github.com/calcom/cal.com/pull/10653#discussion_r1293459542) I have one more concern.

`categories` is for showing the categories in UI. It doesn't feel good to me to filter based on that because there can be re-categorization like it happened few months back. We should have a way to freely re-categorize apps in UI quickly without impacting functionality.

Because it's fixing a bug at the moment, the fix is quite simple and I am opening a separate PR for that.

2023-08-28 09:19 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/calcom/cal.com?pullRequest=10653) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/calcom/cal.com?pullRequest=10653) before we can accept your contribution.<br/>**0** out of **3** committers have signed the CLA.<br/><br/>:x: joeauyeung<br/>:x: hariombalhara<br/>:x: zomars<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/calcom/cal.com?pullRequest=10653) it.</sub>

2023-08-29 12:59 UTC, alannnc approved these changes

2023-08-31 18:35 UTC, PeerRich approved these changes

2023-08-31 20:16 UTC, PeerRich commented
not sure why type check failing @joeauyeung

2023-09-04 05:27 UTC, hariombalhara requested changes
Blocking merge to get some clarity on the purpose of the PR as the bug described here was already fixed with https://github.com/calcom/cal.com/pull/10741(based on this PR only). 

I am in discussion with @joeauyeung.

Also, removing the high priority label now as it's not fixing a high priority bug anymore. Please add it back if that's not the case.

2023-09-15 11:14 UTC, hariombalhara commented
Closing this in favour of https://github.com/calcom/cal.com/pull/11167 which fixes it in an acceptable way for now.

2023-09-15 11:14 UTC, closed without merging