fix: include orgs slug in getUserByUsername just like [user]/[type] page
calcom/cal.com pull request #10723
Opened 2023-08-11 20:05 UTC by alannnc

## What does this PR do?

Fixes # (issue)

## Requirement/Documentation

- If there is a requirement document, please, share it here.
- If there is ab UI/UX design document, please, share it here.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

- Are there environment variables that should be set?
- What are the minimal test data to have?
- What is expected (happy path) to have (input and output)?
- Any other important info that could help to test that PR

## Mandatory Tasks

- [ ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist

- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my PR needs changes to the documentation
- I haven't checked if my changes generate no new warnings
- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

2023-08-11 20:19 UTC, alannnc commented on packages/trpc/server/routers/viewer/slots/util.ts
> +  const orgDetails = orgDomainConfig(ctx.req.headers.host ?? "");
Getting org slug from contex just as we do on booking pages.

2023-08-11 20:20 UTC, alannnc commented on packages/trpc/server/routers/viewer/slots/util.ts
> +      organization: isValidOrgDomain && currentOrgDomain ? getSlugOrRequestedSlug(currentOrgDomain) : null,
This was required if an org user have the same username with another one without org.

2023-08-11 20:29 UTC, zomars commented
We got a type error 
<img width="717" alt="image" src="https://github.com/calcom/cal.com/assets/3504472/62bb1b74-d744-4a6f-8219-ef62b6142387">

2023-08-11 23:42 UTC, zomars requested changes
Let's fix the types first 🙏🏽

2023-08-15 20:57 UTC, alannnc commented
@zomars No more type erros on this :)

2023-08-23 06:59 UTC, Udit-takkar requested changes, later dismissed
Getting 404 on getSchedule

If a user creates a team "engineering" and another user has a team name "engineering" but in his organisation then i get 404 on getSchedule when i go the booking page.

<img width="1438" alt="Screenshot 2023-08-23 at 12 27 22 PM" src="https://github.com/calcom/cal.com/assets/53316345/06839816-8e6d-4bb4-b451-69755ba1442b">

2023-08-24 19:06 UTC, alannnc commented
> Getting 404 on getSchedule
> 
> If a user creates a team "engineering" and another user has a team name "engineering" but in his organisation then i get 404 on getSchedule when i go the booking page.
> 
> <img alt="Screenshot 2023-08-23 at 12 27 22 PM" width="1438" src="https://user-images.githubusercontent.com/53316345/262581562-06839816-8e6d-4bb4-b451-69755ba1442b.png">

Nice find @Udit-takkar, it was a different bug from what I was solving but related as I applied the same logic to solve team names collition.

2023-08-24 23:40 UTC, zomars approved these changes
![LGTM](https://media3.giphy.com/media/NytMLKyiaIh6VH9SPm/200.gif)

2023-08-24 23:41 UTC, merged