feat: sorting for workflow and routing forms
calcom/cal.com pull request #10780
Opened 2023-08-15 17:26 UTC by neo773

## What does this PR do?
This PR adds ability to sort Routing Forms & Workflows

https://github.com/calcom/cal.com/assets/62795688/9371a29a-1e98-4fcc-92f9-be1f5fc0a1b4

/claim #10753 
Fixes #10753
P.S This was quite a bit work, would appreciate if you could up the bounty a bit (if possible)

## Type of change

- [x] New feature (non-breaking change which adds functionality)

2023-08-21 09:12 UTC, Udit-takkar commented on packages/app-store/routing-forms/pages/forms/[...appPages].tsx
> +    })!;
lint is failing here

2023-08-21 11:24 UTC, Udit-takkar commented on packages/app-store/routing-forms/pages/forms/[...appPages].tsx
> +                                className="bg-default text-muted hover:text-emphasis border-default hover:border-emphasis invisible absolute left-[5px] -ml-4 -mt-4 mb-4 hidden h-6 w-6 scale-0 items-c
can we create a common component for these Arrow Up and Arrow Down button ? It's used in /event-types, routing forms and workflow

2023-08-21 11:26 UTC, Udit-takkar reviewed
You need to add animation like /event-types in both of the pages

https://github.com/calcom/cal.com/assets/53316345/4cc3f7b2-76ec-4766-9798-8c0430805a36

2023-08-21 11:41 UTC, Udit-takkar commented on packages/trpc/server/routers/loggedInViewer/routingFormOrder.handler.ts
> +  const where = getPrismaWhereFromFilters(user, undefined);
you are always passing undefined so why not just use prismaQueries.all in where 

```
{
      OR: [
        {
          userId: user.id,
        },
        {
          team: {
            members: {
              some: {
                userId: user.id,
                accepted: true,
              },
            },
          },
        },
      ],
    }
```
i don't you need getPrismaWhereFromFilters function if you always passing undefined

2023-08-26 13:43 UTC, neo773 commented
@Udit-takkar I've made all the changes you requested can you review it?

2023-08-28 09:18 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/calcom/cal.com?pullRequest=10780) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/calcom/cal.com?pullRequest=10780) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/calcom/cal.com?pullRequest=10780) it.</sub>

2023-08-28 09:22 UTC, neo773 commented
> 

I agree

2023-08-28 09:23 UTC, Udit-takkar commented
@neo773 open this  https://cla-assistant.io/calcom/cal.com?pullRequest=10780  and "sign in with github to agree"

2023-08-28 09:23 UTC, neo773 commented
@Udit-takkar Signed!

2023-08-28 12:46 UTC, Udit-takkar requested changes
<img width="489" alt="Screenshot 2023-08-28 at 6 14 17 PM" src="https://github.com/calcom/cal.com/assets/53316345/1966df11-019b-4584-92dc-02c8eb1c99ea">

the position of arrows in /workflows. Everything else works fine  🙏

2023-08-28 12:47 UTC, neo773 commented
> <img width="489" alt="Screenshot 2023-08-28 at 6 14 17 PM" src="https://github.com/calcom/cal.com/assets/53316345/1966df11-019b-4584-92dc-02c8eb1c99ea">
> 
> 
> 
> the position of arrows in /workflows. Everything else works fine  🙏

Will look into it

2023-08-31 18:05 UTC, Udit-takkar commented
@neo773 can you think of some other way to fix this ? !static seems very hacky solution

2023-08-31 18:09 UTC, neo773 commented
@Udit-takkar 
`useAutoAnimate` overrides it at runtime and this what `event-types` also currently does

<img width="1133" alt="image" src="https://github.com/calcom/cal.com/assets/62795688/f92fe39a-b5a3-4cbc-94c8-b147be78807f">

2023-08-31 18:13 UTC, Udit-takkar approved these changes
@neo773  LGTM. Great work

2023-08-31 18:57 UTC, merged