test: Create unit tests for react components in packages/ui/components/form/wizard
calcom/cal.com pull request #10785
Opened 2023-08-15 19:00 UTC by gitstart-calcom

## What does this PR do?
 * This PR adds tests to the component `WizardForm` to ensure that it works as expected.
 * To reproduce the tests run the following command: 
 ```
yarn test wizardForm
```
 
 ## Issue References
 * https://github.com/calcom/cal.com/issues/10406
 
 ## Video/Screenshot Demo
 ##### Result:
![image](https://github.com/GitStartHQ/client-cal.com/assets/50892465/cbb5beea-3879-4f7c-bc11-485543a7731a)

___
 
 This code was written and reviewed by GitStart Community. Growing future engineers, one PR at a time.

2023-08-28 09:18 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/calcom/cal.com?pullRequest=10785) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/calcom/cal.com?pullRequest=10785) before we can accept your contribution.<br/>**0** out of **3** committers have signed the CLA.<br/><br/>:x: shivamklr<br/>:x: gitstart-calcom<br/>:x: gitstart<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/calcom/cal.com?pullRequest=10785) it.</sub>

2023-08-28 13:13 UTC, shivamklr requested changes
There are a few instances where getByTestId and toBeInTheDocument() are used together, which imo is not needed. Let me know if you think otherwise.

2023-08-28 13:13 UTC, shivamklr commented on packages/ui/components/form/wizard/wizardForm.test.tsx
> +    expect(queryByText(nextLabel)).toBeInTheDocument();
Isn't this redundant? Queries are the methods that Testing Library gives you to find elements on the page. The assertion 'toBeInTheDocument' does the same thing.

2023-08-28 19:46 UTC, gitstart-calcom commented
Hi @shivamklr we made the requested changes here, please take a look 😄

2023-08-29 17:47 UTC, shivamklr approved these changes
lgtm

2023-08-29 18:14 UTC, merged