chore: add datePicker in storybook (CALCOM-10760)
calcom/cal.com pull request #10784
Opened 2023-08-15 18:43 UTC by gitstart-calcom

Here is the GitStart Ticket for this pull request: [CALCOM-10760](https://developers.gitstart.com/client/calcom/ticket/CALCOM-10760)

- Please mark your PR as "ready for review" when you have completed all requirements.
- Please ensure that your PR is reviewed by at least 2 people after you have completed it.
- Comments for review or requested changes from the upstream client will be notified to you by email and will also show on the [ticket page](https://developers.gitstart.com/client/calcom/ticket/CALCOM-10760).
- After the PR is merged on the upstream, please merge this PR.
- If there exist merge conflicts on your current PR and you have to close the PR instead of merging it, please go to the [ticket page](https://developers.gitstart.com/client/calcom/ticket/CALCOM-10760) to manually finish the task that is related to this PR.

Happy hacking! 🎉

2023-08-16 08:54 UTC, sean-brydon requested changes
Judging with how this component is styled. I believe this is the wrong date picker. 

I did a quick look at refernces and this appears to be dead component that we dont use anywhere

2023-08-16 12:16 UTC, gitstart-calcom commented
Hi @sean-brydon please can you help us to find the correct file?

2023-08-17 14:22 UTC, PeerRich commented
definitely wrong component. should we close this PR and open a new one or do you wanna edit this?

2023-08-17 14:45 UTC, sean-brydon commented
> Hi @sean-brydon please can you help us to find the correct file?

Hi the correct file we use for date picker is located at

cal.com/packages/features/calendars/DatePicker.tsx

2023-08-17 15:19 UTC, gitstart-calcom commented
> definitely wrong component. should we close this PR and open a new one or do you wanna edit this?

We have already updated to the right component in the same PR. We will be pushing the changes shortly

2023-08-21 18:28 UTC, gitstart-calcom commented
Hi @sean-brydon we made the requested changes here, please take a look

2023-08-22 03:14 UTC, gitstart-calcom commented on packages/features/calendars/DatePicker.tsx
> +            active && "invert"
We noticed some style issues and fixed them too. Please checkout the video for more detail
https://www.loom.com/share/ed35d62be2d34f199c2af8796b467cce

2023-08-22 09:27 UTC, sean-brydon approved these changes
Great job :) Thanks for the prompt fixes. Nice spot on the active state too

2023-08-22 09:27 UTC, merged