Fix existing typos, add `cspell` in pre-commit to avoid future typos
calcom/cal.com pull request #10840
Opened 2023-08-18 14:36 UTC by kavinkuma6

## What does this PR do?

Current version of the code have typos which counts to around 120 unique word. I feel a well maintained project should not have typos. So, I have fixed them. 

Also to void future typos, I have added a config setup in pre-commit hook using the [cspell](https://www.npmjs.com/package/cspell) package. This will prevent users from committing code with unintentional mis spellings. 

Created a [file](https://github.com/kavinkuma6/cal.com/blob/add-cspell-pre-commit-to-fix-typos/.cspell/projectWords.txt), which contains the project specific words or words not found dictionary. This can be used by the package. In future, incase if the user wants to add a non dictionary word to the code,  the same should be added here. I have added a terminal instruction for the same [here](https://github.com/kavinkuma6/cal.com/blob/add-cspell-pre-commit-to-fix-typos/.cspell/cspell.sh#L7) which would be shown in pre commit hook.

Incase, if we want to check the spelling for the whole project, unlike only the staged files as mentioned above, we can use the newly added script `npm run spell-check`

## Requirement/Documentation

- If there is a requirement document, please, share it here.
- If there is ab UI/UX design document, please, share it here.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Chore (refactoring code, technical debt, workflow improvements)

## How should this be tested?

- Are there environment variables that should be set? - No
- What are the minimal test data to have? - NA
- What is expected (happy path) to have (input and output)? - NA
- Any other important info that could help to test that PR: I agree we have lot of variable name changes. But we can do most of the testing in the PR review process itself. Then we can use the other test setups to verify the overall workings. 

## Mandatory Tasks

- [ ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

2023-08-18 14:48 UTC, kavinkuma6 commented on apps/web/components/eventtype/EventSetupTab.tsx
>                  <Trans i18nKey="event_type_requres_google_cal">
I dont find `event_type_requres_google_cal` defined anywhere. So ignored cspell temporarily

2023-08-18 16:14 UTC, kavinkuma6 commented on apps/web/public/static/locales/es/common.json
> -  "choose_license_description": "Cal.com viene con una licencia AGPLv3 accesible y gratuita, la cual tiene algunas limitaciones. Esta licencia se puede actualizar a una licencia Empresarial en cualqu
Hope this a typo.

2023-08-18 16:20 UTC, kavinkuma6 commented on packages/features/ee/organizations/pages/settings/profile.tsx
> +      showToast(t("your_organisation_updated_sucessfully"), "success"); // cspell:ignore sucessfully
I dont find the declaration anywhere. So, for safety ignored it.

2023-08-18 16:22 UTC, kavinkuma6 commented on packages/features/ee/support/components/HelpMenuItem.tsx
> +          // cspell:ignore defualt
In some places, this `text-defualt` class is used. Can any one confirm whether it is intentional or bug?

For now, added `ignore` for safety.

2023-08-18 16:24 UTC, kavinkuma6 commented on packages/types/ical.d.ts
> +      options?: { strictExceptions: boolean; exceptions: Array<Component | Event> }
I dont see this prop used. So corrected it. Pls confirm.

2023-08-20 15:34 UTC, zomars commented
Hi @kavinkuma6 Thank you for your contribution 🙏 I love the fact the we're actually fixing typos. I got some questions about the proposed workflow tho. Does this means that a spell check can prevent a commit being made? Doesn't it feels too obtrusive to a regular dev workflow?

2023-08-20 16:24 UTC, kavinkuma6 commented
> Hi @kavinkuma6 Thank you for your contribution 🙏 I love the fact the we're actually fixing typos. I got some questions about the proposed workflow tho. Does this means that a spell check can prevent a commit being made? Doesn't it feels too obtrusive to a regular dev workflow?

@zomars 
 when a commit is being made, it will run the spell check only on the staged files. This will get executed after the current lint check implementation on the staged files. Yes, it will prevent the commit similar to how lint check prevents a commit.

Since it runs only on the staged files, it won't be too obtrusive. Also, it won't take much time than the time taken by the lint check on the staged files. 

This is my input. But you can also run it once and share your feedback.

2023-08-28 09:18 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/calcom/cal.com?pullRequest=10840) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/calcom/cal.com?pullRequest=10840) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/calcom/cal.com?pullRequest=10840) it.</sub>

2023-09-07 17:19 UTC, PeerRich requested changes
imo this PR is quite intruisive, touches a ton of files and I am not sure if we want an automated spell checker at this point

2023-10-18 00:16 UTC, closed without merging