chore: add Navigation in storybook (CALCOM-10760)
calcom/cal.com pull request #10867
Opened 2023-08-21 15:28 UTC by gitstart-calcom

## Demo
https://www.loom.com/share/7ce9b388d5af471180f2a3f409997614

2023-08-28 09:17 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/calcom/cal.com?pullRequest=10867) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/calcom/cal.com?pullRequest=10867) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: gitstart<br/>:x: gitstart-calcom<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/calcom/cal.com?pullRequest=10867) it.</sub>

2023-09-18 18:26 UTC, Udit-takkar commented on packages/ui/components/navigation/tabs/__stories__/horizontalTabs.stories.mdx
> +        },
same as https://github.com/calcom/cal.com/pull/10867/files#r1329125194

2023-09-18 18:31 UTC, Udit-takkar requested changes, later dismissed
Can we remove these from horizontal and vertical tabs?

<img width="414" alt="Screenshot 2023-09-18 at 11 58 15 PM" src="https://github.com/calcom/cal.com/assets/53316345/888a32f3-121b-4c5e-86dd-90dd34ab84e1">

2023-09-19 03:29 UTC, gitstart-calcom commented
We made the changes, please take a look @Udit-takkar

2023-10-05 14:53 UTC, keithwillcode commented
<img width="356" alt="Screen Shot 2023-10-05 at 11 52 29 AM" src="https://github.com/calcom/cal.com/assets/2538462/debe180b-357a-4f30-9760-a1917be42e0f">

Seeing this. Know why, @gitstart-calcom?

2023-10-05 14:53 UTC, keithwillcode requested changes, later dismissed
<img width="356" alt="Screen Shot 2023-10-05 at 11 52 29 AM" src="https://github.com/calcom/cal.com/assets/2538462/debe180b-357a-4f30-9760-a1917be42e0f">

Seeing this. Know why, @gitstart-calcom?

2023-10-05 15:02 UTC, gitstart-calcom commented
@keithwillcode That's weird, we will look into that and provide a fix now

2023-10-05 18:30 UTC, gitstart-calcom commented
@keithwillcode We noticed this is happening in all files, can we create a ticket to fix that?
<img width="651" alt="image" src="https://github.com/calcom/cal.com/assets/121884634/c1e14818-e5ee-40d0-aa93-32f34b9e821d">

2023-10-09 08:38 UTC, PeerRich approved these changes

2023-10-09 08:45 UTC, merged