chore: add Dropdown in storybook (CALCOM-10760)
calcom/cal.com pull request #10874
Opened 2023-08-21 23:41 UTC by gitstart-calcom

Here is the GitStart Ticket for this pull request: [CALCOM-10760](https://developers.gitstart.com/client/calcom/ticket/CALCOM-10760)

- Please mark your PR as "ready for review" when you have completed all requirements.
- Please ensure that your PR is reviewed by at least 2 people after you have completed it.
- Comments for review or requested changes from the upstream client will be notified to you by email and will also show on the [ticket page](https://developers.gitstart.com/client/calcom/ticket/CALCOM-10760).
- After the PR is merged on the upstream, please merge this PR.
- If there exist merge conflicts on your current PR and you have to close the PR instead of merging it, please go to the [ticket page](https://developers.gitstart.com/client/calcom/ticket/CALCOM-10760) to manually finish the task that is related to this PR.

Happy hacking! 🎉

### Loom
https://www.loom.com/share/a33f7e06fcd34a4b9813b617f127c000?sid=b68bde67-ee50-42d9-9ae0-57fa1001dfd5

2023-08-23 08:12 UTC, Udit-takkar requested changes, later dismissed
@gitstart-calcom this is not how we implement and use dropdown.


you can check  here

<img width="247" alt="Screenshot 2023-08-23 at 1 39 31 PM" src="https://github.com/calcom/cal.com/assets/53316345/56f6d199-a530-4d39-a3d8-7fd133efaa76">

https://github.com/calcom/cal.com/blob/376f023e0fd69c0f30569152785b56c277a32bc8/apps/web/components/eventtype/EventTypeSingleLayout.tsx#L337

2023-08-23 08:25 UTC, sean-brydon commented
> @gitstart-calcom this is not how we implement and use dropdown.
> 
> you can check here
> 
> <img alt="Screenshot 2023-08-23 at 1 39 31 PM" width="247" src="https://user-images.githubusercontent.com/53316345/262601243-56f6d199-a530-4d39-a3d8-7fd133efaa76.png">
> https://github.com/calcom/cal.com/blob/376f023e0fd69c0f30569152785b56c277a32bc8/apps/web/components/eventtype/EventTypeSingleLayout.tsx#L337

Damn we really need to cleanup these old components :D

2023-08-28 09:17 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/calcom/cal.com?pullRequest=10874) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/calcom/cal.com?pullRequest=10874) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/calcom/cal.com?pullRequest=10874) it.</sub>

2023-08-29 22:49 UTC, gitstart-calcom commented
Hi @Udit-takkar we made the requested changes here please take a look 😄

2023-09-01 08:59 UTC, Udit-takkar commented on packages/ui/components/form/dropdown/dropdown.stories.mdx
> +#### DropdownMenuSeparator
also mention DropdownItem here

2023-09-01 08:59 UTC, Udit-takkar reviewed
LGTM. Left one comment

2023-09-01 15:25 UTC, gitstart-calcom commented
@Udit-takkar We made the changes here please take a look 😄

2023-09-01 16:08 UTC, PeerRich approved these changes

2023-09-01 16:08 UTC, merged