chore: expect emails e2e
calcom/cal.com pull request #10881
Opened 2023-08-22 11:12 UTC by shivamklr

## What does this PR do?

Fixes #10855 
- Made emails fixture optional
- Add env variable to enable mailhog checks
- Refactor code

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Chore (refactoring code, technical debt, workflow improvements)

## How should this be tested?

- Case 1:
    - Set env `E2E_TEST_MAILHOG_ENABLED="1"`
    - Run mailhog container
    - Run e2e tests
- Case 2:
    -  Set env `E2E_TEST_MAILHOG_ENABLED=`
    - Run e2e tests

## Mandatory Tasks

- [ ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

2023-08-22 11:23 UTC, shivamklr reviewed
Self Review

2023-08-22 11:23 UTC, shivamklr commented on .env.example
> -# This is used so we can bypass emails in auth flows for E2E testing
No longer bypasses emails

2023-08-22 11:23 UTC, shivamklr commented on apps/web/playwright/lib/fixtures.ts
> +    }
Optional fixture

2023-08-22 12:45 UTC, keithwillcode requested changes
Nice work! Just one little change I saw to make

2023-08-22 12:45 UTC, keithwillcode commented on .env.example
> +# If you need to run email tests with mailhog locally,
This comment is out of place now that the value is on line 180

2023-08-22 12:59 UTC, nicktrn commented
@shivamklr @keithwillcode @zomars 

Not not downplay the effort that has been put into the current email testing framework, but I think the real issue is that an external (unmaintained) third party app is required for successful test runs.

I don't think adding more complexity / env vars, and conditionally disabling email tests is a workable solution.

What happens if a test relies on information from emails to continue, e.g. clicking the CTA link?

With mailhog, the workarounds already start when trying to disable authentication for local testing. Its REST API is rather limited - you will run into more issues requiring unsightly workarounds here too. Extending the API requires patches in Go for the server itself, in addition to patching the JS package used here.

You could have a look at #10560 for an alternative in pure JS. The [SMTP server](https://nodemailer.com/extras/smtp-server/) is automatically started by Playwright, following the same pattern used for Next.

I may be completely off-track but I think it's much more maintainable and extensible. It should also solve other problems that will show up on the current path.

(Haven't rebased recently as I would have to rollback most of the mailhog-related changes.)

2023-08-22 13:25 UTC, keithwillcode commented
> @shivamklr @keithwillcode @zomars
> 
> Not not downplay the effort that has been put into the current email testing framework, but I think the real issue is that an external (unmaintained) third party app is required for successful test runs.
> 
> I don't think adding more complexity / env vars, and conditionally disabling email tests is a workable solution.
> 
> What happens if a test relies on information from emails to continue, e.g. clicking the CTA link?
> 
> With mailhog, the workarounds already start when trying to disable authentication for local testing. Its REST API is rather limited - you will run into more issues requiring unsightly workarounds here too. Extending the API requires patches in Go for the server itself, in addition to patching the JS package used here.
> 
> You could have a look at #10560 for an alternative in pure JS. The [SMTP server](https://nodemailer.com/extras/smtp-server/) is automatically started by Playwright, following the same pattern used for Next.
> 
> I may be completely off-track but I think it's much more maintainable and extensible. It should also solve other problems that will show up on the current path.
> 
> (Haven't rebased recently as I would have to rollback most of the mailhog-related changes.)

Hey @nicktrn, appreciate your comment here and the work you put into #10560. At the moment, we aren't going to take on maintaining something built from scratch with the complexity as in #10560. It's a very cool and clever solution, but will be more work to maintain moving forward.

2023-08-22 13:34 UTC, keithwillcode approved these changes, later dismissed

2023-08-22 14:52 UTC, zomars submitted a review, later dismissed
Lovely!

2023-08-22 16:11 UTC, nicktrn commented
@keithwillcode thanks for having a look and the positive feedback. I certainly understand your point re complexity. It's sad there are no well-established solutions out there yet, bar some online services that come with their own issues. Will let you all get on with the current email strategy. Any major roadblocks, just give me a ping.

2023-08-23 09:08 UTC, keithwillcode approved these changes

2023-08-23 09:08 UTC, merged