fix: handle collective multiple host on destinationCalendar
calcom/cal.com pull request #10967
Opened 2023-08-25 21:08 UTC by alannnc

## What does this PR do?

Fixes # (issue)

## Requirement/Documentation

- If there is a requirement document, please, share it here.
- If there is ab UI/UX design document, please, share it here.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

- Are there environment variables that should be set?
- What are the minimal test data to have?
- What is expected (happy path) to have (input and output)?
- Any other important info that could help to test that PR

## Mandatory Tasks

- [ ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist

- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my PR needs changes to the documentation
- I haven't checked if my changes generate no new warnings
- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

2023-08-25 21:13 UTC, alannnc commented on packages/core/CalendarManager.ts
> +  externalId?: string
I had a hard time figuring out how to pass externalId here, so I opted for this approach as it worn't interfere with createEvent calls that don't send this new parameter.

2023-08-25 21:14 UTC, alannnc commented on packages/core/CalendarManager.ts
> +    calEvent.additionalNotes = "Notes have been hidden by the organizer"; // TODO: i18n this string?
typo

2023-08-25 21:14 UTC, alannnc commented on packages/core/CalendarManager.ts
> +    externalId,
sending it back

2023-08-25 21:15 UTC, alannnc commented on packages/core/CalendarManager.ts
> +  externalId?: string
Basically here we have 3 types of data eventCalendar, resultEvent and credential and I find that if I added the anchor value on resultEvent it wont have that many side effects in the entire process so it can be passed properly without trouble.

2023-08-25 21:16 UTC, alannnc commented on packages/core/EventManager.ts
> +    if (evt.location === MeetLocationType && mainHostDestinationCalendar.integration !== "google_calendar") {
supporting only 1 item inside event.destinationCalendar.

2023-08-25 21:16 UTC, alannnc commented on packages/core/EventManager.ts
> +        credentialId: isCalendarType ? result.credentialId : undefined,
With the fix on the first file we should have an explicit externalId and credentialId and with these we can stop the guessing game and just grab it from result.externalId.

2023-08-25 21:17 UTC, alannnc commented on packages/core/EventManager.ts
> +        credentialId: result.credentialId ?? undefined,
Same as above.

2023-08-25 21:18 UTC, alannnc commented on packages/core/EventManager.ts
> +    if (event.destinationCalendar && event.destinationCalendar.length > 0) {
Supporting array for event.destinationCalendar. Right now when fetching appCredentials we only use organizer one, now we can fetch any required calendar for every host.

2023-08-25 21:18 UTC, alannnc commented on packages/features/bookings/lib/handleNewBooking.ts
> +  const originalBookingDuration = input.originalRescheduledBooking
typo

2023-08-25 21:18 UTC, alannnc commented on packages/features/bookings/lib/handleNewBooking.ts
> +        duration: originalBookingDuration,
typo

2023-08-25 21:19 UTC, alannnc commented on packages/features/bookings/lib/handleNewBooking.ts
> +    !!eventType.schedulingType && ["COLLECTIVE", "ROUND_ROBIN"].includes(eventType.schedulingType);
little improvement

2023-08-25 21:19 UTC, alannnc commented on packages/features/bookings/lib/handleNewBooking.ts
> +      throw new HttpError({ statusCode: 500, message: "Unable to load users" });
improve readability

2023-08-25 21:20 UTC, alannnc commented on packages/features/bookings/lib/handleNewBooking.ts
> +  });
improve readability and types

2023-08-25 21:20 UTC, alannnc commented on packages/features/bookings/lib/handleNewBooking.ts
> +      : null,
updating so it now handles destinationCalendar as array further down

2023-08-25 21:21 UTC, alannnc commented on packages/features/bookings/lib/handleNewBooking.ts
> +          : undefined,
Here we connected booking with the main host destinationCalendarId.

2023-08-28 09:15 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/calcom/cal.com?pullRequest=10967) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/calcom/cal.com?pullRequest=10967) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/calcom/cal.com?pullRequest=10967) it.</sub>

2023-08-30 20:21 UTC, zomars reviewed
Codewise LGTM. Can we get a demo/loom before merging? Can we verify that the the attendees are showing properly on gCal?

2023-08-31 17:46 UTC, zomars approved these changes
LGTM. Let's test one more time in staging cc @shivamklr 🙏🏽 

Nice work @alannnc

2023-08-31 17:47 UTC, merged

2023-09-10 14:00 UTC, leog commented on packages/trpc/server/routers/viewer/organizations/create.handler.ts
> +            ...(IS_TEAM_BILLING_ENABLED ? { slug } : {}),
@zomars @alannnc note that this unintentional change on the condition ("!" removed) created some unexpected behavior when creating orgs locally as there was no slug registered for new orgs, adding it back in an upcoming PR

2026-04-10 00:44 UTC, mfeuerstein reviewed
## PR Review — approved

Reviewed 22 files. 0 high-severity issues found. Verdict: approved.

### `packages/core/builders/CalendarEvent/builder.ts` (low)

- Reviewed packages/core/builders/CalendarEvent/builder.ts — looks good

### `packages/app-store/office365calendar/lib/CalendarService.ts` (low)

- Reviewed packages/app-store/office365calendar/lib/CalendarService.ts — looks good

### `packages/app-store/larkcalendar/lib/CalendarService.ts` (low)

- Reviewed packages/app-store/larkcalendar/lib/CalendarService.ts — looks good

### `apps/web/pages/api/cron/bookingReminder.ts` (low)

- Reviewed apps/web/pages/api/cron/bookingReminder.ts — looks good

### `packages/app-store/googlecalendar/lib/CalendarService.ts` (low)

- Reviewed packages/app-store/googlecalendar/lib/CalendarService.ts — looks good

### `packages/core/CalendarManager.ts` (medium)

- Reviewed packages/core/CalendarManager.ts — looks good

### `apps/web/playwright/webhook.e2e.ts` (low)

- Reviewed apps/web/playwright/webhook.e2e.ts — looks good

### `packages/emails/src/templates/BrokenIntegrationEmail.tsx` (low)

- Reviewed packages/emails/src/templates/BrokenIntegrationEmail.tsx — looks good

### `packages/features/bookings/lib/handleCancelBooking.ts` (low)

- Reviewed packages/features/bookings/lib/handleCancelBooking.ts — looks good

### `packages/core/builders/CalendarEvent/class.ts` (low)

- Reviewed packages/core/builders/CalendarEvent/class.ts — looks good

### `packages/features/ee/payments/api/webhook.ts` (low)

- Reviewed packages/features/ee/payments/api/webhook.ts — looks good

### `packages/lib/CalendarService.ts` (low)

- Reviewed packages/lib/CalendarService.ts — looks good

### `packages/trpc/server/routers/viewer/bookings/editLocation.handler.ts` (low)

- Reviewed packages/trpc/server/routers/viewer/bookings/editLocation.handler.ts — looks good

### `packages/trpc/server/routers/loggedInViewer/deleteCredential.handler.ts` (low)

- Reviewed packages/trpc/server/routers/loggedInViewer/deleteCredential.handler.ts — looks good

### `packages/core/EventManager.ts` (low)

- Reviewed packages/core/EventManager.ts — looks good

### `packages/trpc/server/routers/viewer/bookings/confirm.handler.ts` (low)

- Reviewed packages/trpc/server/routers/viewer/bookings/confirm.handler.ts — looks good

### `packages/features/ee/payments/api/paypal-webhook.ts` (low)

- Reviewed packages/features/ee/payments/api/paypal-webhook.ts — looks good

### `packages/features/bookings/lib/handleNewBooking.ts` (low)

- Reviewed packages/features/bookings/lib/handleNewBooking.ts — looks good

### `packages/trpc/server/routers/viewer/bookings/requestReschedule.handler.ts` (medium)

- Reviewed packages/trpc/server/routers/viewer/bookings/requestReschedule.handler.ts — looks good

### `packages/trpc/server/routers/viewer/organizations/create.handler.ts` (low)

- Reviewed packages/trpc/server/routers/viewer/organizations/create.handler.ts — looks good

### `packages/types/Calendar.d.ts` (low)

- Reviewed packages/types/Calendar.d.ts — looks good

### `packages/types/EventManager.d.ts` (low)

- Reviewed packages/types/EventManager.d.ts — looks good

2026-08-12 18:29 UTC, ron-x5labs requested changes
## Code Review: Convert `destinationCalendar` to an array

### Problem
Support multiple destination calendars on a `CalendarEvent` so collective/team events can create calendar entries on each host's calendar (fixes #7754).

### Solution Reviewed
`CalendarEvent.destinationCalendar` changes from `DestinationCalendar | null` to `DestinationCalendar[] | null`. Every calendar provider, EventManager (create/update/delete now loop the array), CalendarManager, booking/payment/cron handlers, and types are updated. Google's `createEvent` gains a `credentialId` param to select the matching destination per credential.

### Summary
The core design is sound and the Google path is mostly correct, but there are several blocking bugs: a NullPointerException on the `mainHostDestinationCalendar.integration` access, a self-referencing `.find()` bug in Google `updateEvent`/`deleteEvent` that targets the wrong (or undefined) calendar, a no-op `?.push` that silently drops team members' calendars, and non-Google providers (Office 365, Lark) ignoring the new `credentialId` so they always target `destinationCalendar[0]` (the organizer's) even when processing another host's credential — defeating the PR's goal for those providers.

### Files Reviewed
- `packages/core/EventManager.ts` — deeply reviewed
- `packages/core/CalendarManager.ts` — deeply reviewed
- `packages/app-store/googlecalendar/lib/CalendarService.ts` — deeply reviewed
- `packages/app-store/office365calendar/lib/CalendarService.ts` — deeply reviewed
- `packages/app-store/larkcalendar/lib/CalendarService.ts` — deeply reviewed
- `packages/lib/CalendarService.ts` (BaseCalendarService/iCal) — deeply reviewed
- `packages/features/bookings/lib/handleNewBooking.ts` — deeply reviewed
- `packages/features/bookings/lib/handleCancelBooking.ts` — deeply reviewed
- `packages/features/ee/payments/api/paypal-webhook.ts` — lightly reviewed (mechanical array wrap)
- `packages/features/ee/payments/api/webhook.ts` — lightly reviewed (mechanical array wrap)
- `packages/trpc/server/routers/loggedInViewer/deleteCredential.handler.ts` — lightly reviewed (mechanical array wrap)
- `packages/trpc/server/routers/viewer/bookings/confirm.handler.ts` — lightly reviewed (mechanical array wrap)
- `packages/trpc/server/routers/viewer/bookings/editLocation.handler.ts` — lightly reviewed (mechanical array wrap)
- `packages/trpc/server/routers/viewer/bookings/requestReschedule.handler.ts` — deeply reviewed
- `packages/trpc/server/routers/viewer/organizations/create.handler.ts` — lightly reviewed (unrelated billing refactor; already flagged by @leog)
- `packages/types/Calendar.d.ts`, `packages/types/EventManager.d.ts` — lightly reviewed (type changes)
- `packages/core/builders/CalendarEvent/*` — lightly reviewed (mechanical)
- `packages/emails/src/templates/BrokenIntegrationEmail.tsx` — lightly reviewed
- `apps/web/pages/api/cron/bookingReminder.ts` — lightly reviewed (mechanical array wrap)
- `apps/web/playwright/webhook.e2e.ts` — lightly reviewed (test fixture)

### Verification
- `yarn type-check:ci` — skipped: fresh worktree has no `node_modules`; enum/string-literal and signature claims verified by source inspection instead.

### Issues Found

#### Blocking
- `packages/core/EventManager.ts:119` — `mainHostDestinationCalendar.integration` NPE when `destinationCalendar` is `null`/`[]`.
- `packages/app-store/googlecalendar/lib/CalendarService.ts:255` — `updateEvent` `.find()` predicate is self-referential; `selectedCalendar` is `undefined`.
- `packages/app-store/googlecalendar/lib/CalendarService.ts:316` — `deleteEvent` same `.find()` bug; falls back to `'primary'`, deleting from the wrong calendar.
- `packages/features/bookings/lib/handleNewBooking.ts:1078` — `evt.destinationCalendar?.push(...)` is a no-op when `destinationCalendar` is `null`; team calendars are silently lost.
- `packages/app-store/office365calendar/lib/CalendarService.ts:73` — ignores `credentialId`, always uses `destinationCalendar[0]`; wrong host's calendar in collective flow (Lark same).

#### Non-blocking
- `packages/core/EventManager.ts:344` — N+1 sequential `prisma.credential.findUnique` inside the destination loop (also `:517` and `handleCancelBooking.ts:433`).
- `packages/core/EventManager.ts:344` — `findUnique` uses `include` (repo rule: `select`), loads `credential.key`, no ownership filter, no `invalid` check, silent skip on null.
- `packages/core/EventManager.ts:554` — reschedule merge only deletes the first old calendar reference (`.find` not `.filter`); orphans remaining host events.
- `packages/trpc/server/routers/viewer/bookings/requestReschedule.handler.ts:240` — dropped `user.destinationCalendar` fallback; inconsistent with every sibling handler.
- `packages/features/bookings/lib/handleNewBooking.ts:724` — `loadUsers` try/catch masks programmer errors and maps all `PrismaClientKnownRequestError` codes to 400.
- `packages/core/EventManager.ts:597` — removed `console.error` in the error path; observability loss.

#### Suggestions
- `packages/app-store/googlecalendar/lib/CalendarService.ts:148` — silent fallback to `'primary'` on credentialId mismatch; consider logging a warning.
- `packages/features/bookings/lib/handleNewBooking.ts:993` — use `SchedulingType.COLLECTIVE` enum constant instead of string literal for maintainability.

### Verdict
Recommend changes before merge — the NPE, the Google update/delete calendar-targeting bugs, and the non-Google `credentialId` gap each break core flows the PR intends to enable.

<!-- pr-local-code-review:v1 -->

2026-08-12 18:29 UTC, ron-x5labs commented on packages/core/EventManager.ts
> +    if (evt.location === MeetLocationType && mainHostDestinationCalendar.integration !== "google_calendar") {
🔴 **NPE — missing optional chaining.** `const [mainHostDestinationCalendar] = evt.destinationCalendar ?? []` yields `undefined` when `destinationCalendar` is `null` or `[]` (the `??` only guards `null`/`undefined`, not empty arrays). The next line dereferences `mainHostDestinationCalendar.integration` without `?.`, throwing `TypeError` whenever `evt.location === MeetLocationType` and no destination calendar is configured.

Empty arrays flow here from the payment webhooks, the cron reminder, and `handleNewBooking` (which sets `destinationCalendar: null` when neither the event type nor organizer has one). Every other `mainHostDestinationCalendar` usage in this PR (Google/Lark/O365/BaseCalendarService) correctly uses `?.externalId`. Fix: `mainHostDestinationCalendar?.integration !== "google_calendar"`.

2026-08-12 18:29 UTC, ron-x5labs commented on packages/app-store/googlecalendar/lib/CalendarService.ts
>          ? externalCalendarId
🔴 **Self-referential `.find()` — `selectedCalendar` is always `undefined` here.** In the `else` branch `externalCalendarId` is already falsy, so the predicate `cal.externalId === externalCalendarId` compares against `undefined`/`null` and never matches a real calendar. `selectedCalendar` is `undefined`, and `calendarId: selectedCalendar` (line 261) is passed to `calendar.events.update` with no `|| 'primary'` fallback (unlike `createEvent`). Every Google Calendar update without an explicit `externalCalendarId` will fail.

The old code used `event.destinationCalendar?.externalId` directly. The array equivalent is `event.destinationCalendar?.[0]?.externalId` (or match on `credentialId` as `createEvent` now does).

2026-08-12 18:29 UTC, ron-x5labs commented on packages/app-store/googlecalendar/lib/CalendarService.ts
> +        ? externalCalendarId
🔴 **Same `.find()` bug in `deleteEvent` — deletes from the wrong calendar.** `event.destinationCalendar?.find((cal) => cal.externalId === externalCalendarId)` with a falsy `externalCalendarId` never matches, so `calendarId` is `undefined` and falls through to `defaultCalendarId` (`'primary'`). When a booking has a real destination calendar, the event is deleted from the user's primary calendar instead of the configured destination — silently wrong.

Fix as above: `event.destinationCalendar?.[0]?.externalId` or match on `credentialId`.

2026-08-12 18:29 UTC, ron-x5labs commented on packages/features/bookings/lib/handleNewBooking.ts
> +    evt.destinationCalendar?.push(...teamDestinationCalendars);
🔴 **`?.push` is a no-op when `destinationCalendar` is `null` — team calendars are silently lost.** Five lines above, `destinationCalendar` is set to `null` when both `eventType.destinationCalendar` and `organizerUser.destinationCalendar` are absent. For a collective event where the organizer has no destination calendar but team members do, `evt.destinationCalendar?.push(...teamDestinationCalendars)` returns `undefined` and the collected `teamDestinationCalendars` are dropped — `EventManager.createAllCalendarEvents` then takes the `else` branch and creates only one event on the organizer's first calendar credential, defeating the PR's core goal.

Fix: `evt.destinationCalendar = [...(evt.destinationCalendar ?? []), ...teamDestinationCalendars];`

2026-08-12 18:29 UTC, ron-x5labs commented on packages/app-store/office365calendar/lib/CalendarService.ts
> +    const [mainHostDestinationCalendar] = event.destinationCalendar ?? [];
🔴 **Ignores `credentialId` — always targets `destinationCalendar[0]`, breaking the collective flow for Office 365 (and Lark).** `EventManager.createAllCalendarEvents` now loops every host's destination calendar and calls `createEvent(credential, event, destination.externalId)` per host. Google's `createEvent` uses the new `credentialId` param to pick the matching destination; O365 (and Lark, `CalendarService.ts:128/164/192/237`) still destructure `event.destinationCalendar[0]` — the organizer's `externalId`. When the loop processes host B's O365 credential with host B's destination, the event is still written to host A's calendar URL → 404 or wrong calendar, and host B never gets their event.

Only Google received the `credentialId`-matching treatment; O365 and Lark need the same per-credential selection for multi-host collective events to work.

2026-08-12 18:29 UTC, ron-x5labs commented on packages/core/EventManager.ts
> +            const credentialFromDB = await prisma.credential.findUnique({
🟡 **N+1 DB queries + convention/defense gaps in the credential fallback.** Three sites (`createAllCalendarEvents` here, `updateAllCalendarEvents:517`, `handleCancelBooking.ts:433`) do `prisma.credential.findUnique` sequentially inside a `for…of` loop — N round-trips for N hosts. Batch with `findMany({ where: { id: { in: ids } } })`.

Additionally: (1) uses `include` instead of `select` (repo rule), loading the full `key`; (2) no `userId`/`teamId` filter — `destination.credentialId` is trusted at write time but there's no defense-in-depth check; (3) `credentialFromDB.invalid` is copied through but never gated on; (4) when `credentialFromDB` is null the destination is silently skipped with no log, leaving an orphaned calendar event.

2026-08-12 18:29 UTC, ron-x5labs commented on packages/core/EventManager.ts
>          const oldCalendarEvent = booking.references.find((reference) => reference.type.includes("_calendar"));
🟡 **Reschedule merge only deletes the first old calendar reference.** `booking.references.find(...)` returns a single reference, but with the array change a team event now has multiple `_calendar` references. Only the first old calendar event is deleted; the rest persist as orphans on the providers' calendars. Use `.filter()` and delete each, mirroring the `updateAllCalendarEvents` change above.

2026-08-12 18:29 UTC, ron-x5labs commented on packages/trpc/server/routers/viewer/bookings/requestReschedule.handler.ts
> +    destinationCalendar: bookingToReschedule?.destinationCalendar
🟡 **Dropped the `user.destinationCalendar` fallback — inconsistent with every sibling handler.** `handleCancelBooking`, `confirm`, `editLocation`, `deleteCredential`, and the Stripe/PayPal/cron handlers all use `booking.destinationCalendar ? [booking.destinationCalendar] : user.destinationCalendar ? [user.destinationCalendar] : []`. This handler falls straight to `[]`, so a reschedule on a booking whose `destinationCalendar` is null but whose user has one will operate without a destination calendar. (The pre-existing code had a duplicated expression — both sides `bookingToReschedule?.destinationCalendar` — but the fix should restore the `user.destinationCalendar` fallback rather than drop it.)

2026-08-12 18:29 UTC, ron-x5labs commented on packages/features/bookings/lib/handleNewBooking.ts
> +  const loadUsers = async () => {
🟡 **`loadUsers` try/catch masks bugs and mis-maps status codes.** The wrapper converts every error to `HttpError` 400/500: `Prisma.PrismaClientKnownRequestError` is unconditionally 400, but infra failures (P1001 connection, P2024 timeout) should be 500; and programmer errors (`TypeError`, `ReferenceError`) are hidden behind a generic "Unable to load users" 500 instead of surfacing the real bug. Consider catching only the expected `HttpError` and letting unexpected errors propagate, and mapping Prisma codes individually.

2026-08-12 18:29 UTC, ron-x5labs commented on packages/core/EventManager.ts
> +      return Promise.resolve(
🟡 **Observability loss in the error path.** The old `console.error(message)` (which logged the credential type and booking context on `updateAllCalendarEvents` failure) was removed and not replaced. The catch now silently returns an error array with no log — failures in multi-host calendar updates will be hard to diagnose in production.

2026-08-12 18:29 UTC, ron-x5labs commented on packages/app-store/googlecalendar/lib/CalendarService.ts
> +        (cal) => cal.credentialId === credentialId
💡 When no `destinationCalendar` matches the current `credentialId`, `selectedCalendar || 'primary'` silently writes to the user's primary calendar. With the old single-object model a mismatch was impossible; with the array model a stale credential/destination mapping would silently misroute. Consider logging a warning so this is observable.

2026-08-12 18:29 UTC, ron-x5labs commented on packages/features/bookings/lib/handleNewBooking.ts
> +      teamDestinationCalendars.push(user.destinationCalendar);
💡 `"COLLECTIVE"` string literal works (the custom enum generator emits uppercase names), but `SchedulingType.COLLECTIVE` is more maintainable — a future enum rename would be caught by the type system. Applies to `:689` and `:1077` too.

2026-08-15 08:26 UTC, ron-x5labs requested changes
## Code Review: Convert `destinationCalendar` to an array

### Problem
Support multiple destination calendars on a `CalendarEvent` so collective/team events create calendar entries on each host's calendar (fixes #7754).

### Solution Reviewed
`CalendarEvent.destinationCalendar` changes from `DestinationCalendar | null` to `DestinationCalendar[] | null`. The `Calendar.createEvent` interface gains a `credentialId` param (only Google uses it to pick the matching destination); `EventManager` create/update/delete now loop the array and fall back to a DB credential fetch per host; booking/payment/cron handlers wrap the single Prisma `destinationCalendar` into an array; providers and `BaseCalendarService` destructure `destinationCalendar[0]` as the "main host".

### Summary
The core design is sound, but several blocking bugs remain: a NullPointerException on `mainHostDestinationCalendar.integration`, a self-referential `.find()` in Google `updateEvent`/`deleteEvent` that targets the wrong (or undefined) calendar, a no-op `?.push` that silently drops team members' calendars, and every non-Google provider (O365, Lark, CalDAV `BaseCalendarService`) ignoring the new `credentialId` so they always write to `destinationCalendar[0]` (the organizer's) — defeating the PR's goal for those providers. I also found the update-path DB-fetch lacks the `if (credential)` guard the create path has, so one stale host credential aborts all calendar updates during a reschedule.

This is an independent full re-review of the entire diff (all 22 files). I re-verified each finding against the current source at the cited lines.

### Files Reviewed
- `packages/core/EventManager.ts` — deeply reviewed
- `packages/core/CalendarManager.ts` — deeply reviewed
- `packages/app-store/googlecalendar/lib/CalendarService.ts` — deeply reviewed
- `packages/app-store/office365calendar/lib/CalendarService.ts` — deeply reviewed
- `packages/app-store/larkcalendar/lib/CalendarService.ts` — deeply reviewed
- `packages/lib/CalendarService.ts` (BaseCalendarService / CalDAV) — deeply reviewed
- `packages/features/bookings/lib/handleNewBooking.ts` — deeply reviewed
- `packages/features/bookings/lib/handleCancelBooking.ts` — deeply reviewed
- `packages/trpc/server/routers/viewer/bookings/requestReschedule.handler.ts` — deeply reviewed
- `packages/features/ee/payments/api/paypal-webhook.ts` — lightly reviewed (mechanical array wrap)
- `packages/features/ee/payments/api/webhook.ts` — lightly reviewed (mechanical array wrap)
- `packages/trpc/server/routers/loggedInViewer/deleteCredential.handler.ts` — lightly reviewed (mechanical array wrap)
- `packages/trpc/server/routers/viewer/bookings/confirm.handler.ts` — lightly reviewed (mechanical array wrap)
- `packages/trpc/server/routers/viewer/bookings/editLocation.handler.ts` — lightly reviewed (mechanical array wrap)
- `packages/trpc/server/routers/viewer/organizations/create.handler.ts` — lightly reviewed (unrelated billing-condition refactor)
- `packages/types/Calendar.d.ts`, `packages/types/EventManager.d.ts` — lightly reviewed (type changes)
- `packages/core/builders/CalendarEvent/builder.ts`, `class.ts` — lightly reviewed (mechanical)
- `packages/emails/src/templates/BrokenIntegrationEmail.tsx` — lightly reviewed
- `apps/web/pages/api/cron/bookingReminder.ts` — lightly reviewed (mechanical array wrap)
- `apps/web/playwright/webhook.e2e.ts` — lightly reviewed (test fixture)

### Verification
- `yarn type-check:ci` — skipped: fresh worktree has no `node_modules`; enum/string-literal and signature claims verified by source inspection instead.
- Source inspection of `getCalendar`, `updateEvent`, `createEvent`, all `createEvent` implementers, and `userSelect` used to ground each finding.

### Issues Found

#### Blocking
- `packages/core/EventManager.ts:119` — `mainHostDestinationCalendar.integration` NPE when `destinationCalendar` is `null`/`[]`.
- `packages/app-store/googlecalendar/lib/CalendarService.ts:256` — `updateEvent` `.find()` predicate is self-referential; `selectedCalendar` is `undefined`, no `|| 'primary'` fallback → update fails.
- `packages/app-store/googlecalendar/lib/CalendarService.ts:317` — `deleteEvent` same `.find()` bug; falls back to `'primary'`, deleting from the wrong calendar.
- `packages/features/bookings/lib/handleNewBooking.ts:1078` — `evt.destinationCalendar?.push(...)` is a no-op when `destinationCalendar` is `null`; team calendars silently lost.
- `packages/app-store/office365calendar/lib/CalendarService.ts:73` — ignores `credentialId`, always uses `destinationCalendar[0]`; wrong host's calendar in collective flow (Lark + CalDAV `BaseCalendarService` same).

#### Non-blocking
- `packages/core/EventManager.ts:542` — update path calls `updateEvent(credential, …)` with no `if (credential)` guard (create path has it); one stale credential aborts all hosts' updates via the outer catch.
- `packages/core/EventManager.ts:344` — N+1 sequential `prisma.credential.findUnique` inside the loop (also `:517`, `handleCancelBooking.ts:433`); uses `include` not `select` (loads `key`), no ownership filter, no `invalid` gate, silent skip on null.
- `packages/core/EventManager.ts:554` — reschedule merge only deletes the first old calendar reference (`.find` not `.filter`); orphans remaining host events.
- `packages/trpc/server/routers/viewer/bookings/requestReschedule.handler.ts:240` — dropped `user.destinationCalendar` fallback; inconsistent with every sibling handler.
- `packages/features/bookings/lib/handleNewBooking.ts:757` — `loadUsers` try/catch masks programmer errors and maps all `PrismaClientKnownRequestError` codes to 400.
- `packages/core/EventManager.ts:597` — removed `console.error` in the error path; observability loss.

#### Suggestions
- `packages/app-store/googlecalendar/lib/CalendarService.ts:154` — silent fallback to `'primary'` on credentialId mismatch; consider logging a warning.
- `packages/features/bookings/lib/handleNewBooking.ts:1077` — use `SchedulingType.COLLECTIVE` enum constant instead of the `"COLLECTIVE"` string literal (also `:689`).

### Verdict
Recommend changes before merge — the NPE, the Google update/delete calendar-targeting bugs, the no-op `push`, and the non-Google `credentialId` gap each break core flows this PR intends to enable.

<!-- pr-local-code-review:v1 -->

2026-08-15 08:26 UTC, ron-x5labs commented on packages/core/EventManager.ts
> +    if (evt.location === MeetLocationType && mainHostDestinationCalendar.integration !== "google_calendar") {
**🔴 NPE — missing optional chaining.** `const [mainHostDestinationCalendar] = evt.destinationCalendar ?? []` yields `undefined` when `destinationCalendar` is `null`, `undefined`, or `[]` (the `??` only guards nullish values, not empty arrays). The next line dereferences `mainHostDestinationCalendar.integration` without `?.`, throwing `TypeError` whenever `evt.location === MeetLocationType` and no destination calendar is configured.

This is reachable from the payment webhooks, the cron reminder, and `handleNewBooking` (which sets `destinationCalendar: null` when neither the event type nor organizer has one). Every other `mainHostDestinationCalendar` usage in this PR uses `?.externalId`.

```ts
if (evt.location === MeetLocationType && mainHostDestinationCalendar?.integration !== "google_calendar") {
```

2026-08-15 08:26 UTC, ron-x5labs commented on packages/app-store/googlecalendar/lib/CalendarService.ts
> +        : event.destinationCalendar?.find((cal) => cal.externalId === externalCalendarId)?.externalId;
**🔴 Self-referential `.find()` — `selectedCalendar` is always `undefined` here.** In the `else` branch `externalCalendarId` is already falsy, so the predicate `cal.externalId === externalCalendarId` compares against `undefined`/`null` and never matches a real calendar. `selectedCalendar` is `undefined`, and `calendarId: selectedCalendar` (line 261) is passed to `calendar.events.update` with no `|| 'primary'` fallback (unlike `createEvent`). Every Google Calendar update without an explicit `externalCalendarId` will fail.

The old code used `event.destinationCalendar?.externalId` directly. The array equivalent is `event.destinationCalendar?.[0]?.externalId` (or match on `credentialId` as `createEvent` now does):
```ts
const selectedCalendar = externalCalendarId
  ? externalCalendarId
  : event.destinationCalendar?.[0]?.externalId;
```

2026-08-15 08:26 UTC, ron-x5labs commented on packages/app-store/googlecalendar/lib/CalendarService.ts
> +        : event.destinationCalendar?.find((cal) => cal.externalId === externalCalendarId)?.externalId;
**🔴 Same `.find()` bug in `deleteEvent` — deletes from the wrong calendar.** `event.destinationCalendar?.find((cal) => cal.externalId === externalCalendarId)` with a falsy `externalCalendarId` never matches, so `calendarId` is `undefined` and falls through to `defaultCalendarId` (`'primary'`, line 322). When a booking has a real destination calendar, the event is deleted from the user's primary calendar instead of the configured destination — silently wrong.

```ts
const calendarId = externalCalendarId
  ? externalCalendarId
  : event.destinationCalendar?.[0]?.externalId;
```

2026-08-15 08:26 UTC, ron-x5labs commented on packages/features/bookings/lib/handleNewBooking.ts
> +    evt.destinationCalendar?.push(...teamDestinationCalendars);
**🔴 `?.push` is a no-op when `destinationCalendar` is `null` — team calendars are silently lost.** Five lines above, `destinationCalendar` is set to `null` when both `eventType.destinationCalendar` and `organizerUser.destinationCalendar` are absent. For a collective event where the organizer has no destination calendar but team members do, `evt.destinationCalendar?.push(...teamDestinationCalendars)` returns `undefined` and the collected `teamDestinationCalendars` are dropped — `EventManager.createAllCalendarEvents` then takes the `else` branch and creates only one event on the organizer's first calendar credential, defeating the PR's core goal.

```ts
evt.destinationCalendar = [...(evt.destinationCalendar ?? []), ...teamDestinationCalendars];
```

2026-08-15 08:26 UTC, ron-x5labs commented on packages/app-store/office365calendar/lib/CalendarService.ts
> +    const [mainHostDestinationCalendar] = event.destinationCalendar ?? [];
**🔴 Ignores `credentialId` — always targets `destinationCalendar[0]`, breaking the collective flow for Office 365 (and Lark, and CalDAV).** `EventManager.createAllCalendarEvents` now loops every host's destination calendar and calls `createEvent(credential, event, destination.externalId)` per host. Google's `createEvent` uses the new `credentialId` param to pick the matching destination; O365 (and Lark at `larkcalendar/lib/CalendarService.ts:128/164/192/237`, and the CalDAV `BaseCalendarService` at `packages/lib/CalendarService.ts:156`) still destructure `event.destinationCalendar[0]` — the organizer's `externalId`. When the loop processes host B's credential with host B's destination, the event is still written to host A's calendar URL → 404 or wrong calendar, and host B never gets their event.

Only Google received the `credentialId`-matching treatment; the other real calendar providers need the same per-credential selection for multi-host collective events to work.

2026-08-15 08:26 UTC, ron-x5labs commented on packages/core/EventManager.ts
>            result.push(updateEvent(credential, event, bookingRefUid, calenderExternalId));
**🟡 Missing `if (credential)` guard in the update path.** Unlike `createAllCalendarEvents` (line 369 guards `if (credential)` before `createEvent`), the update path calls `updateEvent(credential, event, bookingRefUid, calenderExternalId)` unconditionally at line 542. If the DB fetch yields no credential (deleted/invalid, or `credentialFromDB.app?.slug` is falsy), `credential` stays `undefined`, `getCalendar(undefined)` throws, and the outer `catch` (line 591) returns failure for **all** references — so one stale host credential aborts every host's calendar update during a reschedule.

```ts
if (credential) {
  result.push(updateEvent(credential, event, bookingRefUid, calenderExternalId));
}
```

2026-08-15 08:26 UTC, ron-x5labs commented on packages/core/EventManager.ts
> +            const credentialFromDB = await prisma.credential.findUnique({
**🟡 N+1 DB queries + convention/defense gaps in the credential fallback.** Three sites (`createAllCalendarEvents` here, `updateAllCalendarEvents:517`, `handleCancelBooking.ts:433`) do `prisma.credential.findUnique` sequentially inside a `for…of` loop — N round-trips for N hosts. Batch with `findMany({ where: { id: { in: ids } } })`.

Additionally: (1) uses `include` instead of `select` (repo rule), loading the full `key`; (2) no `userId`/`teamId` filter — `destination.credentialId` is trusted at write time but there's no defense-in-depth check; (3) `credentialFromDB.invalid` is copied through but never gated on; (4) when `credentialFromDB` is null the destination is silently skipped with no log, leaving an orphaned calendar event.

2026-08-15 08:26 UTC, ron-x5labs commented on packages/core/EventManager.ts
>          const oldCalendarEvent = booking.references.find((reference) => reference.type.includes("_calendar"));
**🟡 Reschedule merge only deletes the first old calendar reference.** `booking.references.find(...)` returns a single reference, but with the array change a team event now has multiple `_calendar` references. Only the first old calendar event is deleted; the rest persist as orphans on the providers' calendars. Use `.filter()` and delete each, mirroring the `updateAllCalendarEvents` change above.

2026-08-15 08:26 UTC, ron-x5labs commented on packages/trpc/server/routers/viewer/bookings/requestReschedule.handler.ts
> +    destinationCalendar: bookingToReschedule?.destinationCalendar
**🟡 Dropped the `user.destinationCalendar` fallback — inconsistent with every sibling handler.** `handleCancelBooking`, `confirm`, `editLocation`, `deleteCredential`, and the Stripe/PayPal/cron handlers all use `booking.destinationCalendar ? [booking.destinationCalendar] : user.destinationCalendar ? [user.destinationCalendar] : []`. This handler falls straight to `[]`, so a reschedule on a booking whose `destinationCalendar` is null but whose user has one will operate without a destination calendar. (The pre-existing code had a duplicated expression — both sides `bookingToReschedule?.destinationCalendar` — but the fix should restore the `user.destinationCalendar` fallback rather than drop it.)

2026-08-15 08:26 UTC, ron-x5labs commented on packages/features/bookings/lib/handleNewBooking.ts
> +    } catch (error) {
**🟡 `loadUsers` try/catch masks bugs and mis-maps status codes.** The wrapper converts every error to `HttpError` 400/500: `Prisma.PrismaClientKnownRequestError` is unconditionally 400, but infra failures (P1001 connection, P2024 timeout) should be 500; and programmer errors (`TypeError`, `ReferenceError`) are hidden behind a generic "Unable to load users" 500 instead of surfacing the real bug. Consider catching only the expected `HttpError` and letting unexpected errors propagate, and mapping Prisma codes individually.

2026-08-15 08:26 UTC, ron-x5labs commented on packages/core/EventManager.ts
> +      return Promise.resolve(
**🟡 Observability loss in the error path.** The old `console.error(message)` (which logged the credential type and booking context on `updateAllCalendarEvents` failure) was removed and not replaced. The catch now silently returns an error array with no log — failures in multi-host calendar updates will be hard to diagnose in production. Re-add a `logger.error` here.

2026-08-15 08:26 UTC, ron-x5labs commented on packages/app-store/googlecalendar/lib/CalendarService.ts
> +          calendarId: selectedCalendar || "primary",
**💡** When no `destinationCalendar` matches the current `credentialId`, `selectedCalendar || 'primary'` silently writes to the user's primary calendar. With the old single-object model a mismatch was impossible; with the array model a stale credential/destination mapping would silently misroute. Consider logging a warning so this is observable.

2026-08-15 08:26 UTC, ron-x5labs commented on packages/features/bookings/lib/handleNewBooking.ts
> +  if (isTeamEventType && eventType.schedulingType === "COLLECTIVE") {
**💡** `"COLLECTIVE"` works (the custom enum generator emits uppercase names), but `SchedulingType.COLLECTIVE` is more maintainable — a future enum rename would be caught by the type system. Applies to the `isTeamEventType` check at `:689` too.

2026-08-21 20:43 UTC, ron-x5labs requested changes
## Code Review: Convert destinationCalendar to array for multi-host support

### Problem
PR #10967 converts `CalendarEvent.destinationCalendar` from a single object to an array, enabling calendar events to be written to each host's calendar in collective/team events (fixes #7754).

### Solution Reviewed
The diff updates `CalendarEvent` type, `EventManager` (create/update/cancel paths), Google/O365/Lark/CalDAV `CalendarService` implementations, `CalendarManager`, booking handlers, and payment webhooks to handle the array form. Google's `createEvent` was updated to accept a `credentialId` parameter for per-host calendar selection.

### Summary
The core idea is sound, but the implementation has **5 blocking bugs** that will crash bookings or silently lose data in production. The Google-specific changes work, but non-Google adapters, the video reference path, and several edge cases were missed. The `create.handler.ts` slug inversion appears to be an accidental unrelated change.

### Files Reviewed
- `packages/core/EventManager.ts` — deeply reviewed (create/update/cancel/reschedule paths)
- `packages/core/CalendarManager.ts` — deeply reviewed (createEvent/updateEvent return shapes)
- `packages/app-store/googlecalendar/lib/CalendarService.ts` — deeply reviewed (create/update/delete)
- `packages/app-store/office365calendar/lib/CalendarService.ts` — deeply reviewed
- `packages/features/bookings/lib/handleNewBooking.ts` — deeply reviewed
- `packages/features/bookings/lib/handleCancelBooking.ts` — deeply reviewed
- `packages/trpc/server/routers/viewer/organizations/create.handler.ts` — deeply reviewed
- `packages/trpc/server/routers/viewer/bookings/requestReschedule.handler.ts` — deeply reviewed
- `packages/trpc/server/routers/viewer/bookings/editLocation.handler.ts` — deeply reviewed
- `packages/types/Calendar.d.ts`, `EventManager.d.ts` — lightly reviewed (type changes)
- `packages/lib/CalendarService.ts` (BaseCalendarService) — deeply reviewed
- `packages/features/ee/payments/api/paypal-webhook.ts`, `webhook.ts` — lightly reviewed
- `apps/web/pages/api/cron/bookingReminder.ts` — lightly reviewed
- `apps/web/playwright/webhook.e2e.ts` — lightly reviewed (fixture only)

### Verification
- Read full source of all modified files in PR worktree
- Verified `CalendarManager.updateEvent` return shape (no `externalId`/`credentialId`) vs `createEvent` (has both)
- Verified `videoClient.ts:78` returns `credentialId: credential.id` and `handleCancelBooking.ts:491` gates deletion on it
- Verified `SchedulingType` enum values (`COLLECTIVE`/`ROUND_ROBIN` uppercase) match string comparisons — not a bug
- Verified all 14 inline comment line numbers fall within diff hunks

### Issues Found

#### Blocking (5)
1. **EventManager.ts:119** — NPE: `mainHostDestinationCalendar.integration` without `?.` when array is null/empty
2. **EventManager.ts:170** — Video refs lose `credentialId` → orphaned video rooms on cancel (#9281 regression)
3. **EventManager.ts:542** — Missing `if(credential)` guard → one missing credential aborts ALL calendar updates
4. **googlecalendar/CalendarService.ts:256** — Self-referential `.find()` → `selectedCalendar` always `undefined`
5. **handleNewBooking.ts:1078** — `?.push()` no-op when `destinationCalendar` is null → team hosts lost
6. **create.handler.ts:151** — Slug condition inverted (`!` dropped) — unrelated to PR purpose

#### Non-blocking (8)
7. **EventManager.ts:209** — `updateLocation` reads fields `updateEvent` doesn't return
8. **EventManager.ts:344** — `include` not `select` (AGENTS.md violation) + N+1 query pattern
9. **EventManager.ts:554** — `.find()` not `.filter()` → orphaned calendar events on reschedule
10. **EventManager.ts:597** — `console.error` removed, no replacement → silent failures
11. **googlecalendar/CalendarService.ts:317** — Same `.find()` bug in deleteEvent → deletes from 'primary'
12. **office365calendar/CalendarService.ts:73** — Ignores `credentialId`, uses `destinationCalendar[0]`
13. **handleNewBooking.ts:758** — Prisma infra errors (P1001/P2024) mapped to 400 not 500
14. **requestReschedule.handler.ts:242** — Drops `user.destinationCalendar` fallback

#### Test Coverage
The PR checklist states "I haven't added tests." The only test change is a Playwright fixture literal (`destinationCalendar: []`). Zero unit/integration tests exist for the new array branching: the per-destination create loop, credentialId-based `.find()` in Google's createEvent, the externalId-based `.find()` in update/delete, the multi-reference filter/map in updateAllCalendarEvents, and the `teamDestinationCalendars` push. Given the 6 blocking bugs above that CI cannot catch, test coverage for the core array branching logic is strongly recommended before merge.

### Verdict
**Request changes before merge.** The 6 blocking bugs (NPE, video credentialId regression, self-referential find, push no-op, missing guard, slug inversion) will crash bookings or silently lose data in production. The non-Google adapter gap means the multi-host feature only works for Google Calendar. Fix the blocking issues, update O365/Lark/CalDAV to accept `credentialId`, and add test coverage for the array branching.

<!-- pr-local-code-review:v1 -->

2026-08-21 20:43 UTC, ron-x5labs commented on packages/core/EventManager.ts
> +    if (evt.location === MeetLocationType && mainHostDestinationCalendar.integration !== "google_calendar") {
**🔴 Blocking: NPE when `destinationCalendar` is null or empty**

`mainHostDestinationCalendar` is `undefined` when `evt.destinationCalendar` is `null` or `[]` (set to `null` in `handleNewBooking.ts:1066` when neither eventType nor organizer has one). The dereference `mainHostDestinationCalendar.integration` throws a `TypeError`, crashing the entire booking flow for Google Meet events without a destination calendar.

The old code used `evt.destinationCalendar?.integration` (optional chaining), which safely returned `undefined` and triggered the Cal Video fallback.

```ts
if (evt.location === MeetLocationType && mainHostDestinationCalendar?.integration !== "google_calendar") {
```

2026-08-21 20:43 UTC, ron-x5labs commented on packages/core/EventManager.ts
> +        credentialId: isCalendarType ? result.credentialId : undefined,
**🔴 Blocking: Video references lose `credentialId`, regressing #9281**

For non-calendar results (`isCalendarType` is false), `credentialId` is now always `undefined`. The old code was `isCalendarType ? evt.destinationCalendar?.credentialId : result.credentialId`, which correctly threaded `result.credentialId` for video providers.

`videoClient.ts:78` returns `credentialId: credential.id`, but this new code discards it. On cancellation, `handleCancelBooking.ts:491` gates video meeting deletion on `bookingVideoReference.credentialId` with no `else` branch — so video rooms (Daily, Zoom, Teams) are orphaned and never deleted.

```ts
credentialId: isCalendarType ? result.credentialId : result.credentialId,
```

2026-08-21 20:43 UTC, ron-x5labs commented on packages/core/EventManager.ts
> +        credentialId: result.credentialId ?? undefined,
**`updateLocation` produces broken calendar references**

`result.externalId` and `result.credentialId` are read here, but `CalendarManager.updateEvent` (CalendarManager.ts:313-322) does not return `externalId` or `credentialId` in its return object — only `createEvent` does (lines 257-269). So calendar references created by `editLocation.handler.ts:120` end up with `externalCalendarId: undefined`, `credentialId: undefined`, and `uid: ""` (updateEvent returns `updatedEvent`, not `createdEvent`). These broken references cascade into failed deletions on later cancel/reschedule.

The old code used `evt.destinationCalendar?.externalId` and `result.credentialId ?? evt.destinationCalendar?.credentialId`.

2026-08-21 20:43 UTC, ron-x5labs commented on packages/core/EventManager.ts
> +            const credentialFromDB = await prisma.credential.findUnique({
**AGENTS.md violation: `include` instead of `select`**

AGENTS.md requires `select` over `include` for performance and security. `include` loads all columns of the credential row plus the full app relation, while `select` would load only the fields needed for the reconstructed credential object (lines 357-366). The same pattern appears in `updateAllCalendarEvents` (line 517). Additionally, both sites run `findUnique` inside `for...of` loops (N+1 query pattern for N-host team events).

```ts
const credentialFromDB = await prisma.credential.findUnique({
  select: { id: true, type: true, userId: true, teamId: true, invalid: true, appId: true, key: true, app: { select: { slug: true } } },
  where: { id: destination.credentialId },
});
```

2026-08-21 20:43 UTC, ron-x5labs commented on packages/core/EventManager.ts
>            result.push(updateEvent(credential, event, bookingRefUid, calenderExternalId));
**🔴 Blocking: Missing `if (credential)` guard — one bad credential aborts all updates**

`updateEvent(credential, ...)` is called without checking `credential` is defined. When the in-memory lookup fails AND the DB fallback returns null (deleted credential), `credential` is `undefined`. `CalendarManager.updateEvent` (line 314) then accesses `credential.appName` → `TypeError`. The outer catch (line 591) catches this and returns failure for ALL `calendarReference` entries, not just the one with the missing credential.

The sibling `createAllCalendarEvents` (line 369) correctly guards with `if (credential)`.

```ts
if (credential) {
  result.push(updateEvent(credential, event, bookingRefUid, calenderExternalId));
}
```

2026-08-21 20:43 UTC, ron-x5labs commented on packages/core/EventManager.ts
>          const oldCalendarEvent = booking.references.find((reference) => reference.type.includes("_calendar"));
**`.find()` only deletes the first old calendar event — others are orphaned**

With `destinationCalendar` now an array, a team collective event has multiple `_calendar` booking references. `.find()` returns only the first match, so only the first host's old calendar event is deleted during reschedule merge — the rest are orphaned on their respective calendars.

The surrounding code correctly migrated to `.filter()` (line 500 for `calendarReference`, `handleCancelBooking.ts:418`). This site was missed.

```ts
const oldCalendarEvents = booking.references.filter((reference) => reference.type.includes("_calendar"));
for (const oldCalendarEvent of oldCalendarEvents) {
  if (oldCalendarEvent?.credentialId) {
    // ...delete each...
  }
}
```

2026-08-21 20:43 UTC, ron-x5labs commented on packages/core/EventManager.ts
> +      return Promise.resolve(
**`console.error(message)` removed — update failures now silent**

The catch block still builds a descriptive `message` string (lines 592-595) but the `console.error(message)` that logged it was removed with no replacement (`log.error`/`logger.error`). The `message` variable is now dead — assigned but never read. Calendar update failures return `{ success: false }` with zero operator visibility.

Consider restoring logging or replacing with `log.error`.

2026-08-21 20:43 UTC, ron-x5labs commented on packages/app-store/googlecalendar/lib/CalendarService.ts
> +        : event.destinationCalendar?.find((cal) => cal.externalId === externalCalendarId)?.externalId;
**🔴 Blocking: Self-referential `.find()` — `selectedCalendar` is always `undefined`**

The `else` branch runs only when `externalCalendarId` is falsy. The predicate `cal.externalId === externalCalendarId` compares each calendar's externalId against a falsy value — which never matches (externalId is a non-empty string). So `.find()` always returns `undefined` and `selectedCalendar` is `undefined`. The Google API call with `calendarId: undefined` rejects.

`updateAllCalendarEvents` passes `calenderExternalId = null` when the booking reference lacks `externalCalendarId`, so this path is exercised. The old code fell back to `event.destinationCalendar?.externalId`.

```ts
const selectedCalendar = externalCalendarId
  ? externalCalendarId
  : event.destinationCalendar?.[0]?.externalId;
```

2026-08-21 20:43 UTC, ron-x5labs commented on packages/app-store/googlecalendar/lib/CalendarService.ts
> +        : event.destinationCalendar?.find((cal) => cal.externalId === externalCalendarId)?.externalId;
**Same self-referential `.find()` in `deleteEvent` — deletes from `'primary'`**

Same bug as `updateEvent` above: the else branch's `.find()` never matches (predicate compares against falsy `externalCalendarId`). Unlike update, `deleteEvent` falls back to `defaultCalendarId` (`"primary"`) at line 322, so it deletes from the user's primary calendar instead of the calendar where the event actually lives — or 404s if no event with that uid exists on primary.

2026-08-21 20:43 UTC, ron-x5labs commented on packages/app-store/office365calendar/lib/CalendarService.ts
> +    const [mainHostDestinationCalendar] = event.destinationCalendar ?? [];
**O365/Lark/CalDAV ignore `credentialId`, always target `destinationCalendar[0]`**

Only Google's `createEvent` was updated to accept `credentialId` and select the matching destination. O365 (here), Lark, and `BaseCalendarService` still destructure `destinationCalendar[0]` (the organizer's) regardless of which credential is passed. In `createAllCalendarEvents`' per-host loop, host B's credential writes to host A's calendar ID — which host B doesn't own (error/4xx, silently caught). Multi-host collective behavior only works for Google.

```ts
async createEvent(event: CalendarEvent, credentialId: number): Promise<NewCalendarEventType> {
  const dest = event.destinationCalendar?.find((cal) => cal.credentialId === credentialId);
  const eventsUrl = dest?.externalId ? `/me/calendars/${dest.externalId}/events` : "/me/calendar/events";
```

2026-08-21 20:43 UTC, ron-x5labs commented on packages/features/bookings/lib/handleNewBooking.ts
> +      if (error instanceof HttpError || error instanceof Prisma.PrismaClientKnownRequestError) {
**Prisma infrastructure errors mapped to 400 instead of 500**

`PrismaClientKnownRequestError` includes connection/timeout codes (P1001 "Can't reach database server", P2024 "Timed out fetching a connection"). These are server-side failures, not client bad-request errors, but they're all surfaced as 400. This misleads monitoring (400s are typically not paged). Consider checking `error.code` to distinguish infra errors (500) from constraint violations (400).

2026-08-21 20:43 UTC, ron-x5labs commented on packages/features/bookings/lib/handleNewBooking.ts
> +    evt.destinationCalendar?.push(...teamDestinationCalendars);
**🔴 Blocking: `?.push()` is a no-op when `destinationCalendar` is `null`**

`evt.destinationCalendar` is set to `null` at line 1066 when neither `eventType` nor `organizerUser` has a destination calendar. The optional chaining `evt.destinationCalendar?.push(...teamDestinationCalendars)` then silently does nothing — all team hosts' destination calendars (built at lines 987-993) are discarded. For COLLECTIVE events without an organizer destination calendar, NO team calendars are targeted, defeating the PR's purpose.

```ts
if (isTeamEventType && eventType.schedulingType === "COLLECTIVE") {
  evt.destinationCalendar = [...(evt.destinationCalendar ?? []), ...teamDestinationCalendars];
}
```

2026-08-21 20:43 UTC, ron-x5labs commented on packages/trpc/server/routers/viewer/organizations/create.handler.ts
> +            ...(IS_TEAM_BILLING_ENABLED ? { slug } : {}),
**🔴 Blocking: Slug condition inverted — unrelated to PR's purpose**

The `!` was dropped: `...(!IS_TEAM_BILLING_ENABLED && { slug })` → `...(IS_TEAM_BILLING_ENABLED ? { slug } : {})`. This reverses when a slug is set directly: self-hosted orgs (billing disabled) now get NO slug at creation, breaking subdomain routing; cloud orgs (billing enabled) get a slug immediately, bypassing the payment-gated publish flow (`publish.handler.ts:39` charges before publishing). The adjacent `requestedSlug` line (153) kept its logic, so cloud orgs now get BOTH `slug` AND `requestedSlug` — contradictory.

```ts
...(!IS_TEAM_BILLING_ENABLED ? { slug } : {}),
```

2026-08-21 20:43 UTC, ron-x5labs commented on packages/trpc/server/routers/viewer/bookings/requestReschedule.handler.ts
> +      : [],
**Drops `user.destinationCalendar` fallback — inconsistent with sibling handlers**

Every sibling handler (`confirm`, `editLocation`, `deleteCredential`, `handleCancelBooking`, payment webhooks) falls back to `user.destinationCalendar` when the booking has none. `requestReschedule` is now the only handler that yields `[]`, so a reschedule for a user with a user-level destination calendar produces a calendar-less event while confirm/cancel of the same booking would target it. `user` is available from `ctx.user`.

```ts
destinationCalendar: bookingToReschedule?.destinationCalendar
  ? [bookingToReschedule?.destinationCalendar]
  : user.destinationCalendar
  ? [user.destinationCalendar]
  : [],
```