refactor: WIP
calcom/cal.com pull request #11124
Opened 2023-09-04 07:38 UTC by Udit-takkar

## What does this PR do?

Fixes # (issue)

## Type of change

- [ ] Chore (refactoring code, technical debt, workflow improvements)

2023-09-22 08:27 UTC, sean-brydon reviewed
Code looks great - few NITS. Nothing blocking.

Will compare UI to designs now

2023-09-22 08:27 UTC, sean-brydon commented on apps/web/pages/settings/my-account/calendars.tsx
> +  }, [query?.isLoading]);
Are we sure we dont need the dependancy here?

2023-09-22 08:27 UTC, sean-brydon commented on apps/web/pages/settings/my-account/calendars.tsx
> +import React, { Fragment, useState, useEffect } from "react";
```suggestion
import { Fragment, useState, useEffect } from "react";
```

I dont think we need to `import React` here

2023-09-22 08:27 UTC, sean-brydon commented on apps/web/pages/settings/my-account/general.tsx
> +  const [isReceiveMonthlyDigestEmailChecked, setIsReceiveMonthlyDigestEmailChecked] = useState<boolean>(
NIT: Not blocking

Lets try to use type infernace here - Normally explicity defining types is useful in cases where we're not sure what the type is - but given all of these are prefixed with `is` i think its fine to handle them as i suggested 
```suggestion
  const [isAllowDynamicBookingChecked, setIsAllowDynamicBookingChecked] = useState(
    !!user.allowDynamicBooking
  );
  const [isAllowSEOIndexingChecked, setIsAllowSEOIndexingChecked] = useState(
    user.allowSEOIndexing
  );
  const [isReceiveMonthlyDigestEmailChecked, setIsReceiveMonthlyDigestEmailChecked] = useState(
```

2023-09-22 08:27 UTC, sean-brydon commented on apps/web/pages/settings/security/password.tsx
> +      );
NIT:

Do you think we should just use a formSchema for this since we are already using rhf for this logic?

2023-09-22 08:27 UTC, sean-brydon commented on packages/features/ee/sso/components/SSOConfiguration.tsx
> +        <div className="[&>*]:border-subtle flex flex-col [&>*:last-child]:rounded-b-xl [&>*]:border [&>*]:border-t-0 [&>*]:px-4 [&>*]:py-6 [&>*]:sm:px-6">
👨‍🍳 Nice

2023-09-22 09:28 UTC, sean-brydon commented
From a design side:
the gap between each form element is a big too much [check spacing](https://www.figma.com/file/UajFu4M1APhn2AywAEJkJr/New-Features?type=design&node-id=7968-59632&mode=design&t=XAgjWnnczAa93H4c-4) > we should be using space-y-6(24px) here and not the 8 we are using as that results in 32px. I think this is the case on most pages i have checked
<img width="955" alt="CleanShot 2023-09-22 at 10 20 17@2x" src="https://github.com/calcom/cal.com/assets/55134778/a281de68-dec5-4897-850c-e4745a3f0698">

Switch should be centered in container 
<img width="514" alt="CleanShot 2023-09-22 at 10 25 16@2x" src="https://github.com/calcom/cal.com/assets/55134778/1fdffdc5-55ae-45bd-945e-04d299ac0d17">

<img width="523" alt="CleanShot 2023-09-22 at 10 26 20@2x" src="https://github.com/calcom/cal.com/assets/55134778/94fb186d-6f3d-433b-b47d-869d152f8454">
Slight padding inconsistency. Title is 24px and list item is 20px. Looks weird when there is a button in both as they are miss aligned. 

NITS: Can be addressed in a follow up. 

@ciaranha  @itsberkaya

2023-09-26 12:13 UTC, Udit-takkar commented
@sean-brydon thanks for the detailed review. everything should be fixed now

<img width="926" alt="Screenshot 2023-09-26 at 5 40 33 PM" src="https://github.com/calcom/cal.com/assets/53316345/2ba6b0f2-a7ae-4517-9821-c764fd1c32eb">

<img width="978" alt="Screenshot 2023-09-26 at 5 41 21 PM" src="https://github.com/calcom/cal.com/assets/53316345/4cf8ed0b-f0ed-4684-91cc-ab5826c07ec3">
<img width="1440" alt="Screenshot 2023-09-26 at 5 42 01 PM" src="https://github.com/calcom/cal.com/assets/53316345/f611f790-ed54-4463-9407-8aa6d1527748">

2023-09-26 12:50 UTC, sean-brydon submitted a review, later dismissed
NICE! 

LGTM - tested everything i think there is to test didnt notice any issue. 

@shivamklr please test this in QA

2023-09-27 11:24 UTC, PeerRich commented
font cut off "g"

![CleanShot 2023-09-27 at 12 24 29@2x](https://github.com/calcom/cal.com/assets/8019099/27e2e2a1-3d4e-41a9-9c27-a8b63e360a1c)

2023-09-27 11:26 UTC, PeerRich requested changes
screenshots dont match figma

many issues, font, positioning.

are screenshots old?

2023-09-27 11:28 UTC, PeerRich commented
not sure if related, can we make this save optimistically? can be a follow up PR

https://github.com/calcom/cal.com/assets/8019099/fbf7c3a0-0626-4bdf-9bc9-d295b473439e

2023-09-27 11:43 UTC, PeerRich requested changes, later dismissed
- [x] empty screen issues:
![CleanShot 2023-09-27 at 12 33 13@2x](https://github.com/calcom/cal.com/assets/8019099/22661092-189b-40fa-9f5f-db655b600036)
![CleanShot 2023-09-27 at 12 33 26@2x](https://github.com/calcom/cal.com/assets/8019099/a5724221-1955-40c5-8bf6-26e308edf7fc)


better:

![CleanShot 2023-09-27 at 12 34 09@2x](https://github.com/calcom/cal.com/assets/8019099/1e159bea-d223-48c8-a174-76810df413ca)


--


![CleanShot 2023-09-27 at 12 35 11@2x](https://github.com/calcom/cal.com/assets/8019099/87f4af2f-a021-4944-89b5-ca51ae4bfdec)

- [x] Danger area font too big (supposed to be 16px / text-base)
- [x] missing subtitle. Lets add: "Careful. Account deletion cannot be undone."

--

- [ ] on mobile we should remove border and padding to make more space

before:
![CleanShot 2023-09-27 at 12 36 48@2x](https://github.com/calcom/cal.com/assets/8019099/eeb7651f-17cd-449d-ba09-dfe91c38385c)

after:
![CleanShot 2023-09-27 at 12 38 45@2x](https://github.com/calcom/cal.com/assets/8019099/b86fddb7-bd62-41d0-93a9-3a5a302edca3)

--

- [ ] team profile header needs love

![CleanShot 2023-09-27 at 12 40 10@2x](https://github.com/calcom/cal.com/assets/8019099/b57a19e5-fcae-4a83-97f2-f1404465bad3)

- [ ] old select box in team settings

![CleanShot 2023-09-27 at 12 40 33@2x](https://github.com/calcom/cal.com/assets/8019099/951c21e5-c5ec-40c9-88f5-46a427d5d2b6)

- [ ] same here

![CleanShot 2023-09-27 at 12 41 14@2x](https://github.com/calcom/cal.com/assets/8019099/7ab7f01d-99e6-4d41-af9d-da1574151aa8)

- [ ] same here

![CleanShot 2023-09-27 at 12 41 39@2x](https://github.com/calcom/cal.com/assets/8019099/7ab5eaf9-46cc-4b7a-9512-d750f8bb4897)


--

- [ ] some skeletons look odd

![CleanShot 2023-09-27 at 12 42 04@2x](https://github.com/calcom/cal.com/assets/8019099/ca97090c-876e-4a6f-ab15-9dc9e95099ae)

--

- [ ] empty team upgrade screen likely doesn't need a headline
![CleanShot 2023-09-27 at 12 42 38@2x](https://github.com/calcom/cal.com/assets/8019099/29387f72-d98a-470e-b14d-a8b0d4f060b6)

2023-09-28 15:53 UTC, Udit-takkar commented on packages/features/settings/layouts/SettingsLayout.tsx
> +          meta.borderInShellHeader === undefined && "mb-8 border-b pb-8"
this is to prevent updating layout of pages like team members, team profile etc.

2023-09-28 18:04 UTC, PeerRich approved these changes
sweet!

2023-09-28 18:04 UTC, merged