fix: Handle removing user from org
calcom/cal.com pull request #11227
Opened 2023-09-08 10:18 UTC by sean-brydon

Loom: https://www.loom.com/share/0d938a0f1ca04d8fbc3e2b8d3b629d8f

See issue for testing steps
Note: Issue has a typo it should be removing from ORG and not sub-teams. Sub-teams work fine from what i discovered.

2023-09-08 10:18 UTC, sean-brydon commented on packages/trpc/server/routers/viewer/teams/removeMember.handler.ts
> +
Find the user by memberID so we can compare its email

2023-09-08 10:18 UTC, sean-brydon commented on packages/trpc/server/routers/viewer/teams/removeMember.handler.ts
> +    const parsedMetadata = teamMetadataSchema.parse(orgInfo.metadata);
Get metadata

2023-09-08 10:19 UTC, sean-brydon commented on packages/trpc/server/routers/viewer/teams/removeMember.handler.ts
> +    }
I put these into seperate IFs so its more read-able.

If the team is an organization & is verified & there is a autoAcceptDomain
AND
if the found users email ends with the autoAcceptDomain
Delete the user

2023-09-09 15:24 UTC, leog requested changes
LGTM, as discussed we need to remove the user completely when password and/or username is not set

2023-09-11 14:35 UTC, leog approved these changes
Thanks for taking care of the last bit, LGTM

2023-09-11 14:46 UTC, merged

2023-09-11 14:53 UTC, Udit-takkar reviewed
@sean-brydon awesome works fine for orgs but if i invite someone to team of an org then when i remove the user then the user is not deleted like in case of orgs