When creating new user, set email handle as username
calcom/cal.com pull request #11238
Opened 2023-09-08 16:42 UTC by joeauyeung

## What does this PR do?

![CleanShot 2023-09-08 at 12 41 50](https://github.com/calcom/cal.com/assets/65426560/f0f93d02-4a14-47e9-aed7-0e1d1ad704b9)

Fixes # (issue)

## Requirement/Documentation

- If there is a requirement document, please, share it here.
- If there is ab UI/UX design document, please, share it here.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

- Are there environment variables that should be set?
- What are the minimal test data to have?
- What is expected (happy path) to have (input and output)?
- Any other important info that could help to test that PR

## Mandatory Tasks

- [ ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist

- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my PR needs changes to the documentation
- I haven't checked if my changes generate no new warnings
- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

2023-09-08 17:45 UTC, leog requested changes
LGTM, although there can be a conflict with external users, it would be great if [this other ticket](https://github.com/calcom/cal.com/issues/11240) can be addressed in this PR

2023-09-08 17:48 UTC, joeauyeung commented
> LGTM, although there can be a conflict with external users, it would be great if [this other ticket](https://github.com/calcom/cal.com/issues/11240) can be addressed in this PR

Ah I knew this issue was too easy. I'll go ahead and tackle the issue you linked as well.

2023-09-11 11:13 UTC, PeerRich commented
this is awesome

2023-09-13 19:52 UTC, leog approved these changes
Changes made, thanks @joeauyeung for starting this PR

2023-09-13 23:46 UTC, merged

2024-01-30 04:44 UTC, zomars commented on packages/trpc/server/routers/viewer/teams/inviteMember/utils.ts
> +      : slugify(`${emailUser}-${emailDomain.split(".")[0]}`);
This is causing a weird edge case where there might be the possibility that the generated user may exist already. causing a prisma error. Example: we have `robert@example.com` being converted to `robert-example` username. Which already exists in prod. On production this only returns a 500 error:

On dev we get this:

```
Object { message: "\nInvalid `prisma.user.create()` invocation:\n\n\nUnique constraint failed on the fields: (`username,`)", code: -32603, data: {…} }
```