fix: org-admin delete other teams
calcom/cal.com pull request #11247
Opened 2023-09-08 23:19 UTC by alannnc

## What does this PR do?

- Adds functionality so owner/admin in orgs can delete teams they don't belong to.
- Adds code to other team listing so disband can appear as an option
- Add trpc function to org router so admin/owners can deleteTeams

Fixes #11205 

## Requirement/Documentation

- If there is a requirement document, please, share it here.
- If there is ab UI/UX design document, please, share it here.

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- Are there environment variables that should be set?
- What are the minimal test data to have?
- What is expected (happy path) to have (input and output)?
- Any other important info that could help to test that PR

## Mandatory Tasks

- [ ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist

- I haven't added tests that prove my fix is effective or that my feature works

2023-09-08 23:20 UTC, alannnc commented on packages/features/ee/organizations/pages/components/OtherTeamList.tsx
> +  const deleteTeamMutation = trpc.viewer.organizations.deleteTeam.useMutation({
Now using different method for orgs

2023-09-08 23:20 UTC, alannnc commented on packages/features/ee/organizations/pages/components/OtherTeamList.tsx
> +      await utils.viewer.organizations.listOtherTeams.invalidate();
invalidating correct listing

2023-09-08 23:20 UTC, alannnc commented on packages/features/ee/organizations/pages/components/OtherTeamListItem.tsx
> +                  </DropdownMenuItem>
Add Disband option

2023-09-11 11:44 UTC, Udit-takkar requested changes
<img width="1440" alt="Screenshot 2023-09-11 at 5 13 52 PM" src="https://github.com/calcom/cal.com/assets/53316345/a01df6ad-3b93-4413-8fcd-c7291a4ffc39">

Getting 401 when trying to disband team from /settings/organizations/teams/other/[team_id]/profile

2023-09-11 11:45 UTC, Udit-takkar commented on packages/trpc/server/routers/viewer/organizations/deleteTeam.handler.ts
> +};
i think we should use prisma.$transaction here

2023-09-11 21:45 UTC, leog commented
@alannnc was the feedback from @Udit-takkar tackled?

2023-09-12 16:07 UTC, alannnc commented
> @alannnc was the feedback from @Udit-takkar tackled?
@leog 
Changes were addressed. Good call @Udit-takkar

2023-09-12 16:09 UTC, Udit-takkar approved these changes
LGTM

2023-09-12 16:19 UTC, merged