E2E Test for CalDav Calendar
calcom/cal.com pull request #11322
Opened 2023-09-12 22:41 UTC by Ruchir28

## What does this PR do?
Adds an E2E Test for CalDav Calendar

Fixes #9372
/claim #9372

## Type of change

- [ ] Chore (refactoring code, technical debt, workflow improvements)

## How should this be tested?

- Are there environment variables that should be set?
  - `E2E_TEST_CALDAV_CALENDER_URL`
  - `E2E_TEST_CALDAV_CALENDAR_USERNAME`
  - `E2E_TEST_CALDAV_CALENDAR_PASSWORD`
  
- What is expected (happy path) to have (input and output)?
   - Run `yarn e2e caldav-calendar.e2e.ts`
   - It should successfully add the CalDav Calendar and test should pass

2023-09-12 22:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/calcom/cal.com?pullRequest=11322) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/calcom/cal.com?pullRequest=11322) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/calcom/cal.com?pullRequest=11322) it.</sub>

2023-09-15 07:01 UTC, hariombalhara commented on apps/web/playwright/caldav-calendar.e2e.ts
> +  test.skip(SHOULD_SKIP_TESTS, "Skipping due to missing test credentials");
```suggestion
  test.skip(SHOULD_SKIP_TESTS, "Skipping 'CalDav Calendar'  tests due to missing CalDav credentials");
```

2023-09-15 07:04 UTC, hariombalhara commented on apps/web/playwright/caldav-calendar.e2e.ts
> +const CALDAV_CALENDAR_PASSWORD = process.env.E2E_TEST_CALDAV_CALENDAR_PASSWORD!;
We need to document how one can get all these test credentials and after that we should create these credentials and then merge the PR. cc @zomars @keithwillcode

2023-09-15 07:59 UTC, hariombalhara requested changes
Thanks @Ruchir28 🙏
Tested locally till clicking on save button, need details on the credentials.

2023-09-15 20:33 UTC, Ruchir28 commented
Hey @hariombalhara ,
Regarding credentials, I used this [website](https://fruux.com/)
Here to get the caldav credentials 
1. Login here  [fruux.com](https://fruux.com/)
2. Then in the navbar, click on the Sync button 
3. After that there will be an option to Sync with a new device, click on that
4. Scroll to last there will be an option with  'Other Clients' & 'CalDav' mentioned
5. Complete the Registration
6. After that you will see the following info (User Name, Password, Server URL) which can be used to set the env variables for testing

2023-10-02 08:38 UTC, Ruchir28 commented
Hey @hariombalhara, 
Added the Requested changes, please review

2023-11-09 00:15 UTC, closed without merging