fix: Adding_Email_Testcases
calcom/cal.com pull request #11496
Opened 2023-09-23 09:23 UTC by Madhan13K

## What does this PR do?

Extending the Embed Code Generator tests with add Email Embed tests.

Fixes #11380

- [ x] Bug fix (non-breaking change which fixes an issue)

2023-09-23 09:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/calcom/cal.com?pullRequest=11496) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/calcom/cal.com?pullRequest=11496) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/calcom/cal.com?pullRequest=11496) it.</sub>

2023-09-24 12:09 UTC, suyash5053 commented
Hello @Madhan13K , currently your test case is failing, kindly check the issue with your test again, and commit with the refactored code.

2023-09-25 04:49 UTC, hariombalhara requested changes
Thanks @suyash5053 for the PR review and thankyou @Madhan13K for the PR. Please do the needful.

2023-09-25 06:09 UTC, Madhan13K commented
Hi all, I will check and commit again

2023-10-17 00:16 UTC, closed without merging