Fixes #11614  booker: layout shift when changing months in  spinner
calcom/cal.com pull request #11630
Opened 2023-09-30 06:57 UTC by bhargavagonugunta

## What does this PR do?
Fixes #11614 
in booker while chainging to next month the spinner animation layout shifting in spinner 

Fixes # (issue)
#11614 

https://github.com/calcom/cal.com/assets/118610174/40a618b6-65fd-43f9-816b-2861b81a1e52

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)

2023-09-30 08:04 UTC, PeerRich commented
this looks taller than before

2023-09-30 08:05 UTC, PeerRich commented on packages/features/bookings/Booker/config.ts
> +      height: "500px",
we should not be giving a fixed height. this will cause issues.

2023-09-30 08:05 UTC, PeerRich commented on packages/features/bookings/Booker/config.ts
> +      height: "500px",
same

2023-09-30 08:05 UTC, PeerRich commented on packages/features/bookings/Booker/config.ts
> +      height: "500px",
same

2023-09-30 08:05 UTC, PeerRich requested changes
fixed height is a bad idea. has to stay auto and fixed differently

2023-09-30 20:14 UTC, bhargavagonugunta commented
hi @PeerRich  Sir please look into it the problem is not about the css 

https://github.com/calcom/cal.com/assets/118610174/b24739d9-25e6-4bd2-9edb-ce482539e9c8

problem with this ramdom method 
`export const AvailableTimesSkeleton = () => (
  <div className="mt-8 flex w-[20%] flex-col only:w-full">
    {/* Random number of elements between 1 and 6. */}
    {Array.from({ length: Math.floor(Math.random() * 6) + 1 }).map((_, i) => (
      <SkeletonText className="mb-4 h-6 w-full" key={i} />
    ))}
  </div>
);
`

2023-10-02 10:34 UTC, PeerRich commented
@sean-brydon fixed this in a different branch. thank you tho!

2023-10-02 10:34 UTC, closed without merging