docs:add google credentials in example env
calcom/cal.com pull request #11695
Opened 2023-10-04 15:10 UTC by sebzz2k2

## What does this PR do?

Fixes #7887 
- Added google credentials in .env.example
- .env.appStore the credentials are already present

## Requirement/Documentation

- If there is a requirement document, please, share it here.
- If there is ab UI/UX design document, please, share it here.

## Type of change

- [x] documentation

## How should this be tested?

- Are there environment variables that should be set?
No
- What are the minimal test data to have?
new env variables in .env.example
- What is expected (happy path) to have (input and output)?
- Any other important info that could help to test that PR

## Mandatory Tasks

- [X] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist

2023-10-05 08:59 UTC, keithwillcode requested changes, later dismissed

2023-10-05 08:59 UTC, keithwillcode commented on .env.example
> +#Google OAuth credentials
Can you please add a space after # like the other comments have?

2023-10-06 09:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/calcom/cal.com?pullRequest=11695) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/calcom/cal.com?pullRequest=11695) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: Udit-takkar<br/>:x: sebzz2k2<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/calcom/cal.com?pullRequest=11695) it.</sub>

2023-10-06 09:26 UTC, Udit-takkar commented on .env.example
> +GOOGLE_API_CREDENTIALS=
@alishaz-polymath  can you also mention in the docs( https://cal.com/docs/introduction/quick-start/self-hosting/install-apps/google) that these variables are also required in .env.appStore. 

The docs only mentions .env file

2023-10-06 09:26 UTC, Udit-takkar approved these changes
LGTM

2023-11-22 11:49 UTC, merged