Fix booking failure when we dont find credential for the destination
calcom/cal.com pull request #11702
Opened 2023-10-05 04:06 UTC by hariombalhara

## What does this PR do?

Fixes # (issue)
![image](https://github.com/calcom/cal.com/assets/1780212/acfe57ea-e948-42f4-aaed-5a8f711e420b)

## Requirement/Documentation

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?
- Are there environment variables that should be set?
- What are the minimal test data to have?
- What is expected (happy path) to have (input and output)?
- Any other important info that could help to test that PR

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist
- I haven't added tests that prove my fix is effective or that my feature works

2023-10-05 05:45 UTC, hariombalhara commented on packages/core/EventManager.ts
> +          const firstCalendarCredential: (typeof destinationCalendarCredentials)[number] | undefined =
With our current configuration, TypeScript doesn't consider it possibly undefined which it could be.

2023-10-05 05:46 UTC, hariombalhara commented on packages/core/EventManager.ts
> +            loggerWithEventDetails.error(
Log the erroneous situation which was earlier silently ignored.

2023-10-05 08:09 UTC, CarinaWolli approved these changes
LGTM 👍

2023-10-05 08:13 UTC, keithwillcode requested changes
I’m concerned this will cause even more confusion if bookings start to go through but no calendar events are created. 

I think our approach to this should be different. 

- Find root cause of why/how this happened
- For event types that this would be triggered on if someone were to book, give the host a notification informing them the destination calendar is broken and they need to reconnect. 

Tagging @ciaranha here for UX suggestions.

2023-10-05 08:48 UTC, hariombalhara commented
Thanks for the review @keithwillcode @CarinaWolli .

Yeah I though about that @keithwillcode. I am just going back to the previous behaviour for now which was there before https://github.com/calcom/cal.com/pull/11668 was merged.

There is a flow to send a broken integration email which is currently disabled for a long time now. There  was [an attempt to enable it earlier ](https://github.com/calcom/cal.com/pull/8082/files), I would revive that again.

I would add that broken integration flow here as well.

I am creating a ticket to hook that broken integration flow here.

2023-10-06 12:20 UTC, hariombalhara commented
Closing this as we don't want booking to be successful when there is a calendar there and it's failing to create event in it.

2023-10-06 12:20 UTC, closed without merging

2023-10-06 12:20 UTC, keithwillcode commented
![CleanShot 2023-10-06 at 13 19 27@2x](https://github.com/calcom/cal.com/assets/2538462/f5c2c4f5-8b8c-4ccb-95e9-db66228df1df)

We are going to hold off on merging this in favor of updating the booking page to something like the following for users who have no connected calendar/credentials.