improve: hard coded zoom to app.slug
calcom/cal.com pull request #11859
Opened 2023-10-12 13:36 UTC by MeenuyD

## What does this PR do?
Use app.slug dynamically instead of hardcoding 'zoom' for improved flexibility.

Fixes #11856

2023-10-12 15:29 UTC, PeerRich commented on packages/app-store/zoomvideo/lib/VideoApiAdapter.ts
> +      app.slug,
```suggestion
      app.slug,
```

2023-10-12 15:30 UTC, PeerRich approved these changes, later dismissed

2023-10-12 16:27 UTC, joeauyeung requested changes
Thanks for your contribution @MeenuyD.

`app` does not exist in the `VideoApiAdapter` so this throws an error. We should find another way to dynamically get the app slug. We should also do this for other apps as well.

2023-10-12 16:40 UTC, MeenuyD commented
Ok I will try

2023-10-12 16:43 UTC, MeenuyD commented
Can you tell me how can we do

2023-10-18 12:09 UTC, Siddharth-2382 commented
> Can you tell me how can we do

add `import metadata from "zoomvideo/_metadata";` at the top.
replace `app.slug` with `metadata.slug`

2023-10-27 11:48 UTC, PeerRich commented
already fixed

2023-10-27 11:48 UTC, closed without merging