chore: upgrades next to 13.5.4
calcom/cal.com pull request #11869
Opened 2023-10-12 20:38 UTC by zomars

## What does this PR do?

Fixes # (issue)

## Requirement/Documentation

- If there is a requirement document, please, share it here.
- If there is ab UI/UX design document, please, share it here.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

- Are there environment variables that should be set?
- What are the minimal test data to have?
- What is expected (happy path) to have (input and output)?
- Any other important info that could help to test that PR

## Mandatory Tasks

- [ ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist

- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my PR needs changes to the documentation
- I haven't checked if my changes generate no new warnings
- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

2023-10-12 20:38 UTC, zomars commented
Current dependencies on/for this PR:
* main
  * **PR #11869** <a href="https://app.graphite.dev/github/pr/calcom/cal.com/11869" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/calcom/cal.com/11869?utm_source=stack-comment).

2023-10-12 20:53 UTC, PeerRich approved these changes, later dismissed

2023-10-14 08:50 UTC, PeerRich approved these changes, later dismissed

2023-10-14 08:53 UTC, PeerRich approved these changes, later dismissed

2023-10-14 10:36 UTC, PeerRich approved these changes

2023-10-14 11:50 UTC, PeerRich requested changes
usage of useSearchParams has changed

2023-10-17 09:34 UTC, PeerRich commented
useSearchParam needs migration

2023-10-17 09:34 UTC, closed without merging