fix: meeting url should be available only when its confirmed
calcom/cal.com pull request #11914
Opened 2023-10-16 11:18 UTC by anikdhabal

## What does this PR do?

 Meeting url should be available only when its confirmed

Fixes #11857 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)

2023-10-20 07:52 UTC, CarinaWolli requested changes

2023-10-20 07:52 UTC, CarinaWolli commented on packages/emails/src/components/LocationInfo.tsx
> +          meetingUrl && !props.calEvent.requiresConfirmation ? (
This is also true for the email when the event gets confirmed. This email should include the meeting URL

2023-11-11 00:15 UTC, closed without merging

2024-05-10 22:20 UTC, anikdhabal commented
@keithwillcode @CarinaWolli this is issue is still unsolved and I've fixed it in my local setup. Can you reopen this Pr please?

2024-05-13 14:41 UTC, anikdhabal commented
@keithwillcode @CarinaWolli this is issue is still unsolved and I've fixed it in my local setup. Can you reopen this Pr please?