feat: managed event types v2
calcom/cal.com pull request #11958
Opened 2023-10-17 20:52 UTC by leog

## What does this PR do?

Implements Managed Event Types v2 where the event owner/team admin can discretely select which field to lock or unlock in a managed event type.

<kbd><img src="https://github.com/calcom/cal.com/assets/467258/28379efe-18e6-4782-a0b7-63ccda794965" /></kbd>

<kbd><img src="https://github.com/calcom/cal.com/assets/467258/657e8a63-3519-4526-af55-b86bf9bdb889" /></kbd>

<kbd><img src="https://github.com/calcom/cal.com/assets/467258/4e9c4149-7a9c-42a0-b600-08c3631aeac4" /></kbd>

<kbd><img src="https://github.com/calcom/cal.com/assets/467258/c9edc1f6-ae58-4667-b4f9-d3b3a37b531d" /></kbd>

@ciaranha just FYI, went for the badge with title and the switch as it was the one that can be universally applied to any type of field, whether is a text or a setting toggle.

Talked to @PeerRich and he instructed me to tag you @CarinaWolli for this in order to have you take over MET.

Pending tasks: 
 - [ ] E2E tests

Fixes #11941 

## Type of change

- [X] New feature (non-breaking change which adds functionality)

## How should this be tested?

Create a team and then a managed event type. Upon getting to the event type settings page, see the different toggles to lock/unlock them.

2023-10-17 20:55 UTC, leog commented on apps/web/components/eventtype/EventAdvancedTab.tsx
> +import type { EventTypeSetupProps } from "pages/event-types/[type]";
Moved FormValues to the features/lib to be able to use it from there too and avoid crossing boundaries between web app and the library

2023-10-17 20:56 UTC, leog commented on apps/web/components/eventtype/EventAdvancedTab.tsx
> +  const { shouldLockDisableProps } = useLockedFieldsManager(eventType, formMethods, t);
We now need form methods in order to set discretely the different fields in the event type metadata

2023-10-17 20:56 UTC, leog commented on apps/web/components/eventtype/EventAppsTab.tsx
> +import type { FormValues } from "@calcom/features/eventtypes/lib/types";
Moved FormValues to the features/lib to be able to use it from there too and avoid crossing boundaries between web app and the library

2023-10-17 20:57 UTC, leog commented on apps/web/components/eventtype/EventAppsTab.tsx
> -          {...shouldLockDisableProps("apps")}
Removed switch from each app as it referred to the general apps locked state now present in the alert

2023-10-17 20:58 UTC, leog commented on apps/web/components/eventtype/EventAppsTab.tsx
> +  const appsDisableProps = shouldLockDisableProps("apps", { simple: true });
`simple` flag makes the lock/unlock indicator to only show the switch which is the one needed for the alert

2023-10-17 20:58 UTC, leog commented on apps/web/components/eventtype/EventAppsTab.tsx
> -            {...shouldLockDisableProps("apps")}
Removed switch from each app as it referred to the general apps locked state now present in the alert

2023-10-17 20:58 UTC, leog commented on apps/web/components/eventtype/EventAppsTab.tsx
> +          {(isManagedEventType || isChildrenManagedEventType) && (
Showing the alert for either admin or member to show lock state for apps

2023-10-17 20:59 UTC, leog commented on apps/web/components/eventtype/EventAppsTab.tsx
> -                  {...shouldLockDisableProps("apps")}
Removed switch from each app as it referred to the general apps locked state now present in the alert

2023-10-17 20:59 UTC, leog commented on apps/web/components/eventtype/EventAvailabilityTab.tsx
> +import type { AvailabilityOption, FormValues } from "@calcom/features/eventtypes/lib/types";
Moved FormValues to the features/lib to be able to use it from there too and avoid crossing boundaries between web app and the library

2023-10-17 20:59 UTC, leog commented on apps/web/components/eventtype/EventAvailabilityTab.tsx
> -};
Also moved to the features/lib to be able to use it from there too and avoid crossing boundaries between web app and the library

2023-10-17 21:00 UTC, leog commented on apps/web/components/eventtype/EventLimitsTab.tsx
> +
This was removed recently to allow these fields to be unlocked for v1, now with v2 we need them as the team admin can discretely select their state

2023-10-17 21:01 UTC, leog commented on apps/web/components/eventtype/EventLimitsTab.tsx
> +            </Label>
This was removed recently to allow these fields to be unlocked for v1, now with v2 we need them as the team admin can discretely select their state

2023-10-17 21:01 UTC, leog commented on apps/web/components/eventtype/EventLimitsTab.tsx
> +                    isDisabled={shouldLockDisableProps("bookingLimits").disabled}
This was removed recently to allow these fields to be unlocked for v1, now with v2 we need them as the team admin can discretely select their state

2023-10-17 21:01 UTC, leog commented on apps/web/components/eventtype/EventLimitsTab.tsx
> +            </Label>
This was removed recently to allow these fields to be unlocked for v1, now with v2 we need them as the team admin can discretely select their state

2023-10-17 21:01 UTC, leog commented on apps/web/components/eventtype/EventLimitsTab.tsx
> +                    isDisabled={shouldLockDisableProps("bookingLimits").disabled}
This was removed recently to allow these fields to be unlocked for v1, now with v2 we need them as the team admin can discretely select their state

2023-10-17 21:01 UTC, leog commented on apps/web/components/eventtype/EventLimitsTab.tsx
> +            />
This was removed recently to allow these fields to be unlocked for v1, now with v2 we need them as the team admin can discretely select their state

2023-10-17 21:01 UTC, leog commented on apps/web/components/eventtype/EventLimitsTab.tsx
> +            </Label>
This was removed recently to allow these fields to be unlocked for v1, now with v2 we need them as the team admin can discretely select their state

2023-10-17 21:01 UTC, leog commented on apps/web/components/eventtype/EventLimitsTab.tsx
> +                    isDisabled={shouldLockDisableProps("slotInterval").disabled}
This was removed recently to allow these fields to be unlocked for v1, now with v2 we need them as the team admin can discretely select their state

2023-10-17 21:01 UTC, leog commented on apps/web/components/eventtype/EventLimitsTab.tsx
> +              {...bookingLimitsLocked}
This was removed recently to allow these fields to be unlocked for v1, now with v2 we need them as the team admin can discretely select their state

2023-10-17 21:01 UTC, leog commented on apps/web/components/eventtype/EventLimitsTab.tsx
> +                />
This was removed recently to allow these fields to be unlocked for v1, now with v2 we need them as the team admin can discretely select their state

2023-10-17 21:01 UTC, leog commented on apps/web/components/eventtype/EventLimitsTab.tsx
> +              {...durationLimitsLocked}
This was removed recently to allow these fields to be unlocked for v1, now with v2 we need them as the team admin can discretely select their state

2023-10-17 21:01 UTC, leog commented on apps/web/components/eventtype/EventLimitsTab.tsx
> +                  disabled={durationLimitsLocked.disabled}
This was removed recently to allow these fields to be unlocked for v1, now with v2 we need them as the team admin can discretely select their state

2023-10-17 21:01 UTC, leog commented on apps/web/components/eventtype/EventLimitsTab.tsx
> +              {...periodTypeLocked}
This was removed recently to allow these fields to be unlocked for v1, now with v2 we need them as the team admin can discretely select their state

2023-10-17 21:01 UTC, leog commented on apps/web/components/eventtype/EventLimitsTab.tsx
> +                  ).map((period) => {
This was removed recently to allow these fields to be unlocked for v1, now with v2 we need them as the team admin can discretely select their state

2023-10-17 21:02 UTC, leog commented on apps/web/components/eventtype/EventLimitsTab.tsx
> +                              disabled={periodTypeLocked.disabled}
This was removed recently to allow these fields to be unlocked for v1, now with v2 we need them as the team admin can discretely select their state

2023-10-17 21:02 UTC, leog commented on apps/web/components/eventtype/EventLimitsTab.tsx
> +                              isDisabled={periodTypeLocked.disabled}
This was removed recently to allow these fields to be unlocked for v1, now with v2 we need them as the team admin can discretely select their state

2023-10-17 21:02 UTC, leog commented on apps/web/components/eventtype/EventLimitsTab.tsx
> +                                  disabled={periodTypeLocked.disabled}
This was removed recently to allow these fields to be unlocked for v1, now with v2 we need them as the team admin can discretely select their state

2023-10-17 21:02 UTC, leog commented on apps/web/components/eventtype/EventLimitsTab.tsx
> +        {...offsetStartLockedProps}
This was removed recently to allow these fields to be unlocked for v1, now with v2 we need them as the team admin can discretely select their state

2023-10-17 21:02 UTC, leog commented on apps/web/components/eventtype/EventLimitsTab.tsx
> +            {...offsetStartLockedProps}
This was removed recently to allow these fields to be unlocked for v1, now with v2 we need them as the team admin can discretely select their state

2023-10-17 21:02 UTC, leog commented on apps/web/components/eventtype/EventSetupTab.tsx
> +import type { FormValues } from "@calcom/features/eventtypes/lib/types";
Moved FormValues to the features/lib to be able to use it from there too and avoid crossing boundaries between web app and the library

2023-10-17 21:03 UTC, leog commented on apps/web/components/eventtype/EventAppsTab.tsx
> +    methods,
We now need form methods in order to set discretely the different fields in the event type metadata

2023-10-17 21:03 UTC, leog commented on apps/web/components/eventtype/EventAvailabilityTab.tsx
> +    formMethods,
We now need form methods in order to set discretely the different fields in the event type metadata

2023-10-17 21:03 UTC, leog commented on apps/web/components/eventtype/EventLimitsTab.tsx
> +  const { shouldLockIndicator, shouldLockDisableProps } = useLockedFieldsManager(eventType, formMethods, t);
This was removed recently to allow these fields to be unlocked for v1, now with v2 we need them as the team admin can discretely select their state

2023-10-17 21:04 UTC, leog commented on apps/web/components/eventtype/EventSetupTab.tsx
> +    useLockedFieldsManager(eventType, formMethods, t);
We now need form methods in order to set discretely the different fields in the event type metadata

2023-10-17 21:04 UTC, leog commented on apps/web/components/eventtype/EventSetupTab.tsx
> +            <Label htmlFor="editor">
Needed to not make clicking the label activate the lock/unlock switch

2023-10-17 21:04 UTC, leog commented on apps/web/components/eventtype/EventSetupTab.tsx
> +            <Skeleton as={Label} loadingClassName="w-16" htmlFor="locations">
Needed to not make clicking the label activate the lock/unlock switch

2023-10-17 21:05 UTC, leog commented on apps/web/components/eventtype/EventTeamTab.tsx
> +import type { FormValues } from "@calcom/features/eventtypes/lib/types";
Moved FormValues to the features/lib to be able to use it from there too and avoid crossing boundaries between web app and the library

2023-10-17 21:05 UTC, leog commented on apps/web/components/eventtype/EventTypeSingleLayout.tsx
> +import type { FormValues, AvailabilityOption } from "@calcom/features/eventtypes/lib/types";
Moved FormValues to the features/lib to be able to use it from there too and avoid crossing boundaries between web app and the library

2023-10-17 21:05 UTC, leog commented on apps/web/components/eventtype/EventTypeSingleLayout.tsx
> +    formMethods,
We now need form methods in order to set discretely the different fields in the event type metadata

2023-10-17 21:05 UTC, leog commented on apps/web/components/eventtype/EventWebhooksTab.tsx
> +  const formMethods = useFormContext<FormValues>();
We now need form methods in order to set discretely the different fields in the event type metadata

2023-10-17 21:05 UTC, leog commented on apps/web/components/eventtype/EventWebhooksTab.tsx
> +                          {t("locked_by_team_admin")}
More specific string title

2023-10-17 21:05 UTC, leog commented on apps/web/components/eventtype/RecurringEventController.tsx
> +import type { FormValues } from "@calcom/features/eventtypes/lib/types";
Moved FormValues to the features/lib to be able to use it from there too and avoid crossing boundaries between web app and the library

2023-10-17 21:06 UTC, leog commented on apps/web/components/eventtype/RecurringEventController.tsx
> +  const { shouldLockDisableProps } = useLockedFieldsManager(eventType, formMethods, t);
We now need form methods in order to set discretely the different fields in the event type metadata

2023-10-17 21:06 UTC, leog commented on apps/web/components/eventtype/RequiresConfirmationController.tsx
> +import type { FormValues } from "@calcom/features/eventtypes/lib/types";
Moved FormValues to the features/lib to be able to use it from there too and avoid crossing boundaries between web app and the library

2023-10-17 21:06 UTC, leog commented on apps/web/components/eventtype/RequiresConfirmationController.tsx
> +  const { shouldLockDisableProps } = useLockedFieldsManager(eventType, formMethods, t);
We now need form methods in order to set discretely the different fields in the event type metadata

2023-10-17 21:06 UTC, leog commented on apps/web/pages/event-types/[type]/index.tsx
> -
Moved FormValues to the features/lib to be able to use it from there too and avoid crossing boundaries between web app and the library

2023-10-17 21:07 UTC, leog commented on packages/features/ee/managed-event-types/hooks/useLockedFieldsManager.tsx
> +    </Tooltip>
New lock/unlock indicator with switch with the possibility to just show the switch for alerts using the `simple` flag

2023-10-17 21:08 UTC, leog commented on packages/features/ee/managed-event-types/hooks/useLockedFieldsManager.tsx
> +  const fieldStates: Record<string, [boolean, Dispatch<SetStateAction<boolean>>]> = {};
Storing field lock/unlock state to be used along the different functions to show a consistent state between all forms

2023-10-17 21:09 UTC, leog commented on packages/features/ee/managed-event-types/hooks/useLockedFieldsManager.tsx
> +  };
In charge of using form methods to store the unlocked fields in the event type metadata. When locked, it gets removed.

2023-10-17 21:09 UTC, leog commented on packages/features/ee/managed-event-types/hooks/useLockedFieldsManager.tsx
> +    return locked;
Refactored initial state into its own function to be used in different places

2023-10-17 21:09 UTC, leog commented on packages/features/ee/workflows/components/EventWorkflowsTab.tsx
> +import type { FormValues } from "@calcom/features/eventtypes/lib/types";
Moved FormValues to the features/lib to be able to use it from there too and avoid crossing boundaries between web app and the library

2023-10-17 21:09 UTC, leog commented on packages/features/ee/workflows/components/EventWorkflowsTab.tsx
> +                ? "locked_by_team_admin"
More specific string title

2023-10-17 21:10 UTC, leog commented on packages/features/ee/workflows/components/WorkflowDetailsPage.tsx
> +            )
Added this filter to avoid having members select managed event types as the target for workflows when workflows are locked.

2023-10-17 21:11 UTC, leog commented on packages/ui/components/alert/Alert.tsx
> +        severity === "green" && "bg-success text-success",
Added this one to be able to show lock/unlock state in workflows and apps alert

2023-10-17 21:11 UTC, leog commented on packages/ui/components/form/switch/SettingsToggle.tsx
> +                    htmlFor="">
Needed to not make clicking the label activate the lock/unlock switch

2023-10-17 21:12 UTC, leog commented on packages/ui/components/form/switch/Switch.tsx
> +    small?: boolean;
Having a way to shrink the switch to be shown in the lock/unlock indicator in each field

2023-10-19 12:37 UTC, CarinaWolli commented on packages/features/ee/workflows/components/EventWorkflowsTab.tsx
> +              title={isChildrenManagedEventType ? t("locked_by_team_admin") : t("locked_for_members")}
I think it's better to not allow unlocking workflows. I changed the alert: 
<img width="991" alt="Screenshot 2023-10-19 at 14 36 09" src="https://github.com/calcom/cal.com/assets/30310907/1e01e76b-a8af-4b82-9a19-f95c79801267">
<img width="992" alt="Screenshot 2023-10-19 at 14 36 25" src="https://github.com/calcom/cal.com/assets/30310907/e44f4c02-86f1-43eb-8701-9b2908f3413b">

2023-10-19 12:37 UTC, CarinaWolli commented on packages/features/ee/workflows/components/EventWorkflowsTab.tsx
> +          (!workflow.teamId || eventType.teamId === workflow.teamId) &&
Make sure to only show team workflows for team event types

2023-10-19 13:31 UTC, CarinaWolli commented on packages/features/ee/workflows/components/EventWorkflowsTab.tsx
> +      setSortedWorkflows(allSortedWorkflows);
If it is locked we only want to show active workflows. Which should only be active team workflows and no personal workflows

2023-11-08 08:55 UTC, alishaz-polymath requested changes
![image](https://github.com/calcom/cal.com/assets/52925846/30d6f505-d101-426b-b67d-a916807d4485)
- More than a few toggles in the advanced tab throws this error:

![image](https://github.com/calcom/cal.com/assets/52925846/84b1db61-d240-45fd-87ec-f3765a3809c5)

- Before event, after event and limit booking frequency all toggle together, doesn't matter which of them is toggled on

![image](https://github.com/calcom/cal.com/assets/52925846/95055ca2-efaf-4ca1-832c-56e2ff75aac6)

2023-11-10 13:32 UTC, alishaz-polymath commented
Closing in favor of #12320 which continues on this work

2023-11-10 13:32 UTC, closed without merging