11642 app shimmer video
calcom/cal.com pull request #12159
Opened 2023-10-31 06:30 UTC by vikcodes

## What does this PR do?

Fixes # (issue)

## Requirement/Documentation

- If there is a requirement document, please, share it here.
- If there is ab UI/UX design document, please, share it here.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

- Are there environment variables that should be set?
- What are the minimal test data to have?
- What is expected (happy path) to have (input and output)?
- Any other important info that could help to test that PR

## Mandatory Tasks

- [ ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist

- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my PR needs changes to the documentation
- I haven't checked if my changes generate no new warnings
- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

2023-10-31 06:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/calcom/cal.com?pullRequest=12159) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/calcom/cal.com?pullRequest=12159) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: vikcorporations<br/>:x: pathaksarvesh<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/calcom/cal.com?pullRequest=12159) it.</sub>

2023-11-06 22:53 UTC, joeauyeung submitted a review, later dismissed
Tested and working on Cal.com side

2023-11-07 06:06 UTC, hariombalhara commented on packages/app-store/shimmervideo/config.json
Removed `dirName` as it's legacy. `dirName` is considered same as `slug` in that case for legacy code using dirName.

Also, modified slug to be as `shimmervideo` which is same as the actual dir name.

2023-11-07 06:06 UTC, hariombalhara commented on packages/app-store/shimmervideo/config.json
cc @joeauyeung

2023-11-07 06:58 UTC, hariombalhara commented on packages/core/EventManager.ts
> +      .filter((cred) => cred.type.endsWith("_video") || cred.type.endsWith("_conferencing"))
I am not sure why it's needed @joeauyeung as we are still using _video postfix for conferencing apps and using the same for shimmer app too . Leaving it as is for now.

2023-11-07 07:04 UTC, hariombalhara commented on packages/app-store/shimmervideo/lib/VideoApiAdapter.ts
> +  const response = await fetch(`https://api.daily.co/v1${endpoint}`, {
Why are we hitting daily API from shimmer video app. If shimmer video app uses daily itself, it shouldn't depend on we hitting daily API. We should contact shimmer app only for that. Shimmer app can do that same at it's backend

2023-11-07 07:07 UTC, hariombalhara commented
@vikcodes Now env variables are removed and configurable from UI. See https://www.loom.com/share/77591402656d4aa2a15fe76bb0ae2a3a

2023-11-07 07:13 UTC, hariombalhara requested changes
Thanks @vikcodes. I have one concern before I can merge it.

I would not recommend hitting daily endpoint from shimmer app. Let's proxy that endpoint from some shimmer endpoint only

2023-11-08 19:59 UTC, joeauyeung approved these changes
Talking with the team, we're going to approve now to get it on production and then refactor at a later date.

2023-11-09 08:33 UTC, hariombalhara approved these changes

2023-11-09 08:33 UTC, merged