Fix team link in request-reschedule
calcom/cal.com pull request #12261
Opened 2023-11-07 12:22 UTC by hariombalhara

## What does this PR do?

Fixes # (issue)

## Requirement/Documentation

- If there is a requirement document, please, share it here.
- If there is ab UI/UX design document, please, share it here.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

- Are there environment variables that should be set?
- What are the minimal test data to have?
- What is expected (happy path) to have (input and output)?
- Any other important info that could help to test that PR

## Mandatory Tasks

- [ ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist

- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my PR needs changes to the documentation
- I haven't checked if my changes generate no new warnings
- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

2023-11-07 12:23 UTC, hariombalhara commented
Current dependencies on/for this PR:
* main
  * **PR #12261** <a href="https://app.graphite.dev/github/pr/calcom/cal.com/12261" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/calcom/cal.com/12261?utm_source=stack-comment).

2023-11-08 10:36 UTC, hariombalhara commented on apps/web/test/utils/bookingScenario/test.ts
> +  _testWithAndWithoutOrg(description, fn, timeout, "only");
It was a bug that got caught due to TS checks

2023-11-08 10:36 UTC, hariombalhara commented on packages/features/bookings/lib/handleNewBooking/test/fresh-booking.test.ts
> +          expectBrokenIntegrationEmails({ organizer, emails });
Unnecessary param

2023-11-08 10:41 UTC, hariombalhara reviewed
Self reviewed

2023-11-08 10:41 UTC, hariombalhara commented on packages/core/builders/CalendarEvent/builder.ts
> +        slug = `team/${eventType.team?.slug}/${eventType.slug}`;
/ is already there in `bookerUrl` and `WEBAPP_URL`

2023-11-08 10:41 UTC, hariombalhara commented on apps/web/test/handlers/requestReschedule.test.ts
> +        bookNewTimePath: "/team/team-1/event-type-1",
This is the regression test.

2023-11-10 18:50 UTC, CarinaWolli requested changes, later dismissed
Fix looks good, but Unit tests are failing: 

<img width="1002" alt="Screenshot 2023-11-10 at 13 47 12" src="https://github.com/calcom/cal.com/assets/30310907/98a4a8d2-135b-49f5-9cf7-411d1fcaa633">

2023-11-13 11:28 UTC, hariombalhara commented
Thanks @CarinaWolli. Fixed the import paths that got broken due to recent merge of main

2023-11-14 20:23 UTC, zomars approved these changes
Nice work @hariombalhara 🙏🏽

2023-11-14 20:23 UTC, merged