feat: integrate formbricks in help feedback box
calcom/cal.com pull request #12276
Opened 2023-11-08 05:09 UTC by ShubhamPalriwala

## What does this PR do?
The Help Feedback Box currently sends the data to our email service. This PR sends it to a pre-created Formbricks Survey for easier visibility and availability in the Formbricks App.

![image](https://github.com/ShubhamPalriwala/cal.com/assets/55556994/08ef123d-3840-4680-8166-e25e2857c88a)

We use the `@formbricks/api` package for minimal dependencies and create a response in the app.

## Requirement/Documentation
We introduce 2 new environment variables that needs to be set:
1. `FORMBRICKS` in the form of `[apiHost]+[environmentId]`
2. `FORMBRICKS_FEEDBACK_SURVEY_ID` in the form of `surveyId`

For testing, use:
```
FORMBRICKS=https://app.formbricks.com+cloob69in56synz0fg6l5vqmx
FORMBRICKS_FEEDBACK_SURVEY_ID=cloob6fn356u0nz0fl0mm1wa5
```

Before merging to main, 
- [ ] Create a Survey on Formbricks
- [ ] Create 2 questions (1 Open Text with Question ID as: `formbricks-share-comments-question` and 1 Rating question with Range of 4  and ID as `formbricks-rating-question` )

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## How should this be tested?

- Set the env variable as suggested above
- Fill the Feedback Box inside the Help Button
- View in the Formbricks App and the response should be reflected

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

2023-11-08 05:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/calcom/cal.com?pullRequest=12276) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/calcom/cal.com?pullRequest=12276) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/calcom/cal.com?pullRequest=12276) it.</sub>

2023-11-08 09:20 UTC, PeerRich approved these changes
looks very good and minimal, will try today!

2023-11-08 09:23 UTC, PeerRich commented
lets also add userid and email

2023-11-08 09:32 UTC, PeerRich commented
added .env to both prod and staging, added formbricks survey with the question ID

2023-11-08 09:32 UTC, PeerRich commented on .env.example
> +FORMBRICKS=
does this have to be FORMBRICKS or NEXT_PUBLIC_FORMBRICKS ?

also, doesn't this need to be added to turbo.json?

2023-11-08 10:07 UTC, alishaz-polymath submitted a review, later dismissed
Tested, works!
NIT: We could also add userId and/or email as a hidden field (auto-populates internally).

Thank you for your contribution 🚀

2023-11-09 08:55 UTC, ShubhamPalriwala commented
Hey, thanks for the quick reviews and testing! Glad it works for everyone 🚀 
We're currently updating our API endpoint to support the linking of userId and email as well via the API. Will ping the reviewers here once the PR is again ready for review

2023-11-09 10:43 UTC, PeerRich commented
draft until API is ready for username and email

2023-11-11 11:18 UTC, PeerRich approved these changes, later dismissed
env and keys added to vercel prod

2023-11-16 18:26 UTC, zomars commented on .env.example
> +FORMBRICKS=
Not quite since is used on the server only. But I would go with something more descriptive.

```suggestion
FORMBRICKS_URL=
```

2023-11-16 18:52 UTC, zomars requested changes, later dismissed
Thank you for your contribution 🙏 

Quick note. Let's prioritize legibility over clever code in this case. Left some suggestions to address.

2023-11-16 18:52 UTC, zomars commented on .env.example
> +FORMBRICKS=
```suggestion
# Formbricks Experience Management Integration
FORMBRICKS_HOST_URL=
FORMBRICKS_ENVIRONMENT_ID=
```

2023-11-16 18:52 UTC, zomars commented on packages/lib/formbricks.ts
> +const [apiHost, environmentId] = process.env.FORMBRICKS.split("+");
```suggestion
if (!process.env. FORMBRICKS_HOST_URL || !process.env. FORMBRICKS_ENVIRONMENT_ID) throw new Error("Missing FORMBRICKS variables");
const apiHost = process.env.FORMBRICKS_HOST_URL;
const environmentId = process.env.FORMBRICKS_ENVIRONMENT_ID;
```

2023-11-16 18:52 UTC, zomars commented on packages/trpc/server/routers/loggedInViewer/submitFeedback.handler.ts
> +  if (process.env.FORMBRICKS) sendFeedbackFormbricks(rating, comment);
```suggestion
  if (process.env. FORMBRICKS_HOST_URL && process.env. FORMBRICKS_ENVIRONMENT_ID) sendFeedbackFormbricks(rating, comment);
```

2023-11-16 18:52 UTC, zomars commented on turbo.json
> +    "FORMBRICKS_FEEDBACK_SURVEY_ID",
```suggestion
    "FORMBRICKS_ENVIRONMENT_ID",
    "FORMBRICKS_FEEDBACK_SURVEY_ID",
    "FORMBRICKS_HOST_URL",
```

2023-11-22 11:31 UTC, ShubhamPalriwala commented
Hey folks, the PR is once again ready for review 🚀 We now add the username of the person as a `userId` as a person and attach it to the response submitted! We do not support the addition of custom attributes in the same response creation API yet hence going ahead with just the username for now. Please take a look 🙏🏼 

Also addressed the env var changes as suggested

2023-11-22 12:01 UTC, PeerRich commented on .env.example
> +FORMBRICKS_HOST_URL=
```suggestion
FORMBRICKS_HOST_URL=https://app.formbricks.com
```

2023-11-22 12:09 UTC, ShubhamPalriwala commented
update, discussed with @mattinannt and restructuring things a bit

2023-11-22 13:25 UTC, mattinannt commented
@PeerRich During our testing, we discovered a potential security issue with the Formbricks API updates we pushed to enable this PR. We will update you as soon as this is fixed. You can review this before then, but please don't merge yet.

2023-12-11 20:38 UTC, PeerRich submitted a review, later dismissed

2023-12-11 20:42 UTC, zomars approved these changes
![LGTM](https://media3.giphy.com/media/NytMLKyiaIh6VH9SPm/200.gif)

2023-12-11 20:42 UTC, zomars commented
We need to fix types tho 
<img width="902" alt="image" src="https://github.com/calcom/cal.com/assets/3504472/c45c1194-b602-4cc8-88ad-e5a42f41cee7">

2023-12-11 20:43 UTC, zomars requested changes, later dismissed
Type checks are failing

2023-12-12 03:03 UTC, ShubhamPalriwala commented
Thanks for the feedback @zomars, I've made the type fixes (apologies for overlooking it) and tested the flow again 💪🏼 
cc: @PeerRich

2023-12-31 19:11 UTC, PeerRich approved these changes

2024-01-02 14:08 UTC, merged