chore: auto verify OTP whenever user enters 6 digits OTP instead of waiting for them to click on verify button
calcom/cal.com pull request #12326
Opened 2023-11-11 08:28 UTC by harshithpabbati

## What does this PR do?

This PR is to auto-verify when there are exactly 6 number of non-empty digits in the VerifyCodeDialog component.

Fixes #12130 

https://www.loom.com/share/1dd7ed45d70f4db99798379d3b7d6ed6

## Requirement/Documentation

- If there is a requirement document, please, share it here.
- If there is ab UI/UX design document, please, share it here.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Chore (refactoring code, technical debt, workflow improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

- Are there environment variables that should be set?
- What are the minimal test data to have?
- What is expected (happy path) to have (input and output)?
- Any other important info that could help to test that PR

## Mandatory Tasks

- [ ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist

- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my PR needs changes to the documentation
- I haven't checked if my changes generate no new warnings
- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

2023-11-11 08:28 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/calcom/cal.com?pullRequest=12326) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/calcom/cal.com?pullRequest=12326) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/calcom/cal.com?pullRequest=12326) it.</sub>

2023-11-17 15:45 UTC, supalarry requested changes
Thanks for the PR Harshith!

1. I tested it locally with incorrect OTP code and the loading gets stuck

<img width="925" alt="Screenshot 2023-11-17 at 16 40 35" src="https://github.com/calcom/cal.com/assets/42170848/bb90972f-fbcc-4126-bcdf-5c02c88b2212">

If you add log on line 64 and check console you see it being logged over and over again, so there might be infinite re-rendering happening or something alike.

2. Next, if the authentication happens automatically, then it would be good to remove the "Verify" button and just leave the "Close" button. I see no instance where having "Verify"  button would be useful.

2023-11-18 16:24 UTC, harshithpabbati commented
<img width="519" alt="Screenshot 2023-11-18 at 9 32 19 PM" src="https://github.com/calcom/cal.com/assets/43822585/dac4fab0-8f71-4273-b673-321e49b38da2">

I just made the change and also removed the verify button.

2023-11-27 10:50 UTC, supalarry approved these changes
Thank you for the PR, awesome stuff! Tested locally and looks good!

2023-12-07 21:08 UTC, merged