Fix - identifer
calcom/cal.com pull request #12426
Opened 2023-11-18 16:46 UTC by sean-brydon

Fixes verify

2023-11-18 16:46 UTC, sean-brydon commented on packages/trpc/server/routers/viewer/auth/_router.tsx
> +        req,
Add req to pass through

2023-11-18 16:46 UTC, sean-brydon commented on packages/trpc/server/routers/viewer/auth/sendVerifyEmailCode.handler.ts
> +  const identifer = req ? getIP(req) : input.email;
Req shouldnt be undefined but can be on a type level

2023-11-18 16:52 UTC, keithwillcode requested changes, later dismissed
Nice thanks for submitting so quickly. Just a small typo

2023-11-18 16:52 UTC, keithwillcode commented on packages/trpc/server/routers/viewer/auth/sendVerifyEmailCode.handler.ts
> +    identifier: `emaiLVerifyByCode.${identifer}`,
L is capitalized

2023-11-20 08:43 UTC, Udit-takkar approved these changes
LGTM. (Fixed type error)

2023-11-20 13:28 UTC, merged