chore: Add team invite tests
calcom/cal.com pull request #12425
Opened 2023-11-18 13:34 UTC by Amit91848

## What does this PR do?

Fixes #12386 
@sean-brydon 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Chore (refactoring code, technical debt, workflow improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

`yarn e2e team/`

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

2023-11-20 11:12 UTC, sean-brydon requested changes
Damn overall amazing job! - Lets make these locators a bit more specific so we dont accidentally break the tests when using classes

2023-11-20 11:12 UTC, sean-brydon commented on apps/web/playwright/team/team-invitation.e2e.ts
> +      await expect(newPage.locator(".text-red-700")).toHaveCount(3);
I prefer if we were a bit more specific on this locator - text-red-700 is easily added else where and would break this test

2023-11-20 11:12 UTC, sean-brydon commented on apps/web/playwright/team/team-invitation.e2e.ts
> +      await expect(inviteLinkPage.locator(".text-red-700")).toHaveCount(2);
Same here

2023-11-20 11:46 UTC, Udit-takkar commented on packages/features/ee/teams/components/MemberInvitationModal.tsx
> +      console.log(window.E2E_CLIPBOARD_VALUE);
NIT: remove this log

2023-11-20 11:49 UTC, Udit-takkar commented on apps/web/playwright/team/team-invitation.e2e.ts
> +      await page.locator('button:text("Send Invite")').click();
we can use localize from testUtils instead of hard coding the text.

2023-11-21 16:37 UTC, Amit91848 commented
Made changes @sean-brydon @Udit-takkar

2023-11-22 11:10 UTC, sean-brydon approved these changes
LGTM

2023-11-22 11:26 UTC, merged