fix: Dynamic duration was always overwritten with the default (30)
calcom/cal.com pull request #12444
Opened 2023-11-20 16:07 UTC by emrysal

## What does this PR do?

multipleDuration useEvent was never set in case of dynamic event - so couldn't be used in the booker store.

2023-11-22 16:15 UTC, Udit-takkar reviewed
@emrysal I am seeing wrong slots when i changed the duration from 30 to 60.


<img width="1123" alt="Screenshot 2023-11-22 at 9 40 42 PM" src="https://github.com/calcom/cal.com/assets/53316345/9210176d-c39f-4cfa-a1cc-b83de4f37419">

<img width="1511" alt="Screenshot 2023-11-22 at 9 42 31 PM" src="https://github.com/calcom/cal.com/assets/53316345/8ad6c9d3-bef2-4d4d-9d2d-549c43fbf928">

and when I tried to book the slot (10:30Am-11:30AM 60min). I am getting error

Could not book the meeting.
Some of the hosts are unavailable for booking.

http://localhost:3000/pro+free

'pro' has a google calendar connected which has a busy event till 2:00 PM 
'free' doesn't have any calendar connected.

2023-11-28 18:44 UTC, zomars requested changes
We got some type check uh-ohs in there

2023-11-29 09:29 UTC, ThyMinimalDev submitted a review, later dismissed
I believe type errors were not linked to this pr, double checking Udit comment before approving

2023-11-29 09:51 UTC, ThyMinimalDev commented
> @emrysal I am seeing wrong slots when i changed the duration from 30 to 60.
> 
> <img alt="Screenshot 2023-11-22 at 9 40 42 PM" width="1123" src="https://private-user-images.githubusercontent.com/53316345/284968098-9210176d-c39f-4cfa-a1cc-b83de4f37419.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyNTE2OTgsIm5iZiI6MTcwMTI1MTM5OCwicGF0aCI6Ii81MzMxNjM0NS8yODQ5NjgwOTgtOTIxMDE3NmQtYzM5Zi00Y2ZhLWExY2MtYjgzZGU0ZjM3NDE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDA5NDk1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0Y2UyYjhiMWJmZmMxZjMyNzRjMGVlOWI1YzU1ZDliNWY4NGQxY2RkOTY0MWIzYjAyODY4ODU1MzAyZGI2OTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mGf1nSO8oQz-_HoaBw4DCFzkZHp9tTZiQASc3vUHcTo"> <img alt="Screenshot 2023-11-22 at 9 42 31 PM" width="1511" src="https://private-user-images.githubusercontent.com/53316345/284968611-8ad6c9d3-bef2-4d4d-9d2d-549c43fbf928.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyNTE2OTgsIm5iZiI6MTcwMTI1MTM5OCwicGF0aCI6Ii81MzMxNjM0NS8yODQ5Njg2MTEtOGFkNmM5ZDMtYmVmMi00ZDRkLTlkMmQtNTQ5YzQzZmJmOTI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDA5NDk1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyYjY4ZjJiYWI0NmI5ZDZhZTg2OTRiZWE3Mjc1NzI3YzI5NzEyZGM4YmNhMzE4MmM5NDNhZmRjM2EyM2E5ODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Lt1v4a70bDWjo_1J9f4NRhjA4iSkwJ_r0hcp8V2JgYY">
> and when I tried to book the slot (10:30Am-11:30AM 60min). I am getting error
> 
> Could not book the meeting. Some of the hosts are unavailable for booking.
> 
> http://localhost:3000/pro+free
> 
> 'pro' has a google calendar connected which has a busy event till 2:00 PM 'free' doesn't have any calendar connected.

not sure to understand what you mean by wrong slots, it seems fine on my end ?

2023-11-29 14:17 UTC, Udit-takkar commented
> not sure to understand what you mean by wrong slots, it seems fine on my end ?


Steps to reproduce this bug locally

http://localhost:3000/pro+free

1) Connect google calendar in one of the account (pro )
2) Create a busy event from 8:30AM - 2PM

<img width="463" alt="Screenshot 2023-11-29 at 7 45 03 PM" src="https://github.com/calcom/cal.com/assets/53316345/67c51616-e8cc-4a30-9a7b-0869f6ee7f45">

3) now go to http://localhost:3000/pro+free

When Duration is 30min slots start are 2:30, 3:00, 3:30 .. 

<img width="1512" alt="Screenshot 2023-11-29 at 7 45 41 PM" src="https://github.com/calcom/cal.com/assets/53316345/a731802d-5bb1-4f54-b163-39bc49ef0502">


Now change the duration to 60min and now the slots start at 9:30AM, 10:30AM .. and so on

<img width="1512" alt="Screenshot 2023-11-29 at 7 46 36 PM" src="https://github.com/calcom/cal.com/assets/53316345/d67658a8-063f-4307-b543-eebf45d10fdd">


It ignored the busy event in calendar till 2PM.

2023-12-05 12:00 UTC, ThyMinimalDev commented
> > not sure to understand what you mean by wrong slots, it seems fine on my end ?
> 
> Steps to reproduce this bug locally
> 
> http://localhost:3000/pro+free
> 
> 1. Connect google calendar in one of the account (pro )
> 2. Create a busy event from 8:30AM - 2PM
> 
> <img alt="Screenshot 2023-11-29 at 7 45 03 PM" width="463" src="https://private-user-images.githubusercontent.com/53316345/286623579-67c51616-e8cc-4a30-9a7b-0869f6ee7f45.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3Nzc4MzcsIm5iZiI6MTcwMTc3NzUzNywicGF0aCI6Ii81MzMxNjM0NS8yODY2MjM1NzktNjdjNTE2MTYtZThjYy00YTMwLTlhN2ItMDg2OWY2ZWU3ZjQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDExNTg1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyZDgxOGZlOWE5ZmNmZmYxMjBmMzlkM2ZhZGNjZjFkMzNhMTIyM2U5YTljZjY0OTMwNjg1MmQ1ZDdmOWFiNmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sgC3oD1wJEdnpyhCrRo0sQsBBK5w2QaULDEZjhFThDE">
> 3. now go to http://localhost:3000/pro+free
> 
> When Duration is 30min slots start are 2:30, 3:00, 3:30 ..
> 
> <img alt="Screenshot 2023-11-29 at 7 45 41 PM" width="1512" src="https://private-user-images.githubusercontent.com/53316345/286623865-a731802d-5bb1-4f54-b163-39bc49ef0502.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3Nzc4MzcsIm5iZiI6MTcwMTc3NzUzNywicGF0aCI6Ii81MzMxNjM0NS8yODY2MjM4NjUtYTczMTgwMmQtNWJiMS00ZjU0LWIxNjMtMzliYzQ5ZWYwNTAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDExNTg1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5ZjhiZWNkOWFkMWVhMjA1NDExYTM3ZjQ4MjZiZGFkZGNmOGM1OGQwNGY2ZDkyY2EzODMxZDk1NzAwMmQ2MWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yPhMwYlvcZM_GISA40xehTArosLbY-iPcfYE72OsIw0">
> Now change the duration to 60min and now the slots start at 9:30AM, 10:30AM .. and so on
> 
> <img alt="Screenshot 2023-11-29 at 7 46 36 PM" width="1512" src="https://private-user-images.githubusercontent.com/53316345/286624200-d67658a8-063f-4307-b543-eebf45d10fdd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3Nzc4MzcsIm5iZiI6MTcwMTc3NzUzNywicGF0aCI6Ii81MzMxNjM0NS8yODY2MjQyMDAtZDY3NjU4YTgtMDYzZi00MzA3LWI1NDMtZWViZjQ1ZDEwZmRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDExNTg1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1NDc4YTMwNGJmMGM3MTI2ZmM5NDg1NzE2OWIxZjRkZmM1NmQ4ODQ2YWY4NzJhOTViMDY0MWEwODQwYmQ0ODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GS2_yhFcQiXSTVWBKMq9NnbZV1uO0SKOuBWZXNd4AZo">
> It ignored the busy event in calendar till 2PM.

can't reproduce this error on both this branch and main branch, can't you double check ?

2023-12-06 13:09 UTC, Udit-takkar commented
I tried again today with a new calendar connection and i am still getting the same slots as the screenshot above.

2023-12-07 09:13 UTC, supalarry commented
I also tried reproducing what Udit reported but could not. 30 and 60 minute slots start at the same time after booking event for the pro account on google calendar.

# Before

## 30 minute slots
<img width="1012" alt="before-30" src="https://github.com/calcom/cal.com/assets/42170848/e205c7d7-48b6-41fc-af05-f533a89f6ad9">
<img width="978" alt="before-30-2" src="https://github.com/calcom/cal.com/assets/42170848/4f7fa9af-cf03-4b22-b0d4-736df435638b">

## 60 minute slots
<img width="984" alt="before-60" src="https://github.com/calcom/cal.com/assets/42170848/d5361a56-13ee-43b5-8b01-1e4519fa4734">

# After

I connected pro to google account and booked from 8:30am to 2pm
<img width="1210" alt="Screenshot 2023-12-07 at 10 10 02" src="https://github.com/calcom/cal.com/assets/42170848/2018fadc-3ef9-418b-9ff0-fc878a7787b9">

## 30 minute slots
<img width="1084" alt="Screenshot 2023-12-07 at 10 10 07" src="https://github.com/calcom/cal.com/assets/42170848/c9a126a1-7ed1-4b6a-9d98-79199c21dc79">

## 60 minute slots
<img width="1027" alt="Screenshot 2023-12-07 at 10 10 11" src="https://github.com/calcom/cal.com/assets/42170848/b4d8ea03-6c59-42de-aede-30524f583d27">

2023-12-07 09:21 UTC, supalarry commented on packages/features/bookings/Booker/types.ts
> +  durationConfig?: number[];
Shall we name it `durationOptions` instead ? I find that word `config` implies a more complex configuration than just a set of possible duration values.

2023-12-11 23:07 UTC, zomars approved these changes
Issues were addressed

2023-12-11 23:07 UTC, merged