chore: improve logs
calcom/cal.com pull request #12467
Opened 2023-11-21 15:19 UTC by Udit-takkar

- Improve some logs and replaced stringify with safeStringify

https://github.com/calcom/cal.com/pull/12460#discussion_r1400414241

2023-11-22 11:41 UTC, PeerRich approved these changes, later dismissed
good refactor

2023-11-22 12:17 UTC, Udit-takkar commented on packages/app-store/googlecalendar/lib/CalendarService.ts
> +        this.log.error("Error Refreshing Google Token", safeStringify(err));
Added this log to check why we are unable to refresh token for some users.

2023-11-22 15:33 UTC, keithwillcode approved these changes

2023-11-22 15:34 UTC, keithwillcode requested changes, later dismissed
Lot's of tests are failing, @Udit-takkar

2023-11-22 15:43 UTC, Udit-takkar commented
> Lot's of tests are failing, @Udit-takkar

Getting this Error: Docker pull failed with exit code 1

2023-11-23 09:20 UTC, sean-brydon reviewed
LGTM - will be superhelpful debugging 

lets just get this one nit changed then i we can merge

2023-11-23 09:20 UTC, sean-brydon commented on packages/app-store/googlecalendar/lib/CalendarService.ts
> +      console.error(
```suggestion
      this.log.error(
```

2023-11-23 10:14 UTC, sean-brydon approved these changes
LGTM

2023-11-29 09:25 UTC, ThyMinimalDev approved these changes
Looking good !

2023-11-29 14:09 UTC, merged