fix: meeting ended incorrect content type
calcom/cal.com pull request #12484
Opened 2023-11-22 10:04 UTC by Amit91848

## What does this PR do?

Fixes #12470 
/claim #12470 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

2023-11-22 19:32 UTC, CarinaWolli requested changes

2023-11-22 19:32 UTC, CarinaWolli commented on packages/features/webhooks/lib/cron.ts
> +          "Content-Type": "application/json",
If payload is not json we should add `application/x-www-form-urlencoded` here instead

Same as here: https://github.com/calcom/cal.com/blob/main/packages/features/webhooks/lib/sendPayload.ts#L108




<br class="Apple-interchange-newline">

2023-11-23 03:41 UTC, Amit91848 commented
Made changes @CarinaWolli

2023-11-28 16:15 UTC, CarinaWolli approved these changes
Looks good now! Thank you for your contribution 🙏

2023-11-30 17:52 UTC, merged