Fix: Cookie Not Expiring After Logout #12483
calcom/cal.com pull request #12493
Opened 2023-11-22 15:17 UTC by mayankthinks

### Fix: Cookie Not Expiring After Logout #12483

Fixes: #12483

**What does this PR do?**
In this updated code:

1. I replaced the manual cookie deletion with the destroy method provided by NextAuth.
2. The destroy method will clear the session and remove the session cookie.
3. I also made sure to call destroy only when the session is authenticated (status === "authenticated").
4. I updated the import for the useRouter hook to be next/router instead of next/navigation as the latter is not a valid import in recent Next.js versions.

2023-11-22 15:17 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/calcom/cal.com?pullRequest=12493) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/calcom/cal.com?pullRequest=12493) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/calcom/cal.com?pullRequest=12493) it.</sub>

2023-11-24 18:20 UTC, PiyushChandra17 reviewed
Looks good 👍

2023-11-29 19:54 UTC, zomars commented
> I updated the import for the useRouter hook to be next/router instead of next/navigation as the latter is not a valid import in recent Next.js versions.

Can you post the docs about this issue? We're deprecating importing from "next/router" as we're planning to migrate to the app router soon.

2023-11-29 19:57 UTC, zomars requested changes
Left some comments. The PR is not achieving the intended result. Also checks seems to be failing.

2023-11-29 19:57 UTC, zomars commented on apps/web/pages/auth/logout.tsx
> +import { destroy, useSession } from "next-auth/react";
As with our current version we get this error:

Module '"next-auth/react"' has no exported member 'destroy'.

2023-11-29 19:57 UTC, zomars commented on apps/web/pages/auth/logout.tsx
> +import { useRouter } from "next/router";
We're deprecating importing from "next/router" as we're planning to migrate to app router and it is incompatible.

2023-12-21 00:16 UTC, closed without merging