chore: [app-router-migration-4]: apps/categories page
calcom/cal.com pull request #12619
Opened 2023-12-01 16:09 UTC by DmytroHryshyn

## What does this PR do?

Migrates apps/categories, apps/categories/[category] pages.

This PR depends on https://github.com/calcom/cal.com/pull/12593

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Chore (refactoring code, technical debt, workflow improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

2023-12-08 13:00 UTC, hariombalhara requested changes, later dismissed
I don't know the reason but I am seeing a consistent crash on accessing http://app.cal.local:3000/apps/categories with future mode.
https://www.loom.com/share/66d37da1d31940c39691f04d7e695e0a

2023-12-12 17:11 UTC, DmytroHryshyn commented
> I don't know the reason but I am seeing a consistent crash on accessing http://app.cal.local:3000/apps/categories with future mode. https://www.loom.com/share/66d37da1d31940c39691f04d7e695e0a

This issue can be related to https://github.com/vercel/next.js/issues/54708. App dir router memory consumption is significantly higher then for Pages dir, but this does not affect production build, this is only dev server problem. It can be temporarily fixed by adding `NODE_OPTIONS="--max-old-space-size=8192"` before `yarn dev` command. We are researching if there is better fix for this.

2023-12-12 17:13 UTC, DmytroHryshyn commented on apps/web/abTest/middlewareFactory.ts
> +  ["/apps/categories", Boolean(process.env.APP_ROUTER_APPS_CATEGORIES_ENABLED)] as const,
Thanks for pointing this out, this was a problem in our internal codemod that generates url patterns and flags. Already fixed this.

2023-12-12 18:42 UTC, zomars approved these changes
![LGTM](https://media3.giphy.com/media/NytMLKyiaIh6VH9SPm/200.gif)

2023-12-12 18:43 UTC, merged