feat: hide default booking success screen
calcom/cal.com pull request #12637
Opened 2023-12-02 20:21 UTC by thehanimo

## What does this PR do?
Fixes #12499

Adds a hideSuccessScreen event that lives under the advanced section of the eventType.

`/api/book/event/` returns a boolean hideSuccessScreen which is then used by useBookingSuccessRedirect hook to add it as a query param to `/booking/*`. This field is used to add a `hidden` className on the wrapper component. This should prevent flicker as mentioned in the bug.

In case the user toggles this field but does not handle the `bookingSuccessful` event to show a custom UI, the user will be stuck on an empty page. Something worth considering!

TODO:
- Add translations for `disable_success_screen ` and `disable_success_screen_description`.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## How should this be tested?

- Toggle the `Hide default success screen` field to true in the advanced section.
- Booking an event should show nothing on the confirmation screen.

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

2023-12-02 20:21 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/calcom/cal.com?pullRequest=12637) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/calcom/cal.com?pullRequest=12637) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/calcom/cal.com?pullRequest=12637) it.</sub>

2023-12-02 23:10 UTC, exception commented
Please ensure e2e tests are passing!

2023-12-03 13:19 UTC, emrysal requested changes
Hello, I pushed a small commit to fix your type errors; please review. Regarding:

> "In case the user toggles this field but does not handle the bookingSuccessful event to show a custom UI, the user will be stuck on an empty page. Something worth considering!"

There needs to be a failsafe for this; because a user being able to get the app into a broken state (or their booking UI in a broken state) is never an acceptable merge.

Please request my review again when these changes are done 🙏

2023-12-28 00:16 UTC, closed without merging

2024-05-25 03:19 UTC, EnriqCG commented
I agree with @thehanimo; I understand that getting the app into a broken state is not desirable but it can also happen when setting the wrong URL using "Redirect on booking". We could add a warning on the settings page to indicate this behavior.