chore: Refactor Large UI components. (WIP)
calcom/cal.com pull request #12648
Opened 2023-12-03 13:59 UTC by PIG208

## What does this PR do?

This progressively breaks down large components into smaller one and aims at making similar future refactoring easier.

Fixes #12600

## Requirement/Documentation

- If there is a requirement document, please, share it here.
- If there is ab UI/UX design document, please, share it here.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Chore (refactoring code, technical debt, workflow improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

No behavioral change is expected from this PR, so the existing test cases are expected to pass.

- Are there environment variables that should be set?
- What are the minimal test data to have?
- What is expected (happy path) to have (input and output)?
- Any other important info that could help to test that PR

## Mandatory Tasks

- [ ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist

- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my PR needs changes to the documentation
- I haven't checked if my changes generate no new warnings
- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

2023-12-03 13:59 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/calcom/cal.com?pullRequest=12648) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/calcom/cal.com?pullRequest=12648) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/calcom/cal.com?pullRequest=12648) it.</sub>

2023-12-03 14:46 UTC, PIG208 commented
The current sequence of commits is ready for review. More refactoring to be added.

2023-12-03 18:47 UTC, joeauyeung reviewed
Looking good so far. Just left one suggestion.

2023-12-03 19:44 UTC, PIG208 commented on apps/web/components/booking/BookingListItemActions.tsx
> +  showCheckRecordingButton,
Thanks for the review. Do you mean that payment actions and view recordings should have their own separate component?

2023-12-09 03:39 UTC, sean-brydon commented on apps/web/components/booking/RecurringBookingsTooltip.tsx
> +        booking.listingStatus === "cancelled") && (
Can we early return if this conditional is not met? 

Havent tested but something like 

``` 
  const isRecurringBooking = booking.recurringInfo && booking.eventType?.recurringEvent;
  const isRecurringListingStatus = ["recurring", "unconfirmed", "cancelled"].includes(booking.listingStatus);
  if (
    !isRecurringBooking ||
    !isRecurringListingStatus ||
    !booking.eventType.recurringEvent ||
    !booking.recurringInfo?.count
  ) {
    return null;
  }
``` 
should work

2023-12-09 03:44 UTC, sean-brydon requested changes
Overall LGTM - lets just tidy up that tooltip component when we are here. 

I will create a follow up issue to extract the Dialogs out of each list item.

2024-01-05 00:17 UTC, closed without merging