Fix production build
calcom/cal.com pull request #12686
Opened 2023-12-05 22:02 UTC by adrian-d-hidalgo

## What does this PR do?

This PR modifies how you can use environment variables on runtime to have "one build, many deployments". With this update, you can now build Docker images, so anybody can deploy with their own environments.

This fix allows PR [#313](https://github.com/calcom/docker/pull/313) to work correctly.

Fixes [#12032](https://github.com/calcom/cal.com/issues/12032)

## Requirement/Documentation

- No extra requirements needed

## Type of change

- [ ] Chore (refactoring code, technical debt, workflow improvements)

## How should this be tested?

- Follow README.md instructions to build for production
- The repository may have some build Issues that should be attended to fix some types of errors, meanwhile, you can run `DISABLE_ESLINT_PLUGIN=true NODE_ENV=production CI=true yarn build` to avoid those errors
- Run `yarn start` to test

2023-12-05 22:02 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/calcom/cal.com?pullRequest=12686) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/calcom/cal.com?pullRequest=12686) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: alannnc<br/>:x: adrian-d-hidalgo<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/calcom/cal.com?pullRequest=12686) it.</sub>

2023-12-06 19:48 UTC, zomars requested changes
While the proposal seems to be simple and fair. We cannot merge any of these until all of the checks are passing.

> The repository may have some build Issues that should be attended to fix some types of errors, meanwhile, you can run DISABLE_ESLINT_PLUGIN=true NODE_ENV=production CI=true yarn build to avoid those errors

We cannot allow this on main unfortunately.

2024-01-29 15:16 UTC, keithwillcode commented
Converting to draft while conflicts are fixed

2024-02-13 05:19 UTC, keithwillcode commented
Closing in favor of #13541

2024-02-13 05:19 UTC, closed without merging