fix: changes encryption key format in crypto.ts to base64 and adjusts README.md accordingly
calcom/cal.com pull request #12698
Opened 2023-12-07 01:05 UTC by stabildev

## What does this PR do?

`README.md` suggests to generate the `CALENDSO_ENCRYPTION_KEY` via `openssl rand -base64`.

However, `packages/lib/crypto.ts` expects a `base64` encoded key. As far as I can tell, the function `symmetricEncrypt` is used only in `apps/web/pages/api/auth/two-factor/totp/setup.ts` to set up 2FA. 

With the current configuration (`openssl rand -base64` + `latin1` encoding in `crypto.ts`) setting up 2FA fails.

Replacing `latin1` with `base64` fixes the issue.

Furthermore, the instructions in `README.md` are not congruent with those in `.env.example`. `AES256` requires a 32 byte key so we should fix that in readme as well.

## Backward compatibility

> To support legacy `latin1` encoded keys I added a function that detects whether a key is latin1 or base64 encoded (always under the assumption of 32 byte keys!):
```ts
const getEncoding = (key: string) => {
  if (key.length === 32) {
    return "latin1" as const;
  }
  return "base64" as const;
};
```
This should ensure that both the recommended 32 byte base64 keys and the apparently currently in use 32 byte latin1 keys work.

Related:
- https://github.com/calcom/cal.com/issues/10805
- https://github.com/calcom/cal.com/pull/12043

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

2023-12-08 01:21 UTC, stabildev commented
@nicktrn what are your thoughts on this, regarding https://github.com/calcom/cal.com/pull/12043#issuecomment-1786784680

2023-12-09 12:11 UTC, nicktrn commented
Hi @stabildev 

> As far as I can tell, the function `symmetricEncrypt` is used only in `apps/web/pages/api/auth/two-factor/totp/setup.ts` to set up 2FA.

It's used in [a few different places](https://github.com/search?q=repo%3Acalcom/cal.com%20symmetricEncrypt&type=code), mainly for integration secrets and 2FA like you mentioned, including backup codes.

Looking back on some of the changes I proposed:

> The key encoding could also be chosen dynamically based on its length

Your PR certainly ticks that box!

> an additional env var OLD_ENCRYPTION_KEY provided to migrate old secrets on-demand

That's really where the issue is. There needs to be a mechanism for decrypting old secrets. Automatically re-encrypting them with the new key would be great.

Would also be a good time to use a more secure, authenticated encryption scheme - I suggested `aes-256-gcm`.

Currently, your PR will break existing secrets.

2023-12-09 12:24 UTC, stabildev commented
Hi @nicktrn

thanks for checking in!

> > As far as I can tell, the function `symmetricEncrypt` is used only in `apps/web/pages/api/auth/two-factor/totp/setup.ts` to set up 2FA.

I meant to edit this out. Wrote it in the initial draft and dug a lot deeper afterwards. Edited it out now.

> > an additional env var OLD_ENCRYPTION_KEY provided to migrate old secrets on-demand
> 
> That's really where the issue is. There needs to be a mechanism for decrypting old secrets. Automatically re-encrypting them with the new key would be great.

My PR checks the key length of CALENDSO_ENCRYPTION_SECRET. If it is base64 encoded with 32 bytes (as is suggested in .env) the key will always be longer than 32 characters. So this is a reliable way to tell old and new keys apart.

You will find that the code with the included check works exactly as before with existing (old) keys while also supporting new base64 keys.

```ts
const getEncoding = (key: string) => {
  if (key.length === 32) {
    return "latin1" as const;
  }
  return "base64" as const;
};
```

```ts
export const symmetricEncrypt = function (text: string, key: string) {
  const _key = Buffer.from(key, getEncoding(key));
  ...
```

Unless I am missing something?

2023-12-09 13:17 UTC, nicktrn commented
Just re-read my comment and I should have defined these terms:

- Key - the encryption key, i.e. `CALENDSO_ENCRYPTION_SECRET`
- Secret - the encrypted data, i.e. AES encrypt output

Yes, you'll be able to use both old `latin1` encoded _keys_, and new `base64` encoded _keys_.

But what happens to old _secrets_ after replacing your encryption key? How would you decrypt them?

For this to work, the new key would have to be the old one, re-encoded in base64. Surely that defeats the purpose?

It would be perfectly fine for fresh deploys with empty databases. My concern is with migrations.

Hope that was clearer!

2023-12-10 01:17 UTC, stabildev commented
@nicktrn I have implemented some of your ideas.

Unfortunately, detecting whether a secret is encrypted using the old or a new key is not straight forward. Especially, since the initial setup can be different, e.g. all existing keys could be either encrypted using the latin1 key or the base64 key, depending on when and how the project was initially set up.

Generally, the only way to find out which key was used is to try both and see which one works. The difficulty here is the definition of "works".

There are currently three kinds of data structures encrypted using the key:
- `user.backupCodes`: an array of strings, referenced in `setup.ts` and `next-auth-options.ts`
- `credential.key`: a JSON object, referenced in `add.ts` and `_postAdd.ts` of various integrations
- `user.twoFactorSecret`: a string with a length of 32 characters

To avoid repeating the logic (trying one key, then trying the other key, finally updating the secret using the new key) in many places, I suggest passing the expected data type as a zod schema to `symmetricDecrypt`, e.g.
- `z.array(z.string())`
- `z.object(...)`
- `z.string().length(32)`

This provides the possibility to detect whether decryption was successful, provides the opportunity to retry immediately before returning a value and providing a convenient callback for updating the secret.

I added some info to the PR description.

What are your thoughts on this approach?

2023-12-11 16:08 UTC, stabildev commented
@PeerRich What are your thoughts on this approach?

2023-12-29 18:22 UTC, PeerRich commented
i have very little knowledge about encryption, will loop in some people. i dont understand what is wrong with our current encryption tho

2024-01-24 22:00 UTC, keithwillcode requested changes
Type checks, build and unit tests are failing

2024-01-25 09:49 UTC, PeerRich commented
/bonus 50 to fix type checks and unit tests

2024-02-12 12:30 UTC, stabildev commented
All test are passing now

2024-03-05 13:16 UTC, keithwillcode commented
Moving this to 4.0 milestone because we need more time based on current priorities

2024-03-13 17:57 UTC, zomars commented on apps/web/pages/api/auth/two-factor/totp/enable.ts
> +import * as z from "zod";
```suggestion
import { z } from "zod";
```

2024-03-13 17:58 UTC, zomars commented on apps/web/pages/api/webhook/app-credential.ts
> +import * as z from "zod";
```suggestion
import { z } from "zod";
```

2024-03-13 17:59 UTC, zomars commented on packages/app-store/closecom/lib/CalendarService.ts
> +import * as z from "zod";
```suggestion
import { z } from "zod";
```

2024-03-13 17:59 UTC, zomars commented on packages/app-store/exchange2016calendar/lib/CalendarService.ts
> +import * as z from "zod";
```suggestion
import { z } from "zod";
```

2024-03-13 18:00 UTC, zomars commented on packages/app-store/exchangecalendar/lib/CalendarService.ts
> +import * as z from "zod";
```suggestion
import { z } from "zod";
```

2024-03-13 18:00 UTC, zomars commented on packages/app-store/ics-feedcalendar/lib/CalendarService.ts
> +import * as z from "zod";
```suggestion
import { z } from "zod";
```

2024-03-13 18:00 UTC, zomars commented on packages/app-store/sendgrid/lib/CalendarService.ts
> +import * as z from "zod";
```suggestion
import { z } from "zod";
```

2024-03-13 18:07 UTC, zomars reviewed
Code LGTM. We still need to test an actual migration. Probably in dev or canary.

2024-05-23 21:59 UTC, zomars requested changes
Blocking to make some changes:

Renaming `CALENDSO_ENCRYPTION_KEY` to `CALENDSO_V2_ENCRYPTION_KEY`

Renaming `CALENDSO_OLD_ENCRYPTION_KEY` to `CALENDSO_ENCRYPTION_KEY`

The reason behind this is because we don't want to have to touch all current `CALENDSO_ENCRYPTION_KEY` values. It's prone to a lot of human error.

Instead we want this to be opt-in. So only if `CALENDSO_V2_ENCRYPTION_KEY` is set. We'll use the new encryption key. Otherwise we fallback to the old encryption model. 

This PR is more of a transition state until we can get rid of `CALENDSO_ENCRYPTION_KEY` in a later update.

2024-05-23 22:05 UTC, zomars commented
> Blocking to make some changes:
> 
> Renaming `CALENDSO_ENCRYPTION_KEY` to `CALENDSO_V2_ENCRYPTION_KEY`
> 
> Renaming `CALENDSO_OLD_ENCRYPTION_KEY` to `CALENDSO_ENCRYPTION_KEY`
> 
> The reason behind this is because we don't want to have to touch all current `CALENDSO_ENCRYPTION_KEY` values. It's prone to a lot of human error.
> 
> Instead we want this to be opt-in. So only if `CALENDSO_V2_ENCRYPTION_KEY` is set. We'll use the new encryption key. Otherwise we fallback to the old encryption model.
> 
> This PR is more of a transition state until we can get rid of `CALENDSO_ENCRYPTION_KEY` in a later update.

I take it back. Seems like it's going to be way more effort to make this opt-in. Will merge into a local branch to make some tests before merging to main. Thanks again! @stabildev

2024-05-23 22:07 UTC, zomars approved these changes

2024-05-23 22:07 UTC, merged