Updated the Big FIx 12773 sing-in
calcom/cal.com pull request #12833
Opened 2023-12-16 13:47 UTC by suprabhu77

## What does this PR do?

Fixes # (issue)
Now User will be able to see the login/Sing In Text even upon the click event. after the click the button bg will be lightly graded.

## Requirement/Documentation

- If there is a requirement document, please, share it here.
- If there is ab UI/UX design document, please, share it here.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Tests (Unit/Integration/E2E or any other test)
- [ ] This change requires a documentation update

## How should this be tested?

- Are there environment variables that should be set?
- What are the minimal test data to have?
- What is expected (happy path) to have (input and output)?
- Any other important info that could help to test that PR

## Mandatory Tasks

- [ ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist

- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my PR needs changes to the documentation
- I haven't checked if my changes generate no new warnings
- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

2023-12-16 13:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/calcom/cal.com?pullRequest=12833) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/calcom/cal.com?pullRequest=12833) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/calcom/cal.com?pullRequest=12833) it.</sub>

2023-12-17 04:14 UTC, suprabhu77 commented
@PeerRich Can you help me in reviewing the code, This is my first Open source PR. Looking forward to contribute more to cal.com.
Happy Open Sourcing.

Regards
Sumantha

2023-12-17 10:05 UTC, sean-brydon requested changes
Hi - thanks for your contribution. 

Try to use tailwind to implement this fix.

The issue here is there is a typo when setting the CSS variable [here](https://github.com/calcom/cal.com/pull/12833/files#diff-d375d403d178baa1229f926b7d2de762c1e2e7e4e2c013834270e1f961ff63c1R176)

`[--cal-brand-subtle:9CA3AF]` -> `[--cal-brand-subtle:#9CA3AF]`

2023-12-17 10:12 UTC, suprabhu77 commented
@sean-brydon Will look into this and update the PR Soon.
Thank you for reviewing.

2023-12-17 10:21 UTC, suprabhu77 commented
@sean-brydon  I have updated the PR, You were right, it was regarding the typo error.
Thank you for the help.
Please help me in contributing to cal.com

2023-12-17 10:40 UTC, sean-brydon submitted a review, later dismissed

2023-12-17 10:50 UTC, suprabhu77 commented
@sean-brydon 
Why is linters workflow is getting failed over there?
How can i again hit the workflow?

2023-12-17 14:18 UTC, suprabhu77 commented
@sean-brydon 
Please help me in this PR, Lint error is getting failed if I make changes to #9CA3AF
Something is wrong in that.

2023-12-18 04:24 UTC, suprabhu77 commented
@sean-brydon 
I have made the changes and now its working.
Can you please approve the request?

2023-12-18 12:32 UTC, Udit-takkar commented on apps/web/pages/auth/login.tsx
> +                className="w-full justify-center bg-white/70">
https://github.com/calcom/cal.com/assets/53316345/de6d7d54-72c7-41f9-9245-9ee6815be1b5

This doesn't fix the issue

2023-12-18 12:37 UTC, Udit-takkar submitted a review, later dismissed
LGTM. I have pushed the fix

2023-12-18 12:42 UTC, suprabhu77 commented
@Udit-takkar I tried changing the tailwind css in the class name, But ESlint workflow was throwing some error.
So I tried changing in the Button Classname

2023-12-18 12:45 UTC, Udit-takkar commented
@suprabhu77 install prettier and configure it to format on save in vscode

2023-12-18 12:50 UTC, suprabhu77 commented
@Udit-takkar 
Can you help me in this Lint Error? I have prettier and there is no error in local setup.

2023-12-18 12:51 UTC, PeerRich commented on .vscode/settings.json
> +    "source.fixAll.eslint": "explicit"
```suggestion
    "source.fixAll.eslint": true
```

2023-12-18 12:51 UTC, PeerRich approved these changes, later dismissed

2023-12-18 16:22 UTC, Udit-takkar commented
> @Udit-takkar Can you help me in this Lint Error? I have prettier and there is no error in local setup.

checking

2023-12-18 18:16 UTC, Udit-takkar approved these changes

2023-12-18 18:21 UTC, merged