fix: check for isEmbed
calcom/cal.com pull request #12907
Opened 2023-12-21 01:43 UTC by sean-brydon

fixes: https://discord.com/channels/1125390093386010654/1182022772000555039/1182022772000555039

Hides "needs help" button on embed.

2023-12-21 08:16 UTC, hariombalhara commented on packages/features/bookings/Booker/components/Header.tsx
> +  const isEmbed = typeof window !== "undefined" && window?.isEmbed?.();
How about using `useIsEmbed`?

2023-12-21 08:16 UTC, hariombalhara requested changes, later dismissed
I think we can use the hook here.

2023-12-22 19:52 UTC, PeerRich commented on packages/features/bookings/Booker/components/Header.tsx
> +  const isEmbed = typeof window !== "undefined" && window?.isEmbed?.();
yeh lets use the useIsEmbed hook her

2023-12-22 19:52 UTC, PeerRich commented
also, the need help button only shows up in your own embed if you are the owner of the link

2023-12-29 18:20 UTC, PeerRich commented on packages/features/bookings/Booker/components/Header.tsx
> +  const isEmbed = typeof window !== "undefined" && window?.isEmbed?.();
```suggestion
  const isEmbed = useIsEmbed();
```

2023-12-29 18:20 UTC, PeerRich commented on packages/features/bookings/Booker/components/Header.tsx
> +  const isEmbed = typeof window !== "undefined" && window?.isEmbed?.();
this is better, no @hariombalhara ?

2024-01-15 09:37 UTC, keithwillcode approved these changes

2024-01-15 09:50 UTC, hariombalhara approved these changes

2024-01-15 10:39 UTC, merged