Fix/teams page layout issue
calcom/cal.com pull request #12968
Opened 2023-12-29 19:53 UTC by Rksingh090

Fixes #12947

2023-12-29 19:53 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/calcom/cal.com?pullRequest=12968) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/calcom/cal.com?pullRequest=12968) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/calcom/cal.com?pullRequest=12968) it.</sub>

2023-12-29 20:12 UTC, Rksingh090 commented
I fixed the issue but accidently pushed the yarn.lock. Somehow i have removed yarn.lock but got other changes that i haven't touched.

2024-01-01 12:27 UTC, PeerRich requested changes
why do you think removing senty server webpack is fixing this issue?

2024-01-01 12:35 UTC, Rksingh090 commented
I just wanted to change 1 line in apps/web/lib/app-providers.tsx. Maybe when i was trying to remove the yarn.lock at that time some wrong commands changed the files. I thing i should create a new pul request with different branch.

2024-01-01 12:47 UTC, closed without merging