feat: Onboarding redesign
calcom/cal.com pull request #13003
Opened 2024-01-03 08:03 UTC by riddhesh-mahajan

## What does this PR do?

This PR adds a new onboarding design. There are no changes made to the onboarding flow; only existing pages ui is updated.

Fixes #12739 

https://www.loom.com/share/18ae1fc7d6794121aad48ded614370a0?sid=96014f57-502b-40a2-9eff-cdd17a5d9a5e

## Type of change

- [ ] New feature (non-breaking change which adds functionality)

## How should this be tested?

- Complete initial step of signup flow
- Verify email
- Go through all onboarding pages

## Note (Maybe someone from internal team can complete the following changes)

- I haven't added 2 new pages from the design. If you check the first 2 pages in design, they are not there in existing flow. Also not sure how you want to save the data from those pages.
You can refer "create account / Personal" and "Create account / Organization" from figma design https://www.figma.com/file/UajFu4M1APhn2AywAEJkJr/New-Features?type=design&node-id=7302-23448&mode=design&t=q0JcZPkS0wrXPsCQ-0
- In the provided figma design, verify email page is placed at the end of the flow. But there were no details provided in the issue to change the signup flow. So I just updated existing page, but it is still appearing before onboarding flow

2024-01-03 10:05 UTC, supalarry commented
This is some next-level stuff! Incredible work Riddhesh!

2024-01-03 16:47 UTC, PeerRich commented on apps/web/package.json
nice work, however thats quiet a lot of dependencies. we'll need to look into all of theses before merging

2024-01-03 16:59 UTC, riddhesh-mahajan commented on apps/web/package.json
Sure. Let me know if any changes are required.

2024-01-24 16:43 UTC, zomars commented on apps/web/pages/getting-started/[[...step]].tsx
> +import * as d3 from "d3";
Between these two we're adding like 400kb to the JS bundle size

<img width="703" alt="image" src="https://github.com/calcom/cal.com/assets/3504472/92b46aa0-7062-43a4-96a9-8d44827e1e04">

I would recommend lazy loading these components in the client.

2024-01-24 16:45 UTC, zomars commented on apps/web/pages/getting-started/[[...step]].tsx
> +import * as d3 from "d3";
Importing only the necessary method helps by a lot as well

<img width="672" alt="image" src="https://github.com/calcom/cal.com/assets/3504472/f516de2a-eb2b-4077-af4f-efd83d5033a9">

2024-01-24 16:47 UTC, zomars commented on apps/web/pages/getting-started/[[...step]].tsx
> +      }
This could easily be a backend endpoint so we only return the data needed instead of download the whole "country-state-city" data in the JS bundle.

2024-01-24 16:49 UTC, zomars requested changes
Left some performance concerns in the comments 🙏🏽

2024-01-25 09:55 UTC, PeerRich commented
/bonus 50 can you fix the merge conflicts?

2024-02-09 14:49 UTC, keithwillcode commented
Putting this back to draft as we are discussing how to best move forward with this.

2024-03-27 12:18 UTC, keithwillcode commented
@riddhesh-mahajan Amazing work on this. Going to close this PR for now though since we have deprioritized it and need to figure out how to best incorporates its changes.

2024-03-27 12:18 UTC, closed without merging