feat: impersonation improvements
calcom/cal.com pull request #13066
Opened 2024-01-06 10:29 UTC by sean-brydon

## What does this PR do?

Fixes SAL-77

 Loom Video: https://www.loom.com/share/9f69dec44bb74677838038bd4982bf7f

## Requirement/Documentation

- If there is a requirement document, please, share it here.
- If there is ab UI/UX design document, please, share it here.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] Tests (Unit/Integration/E2E or any other test)
- [ ] This change requires a documentation update

## How should this be tested?
1) Login as admin -> impersonate user -> return to admin
2) Login as account connected to org -> impersonate member -> return to org account
3) Login as team owner -> impersonate member -> logged out

2024-01-06 10:29 UTC, sean-brydon commented on apps/web/playwright/impersonation.e2e.ts
> +// a doubling of tests failing on logout & logout, we can group them.
```suggestion
```

2024-01-06 10:30 UTC, sean-brydon commented on packages/features/ee/impersonation/components/ImpersonatingBanner.tsx
> +          canReturnToSelf ? (
Validation also happens on BE just easier to handle this signout functionality here than within the custom provider from next-auth

2024-01-06 10:30 UTC, sean-brydon commented on packages/features/ee/impersonation/lib/ImpersonationProvider.ts
> +    if (creds?.returnToId) return;
If there is no username and a returnToId -> we dont need to throw here

2024-01-06 10:31 UTC, sean-brydon commented on packages/features/ee/impersonation/lib/ImpersonationProvider.ts
> +    if (returningUser.role !== "ADMIN" && !returningUser.organizationId) return;
Ensure this can only be used by admins and if you are in an org

2024-01-06 10:31 UTC, sean-brydon commented on packages/types/next-auth.d.ts
> +    };
Easier to handle FE permissions when in impersonation

2024-01-06 12:36 UTC, baileypumfleet commented
Wow this looks like a way snappier experience! I love it

2024-01-09 14:18 UTC, Udit-takkar reviewed
~Getting this error. I am an org owner.~

Edit: It works now



https://github.com/calcom/cal.com/assets/53316345/a104161a-1812-4060-9121-e477a4874dc4

2024-01-09 14:53 UTC, Udit-takkar commented
@sean-brydon works great. some type checks are failing and E2E tests (don't seem related to changes in this PR).

2024-01-11 10:57 UTC, Udit-takkar approved these changes

2024-01-11 11:02 UTC, keithwillcode requested changes
![IMG_0409](https://github.com/calcom/cal.com/assets/2538462/501c095c-76b5-41e0-9c36-28b57d6936b7)

Downstream API build is failing

2024-01-15 09:03 UTC, keithwillcode approved these changes

2024-01-16 08:45 UTC, merged