fix: loading animation of update buttons
calcom/cal.com pull request #13131
Opened 2024-01-09 18:26 UTC by moulibrota-das

## What does this PR do?

This PR fixes the loading animation in update buttons located in the appearance settings page.

Fixes #13110 (issue)

[Screencast from 09-01-24 11:32:56 PM IST.webm](https://github.com/calcom/cal.com/assets/88196189/6baaf03e-28de-4f77-ab3a-539d1a5c745c)

## Type of change

- Bug fix (non-breaking change which fixes an issue)

2024-01-09 18:26 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/calcom/cal.com?pullRequest=13131) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/calcom/cal.com?pullRequest=13131) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/calcom/cal.com?pullRequest=13131) it.</sub>

2024-01-10 08:39 UTC, Udit-takkar requested changes, later dismissed
@moulibrota-das no need to create a state variable. try to use formState.isSubmitting from react hook form. (check isBrandColorsFormSubmitting, isBookerLayoutFormSubmitting)

2024-02-02 16:02 UTC, joeauyeung submitted a review, later dismissed

2024-02-04 04:55 UTC, moulibrota-das commented on apps/web/pages/settings/my-account/appearance.tsx
> +            loading={mutation.isLoading}
Made the suggested changes

2024-02-13 06:23 UTC, Udit-takkar approved these changes
LGTM

2024-02-13 06:32 UTC, merged