Fix: fix breakpoint on app.cal.com/auth/signup
calcom/cal.com pull request #13208
Opened 2024-01-13 05:27 UTC by sean-brydon

Fixes side banner appearing in a stack on mobile.

2024-01-13 20:55 UTC, PeerRich requested changes

2024-01-13 20:55 UTC, PeerRich commented on apps/web/pages/signup.tsx
> +        <div className="border-muted  mx-auto mt-24 hidden w-full max-w-2xl flex-col justify-between rounded-l-2xl bg-[radial-gradient(162.05%_170%_at_109.58%_35%,_rgba(102,_117,_147,_0.7)_0%,_rgba(2
imo we should keep awards but hide features

maybe make awards a bit smaller with more spacing on mobile

2024-01-13 23:31 UTC, PeerRich commented
will take over

2024-01-13 23:48 UTC, sean-brydon commented
> will take over

My guy ❤️

2024-01-16 16:15 UTC, PeerRich commented
fixed

2024-01-16 16:15 UTC, closed without merging