Revert "Revert "chore: Chore team metadata table + isOrganization migration
calcom/cal.com pull request #13271
Opened 2024-01-17 06:25 UTC by hariombalhara

This is @sean-brydon's PR with migration fixed by removing the unique constraint [slug, isOrganization] which was unnecessary

unique constraint [slug, parentId] is what we need
Requirements:
1. calcom can be an Organization slug -> slug='calcom', parentId=null
2. calcom can be a sub-team slug in org1 -> slug='calcom', parentId="org1"
3. calcom can be a sub-team slug in org2 -> slug='calcom', parentId="org2"
4. calcom can't be a non-sub-team slug -> slug='calcom'; parentId=null - Conflicts with 1
5. calcom can't be another organization's slug -> slug='calcom'; parentId=null - Conflicts with 1

2024-01-17 06:26 UTC, hariombalhara commented on packages/prisma/schema.prisma
>    @@unique([slug, parentId])
Notice there is no unique constraint [slug, isOrganization] which was there in original PR [here ](https://github.com/calcom/cal.com/pull/12828/files#diff-56fa4d384ba6fb94b130e9eb42c5cad00734b025ebd6c197f76873469725ae87R323)

2024-01-17 06:28 UTC, hariombalhara commented on packages/prisma/migrations/20240117062434_move_org_metadata_to_org_settings/migration.sql
> +
Notice the constraint is not there now https://github.com/calcom/cal.com/pull/12828/files#r1453879560

2024-01-17 06:40 UTC, hariombalhara commented
I have deleted the previous faulty migration and added a new one. I believe this is the best solution considering that the faulty migration must have been already rolled back. cc @zomars

2024-01-17 12:27 UTC, zomars commented
So are we okay with nested subteams if the same org having the same slug?

Say id=1,slug=calcom,parentId=null can have a subteam id=2,slug=calcom,parentId=1 which in turn can have a subteam id=3,slug=calcom,parentId=2 and so on and so on... so an org can have an infinite amount of calcom subteams as long are they're not siblings. Are we okay with that? What would be the permalink of each one?

2024-01-19 19:09 UTC, zomars requested changes
So are we okay with nested subteams if the same org having the same slug?

Say id=1,slug=calcom,parentId=null can have a subteam id=2,slug=calcom,parentId=1 which in turn can have a subteam id=3,slug=calcom,parentId=2 and so on and so on... so an org can have an infinite amount of calcom subteams as long are they're not siblings. Are we okay with that? What would be the permalink of each one?

2024-01-23 10:56 UTC, hariombalhara commented
> So are we okay with nested subteams if the same org having the same slug?
> 
> Say id=1,slug=calcom,parentId=null can have a subteam id=2,slug=calcom,parentId=1 which in turn can have a subteam id=3,slug=calcom,parentId=2 and so on and so on... so an org can have an infinite amount of calcom subteams as long are they're not siblings. Are we okay with that? What would be the permalink of each one?

We don't support nested sub teams and I don't think we are going to support them in near future. There is going to be an organization and it's children teams. That's it.

Yeah normally someone won't create a subteam in an organization with same slug as org but practically it happens when a team requestes to be upgraded to become an organization.

2024-01-24 18:04 UTC, zomars submitted a review, later dismissed

2024-01-25 09:53 UTC, PeerRich approved these changes
reapproving on behalf of @zomars (his review went stale after fixing things)

2024-02-13 14:29 UTC, keithwillcode commented
@hariombalhara What's the status of this one? I feel like we need to get it moving along again or close it.

2024-02-13 14:46 UTC, hariombalhara commented
I will pick it this milestone

2024-02-15 13:04 UTC, hariombalhara commented
Closing in favour of #13700

2024-02-15 13:04 UTC, closed without merging