fix: prevent duplicate calendar account linking
calcom/cal.com pull request #13310
Opened 2024-01-18 18:16 UTC by Amit91848

## What does this PR do?

Fixes #13302 

- Bug fix (non-breaking change which fixes an issue)

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

2024-01-22 11:31 UTC, Udit-takkar reviewed
@Amit91848 we also have few more calendars like lark calendar, amie, cron, vimcal, apple calendar.

2024-01-22 15:56 UTC, Amit91848 commented
@Udit-takkar for lark if user tries to sign in using the same account, new credentials are overwriting the older ones. Should I change this?
Will check for others.

2024-01-22 16:06 UTC, Amit91848 commented
@emrysal made changes.

2024-02-01 06:21 UTC, Udit-takkar requested changes
@Amit91848 1) there are some mrege conflicts 

2) when i tried to add duplicate calendar I got this json in return which is not how we should display error to user. we should simply display toast message. 

<img width="1512" alt="Screenshot 2024-02-01 at 11 47 16 AM" src="https://github.com/calcom/cal.com/assets/53316345/49f7cecf-6e16-4b50-b002-9b39b29f5e66">

2024-02-07 11:59 UTC, Udit-takkar reviewed
@emrysal Great work. I see the toast message now on app/[slug] page but the apps/installed/calendar still doesn't display any error message or toast when you try to link duplicate calendar.

2024-02-08 07:19 UTC, Udit-takkar approved these changes
LGTM

2024-02-08 10:52 UTC, merged