Fix routing-form access restrictions
calcom/cal.com pull request #13416
Opened 2024-01-26 09:49 UTC by hariombalhara

## What does this PR do?

Fixes # (issue)

## Requirement/Documentation

- If there is a requirement document, please, share it here.
- If there is ab UI/UX design document, please, share it here.

## Type of change

- Bug fix (non-breaking change which fixes an issue)
- Chore (refactoring code, technical debt, workflow improvements)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Tests (Unit/Integration/E2E or any other test)
- This change requires a documentation update

## How should this be tested?

- Are there environment variables that should be set?
- What are the minimal test data to have?
- What is expected (happy path) to have (input and output)?
- Any other important info that could help to test that PR

## Mandatory Tasks

- [ ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist

- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my PR needs changes to the documentation
- I haven't checked if my changes generate no new warnings
- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

2024-01-26 09:49 UTC, hariombalhara commented
Current dependencies on/for this PR:
* `main`
  * **PR #13416** <a href="https://app.graphite.dev/github/pr/calcom/cal.com/13416?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/calcom/cal.com/13416?utm_source=stack-comment).

2024-02-01 08:30 UTC, hariombalhara commented on packages/prisma/zod-utils.ts
> +    migratedToOrgFrom: z
The data is already in there. Adding the schema to get type safety.

2024-02-01 08:31 UTC, hariombalhara commented on packages/prisma/zod-utils.ts
> +      .optional(),
Keeping it very loose, in case some of these props aren't set.

2024-02-01 16:13 UTC, CarinaWolli commented
> How should this be tested?
See the loom for all the cases.

@hariombalhara What loom?

2024-02-01 16:18 UTC, hariombalhara commented
lol here it is https://www.loom.com/share/dfdd7a324cbd41ccb2030b5f45c481ae

2024-02-02 17:34 UTC, CarinaWolli requested changes
I am getting 404 now for the routing form link (`forms/[id]`)

I didn't do anything related to orgs, this is just a normal team routing form

2024-02-02 17:34 UTC, CarinaWolli commented on packages/app-store/routing-forms/pages/routing-link/[...appPages].tsx
> +      form.migratedUserToOrgFrom;
```suggestion
```

2024-02-02 18:17 UTC, hariombalhara commented
Thanks @CarinaWolli 🙏 Fixed the issue. Waiting for tests to pass now.

2024-02-02 18:47 UTC, CarinaWolli submitted a review, later dismissed
Works now and tests are passing. Fix looks good 👍

2024-02-05 09:06 UTC, hariombalhara commented
Fixed conflicts with New Org Schema PR and custom route PR. Up for review again. Changed the logic a bit @CarinaWolli.

2024-02-05 09:49 UTC, Udit-takkar reviewed
LGTM. Tested and worked fine

2024-02-05 15:35 UTC, CarinaWolli approved these changes

2024-02-05 15:51 UTC, merged