feat: remember last slug for event-type
calcom/cal.com pull request #13525
Opened 2024-02-03 23:17 UTC by abhijeetsingh-22

## What does this PR do?

When changing the `slug` for `event-type` store the previous slug. The previous slug redirects to the current event page.

Fixes #13497 

https://github.com/calcom/cal.com/assets/55000107/b7f717ff-18ba-4816-9a7f-c9587d596195

-->

## Type of change

- New feature (non-breaking change which adds functionality)

## How should this be tested?

- Create a event-type 
- Update the slug for the event type.
- Try to access /[user]/[type] with both current and the previous slug. 
- Repeat this for team events.

## Expected Behaviour
Lets say we have a event with slug1
- On changing the slug to slug2 the slug1 should redirect to slug2.
- If a new event type is created with slug1 or any existing event-type is updated to have slug1 then the slug1 stops redirecting to slug2 .

### For managed events
- When users are added to managed event if they have any event-type for which previousSlug is equal to slug of the managed event, then that prevSlug is removed from their event-type.

## Mandatory Tasks

- [ x ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist

- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

2024-02-05 12:33 UTC, PeerRich reviewed
very cool, will see what priority we can put this in for review

2024-02-05 15:57 UTC, zomars commented
My two cents in here. Can we provide an option similarly to this? 


https://github.com/calcom/cal.com/assets/3504472/897fe4a8-9258-476f-bcba-44b5f726231a

2024-02-06 22:13 UTC, abhijeetsingh-22 commented
https://github.com/calcom/cal.com/assets/55000107/ce87cebc-36ab-4a9c-9d16-bfd4b3fbd8ed

@zomars , pl review I have made the requested changes.

2024-02-06 22:19 UTC, abhijeetsingh-22 commented on apps/web/lib/team/[slug]/[type]/getServerSideProps.tsx
> +    }
If the `event-type` is not found using the slug, try to use `previousSlug` to find the `event-type` if found we should redirect to the slug of the `eventTypeByPreviousSlug`

2024-02-06 22:22 UTC, abhijeetsingh-22 commented on apps/web/modules/users/views/users-type-public-view.getServerSideProps.tsx
> +    }
Try to find the user `event-type` using `slug`, if not found use the `previousSlug` to find the `event-type` . If the `event-type` is found using the `previousSlug` it means we need to redirect to the `slug` of `eventTypeByPreviousSlug`

2024-02-06 22:24 UTC, abhijeetsingh-22 commented on packages/features/ee/managed-event-types/lib/handleChildrenEventTypes.ts
> +  });
Remove the previousSlugs for the `event-type` of users of current event for which `previousSlug === slug`

2024-02-06 22:27 UTC, abhijeetsingh-22 commented on packages/features/eventtypes/lib/previousSlugManager.ts
> +  }
Used `.update()` method when there is only one userId/teamId as `.update()` is faster than `.updateMany()` for a single entry.

2024-02-06 22:30 UTC, abhijeetsingh-22 commented on packages/lib/server/queries/teams/index.ts
> +  }
When a new user joins the team clear the previousSlugs which are the same as the slug of event-types to add to user.

2024-02-06 22:33 UTC, abhijeetsingh-22 commented on packages/trpc/server/routers/viewer/eventTypes/create.handler.ts
> +  await removePreviousSlug({ userId, teamId, previousSlug: slug });
when creating a new `event-type` remove any `previousSlug` that equals the `slug` in any of the `event-type` of the given user/team.

2024-02-13 05:44 UTC, keithwillcode requested changes
Thanks for the contribution! 

Critical features like this around loading booking pages need automated tests written before merge to verify functionality.

2024-02-23 15:35 UTC, CarinaWolli commented
Hey @abhijeetsingh-22! Will you be able to fix the merge conflicts and write some tests for it?

2024-04-22 18:22 UTC, keithwillcode commented
Closing due to staleness. Please feel free to reopen if work continues.

2024-04-22 18:22 UTC, closed without merging