feat: invite emails from assignment
calcom/cal.com pull request #13555
Opened 2024-02-06 11:32 UTC by SomayChauhan

## What does this PR do?

Fixes #13532
/claim #13532

2024-02-14 09:45 UTC, supalarry commented
1. Is it hard to allow adding existing team members by e-mail? I think that if we can add new members by e-mail, we should allow searching existing ones by e-mail too.
2. I think under "Team" heading above dropdown to "Add attendees" should be an explanation - "Add existing team members by name or e-mail or invite new team members using e-mail" because otherwise this feature is hidden from users.

@PeerRich do you agree?

2024-02-15 16:21 UTC, joeauyeung commented
> 1. Is it hard to allow adding existing team members not only by name but also by e-mail? I think that if we can add new members by e-mail, we should allow searching existing ones by e-mail too.
> 2. I think under "Team" heading above dropdown to "Add attendees" should be an explanation - "Add existing team members by name or e-mail or invite new team members using e-mail" because otherwise this feature is hidden from users.
> 
> @PeerRich do you agree?

What if under the user dropdown link we add an option "Invite new team members" or something similar that opens the member invite dialog. That way we can reuse the logic or email or username look up and role assignment. I think the only thing that needs to be added would be to auto assign them to the team but not included in the availability query (might already exist?)

2024-02-16 17:08 UTC, CarinaWolli requested changes
Can you please address my comments below, let me know if you have any questions 
🙏

Also, there are merge conflicts. Most of them are probably coming from this PR: https://github.com/calcom/cal.com/pull/13566

2024-02-17 04:33 UTC, SomayChauhan commented
@CarinaWolli 
are we sure we want to go forward with this approach
i mean @joeauyeung suggestion was pretty good too

2024-02-19 21:21 UTC, CarinaWolli commented
> What if under the user dropdown link we add an option "Invite new team members" or something similar that opens the member invite dialog. That way we can reuse the logic or email or username look up and role assignment. I think the only thing that needs to be added would be to auto assign them to the team but not included in the availability query (might already exist?)

Sorry, I totally missed that comment. I do think we should make it more clear, like @supalarry said, right now this feature would be hidden for users. @joeauyeung where would you put the option to 'Invite new team members'? I think we want to avoid to add anything below the list of hosts, as this list can get long

2024-02-27 17:01 UTC, CarinaWolli commented
Maybe @ciaranha can give some input here how to best do that ui/ux-wise

2024-04-26 17:00 UTC, CarinaWolli commented
@SomayChauhan Is this the same as https://github.com/calcom/cal.com/pull/14185?

2024-04-26 17:04 UTC, SomayChauhan commented
yes!!, closing this in favour of https://github.com/calcom/cal.com/pull/14185

2024-04-26 17:04 UTC, closed without merging

2024-10-11 18:02 UTC, hamzakhalidchouhdary commented on packages/features/eventtypes/components/CheckedTeamSelect.tsx
> +              : targetValues.map((email) => email.trim().toLocaleLowerCase());
`const emails = targetValues.map((email) => email.trim().toLocaleLowerCase());`