fix: open reporting in new tab full screen
calcom/cal.com pull request #13659
Opened 2024-02-13 15:17 UTC by PeerRich

![CleanShot 2024-02-13 at 15 17 33@2x](https://github.com/calcom/cal.com/assets/8019099/7954fa47-6413-401e-87e4-eda95567b9de)

2024-02-14 08:17 UTC, Udit-takkar reviewed
https://github.com/calcom/cal.com/assets/53316345/1482dfe5-2824-4f30-b531-2c49468ed835

1) can't see some elements when banner is active
2) hydration err

<img width="1505" alt="Screenshot 2024-02-14 at 1 46 11 PM" src="https://github.com/calcom/cal.com/assets/53316345/ed6981ee-6012-413d-9149-3bdf3134341f">

2024-02-15 07:01 UTC, hariombalhara approved these changes, later dismissed
Hydration error is pre-existing. We can merge it when we fix the banner issue.

2024-02-21 19:24 UTC, CarinaWolli requested changes
Banner on top and mobile view needs to be fixed

Mobile:
![Screenshot 2024-02-21 at 2 24 02 PM](https://github.com/calcom/cal.com/assets/30310907/3805f8d3-0888-4adf-b2b6-d590982a43c8)

2024-03-12 15:25 UTC, PeerRich commented on packages/app-store/routing-forms/pages/reporting/[...appPages].tsx
> +    <div className="cal-query-builder bg-default fixed inset-0 w-full overflow-scroll ltr:mr-2 rtl:ml-2">
```suggestion
    <div className="cal-query-builder bg-default fixed inset-0 w-full overflow-scroll pt-12 ltr:mr-2 rtl:ml-2 sm:pt-0">
```

2024-03-12 15:46 UTC, CarinaWolli approved these changes

2024-03-12 15:46 UTC, merged