fix: signup form validation #13661
calcom/cal.com pull request #13663
Opened 2024-02-13 18:28 UTC by saurabhraj123

## What does this PR do?
Fix signup form validation issue.
 
Refer to this issue: [here](https://github.com/calcom/cal.com/issues/13661)

Fixes # (issue)

## Requirement/Documentation
Refer to this issue: [here](https://github.com/calcom/cal.com/issues/13661)

## Type of change
- Bug fix (non-breaking change which fixes an issue)

**Before**

https://github.com/calcom/cal.com/assets/24193157/647166c4-4b46-45b3-9d98-4f65218ff200

**After**

https://github.com/calcom/cal.com/assets/24193157/e5a44387-793e-454c-bfa4-6331e6ce1ffb

## How should this be tested?
Go to signup page at `http://localhost:3000/signup` and test the signup form.

2024-02-13 18:28 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/calcom/cal.com?pullRequest=13663) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/calcom/cal.com?pullRequest=13663) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/calcom/cal.com?pullRequest=13663) it.</sub>

2024-02-13 22:21 UTC, PeerRich requested changes
i thought we had replaced this with the new signup: https://app.cal.com/signup?

maybe the old component is still somehow in the codebase

2024-02-13 22:35 UTC, closed without merging

2024-02-13 22:35 UTC, PeerRich commented
i think you were working on an older version of cal.com

2024-02-14 10:57 UTC, saurabhraj123 commented
My bad😢