fix: event type redirect for orgs in preview test (routing-forms)
calcom/cal.com pull request #13686
Opened 2024-02-14 17:13 UTC by CarinaWolli

## What does this PR do?
Fixes that clicking on the event URL didn't redirect to the correct org URL. 
![Screenshot 2024-02-14 at 11 57 14 AM](https://github.com/calcom/cal.com/assets/30310907/ad06765f-6368-4fbe-92c9-11a068b14ac9)

2024-02-19 20:24 UTC, joeauyeung commented on packages/app-store/routing-forms/components/getServerSidePropsSingleForm.ts
> +  const formWithoutProfilInfo = {
```suggestion
  const formWithoutProfileInfo = {
```

2024-02-19 20:40 UTC, joeauyeung requested changes
When testing this it still points to the non org link for both the preview and the form it self.

I was taking a look at this but before I dive into some more are you also seeing the same thing?

2024-02-19 21:08 UTC, CarinaWolli commented
> When testing this it still points to the non org link for both the preview and the form it self.
> 
> I was taking a look at this but before I dive into some more are you also seeing the same thing?

Works for me. So if you create a routing form for an org user with event redirect it redirects you to a 404 page?

2024-03-04 17:53 UTC, joeauyeung submitted a review, later dismissed
Tested again and it's working now. Odd it wasn't before.

2024-03-05 11:10 UTC, PeerRich approved these changes
approved on behalf of @joeauyeung

2024-03-05 13:55 UTC, merged