fix: before/after event buffer with seats
calcom/cal.com pull request #13751
Opened 2024-02-19 12:37 UTC by MehulZR

## What does this PR do?

Fixes #13605  (issue)

https://github.com/calcom/cal.com/assets/86384652/4ffcfed8-c4a2-4a91-a772-d8b1baabb319

https://github.com/calcom/cal.com/assets/86384652/ac01fbba-cf6f-4035-aca3-4f86917b7188

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

2024-02-20 12:12 UTC, MehulZR commented
https://github.com/calcom/cal.com/blob/851cd4d9938a979241d5fcc74691d4c0c96ad5f5/packages/core/getBusyTimes.ts#L157-L158

In tests the value of seatReferences returned is undefined. Causing the tests to fail.
It probably has something to do with prisma mock which I was not able to figure it out. So, I will need some help here.

Aside from that, the issue is resolved in actual dev server.

2024-02-20 12:31 UTC, MehulZR commented
`apps/web/test/lib/getSchedule.test.ts > getSchedule > User Event > afterBuffer and beforeBuffer tests for seated event - Non Cal Busy Time` is failing because we are subtracting formattedBusyTimes (GMT) from dateRanges (any tz).

Which is solved in this [PR](https://github.com/calcom/cal.com/pull/13526)
https://github.com/calcom/cal.com/blob/da22eda662318ae75d23520c92e41b9c9067f7e9/packages/core/getUserAvailability.ts#L334-L346


`apps/web/test/lib/getSchedule.test.ts > getSchedule > User Event > afterBuffer and beforeBuffer tests for seated event - Cal Busy Time` is failing which is explained [here](https://github.com/calcom/cal.com/pull/13751#issuecomment-1954085933)

2024-02-20 12:33 UTC, MehulZR commented
I marked the PR ready as I need some help regarding Prisma mock returning `underfined`.

2024-04-15 16:19 UTC, CarinaWolli requested changes
Fix looks pretty good already, but found one more issue. Could you take a look at that? Also, would be great to cover this case in a test as well

2024-04-15 16:19 UTC, CarinaWolli commented on packages/core/getBusyTimes.ts
> +              end: dayjs(startTime).toDate(),
I think we also need to add buffer here. 
For example, a 15 minute event with a 1 hour before buffer: 
![Screenshot 2024-04-15 at 12 16 17 PM](https://github.com/calcom/cal.com/assets/30310907/63ca4cbe-f1ff-4c5b-a555-9472671a0b84)
12:15 can be booked but wouldn't have a 1 hour before buffer. For other event types this is applied correctly:
![Screenshot 2024-04-15 at 12 16 44 PM](https://github.com/calcom/cal.com/assets/30310907/b03cc8ab-9712-4850-9695-ee4e74f581b8)

2024-04-15 16:19 UTC, CarinaWolli commented on packages/core/getBusyTimes.ts
> +              start: dayjs(endTime).toDate(),
same here

2024-04-22 12:54 UTC, MehulZR commented on apps/web/test/lib/getSchedule.test.ts
> +      );
Oops, my bad. Thanks for the heads-up.

2024-06-04 18:52 UTC, MehulZR commented
`apps/web/test/lib/getSchedule.test.ts > getSchedule > User Event > beforeBuffer tests for seated event - Cal Busy Time`
`apps/web/test/lib/getSchedule.test.ts > getSchedule > User Event > afterBuffer tests for seated event - Cal Busy Time`
`apps/web/test/lib/getSchedule.test.ts > getSchedule > User Event > afterBuffer and beforeBuffer tests for seated event - Cal Busy Time`
 These tests are failing which is explained [here](https://github.com/calcom/cal.com/pull/13751#issuecomment-1954085933)
 
 
 `apps/web/test/lib/getSchedule.test.ts > getSchedule > User Event > afterBuffer and beforeBuffer tests - Non Cal Busy Time`
`apps/web/test/lib/getSchedule.test.ts > getSchedule > User Event > afterBuffer and beforeBuffer tests - Cal Busy Time`

https://github.com/calcom/cal.com/blob/da22eda662318ae75d23520c92e41b9c9067f7e9/packages/core/getUserAvailability.ts#L334-L346

were passing earlier because we were subtracting formattedBusyTimes (GMT) from dateRanges (any tz).


For example.
```ts
    test("afterBuffer and beforeBuffer tests - Non Cal Busy Time", async () => {
      const { dateString: plus2DateString } = getDate({ dateIncrement: 2 });
      const { dateString: plus3DateString } = getDate({ dateIncrement: 3 });

      CalendarManagerMock.getBusyCalendarTimes.mockResolvedValue([
        {
          start: `${plus3DateString}T04:00:00.000Z`, // 9 AM IST Day 3
          end: `${plus3DateString}T05:59:59.000Z`, //  11 AM IST Day 3
        },
      ]);

      const scenarioData = {
        eventTypes: [
          {
            id: 1,
            length: 120,
            beforeEventBuffer: 120,
            afterEventBuffer: 120,
            users: [
              {
                id: 101,
              },
            ],
          },
        ],
        users: [
          {
            ...TestData.users.example,
            id: 101,
            schedules: [TestData.schedules.IstWorkHours],
            credentials: [getGoogleCalendarCredential()],
            selectedCalendars: [TestData.selectedCalendars.google],
          },
        ],
        apps: [TestData.apps["google-calendar"]],
      };

      await createBookingScenario(scenarioData);

      const scheduleForEventOnADayWithNonCalBooking = await getSchedule({
        input: {
          eventTypeId: 1,
          eventTypeSlug: "",
          startTime: `${plus2DateString}T18:30:00.000Z`, // 0:00 IST Day 3
          endTime: `${plus3DateString}T18:29:59.999Z`, //  23:59 IST Day 3
          timeZone: Timezones["+5:30"],
          isTeamEvent: false,
        },
      });

      expect(scheduleForEventOnADayWithNonCalBooking).toHaveTimeSlots(
        [
          // Info.
          // Working hours / Availability is set to 9:30 AM - 6 PM IST
          // Event length is 2 hours so by default event interval is 2 hours too.

          // Earlier
          // `04:00:00.000Z`, // - 9:30 AM IST is booked
          // `06:00:00.000Z`, // - 6 AM is not available because 08:00AM slot has a `beforeEventBuffer`
          `08:00:00.000Z`, // - 8 AM is available because of availability of 06:00 - 07:59
          `10:00:00.000Z`,
          `12:00:00.000Z`,

          // After
          // But First slot will actually start from `04:30:00.000Z` (10 AM IST) because of event interval being 2 hours.

          // `04:30:00.000Z` // - 10 AM IST (middle of the booking)
          // `06:30:00.000Z`, // - 12 AM IST is not available because 2 PM IST slot has a `beforeEventBuffer`
          `08:30:00.000Z`, // - 2 PM IST is available
          `10:00:00.000Z`, // - 4 PM IST is available
          `12:00:00.000Z`, // - 6 PM IST is unavailable because of IST working hours
        ],
        {
          dateString: plus3DateString,
        }
      );
    });
```

2024-06-04 19:01 UTC, MehulZR commented
I have tried to explain but it's a bit complex (more like intertwined with other issues)

I will suggest to look a bit into my other PRs like [this](https://github.com/calcom/cal.com/pull/13707) & [this](https://github.com/calcom/cal.com/pull/13651) as they work on more deeper layers.

I discovered these while working on this [PR](https://github.com/calcom/cal.com/pull/13526). So a lot of the context is there too.

If you have any questions, please feel free to ask.
Not putting a lot of time in those will help me too as a lot of the context around these problems gets skipped from mind if there is a long delay.

2024-06-04 22:42 UTC, MehulZR commented
Before:
This is main branch without any edit's except the comments.

https://github.com/calcom/cal.com/assets/86384652/86643d1d-9b5f-4e36-b044-4cf2420f0e1a

After: 
Only edits are converting the `formattedBusyTimes` from UTC to host's timezone. So that it can subtract from the host's dateRanges without an issue.
https://github.com/calcom/cal.com/blob/c2d4677dcd148dfbb7b708eda95fa561674f669f/packages/core/getUserAvailability.ts#L411-L416

https://github.com/calcom/cal.com/assets/86384652/66c31399-69cf-45af-8c8f-623b265905fa

2024-06-26 16:16 UTC, CarinaWolli reviewed
The fix looks good and works. I would love to have @emrysal look at it at it as well

2024-06-26 16:16 UTC, CarinaWolli commented on packages/core/getUserAvailability.ts
> +    start: dayjs(busy.start).tz(timeZone),
same question as here: https://github.com/calcom/cal.com/pull/13526#discussion_r1655101788

2024-07-01 09:36 UTC, MehulZR commented on packages/core/getUserAvailability.ts
> +    start: dayjs(busy.start).tz(timeZone),
Answered [here](https://github.com/calcom/cal.com/pull/13526#issuecomment-2199681257)

2025-02-06 12:55 UTC, MehulZR commented
![image](https://github.com/user-attachments/assets/5293e332-9380-4e22-afa9-e90ae93bf754)

Hey @CarinaWolli @emrysal,

I was working on updating the PR after quite some time & was wondering about something.
Should the first slot be invalid as it doesn't have a `before event buffer`. 

As if the boundary is a Non Cal busy time (rather than user availability), then the proceeding slot is unavailable due to not having `before event buffer`.

![image](https://github.com/user-attachments/assets/74fa1499-3da4-49d8-8678-dde0cbb70580)

2025-03-31 12:19 UTC, emrysal commented
Hi @MehulZR

This is now fixed in https://github.com/calcom/cal.com/pull/20233 - it's been a while in the making but we got there 😎 

Thank you!

2025-03-31 12:19 UTC, closed without merging