feat: added skeleton instead of spinning loader for embeds
calcom/cal.com pull request #13768
Opened 2024-02-19 21:21 UTC by PeerRich

- [ ] needs testing
- [ ] could not figure out how to test locally @hariombalhara 

here's the html sandbox https://play.tailwindcss.com/bpzsjZ5yBx?layout=horizontal

![CleanShot 2024-02-19 at 21 19 46@2x](https://github.com/calcom/cal.com/assets/8019099/fd47269a-7575-40c6-8d95-145e53311d2a)

2024-02-19 21:26 UTC, PeerRich commented on .env.example
> +NEXT_PUBLIC_HEAD_SCRIPTS=console.log('hey, Peer')
```suggestion
```

2024-02-19 22:22 UTC, ciaranha commented
Looks great 👌

2024-02-20 12:10 UTC, Udit-takkar requested changes
@PeerRich Getting this error "No loader element"

<img width="1512" alt="Screenshot 2024-02-20 at 5 39 53 PM" src="https://github.com/calcom/cal.com/assets/53316345/be681cb6-884d-47a0-bf2d-445fb04a53e0">

2024-02-20 12:11 UTC, Udit-takkar commented
To test 

do cd packages/embeds/embed-core and yarn dev
and yarn dev on new terminal (default directory)

then go to http://localhost:3100/embed/

2024-02-20 19:19 UTC, PeerRich commented
figured out some of the glitches but dont know how to load our custom colors in. thats why its a blank screen and also why dark mode is not working.


any ideas @Udit-takkar ?
https://github.com/calcom/cal.com/assets/8019099/2f1e22c2-f880-43d7-a2e8-deba62031811

2024-02-21 13:52 UTC, PeerRich commented
added bg-gray-200 etc. instead of our token colors. should do the trick for now

2024-02-21 18:57 UTC, Udit-takkar reviewed
I also see Booker skeleton even when i open user page

https://github.com/calcom/cal.com/assets/53316345/e887b465-c953-4e13-a49d-e2ebcef56788

2024-02-21 19:38 UTC, Udit-takkar commented
I think there is some issue in detecting theme on embed. even when you open embed of dark theme loader does not use color with dark: attribute

2024-02-21 20:18 UTC, PeerRich commented
> I also see Booker skeleton even when i open user page

yeah I could not figure out yet how to differentiate between user profile, booking page and routing form. maybe @hariombalhara knows if this is possible?

2024-04-25 14:15 UTC, closed without merging

2024-04-25 14:15 UTC, PeerRich commented
we should probably fix this with atoms and give people proper react embeds and keep iframes as they are