fix: #14016
calcom/cal.com pull request #14018
Opened 2024-03-07 16:25 UTC by ASQUAREEE

fix Issue: #14016

I just converted an X icon to an Xcircle icon and fixed the issue.

2024-03-07 16:25 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/calcom/cal.com?pullRequest=14018) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/calcom/cal.com?pullRequest=14018) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/calcom/cal.com?pullRequest=14018) it.</sub>

2024-03-07 16:30 UTC, keithwillcode submitted a review, later dismissed

2024-03-07 16:41 UTC, PeerRich requested changes, later dismissed
thats not the right icon. i think we have a svg icon somewhere

2024-03-07 17:37 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/calcom/cal.com?pullRequest=14018) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/calcom/cal.com?pullRequest=14018) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: keithwillcode<br/>:x: ASQUAREEE<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/calcom/cal.com?pullRequest=14018) it.</sub>

2024-03-08 05:22 UTC, Udit-takkar commented on apps/web/modules/bookings/views/bookings-single-view.tsx
> +                  )}
Doesn't look good in dark mode

2024-03-08 05:41 UTC, Udit-takkar commented on apps/web/styles/globals.css
> +  --cal-bg-error: hsla(3,66%,93%,1);
This was the bug in light mode. I have removed the svg that you added

2024-03-08 05:41 UTC, Udit-takkar approved these changes
LGTM. I have fixed it now

<img width="588" alt="Screenshot 2024-03-08 at 11 11 43 AM" src="https://github.com/calcom/cal.com/assets/53316345/5a550cc8-b02b-4db8-903a-21c3a3be7541">

2024-03-11 10:01 UTC, PeerRich approved these changes

2024-03-12 10:08 UTC, merged