Fix: view team bookings
calcom/cal.com pull request #14079
Opened 2024-03-14 07:50 UTC by SomayChauhan

## What does this PR do?

redoing #13591 - that was reverted due to DB load issues introduced.

Fixes #13582

2024-04-03 15:29 UTC, joeauyeung requested changes

2024-04-03 15:29 UTC, joeauyeung commented on packages/trpc/server/routers/viewer/bookings/get.handler.ts
From this comment, I'm not seeing any `select` fields in the queries. https://github.com/calcom/cal.com/pull/13591#pullrequestreview-1931896242

Let's figure out the minimum amount of data we need from the DB for this endpoint.

2024-04-03 15:58 UTC, SomayChauhan commented on packages/trpc/server/routers/viewer/bookings/get.handler.ts
how about now?

2024-04-03 18:20 UTC, joeauyeung approved these changes, later dismissed
@SomayChauhan I like this commit: [`0aa47bd` (#14079)](https://github.com/calcom/cal.com/pull/14079/commits/0aa47bde45f6defebfbc3a132f48ef85b45963b4)

I'll approve for now, but let's see what @keithwillcode and @zomars have to say. 

As a follow up I found two things that we can improve on:
- `getUniqueBookings` filters duplicate bookings based on `uid` but when getting the nested fields from the bookings we filter on `id`. We should change `getUniqueBookings` to filter on just `id`s to reduce the amount of data we need to initially query the database for.
- Optimize `getUniqueBookings`
	- Right now it loops through the array of bookings theoretically two times but I think we can cut it down to once
```
const getUniqueBookings = <T extends { uid: string }>(arr: T[]) => {
	const  unique = new Set();
    arr.forEach((booking) => {
    set.add(booking.uid);
  	});
  return [ ...unique.values() ];
};
```

2024-04-04 18:30 UTC, zomars commented
For some reason e2e tests are broken. Will revisit after release.

2024-04-10 15:57 UTC, emrysal approved these changes
Tests passing, looks ready to go! :)

2024-04-10 15:57 UTC, merged