fix: email displayed as organizer eventtype settings
calcom/cal.com pull request #14102
Opened 2024-03-15 14:31 UTC by Amit91848

## What does this PR do?

Fixes #14001 

Accidentally deleted #14042 

![Screenshot 2024-03-09 at 1 56 09 PM](https://github.com/calcom/cal.com/assets/74371312/6a04b5de-5227-493a-a819-f7b5a29094f9)
![Screenshot 2024-03-09 at 1 56 19 PM](https://github.com/calcom/cal.com/assets/74371312/319fcdbf-a70a-466c-8c24-5e14a54b70a7)

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

2024-03-18 17:17 UTC, supalarry requested changes
Great work Amit ! Thank you for your contributions!

I confirm that the functionality works, but just have a small note about quotes in translation string which I fixed and then  destination calendar input appearing when it should not, which should be fixed. After it is fixed it is good to go! : )

2024-03-18 17:20 UTC, supalarry commented on apps/web/public/static/locales/en/common.json
> +  "if_enabled_email_address_as_organizer": "If enabled, we'll display the email address from your 'Add to calendar as organizer and send confirmation emails there",
Fixed in [fix: quotation in i18n file](https://github.com/calcom/cal.com/pull/14102/commits/1256a427cf1a3880cafc10cdbb4ad601aabaede0)

2024-03-18 17:30 UTC, supalarry commented on apps/web/components/eventtype/EventAdvancedTab.tsx
> +          {displayDestinationCalendarSelector && (
To reproduce:

1 in "apps/web/components/eventtype/EventAdvancedTab.tsx" set "const displayDestinationCalendarSelector = false;"

2 login using teampro2 account:
username: teampro2
password: teampro2

3 connect google calendar

4 create an event type and check advanced settings of it

2024-03-19 09:47 UTC, Amit91848 commented on apps/web/components/eventtype/EventAdvancedTab.tsx
> +          {displayDestinationCalendarSelector && (
Fixed this, accidentally removed some conditions

2024-03-19 11:40 UTC, supalarry commented
Hmm, now I don't see the dropdown under the toggle.

What i see:
<img width="1213" alt="Screenshot 2024-03-19 at 12 40 29" src="https://github.com/calcom/cal.com/assets/42170848/bfcd477e-e92d-4986-8552-ef99d8d0f0d9">

What is in the design:
![image](https://github.com/calcom/cal.com/assets/42170848/cf4f83d8-fe2c-4127-b188-bed425ae1ca0)

2024-03-19 11:42 UTC, Amit91848 commented
Do you have a secondary email added @supalarry ?

2024-03-19 11:42 UTC, supalarry commented
Also, I think that we can add to "if_enabled_email_address_as_organizer" explaining that by default cal account e-mail will be used: "If enabled, we'll display the email address from your \"Add to calendar\" as organizer and send confirmation emails there. Otherwise, e-mail used to sign up at Cal is used."

2024-03-19 11:59 UTC, Amit91848 commented
Works now

2024-03-19 14:43 UTC, supalarry approved these changes
Great work Amit! Appreciate the fast response and thank you for the amazing contribution! 🚀

2024-03-20 10:27 UTC, merged