fix: improve defined slot start times
calcom/cal.com pull request #14107
Opened 2024-03-15 18:59 UTC by CarinaWolli

## What does this PR do?

Fixes # (issue)

## Requirement/Documentation

- If there is a requirement document, please, share it here.
- If there is a UI/UX design document, please, share it here.

## Type of change

- Bug fix (non-breaking change which fixes an issue)
- Chore (refactoring code, technical debt, workflow improvements)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Tests (Unit/Integration/E2E or any other test)
- This change requires a documentation update

## How should this be tested?

- Are there environment variables that should be set?
- What are the minimal test data to have?
- What is expected (happy path) to have (input and output)?
- Any other important info that could help to test that PR

## Mandatory Tasks

- [ ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist

- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my PR needs changes to the documentation
- I haven't checked if my changes generate no new warnings
- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

2024-03-15 19:12 UTC, CarinaWolli commented on packages/lib/slots.ts
> +  let interval = Number(process.env.NEXT_PUBLIC_AVAILABILITY_SCHEDULE_INTERVAL) || 1;
Let a slot start at any minute if the frequency (timeslot interval) is not dividable by any of the defined starting times (60, 30, 20, 15, 10, 5). 

The main thing that will be changed is that the first slot of a date range from a 5 min event now doesn't need to start at 15 minute slot no more. This caused 'missing' slots, here is an example:
- 1:00, 1:05, 1:10, 1:15 is available 
- 1:00 gets booked
- With the old logic 1:15 would be the first available slot now
- With the new logic 1:05 is the first available slot

What also changes: 
- Slots with a timeslot interval (duration) of, for example, 7 minutes will now start at any arbitrary minute and not at a 15 minute slot.

2024-03-20 13:48 UTC, joeauyeung requested changes
When I added a 5 minute buffer before or after, the next slot jumps to the :15 minute slot.

Ex. Booking at 4:05 and adding a 5 minute buffer either before or after an event removes the 4:00 and 4:10 slots.
![image](https://github.com/calcom/cal.com/assets/65426560/eb7691d4-fb69-4c25-b013-2a78246bedde)

I think this is a blocking comment but willing to defer to @emrysal's judgement.

2024-03-20 16:00 UTC, CarinaWolli commented
> When I added a 5 minute buffer before or after, the next slot jumps to the :15 minute slot.
> 
> Ex. Booking at 4:05 and adding a 5 minute buffer either before or after an event removes the 4:00 and 4:10 slots. ![image](https://private-user-images.githubusercontent.com/65426560/314522623-eb7691d4-fb69-4c25-b013-2a78246bedde.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5NTAwNTYsIm5iZiI6MTcxMDk0OTc1NiwicGF0aCI6Ii82NTQyNjU2MC8zMTQ1MjI2MjMtZWI3NjkxZDQtZmI2OS00YzI1LWIwMTMtMmE3ODI0NmJlZGRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIwVDE1NDkxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyMDdhNDhmMzllNDg3MGRmMGUxNWNiYTBiYjcwM2FlZDVkYjYxYzc2MjQyZGI0MjY0YzQ2NGQzNjViMTBkMDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BpHQxLq9yZzkOAo85D5wVwcSEoWGlGvf69bPHS7GZNY)
> 
> I think this is a blocking comment but willing to defer to @emrysal's judgement.

That's intended. 

3:55 ->  Possible Slot
4:00-4:05 ->  Before buffer for booking
4:05-4:10 ->  **Booking**
4:10-4:15 ->  Before buffer for next possible slot 
4:15 ->  Next possible slot

2024-03-20 16:03 UTC, joeauyeung approved these changes
@CarinaWolli thanks for your clarifying comment. This PR is working as expected.

2024-03-20 16:04 UTC, merged