fix: timezone display on booking page to reflect event availability timezone
calcom/cal.com pull request #14127
Opened 2024-03-18 11:15 UTC by Shaik-Sirajuddin

## What does this PR do?

Currently when the "Lock timezone on booking page" feature is enabled for the event ,
the timezone on the booking page locked is based on the timezone of the user accessing the booking page

this pr updates the display of the timezone on the booking page to the same timezone for which the 'availability' settings for that event have been defined.

Fixes #13521 

[Fix Video](https://www.loom.com/share/5aaaf522deaa412a8a662facee8044ba?sid=332878f5-7655-479d-868e-afdbe507ef29)

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

2024-03-18 11:15 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/calcom/cal.com?pullRequest=14127) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/calcom/cal.com?pullRequest=14127) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: Shaik-Sirajuddin<br/>:x: siraj<br/><hr/>**siraj** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/calcom/cal.com?pullRequest=14127) it.</sub>

2024-03-18 15:58 UTC, joeauyeung requested changes
Thanks for your contribution @Shaik-Sirajuddin.

I only have one blocking comment to address.

2024-03-18 15:58 UTC, joeauyeung commented on packages/features/bookings/Booker/components/EventMeta.tsx
> +  }, [event, setTimezone, eventOwnerDefaultShedule]);
**Blocking**: Let's move the logic of getting the owner's timezone to server side

2024-03-18 15:58 UTC, joeauyeung commented on packages/features/bookings/Booker/components/EventMeta.tsx
> +  const { data: eventOwnerDefaultShedule } = trpc.viewer.availability.schedule.get.useQuery({
Let's fix this typo here as well

```suggestion
  const { data: eventOwnerDefaultSchedule } = trpc.viewer.availability.schedule.get.useQuery({
```

2024-03-19 08:38 UTC, Shaik-Sirajuddin commented
Migrated fetching owners default schedule to server side :+1: 
PTAL @joeauyeung

2024-03-19 17:51 UTC, joeauyeung approved these changes
Working as expected. Thanks again @Shaik-Sirajuddin!

2024-03-19 18:15 UTC, merged