feat: Delete/Create WebhookScheduledTriggers for existing bookings
calcom/cal.com pull request #14121
Opened 2024-03-17 10:46 UTC by Amit91848

## What does this PR do?

Fixes #14103 

https://github.com/calcom/cal.com/assets/74371312/1d685aae-5742-45ec-b2d1-f39252160cb0

## Type of change

- New feature (non-breaking change which adds functionality)

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

2024-03-17 10:46 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/calcom/cal.com?pullRequest=14121) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/calcom/cal.com?pullRequest=14121) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/calcom/cal.com?pullRequest=14121) it.</sub>

2024-03-25 18:06 UTC, CarinaWolli requested changes
Great start already, but we also need to handle account wide webhooks from http://localhost:3000/settings/developer/webhooks. Right now this only takes care of event type specific webhooks. 

I have a PR open that adds a relationship between `WebhooksScheduledTriggers` and `Webhook`, which probably would make it easier to find the jobs we need to cancel https://github.com/calcom/cal.com/pull/14188

2024-03-26 08:29 UTC, Amit91848 commented on packages/features/webhooks/lib/scheduleTrigger.ts
> +    removedEventTriggers.some((trigger) => SCHEDULING_TRIGGER.includes(trigger))
Forgot to remove it from here.

2024-03-26 08:30 UTC, Amit91848 commented on packages/features/webhooks/lib/scheduleTrigger.ts
> +    where: {
Yeah right, slipped my mind 😅

2024-03-26 08:35 UTC, Amit91848 commented
> Great start already, but we also need to handle account wide webhooks from http://localhost:3000/settings/developer/webhooks. Right now this only takes care of event type specific webhooks.
> 
> I have a PR open that adds a relationship between `WebhooksScheduledTriggers` and `Webhook`, which probably would make it easier to find the jobs we need to cancel #14188

Will make other changes till your pr is merged.

2024-04-05 10:42 UTC, Amit91848 commented
@CarinaWolli  Now this works for account wide webhooks too.

2024-04-12 16:51 UTC, CarinaWolli approved these changes
Looks good, tested and works 🙌🏻 Thank you 🙏

2024-04-12 16:57 UTC, merged