feat: AI Transcribe
calcom/cal.com pull request #14140
Opened 2024-03-19 11:36 UTC by exception

## What does this PR do?

Fixes # (issue)

## Requirement/Documentation

- If there is a requirement document, please, share it here.
- If there is a UI/UX design document, please, share it here.

## Type of change

- Bug fix (non-breaking change which fixes an issue)
- Chore (refactoring code, technical debt, workflow improvements)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Tests (Unit/Integration/E2E or any other test)
- This change requires a documentation update

## How should this be tested?

- Are there environment variables that should be set?
- What are the minimal test data to have?
- What is expected (happy path) to have (input and output)?
- Any other important info that could help to test that PR

## Mandatory Tasks

- [ ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist

- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my PR needs changes to the documentation
- I haven't checked if my changes generate no new warnings
- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

2024-04-04 14:04 UTC, Udit-takkar commented on apps/web/pages/api/send-daily-video-transcript.ts
> +  }
You can comment these lines while testing the end point

2024-04-04 14:06 UTC, Udit-takkar commented on apps/web/modules/videos/views/videos-single-view.tsx
> +          iconPathDarkMode: `${WEBAPP_URL}/sparkles.svg`,
we can only use https url here. ignore the icon not loading locally. it would load once this gets deployed

2024-04-12 19:34 UTC, CarinaWolli requested changes
Tested and works, will approved after my two comments are addressed 🙏

2024-04-12 19:34 UTC, CarinaWolli commented on apps/web/pages/api/send-daily-video-transcript.ts
> +  }
```suggestion
```

Not needed. Sengrid keys are only used for workflow emails. This email uses SMTP settings

2024-04-12 19:34 UTC, CarinaWolli commented on packages/app-store/dailyvideo/lib/VideoApiAdapter.ts
> +    console.log("dailyEvent", dailyEvent);
```suggestion
```

2024-04-17 15:02 UTC, CarinaWolli approved these changes

2024-04-17 15:09 UTC, merged