chore: manually type getConnectedDestinationCalendars returnType
calcom/cal.com pull request #14213
Opened 2024-03-26 08:41 UTC by ThyMinimalDev

…help typescript

## What does this PR do?

manually type getConnectedDestinationCalendars returnType to help typescript

2024-03-26 17:04 UTC, emrysal approved these changes

2024-03-27 10:34 UTC, sean-brydon approved these changes
Nice one!

2024-04-04 17:02 UTC, zomars approved these changes

2024-04-04 17:10 UTC, zomars requested changes
We have some typing issues 

<img width="1285" alt="image" src="https://github.com/calcom/cal.com/assets/3504472/b6bd2254-d141-4def-acfe-c0fe1fc5a453">

2024-04-18 07:03 UTC, closed without merging