chore: `EventManager` add `cancelEvent` method
calcom/cal.com pull request #14261
Opened 2024-03-29 04:06 UTC by joeauyeung

## This PR is stacked on #14147. A part of the CRM refactor  

## What does this PR do?

This PR adds the `cancelEvent` method to the `EventManager` class. Logic surrounding deleting 3rd party data when canceling a booking lived in both `handleCancelBooking` and the `EventManager` in a private class. 

My hope with this PR is to refactor this so this logic only lives inside of the `EventManager`

Fixes # (issue)

## Requirement/Documentation

- If there is a requirement document, please, share it here.
- If there is a UI/UX design document, please, share it here.

## Type of change

- Chore (refactoring code, technical debt, workflow improvements)

## How should this be tested?

- Install a calendar and a video integration and enable them on an event type
	- I used GCal and Zoom
- Create a booking
	- The references should be created in the 3rd party apps
- Delete the booking
	- The references should be deleted in the 3rd party apps	

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist

- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

2024-03-29 04:24 UTC, joeauyeung commented on packages/core/EventManager.ts
> +        : reference.uid;
Check if we're deleting a booking in a recurring series. This change was made in `handleCancelBooking` but missing in the `EventManager`

2024-03-29 04:24 UTC, joeauyeung commented on packages/core/EventManager.ts
> +            })
Before this function would query the database for the credential. When we create a new instance of the `EventManager` class we need to pass the credentials anyways. Let's search through the appropriate credential arrays first before querying the database.

2024-03-29 04:24 UTC, joeauyeung commented on packages/core/EventManager.ts
> +  }
Expose the `deleteEventsAndMeetings` method.

2024-03-29 04:24 UTC, joeauyeung commented on packages/core/EventManager.ts
> -    });
We're looping through the booking references two times.

2024-03-29 04:24 UTC, joeauyeung commented on packages/core/EventManager.ts
> +          this.deleteCalendarEventForBookingReference({
Let's loop through the references once and call the appropriate method.

2024-03-29 04:24 UTC, joeauyeung commented on packages/core/EventManager.ts
> +    log.debug("deleteEventsAndMeetings", safeStringify({ calendarReferences, videoReferences }));
I still kept this for logging though.

2024-03-29 04:36 UTC, joeauyeung commented on packages/features/bookings/lib/handleCancelBooking.ts
With this refactor we're reducing the size of `handleCancelBooking` by 21%.

2024-04-10 19:10 UTC, zomars approved these changes
![LGTM](https://media3.giphy.com/media/NytMLKyiaIh6VH9SPm/200.gif) 

Nice work @joeauyeung 🙏🏽

2024-04-10 19:24 UTC, zomars requested changes
We're having some type errors in CI. Let's get this fix before merging

2024-04-12 15:39 UTC, joeauyeung commented on packages/features/bookings/lib/getAllCredentialsForUsersOnEvent/getAllCredentials.ts
> +  eventType: { team: { id: number | null } | null; parentId: number | null } | null
@zomars made some changes here. I think the types casted too broad of an umbrella. I narrowed it down to what's really needed. Thoughts?

2024-04-22 17:13 UTC, sean-brydon approved these changes

2024-04-23 17:52 UTC, zomars approved these changes
LGTM. Let's wait for the missing check

2024-04-23 17:54 UTC, merged

2024-09-19 17:48 UTC, zomars commented on packages/features/bookings/lib/handleCancelBooking.ts
>    const prismaPromises: Promise<unknown>[] = [bookingReferenceDeletes];
This is now orphaned @joeauyeung is should we remove this?