Add kazakh language
calcom/cal.com pull request #14277
Opened 2024-04-01 08:53 UTC by T1sev4

## What does this PR do?

Add kazakh language

2024-04-01 08:53 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/calcom/cal.com?pullRequest=14277) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/calcom/cal.com?pullRequest=14277) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/calcom/cal.com?pullRequest=14277) it.</sub>

2024-04-01 10:49 UTC, Ryukemeister commented
@T1sev4 ideally you don't need to push the `yarn.lock` file changes unless you add or remove a new dependency. Can you revert the `yarn.lock` file changes with the help of this guide https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md#guidelines-for-committing-yarn-lockfile

2024-04-01 10:51 UTC, Ryukemeister requested changes
@T1sev4 ideally you don't need to push the `yarn.lock` file changes unless you add or remove a new dependency. Can you revert the `yarn.lock` file changes with the help of this guide https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md#guidelines-for-committing-yarn-lockfile

2024-05-08 12:31 UTC, keithwillcode commented
Closing due to staleness. Please reopen if work will continue.

2024-05-08 12:31 UTC, closed without merging