feat: isPlatform toggle during org creation
calcom/cal.com pull request #14284
Opened 2024-04-02 08:49 UTC by supalarry

Platform orgs are setup manually, so add a toggle that sets "Team.isPlatform" when creating the org. By default it is false:

<img width="1707" alt="Screenshot 2024-04-02 at 10 44 40" src="https://github.com/calcom/cal.com/assets/42170848/951e62ca-74f2-43cd-9fb4-95dd9fd8e873">

Platform org in database has "isPlatform" true:
<img width="1378" alt="Screenshot 2024-04-02 at 10 45 04" src="https://github.com/calcom/cal.com/assets/42170848/5e68fe1e-3fae-4d49-957f-69104f6e808e">

After this "settings/organizations/platform/oauth-clients" can be browsed to create client and because org has "isPlatform" client creation is successful. Non platform orgs can't create OAuth clients.

2024-04-02 09:56 UTC, ThyMinimalDev approved these changes

2024-04-02 10:01 UTC, sean-brydon commented
Do you think this could wait till https://github.com/calcom/cal.com/pull/13139 is merged? 

We can handle this only in the admin view in this PR instead of this PR being anyone can create a org with this as its a public URL

cc: @hariombalhara

2024-04-02 10:15 UTC, supalarry commented
> Do you think this could wait till #13139 is merged?
> 
> We can handle this only in the admin view in this PR instead of this PR being anyone can create a org with this as its a public URL
> 
> cc: @hariombalhara

@sean-brydon do you know estimated time to merge #13139 ? Also, I am not sure i followed "We can handle this only in the admin view in this PR instead of this PR being anyone can create a org with this as its a public URL" - so is there a way to accomplish what this PR does before yours gets merged? I didn't understand the connection to the public URL since only admins can create orgs, and non-admins can visit this page but can't actually create org.

2024-04-02 10:52 UTC, hariombalhara commented
Soon, a regular user will be able to create an org.

2024-04-02 10:58 UTC, PeerRich commented on packages/features/ee/organizations/components/CreateANewOrganizationForm.tsx
> +        </div>
is this for admins only? if yes, it should be wrapped in isAdmin

if this is for self-serve too, we should instead build a self-serve checkout for platform customerss

2024-04-02 10:59 UTC, PeerRich requested changes

2024-04-02 10:59 UTC, PeerRich commented on packages/features/ee/organizations/components/CreateANewOrganizationForm.tsx
> +        </div>
https://app.cal.com/settings/platform/new can reuse some of the same UI but is more tailored towards platform inputs

2024-04-02 11:15 UTC, sean-brydon commented
> > Do you think this could wait till #13139 is merged?
> > We can handle this only in the admin view in this PR instead of this PR being anyone can create a org with this as its a public URL
> > cc: @hariombalhara
> 
> @sean-brydon do you know estimated time to merge #13139 ? Also, I am not sure i followed "We can handle this only in the admin view in this PR instead of this PR being anyone can create a org with this as its a public URL" - so is there a way to accomplish what this PR does before yours gets merged? I didn't understand the connection to the public URL since only admins can create orgs, and non-admins can visit this page but can't actually create org.

Sorry i made no sense lol.

Hopefully we can get the migration PR merged pretty soon. Just concerned about this as in that PR this page isnt just for admins only and we'd have to fix it while merging with this branch.

2024-04-03 13:33 UTC, sean-brydon commented
@supalarry we have merged self serve 🙏

2024-04-16 12:13 UTC, closed without merging