fix: update playwright config to allow permissions
calcom/cal.com pull request #14526
Opened 2024-04-11 12:56 UTC by sean-brydon

## What does this PR do?

Grants clipboard permissions to chromium 

Fixes #14487 CAL-3379

2024-04-11 13:12 UTC, emrysal approved these changes

2024-04-11 18:48 UTC, zomars requested changes
Something weird is happening in all e2e tests with change:
<img width="345" alt="image" src="https://github.com/calcom/cal.com/assets/3504472/f64c64c0-fe0a-4349-af77-8a39631fd0f5">

![This Is Fine Fire GIF](https://media.tenor.com/PR6r2JSRpIYAAAAC/this-is-fine-fire.gif)

2024-04-11 18:50 UTC, sean-brydon commented
> Something weird is happening in all e2e tests with change: <img alt="image" width="345" src="https://private-user-images.githubusercontent.com/3504472/321749081-f64c64c0-fe0a-4349-af77-8a39631fd0f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4NjE3MDUsIm5iZiI6MTcxMjg2MTQwNSwicGF0aCI6Ii8zNTA0NDcyLzMyMTc0OTA4MS1mNjRjNjRjMC1mZTBhLTQzNDktYWY3Ny04YTM5NjMxZmQwZjUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTFUMTg1MDA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjI3NDhjMzhlNTRlNjM0Mzc0YjliNjE2N2Y3MmU4OWM5NTUyZTA4NjQwMjIxNTNiZGYyYjRmNTRjNTMyY2FkZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.neC_e7NNL3xLpBNXaQn0wxlCfe_nQf3FERxhr28XeZI">
> 
> ![This Is Fine Fire GIF](https://camo.githubusercontent.com/88ef09d0043efb7896f1f15e952f78a94f15b8543479872bda21f9c6a534459c/68747470733a2f2f6d656469612e74656e6f722e636f6d2f50523672324a535270495941414141432f746869732d69732d66696e652d666972652e676966) [ ![This Is Fine Fire GIF](https://camo.githubusercontent.com/88ef09d0043efb7896f1f15e952f78a94f15b8543479872bda21f9c6a534459c/68747470733a2f2f6d656469612e74656e6f722e636f6d2f50523672324a535270495941414141432f746869732d69732d66696e652d666972652e676966) ](https://camo.githubusercontent.com/88ef09d0043efb7896f1f15e952f78a94f15b8543479872bda21f9c6a534459c/68747470733a2f2f6d656469612e74656e6f722e636f6d2f50523672324a535270495941414141432f746869732d69732d66696e652d666972652e676966) [ ](https://camo.githubusercontent.com/88ef09d0043efb7896f1f15e952f78a94f15b8543479872bda21f9c6a534459c/68747470733a2f2f6d656469612e74656e6f722e636f6d2f50523672324a535270495941414141432f746869732d69732d66696e652d666972652e676966)

:O will look tomorrow - this worked for me locally

2024-04-12 09:21 UTC, sean-brydon commented
@zomars i re-ran E2E and they all work fine - the E2E failure message was that it couldnt find the database url in the builds. 

Seems to have fixed itself

2024-04-12 21:13 UTC, zomars approved these changes

2024-04-12 21:13 UTC, merged