feat: "Add an Override" calendar starts with the day specified in general settings
calcom/cal.com pull request #14663
Opened 2024-04-19 05:07 UTC by shaik-zeeshan

…al settings

## What does this PR do?

Fixes #14334

Before, Add an Override calendar in Availability page starts with Sunday
![Screen Shot 2024-04-19 at 10 26 59 AM](https://github.com/calcom/cal.com/assets/145040231/a3c7e1f2-82d4-4db3-84ee-6677ed81db04)

After, calendar starts with day user has specified in general settings
![Screen Shot 2024-04-19 at 10 27 18 AM](https://github.com/calcom/cal.com/assets/145040231/514285de-6805-481b-8d5e-38062333b0b0)

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

2024-04-19 05:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/calcom/cal.com?pullRequest=14663) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/calcom/cal.com?pullRequest=14663) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/calcom/cal.com?pullRequest=14663) it.</sub>

2024-04-26 15:10 UTC, joeauyeung requested changes
Great work so far @shaik-zeeshan!

One thing I would like to see before merging is when editing an override,  we should also use the user's `weekStart`

2024-04-26 16:00 UTC, shaik-zeeshan commented
i have update the edit calendar to use user's weekday  @joeauyeung 
![Screenshot 2024-04-26 at 9 22 34 PM](https://github.com/calcom/cal.com/assets/145040231/5ea5fd0c-c898-4e0b-8aeb-36fb1f8b5e19)

2024-05-06 19:34 UTC, joeauyeung approved these changes
Thanks for addressing the feedback and your contribution @shaik-zeeshan

2024-05-06 22:00 UTC, merged