feat: Add ratings to insights
calcom/cal.com pull request #14687
Opened 2024-04-21 20:59 UTC by alishaz-polymath

## What does this PR do?

This PR adds rating feedback metrics to insights. Following are the screenshots with various metrics added:

![image](https://github.com/calcom/cal.com/assets/52925846/2b391a05-0d39-4f91-830f-10b0f3c0213c)

![image](https://github.com/calcom/cal.com/assets/52925846/b7e1b6c3-a9ef-40c0-b458-c3aa45ea3e63)

![image](https://github.com/calcom/cal.com/assets/52925846/04f66fff-8ecd-4fc2-9fbf-90ab057013b8)

Fixes # (issue)

## Requirement/Documentation

- If there is a requirement document, please, share it here.
- If there is a UI/UX design document, please, share it here.

## Type of change

- Bug fix (non-breaking change which fixes an issue)
- Chore (refactoring code, technical debt, workflow improvements)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Tests (Unit/Integration/E2E or any other test)
- This change requires a documentation update

## How should this be tested?

- Are there environment variables that should be set?
- What are the minimal test data to have?
- What is expected (happy path) to have (input and output)?
- Any other important info that could help to test that PR

## Mandatory Tasks

- [ ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist

- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my PR needs changes to the documentation
- I haven't checked if my changes generate no new warnings
- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

2024-04-22 04:25 UTC, alishaz-polymath reviewed
Self review added. It's all self explanatory and easy to follow tbh

2024-04-22 04:25 UTC, alishaz-polymath commented on packages/features/insights/components/HighestNoShowHostTable.tsx
> +    <></>
We only show it if there's actual useful data here

2024-04-22 04:25 UTC, alishaz-polymath commented on packages/features/insights/components/HighestRatedMembersTable.tsx
> +    <></>
Again, show the table only if there's actual data in here

2024-04-22 04:25 UTC, alishaz-polymath commented on packages/features/insights/components/LowestRatedMembersTable.tsx
> +    <></>
Same as above, show only when there's useful data in here

2024-04-22 04:25 UTC, alishaz-polymath commented on packages/features/insights/components/FeedbackTable.tsx
> +            <EmptyScreen Icon="zap" headline={t("no_ratings")} description={t("no_ratings_description")} />
We use this empty screen if there are no ratings to let users know what to do to enable this

2024-04-22 04:25 UTC, alishaz-polymath commented on packages/prisma/migrations/20240419114622_add_ratings_to_insights/migration.sql
> +LEFT JOIN users u ON u.id = "Booking"."userId";
Can only create or replace a view, not edit it currently

2024-04-22 04:25 UTC, alishaz-polymath commented on packages/prisma/schema.prisma
> +  noShowHost     Boolean?
3 new columns added for rating and noshow

2024-04-22 04:25 UTC, alishaz-polymath commented on packages/features/insights/server/trpc-router.ts
> +  },
defaults

2024-04-22 08:51 UTC, emrysal commented on packages/features/insights/components/HighestNoShowHostTable.tsx
> +      enabled: !!(initialConfig?.teamId || initialConfig?.userId || initialConfig?.isAll),
The earlier de-structuring makes me suspect this doesn't work, needs clarification.

2024-04-22 08:53 UTC, emrysal requested changes, later dismissed
Looks 👍 , just implement getUserAvatar and good to go.

2024-04-22 09:09 UTC, Udit-takkar reviewed
@alishaz-polymath how should we handle this case?

 In a collective team event type where multiple team members are fixed hosts. Rating is given to only one host
 
<img width="648" alt="Screenshot 2024-04-22 at 2 39 20 PM" src="https://github.com/calcom/cal.com/assets/53316345/a9ccd4a8-0dc4-4e7b-9092-2a1208ed3ed6">

2024-04-22 09:13 UTC, Udit-takkar commented on packages/features/insights/server/trpc-router.ts
> +        if (typeof booking.userId === "number" && !userIds.includes(booking.userId)) {
NIT:
```suggestion
        if (!!booking.userId && !userIds.includes(booking.userId)) {
```

2024-04-22 09:31 UTC, alishaz-polymath commented
> @alishaz-polymath how should we handle this case?
> 
> In a collective team event type where multiple team members are fixed hosts. Rating is given to only one host
> <img alt="Screenshot 2024-04-22 at 2 39 20 PM" width="648" src="https://private-user-images.githubusercontent.com/53316345/324400521-a9ccd4a8-0dc4-4e7b-9092-2a1208ed3ed6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3Nzg0MTEsIm5iZiI6MTcxMzc3ODExMSwicGF0aCI6Ii81MzMxNjM0NS8zMjQ0MDA1MjEtYTljY2Q0YTgtMGRjNC00ZTdiLTkwOTItMmExMjA4ZWQzZWQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDA5MjgzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjNTE5MDBkNGRjOWYwZjIyYmJhZDIwMjA1NDljNDQ1OWUyNTE2NWJlNjY0MjU2YTNjNGM0YzFiOTI3NTZkZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ktv6yO7x9r4HvtdFV6hnMy0CvQfTfzDCX5dAIttL5uE">

I was wondering about that this morning. I think the best way would be to just forward that to each host I think, so a collective event marked well should reflect the same rating to each individual, and vice-versa. Another thing I was thinking of was, multiple attendees, each attendee giving a new feedback. Currently, we would simply overwrite it. So I think we need a follow up to handle more than one hosts & more than one attendees logic, with proper RFC.

2024-04-22 09:51 UTC, emrysal submitted a review, later dismissed
lgtm

2024-04-22 10:01 UTC, PeerRich submitted a review, later dismissed

2024-04-22 10:01 UTC, PeerRich commented on packages/features/insights/components/FeedbackTable.tsx
> +            <EmptyScreen Icon="zap" headline={t("no_ratings")} description={t("no_ratings_description")} />
NIT: maybe a button that links to "/workflows" and a "learn more" with a link to docs how to set up ratings

2024-04-22 10:01 UTC, keithwillcode commented
@alishaz-polymath how did this perform locally when having lots of insights data?

2024-04-22 10:01 UTC, alishaz-polymath commented
> Instead of NoShowHost lets call this "No-Show (Host)"

Where specifically? All user facing elements?

2024-04-22 10:02 UTC, alishaz-polymath commented
> @alishaz-polymath how did this perform locally when having lots of insights data?

Haven't tested against that yet.

2024-04-22 10:07 UTC, alishaz-polymath commented
> > > @alishaz-polymath how did this perform locally when having lots of insights data?
> > 
> > 
> > Haven't tested against that yet.
> 
> Ok reminder there’s a seed script to populate lots of data for insights testing.

I wasn't aware of it, will test 🙏
Thank you!!

2024-04-22 13:47 UTC, alishaz-polymath commented
> @alishaz-polymath how did this perform locally when having lots of insights data?

@keithwillcode Looks good
![Uploading image.png…]()

I have also updated the script to include new data

2024-04-23 21:40 UTC, PeerRich reviewed
great work. excited for this

2024-04-26 10:58 UTC, sean-brydon approved these changes
Tested locally - works well. Nice job! 

Few NITS but nothing blocking

2024-04-26 10:58 UTC, sean-brydon commented on packages/features/insights/components/TotalUserFeedbackTable.tsx
> +      }[]
NIT lets extract this type - its used elsewhere too

2024-04-26 10:58 UTC, sean-brydon commented on packages/features/insights/components/FeedbackTable.tsx
> +      }[]
nit: Same here

2024-04-26 10:58 UTC, sean-brydon commented on packages/features/insights/components/LowestRatedMembersTable.tsx
> +  return data && data.length > 0 ? (
Shall we early return so we dont need this tenery ?

2024-04-26 10:58 UTC, merged