Feat/date range picker
calcom/cal.com pull request #14713
Opened 2024-04-23 08:58 UTC by sean-brydon

Replace with the new date-range-picker that works in safari 

Matches DS here: https://www.figma.com/file/9MOufQNLtdkpnDucmNX10R/Cal-DS---Components?type=design&node-id=30050-112293&mode=dev

Fixes: CAL-3498
Fixes: #14661

2024-04-23 09:23 UTC, sean-brydon commented on packages/ui/package.json
> +    "date-fns": "^3.6.0",
We already have this as part of a peer-dep for tremor. But we need this as a dependancy as react-day-picker needs it.

2024-04-23 09:24 UTC, sean-brydon commented on packages/ui/components/form/date-range-picker/Calendar.tsx
> +function Calendar({ className, classNames, showOutsideDays = true, ...props }: CalendarProps) {
https://ui.shadcn.com/docs/components/calendar

Matches our DS with shadcn calendar component

2024-04-23 09:25 UTC, sean-brydon commented on apps/web/pages/settings/my-account/out-of-office/index.tsx
> +                  render={({ field: { onChange, value } }) => (
Lets actually use the controller fields instead of getValues etc

2024-04-23 09:25 UTC, sean-brydon commented on apps/web/components/settings/TravelScheduleModal.tsx
> +                  // If newStartDate does become undefined - we resort back to to-todays date
@CarinaWolli can you test this all works as you expect - (i tested locally and it seems to be fine) 

undefined doesnt ever happen so this shouldnt be an issue

2024-04-23 11:11 UTC, Udit-takkar reviewed
<img width="320" alt="Screenshot 2024-04-23 at 4 41 09 PM" src="https://github.com/calcom/cal.com/assets/53316345/11d032c9-e55a-4e5a-98e5-560dd9e79ebf">

slight overflow in mobile

2024-04-23 11:13 UTC, Udit-takkar commented
there should be a close button to close calendar after selection

2024-04-23 15:09 UTC, CarinaWolli requested changes, later dismissed
The DateRangePicker is not working in Dialogs. It's not working for adding a travel schedule or OOO
Loom: https://www.loom.com/share/56480d737a714fb18aaa04f2f5df2c82

2024-04-24 08:49 UTC, sean-brydon commented
> The DateRangePicker is not working in Dialogs. It's not working for adding a travel schedule or OOO Loom: https://www.loom.com/share/56480d737a714fb18aaa04f2f5df2c82

@CarinaWolli please let me know chrome version etc - myself and Udit can't replicate the issues you are seeing

2024-04-25 10:27 UTC, Udit-takkar approved these changes

2024-04-26 13:38 UTC, merged