feat: skype app added
calcom/cal.com pull request #14751
Opened 2024-04-25 11:23 UTC by anikdhabal

## What does this PR do?

Fixes #14747

2024-05-27 09:45 UTC, SomayChauhan reviewed
I'm curious if it's possible to implement OAuth login for Skype and automatically generate a meeting link, similar to what is available with Google Meet and Zoom.

2024-05-27 11:47 UTC, PeerRich commented on packages/app-store/skype/static/2.jpeg
this image is skewed, lets use only screenshots here

2024-05-27 11:47 UTC, PeerRich approved these changes

2024-05-27 11:48 UTC, PeerRich commented
> I'm curious if it's possible to implement OAuth login for Skype and automatically generate a meeting link, similar to what is available with Google Meet and Zoom.

that could be a cool v2 of this app

2024-05-28 17:49 UTC, keithwillcode requested changes, later dismissed
Per @SomayChauhan and @PeerRich request, let's update to the OAuth implementation

2024-05-28 17:51 UTC, anikdhabal commented
> Per @SomayChauhan and @PeerRich request, let's update to the OAuth implementation

Sure @keithwillcode

2024-06-16 15:38 UTC, anikdhabal commented
Hey @PeerRich @SomayChauhan There was no API reference or authorization documentation for Skype. I read somewhere that Skype discontinued its API in 2013.

2024-07-03 09:44 UTC, hariombalhara commented
I think Skype for Business does provide its OAuth API through azure portal. 

@keithwillcode What should we do here? I am thinking that we let it merge and improve upon it as per the usage and requirements.

2024-07-22 07:49 UTC, keithwillcode commented
> I think Skype for Business does provide its OAuth API through azure portal.
> 
> @keithwillcode What should we do here? I am thinking that we let it merge and improve upon it as per the usage and requirements.

Sorry for the delay here. Yeah that's fine, @hariombalhara 🙏

2024-07-23 09:34 UTC, hariombalhara approved these changes

2024-07-23 09:39 UTC, merged