FIX #14875 : Fixed Scrollable overlay AddActionDialog Component
calcom/cal.com pull request #14876
Opened 2024-05-04 18:50 UTC by priyank-1

## What does this PR do?

This PR fixes a bug that the UI was breaking in AddActionDialog on reducing the window height 

Fixes #14875 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

1.Go to 'Workflow' -> Add/Update a workflow
2.Click on 'Add action'
3.Reduce the browser window height manually or from responsive view in Chrome DevTools and notice that partial information is shown to the user.

## Mandatory Tasks

- [ ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist

2024-05-04 18:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/calcom/cal.com?pullRequest=14876) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/calcom/cal.com?pullRequest=14876) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/calcom/cal.com?pullRequest=14876) it.</sub>

2024-05-05 17:14 UTC, utkershrajvenshi requested changes
Need to rework this fix using tailwind classes, since in the repo we're relying on it primarily for styling css

2024-05-05 17:14 UTC, utkershrajvenshi commented on package.json
> +    "turbo-http": "^0.3.2"
What could be the reason for this dependency addition?

2024-05-05 17:14 UTC, utkershrajvenshi commented on packages/features/ee/workflows/components/scrollable.css
> +.scrollable-content {
We should have implemented this fix using Tailwind's utility classes instead of traditional CSS.

2024-05-06 13:56 UTC, CarinaWolli commented
Closing this, because https://github.com/calcom/cal.com/pull/14892 has a better fix for this. Thank you for your effort 🙏

2024-05-06 13:56 UTC, closed without merging