feat: use tokens for public mutating endpoints
calcom/cal.com pull request #14946
Opened 2024-05-08 15:13 UTC by anikdhabal

## What does this PR do?

- Fixes #14342 
- Fixes CAL-XXXX (Linear issue number - should be visible at the bottom of the GitHub issue description)

## Mandatory Tasks (DO NOT REMOVE)

- [ ] I have self-reviewed the code (A decent size PR without self-review might be rejected)
- [ ] I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com)
- [ ] I have added or modified automated tests that prove my fix is effective or that my feature works (PRs might be rejected if logical changes are not properly tested)

## How should this be tested?

- Are there environment variables that should be set?
- What are the minimal test data to have?
- What is expected (happy path) to have (input and output)?
- Any other important info that could help to test that PR

## Checklist

- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my changes generate no new warnings

2024-05-08 15:17 UTC, anikdhabal commented
This is one of many. @zomars @alishaz-polymath could you guys give feedback?

2024-05-09 19:21 UTC, anikdhabal commented
This is one of many. @zomars @alishaz-polymath could you guys give feedback?

2024-06-05 18:35 UTC, anikdhabal commented
cc @zomars

2024-07-03 09:35 UTC, hariombalhara requested changes, later dismissed
I am a bit confused here. Why are we adding tokens everywhere? I think the issue meant to add this for `noShow` and `submitRating` which are newly added mutations and so that an unauthorized person can't update these as the links are sent in an email

2024-08-01 19:27 UTC, zomars requested changes
Thanks for the initiative @Amit91848 Left some feedback to address. 🙏

2024-08-01 19:27 UTC, zomars commented on apps/web/components/booking/BookingListItem.tsx
> +    noShowMutation.mutate({ token });
Encryption shouldn't happen on client side. Also `process.env.CALENDSO_ENCRYPTION_KEY` is not available in browsers for the same reason.

2024-08-01 19:27 UTC, zomars commented on apps/web/components/booking/BookingListItem.tsx
> +    );
Same here.

2024-08-14 19:32 UTC, zomars requested changes
> I am a bit confused here. Why are we adding tokens everywhere? I think the issue meant to add this for `noShow` and `submitRating` which are newly added mutations and so that an unauthorized person can't update these as the links are sent in an email

I'm also quite a bit confused. I want to clear up some things about the purpose of the original issue. @hariombalhara @anikdhabal 

The noShow and and submitRating handlers introduced in #14215 are public and don't have any kind of logged in user protections.

Anyone who knows a booking uid can submit ratings and comments to the exposed endpoint which is not desirable. Since these are supposed to come from an email link. We should generate a token to the sent email and pass it back when click that link. That way we know that the link came from the sent email.

We did something similar with the confirmation emails in #6151 

The idea is to use the same approach to mark bookings as noShow and rating.

Having said this my proposal is this:

- Have a protected noShow and submitRating mutations in tRPC that requires the user to be logged in to use it.
- Have the same as public endpoints that requires an ecrypted `token` parameter that are going to be used from the email links as made in #6151.

The current implementation is not achieving the desired solution.

2024-08-14 19:33 UTC, zomars commented
I'm going to re-draft until concerns are addressed. Feel free to mark as ready and ask for re-review until then.

2024-08-15 03:15 UTC, anikdhabal commented
Thanks for the explanation, @zomars. Got it; I will update that shortly.

2025-03-10 00:58 UTC, emrysal commented
Closing this as stale for now, branch still exists so please re-open when you pick up @anikdhabal 🙏

2025-03-10 00:58 UTC, closed without merging