chore: Add test for booking cancelled webhook
calcom/cal.com pull request #14940
Opened 2024-05-08 10:56 UTC by Amit91848

## What does this PR do?

Fixes #14886 
Fixes CAL-3641

## Type of change

- Tests (Unit/Integration/E2E or any other test)

## How should this be tested?

`yarn test cancel.test.ts
`

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

2024-05-10 12:43 UTC, Udit-takkar requested changes
@Amit91848 we wanted unit tests here. one of the contributor created this function expectBookingCancelledWebhookToHaveBeenFired (https://github.com/calcom/cal.com/pull/14745/files) which we can use.

2024-05-13 13:11 UTC, Udit-takkar commented on apps/web/playwright/webhook.e2e.ts
> +test.describe("BOOKING_CANCELLED", async () => {
can you remove this E2E test?

2024-05-13 13:12 UTC, Udit-takkar commented on packages/features/bookings/lib/handleNewBooking/test/cancel.test.ts
> +
you need to add some assertions to make sure booking was created successfully.

2024-05-13 13:16 UTC, Udit-takkar commented on packages/features/bookings/lib/handleNewBooking/test/cancel.test.ts
> +
you can check other unit test

2024-05-14 07:12 UTC, Amit91848 commented
Unit test passes but there is an error thrown when cancelling scheduled jobs

When booking is created scheduledJobs is null
https://github.com/Amit91848/cal.com/blob/87a260eba39c059f2626d6257a0d2dcb79f05986/packages/features/bookings/lib/handleNewBooking/test/cancel.test.ts#L101

![Screenshot 2024-05-14 at 12 37 10 PM](https://github.com/calcom/cal.com/assets/74371312/28cfc1c9-0a10-4974-9cb2-02d675828298)


But when you fetch it from database it converts to an object?? Like here
https://github.com/Amit91848/cal.com/blob/87a260eba39c059f2626d6257a0d2dcb79f05986/packages/features/bookings/lib/handleNewBooking/test/cancel.test.ts#L112-L118
![Screenshot 2024-05-14 at 12 38 28 PM](https://github.com/calcom/cal.com/assets/74371312/b5b617e2-54f6-49c6-b35e-1621186d147c)

2024-05-17 13:38 UTC, Udit-takkar commented on packages/features/bookings/lib/handleCancelBooking/test/webhook.test.ts
> +          timeZone: organizer.timeZone,
I added this new test instead. 

we just wanted to test booking cancelled so i just created a dummy booking using `getScenarioData` and also you skipped checking if organizer id is passed in payload which is the main thing that needs to be checked

2024-05-17 13:38 UTC, Udit-takkar approved these changes

2024-05-17 13:56 UTC, merged