fix: broken url on booking page
calcom/cal.com pull request #15028
Opened 2024-05-14 13:46 UTC by Udit-takkar

## What does this PR do?

- Fixes https://github.com/calcom/cal.com/issues/15021
- Fixes CAL-3702 (Linear issue number - should be visible at the bottom of the GitHub issue description)

Regression from https://github.com/calcom/cal.com/pull/14777/files.

## Mandatory Tasks (DO NOT REMOVE)

- [ ] I have self-reviewed the code (A decent size PR without self-review might be rejected)
- [ ] I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com)
- [ ] I have added or modified automated tests that prove my fix is effective or that my feature works (PRs might be rejected if logical changes are not properly tested)

## How should this be tested?

1) Go to any team event type url and make sure team logo is not visible. (for non org event types)

2024-05-14 13:47 UTC, Udit-takkar commented on packages/features/bookings/components/event-meta/Members.tsx
> +      ]
This was only meant for org event types and not normal event types

2024-05-14 18:58 UTC, zomars approved these changes

2024-05-16 20:38 UTC, zomars submitted a review, later dismissed
We're having merge conflicts now. @Udit-takkar Can you take a look?

2024-05-22 10:41 UTC, hariombalhara commented on packages/features/bookings/components/event-meta/Members.tsx
>            ...shownUsers.map((user) => ({
`shownUsers` is empty array for a non-org user event. That should also be fixed. We should show the user avatar for such an event and that should take to the user profile page.

This is what the reporter also mentioned here.
![image](https://github.com/calcom/cal.com/assets/1780212/a5fd2bd4-d6fe-42b4-8ff4-106bc6af4755)

2024-05-22 10:42 UTC, hariombalhara requested changes, later dismissed
Left a blocking comment otherwise it is good.

2024-05-22 14:17 UTC, hariombalhara approved these changes

2024-05-22 14:18 UTC, hariombalhara commented
Approved but let's add a test for this in a follow-up

2024-05-23 16:17 UTC, merged