fix: bookings made via API don't include the specified location
calcom/cal.com pull request #15067
Opened 2024-05-16 06:33 UTC by Shaik-Sirajuddin

## What does this PR do?

- Fixes #14341 and #15059  (GitHub issue number)
- Fixes CAL-3360 (Linear issue number - should be visible at the bottom of the GitHub issue description)

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected)
- [ ] I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com)
- [ ] I have added or modified automated tests that prove my fix is effective or that my feature works (PRs might be rejected if logical changes are not properly tested)

## How should this be tested?

- #14341
- Create an event in profile with location set to conferencing or option of choice
- Create a booking for just created event via API , leaving location blank or unspecified
- View bookings page , the location used for booking will be the one specified in event or users default
- #15059 
- Create a new user account , a new user account has default events with no location set
- Update default conferencing app in profile settings , reject bulk update event option
- Book an event of newly created account via alternative account
- Booking will use users default conferencing app if events default is not available 
## Checklist

- I haven't checked if my changes generate no new warnings

2024-05-23 05:30 UTC, Shaik-Sirajuddin commented
Loom Videos were commented out earlier.
Video links are now available in description for easier review.

2024-06-04 07:30 UTC, sean-brydon requested changes, later dismissed
Hey @Shaik-Sirajuddin I have manually tested this and it works pretty well. 

Do you think you could expand our tests to cover this edge case? 
Off the top of my head `fresh-booking.test.ts` will be the test fill that needs this edge case adding to

2024-06-05 09:43 UTC, Shaik-Sirajuddin commented
> Hey @Shaik-Sirajuddin I have manually tested this and it works pretty well.
> 
> Do you think you could expand our tests to cover this edge case? Off the top of my head `fresh-booking.test.ts` will be the test fill that needs this edge case adding to

Hi @sean-brydon
As suggested , I have added tests to cover the cases when location is not specified.
A fix for a failing test case has also been implemented.
PTAL

2024-06-05 09:45 UTC, Shaik-Sirajuddin commented on packages/features/bookings/lib/handleNewBooking/test/team-bookings/collective-scheduling.test.ts
> +            location: BookingLocations.CalVideo,
webook responses contains exact location of booking
which is calvideo in this case

2024-06-11 17:01 UTC, emrysal approved these changes
Looks good to me, happy to merge 🙏  - thank you for adding the tests

2024-06-11 17:20 UTC, merged