fix: trigger workflow only for first recurring event
calcom/cal.com pull request #15128
Opened 2024-05-20 14:00 UTC by CarinaWolli

## What does this PR do?

This fixes that a workflow with the 'when new event is booked' trigger is only triggered for the first recurring event

2024-05-21 10:12 UTC, sean-brydon requested changes
![CleanShot 2024-05-21 at 11 11 23](https://github.com/calcom/cal.com/assets/55134778/5073ed3d-2b1c-48ba-a0d2-7ff7dacbbce6)

Hey @CarinaWolli i just tested this and it doesnt seem to work as i am still getting all the emails per scheduled event - am i misunderstanding something

2024-05-21 15:02 UTC, CarinaWolli commented on packages/features/ee/workflows/lib/reminders/reminderScheduler.ts
> +    isFirstRecurringEvent = true,
@Udit-takkar  `isFirstRecurringEvent` should default to `true` if it is normal event and not recurring. Why? The first recurring event is handled the same as a normal event

2024-05-22 16:12 UTC, CarinaWolli commented
> ![CleanShot 2024-05-21 at 11 11 23](https://private-user-images.githubusercontent.com/55134778/332381638-5073ed3d-2b1c-48ba-a0d2-7ff7dacbbce6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzOTQ0NDIsIm5iZiI6MTcxNjM5NDE0MiwicGF0aCI6Ii81NTEzNDc3OC8zMzIzODE2MzgtNTA3M2VkM2QtMmIxYy00OGJhLWEwZDItN2ZmN2RhY2JiY2U2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDE2MDkwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjMjQxMGQ2NjQwNDQ1NzM3NjNiZmRlZTc4NzljNTYxYzY4MTE4YzVkNGViNDQ3ZDdhODQ1MjE4NDk4ODZjYjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aoHlY73uyP2KY-VIBCC9PlyPsac6c-WULoAeodD08EQ)
> 
> Hey @CarinaWolli i just tested this and it doesnt seem to work as i am still getting all the emails per scheduled event - am i misunderstanding something

@sean-brydon is that a workflow email? looks like the broken integration email

2024-05-31 09:42 UTC, sean-brydon commented
> > ![CleanShot 2024-05-21 at 11 11 23](https://private-user-images.githubusercontent.com/55134778/332381638-5073ed3d-2b1c-48ba-a0d2-7ff7dacbbce6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzOTQ0NDIsIm5iZiI6MTcxNjM5NDE0MiwicGF0aCI6Ii81NTEzNDc3OC8zMzIzODE2MzgtNTA3M2VkM2QtMmIxYy00OGJhLWEwZDItN2ZmN2RhY2JiY2U2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDE2MDkwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjMjQxMGQ2NjQwNDQ1NzM3NjNiZmRlZTc4NzljNTYxYzY4MTE4YzVkNGViNDQ3ZDdhODQ1MjE4NDk4ODZjYjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aoHlY73uyP2KY-VIBCC9PlyPsac6c-WULoAeodD08EQ)
> > Hey @CarinaWolli i just tested this and it doesnt seem to work as i am still getting all the emails per scheduled event - am i misunderstanding something
> 
> @sean-brydon is that a workflow email? looks like the broken integration email

Sorry for the late reply on this - slipped my inbox. 

I've just tested this again and im seeing the same issue :/ I logged out and send email is still being called N times for the number of recuring events so im not sure its something to do with the email integration 🤔  Will have a dig around

2024-05-31 13:53 UTC, CarinaWolli commented
> > > ![CleanShot 2024-05-21 at 11 11 23](https://private-user-images.githubusercontent.com/55134778/332381638-5073ed3d-2b1c-48ba-a0d2-7ff7dacbbce6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzOTQ0NDIsIm5iZiI6MTcxNjM5NDE0MiwicGF0aCI6Ii81NTEzNDc3OC8zMzIzODE2MzgtNTA3M2VkM2QtMmIxYy00OGJhLWEwZDItN2ZmN2RhY2JiY2U2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDE2MDkwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjMjQxMGQ2NjQwNDQ1NzM3NjNiZmRlZTc4NzljNTYxYzY4MTE4YzVkNGViNDQ3ZDdhODQ1MjE4NDk4ODZjYjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aoHlY73uyP2KY-VIBCC9PlyPsac6c-WULoAeodD08EQ)
> > > Hey @CarinaWolli i just tested this and it doesnt seem to work as i am still getting all the emails per scheduled event - am i misunderstanding something
> > 
> > 
> > @sean-brydon is that a workflow email? looks like the broken integration email
> 
> Sorry for the late reply on this - slipped my inbox.
> 
> I've just tested this again and im seeing the same issue :/ I logged out and send email is still being called N times for the number of recuring events so im not sure its something to do with the email integration 🤔 Will have a dig around

That's weird. Could you provide the steps how you are testing it? 

That's how I test it:
1. Create a user event type and enable recurring events 
2. Create workflow with 'when new event is booked' trigger and 'email to attendee' action 
3. Set event type active on that workflow 
4. Book the event type with several recurrences
5. I have sendgrid for workflow emails set up, so I check if I received ONE workflow email only

2024-06-05 13:45 UTC, sean-brydon commented
> > > > ![CleanShot 2024-05-21 at 11 11 23](https://private-user-images.githubusercontent.com/55134778/332381638-5073ed3d-2b1c-48ba-a0d2-7ff7dacbbce6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzOTQ0NDIsIm5iZiI6MTcxNjM5NDE0MiwicGF0aCI6Ii81NTEzNDc3OC8zMzIzODE2MzgtNTA3M2VkM2QtMmIxYy00OGJhLWEwZDItN2ZmN2RhY2JiY2U2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDE2MDkwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjMjQxMGQ2NjQwNDQ1NzM3NjNiZmRlZTc4NzljNTYxYzY4MTE4YzVkNGViNDQ3ZDdhODQ1MjE4NDk4ODZjYjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aoHlY73uyP2KY-VIBCC9PlyPsac6c-WULoAeodD08EQ)
> > > > Hey @CarinaWolli i just tested this and it doesnt seem to work as i am still getting all the emails per scheduled event - am i misunderstanding something
> > > 
> > > 
> > > @sean-brydon is that a workflow email? looks like the broken integration email
> > 
> > 
> > Sorry for the late reply on this - slipped my inbox.
> > I've just tested this again and im seeing the same issue :/ I logged out and send email is still being called N times for the number of recuring events so im not sure its something to do with the email integration 🤔 Will have a dig around
> 
> That's weird. Could you provide the steps how you are testing it?
> 
> That's how I test it:
> 
> 1. Create a user event type and enable recurring events
> 2. Create workflow with 'when new event is booked' trigger and 'email to attendee' action
> 3. Set event type active on that workflow
> 4. Book the event type with several recurrences
> 5. I have sendgrid for workflow emails set up, so I check if I received ONE workflow email only

Well - it turns out there was an issue with my mail setup - had four containers running somehow and they were all receiving emails. 


Works fine now :D Sorry!

2024-06-05 13:45 UTC, sean-brydon approved these changes
LGTM

2024-06-06 18:50 UTC, merged