feat: add get recording API endpoint
calcom/cal.com pull request #15131
Opened 2024-05-20 15:14 UTC by Udit-takkar

## What does this PR do?

- Fixes #XXXX (GitHub issue number)
- Fixes CAL-XXXX (Linear issue number - should be visible at the bottom of the GitHub issue description)

## Mandatory Tasks (DO NOT REMOVE)

- [ ] I have self-reviewed the code (A decent size PR without self-review might be rejected)
- [ ] I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com)
- [ ] I have added or modified automated tests that prove my fix is effective or that my feature works (PRs might be rejected if logical changes are not properly tested)

2024-05-21 15:02 UTC, keithwillcode commented
@Udit-takkar None of the mandatory tasks are checked. Were you planning on doing them?

2024-05-21 16:49 UTC, zomars reviewed
Simple and clean. I love it. Some basic unit tests would be nice tho. You can use the ones at `apps/api/v1/test/lib/event-types/[id]/_get.test.ts` as reference.

2024-05-21 18:21 UTC, keithwillcode requested changes
Awaiting unit tests

2024-05-22 12:59 UTC, emrysal approved these changes
Happy with the new tests from my perspective :)

2024-05-22 13:04 UTC, keithwillcode approved these changes

2024-05-22 13:04 UTC, merged