feat: org-wide webhooks
calcom/cal.com pull request #15144
Opened 2024-05-21 09:17 UTC by kart1ka

## What does this PR do?

The org wide webhook works for user and team events for that org.

- Fixes #14827 
- Fixes CAL-3595

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected)
- [x] I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com)
- [ ] I have added or modified automated tests that prove my fix is effective or that my feature works (PRs might be rejected if logical changes are not properly tested)

## How should this be tested?

- Login using org owner credentials and go to the /settings/developer/webhooks page and click New Button to create a new webhook.
- Notice that org is also included in the list of teams. 
- Create a new webhook for the org.
- You can further test the webhook by creating bookings on user and/or team events.

2024-05-28 16:11 UTC, CarinaWolli requested changes
Nice work so far! Left some comments that need to be addressed first 🙏

2024-05-29 06:27 UTC, Udit-takkar reviewed
![Screenshot 2024-05-29 at 11 56 42 AM](https://github.com/calcom/cal.com/assets/53316345/65fb068d-8870-4ea8-b84a-f70b85e77808)

org wide webhook Instant meeting created works fine but it doesn't show up here in event type setting which could be confusing to some users.

2024-05-30 08:51 UTC, kart1ka commented on packages/features/bookings/lib/handleNewBooking.ts
> +export async function getOrgIdFromMemberOrTeamId(args: { memberId?: number | null; teamId?: number | null }) {
Moved `getOrgIdFromMemberOrTeamId` to a separate file in packages/lib

2024-05-30 09:13 UTC, kart1ka commented
> ![Screenshot 2024-05-29 at 11 56 42 AM](https://private-user-images.githubusercontent.com/53316345/334681293-65fb068d-8870-4ea8-b84a-f70b85e77808.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwNTg5NDUsIm5iZiI6MTcxNzA1ODY0NSwicGF0aCI6Ii81MzMxNjM0NS8zMzQ2ODEyOTMtNjVmYjA2OGQtODg3MC00ZWE4LWI4NGEtZjcwYjg1ZTc3ODA4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMwVDA4NDQwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiYjZhNWFiNmNjM2YyMjNjZDU5YzA1NzdmNzA2NWEyNzNlNzkzZmFjMzUxOWZiYjU1NzhlZDI4YzdmZTQ1M2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5ATbJ3IYlhVIkLyDdFW5Sfxn6lwK1O8YCEy1_hUlIvM)
> 
> org wide webhook Instant meeting created works fine but it doesn't show up here in event type setting which could be confusing to some users.

Hi @Udit-takkar 
As I understand, The "Instant Bookings" tab in the Event Type settings is designed to display the Instant Meeting Webhook added specifically to that Event Type. 

Team and Individual User Webhooks with the "Instant Meeting Created" trigger event are also not displayed in the Event Type settings.

Do let me know if you would still like Org-wide webhooks with the "Instant Meeting Created" trigger event to be displayed in the Instant Bookings tab.

2024-06-04 10:02 UTC, kart1ka commented
Hi @CarinaWolli 
Just wanted to check in on the status of this PR. I've made the changes you suggested. If there's anything else I need to do before merging, please let me know.

2024-06-04 14:55 UTC, CarinaWolli approved these changes
Awesome work @kart1ka 🙌🏻

2024-06-04 20:29 UTC, merged