feat: Link to rescheduled booking from the old one
calcom/cal.com pull request #15211
Opened 2024-05-27 19:15 UTC by Amit91848

## What does this PR do?

- Fixes #14707 
- Fixes CAL-3755

https://github.com/calcom/cal.com/assets/74371312/c7042dd7-51e7-4785-a964-2a29e354906e

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected)
- [ ] I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com)
- [ ] I have added or modified automated tests that prove my fix is effective or that my feature works (PRs might be rejected if logical changes are not properly tested)

2024-05-27 19:17 UTC, Amit91848 commented
Currently just adds it to notes, lmk if you want to have it as first class field

2024-05-31 10:49 UTC, SomayChauhan approved these changes, later dismissed
Tested, LGTM!!

2024-06-04 21:03 UTC, keithwillcode submitted a review, later dismissed
Would like sign off from @ciaranha / @PeerRich before we merge this.

2024-07-02 09:28 UTC, hariombalhara commented
I don't prefer updating the description on cancellation. `description` is a property of the booking that could have some existing value that gets overwritten in this way.

Why don't we simply use `fromReschedule` to identify the booking to which the cancelled booking has been scheduled. It should allow us to show the value on the booking details page.

2024-07-02 09:28 UTC, hariombalhara requested changes
I don't prefer updating the description on cancellation. `description` is a property of the booking that could have some existing value that gets overwritten in this way.

Why don't we simply use `fromReschedule` to identify the booking to which the cancelled booking has been scheduled. It should allow us to show the value on the booking details page.

2024-07-02 11:02 UTC, Amit91848 commented
> I don't prefer updating the description on cancellation. `description` is a property of the booking that could have some existing value that gets overwritten in this way.

Previous description is still present it just adds a line to it, but I get your point.

> Why don't we simply use `fromReschedule` to identify the booking to which the cancelled booking has been scheduled. It should allow us to show the value on the booking details page.

Will make changes to it

2024-07-08 07:47 UTC, Amit91848 commented
Made changes @hariombalhara , please review again


https://github.com/calcom/cal.com/assets/74371312/84df993b-a56b-4e69-9c5c-a90e3316dae9

2024-07-16 10:05 UTC, hariombalhara commented on apps/web/modules/bookings/views/bookings-single-view.tsx
> +                        )}
Let's move it out into it's own component within this module.

Possible name could be <RescheduledToLink>

```
{rescheduledToUid ? <RescheduledToLink>: null}
```

2024-07-16 16:47 UTC, Amit91848 commented on packages/features/bookings/lib/getRescheduledToBooking.tsx
> +  });
Done

2024-07-16 16:47 UTC, Amit91848 commented
> @Amit91848 Could you add the updated snapshot in the PR description.
> 
> We are also waiting for @ciaranha @PeerRich to approve it as well

Updated the description

2024-07-18 07:20 UTC, hariombalhara approved these changes, later dismissed
Looks good !!

@PeerRich @ciaranha Could you confirm the design here? Should be quick.

2024-07-22 22:19 UTC, ciaranha commented
Can we just edit the copy 

Change "Rescheduled to" to "Rescheduled". "Link to" to "View booking"

2024-07-23 06:02 UTC, Amit91848 commented
> Can we just edit the copy

Not sure wdym by that

> Change "Rescheduled to" to "Rescheduled". "Link to" to "View booking"

Changed the text @ciaranha

2024-07-23 10:35 UTC, ciaranha commented
> Not sure wdym by that

I just meant to update the text like you did :) (Update copy = Update text)

Thanks!

2024-07-23 11:06 UTC, hariombalhara approved these changes

2024-07-23 12:39 UTC, merged