fix: Booking Error - cannot be booked at this time
calcom/cal.com pull request #15288
Opened 2024-06-01 03:59 UTC by hariombalhara

## What does this PR do?

- Fixes #XXXX (GitHub issue number)
- Fixes CAL-XXXX (Linear issue number - should be visible at the bottom of the GitHub issue description)

## Mandatory Tasks (DO NOT REMOVE)

- [ ] I have self-reviewed the code (A decent size PR without self-review might be rejected)
- [ ] I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com)
- [ ] I have added or modified automated tests that prove my fix is effective or that my feature works (PRs might be rejected if logical changes are not properly tested)

## How should this be tested?

- Are there environment variables that should be set?
- What are the minimal test data to have?
- What is expected (happy path) to have (input and output)?
- Any other important info that could help to test that PR

## Checklist

- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my changes generate no new warnings

2024-06-01 03:59 UTC, hariombalhara commented
* **#15288** <a href="https://app.graphite.dev/github/pr/calcom/cal.com/15288?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @hariombalhara and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-06-01 04:00 UTC, hariombalhara commented on apps/web/test/lib/getSchedule/futureLimit.timezone.test.ts
> +    if (periodCountCalendarDays === undefined || !periodDays) {
To allow `false` value.

2024-06-01 04:01 UTC, hariombalhara commented on apps/web/test/lib/getSchedule/futureLimit.timezone.test.ts
Simplified the tests by not using  deprecated `getDate` function and instead mock a particular time to be able to test different sceanrios.

2024-06-01 04:01 UTC, hariombalhara commented on apps/web/test/utils/bookingScenario/bookingScenario.ts
> -      id: 1,
Wasn't used

2024-06-01 07:01 UTC, hariombalhara commented on packages/lib/isOutOfBounds.tsx
> +      return { rollingEndDay: rollingEndDay.endOf("day"), rangeStartDay: null, rangeEndDay: null };
Doing endOf('day') once.

2024-06-01 09:24 UTC, hariombalhara reviewed
Self review done

2024-06-03 13:51 UTC, joeauyeung approved these changes
Awesome find @hariombalhara.

Tested with the organizer set as New York and the booker as Pago Pago. Working as expected. 

I'm approving but I do have a comment about the optimization of filtering slots. It's not blocking but might be something to consider.

2024-06-03 14:25 UTC, hariombalhara commented
Regarding this https://github.com/calcom/cal.com/pull/15288#discussion_r1624498200

We were already doing that outOfBound check per timeslot before the future limit improvement. I had tried to optimize that in my previous PR and that approach had this bug that I fixed now.

But it is still better than earlier implementation as we stop as soon as we find the first violation of timeslot. Usually the future limit is a small number of days so we should stop early on.

Starting backwards won't work logically as we have to test for first few bookable time slots, there would always be bookable timeslots at the end but we don't want those. We only want the first ones

2024-06-03 14:26 UTC, hariombalhara commented
Thanks for the quick review @joeauyeung 🙏

2024-06-03 15:03 UTC, CarinaWolli requested changes
I see a bug with 'Limit future bookings' when testing locally, see loom: https://www.loom.com/share/250ab868612547a8bcec4450b964b94f

2024-06-03 15:17 UTC, joeauyeung commented
> I see a bug with 'Limit future bookings' when testing locally, see loom: [loom.com/share/250ab868612547a8bcec4450b964b94f](https://www.loom.com/share/250ab868612547a8bcec4450b964b94f)

Good catch @CarinaWolli! Just tested as well and the time fits the slot but the date is being booked outside of the set range.

2024-06-03 15:35 UTC, hariombalhara commented
Great catch @CarinaWolli 

[Just tested this and found it to be an existing behaviour before the future limit improvements](https://www.loom.com/share/6b5f42cb33054b6ebf727cd82ea59fbb). I can take it up as a follow up.

2024-06-04 14:09 UTC, CarinaWolli approved these changes
Can confirm the issue I mentioned already existed before. These changes look good and I created an issue for the other bug: https://github.com/calcom/cal.com/issues/15320

2024-06-04 15:46 UTC, merged