feat: Assign colors to events
calcom/cal.com pull request #15298
Opened 2024-06-02 18:15 UTC by anikdhabal

## What does this PR do?

- Fixes #7507
- Fixes CAL-XXXX (Linear issue number - should be visible at the bottom of the GitHub issue description)

## Mandatory Tasks (DO NOT REMOVE)

- [ ] I have self-reviewed the code (A decent size PR without self-review might be rejected)
- [ ] I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com)
- [ ] I have added or modified automated tests that prove my fix is effective or that my feature works (PRs might be rejected if logical changes are not properly tested)

## How should this be tested?

- Are there environment variables that should be set?
- What are the minimal test data to have?
- What is expected (happy path) to have (input and output)?
- Any other important info that could help to test that PR

## Checklist

- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my changes generate no new warnings

2024-06-28 17:50 UTC, Amit91848 commented on apps/web/components/eventtype/EventAdvancedTab.tsx
> +                  <Alert severity="warning" message={t("light_theme_contrast_error")} />
> Light Theme color doesn't pass contrast check. We recommend you change this colour so your buttons will be more visible.

Ig we should change this text. We aren't talking about button's visibility here.

2024-06-28 18:02 UTC, Amit91848 submitted a review, later dismissed
Amazing work so far @anikdhabal ! Found a small issue that should be fixed. Can you also fix the merge conflicts.

You select a specific colour for event type and save the event type. Now you toggle the colour settings off and on again, but don't save the event type. The colour reverts to its default value, becoming inconsistent with current state of event type. Ideally it should still be the colour previously saved as we did not make any changes to it. Attached a video for better understanding.

https://github.com/calcom/cal.com/assets/74371312/478b97c9-0bf5-42fc-be15-3f940a3c213d

2024-07-26 10:23 UTC, CarinaWolli reviewed
We want to use american english so `color` and not `colour`. But feature looks great 🙌🏻

2024-07-26 10:23 UTC, CarinaWolli commented on apps/web/public/static/locales/en/common.json
> +  "event_type_colour": "Event type colour",
```suggestion
  "event_type_color": "Event type color",
```
We should use American English

2024-07-31 19:10 UTC, Udit-takkar submitted a review, later dismissed
This doesn't match the designs in figma https://www.figma.com/design/UajFu4M1APhn2AywAEJkJr/New-Features?node-id=4673-355405&t=ih0GY2rAHb4Wc3wX-0.

This design is marked as "ready for dev"

![Screenshot 2024-08-01 at 12 40 27 AM](https://github.com/user-attachments/assets/0ccdd5ea-89b3-4db6-8a6c-85b31909fa08)

2024-07-31 20:06 UTC, anikdhabal commented
> This doesn't match the designs in figma https://www.figma.com/design/UajFu4M1APhn2AywAEJkJr/New-Features?node-id=4673-355405&t=ih0GY2rAHb4Wc3wX-0.
> 
> This design is marked as "ready for dev"
> 
> ![Screenshot 2024-08-01 at 12 40 27 AM](https://private-user-images.githubusercontent.com/53316345/353963411-0ccdd5ea-89b3-4db6-8a6c-85b31909fa08.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0NTY0NDAsIm5iZiI6MTcyMjQ1NjE0MCwicGF0aCI6Ii81MzMxNjM0NS8zNTM5NjM0MTEtMGNjZGQ1ZWEtODliMy00ZGI2LThhNmMtODViMzE5MDlmYTA4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDIwMDIyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxNWNlYzQxYTllOThjYTYxMDhmMzg4ZWZiMWI4OTVmZjFmYzMxMjU4MjA0MWE5MzBhYzBiZjBhNTZkNzg3ZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2eRBHsWdPS88ybX-WchPBXaL2UYFU4veShC4RwsRUrM)

Hey @Udit-takkar , why do we need to create a different color picker component with limited colors when we already have one? I think the current picker provides more color options. Additionally, creating a new component would make the code larger, and the use case for that color component is only for the event type color picker. Lmk what you think

2024-08-01 04:32 UTC, anikdhabal commented on apps/web/public/static/locales/en/common.json
> +  "event_type_colour": "Event type colour",
done

2024-08-01 08:21 UTC, Udit-takkar commented
> Hey @Udit-takkar , why do we need to create a different color picker component with limited colors when we already have one? 

We can't allow any colour to be selected as we have to make sure it doesn't fail the WCAG Contrast guidelines https://developer.mozilla.org/en-US/docs/Web/Accessibility/Understanding_WCAG/Perceivable/Color_contrast. Just confirm with @ciaranha once about the design and let me know

2024-08-01 08:53 UTC, anikdhabal commented
> > Hey @Udit-takkar , why do we need to create a different color picker component with limited colors when we already have one?
> 
> We can't allow any colour to be selected as we have to make sure it doesn't fail the WCAG Contrast guidelines https://developer.mozilla.org/en-US/docs/Web/Accessibility/Understanding_WCAG/Perceivable/Color_contrast. Just confirm with @ciaranha once about the design and let me know

Sure @Udit-takkar , and for WCAG contrast guidelines, we can add a check and display a message. I think in our code, we check the contrast for both dark and light modes in some components

2024-08-07 06:46 UTC, anikdhabal commented
> We can't allow any colour to be selected as we have to make sure it doesn't fail the WCAG Contrast guidelines https://developer.mozilla.org/en-US/docs/Web/Accessibility/Understanding_WCAG/Perceivable/Color_contrast. Just confirm with @ciaranha once about the design and let me know

Ciaran confirmed that we can use the color picker that we should have

2024-08-08 11:05 UTC, sean-brydon requested changes
![CleanShot 2024-08-08 at 11 55 49](https://github.com/user-attachments/assets/3de8d989-8239-410f-8a8e-06621ba7b11f)
Translation not loading
--
![CleanShot 2024-08-08 at 11 57 23](https://github.com/user-attachments/assets/8bda1185-41c7-4dca-9be2-0c18e15da0eb)
I was able to set this colour and didnt get an error

![CleanShot 2024-08-08 at 11 59 50](https://github.com/user-attachments/assets/ede3d72c-fc2d-43a5-93f4-cad6d64cc116)

Created a [replit](https://replit.com/@seanbrydon4/wcagchecker#index.ts) for easier testing of this fn manually

2024-08-08 11:33 UTC, anikdhabal commented
@sean-brydon Thanks for the review. I'm on it. Also, the translation is perfect locally on my end. I don't know why it's not loading on your end.

2024-08-10 08:22 UTC, anikdhabal commented
Hey @sean-brydon, the problem is that the way we handle the contrastCheck function is not optimal. The function is guaranteed to return a boolean, but we unnecessarily use it inside a try-catch block in every instance.

Before:-
![Screenshot 2024-08-10 133818](https://github.com/user-attachments/assets/5ab96b4f-0564-4ac9-9613-93731d624765)

After changes:-

![Screenshot 2024-08-10 135243](https://github.com/user-attachments/assets/8b0803b9-40e1-4099-b714-d22e796f5be3)

2024-08-12 10:08 UTC, sean-brydon submitted a review, later dismissed
Nice one! Thanks for making them changes - much better behaviour now

2024-08-14 10:02 UTC, sean-brydon approved these changes
Tested again - this is a neat feature!

2024-08-14 13:10 UTC, merged