feat: add passkey login feature (without any external solution)
calcom/cal.com pull request #15398
Opened 2024-06-10 17:24 UTC by anikdhabal

## What does this PR do?

- Fixes #13342 
- Fixes CAL-XXXX (Linear issue number - should be visible at the bottom of the GitHub issue description)

## Mandatory Tasks (DO NOT REMOVE)

- [ ] I have self-reviewed the code (A decent size PR without self-review might be rejected)
- [ ] I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com)
- [ ] I have added or modified automated tests that prove my fix is effective or that my feature works (PRs might be rejected if logical changes are not properly tested)

## How should this be tested?

- Are there environment variables that should be set?
- What are the minimal test data to have?
- What is expected (happy path) to have (input and output)?
- Any other important info that could help to test that PR

## Checklist

- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my changes generate no new warnings

2024-06-16 17:17 UTC, anikdhabal commented
#14741

2024-08-19 10:37 UTC, keithwillcode requested changes
@anikdhabal Great PR. 

Let's add some integration tests to verify all of the new code added in the handlers

2024-08-19 10:46 UTC, anikdhabal commented
> @anikdhabal Great PR.
> 
> Let's add some integration tests to verify all of the new code added in the handlers

Yeah @keithwillcode , it needs good amount of tests. I will add that

2024-09-26 14:23 UTC, MJomaa commented
Auth.js v5 has a passkey implementation as well https://authjs.dev/getting-started/providers/passkey

How feasible would be upgrading to v5?

2024-10-23 14:42 UTC, closed without merging