Wrong language in emails
calcom/cal.com pull request #1541
Opened 2022-01-18 12:43 UTC by alishaz-polymath

## What does this PR do?

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code and corrected any misspellings
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-01-18 23:17 UTC, PeerRich commented
what's required to go live with this?

2022-01-19 06:23 UTC, alishaz-polymath commented
> what's required to go live with this?

I'm testing things out here as I am unable to test this locally. If I'm right, I should be able to tweak things a bit and get this working today. The deployment was failing yesterday because of the DB server not responding.

2022-01-20 13:44 UTC, emrysal requested changes, later dismissed
So I think (Sorry, major change here) we should make "language" a property of `Person`. 

```
Person {
  name,
  email,
  timeZone,
  language
}
```

I also think this language should be a string ("en", "fr"). Something of the calEvent we can store in the Booking. The language function should be obtained otherwise. Seperate from calEvent I think.

2022-01-20 13:44 UTC, emrysal commented on lib/CalEventParser.ts
> +${calEvent.organizer.name} - ${calEvent.organizerLanguage("organizer")}
calEvent.organizer.language

2022-01-20 16:51 UTC, zomars reviewed
Agreed with @emrysal. We should strive for more maintainable code instead of constantly patching everywhere.

2022-01-27 20:30 UTC, zomars approved these changes
Code looking good and tested on preview. Let's merge this and monitor any edge cases.

2022-01-27 20:32 UTC, merged