fix: modal logic for assignment reminder
calcom/cal.com pull request #15488
Opened 2024-06-19 09:22 UTC by sean-brydon

Fixes: https://app.campsite.co/cal/posts/fua85mqwhijl

2024-06-19 09:22 UTC, sean-brydon commented on apps/web/modules/event-types/views/event-types-single-view.tsx
> +      }
Use logic for assignees on managed event types

2024-06-19 09:23 UTC, sean-brydon commented on apps/web/modules/event-types/views/event-types-single-view.tsx
> +      }
If all team members toggle is checked we don't need to worry about showing the modal as there is users assigned but in a different way

2024-06-19 09:23 UTC, sean-brydon commented on apps/web/modules/event-types/views/event-types-single-view.tsx
> -  useEffect(() => {
Moved below so we have access to form values

2024-06-19 16:41 UTC, joeauyeung requested changes
Heads up if we enable the all member assignment but don't save the modal doesn't show up. I think this is going to cause a lot of confusion for users so I think it's a blocking issue.

2024-06-20 11:52 UTC, sean-brydon commented
> Heads up if we enable the all member assignment but don't save the modal doesn't show up. I think this is going to cause a lot of confusion for users so I think it's a blocking issue.

I agree - me and @ciaranha were talking about this but i feel like this is a differnt modal we need to show when something hasnt been saved 🤔

2024-06-20 11:53 UTC, sean-brydon commented
> > Heads up if we enable the all member assignment but don't save the modal doesn't show up. I think this is going to cause a lot of confusion for users so I think it's a blocking issue.
> 
> I agree - me and @ciaranha were talking about this but i feel like this is a differnt modal we need to show when something hasnt been saved 🤔

I'll fix this issue here and we can do the save modal later on

2024-06-20 13:04 UTC, joeauyeung approved these changes
LGTM

2024-06-20 13:05 UTC, joeauyeung commented
> > Heads up if we enable the all member assignment but don't save the modal doesn't show up. I think this is going to cause a lot of confusion for users so I think it's a blocking issue.
> 
> I agree - me and @ciaranha were talking about this but i feel like this is a differnt modal we need to show when something hasnt been saved 🤔

That's true. It feels like we could look for any dirty fields in the form and show a modal with "Do you want to leave without saving your changes?"

2024-06-21 07:48 UTC, hariombalhara approved these changes
Tested. Works !!

2024-06-21 08:03 UTC, merged