Cal 3939 fix org banner
calcom/cal.com pull request #15504
Opened 2024-06-20 08:47 UTC by Preetam078

## What does this PR do?

- Fixes #XXXX (GitHub issue number)
- Fixes CAL-XXXX (Linear issue number - should be visible at the bottom of the GitHub issue description)

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected)
- [ ] I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com)
- [ ] I have added or modified automated tests that prove my fix is effective or that my feature works (PRs might be rejected if logical changes are not properly tested)

## How should this be tested?

- There was no as such tests need to run since this the minimal UI change for banner upload.

2024-06-20 08:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/calcom/cal.com?pullRequest=15504) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/calcom/cal.com?pullRequest=15504) before we can accept your contribution.<br/><hr/>**Preetam Mondal** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/calcom/cal.com?pullRequest=15504) it.</sub>

2024-06-21 17:18 UTC, joeauyeung requested changes
Great work so far @Preetam078. I would love to see some more even spacing when a banner isn't uploaded. It would also be great to see a placeholder banner when there isn't a banner set.

![CleanShot 2024-06-21 at 13 17 53@2x](https://github.com/calcom/cal.com/assets/65426560/69020315-0279-4c09-9220-c98603439a19)

2024-06-21 17:18 UTC, joeauyeung commented on packages/ui/components/avatar/Avatar.tsx
If we're passing `isBannerAvatar` we should create a new `BannerAvatar` component. Thoughts @sean-brydon?

2024-06-21 17:27 UTC, Preetam078 commented on packages/ui/components/avatar/Avatar.tsx
hii @joeauyeung is there any suggestions from your side which I can use as the placeholder may be like a Fallback image or a simple html container to control the `CLS (content load shifting)` in case there is no banner image is uploaded, Thoughts @sean-brydon ? also let me know if there is a separate component required for `BannerAvatar`.

2024-06-21 17:52 UTC, sean-brydon commented on packages/ui/components/avatar/Avatar.tsx
Yeah i'd suggest these being seperate components i think. They're pretty different from one another

2024-06-21 17:55 UTC, Preetam078 commented on packages/ui/components/avatar/Avatar.tsx
@sean-brydon what about the placeholder, if in case there is no banner uploaded ?

2024-06-22 04:38 UTC, Preetam078 commented on packages/ui/components/avatar/Avatar.tsx
hey @joeauyeung, @sean-brydon  I have created a separate component for BannerAvatar in my local machine. Just wanted to know if their is any suggestion you guys have for placeholder for banner before PR update ?

2024-06-23 03:08 UTC, Ryukemeister commented
@Preetam078 it looks like you've pushed the changes for the `yarn.lock `file. We generally update the `yarn.lock `while updating or deleting packages and it doesn't seem like we're doing that here, can you revert the changes made to the `yarn.lock` file?

2024-06-24 17:23 UTC, joeauyeung commented on packages/ui/components/avatar/Avatar.tsx
If you could find an image similar to this as the placeholder I think that would be great. It should have the same dimensions as the banner.
![image](https://github.com/calcom/cal.com/assets/65426560/f295a8ba-61c9-4807-a921-d46ca5ddfbb2)

2024-06-28 17:55 UTC, closed without merging