fix: modal intercept
calcom/cal.com pull request #15615
Opened 2024-06-28 12:25 UTC by sean-brydon

Fixes Managed event types:
https://github.com/calcom/cal.com/assets/55134778/7288a939-d5d2-470e-b9a6-e1eb4ed7d252

Fixes round robin: (WIP)

2024-06-28 13:01 UTC, sean-brydon commented on apps/web/modules/event-types/views/event-types-single-view.tsx
Lets prefer early returns here - easier to understand the logic of when we're skipping

2024-06-28 13:02 UTC, sean-brydon commented on apps/web/modules/event-types/views/event-types-single-view.tsx
>        }
Added a new query param when we leave to the destination route so we can easily know when to avoid calling this handler

2024-06-28 14:37 UTC, Udit-takkar commented on apps/web/modules/event-types/views/event-types-single-view.tsx
> +      }
```suggestion
      if (isRoundRobin && hosts.length > 0 || assignedUsers.length > 0) {
          return;
      }
```

2024-06-28 14:39 UTC, Udit-takkar reviewed
https://github.com/calcom/cal.com/assets/53316345/b14e926c-f0bf-4d1c-bc60-cb9bb4d099a8

I tried creating a team event type and even after assigning host i still get the "Leave without assigning" modal

2024-06-29 09:26 UTC, hariombalhara commented on apps/web/modules/event-types/views/event-types-single-view.tsx
>      const handleRouteChange = (url: string) => {
This is complex enough to be unit tested now. I think we can refactor out a function from it that accepts `eventType` and url and would give us boolean to inform if navigation should happen or not.

2024-06-29 09:30 UTC, hariombalhara requested changes
I am getting the modal on personal event as well

https://www.loom.com/share/82c3db9d3a9047009851f36005fba5a9

2024-07-29 03:43 UTC, keithwillcode commented
This PR is being closed due to a lack of activity. Please reopen if work is to continue.

2024-07-29 03:43 UTC, closed without merging