feat: add BigBlueButton integration (continuation)
calcom/cal.com pull request #15627
Opened 2024-06-30 14:06 UTC by abnud11

## What does this PR do?

This PR is a continuation of the work done in https://github.com/calcom/cal.com/pull/10803

Including Old PR description here:

As much a new integration as a POC for templated meeting links and redirects.

1. New BBB app with credential validation
2. On-demand meeting creation
3. Redirect via Cal.com link /booking/<uid>/join/<hash>
4. User-specific link generation (booking page and emails)

Todo:
- [x] get permission to use official logo
- [x]  receive go-ahead for redirect pages
- [x]  finalise description page
- [x]  add remaining moderator types, e.g. team members

Fixes https://github.com/calcom/cal.com/issues/1985
/claim https://github.com/calcom/cal.com/issues/1985

- Fixes #XXXX (GitHub issue number)
- Fixes CAL-XXXX (Linear issue number - should be visible at the bottom of the GitHub issue description)

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [ ] I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com). If N/A, write N/A here and check the checkbox.
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## Checklist

- I haven't added tests that prove my fix is effective or that my feature works

2024-06-30 14:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/calcom/cal.com?pullRequest=15627) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/calcom/cal.com?pullRequest=15627) before we can accept your contribution.<br/>**3** out of **5** committers have signed the CLA.<br/><br/>:white_check_mark: nicktrn<br/>:white_check_mark: leog<br/>:white_check_mark: aar2dee2<br/>:x: crowdin-bot<br/>:x: abnud11<br/><hr/>**abnud11** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/calcom/cal.com?pullRequest=15627) it.</sub>

2024-07-24 15:08 UTC, keithwillcode commented
@SomayChauhan Since you've worked quite a lot on the apps and how they are wired up, can you please take a look at this?

2024-09-07 09:12 UTC, Amit91848 requested changes

2024-09-07 09:12 UTC, Amit91848 commented on apps/web/pages/booking/[uid]/join/[hash].tsx
> +import { bbbOptionsSchema } from "@calcom/app-store/bigbluebutton/lib/bbbApi";
Thanks for the PR @abnud11 
 Concerns were raised in the previous pr about importing apps in core modules here https://github.com/calcom/cal.com/pull/10803#pullrequestreview-1652440876.
Have you tried if there is any other way around this?

2024-10-13 15:49 UTC, Abhi-0001 commented
How Can I start working on this issue?

2024-10-15 16:04 UTC, zomars requested changes
Awesome work so far @abnud11. Could you resolve the conflicts before continuing. Left some minor feedback. Also extra points for video evidence showing the main flows. 🙏

2024-10-15 16:06 UTC, zomars commented
> How Can I start working on this issue?

@Abhi-0001  Please check our contribution guide and if you still have doubt you can help us improve the guide itself. 🙏🏽

2024-12-16 00:55 UTC, flowersofpepper commented
Great work guys hope to see this integration soon.

2025-01-09 19:42 UTC, zomars commented
Closing due to staleness. Feel free to re-open.

2025-03-07 11:53 UTC, retrogtx commented
Closing due to staleness. Happy to review when ready 🙏

2025-03-07 11:53 UTC, closed without merging