Changing the zoom type meeting in recurring events
calcom/cal.com pull request #15668
Opened 2024-07-05 00:15 UTC by Franz1241

## What does this PR do?

Using type 8 creates multiple recurring zoom meetings effectively creating a new meeting for each occurrence. Changing the type to 2 will create a single meeting the right amount of occurrences. docs: https://developers.zoom.us/docs/api/rest/reference/zoom-api/methods/#operation/meetingCreate

- Fixes #14171
https://github.com/calcom/cal.com/issues/14171
## Mandatory Tasks (DO NOT REMOVE)

- [X ] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [ X] I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com). If N/A, write N/A here and check the checkbox.
- [ X] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## Checklist

- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my changes generate no new warnings

2024-07-05 01:25 UTC, anikdhabal reviewed
Hey @Franz1241 can you pls share a screenshot?

2024-07-05 01:48 UTC, anikdhabal reviewed
Shouldn't we check cases and update the type here?

2024-07-05 01:52 UTC, anikdhabal requested changes
Left some comments.

2024-07-05 15:44 UTC, Franz1241 commented
> Aren't we checking for cases and updating the type here? Also, there is a type error present.
> 
> ```
> switch (recurringEvent.freq) {
>         case Frequency.DAILY:
>           recurrence = {
>             type: 1,
>           };
>           break;
>         case Frequency.WEEKLY:
>           recurrence = {
>             type: 2,
>             weekly_days: dayjs(startTime).tz(attendees[0].timeZone).day() + 1,
>           };
>           break;
>         case Frequency.MONTHLY:
>           recurrence = {
>             type: 3,
>             monthly_day: dayjs(startTime).tz(attendees[0].timeZone).date(),
>           };
>           break;
>         default:
>           // Zoom does not support YEARLY, HOURLY or MINUTELY frequencies, don't do anything in those cases.
>           return;
>       }
> ```

In that block, the type you're setting is inside the recurrence object and determines the recurring type, not the meeting type which is at the root of the config object.

![image](https://github.com/calcom/cal.com/assets/72873924/8dccb1a2-aff7-4ca9-9290-abf28e6146c5)


![image](https://github.com/calcom/cal.com/assets/72873924/8d392e59-e3b8-47b0-bbe1-a631e17322fa)


And the issue I mentioned (#14171 )  showcases the issue correctly

2024-07-06 13:54 UTC, anikdhabal commented
> Hey @Franz1241 can you share a screenshot?


Please share a screenshot of the result. Additionally, there is a type error that needs to be fixed.

2024-07-16 08:23 UTC, anikdhabal commented
Hey, closing it for now. Feel free to address the requested changes and reopen it.

2024-07-16 08:23 UTC, closed without merging