feat: Format lists pasted into Routing Forms
calcom/cal.com pull request #15706
Opened 2024-07-09 11:40 UTC by danrfletcher

## What does this PR do?

- Fixes #14224 

- Fixes #XXXX (GitHub issue number)
- Fixes CAL-XXXX (Linear issue number - should be visible at the bottom of the GitHub issue description)

[](https://www.loom.com/share/7d183a88a01f4412a11955d0c0a45834?sid=23ce80c3-1f34-4490-9844-2a5c094df150)

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [ ] --(N/A)-- I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com). If N/A, write N/A here and check the checkbox.
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works.

2024-07-09 11:40 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/calcom/cal.com?pullRequest=15706) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/calcom/cal.com?pullRequest=15706) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/calcom/cal.com?pullRequest=15706) it.</sub>

2024-07-09 11:50 UTC, sean-brydon submitted a review, later dismissed
![CleanShot 2024-07-09 at 12 49 42](https://github.com/calcom/cal.com/assets/55134778/57349cb7-98cf-4621-942a-d5c2bf2621d1)
Works pretty well thanks for this - Slight NIT. When you paste on existing values it deletes everything up to that point. We should probably not run the logic if there is not multiple items

2024-07-09 15:01 UTC, anikdhabal requested changes
https://github.com/calcom/cal.com/assets/81948346/89b037fa-6f98-43ca-8d0a-6bc1bb42918a

Currently found some issues:
1.If there are two single selections input fields, after pasting input in the second field, all the options of both fields are cleared.
2. After moving two fields, the options of one field are cleared.

2024-07-11 13:34 UTC, danrfletcher commented
@hariombalhara please see changed to zod to accommodate form options object for use with rhf useWatch.

2024-07-13 09:01 UTC, hariombalhara commented on packages/app-store/routing-forms/zod.ts
> +        placeholder: z.string(),
Why are we making placeholder required?

2024-07-13 09:21 UTC, hariombalhara commented on packages/app-store/routing-forms/zod.ts
> +        placeholder: z.string(),
Infact we don't need to save placeholder. It is just a UI thing.

Placeholder is only needed when option isn't filled and you can't save without filling the option.

2024-07-13 09:25 UTC, hariombalhara commented on packages/app-store/routing-forms/pages/form-edit/[...appPages].tsx
> +      name: `${hookFieldNamespace}.options`,
Now that we are saving `options` directly. We need to get rid of `selectText` which was used to build options at run time.

`selectText` is legacy from the time when we provided just a textarea to freely add, reorder options as text.


But `selectText` would still be there for backward compatibility i.e. all existing fields would have selectText(and not options) and that should be mapped to options and we would give preference to `options` over `selectText`

2024-07-13 09:29 UTC, hariombalhara commented on packages/app-store/routing-forms/pages/form-edit/[...appPages].tsx
> +        (value) => value.placeholder === "New Option"
why are we filtering on `placeholder`

2024-07-13 09:31 UTC, hariombalhara commented on packages/app-store/routing-forms/pages/form-edit/[...appPages].tsx
> +      .split(/[\n,;]+/)
Do we need to split on , and ; ?  I think we should just split on new line and extend this feature if someone really need to have commas or semicolon support.

Reason being someone might find it suitable to provide a literal comma in one of their options.

Also, let's move this regex out as a constant in this module.

2024-07-13 09:32 UTC, hariombalhara commented on packages/app-store/routing-forms/pages/form-edit/[...appPages].tsx
> +      .map((value) => ({ placeholder: "New Option", value: value.trim(), id: uuidv4() }))
I don't think we need to provide a placeholder when value is already there. We are anyway going to reject all entries that don't have value.

2024-07-13 09:32 UTC, hariombalhara commented on packages/app-store/routing-forms/pages/form-edit/[...appPages].tsx
> +                    onPaste={(event: ClipboardEvent) => handlePaste(event, index)}>
Nice, I didn't know there is an onPaste event

2024-07-13 09:33 UTC, hariombalhara submitted a review, later dismissed
Left some blocking comments

2024-07-16 13:10 UTC, danrfletcher commented
@hariombalhara I have addressed all of the above, please let me know if any other changes are required 🎉

2024-07-16 13:23 UTC, danrfletcher commented
Now fixing type errors before review

2024-07-18 16:33 UTC, anikdhabal submitted a review, later dismissed
Hey @danrfletcher great work so far. But currently found some minor bugs:- 

1. After paste options, it creates an additional empty option.

https://github.com/user-attachments/assets/50364bdb-c6f5-4fa3-954f-8270a84ee981


2. When selecting an option and pasting, for example, two options, it won't replace the selected option with one but instead create two new options along with the selected one.

https://github.com/user-attachments/assets/f228b2a4-5400-45f2-a885-80e671c0fd3a

Let me know what you think

2024-07-30 15:17 UTC, danrfletcher commented
@anikdhabal I refactored the function to fix these issues & added tests. They are probably overkill, but do outline how the function handles other edge cases to avoid confusion.

2024-07-30 15:19 UTC, anikdhabal commented
> @anikdhabal I refactored the function to fix these issues & added tests. They are probably overkill, but do outline how the function handles other edge cases to avoid confusion.

okay, I will check that

2024-07-31 08:38 UTC, hariombalhara commented
I am working on a ticket that will build over it. It needs the new `options` prop that we are setting. So, I will be taking over this PR and merge it soon.

2024-07-31 12:52 UTC, hariombalhara commented on packages/app-store/routing-forms/pages/form-edit/[...appPages].tsx
> -
Removed this `useEffect` by doing this calculation at backend in `getSerializableForm`

2024-07-31 12:52 UTC, hariombalhara commented on packages/app-store/routing-forms/pages/form-edit/[...appPages].tsx
`updateSelectText` doesn't need to be done now as the source of truth would be `options` going forward

2024-07-31 12:53 UTC, hariombalhara commented on packages/app-store/routing-forms/pages/form-edit/[...appPages].tsx
> +                          options.length > 1 ? (
Ensures that last option isn't removable

2024-08-14 08:26 UTC, hariombalhara commented on apps/web/playwright/fixtures/users.ts
> +                label: "Multi Select(with Legacy `selectText`)",
Existing field is legacy. Added a new one with the new options format.

2024-08-14 08:53 UTC, hariombalhara commented on packages/app-store/routing-forms/pages/form-edit/[...appPages].tsx
> -    updateSelectText(newList);
No need to update selectText, we save the options only now.

2024-08-14 08:59 UTC, hariombalhara commented on packages/app-store/routing-forms/playwright/tests/basic.e2e.ts
> +    if (fieldTypeLabel === "Multiple Selection" || fieldTypeLabel === "Single Selection") {
This was a bug where we were checking wrong values for label

2024-08-14 14:50 UTC, hariombalhara commented on packages/app-store/routing-forms/components/FormInputFields.tsx
> -                      value: transformResponse({ field, value }),
Better renamed

2024-08-14 14:51 UTC, hariombalhara commented on packages/app-store/routing-forms/lib/substituteVariables.ts
> +      const field = fields.find((field) => field.id === key)
There was a type issue earlier causing this error to be not caught.

2024-08-14 14:51 UTC, hariombalhara commented on packages/app-store/routing-forms/lib/substituteVariables.ts
> +      const identifier = getFieldIdentifier(field);
There was a type issue earlier allowing possibly undefiend value to be passed

2024-08-14 14:51 UTC, hariombalhara commented on packages/app-store/routing-forms/lib/transformResponse.ts
> -export default function transformResponse({
Renamed to `getFieldResponseForJsonQuery`

2024-08-15 09:45 UTC, hariombalhara commented on packages/app-store/routing-forms/api/responses/[formId].ts
> +import type { FormResponse, SerializableForm } from "../../types/types";
It is just a rename from `Response` to `FormResponse`.

Response conflicts with Next.js reponse when auto-importing

2024-08-15 09:50 UTC, hariombalhara commented on packages/app-store/routing-forms/trpc/utils.ts
> +  const fieldResponsesByIdentifier: FORM_SUBMITTED_WEBHOOK_RESPONSES = {};
Renamed to `fieldResponsesByIdentifier` because that is more apt.

2024-08-15 09:50 UTC, hariombalhara commented on packages/app-store/routing-forms/trpc/utils.ts
> +        responses: fieldResponsesByIdentifier,
These responses are verified by e2e tests in webhook.e2e.ts

2024-08-15 09:51 UTC, hariombalhara commented on packages/app-store/routing-forms/types/types.d.ts
> +export type Field = NonNullable<Fields>[number];
It was typo causing Field to become any without any warning/errors

2024-08-18 17:41 UTC, hariombalhara commented on packages/app-store/routing-forms/pages/routing-link/getUrlSearchParamsToForward.ts
> +    }
Just moved the `getUrlSearchParamsToForward` function here with this change.

2024-08-20 08:34 UTC, hariombalhara commented on packages/features/shell/Shell.tsx
> +        {banners && !props.isPlatformUser && !isFullPageWithoutSidebar && (
Hides the banner that doesn't let the user use the Filter on reporting.

2024-08-22 07:25 UTC, hariombalhara approved these changes
Self reviewed this as I have done a ton of changes on the original PR.

2024-08-22 07:26 UTC, hariombalhara commented
@sean-brydon @anikdhabal Could you take a look at it now !!

2024-08-22 10:57 UTC, anikdhabal approved these changes
LGTM!!

2024-08-22 13:38 UTC, merged