Adding a script to remove unused strings
calcom/cal.com pull request #15716
Opened 2024-07-10 04:59 UTC by hjonasson

/claim #15623 
## What does this PR do?

- Updates `i18n-unused` to the most recent package
- Updates the associated config to cover all locations with strings in them
- Updates the lookup regular expression to cover other use cases for using strings (such as `language("my_string")`)
- Adds a script to `scripts` in `package.json` to run when you want to remove strings. It should be added to CI in my opinion but that is out of scope for this issue.
- Fixes a file parsing bug in the missing `localeFileParser` (the default doesn't work in this repo)

- Fixes [CAL-3991]

## Mandatory Tasks (DO NOT REMOVE)

- [X] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [ ] I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com). If N/A, write N/A here and check the checkbox.
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

Run the new script `delete-unused-strings`. All unused strings should be deleted for all locales, including English.

2024-07-10 04:59 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/calcom/cal.com?pullRequest=15716) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/calcom/cal.com?pullRequest=15716) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/calcom/cal.com?pullRequest=15716) it.</sub>

2024-07-10 11:24 UTC, Amit91848 requested changes
Thanks for the PR @hjonasson ! Great start but it is also removing translation that are being used. This needs some more adjusting. Attached a few screenshots below.

Also add a command which prints all the extra strings for each translation would be of great help 🙌. You can checkout other prs solving the same issue which has those.

![Screenshot 2024-07-10 164520](https://github.com/calcom/cal.com/assets/74371312/d44740fb-93cf-43d7-b3c4-b3cb6733cb78)
![Screenshot 2024-07-10 164633](https://github.com/calcom/cal.com/assets/74371312/cccb848c-dd61-4e24-a7de-5b78deccfd30)
![Screenshot 2024-07-10 164758](https://github.com/calcom/cal.com/assets/74371312/a5a1d27d-8a7b-4658-a951-284bbd55e944)
![Screenshot 2024-07-10 165203](https://github.com/calcom/cal.com/assets/74371312/7300f4e2-005c-4b15-a3bb-7ce34d6d9b87)

2024-07-10 22:18 UTC, hjonasson commented
Thanks for checking it out @Amit91848 ! After your review I found more ways strings are used. I have now covered them all. Adding more utility scripts will be easy but that was not a part of the original ticket so I might leave it out.

2024-07-16 11:25 UTC, Amit91848 requested changes
Much better thanks @hjonasson ! Left a few suggestions. Also can you exclude "ADD_NEW_STRINGS_ABOVE_THIS_LINE_TO_PREVENT_MERGE_CONFLICTS" from being removed, it isn't being used anywhere but we want it to be present.

2024-07-16 11:25 UTC, Amit91848 commented on i18n-unused.config.js
> +//   /(?<!\w)(?:(t|language|goToTab|translate|Error)\s*\(\s*"([^"]*)"(?:,\s*\{[^}]*\})?\)|(i18nKey\s*=\s*"[^"]*"|[\w\.]+language\s*\(\s*"([^"]*)"\s*\)))/gi;
NIT: clean up code

2024-07-16 11:25 UTC, Amit91848 commented on i18n-unused.config.js
>   * */
Extend comment based on the changes you have made to the translationKeyRegex. It would be really helpful to debug issues in future to make updates 🙌

2024-07-17 02:58 UTC, closed without merging