fix: #15726 increase max recurring events limit input
calcom/cal.com pull request #15728
Opened 2024-07-11 07:26 UTC by vijayraghav-io

## What does this PR do?

- Fixes #15726 
- Fixes CAL-XXXX (Linear issue number - should be visible at the bottom of the GitHub issue description)

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [ ] I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com). If N/A, write N/A here and check the checkbox.
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works.

2024-07-11 11:12 UTC, sean-brydon commented
@PeerRich @keithwillcode is this something we plan to do - There was a very good reason for limiting this to 20 im not sure if we plan to increase it while this œuery is still on slow side

2024-07-16 21:01 UTC, mahir22B approved these changes

2024-07-22 08:03 UTC, keithwillcode commented
Yeah, we had reduced it actually because of the difficulties of booking so far out. @anikdhabal Did you test this with 40? If there isn't a performance issue, we can try and go ahead with this change as I recall we changed how booking recurring events works so it's more flexible in working even when it runs into conflicts. 

@CarinaWolli You may have thoughts here as well.

2024-07-23 05:56 UTC, CarinaWolli commented
> Yeah, we had reduced it actually because of the difficulties of booking so far out. @anikdhabal Did you test this with 40? If there isn't a performance issue, we can try and go ahead with this change as I recall we changed how booking recurring events works so it's more flexible in working even when it runs into conflicts.
> 
> @CarinaWolli You may have thoughts here as well.

As it is now, it shouldn't be an issue performance-wise because we only check the availability for the first two slots. I am just wondering if this was a temporary solution to fix recurring events and if we may plan in the future to again check all slots for their availability along with other performance improvements.

Also not related to this question, but we don't mention this anywhere for the user that only the first two slots are checked for availability (cc @ciaranha): 
![Screenshot 2024-07-23 at 7 55 41 AM](https://github.com/user-attachments/assets/a48e88b0-2d78-4cf5-b6e6-75edd84cb84b)

2024-08-01 10:25 UTC, Amit91848 commented
> As it is now, it shouldn't be an issue performance-wise because we only check the availability for the first two slots. I am just wondering if this was a temporary solution to fix recurring events and if we may plan in the future to again check all slots for their availability along with other performance improvements.
> 
> Also not related to this question, but we don't mention this anywhere for the user that only the first two slots are checked for availability (cc @ciaranha)

This has been reported by others #15997

2024-08-05 06:30 UTC, CarinaWolli requested changes

2024-08-05 06:47 UTC, vijayraghav-io commented on apps/web/components/eventtype/RecurringEventController.tsx
> +                        max="40"
sure, will update.

2024-08-05 07:14 UTC, vijayraghav-io commented on apps/web/components/eventtype/RecurringEventController.tsx
> +                        max="40"
done

2024-08-07 07:23 UTC, CarinaWolli approved these changes
Thank you 🙏

2024-08-09 08:24 UTC, merged