fix: Disable all emails per event type w/o a workflow [CAL-4066]
calcom/cal.com pull request #15902
Opened 2024-07-25 02:53 UTC by joeauyeung

## What does this PR do?

This PR enables team event types under an org to disable the standard emails without having a workflow set.

There was also some confusion with some users where they believed that the current option would disable all emails. This PR expands disabling emails for the following:
- Scheduled
- Requested bookings
- Request reminders
- Requested denied
- Reschedule
- Requested reschedule
- Cancelled
- Payment requested
- Round robin emails to team members
- Seats specific emails

- Fixes #XXXX (GitHub issue number)
- Fixes CAL-4066 (Linear issue number - should be visible at the bottom of the GitHub issue description)

## Mandatory Tasks (DO NOT REMOVE)

- [ ] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [ ] I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com). If N/A, write N/A here and check the checkbox.
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

- Under an event type in a team in an org you should be able to see the two options under the advanced tab
- When enabling the options a dialog should appear where you have to type confirm to enable the option
- Enable both options
- Under each type of email that can be disabled, create a booking to test that the emails ARE NOT SENT
- Disable the option and ensure emails ARE SENT

2024-07-25 03:19 UTC, joeauyeung reviewed
I would look at `email-manager.ts` to see which emails are being affected by this PR.

When getting the metadata there is a lot of optional chaining when getting the event type metadata. This is because dynamic bookings might not have an event type associated with them in the DB. 

I have omitted optional chaining where an event type is guaranteed such as bookings that require confirmation and payments associated with them.

2024-07-25 07:15 UTC, CarinaWolli reviewed
Early review: 

- We said to allow disabling all emails without workflows only for orgs. But now every user can disable ALL emails only by having one workflow that triggers when booking is created.  
  - we either allow it for all users to disable emails without workflows 
  - or, non-org users can only disable the booking confirmation email (not all emails) when the workflows exists --> same as it was before 
- What happens to event types that already had the confirmation email disabled before? To me it looks like this would now change for them and all emails would stop sending
- Orgs can only disable the emails for team event types. I think we want that for personal event types as well

2024-07-25 19:45 UTC, joeauyeung reviewed
@CarinaWolli addressed your feedback.

I don't think there would be a lot of use cases where an individual wants to disable all emails as it takes a lot of setup which might be specific to their company. If a company did want this for individual events they should use the managed event type.

2024-07-25 19:45 UTC, joeauyeung commented on apps/web/components/eventtype/EventAdvancedTab.tsx
> +      {hasValidLicense && (
We now only allow these options for enterprise customers. We'll still keep both options available but will replace once we allow users to set granular options for emails
![CleanShot 2024-07-25 at 15 18 50@2x](https://github.com/user-attachments/assets/e2d565d8-5a89-45d1-8140-8debdee3132f)

2024-07-25 19:45 UTC, joeauyeung commented on packages/prisma/zod-utils.ts
> +          .optional(),
We now have a new option to disable all emails while still keeping the old option for just confirmation emails.

2024-07-30 13:51 UTC, CarinaWolli requested changes
- [ ]  `sendScheduledEmails` and `sendScheduledSeatsEmails` doesn't support disabling all emails (only the old feature to disable confirmation email when workflow enabled is supported)
- [ ] In `eventTypes/update.handler.ts` we need to check if the event type is from an org before updating `metadata.disableStandardEmails.all`
- [ ] we also should not send reminder emails in`scheduleMandatoryReminder` if all emails to attendees are disabled

2024-07-30 13:51 UTC, CarinaWolli commented on apps/web/components/eventtype/EventAdvancedTab.tsx
> +        />
I think we can move this up right after themetadata.disableStandardEmails.all.attendee Controller. No need check for `team?.parentId` again

2024-07-30 13:51 UTC, CarinaWolli commented on apps/web/components/eventtype/EventAdvancedTab.tsx
> +  const hasValidLicense = session.data ? session.data.hasValidLicense : null;
`hasValidLicense` isn't used

2024-07-30 13:51 UTC, CarinaWolli commented on apps/web/components/eventtype/settings/DisableAllEmailsSetting.tsx
> +              reschedules and reschedule requests, and cancellation emails.
We are missing the location change emails here (maybe some other email too)

Should we add something like 'and any other emails related to booking updates'

2024-07-30 13:51 UTC, CarinaWolli commented on apps/web/components/eventtype/settings/DisableAllEmailsSetting.tsx
> +              changes to their booking.
```suggestion
              changes to their bookings.
```

2024-08-08 18:05 UTC, joeauyeung commented
> * [ ]   `sendScheduledEmails` and `sendScheduledSeatsEmails` doesn't support disabling all emails (only the old feature to disable confirmation email when workflow enabled is supported)
> * [ ]  In `eventTypes/update.handler.ts` we need to check if the event type is from an org before updating `metadata.disableStandardEmails.all`
> * [ ]  we also should not send reminder emails in`scheduleMandatoryReminder` if all emails to attendees are disabled

Addressed all feedback

2024-08-09 09:29 UTC, CarinaWolli requested changes
Found some places where we don't pass `eventTypeMetadata` when calling the email function, let me know in case it's not needed there:
- [ ] `sendRoundRobinCancelledEmails` in new `roundRobinReassignment` function 
- [ ] `sendCancelledEmails` in `handleDeleteCredential`
- [ ] `sendRequestRescheduleEmail` in `app-store/vital/lib/reschedule.ts`

2024-08-09 09:29 UTC, CarinaWolli commented on packages/trpc/server/routers/viewer/eventTypes/update.handler.ts
> +    if (!eventType.team.parentId) {
type error here `'eventType.team' is possibly 'null'`

2024-08-09 09:29 UTC, CarinaWolli commented on packages/emails/email-manager.ts
> +  if (!hostEmailDisabled && !eventTypeDisableHostEmail(eventTypeMetadata)) {
`eventTypeMetadata` is missing as a param

2024-08-14 10:19 UTC, CarinaWolli approved these changes
All my comments have been addressed, looks good now 🙏

2024-08-14 11:17 UTC, merged

2024-10-02 08:43 UTC, YPC-Avishai commented
Is this feature available for teams on cal.com, too? 
Because I can not find those toggles. @joeauyeung

2024-10-23 18:50 UTC, janrabek commented
I can confirm @YPC-Avishai

We really need this feature, does anyone know when it's going to be released on cal.com?

2025-06-07 06:30 UTC, nakul-malhotra commented
is this ever going to be introduced for individuals? why are we blocking this to enterprise only?