chore: updated city-timezones to support kyiv
calcom/cal.com pull request #15927
Opened 2024-07-26 12:20 UTC by PeerRich

see: https://github.com/kevinroberts/city-timezones/pull/26

2024-07-26 12:24 UTC, PeerRich commented
currently getting an error 

<img width="1045" alt="CleanShot 2024-07-26 at 14 23 52@2x" src="https://github.com/user-attachments/assets/e17c9415-c2af-4431-b0e6-e060ad8ec3a3">

2024-07-26 12:35 UTC, emrysal submitted a review, later dismissed

2024-07-26 12:41 UTC, PeerRich commented
works now

2024-07-26 12:42 UTC, PeerRich commented on apps/web/package.json
> +    "react-timezone-select": "^3.2.7",
react-timezone-select needs update since it's still expecting Kiev not Kyiv

2024-08-06 00:14 UTC, zomars requested changes
We have some type errors with the new version:

![image.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/zQbH4zeZd9J8lCntUKAP/66ffafc5-7c0f-4c2b-a3ab-2df67c535a59.png)

2024-08-15 13:17 UTC, PeerRich commented
not sure why

2024-09-03 14:49 UTC, AlexHladin commented
> We have some type errors with the new version:
> 
> ![image.png](https://camo.githubusercontent.com/b02c739c43b9943cc14eb5ce1c2b977575c2043cb2fa5c677e96a66b3fa660c0/68747470733a2f2f67726170686974652d757365722d75706c6f616465642d6173736574732d70726f642e73332e616d617a6f6e6177732e636f6d2f7a516248347a655a64394a386c436e74554b41502f36366666616663352d376330662d346332622d613361622d3264663637633533356135392e706e67)

@PeerRich @zomars the issue with `isMulti` is fixed. Please update `react-timezone-select` to 3.2.8.
PR where issue was resolved https://github.com/ndom91/react-timezone-select/pull/129

2024-10-14 10:03 UTC, AlexHladin commented
Hey @PeerRich, @zomars, @anikdhabal, @Amit91848 
Would you be able to merge this PR? Once you update `react-timezone-select` to 3.2.8 the issue will be solved (https://github.com/calcom/cal.com/pull/15927#issuecomment-2326727608).

2024-11-06 13:11 UTC, keithwillcode commented
This is also implemented in #17159

2024-11-06 13:11 UTC, closed without merging