internal audit logger
calcom/cal.com pull request #15948
Opened 2024-07-28 08:12 UTC by TaduJR

## What does this PR do?
This change tries to resolve #1461 by adding audit logger on v1 and v2 api and on nextjs backend.
These are the list of events handled on Teams and Organizations
```bash
Event-Types
	- Modified
		Event Setup
			Title
			Duration
			Location
		Assignment
		        Scheduling Type
	- Created
	- Delete

Bookings
	- Modified
		Reschedule
		Edit Location
	- Created
	- Cancelled
```

- Fixes #1461 (GitHub issue number)
- Fixes CAL-1461 (Linear issue number - should be visible at the bottom of the GitHub issue description)

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected)
- [ ] I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com)
- [ ] I have added or modified automated tests that prove my fix is effective or that my feature works (PRs might be rejected if logical changes are not properly tested)

## How should this be tested?

- Are there environment variables that should be set? No
- What are the minimal test data to have? Team/Organization and User Entity Records
- What is expected (happy path) to have (input and output)? 
- Any other important info that could help to test that PR?

## Checklist

- I haven't commented my code, particularly in hard-to-understand areas
/claim #1461

2024-07-28 18:57 UTC, TaduJR commented
Moving to this PR for more cleaner approach from https://github.com/calcom/cal.com/pull/15948

2024-10-04 06:57 UTC, anikdhabal commented
@TaduJR really great work, could you pls fix the conflicts🙏

2024-10-04 10:16 UTC, TaduJR commented
Thank you @anikdhabal. I thought the team abandoned this issue.
Ok, I will fix the conflicts.

2024-10-04 20:14 UTC, zomars commented
> Thank you @anikdhabal. I thought the team abandoned this issue. Ok, I will fix the conflicts.

/tip 20

Thanks for the effort so far. We really appreciate it 🙏🏽

2024-10-11 05:03 UTC, TaduJR commented
Thank you @zomars. Working on the conflicts.

2024-10-15 14:57 UTC, TaduJR commented
Hello @zomars. I am sorry for not finishing it quickly. I was busy. I am working on the it right now to pass the tests. Sorry I should have converted it to draft.

2024-10-15 14:58 UTC, zomars commented
> Hello @zomars. I am sorry for not finishing it quickly. I was busy. I am working on the it right now to pass the tests. Sorry I should have converted it to draft.

It's ok I'm just getting another round of review. Appreciate the patience 🙏🏽

2024-10-15 15:06 UTC, zomars requested changes
I'm seeing that you're still working on this. Could you check the test. And while at it, could you add some video demos?

2024-10-18 13:15 UTC, TaduJR commented on turbo.json
> +    "AUDIT_LOG_ENABLED"
Done.

2024-10-18 16:57 UTC, TaduJR commented
> I'm seeing that you're still working on this. Could you check the test. And while at it, could you add some video demos?

Hello @zomars. Fixed the PR to pass the test also checkout the loom.

2024-11-13 19:13 UTC, zomars requested changes
Just finished reviewing the code and while the functionality is delivering as promised. The code feels way too intrusive to the core of the product itself. We strive to make the code legible and maintainable as possible. We're also trying to follow well tested and stablished conventions like Clean Code practices.

Will close this PR for now until we make more robust requirements on the desired approach code-wise.

Thank you again for your contribution 🙏

2024-11-13 19:13 UTC, closed without merging