fix: added translations for connect atoms
calcom/cal.com pull request #15969
Opened 2024-07-29 09:51 UTC by SomayChauhan

## What does this PR do?

adds translations to connect atoms

- Fixes #15906 (GitHub issue number)
- Fixes CAL-4068 (Linear issue number - should be visible at the bottom of the GitHub issue description)

## Mandatory Tasks (DO NOT REMOVE)

- [ ] --(N/A)-- I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [ ] --(N/A)-- I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com). If N/A, write N/A here and check the checkbox.
- [ ] --(N/A)-- I confirm automated tests are in place that prove my fix is effective or that my feature works.

2024-07-29 09:54 UTC, keithwillcode requested changes

2024-07-29 09:54 UTC, keithwillcode commented on apps/web/public/static/locales/en/common.json
> +  "apple_connect_atom_alredy_connected_label": "Connected Apple Calendar",
“alredy” is misspelled

2024-07-29 09:54 UTC, keithwillcode commented on apps/web/public/static/locales/en/common.json
> +  "google_connect_atom_alredy_connected_label": "Connected Google Calendar",
“alredy” is misspelled

2024-07-29 09:54 UTC, keithwillcode commented on apps/web/public/static/locales/en/common.json
> +  "outlook_connect_atom_alredy_connected_label": "Connected Outlook Calendar",
“alredy” is misspelled

2024-07-29 10:15 UTC, ThyMinimalDev approved these changes, later dismissed

2024-07-30 14:04 UTC, keithwillcode submitted a review, later dismissed

2024-07-30 14:07 UTC, keithwillcode approved these changes

2024-07-30 14:34 UTC, merged