utils: i18n cleanup script
calcom/cal.com pull request #16015
Opened 2024-07-31 22:21 UTC by randal923

## What does this PR do?

- Fixes #15623
- /claim #15623
- 
## Mandatory Tasks (DO NOT REMOVE)

- [ x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [ x] I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com). If N/A, write N/A here and check the checkbox.
- [ x] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

Make sure all the correct unused keys are being removed. Also, make sure to add any keys that should not be removed to the KEYS_TO_NOT_REMOVE array.

I initially considered two approaches. The first was to use glob to return a string of each component and then match regex patterns for i18n, t(), and other patterns. The second approach involved parsing the Abstract Syntax Tree (AST) and looking for these patterns to remove. But, I noticed that some parts of the code weren't using these patterns at all, so I decided to take a different route. Now, I'm first getting the keys from the common files and then searching for them in the string of the component that glob provides and removing them if they don't exist.

2024-07-31 22:21 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/calcom/cal.com?pullRequest=16015) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/calcom/cal.com?pullRequest=16015) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/calcom/cal.com?pullRequest=16015) it.</sub>

2024-07-31 22:40 UTC, randal923 commented
Looks like me merging the main to fix a conflict also fixed the formatting of 3 unrelated files. Should I remove them?

2024-08-01 08:12 UTC, Amit91848 requested changes
Great stuff @randal923 Looks promising. I haven't looked at the code yet but seems to be working well. 

You would also have to sign the CLA, without it we cannot merge this.

Small issues I found:
- Unit test that you added are failing, please look into it.
- We have a few strings that are being stored directly in the database, we would like to keep those.
  ![Screenshot 2024-08-01 133921](https://github.com/user-attachments/assets/1263e448-83af-4b69-9656-66d53ec4112b)
- "ADD_NEW_STRINGS_ABOVE_THIS_LINE_TO_PREVENT_MERGE_CONFLICTS": This line is getting removed from all translations. Please ignore this, we want it to be there in the all files.

2024-08-01 08:55 UTC, Amit91848 commented on apps/web/scripts/i18n-cleanup/main.ts
> +  const sourceFiles = glob.sync(`${sourceDir}/**/*.{ts,tsx,js,jsx}`, {
Might also want to include sql files here as we have some keys directly stored in db

2024-08-01 09:05 UTC, Amit91848 commented on apps/web/scripts/i18n-cleanup/main.ts
> +export const KEYS_TO_NOT_REMOVE: readonly string[] = [] as const;
```suggestion
export const KEYS_TO_NOT_REMOVE: readonly string[] = [
  "ADD_NEW_STRINGS_ABOVE_THIS_LINE_TO_PREVENT_MERGE_CONFLICTS",
] as const;
```

2024-08-01 09:06 UTC, Amit91848 commented on apps/web/scripts/i18n-cleanup/utils.ts
> +    fs.writeFileSync(filePath, JSON.stringify(data, null, 2), "utf8");
Need to leave a line at the end of the file

2024-08-01 09:10 UTC, Amit91848 commented on apps/web/scripts/i18n-cleanup/main.ts
> +  const sourceFiles = glob.sync(`${sourceDir}/**/*.{ts,tsx,js,jsx}`, {
```suggestion
  const sourceFiles = glob.sync(`${sourceDir}/**/*.{ts,tsx,js,jsx,sql}`, {
```

2024-08-01 14:55 UTC, randal923 commented
Hi @Amit91848, thanks for the feedback. I will work on the changes.

2024-08-01 15:24 UTC, randal923 commented
@Amit91848 I think these commits fixes everything you asked for. Let me know if there is anything else I need to change.

2024-08-09 08:44 UTC, Amit91848 commented on apps/web/scripts/i18n-cleanup/main.ts
> +  const sourceFiles = glob.sync(`${sourceDir}/**/*.{ts,tsx,js,jsx, sql}`, {
```suggestion
  const sourceFiles = glob.sync(`${sourceDir}/**/*.{ts,tsx,js,jsx,sql}`, {
```

2024-08-09 09:21 UTC, Amit91848 reviewed
Works fine now. Only removes the un used translation keys. 

It is a lot slower than the PR we have, maybe if we parallelize scanning files and use regex instead of  .includes, it could be a lot faster. But wait for a second review from senior team members before making any changes and let them decide.

2024-08-09 14:32 UTC, randal923 commented
> Works fine now. Only removes the un used translation keys.
> 
> It is a lot slower than the PR we have, maybe if we parallelize scanning files and use regex instead of .includes, it could be a lot faster. But wait for a second review from senior team members before making any changes and let them decide.

Using regex won't clean all the unused string because some of them don't follow any of the i18n library patterns (t(), i18n(), etc...)

2024-08-28 19:03 UTC, closed without merging