fix: #16141 team name nullable
calcom/cal.com pull request #16143
Opened 2024-08-08 20:01 UTC by emiliodeg

## What does this PR do?

Working with 16083 I found there are locations like "Google meet" which does not have `teamName` and it is set as `null`. If that is right, then the zod model is wrong. 

- Fixes #16141 
- Fixes CAL-none
Related with #16083 

## Mandatory Tasks (DO NOT REMOVE)

- [ ] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [ ] I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com). If N/A, write N/A here and check the checkbox.
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

- Are there environment variables that should be set? Default setup
- What are the minimal test data to have? run test
- What is expected (happy path) to have (input and output)? Editing a location of any Booking, and set a location without `teamName` is possible
- Any other important info that could help to test that PR

2024-08-08 20:02 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/calcom/cal.com?pullRequest=16143) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/calcom/cal.com?pullRequest=16143) before we can accept your contribution.<br/><hr/>**Emilio Degiovanni** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/calcom/cal.com?pullRequest=16143) it.</sub>

2024-08-09 02:40 UTC, anikdhabal commented on apps/web/components/dialog/EditLocationDialog.tsx
> +                                if (typeof val.credentialId === "number" && val.credentialId >= 0) {
Aren't you solving this here https://github.com/calcom/cal.com/pull/16142?

2024-08-14 22:21 UTC, zomars requested changes
Seems like we're having type errors in other areas due the schema changes

2024-10-01 06:14 UTC, anikdhabal commented
Closing it due to staleness. Feel free to reopen it if you wanted to fix it

2024-10-01 06:14 UTC, closed without merging