inital commit
calcom/cal.com pull request #16167
Opened 2024-08-11 19:19 UTC by TaduJR

## What does this PR do?

- Fixes #16009(GitHub issue number)
- Fixes CAL-[3946](Linear issue number - should be visible at the bottom of the GitHub issue description)

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com). If N/A, write N/A here and check the checkbox.
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

- Are there environment variables that should be set? No
- What are the minimal test data to have? 
- What is expected (happy path) to have (input and output)?
- Any other important info that could help to test that PR? No

## Checklist

- My code doesn't follow the style guidelines of this project
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my changes generate no new warnings

2024-08-11 19:50 UTC, anikdhabal requested changes
Can't reproduce the issue in my end. Am I doing this right, correct?

https://github.com/user-attachments/assets/92e70323-9810-443e-a010-8468f0ae3925

2024-08-11 19:50 UTC, anikdhabal commented on packages/features/form-builder/Components.tsx
> +    }) {
Why do we need subtypes? I don't think this is the correct way

2024-08-11 20:11 UTC, TaduJR commented
Hey @anikdhabal. I think it got fixed without linking the PR. I was working on 40 commit behind. Damn, Three straight days debugging for noting 😔.

Anyways, Thank you @anikdhabal.

2024-08-12 04:37 UTC, anikdhabal commented
@TaduJR I understand you. Looking forward to reviewing your other PR.

2024-08-12 04:37 UTC, closed without merging