Fixing build error & favicon.ico path
calcom/cal.com pull request #16255
Opened 2024-08-17 15:04 UTC by Upellift99

## What does this PR do?

- Fixes #16232
- Fixes #14457

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com). If N/A, write N/A here and check the checkbox.
- [x] I confirm automated tests are in place that prove my fix is effective or that my feature works.

2024-08-17 15:54 UTC, anikdhabal requested changes

2024-08-17 15:54 UTC, anikdhabal commented on packages/features/ee/organizations/pages/settings/attributes/attributes-edit-view.tsx
> +  const { id } = useParams<{ id: string }>()!;
```suggestion
  const params = useParams<{ id: string }>();
  const id = params?.id || "";
```

2024-08-17 15:55 UTC, anikdhabal commented
In Pages Router, useParams will return null on the initial render and updates with properties following the rules above once the router is ready

2024-08-17 16:53 UTC, anikdhabal commented on packages/features/ee/organizations/pages/settings/attributes/attributes-edit-view.tsx
> +  const { id } = useParams<{ id: string }>()!;
Also, it would be better to remove the other type assertion for id in this file

2024-08-19 10:36 UTC, anikdhabal commented
Fixed by this https://github.com/calcom/cal.com/pull/16243

2024-08-19 10:36 UTC, closed without merging

2024-09-19 12:23 UTC, JVKeller commented
This still seems to be an issue?

```
Build error on favicon.ico still exists:
Export encountered errors on following paths:
@calcom/web:build:      /favicon.ico/route: /favicon.ico
@calcom/web:build:     ERROR: command finished with error: command (/root/cal.com/apps/web) yarn run build exited (1)
command (/root/cal.com/apps/web) yarn run build exited (1)

 Tasks:    10 successful, 11 total
Cached:    6 cached, 11 total
  Time:    2m32.69s 
Failed:    @calcom/web#build

 ERROR  run failed: command  exited (1)
```

### Steps to Reproduce

1. Clone repository
2. Tested with yarn dx with little issue
3. tried to build

Any Suggestions?