feat: :sparkles: support for adding script url added for umami
calcom/cal.com pull request #16300
Opened 2024-08-21 10:00 UTC by AkashRajpurohit

## What does this PR do?

- Adds support for adding the script URL while setting up Umami App.
- The current version of the app only works with hosted solution but with this, users can use their self-hosted version of Umami as well to set up Analytics in cal.com (ref: https://github.com/calcom/cal.com/pull/14783#issuecomment-2104420069)

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [ ] I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com/docs). If N/A, write N/A here and check the checkbox.
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

- Add the Umami App to your booking.
- Set Script URL along with Site ID.
- Verify the events coming in on your Umami app when the event page is opened.

![SCR-20240821-l8q](https://github.com/user-attachments/assets/b56b4e00-3702-484b-b43d-47baefc49960)

![SCR-20240821-l9e](https://github.com/user-attachments/assets/8b8500e0-0e0a-4e27-ac60-f8f690d3d585)

![SCR-20240821-l9w](https://github.com/user-attachments/assets/dbc28f2a-4a9d-460b-8342-1d6d5fffd3ed)

## Checklist

- I haven't checked if my changes generate no new warnings

2024-08-21 10:01 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/calcom/cal.com?pullRequest=16300) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/calcom/cal.com?pullRequest=16300) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/calcom/cal.com?pullRequest=16300) it.</sub>

2024-08-21 10:22 UTC, anikdhabal requested changes

2024-08-21 10:22 UTC, anikdhabal commented on packages/app-store/umami/config.json
> +          "src": "{SCRIPT_URL}",
I think it's better to let the user choose whether they want to add SCRIPT_URL or not

2024-08-22 03:08 UTC, anikdhabal commented on packages/app-store/umami/config.json
> +          "src": "{SCRIPT_URL}",
Looks good

2024-08-22 03:09 UTC, anikdhabal approved these changes
LGTM!

2024-08-22 07:39 UTC, merged

2024-09-11 17:31 UTC, avocadoattack commented
I've been following this PR carefully, and I'm wondering when the Umami Analytics integration will be available within Cal