chore: App-router-migration`(/apps`) fix metadata, extract components into `/module` and finish migration
calcom/cal.com pull request #16354
Opened 2024-08-25 18:06 UTC by hbjORbj

## What does this PR do?

- Fixes #XXXX (GitHub issue number)
- Fixes CAL-XXXX (Linear issue number - should be visible at the bottom of the GitHub issue description)

## Mandatory Tasks (DO NOT REMOVE)

- [ ] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [ ] I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com/docs). If N/A, write N/A here and check the checkbox.
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

- Are there environment variables that should be set?
- What are the minimal test data to have?
- What is expected (happy path) to have (input and output)?
- Any other important info that could help to test that PR

## Checklist

- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my changes generate no new warnings

2024-08-26 15:02 UTC, hbjORbj commented on apps/web/modules/apps/[slug]/[...pages]/pages-view.tsx
> +  }
This is a new block of code I added

2024-08-29 02:27 UTC, hbjORbj commented on apps/web/modules/apps/[slug]/[...pages]/pages-view.tsx
> +): Promise<GetServerSidePropsResult<any>> {
This is a new block of code I added

2024-08-29 17:45 UTC, joeauyeung requested changes
@hbjORbj I noticed when I try and navigate to `/future/installation/[[...step]]` I'm being redirected back to the app store.

Other routes are working fine

2024-08-29 21:05 UTC, hbjORbj commented
> @joeauyeung I noticed when I try and navigate to /future/installation/[[...step]] I'm being redirected back to the app store.

Hey Joe, I experienced the same with `/installation/[[...step]]`. Can you give me an example of URL you tested this route with? (a.k.a what [[...step]] value did you use?)

2024-08-30 14:51 UTC, joeauyeung commented
> > @joeauyeung I noticed when I try and navigate to /future/installation/[[...step]] I'm being redirected back to the app store.
> 
> Hey Joe, I think this is ok because the experience is the same in Pages Router (both in dev/prod). Btw, what [[...step]] value did you use?

@hbjORbj here's what I'm experiencing
https://www.loom.com/share/dbb8bd50228247d987a879888f763a2d?sid=30594643-a418-4378-8478-13d4bf88d7dc

2024-09-02 06:49 UTC, hbjORbj commented
@joeauyeung, Hey Joe, thanks for the screencast 🙏. You are right! I fixed the bug in this [commit](https://github.com/calcom/cal.com/pull/16354/commits/7469a51daebe22ed871f8d4cc4716c885d79f6f6).

2024-09-03 14:53 UTC, joeauyeung approved these changes
Installation page is now working. Great work @hbjORbj!

2024-09-06 15:40 UTC, merged