add hashed link retrieval from event types v1 api
calcom/cal.com pull request #16437
Opened 2024-08-30 20:44 UTC by JOSU9435

## What does this PR do?

- Fixes #15619 (GitHub issue number)
- Fixes CAL-4047 (Linear issue number)

Adds an optional `hashedLink` field in the event-types v1 APIs response for retrieving the private URL.

```json
"hashedLink": {
    "id": 2,
    "link": "cS4DSPAq28ALSHkyFov1y2",
    "eventTypeId": 3
}
```

## Mandatory Tasks (DO NOT REMOVE)

- [ ] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [ ] I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com/docs).
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

- Start the v1 API and generate an API key.
- Send a GET request to http://localhost:3003/api/v1/event-types?apiKey={API_KEY}. The response should include the hashedLink field.
- Send a GET request to http://localhost:3003/api/v1/event-types/{eventTypeId}?apiKey={API_KEY}. The response should contain the hashLinked field.

2024-08-30 20:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/calcom/cal.com?pullRequest=16437) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/calcom/cal.com?pullRequest=16437) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/calcom/cal.com?pullRequest=16437) it.</sub>

2024-08-31 00:16 UTC, Amit91848 requested changes
Thanks for the PR @JOSU9435 but I have a suggestion
Let's not return eventTypeId as it's already present. Also remove id of hashed link as there is nothing that can be done with it.

2024-08-31 02:52 UTC, anikdhabal commented on apps/api/v1/pages/api/event-types/_get.ts
> +      hashedLink: true,
Same

2024-08-31 02:52 UTC, anikdhabal commented on apps/api/v1/pages/api/event-types/[id]/_get.ts
> +      hashedLink: true,
Select only the link here

2024-08-31 03:08 UTC, anikdhabal submitted a review, later dismissed
LGTM !!

2024-08-31 20:48 UTC, JOSU9435 commented
Thanks for the review @Amit91848, @anikdhabal 
I have pushed the changes that you have suggested.

2024-09-01 03:26 UTC, anikdhabal approved these changes

2024-09-02 05:08 UTC, Amit91848 approved these changes
LGTM!!

2024-09-06 06:47 UTC, merged