chore: App router migration - Refactor & Move `getServerSideProps` to `/lib`
calcom/cal.com pull request #16457
Opened 2024-09-02 10:08 UTC by hbjORbj

## What does this PR do?

- Fixes CAL-4247

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] N/A - I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com/docs). If N/A, write N/A here and check the checkbox.
- [x] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

- Navigate to:

1. `future/event-types/[type]`
2. `future/event-types`
3. `/event-types/[type]`
14 `/event-types`

2024-09-06 19:16 UTC, Udit-takkar requested changes, later dismissed
I am getting these errors on /future/event-types/[type] "NextRouter was not mounted."

![Screenshot 2024-09-07 at 12 46 26 AM](https://github.com/user-attachments/assets/3fb6ace0-d5a6-40c6-a63d-00ea46426a6b)

2024-09-07 01:38 UTC, hbjORbj commented
Hey Udit, I couldn't reproduce the error you had. BUT thanks to you, I found one thing that was bothering; we were importing useRouter from next/router, which we shouldn't for app router. So, this means, I need to create a copy of this `EventType` component and refactor it for app router. I will convert it to a draft and ping you once it's done ;)

2024-09-11 02:07 UTC, hbjORbj commented
@Udit-takkar Hey Udit, thanks for the review. The problem was that router was being created from `useRouter` imported from `next/router`, not the one from `next/navigation`. I created a copy of `EventType` component called `EventTypeAppDir`. Now it should render fine.

<img width="1440" alt="Screenshot 2024-09-10 at 22 04 47" src="https://github.com/user-attachments/assets/a45901e5-e9f7-4cbc-a7bd-3e8f1398f87e">

2024-09-11 02:09 UTC, hbjORbj commented on packages/features/eventtypes/components/EventTypeAppDir.tsx
> +  // The part where it is different from the original code in `EventType` component ENDS HERE
FYI

2024-09-11 02:24 UTC, zomars approved these changes, later dismissed

2024-09-11 02:26 UTC, zomars approved these changes

2024-09-11 02:41 UTC, merged