Fix: Bookings page going blank on Reschedule
calcom/cal.com pull request #16460
Opened 2024-09-02 13:00 UTC by chaithanya009

## What does this PR do?

- Fixes #16422 (GitHub issue number)
- Fixes CAL-XXXX (Linear issue number - should be visible at the bottom of the GitHub issue description)

## Mandatory Tasks (DO NOT REMOVE)

- [ ] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [ ] I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com/docs). If N/A, write N/A here and check the checkbox.
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

- Are there environment variables that should be set?
- What are the minimal test data to have?
- What is expected (happy path) to have (input and output)?
- Any other important info that could help to test that PR

## Checklist

- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my changes generate no new warnings

2024-09-02 13:00 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/calcom/cal.com?pullRequest=16460) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/calcom/cal.com?pullRequest=16460) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/calcom/cal.com?pullRequest=16460) it.</sub>

2024-09-02 13:19 UTC, anikdhabal requested changes

2024-09-02 13:19 UTC, anikdhabal commented on apps/web/components/dialog/RescheduleDialog.tsx
> +      queryClient.invalidateQueries(queryKeys);
This is not correct

2024-09-02 13:20 UTC, chaithanya009 commented
The underlying issue is the cursor for the infinite query used in bookings is not reset on invalidation.
refer: https://tanstack.com/query/latest/docs/framework/react/guides/infinite-queries?from=reactQueryV3#what-happens-when-an-infinite-query-needs-to-be-refetched

2024-09-02 13:28 UTC, Amit91848 reviewed
Can you add a before after video? Can't seem to replicate it 🤔 @chaithanya009

2024-09-02 13:28 UTC, anikdhabal commented
> The underlying issue is the cursor for the infinite query used in bookings is not reset on invalidation. refer: https://tanstack.com/query/latest/docs/framework/react/guides/infinite-queries?from=reactQueryV3#what-happens-when-an-infinite-query-needs-to-be-refetched

First, I can't reproduce the issue on my end. Could you please share a Loom video of the bug and its solution?

2024-09-04 07:32 UTC, closed without merging

2024-09-04 07:32 UTC, chaithanya009 commented
Closing the PR. From what I tested there is an issue invalidating infiniteQuery.