perf: server-side fetching for all pages in `settings/developer`
calcom/cal.com pull request #16604
Opened 2024-09-12 01:12 UTC by hbjORbj

## What does this PR do?

- Fixes CAL-4311

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] N/A - I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com/docs). If N/A, write N/A here and check the checkbox.
- [x] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

- Are there environment variables that should be set?
- What are the minimal test data to have?
- What is expected (happy path) to have (input and output)?
- Any other important info that could help to test that PR

## Checklist

- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my changes generate no new warnings

2024-09-12 07:03 UTC, Udit-takkar requested changes
page /future/settings/developer/api-keys doesn't get updated when i create or delete a key without reloading

https://github.com/user-attachments/assets/7da41a7b-350e-4c85-9c10-82e1116f0a2a

2024-09-12 08:31 UTC, sean-brydon commented
> page /future/settings/developer/api-keys doesn't get updated when i create or delete a key without reloading
> 
>  Screen.Recording.2024-09-12.at.12.32.58.PM.mov

https://github.com/calcom/cal.com/blob/91f5d49cd4be95719f6231842a7ef11a44c587e1/packages/features/ee/api-keys/components/ApiKeyListItem.tsx#L36 

We need to somehow call revalidateTag/revalidatePage here to make this behave the way we expect. The only issue is that we need to call that from within a server action. Draw back to still supporting app and pages is that theres no simple way to invalidate both.

-- I found a solution
I created a working example here: https://github.com/calcom/cal.com/pull/16607 let me know what you think of this approach cc: @Udit-takkar @hbjORbj

2024-09-14 22:50 UTC, hbjORbj commented
@sean-brydon Thanks Sean, I merged your PR into this PR and added some refactors

2024-09-16 08:36 UTC, Udit-takkar requested changes
https://github.com/user-attachments/assets/3446bf74-def3-4aab-8346-ff73b2970feb

Deletion works fine now but i still have to reload to see newly added API keys

2024-09-16 09:57 UTC, sean-brydon commented
> Screen.Recording.2024-09-16.at.2.06.09.PM.mov 
> Deletion works fine now but i still have to reload to see newly added API keys

Can you try with the redirect in place? We are revalidating the path of /settings/developer/api-keys. Not the /future/ version

2024-09-16 17:24 UTC, Udit-takkar commented
@sean-brydon  But the path in constant contains '/future'. we are validating it

export const PATHS_MAP = {
  SETTINGS_DEVELOPER_API_KEYS: "/future/settings/developer/api-keys",
};

2024-09-17 07:42 UTC, sean-brydon commented
> @sean-brydon But the path in constant contains '/future'. (which we are revalidating)
> 
> export const PATHS_MAP = { SETTINGS_DEVELOPER_API_KEYS: "/future/settings/developer/api-keys", };

My bad!  @hbjORbj You got any idea ?

2024-09-17 10:03 UTC, hbjORbj commented
This is actually annoying. Both `revalidatePath` and `revalidateTag` do not seem to trigger a refetch after api key creation while they trigger it after deletion / update.

2024-10-15 20:18 UTC, sean-brydon commented
> This is actually annoying. Both `revalidatePath` and `revalidateTag` do not seem to trigger a refetch after api key creation while they trigger it after deletion / update.

@hbjORbj Whats the status here? This has been stale for some time now - do you need a hand getting this merged?

2025-01-06 13:22 UTC, closed without merging