chore: Fixing ICS file in workflows & ICS calendar descriptions
calcom/cal.com pull request #16731
Opened 2024-09-19 19:10 UTC by joeauyeung

## What does this PR do?

For our emails we use `generateIcsString()` while in workflows they had their own function to generate ICS strings. We should keep the calendar events unified. By doing this we solve two problems
- Double calendar events on calendars because the ICS file had a different UID than the calendar event we created when the booking was made
- Syncing calendar events with relevant information by removing the title and subtitle from the calendar description
### Before
![CleanShot 2024-09-19 at 15 10 13@2x](https://github.com/user-attachments/assets/ddf56a9c-5afe-4001-be18-356d00bc9217)

### After
![CleanShot 2024-09-19 at 15 10 31@2x](https://github.com/user-attachments/assets/f4556a50-41d6-4a1c-9acf-ef3eb12ae7d1)
 

- Fixes #XXXX (GitHub issue number)
- Fixes CAL-XXXX (Linear issue number - should be visible at the bottom of the GitHub issue description)

## Mandatory Tasks (DO NOT REMOVE)

- [ ] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [ ] I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com/docs). If N/A, write N/A here and check the checkbox.
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

- Are there environment variables that should be set?
- What are the minimal test data to have?
- What is expected (happy path) to have (input and output)?
- Any other important info that could help to test that PR

## Checklist

- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my changes generate no new warnings

2024-09-19 19:17 UTC, joeauyeung commented on packages/emails/lib/generateIcsString.ts
Remove the `title`, `subtitle`, `role`, and `isRequestRescheduled` params as they are not needed anymore.

2024-09-19 19:17 UTC, joeauyeung commented on packages/features/ee/workflows/api/scheduleEmailReminders.ts
> +                          generateIcsString({ event: reminder.booking, status: "CONFIRMED" }) || ""
Assume that we only schedule workflow emails for confirmed bookings.

2024-09-19 19:17 UTC, joeauyeung commented on packages/features/ee/workflows/lib/reminders/emailReminderManager.ts
> -    const status: ParticipationStatus =
This status should be for the whole event and not just an attendee.

2024-09-19 19:17 UTC, joeauyeung commented on packages/features/ee/workflows/lib/reminders/emailReminderManager.ts
> -        ? "COMPLETED"
`COMPLETED` is not part of the ICS standard. Most calendars handle bookings in the past on their own

2024-09-25 17:49 UTC, joeauyeung commented on packages/lib/CalEventParser.ts
Made a lot of changes to the typing of these functions. Rather than expecting a whole `CalendarEvent` object, only require the fields needed.

2024-10-01 18:36 UTC, CarinaWolli requested changes
can you fix the type errors? 🙏

2024-10-01 18:36 UTC, CarinaWolli commented on packages/trpc/server/routers/viewer/workflows/util.ts
> +        };
do we need to do that in other places too where we call `scheduleEmailReminder`?

2024-10-07 14:50 UTC, CarinaWolli approved these changes
LGTM 👍

2024-10-07 14:50 UTC, merged