Feature/1445 jitsi meet integration
calcom/cal.com pull request #1674
Opened 2022-02-01 20:00 UTC by philippdormann

## What does this PR do?

meet.jit.si support

Fixes #1445

## Type of change
- [x] New feature (non-breaking change which adds functionality)

## How should this be tested?

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code and corrected any misspellings
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-02-05 15:45 UTC, PeerRich commented
what's missing @philippdormann can we help?

2022-02-07 19:59 UTC, PeerRich commented
> what's missing @philippdormann can we help?

ping

oh btw, "This branch is out-of-date with the base branch"

lets try and get this merged tomorrow 🎉

2022-02-07 20:01 UTC, philippdormann commented
heya! it's done^^
figured you notices this and requested the reviewers 😅

just updated the branch :)

2022-02-08 18:17 UTC, zomars requested changes
We have some type issues in BookingPage and success page.

2022-02-08 18:17 UTC, zomars commented on components/booking/pages/BookingPage.tsx
> +  ) => {
This is causing a type error and it seems unnecessary
```suggestion
  const getLocationValue = (booking: Pick<BookingFormValues, "locationType" | "phone">) => {
```

2022-02-08 19:36 UTC, philippdormann commented on lib/integrations/getIntegrations.ts
> +    installed: true,
your decision - I think Jitsi Meet (and other services without signup) should be enabled by default.

2022-02-08 19:38 UTC, philippdormann commented on lib/integrations/Jitsi/JitsiVideoApiAdapter.ts
> +  };
not that i know of.

the huddle01 integration does the same thing.

2022-02-08 19:39 UTC, philippdormann commented on pages/success.tsx
> +                            )}
?

2022-02-08 20:16 UTC, zomars commented on lib/integrations/getIntegrations.ts
> +    installed: true,
That's @PeerRich and @baileypumfleet decision to make. I'm just pointing it out.

2022-02-08 20:16 UTC, zomars commented on pages/integrations/index.tsx
> +  }
Can we apply these suggestions to avoid too much duplication?

2022-02-08 20:17 UTC, zomars reviewed
We're almost there. Just some suggestions pending.

2022-02-08 21:21 UTC, philippdormann commented on pages/integrations/index.tsx
> +  }
done ✅

2022-02-08 21:23 UTC, zomars approved these changes

2022-02-08 22:12 UTC, merged

2022-02-08 22:32 UTC, philippdormann commented
cheers, guys 🎉🎉

2022-02-08 22:40 UTC, baileypumfleet commented
Thank you for your incredible work! We really appreciate the contribution :)