chore: `settings/teams` remove pages router and use app router
calcom/cal.com pull request #16751
Opened 2024-09-21 00:01 UTC by hbjORbj

## What does this PR do?

- Fixes #XXXX (GitHub issue number)
- Fixes CAL-XXXX (Linear issue number - should be visible at the bottom of the GitHub issue description)

## Mandatory Tasks (DO NOT REMOVE)

- [ ] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [ ] I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com/docs). If N/A, write N/A here and check the checkbox.
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

- Are there environment variables that should be set?
- What are the minimal test data to have?
- What is expected (happy path) to have (input and output)?
- Any other important info that could help to test that PR

## Checklist

- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my changes generate no new warnings

2024-09-23 10:10 UTC, sean-brydon requested changes, later dismissed
LGTM but lets add yarn.lock back in from main

2024-09-23 10:10 UTC, sean-brydon commented on yarn.lock
Can we restore this file?

2024-09-23 13:55 UTC, hbjORbj commented on yarn.lock
Yeah sure, done!

2024-09-23 17:39 UTC, hbjORbj commented
TODO: Test on Prod

2024-09-23 19:36 UTC, hbjORbj commented
Added booking liimits page as a follow up of #16614

2024-12-02 13:18 UTC, hbjORbj commented
Blocked by the failing integration test. Seems like there's a problem with the test.

2024-12-02 18:36 UTC, joeauyeung submitted a review, later dismissed

2024-12-04 16:55 UTC, joeauyeung approved these changes

2024-12-04 17:31 UTC, merged