fix: undefined in meeting url workflow variable
calcom/cal.com pull request #16771
Opened 2024-09-23 15:52 UTC by CarinaWolli

## What does this PR do?

- Fixes #XXXX (GitHub issue number)
- Fixes CAL-XXXX (Linear issue number - should be visible at the bottom of the GitHub issue description)

## Mandatory Tasks (DO NOT REMOVE)

- [ ] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [ ] I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com/docs). If N/A, write N/A here and check the checkbox.
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

- Are there environment variables that should be set?
- What are the minimal test data to have?
- What is expected (happy path) to have (input and output)?
- Any other important info that could help to test that PR

## Checklist

- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my changes generate no new warnings

2024-09-24 14:57 UTC, joeauyeung requested changes
I noticed that for workflows the event is typed as `BookingInfo`. Should we add the `bookerUrl` as a property so we ensure we're always handling org domains?

Found in `packages\features\ee\workflows\lib\reminders\smsReminderManager.ts` line 37

2024-09-24 16:16 UTC, joeauyeung approved these changes, later dismissed
Feedback addressed. 

Just a heads up that we don't have to do `Omit<CalendarEvent, "bookerUrl">` if we're declaring `bookerUrl` in `ExtendedCalendarEvent`

2024-09-24 17:03 UTC, CarinaWolli commented on packages/features/bookings/lib/handleSeats/types.d.ts
> +import type { AppsStatus, CalendarEvent } from "@calcom/types/Calendar";
`CalendarEvent` wasn't imported, so `evt` was treated as `any` instead. Importing it now caused some other type errors that needed to be fixed

2024-09-30 14:35 UTC, CarinaWolli commented
@joeauyeung Fixed the merge conflicts, can you re-review?

2024-09-30 16:46 UTC, joeauyeung approved these changes

2024-09-30 19:25 UTC, merged