feat: reconnect bookingreference for new credential
calcom/cal.com pull request #16878
Opened 2024-09-30 06:41 UTC by vijayraghav-io

## What does this PR do?

- Fixes #16785 
- Fixes CAL-4398 (Linear issue number - should be visible at the bottom of the GitHub issue description)

**Before Changes:** 
https://www.loom.com/share/a3ec8e7b7181419d91b12abfa9729a99?sid=a8440350-c26e-4778-abd9-73ce539338f6

**After Changes**
https://www.loom.com/share/a36bf823820947d2b0d2225853363885?sid=866df2d7-dafb-4a63-8e72-cd3f5ed8f293

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [ ] I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com/docs). If N/A, write N/A here and check the checkbox.
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works.

2024-10-01 17:40 UTC, keithwillcode commented
@vijayraghav-io Really appreciate your work on this PR. Helps us move forward in using repositories more.

A suggestion for the future. Avoid big refactors with feature changes.
- If the refactor causes an issue for some reason and we need to revert/rollback, the new feature is also lost in the process. Ideally, the feature is added in 1 PR and the refactor is done in another PR to avoid this situation.
- It makes reviewing the PR harder because the context is wider.

2024-10-01 17:41 UTC, keithwillcode requested changes
There don't seem to be new tests added to verify this functionality. Please add 🙏

2024-10-02 01:24 UTC, vijayraghav-io commented
> @vijayraghav-io Really appreciate your work on this PR. Helps us move forward in using repositories more.
> 
> A suggestion for the future: avoid big refactors with feature changes.
> - If the refactor causes an issue for some reason and we need to revert/rollback, the new feature is also lost in the process. Ideally, the feature is added in 1 PR and the refactor is done in another PR to avoid this situation.
> - It makes reviewing the PR harder because the context is wider.

Thankyou! :pray @keithwillcode 

Sure, will take care of having refactor in a separate PR. I can split this right away, will update with new PR for refactor.

Also will add tests for the fix.

2024-10-17 00:53 UTC, vijayraghav-io commented
sorry for the delay, in middle of other PR, will update this PR by this week.

2024-10-23 11:43 UTC, vijayraghav-io commented
creation of tests in progress....

2024-10-23 15:24 UTC, vijayraghav-io commented on packages/lib/server/repository/bookingReference.ts
> +      });
raw SQL Query generated -
```
SELECT
    "BookingReference"."id",
    "BookingReference"."type"
FROM
    "public"."BookingReference"
LEFT JOIN
    "public"."Booking" AS "j1" ON "j1"."id" = "BookingReference"."bookingId"
WHERE
    "BookingReference"."type" = $1
    AND "j1"."userId" = $2
    AND "j1"."id" IS NOT NULL
    AND "BookingReference"."credentialId" IS NULL
    AND "BookingReference"."externalCalendarId" IN ($3)
    AND "BookingReference"."deleted" IS NULL
OFFSET $4;
```

2024-10-23 15:31 UTC, vijayraghav-io commented on packages/lib/server/repository/bookingReference.ts
> +      });
raw SQL Query generated -
```
SELECT
    "BookingReference"."id",
    "BookingReference"."type"
FROM
    "public"."BookingReference"
LEFT JOIN
    "public"."Booking" AS "j1" ON "j1"."id" = "BookingReference"."bookingId"
WHERE
    "BookingReference"."type" = $1
    AND "j1"."userId" = $2
    AND "j1"."id" IS NOT NULL
    AND "BookingReference"."credentialId" IS NULL
    AND "BookingReference"."externalCalendarId" IN ($3)
    AND "BookingReference"."deleted" IS NULL
OFFSET $4;
```
IMO: results in single left-join, not much complex.

2024-10-24 17:59 UTC, vijayraghav-io commented
Hi @keithwillcode,
Sorry for the delay!
Updated this PR to have issue fix only, without using Repository approach.

Updates in comparison to previous approach :
1. Reverted the use of `CredentialRepository` wherever the Credential is being created with `prisma.credential.create()` as it was before.
2. Calling the `reconnectWithNewCredential()` function after the `credential` is created, wherever it is being created.

IMO the best place to have this function - `reconnectWithNewCredential()` is inside BookingReferenceRepository.

To do:
Will create a new PR that will -
1. Replace all `prisma.credential.create()` with `CredentialRepository.Create()`. 
2. `BookingReferenceRepository.reconnectWithNewCredential()` will be called from within the `CredentialRepository.Create()`. 
This also ensures that in future if, we have a new req to write code to create new `credential` , dev or reviewer need not remember to call `BookingReferenceRepository.reconnectWithNewCredential()` after credential creation. But just ensure to use the CredentialRepository.Create(), instead of directly using prisma. 
3. Calling the `reconnectWithNewCredential()` from outside the Repository, introduced from this PR will have to be removed, after this current PR is merged.

2024-11-13 16:23 UTC, vijayraghav-io commented
> @vijayraghav-io could pls fix the conflicts🙏

🙏  sure will do

2024-11-13 17:37 UTC, vijayraghav-io commented
@anikdhabal , resolved merge conflicts.

2024-12-03 10:06 UTC, vijayraghav-io commented
Gentle reminder!

2024-12-11 16:24 UTC, keithwillcode commented
@emrysal Can you please review this? I know you had fixed a lot of the credentials issues with booking references in the db.

2025-06-26 09:36 UTC, Devanshusharma2005 requested changes
hey @vijayraghav-io Thanks for the PR! Just noticed there aren’t any new tests to check the "reconnectWithNewCredential" functionality could you add some automated tests to make sure orphaned BookingReferences get reconnected properly for both user and team cases? Also, there are some merge conflicts right now, so please rebase your branch onto main, fix those up, and push the changes. Once you’ve added the tests and sorted the conflicts, just ping the reviewers so we can take another look. Thanks!

2025-06-26 09:51 UTC, vijayraghav-io commented
> hey @vijayraghav-io Thanks for the PR! Just noticed there aren’t any new tests to check the "reconnectWithNewCredential" functionality could you add some automated tests to make sure orphaned BookingReferences get reconnected properly for both user and team cases? Also, there are some merge conflicts right now, so please rebase your branch onto main, fix those up, and push the changes. Once you’ve added the tests and sorted the conflicts, just ping the reviewers so we can take another look. Thanks!

sure, will resolve merge conflicts and update!

2025-06-30 10:15 UTC, vijayraghav-io commented
@Devanshusharma2005 , @keithwillcode , @emrysal 

🙏 
To reiterate the approach and updates after resolving merge conflicts (since CredentialRepository was also created by other PR). 

Leveraged existing CredentialRepository to reconnect orphaned BookingReferences.
1. Reconnecting BookingReferences with Credential is called in 3 scenarios -
    i. When New Credential is created using CredentialRepository.create
    ii. When New SelectedCalendar is created using SelectedCalendarRepository.create
    iii. When SelectedCalendar is updated using SelectedCalendarRepository.upsert
2. The combination of 3 fields - 'userId or teamId' , 'credentialType' , 'credentialId==null' is used to detect orphaned bookingReference. For Calendar Apps, additional field - 'externalCalendarId' is used to detect orphaned bookingReferences.
3. Replaced all `prisma.credential.create` in app-store packages with `CredentialRepository.create` so that `BookingReferences.reconnectWithNewCredential()` is called.

Tested again the functionality, latest loom - https://www.loom.com/share/a8397107cbe3416ea7ac7997ee832e15?sid=51e7aac3-8ca1-4ce7-8bc5-b4578578de43 

The failing tests `E2E API v2` , `E2E Embed React` requires re-run, were passing in previous run.

2025-06-30 10:18 UTC, vijayraghav-io commented
> hey @vijayraghav-io Thanks for the PR! Just noticed there aren’t any new tests to check the "reconnectWithNewCredential" functionality could you add some automated tests to make sure orphaned BookingReferences get reconnected properly for both user and team cases? Also, there are some merge conflicts right now, so please rebase your branch onto main, fix those up, and push the changes. Once you’ve added the tests and sorted the conflicts, just ping the reviewers so we can take another look. Thanks!

@Devanshusharma2005 , had already added the tests for same, please refer https://github.com/calcom/cal.com/pull/16878/files#diff-6a23fb219767e34088b3d5162be4eb918fe782756890d00bd33da6e2edf6d22a 

[packages/lib/server/repository/bookingReference.test.ts](https://github.com/calcom/cal.com/pull/16878/files#diff-6a23fb219767e34088b3d5162be4eb918fe782756890d00bd33da6e2edf6d22a)

2025-07-03 11:27 UTC, vijayraghav-io commented
All tests are passing!

2025-09-08 04:09 UTC, anikdhabal commented
@vijayraghav-io can you pls fix the conflicts?

2025-09-08 07:26 UTC, vijayraghav-io commented on packages/app-store/feishucalendar/api/callback.ts
>      } else {
The other calendars like google-calendar are already using repository for `selectedCalendar` creation.
Ref - https://github.com/calcom/cal.com/blob/411a14dd3d7771921bb88bdd573b6448007be64f/packages/app-store/googlecalendar/lib/CalendarService.ts#L1037

Hence wherever the repository functions are already used for `selectedCalendar` creation, the reconnection of bookingReferences (introduced from this PR) will work.

While creating this PR, was not sure if replacement of direct `prisma.create` with repository function everywhere, for `selectedCalendar` also should also be part of this PR. 

Will it include it as it make sense that reconnection should work for all calendars.

2025-09-08 08:07 UTC, vijayraghav-io commented on packages/app-store/feishucalendar/api/callback.ts
>      } else {
Also in existing code though newCredential was created if no currentCredential, but this newCredential was not used in creating the selectedCalendar.

2025-09-08 09:53 UTC, vijayraghav-io commented on packages/lib/server/repository/credential.ts
> +import { BookingReferenceRepository } from "./bookingReference";
updated to not have circular dependency

2025-09-08 10:07 UTC, vijayraghav-io commented on packages/app-store/larkcalendar/api/callback.ts
>          });
since office365calendar/api/callback.ts  and zohocalendar/api/callback.ts  have logic in catch block, so didn't want to disturb this, hence manually calling reconnect function at the end, to ensure reconnect happens if not reconnected properly

2025-09-08 10:09 UTC, vijayraghav-io commented on packages/lib/server/repository/credential.ts
>  };
This is an existing issue that key is defined as any,
updating this requires lot of code changes which is not related to current PR scope.

2025-09-08 10:10 UTC, vijayraghav-io commented on packages/lib/server/repository/credential.ts
> +
Not implementing this change as of now, as it requires type updation in lot of other files.
But ensured that no where teamId and userId , both are passed in the payload. Either of them is only passed.

2025-09-08 10:22 UTC, vijayraghav-io commented
@anikdhabal , resolved merge conflicts and addressed latest coderabbit comments.

2025-11-21 19:11 UTC, closed without merging

2025-11-21 19:11 UTC, dhairyashiil commented
Thank you so much for your time and effort on this. I checked with the team, and it looks like this issue isn’t planned for the near future. If we need it later, we’ll be sure to revisit your work. For now, I’ll close the PR. Thank you again 🙏🏼