feat: payments tab for event types atom
calcom/cal.com pull request #16892
Opened 2024-10-01 10:00 UTC by Ryukemeister

## What does this PR do?

- Fixes #XXXX (GitHub issue number)
- Fixes CAL-XXXX (Linear issue number - should be visible at the bottom of the GitHub issue description)

## Mandatory Tasks (DO NOT REMOVE)

- [ ] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [ ] I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com/docs). If N/A, write N/A here and check the checkbox.
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

- Are there environment variables that should be set?
- What are the minimal test data to have?
- What is expected (happy path) to have (input and output)?
- Any other important info that could help to test that PR

## Checklist

- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my changes generate no new warnings

2024-10-09 13:03 UTC, Ryukemeister commented on apps/api/v2/src/modules/atoms/services/event-types-atom.service.ts
> +  async getEventTypesAppIntegration(slug: string, userId: number, userName: string | null, teamId?: number) {
Will simplify this once #16946 merges so that we don't have to repeat this twice in two different place

2024-10-09 13:04 UTC, Ryukemeister commented on packages/platform/libraries/package.json
> +  "version": "1.2.3",
This is temporary, will fix it once we release a new version of platform libraries.

2024-10-09 13:05 UTC, Ryukemeister commented on apps/api/v2/package.json
> +    "@calcom/platform-libraries-1.2.3": "npm:@calcom/platform-libraries@1.2.3",
Same here it's temporary, will be fixed once we release a new version of platform libraries.

2024-10-15 18:08 UTC, Ryukemeister commented
Payments tab is ready for event types, but unless we don't have the payment form in the Booker component this is not of much use.

2024-10-21 11:43 UTC, ThyMinimalDev approved these changes
great work

2024-10-21 11:44 UTC, ThyMinimalDev requested changes, later dismissed
remove yarn.lock

2024-10-21 12:48 UTC, ThyMinimalDev approved these changes

2024-10-21 13:19 UTC, merged