Chore/refactor shell
calcom/cal.com pull request #16893
Opened 2024-10-01 10:15 UTC by sean-brydon

## What does this PR do?

- Fixes #XXXX (GitHub issue number)
- Fixes CAL-XXXX (Linear issue number - should be visible at the bottom of the GitHub issue description)

## Mandatory Tasks (DO NOT REMOVE)

- [ ] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [ ] I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com/docs). If N/A, write N/A here and check the checkbox.
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

- Are there environment variables that should be set?
- What are the minimal test data to have?
- What is expected (happy path) to have (input and output)?
- Any other important info that could help to test that PR

## Checklist

- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my changes generate no new warnings

2024-10-01 12:19 UTC, sean-brydon commented on packages/features/auth/lib/hooks/useRedirectToLoginIfUnauthenticated.tsx
Move to a hook that can live outside of shell

2024-10-01 12:19 UTC, sean-brydon commented on packages/features/auth/lib/hooks/useRedirectToOnboardingIfNeeded.tsx
Same goes as above with its helper fuctions

2024-10-01 12:20 UTC, sean-brydon commented on packages/features/ee/support/lib/intercom/useIntercom.ts
Create a hook that boots intercom - no need for this to live directly in shell either. Means we can control when the "me" query is called much easier i the future as it was being called on every render

2024-10-01 12:20 UTC, sean-brydon commented on packages/features/shell/Shell.tsx
Wow thats a lot less lines

2024-10-01 12:21 UTC, sean-brydon commented on packages/features/shell/banners/LayoutBanner.tsx
> +        }
The old confused me - its exactly the same as this but way more simple
```ts
           {Object.keys(banners).map((key) => {
              if (key === "teamUpgradeBanner") {
                const Banner = BannerComponent[key];
                return <Banner data={banners[key]} key={key} />;
              } else if (key === "orgUpgradeBanner") {
                const Banner = BannerComponent[key];
                return <Banner data={banners[key]} key={key} />;
              } else if (key === "verifyEmailBanner") {
                const Banner = BannerComponent[key];
                return <Banner data={banners[key]} key={key} />;
              } else if (key === "adminPasswordBanner") {
                const Banner = BannerComponent[key];
                return <Banner data={banners[key]} key={key} />;
              } else if (key === "impersonationBanner") {
                const Banner = BannerComponent[key];
                return <Banner data={banners[key]} key={key} />;
              } else if (key === "calendarCredentialBanner") {
                const Banner = BannerComponent[key];
                return <Banner data={banners[key]} key={key} />;
              } else if (key === "invalidAppCredentialBanners") {
                const Banner = BannerComponent[key];
                return <Banner data={banners[key]} key={key} />;
              }
            })}
```

2024-10-01 12:22 UTC, sean-brydon commented on packages/features/shell/banners/useBanners.ts
> +const useBanners = () => {
Lets just have one hook to get all banners and calculate the height

2024-10-01 15:27 UTC, joeauyeung requested changes
Great refactor @sean-brydon

## Test Cases
- Desktop view ✅ 
- Reduced side bar ✅ 
- Mobile nav ❌ 
- Unauthed redirect to login page ✅ 
- Onboarding trigger ✅ 

## Blocking
- If we're refactoring right now can we abstract some of the hooks logic so we can prepare for the app router migration? If it's too big then I'm ok having this in a follow up PR. FYI @hbjORbj 
- In the mobile nav container when clicking `More` I get this error
![CleanShot 2024-10-01 at 10 27 25@2x](https://github.com/user-attachments/assets/981e01bb-c36f-49cb-bc09-f4e689336953)


## Non-blocking
- Have you considered using `useCallback` at all to help with preventing rerenders? I'm also ok with having it in a follow up PR

2024-10-02 08:41 UTC, sean-brydon commented on packages/features/shell/user-dropdown/ProfileDropdown.tsx
> +          className="min-w-56 hariom group overflow-hidden rounded-md">
Thats a great question lol

2024-10-02 08:43 UTC, sean-brydon commented
> * Have you considered using `useCallback` at all to help with preventing rerenders? I'm also ok with having it in a follow up PR

100%! As i mentioned in the PR description - i've not made any perf improvements here. Just making the component more manageable! 

> If we're refactoring right now can we abstract some of the hooks logic so we can prepare for the app router migration? If it's too big then I'm ok having this in a follow up PR. FYI @hbjORbj

I don't understand what you mean here? I've tried to abstract all hooks that were present in the shell

> Mobile nav ❌
On it! Also some type errors i need to fix around this area too

2024-10-02 14:09 UTC, joeauyeung approved these changes
Navigation is now working as expected. 

In terms of my abstracting hooks logic comment. We can't call hooks in server components so ideally I would have liked to see the logic inside of the hooks to be abstracted. Although looking through it some more I realize it would be too big for this PR so let's cross that bridge when we get there.

2024-10-02 14:35 UTC, merged