Updated Huddle01 App Flow
calcom/cal.com pull request #16907
Opened 2024-10-02 11:51 UTC by ponikar

## What does this PR do?

- We at huddle01 has revamped serval things including how users used to interact and communicate through huddle01 app. Huddle01 has a dedicated OAuth mechanism to empowers third party application like CalCom. So in order to make calcom work with new flow, we have re-written the current app. 
- Introduced Authentication page to let user confirm their identity before scheduling a call.  
- Huddle01 OAuth support that work independently.  
- New sets of API to communicate with huddle01 servers.  

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [ ] I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com/docs). If N/A, write N/A here and check the checkbox.
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?
- Once you install a fresh huddle01 app, you are required to confirm your identify via login to Huddle01 auth page. 
- Once you authentication process succeed, you can configure your events to use huddle01 app to schedule meetings when users make booking. 
- Now while booking a call, user should see Huddle01 app to book a call. 
- API calls should work and user should see the meeting link after he/she makes booking. 
- Test modify, cancel flow, we have added separate apis call correspond to each functionality. 
- In the booking pages, meeting details should be visible. 

- Are there environment variables that should be set?
Yes, We have new `HUDDLE01_API_TOKEN` to handle authentication process. It needs to be set. 

- What are the minimal test data to have?
Huddle01 account to test authenticate. 
- What is expected (happy path) to have (input and output)?
- Install huddle01 app, complete authentication process.
- Configure your events to use huddle01 app for scheduling meetings. 
- Users should be able to schedule, modify and cancel the meeting. 

## Checklist

- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
I haven't commented my code, particularly in hard-to-understand areas
I haven't checked if my changes generate no new warnings

2024-10-02 11:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/calcom/cal.com?pullRequest=16907) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/calcom/cal.com?pullRequest=16907) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/calcom/cal.com?pullRequest=16907) it.</sub>

2024-10-02 12:53 UTC, anikdhabal requested changes
Hey @ponikar, can you please uncommit the lock file? I don't think it's need to update for the current changes.

2024-10-02 13:47 UTC, anikdhabal commented on packages/app-store/huddle01video/api/callback.ts
> +  const { identityToken } = req.query;
grrg

2024-10-02 13:47 UTC, anikdhabal commented on packages/app-store/huddle01video/api/callback.ts
> +
grg

2024-10-02 17:41 UTC, anikdhabal commented
Thanks @ponikar , Could you also please add a README to explain the process of obtaining the Huddle API token? Like this:- https://github.com/calcom/cal.com/blob/main/packages/app-store/webex/README.md

2024-10-03 05:43 UTC, ponikar commented
> Hey @ponikar, can you please uncommit the lock file? I don't think it's need to update for the current changes.

Hey @anikdhabal 
We don't provide third party authentication publicly as of now. We have internal APIs to create token to identify Calcom internally. It shouldn't affect calcom users to any other ways. 

If anyone requires to generate a similar token they can reach out to support@huddle01.com 

Feel free to share concern regarding any of it.

2024-10-03 15:41 UTC, anikdhabal commented on yarn.lock
> +  linkType: hard
Remove unnecessary changes. Need one line space

2024-10-03 15:41 UTC, anikdhabal commented on .env.appStore.example
> +HUDDLE01_API_TOKEN=
same here

2024-10-04 07:48 UTC, ponikar commented
> Hey @ponikar I got you! Could you please provide a Loom video of the entire workflow?

Sure. Our team will make a video to understand the entire flow.

2024-10-04 07:56 UTC, anikdhabal commented
> Sure. Our team will make a video to understand the entire flow.

I mean from our app's perspective: starting with installation from our app store using OAuth, then book an event with this app

2024-10-04 07:58 UTC, anikdhabal commented on .env.appStore.example
> +HUDDLE01_API_TOKEN=
I suggest that you leave one extra line. It currently ends at 144, line should end at 145. Just press Enter

2024-10-04 07:59 UTC, ponikar commented
> > Sure. Our team will make a video to understand the entire flow.
> 
> I mean from our app's perspective: starting with installation from our app store using OAuth, then book an event with this app

Thanks for the detailed requirement.

2024-10-04 09:34 UTC, ponikar commented
@anikdhabal we have some concern regarding how calcom will manage huddle01 flow for older users who is using the old version. Can we connect over slack or email? Please provide your email address to communicate further.

2024-10-07 08:21 UTC, ponikar commented
> @anikdhabal we have some concern regarding how calcom will manage huddle01 flow for older users who is using the old version. Can we connect over slack or email? Please provide your email address to communicate further. 

Hey @anikdhabal any updates on this? We are creating a video but want to clarify this as well.

2024-10-08 05:55 UTC, ponikar commented
@anikdhabal 
Here's video demonstration https://www.loom.com/share/d3d725a07fc54ae0b7cb95a608b183d2?sid=b5c0a6fd-3766-45e8-83d4-c38134e3088f. 

Let me know if you need anything else.

2024-10-08 06:55 UTC, anikdhabal commented
@ponikar thanks for the loom video, I will give the final review.

2024-10-15 06:13 UTC, ponikar commented
@anikdhabal Hey any updates on this?

2024-10-17 04:29 UTC, anikdhabal commented
@ponikar Thanks for your work. But I have a suggestion for users who have already installed it

I think we can keep the same app and implement oauth for new install. But just making sure that legacy ones still works. And if someone wants to use the new one they can just uninstall and reinstall. We could also provide some banner for people with the legacy version

2024-10-17 11:16 UTC, ponikar commented
Thanks for the response. I will talk with my team and will get back to you by end of the day.

2024-10-18 05:17 UTC, ponikar commented
Hey @anikdhabal

Thanks for the response, We are good with the flow you suggested, We will support backward compatibly for old users. 

> We could also provide some banner for people with the legacy version
Please share more details on this, we would want to encourage old users to update the app. 

Also, If everything is good, can you please tell me where this PR will get merge and deploy?

2024-10-21 08:52 UTC, ponikar commented
Hey @anikdhabal please let me know if we are good with merging this PR, let me know if I have to make any changes. 
Thanks

2024-10-22 11:23 UTC, anikdhabal approved these changes
Great Work @ponikar

2024-10-22 11:50 UTC, merged

2024-10-24 12:17 UTC, ponikar commented
Thank you so much @anikdhabal.

2024-10-29 05:51 UTC, ponikar commented
@anikdhabal We can see the Calcom app has been updated. However when we are trying to test new flow its scheduling meeting to Calcom video. Also your team didn't ask for `API_KEY` without this you can't communicate with our backend. 

Please let me know if I have missed something from my end. Users are not able to create meetings and they are reaching out to us.

2024-10-29 05:57 UTC, ponikar commented
cc @AkMo3

2024-10-29 06:02 UTC, anikdhabal commented
Hey @ponikar, have you tried uninstalling and reinstalling it? Does it fall back to the call video? If the problem persists with the new flow, then I think I will check that. Also, were you able to authenticate and install the app successfully? If possible, could you please share a video of the whole flow?

2024-10-29 06:09 UTC, ponikar commented
Hi @anikdhabal 
Yes I reinstalled the app, the authentication worked and yes it fallbacks to call video. We were not able to see any logs from the backend to debug this issue.

2024-10-29 06:43 UTC, anikdhabal commented
Thanks @ponikar will get back to this

2024-10-30 06:37 UTC, ponikar commented
@anikdhabal We noticed that your team has disabled our old application without notifying us on prior. This is important for our users. Please restore the old application till the time your team figure out the fix. 

Please consider this one as priority.

2024-10-30 07:36 UTC, anikdhabal commented
@ponikar what do you mean by disabling the old application? Could you pls explain? Btw it's there in the app store, maybe disabled and quickly enable it for testing

2024-10-30 07:50 UTC, ponikar commented
calcom disabled our app and sent email to all our users. We have no idea why your team did this?

![image](https://github.com/user-attachments/assets/14de1abf-1df7-44b8-80a7-8594e983d46d)

2024-10-30 07:54 UTC, ponikar commented
I am requesting you to take this a priority as this is affecting out partners. Please inform us on priority. Is there any way to reach out you via slack? This is urgent and important we can afford much delay on this.

2024-10-30 07:57 UTC, anikdhabal commented
> calcom disabled our app and sent email to all our users. We have no idea why your team did this?

Ah, this one! Don’t panic; I was just working to fix the current issue in the morning. I disabled it and then enabled it again. Now there’s no issue, and the app is working. Inform it other
![Screenshot 2024-10-30 130449](https://github.com/user-attachments/assets/3c187d09-69da-4f89-84ee-e7ae7896859f)

2024-10-30 08:00 UTC, ponikar commented
Thanks @anikdhabal if it is possible can we talk about this on slack/discord, this is really important for us. 
also what will happen now, will all users use new version? 

Our new version is not working as well, its falling back to cal video. We cannot debug this from our end.

2024-10-30 08:01 UTC, ponikar commented
Can you send this confirmation email to all our existing users if possible, our users got panicked when they received this email.

2024-10-30 08:02 UTC, anikdhabal commented
@ponikar let's talk about it in discord. Pls share you your link

2024-10-30 08:03 UTC, arcinston commented
hi @anikdhabal , Arush here from Huddle01 Engineering team

this email has been sent to all our addon users which has lead to user panic and lots of support tickets opening

would request you to send an email as a followup informing all users that the addon is enabled

this would help swiftly solve this issue

2024-10-30 08:06 UTC, arcinston commented
this is the link to our discord community : https://discord.gg/d9587UPR

2024-10-30 08:08 UTC, arcinston commented
my username on discord : arcinston

send across a friend request and lets resolve this ASAP 
thanks