feat: Add Adyen Payment App
calcom/cal.com pull request #17151
Opened 2024-10-17 19:58 UTC by vijayraghav-io

## What does this PR do?

- Fixes #16860 
- Fixes CAL-4427 

https://www.loom.com/share/dd294f65d58c432eb7d74ecca2e0fac0?sid=4a17a78a-ac27-4780-a596-772e8ca1c41f

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [ ] I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox.
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works.

Refer docs for setting up Adyen account in live and test, creation of OAuth App -
https://docs.adyen.com/development-resources/oauth/
https://docs.adyen.com/development-resources/webhooks/verify-hmac-signatures/?programming_language=js

2024-10-18 08:00 UTC, vijayraghav-io commented
Did one more round of self-review and some minor refactoring and removed not required code.

Now, PR is fully ready for review!

2024-10-18 10:51 UTC, Praashh commented
Hey @vijayraghav-io , thanks for contributing, I need to test this locally which may take time.

2024-10-30 15:04 UTC, vijayraghav-io commented
Please Note:
Usage of API keys, i.e. asking user to enter API keys while installing Adyen App is not a good approach or best practice.
Though all examples in Adyen repos shows this approach, it is only for understanding how Adyen APIs work and the payment flow.

As a 3rd party App or Partner ,we should ask for authorization of the user while installing and get accessToken and access the APIs on behalf of the user. 
This is the approach implemented in this PR with oAuth Integration and PKCE Auth flow as recommended by Adyen docs for Partner's implementation.

2024-11-22 20:07 UTC, Praashh requested changes
https://github.com/user-attachments/assets/6c7b343c-deb0-4afb-8c08-96bfe56215f1

If somehow the app installation failed, then it'll not mark as connected/installed.

2024-11-23 11:15 UTC, vijayraghav-io commented
> If somehow the app installation failed, then it'll not mark as connected/installed.

An account and oAuth App needs to be created with cal domain in Adyen. 
The clientId and clientSecret of this oAuth App needs to be entered by cal admin while enabling Adyen App, this is the primary step. 
Without this step, we get error.

PFB video for reference (this step is also shown in the main video in description)
https://www.loom.com/share/44a518bd141543789f08080db657ccd3?sid=6785caf0-81a5-4888-9f5b-7e5f1e93b9cb

Anyway, updated to show appropriate err msg if this step is missed (should not be) in any case.

2024-11-23 12:35 UTC, Praashh commented
> > If somehow the app installation failed, then it'll not mark as connected/installed.
> 
> An account and oAuth App needs to be created with cal domain in Adyen. The clientId and clientSecret of this oAuth App needs to be entered by cal admin while enabling Adyen App, this is the primary step. Without this step, we get error.
> 
> PFB video for reference (this step is also shown in the main video in description) https://www.loom.com/share/44a518bd141543789f08080db657ccd3?sid=6785caf0-81a5-4888-9f5b-7e5f1e93b9cb
> 
> Anyway, updated to show appropriate err msg if this step is missed (should not be) in any case.

but if it failed then we shouldn't have already installed thing on the apps route

2024-11-23 12:57 UTC, vijayraghav-io commented
> but if it failed then we shouldn't have already installed thing on the apps route

Yes this is taken care

2024-11-23 17:37 UTC, vijayraghav-io commented
Just for info , other payment apps like alby, paypal ,... also have similar issue. Similar fix would be required in their add.ts as well.
May be can be fixed with separate issues. 
Anyway , its rarely occuring scenario if client_id and client_secret is not populated in App table for respective apps, and if App is tried to be used.

2024-12-08 08:04 UTC, vijayraghav-io commented
Gentle Reminder!

2024-12-08 08:13 UTC, Praashh reviewed
@vijayraghav-io , I'll give it a touch.

2024-12-08 14:21 UTC, vijayraghav-io commented
> @vijayraghav-io your branch has some conflicts please, I'll give it a touch.

resolved conflicts

2024-12-11 13:16 UTC, vijayraghav-io commented
> 
> @vijayraghav-io There are some minor conflicts, can you please resolve 🙏

@Praashh  resolved

2024-12-12 17:28 UTC, Praashh reviewed
working fine locally, waiting for @anikdhabal 's review.

2024-12-13 06:58 UTC, Praashh requested changes
<img width="259" alt="Screenshot 2024-12-13 at 12 27 14 PM" src="https://github.com/user-attachments/assets/f9693819-4aef-493e-8796-43bc71da4b76" />

@vijayraghav-io can you please fix this.

should be Connect With Adyen.

2024-12-13 07:05 UTC, vijayraghav-io commented
> <img alt="Screenshot 2024-12-13 at 12 27 14 PM" width="259" src="https://private-user-images.githubusercontent.com/99237795/395460827-f9693819-4aef-493e-8796-43bc71da4b76.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwNzM3NjYsIm5iZiI6MTczNDA3MzQ2NiwicGF0aCI6Ii85OTIzNzc5NS8zOTU0NjA4MjctZjk2OTM4MTktNGFlZi00OTNlLTg3OTYtNDNiYzcxZGE0Yjc2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEzVDA3MDQyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0ODkzMTE4Mzc0Mjc2YWExNzRhYmMzODRjZTBkNDk0ZTRlMjQ2MzQ4MDM4NzlkYmMyOTkxZDYyMWM1MjZkOGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.RBks1W6w3eOUc41TjzBIREeZVAOHoXMRKzfsA6neDb0">
> @vijayraghav-io can you please fix this.
> 
> should be Connect With Adyen.

ok, sure 🙏

2024-12-13 17:46 UTC, vijayraghav-io commented
> > @vijayraghav-io can you please fix this.
> > 
> > should be Connect With Adyen.
> 
> ok, sure 🙏 

@Praashh , updated :pray

2024-12-13 19:58 UTC, Praashh commented
> > > @vijayraghav-io can you please fix this.
> > > should be Connect With Adyen.
> > 
> > 
> > ok, sure 🙏
> 
> @Praashh , updated 🙏

this will need an review from @anikdhabal 🙏

2024-12-30 08:44 UTC, vijayraghav-io commented
Gentle Reminder for review.

2025-02-05 16:20 UTC, retrogtx commented
@vijayraghav-io we are looking at this PR for the same! however for testing Adyen has closed the testing accounts for now.

https://www.adyen.com/signup

2025-02-07 01:11 UTC, vijayraghav-io commented
> @vijayraghav-io we are looking at this PR for the same! however for testing Adyen has closed the testing accounts for now.
> 
> https://www.adyen.com/signup

Thankyou! for the update @retrogtx

2025-03-10 07:33 UTC, anikdhabal commented
@vijayraghav-io could you pls fix the conflicts

2025-03-10 07:53 UTC, vijayraghav-io commented
> @vijayraghav-io could you pls fix the conflicts

ok sure

2025-03-10 13:00 UTC, vijayraghav-io commented
> > @vijayraghav-io could you pls fix the conflicts
> 
> ok sure

after merge, yarn.lock has some minor issues, 
will fix this once i complete working on the other PR (OOO daterange filter)

2025-07-01 04:06 UTC, Devanshusharma2005 commented
@vijayraghav-io can you please address the conflicts. Drafing the pr for now.

2025-07-01 05:54 UTC, vijayraghav-io commented
> @vijayraghav-io can you please address the conflicts. Drafing the pr for now.

Sure, will resolve conflicts and update.

2025-07-03 13:06 UTC, vijayraghav-io commented
@Devanshusharma2005 , resolved merge conflicts.

2025-07-09 06:35 UTC, anikdhabal commented
@vijayraghav-io thanks for your work. Firstly, the attached Adyen docs link currently throws a 404 error when opened. Also, how do we generate API keys—for live or for development?

2025-07-09 08:23 UTC, vijayraghav-io commented
> @vijayraghav-io thanks for your work. Firstly, the attached Adyen docs link currently throws a 404 error when opened. Also, how do we generate API keys—for live or for development?

@anikdhabal 🙏 , Updated the first 3 links in description (adyen has updated recently the route to these documents from .../development-resources/... to ../partners/... , updated accordingly)
Also added note about using `oAuth App` approach instead of API keys 

To create a development/Test account :
- Go to this link https://www.adyen.com/signup and fill the form
- Business Email should be of a registered domain type (gmail will not work) . Example : _someone_@cal.com
- Once a account is created with registered domain email id, log in to the account and navigate (on left menu) to Developers -> OAuth Apps -> And create a app 
- Copy the client_id and client_secret generated
Use these client_id and client_secret to add the adyen app in cal.com

To create a production/live account :
- contact adyen sales team - https://www.adyen.com/contact/sales

2025-07-09 09:55 UTC, vijayraghav-io commented
@anikdhabal , FYI Tested this PR by creating an adyen account with an domain email id.
Please refer loom video link added in description.

2025-08-11 04:04 UTC, anikdhabal commented
Hey @vijayraghav-io Thanks for your work. We’ve tried to connect with the Adyen team for a long time, but we haven’t received any responses. Closing this for now

2025-08-11 04:04 UTC, closed without merging