Updated city-timezones to support Kyiv
calcom/cal.com pull request #17159
Opened 2024-10-18 10:41 UTC by AlexHladin

## What does this PR do?

This PR fixes the incorrect timezone name for Kyiv.

- Fixes #12224 (GitHub issue number)

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [ ] I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox.
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works.

2024-10-24 16:08 UTC, zomars approved these changes, later dismissed

2024-10-30 20:16 UTC, PeerRich submitted a review, later dismissed

2024-11-06 12:35 UTC, keithwillcode requested changes, later dismissed
Unit tests are failing

2024-11-24 17:59 UTC, PeerRich commented
why are there so many other changes?

2024-11-30 13:36 UTC, AlexHladin commented
Hey @keithwillcode @zomars @PeerRich 
The PR is passed unit tests and types check.
Could you please review and merge PR?

2025-01-14 15:55 UTC, zomars commented
Closing this PR as it is doing way more that describes. Feel free to re-open with only the relevant parts. Also feel free to open another one with type improvements if necessary.

2025-01-14 15:55 UTC, closed without merging

2025-01-14 15:56 UTC, hbjORbj commented
@AlexHladin Hey Alex, there's lots of type improvements going on in this PR. While we massively appreciate it, it makes it very difficult to review. Please open a fresh PR and request me a review.

2025-01-14 15:59 UTC, AlexHladin commented
@hbjORbj @zomars types changes are required, because react-timezone requires it. I can't skip types improvement things.