Fix inconsistent phrasing and remove duplicate words in localization …
calcom/cal.com pull request #17339
Opened 2024-10-25 19:11 UTC by AliPythonDev

…strings in common.json

## What does this PR do?
This PR refactors the localization strings in common.json for consistency and clarity, addressing several issues related to phrasing and grammatical accuracy. The changes enhance the overall readability of the user interface.

## Mandatory Tasks (DO NOT REMOVE)
- [ ] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [ ] I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox.
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works.

2024-10-26 04:58 UTC, Praashh approved these changes
looks good to me, please change the PR title to fix: Inconsistent phrasing and remove duplicate words in localization #17339

2024-10-26 14:22 UTC, Praashh requested changes
please change the PR title to fix: Inconsistent phrasing and remove duplicate words in localization https://github.com/calcom/cal.com/pull/17339

2024-10-27 14:44 UTC, Praashh approved these changes, later dismissed

2024-10-28 14:10 UTC, anikdhabal approved these changes

2024-10-28 14:10 UTC, merged