Fix URL by removing slash and backslash
calcom/cal.com pull request #1733
Opened 2022-02-07 22:06 UTC by Jenietoc

## What does this PR do?

This PR validates that when creating or editing an eventType it is not possible to write `slash` or `backslash`.

Fixes #1729

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

- [X] This implementation was tested by creating and editing several newTypes and the validation worked correctly.

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code and corrected any misspellings
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-02-08 20:02 UTC, zomars requested changes
Left some comments, we should also avoid unsanitized slugs to reach the DB by updating our schema here:

https://github.com/calcom/cal.com/blob/38b41f0adbdfd25b72510375168cecd2d6f503b9/prisma/zod-utils.ts#L9

To this:

```js
export const eventTypeSlug = z.string().transform((val) => slugify(val.trim()));
```

2022-02-08 20:02 UTC, zomars commented on components/eventtype/CreateEventType.tsx
> +        }
Let's avoid duplicating code by just using our `slugify` function located at `@lib/slugify`

2022-02-08 20:02 UTC, zomars commented on pages/event-types/[type].tsx
> +                          }}
Same as above

2022-02-08 23:06 UTC, Jenietoc commented on components/eventtype/CreateEventType.tsx
> +        }
Perfect, I have already implemented slugify

2022-02-09 13:54 UTC, Jenietoc commented on pages/event-types/[type].tsx
> +                          }}
Hi @zomars is this the issue you are talking about?
`formMethods.setValue("slug", slugify(String(event.target.value)));`
Would it look good?

2022-02-09 17:13 UTC, zomars commented on pages/event-types/[type].tsx
> +                          }}
good enough yeah

2022-02-10 11:51 UTC, PeerRich commented
hey @Jenietoc, there seems to be conflicts that only the PR creator can fix "This branch has conflicts that must be resolved" 

can you also take a look at @zomars comment: https://github.com/calcom/cal.com/pull/1733#pullrequestreview-876583820?

2022-02-10 14:18 UTC, Jenietoc commented
> hey @Jenietoc, there seems to be conflicts that only the PR creator can fix "This branch has conflicts that must be resolved"
> 
> can you also take a look at @zomars comment: [#1733 (review)](https://github.com/calcom/cal.com/pull/1733#pullrequestreview-876583820)?

Hi @PeerRich conflicts have already been resolved

2022-02-11 10:48 UTC, PeerRich commented
we moved to turbo repo which caused this branch to fail @Jenietoc. can you take a look at the new file structure? `apps/web`

2022-02-11 16:41 UTC, zomars commented
There's seems to be an issue with the classname sorted. We may want to prioritize this #1796

2022-02-21 14:59 UTC, Jenietoc commented
Hello  @PeerRich  @zomars , what should I do to fix the errors in this PR? and if you can do merge.

2022-02-21 15:28 UTC, PeerRich commented
> Hello  @PeerRich  @zomars , what should I do to fix the errors in this PR? and if you can do merge.

@zomars will review and likely merge today 🙏

2022-02-21 15:47 UTC, Jenietoc commented
> > Hello @PeerRich @zomars , what should I do to fix the errors in this PR? and if you can do merge.
> 
> Hey @Jenietoc please rebase/merge from main and solve a conflict with `packages/prisma/zod-utils.ts` I tried to solved it for you but it seems that your [settings doesn't allow me to](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).

I will talk to the person who created the fork to give those permissions, I will also try to solve the conflicts. thank you very much for your time.

2022-02-21 16:53 UTC, merged

2022-02-21 16:53 UTC, zomars commented
Merging as it already passed but it got out of date again.