feat: Refactor to Use credentialRepository for credential create.
calcom/cal.com pull request #17336
Opened 2024-10-25 18:44 UTC by vijayraghav-io

## What does this PR do?

- Fixes #XXXX (GitHub issue number)
- Fixes CAL-XXXX (Linear issue number - should be visible at the bottom of the GitHub issue description)

Refer PR: https://github.com/calcom/cal.com/pull/16878

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [ ] I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox.
- [x] I confirm automated tests are in place that prove my fix is effective or that my feature works.

2024-10-26 11:08 UTC, AliPythonDev commented on apps/api/v1/pages/api/credential-sync/_post.ts
> +  const createdcredential = await CredentialRepository.create({
The Prisma.JsonNull handling for key is also a solid choice for cleaner code. Nicely done!

2024-10-26 11:12 UTC, AliPythonDev commented on apps/api/v1/pages/api/credential-sync/_post.ts
> +import { CredentialRepository } from "@calcom/lib/server/repository/credential";
Good refactor! Switching to "CredentialRepository" improves modularity and organizes dependencies more effectively with the added import.

2024-10-26 18:08 UTC, Praashh requested changes
I did notice, In the second test case you are using the `newGoogleCalCredentialId`, This might be involuntary as `google_meet_video` should ideally connect to the `newGoogleMeetCredentialId` instead of `newGoogleCalCredentialId`.

2024-10-27 06:43 UTC, vijayraghav-io commented
> I did notice, In the second test case you are using the `newGoogleCalCredentialId`, This might be involuntary as `google_meet_video` should ideally connect to the `newGoogleMeetCredentialId` instead of `newGoogleCalCredentialId`.

Good notice!. This is intentional, google_video being a special case and that's why this test case was added.
Please refer this https://github.com/calcom/cal.com/blob/7d51741de0f3b5fc286ca9c1aac1da47ea66a689/packages/features/bookings/lib/handleNewBooking.ts#L1130

here the credential of googleCal is only mapped to `google_meet_video` as well, while creating the bookingReferences for new booking.
As per the generic app installation flow, credential record for `google_video` will be created, but the keys will be empty, `google_calendar` 's credential is only used for google video as well.

2024-10-27 08:48 UTC, Praashh commented
> > I did notice, In the second test case you are using the `newGoogleCalCredentialId`, This might be involuntary as `google_meet_video` should ideally connect to the `newGoogleMeetCredentialId` instead of `newGoogleCalCredentialId`.
> 
> Good notice!. This is intentional, google_video being a special case and that's why this test case was added. Please refer this
> 
> https://github.com/calcom/cal.com/blob/7d51741de0f3b5fc286ca9c1aac1da47ea66a689/packages/features/bookings/lib/handleNewBooking.ts#L1130
> 
> here the credential of googleCal is mapped to `google_meet_video` as well, while creating the bookingReferences for new booking. As per the generic app installation flow, credential record for `google_video` will be created, but the keys will be empty, `google_calendar` 's credential is only used for google video as well.

ahh got it, I need a final check, I'll let you know..

2024-10-28 11:07 UTC, Praashh approved these changes
tested the changes locally, looks good to me.

2024-10-28 15:04 UTC, keithwillcode requested changes
Just blocking this from merge until @joeauyeung can take a look

2024-11-07 13:00 UTC, keithwillcode commented
This may have been taken care of by @hbjORbj in #17443

2024-11-07 13:59 UTC, vijayraghav-io commented
No, this https://github.com/calcom/cal.com/pull/17443 is not reconnecting booking references, which is the purpose of this current PR

2025-06-28 07:55 UTC, Devanshusharma2005 commented
Hey @vijayraghav-io this pr has been drafted and inactive since a very long time and also facing merge conflicts. Closing it for now. Feel free for a reopen.

2025-06-28 07:55 UTC, closed without merging