fix: Resolve lint errors by updating RerouteDialog.test.tsx
calcom/cal.com pull request #17352
Opened 2024-10-27 06:17 UTC by mavishay

## What does this PR do?

Another step of fixing build by fixing pre-running lint errors
![image](https://github.com/user-attachments/assets/45de914b-3dbf-402f-b469-c98a92beddc7)

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] I didn't updated the developer docs.
- [x] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

- Install dependencies by running `yarn`
- Running `yarn --cwd apps/web workspace @calcom/web run build` and see the error disappear

2024-10-27 06:17 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/calcom/cal.com?pullRequest=17352) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/calcom/cal.com?pullRequest=17352) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/calcom/cal.com?pullRequest=17352) it.</sub>

2024-10-27 17:10 UTC, Praashh requested changes, later dismissed
can you remove this, don't think we need async function here.

2024-10-28 17:17 UTC, anikdhabal commented on apps/web/components/dialog/__tests__/RerouteDialog.test.tsx
>  }
Hey @Praashh I think it's okay, as it's just fixing the lint error

2024-10-28 17:18 UTC, anikdhabal approved these changes

2024-10-28 17:19 UTC, merged

2024-10-28 18:40 UTC, Praashh commented on apps/web/components/dialog/__tests__/RerouteDialog.test.tsx
>  }
sure