feat: preview Taurify for desktop
calcom/cal.com pull request #17366
Opened 2024-10-28 14:39 UTC by lucasfernog-crabnebula

This pull request introduces [taurify](https://crabnebula.dev/taurify/), a service for developing and distributing desktop and mobile apps using a Web frontend. It can be seen as a ToDesktop alternative.

To try this out, run `npx taurify dev` in the `apps/web` directory.

This initial demonstration includes a tray icon populated with upcoming events and the `cal://` deep link, though it is capable of much more. We will share documentation soon.

2024-10-28 14:39 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/calcom/cal.com?pullRequest=17366) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/calcom/cal.com?pullRequest=17366) before we can accept your contribution.<br/>**0** out of **3** committers have signed the CLA.<br/><br/>:x: lucasfernog<br/>:x: lucasfernog-crabnebula<br/>:x: atilafassina<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/calcom/cal.com?pullRequest=17366) it.</sub>

2024-10-28 16:49 UTC, Praashh commented
hey @lucasfernog-crabnebula, can you please sign CLA ?

2024-10-28 20:04 UTC, lucasfernog-crabnebula commented
already signed :) now we need @atilafassina

2024-10-28 20:07 UTC, atilafassina commented
> already signed :) now we need @atilafassina

Signed!!! 🎉🔥

2024-10-29 10:38 UTC, PeerRich commented
can you make a loom video?

2024-10-30 16:38 UTC, lucasfernog-crabnebula commented
my dev environment is super slow (i'm not sure if that's expected) but here is a quick demo https://drive.google.com/file/d/1SK_BpRsaGtq__Qo_s32riQ5ZiWxg-hm6/view?usp=sharing

2024-11-20 17:29 UTC, Praashh requested changes, later dismissed
hey @lucasfernog-crabnebula  please fix, yarn.lock changes

2024-12-02 22:44 UTC, lucasfernog-crabnebula commented
hey guys I just got back from vacation and fixed some conflicts. Let me know if you have any questions.

2024-12-02 22:47 UTC, lucasfernog-crabnebula commented on apps/web/modules/bookings/views/bookings-listing-view.tsx
> -        ...filterQuery,
oops looks like an invalid change, just removed it

2024-12-11 16:11 UTC, eunjae-lee commented
> hey guys I just got back from vacation and fixed some conflicts. Let me know if you have any questions.

Hey @lucasfernog-crabnebula I tried to run it locally. After the login page, it's blank. Am I doing something wrong?

```
(cd apps/web && npx taurify dev)
```

![Screenshot 2024-12-11 at 17 10 29](https://github.com/user-attachments/assets/cf8c2acd-7115-44f9-946d-e609bd20169f)

![Screenshot 2024-12-11 at 17 08 13](https://github.com/user-attachments/assets/9bad471d-eaa5-4dd7-9b41-d6224c578d93)


I don't know the scope of this PR, but I've found the app icon a bit bigger and blury:

![image](https://github.com/user-attachments/assets/ed0cc815-b950-4fef-84a4-b4cbdbc88418)

2024-12-17 10:39 UTC, lucasfernog-crabnebula commented
@eunjae-lee you can try opening the inspector to see what is the problem by either right clicking in the app window or by pressing `Command + Option + I`, looks like the frontend crashed somewhere.

I'll see what I can do about the app icon.

2024-12-17 16:32 UTC, lucasfernog-crabnebula commented
I've fixed the blurry macOS icon (it was only a development mode issue), should be good now. Let me know if you can find any errors in the console.

2025-01-08 12:52 UTC, lucasfernog-crabnebula commented
> > I've fixed the blurry macOS icon (it was only a development mode issue), should be good now. Let me know if you can find any errors in the console.
> 
> Hi @lucasfernog-crabnebula sorry for the late response.
> 
> Here's what i've got:
> 
>  Screenshot.2025-01-07.at.16.29.26.mp4

looks like the login isn't redirecting to `localhost:3000/event-types` and `window.location.href` is probably `about:blank` (or the app is failing to load somehow? that is weird). I also don't see all those CORS issues you have. Which macOS version are you using?

![image](https://github.com/user-attachments/assets/824a3100-d316-4e49-9ec4-10bbec45392b)

![image](https://github.com/user-attachments/assets/92614853-63b2-402a-8835-8534fc7fd8ec)

2025-02-11 06:44 UTC, TusharBhatt1 commented
@lucasfernog-crabnebula are you still working on it , are the issues fix (if any) ?

2025-02-12 09:32 UTC, eunjae-lee commented
> I did not make any new change after the discussion about the macOS issue - I think it would be valuable to get feedback from other macOS users

Thanks for waiting. I was occupied with other tasks. You gave me a hint, and it was because I enabled "Organizations" in my local .env file, by having

```
ORGANIZATIONS_ENABLED=1
```

and

```
NEXT_PUBLIC_WEBAPP_URL='http://app.cal.local:3000'
```

After resetting them, now it works.

2025-02-15 17:47 UTC, lucasfernog-crabnebula commented
what else can I do here to move this further?

2025-05-01 16:45 UTC, PeerRich submitted a review, later dismissed
apologies for they delay

i’m taking this with high priority now

2025-05-01 18:03 UTC, PeerRich approved these changes, later dismissed

2025-05-01 18:50 UTC, PeerRich commented
@lucasfernog-crabnebula checks failing


![CleanShot 2025-05-01 at 19 49 51@2x](https://github.com/user-attachments/assets/08b3186d-7333-482b-927d-a2217f431921)

2025-05-13 05:00 UTC, retrogtx commented
some failing check!

2025-06-30 04:10 UTC, Devanshusharma2005 commented
@lucasfernog-crabnebula thanks for the pr, some merge conflicts are still there. Due to inactivity for a long time , closing this pr for now . Feel free to reopen it if you want to continue your work on it.

2025-07-18 15:11 UTC, closed without merging