feat: Change 'add override' to 'save override'
calcom/cal.com pull request #17434
Opened 2024-11-01 15:28 UTC by Amit91848

## What does this PR do?

- Fixes #17424  
- Fixes CAL-4654 

[Screencast from 2024-11-01 20-54-22.webm](https://github.com/user-attachments/assets/002c204a-6bde-40fc-932b-36257e14f74a)

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox.
- [x] I confirm automated tests are in place that prove my fix is effective or that my feature works.

2024-11-01 15:30 UTC, Amit91848 commented on packages/features/schedules/components/DateOverrideList.tsx
> +                  handleAvailabilityUpdate();
Automatically save in case of deleting an override as well. Not sure if this is needed or not, lmk if this needs to be removed

2024-11-01 15:41 UTC, anikdhabal submitted a review, later dismissed
Fix the type error

2024-11-04 11:29 UTC, Amit91848 commented on packages/features/timezone-buddy/components/AvailabilityEditSheet.tsx
> -      props.onOpenChange(false);
Removed this because on every auto save the sheet was getting closed

2024-11-19 21:42 UTC, Praashh requested changes
all good but we should have locale in languages for `Save Override` and `Update Override`.
<img width="754" alt="Screenshot 2024-11-20 at 3 13 25 AM" src="https://github.com/user-attachments/assets/ad4c410a-4c4a-42d3-9594-1a862a2a4a79">

2024-11-21 21:32 UTC, zomars submitted a review, later dismissed
Left some feedback 🙏

2024-11-23 14:54 UTC, Amit91848 commented
> all good but we should have locale in all languages for `Save Override` and `Update Override`. <img alt="Screenshot 2024-11-20 at 3 13 25 AM" width="754" src="https://private-user-images.githubusercontent.com/99237795/387845160-ad4c410a-4c4a-42d3-9594-1a862a2a4a79.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzNzM4MjAsIm5iZiI6MTczMjM3MzUyMCwicGF0aCI6Ii85OTIzNzc5NS8zODc4NDUxNjAtYWQ0YzQxMGEtNGM0YS00MmQzLTk1OTQtMWE4NjJhMmE0YTc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIzVDE0NTIwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiNzQ4ZjAyMjlmNTM3ZmYxYjUzY2QzODVhYjg2YzVlZWQxNzA0ZWNlNDEyMjhlZWFmOTNmODRiMDY5NGI0ZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.TPunJbuCVqElCE2f4tP43acmKAWGlBMrtgQ9P_Yp8Ko">
> 
> ### expected:
> <img alt="Screenshot 2024-11-20 at 10 55 25 AM" width="762" src="https://private-user-images.githubusercontent.com/99237795/387949585-432465f5-772c-43ae-8889-503ff6b58fd2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzNzM4MjAsIm5iZiI6MTczMjM3MzUyMCwicGF0aCI6Ii85OTIzNzc5NS8zODc5NDk1ODUtNDMyNDY1ZjUtNzcyYy00M2FlLTg4ODktNTAzZmY2YjU4ZmQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIzVDE0NTIwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1MWZjOGQ3NDRjMmZhYjJjMGQ0OWQxMTNlMDdhM2UzNjFhODA2YWE0NmZkMDcyNjk3MzJlZTVkNTU4ZDljN2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8MtVJQWBDJztPCspx5Ivwmw0iXYVLR8ukVzW7fsoMoI">

Wouldn't this be handled by replexica bot @Praashh ?
Also I see you handled noop, thanks for that

2024-11-23 14:59 UTC, Praashh commented
> > all good but we should have locale in all languages for `Save Override` and `Update Override`. <img alt="Screenshot 2024-11-20 at 3 13 25 AM" width="754" src="https://private-user-images.githubusercontent.com/99237795/387845160-ad4c410a-4c4a-42d3-9594-1a862a2a4a79.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzNzM4MjAsIm5iZiI6MTczMjM3MzUyMCwicGF0aCI6Ii85OTIzNzc5NS8zODc4NDUxNjAtYWQ0YzQxMGEtNGM0YS00MmQzLTk1OTQtMWE4NjJhMmE0YTc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIzVDE0NTIwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiNzQ4ZjAyMjlmNTM3ZmYxYjUzY2QzODVhYjg2YzVlZWQxNzA0ZWNlNDEyMjhlZWFmOTNmODRiMDY5NGI0ZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.TPunJbuCVqElCE2f4tP43acmKAWGlBMrtgQ9P_Yp8Ko">
> > ### expected:
> > <img alt="Screenshot 2024-11-20 at 10 55 25 AM" width="762" src="https://private-user-images.githubusercontent.com/99237795/387949585-432465f5-772c-43ae-8889-503ff6b58fd2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzNzM4MjAsIm5iZiI6MTczMjM3MzUyMCwicGF0aCI6Ii85OTIzNzc5NS8zODc5NDk1ODUtNDMyNDY1ZjUtNzcyYy00M2FlLTg4ODktNTAzZmY2YjU4ZmQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIzVDE0NTIwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1MWZjOGQ3NDRjMmZhYjJjMGQ0OWQxMTNlMDdhM2UzNjFhODA2YWE0NmZkMDcyNjk3MzJlZTVkNTU4ZDljN2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8MtVJQWBDJztPCspx5Ivwmw0iXYVLR8ukVzW7fsoMoI">
> 
> Wouldn't this be handled by replexica bot @Praashh ? Also I see you handled noop, thanks for that
<img width="587" alt="Screenshot 2024-11-23 at 8 29 25 PM" src="https://github.com/user-attachments/assets/29c69c3e-4297-4e72-97c1-bb33a4877ca6">

sorry @Amit91848 but cant see SS you sent.

2024-11-23 15:02 UTC, Praashh commented
alrighty, it's working now for all the langs, thank you @Amit91848 approving it.

2024-11-23 15:02 UTC, Praashh approved these changes

2024-12-11 21:20 UTC, merged