chore: add sentry performance tracking api-v2
calcom/cal.com pull request #17519
Opened 2024-11-06 18:14 UTC by ThyMinimalDev

## What does this PR do?

Adding performance tracking of endpoints with sentry on api v2

## Mandatory Tasks (DO NOT REMOVE)

- [ ] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [ ] N/A-  I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox.
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works.

2024-11-06 21:38 UTC, keithwillcode approved these changes
We should probably make configurable at some point

2024-11-06 22:31 UTC, keithwillcode requested changes
API v2 build is failing

2024-11-07 09:42 UTC, ThyMinimalDev commented
> API v2 build is failing

resolved

2024-11-07 10:02 UTC, supalarry approved these changes

2024-11-07 12:37 UTC, keithwillcode approved these changes

2024-11-07 12:38 UTC, merged