fix: Routing Form - Small Improvements
calcom/cal.com pull request #17538
Opened 2024-11-07 12:17 UTC by hariombalhara

## What does this PR do?

- Fix title. On switching the tab the title was reset to 'Cal.com|cal.com' causing confusion as to which tab had the Routing Form.
- Make route name editable. Give a meaningful name to your route that makes it easier to explain to others as well for the purpose of route.
- Make route collapsible - Helps in easy rearranging of Routes and focussing on a single route only
[Loom ](https://www.loom.com/share/0b3af8e19de74d8ca38b01eb990bb272)

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [N/A] I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox.
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works.

2024-11-07 14:08 UTC, Udit-takkar requested changes, later dismissed
build is failing because of missing "use client"

2024-11-08 13:13 UTC, Udit-takkar approved these changes, later dismissed

2024-11-11 04:47 UTC, hariombalhara commented
@Udit-takkar Icons test was failing. Updated the snapshot. Need a re-approval after tests pass.

2024-11-11 08:44 UTC, Udit-takkar approved these changes

2024-11-11 08:44 UTC, merged