feat: Delete attribute modal
calcom/cal.com pull request #17557
Opened 2024-11-08 14:42 UTC by Amit91848

## What does this PR do?

- Fixes #17543 
- Fixes CAL-4687

https://github.com/user-attachments/assets/70416a94-2118-4672-b408-7ae6a0d59b97

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox.
- [x] I confirm automated tests are in place that prove my fix is effective or that my feature works.

2024-11-08 15:14 UTC, anikdhabal commented on packages/features/ee/organizations/pages/components/DeleteAttributeModal.tsx
> +  setAttributeToDelete,
Let's move this inside /attributes

2024-11-08 16:04 UTC, Praashh requested changes
hey @Amit91848 , can you move the `modal` to `attributes` folder

2024-11-09 06:24 UTC, Amit91848 commented
> hey @Amit91848 , can you move the `modal` to `attributes` folder

Done

2024-11-11 08:14 UTC, sean-brydon approved these changes
LGTM! Thanks for tackling this.

2024-11-11 08:15 UTC, Praashh approved these changes

2024-11-11 08:33 UTC, merged