fix: hydration error in [org-slug]/[team-slug], [org-slug]/[team-slug]/[type] pages
calcom/cal.com pull request #17576
Opened 2024-11-11 08:41 UTC by vijayraghav-io

## What does this PR do?

- Fixes #17575
- Fixes CAL-XXXX (Linear issue number - should be visible at the bottom of the GitHub issue description)

fixes hydration error due to nested <a> anchor elements.

Before Fix / Issue :
https://www.loom.com/share/20d314a3952c47a4a53b252a5eb79edc?sid=a145ef5f-d97a-4d34-8cc7-882e8a91b05c

After Fix :
https://www.loom.com/share/c72b274adc8441c498d2a8165dc478db?sid=bcc7d554-328b-4bb0-adcd-76e2ff626dd9

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] - N/A -I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox.
- [x] I confirm automated tests are in place that prove my fix is effective or that my feature works.

2024-11-11 09:37 UTC, vijayraghav-io commented
Ready for review!

2024-11-19 15:05 UTC, Praashh commented
Hey @vijayraghav-io can you please attach a loom video of the fix.

2024-11-21 18:41 UTC, Praashh reviewed
LGTM!, tagging @anikdhabal for a final review before approving.

2024-12-06 13:22 UTC, vijayraghav-io commented
Gentle Reminder!

2024-12-30 08:30 UTC, vijayraghav-io commented
Gentle Reminder! for review

2025-02-19 14:09 UTC, hbjORbj requested changes
I feel that this PR introduces changes that outweigh the benefit of removing hydration error. Can you please revise it so that we don't add such a lot of changes? We wanna play it safe

2025-02-20 07:43 UTC, vijayraghav-io commented on apps/web/modules/team/team-view.tsx
> +              router.push(url);
This is the only key change done in this block compared to existing code.
Instead of having <Link , onClick() event on `li` is used to set the router.
As <Link inside <li is causing hydration error.

2025-02-20 07:51 UTC, vijayraghav-io commented on apps/web/modules/team/team-view.tsx
> +  const queryString = new URLSearchParams(flattenedQueryParams).toString();
This is just constructing the queryString to append in the url.

<Link accepts the query parameters in [key,value] pair format, where the value can be string or an array of string. So flattening was not required. <Link handles this internally.

But now since url with query params has to constructed manually, hence this reduce function to flatten.

For Example:
const queryParamsToForward = {
  filter: ["active", "pending"],
  page: "2",
  sort: "name",
};

is converted to 
queryString = "filter=active,pending&page=2&sort=name"

2025-07-14 17:11 UTC, kart1ka commented
Hey @vijayraghav-io, can you pls resolve merge conflicts? A test seems to be failing. Can you pls address that as well?

2025-07-14 17:15 UTC, kart1ka requested changes

2025-07-14 17:15 UTC, kart1ka commented on apps/web/playwright/organization/organization-team-page.e2e.ts
> +});
This test seems to be flaky. Can you check?

2025-07-15 03:59 UTC, vijayraghav-io commented
> Hey @vijayraghav-io, can you pls resolve merge conflicts? A test seems to be failing. Can you pls address that as well?

Sure will check and update

2025-07-16 08:49 UTC, vijayraghav-io commented
@coderabbitai review

2025-07-28 17:18 UTC, vijayraghav-io commented on apps/web/playwright/organization/organization-team-page.e2e.ts
> +});
removed the hardcoded `orgRequestedSlug` , may be the requested slug `example` was trying to override an existing org slug and was causing flakiness. 
So made the org slug dynamic (which is by default).

2025-07-28 17:21 UTC, vijayraghav-io commented
> Hey @vijayraghav-io, can you pls resolve merge conflicts? A test seems to be failing. Can you pls address that as well?

@kart1ka  All tests are passing now. The flaky failing test was a unrelated one.
Also removed the flakiness in new test in this PR.

2025-07-30 04:37 UTC, kart1ka approved these changes
LGTM

2025-08-28 12:27 UTC, hbjORbj commented
@vijayraghav-io Hey, I apologize for a late response and thanks for opening this PR. I agree that we have a hydration error due to nested anchor elements in the team page. The following is my analysis:

`UserAvatarGroup` computes hrefs on render using `getBookerBaseUrlSync(user.profile?.organization?.slug)`.
->
That calls getOrgFullOrigin, which depends on env-derived constants like WEBAPP_URL/WEBSITE_URL
->
Hence, the server-rendered <a href="..."> values differ from the client-rendered ones during hydration.

So, this issue must be addressed from the component `UserAvatarGroup` itself, not from team-view. I will address this myself in a separate PR.

2025-08-28 12:27 UTC, closed without merging