Feat: exclude emails and domains
calcom/cal.com pull request #17591
Opened 2024-11-12 04:30 UTC by VK-RED

## What does this PR do?

Added support for excluding emails and domains option in booking forms

- Fixes #17580 
- Fixes CAL-4697

/claim #17580 

[Screencast from 2024-11-12 09-33-33.webm](https://github.com/user-attachments/assets/3d1d55e8-812d-4f9c-9fd8-d25a723ab2e2)

## Mandatory Tasks (DO NOT REMOVE)

- [ ] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [ ] I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox.
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works.

2024-11-12 04:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/calcom/cal.com?pullRequest=17591) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/calcom/cal.com?pullRequest=17591) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/calcom/cal.com?pullRequest=17591) it.</sub>

2024-11-12 17:29 UTC, emrysal commented
Thinking about the wording here: It's not a feature that blocks the work email, it's any email that matches a given pattern. So "please try a work email" is not great here, better would be something like "Unfortunately, some email domains are not permitted. If your email was declined, please try a different email address."

2024-11-12 17:44 UTC, emrysal requested changes, later dismissed
We need some validation on the inputField to ensure the domains entered are valid and that the comma separated value is correct. @hariombalhara I also think the schema itself is very specific in this situation, maybe a more generic feature like excludedPattern is better - would like to know your opinion.

2024-11-12 18:57 UTC, Praashh requested changes, later dismissed
Can you please add lowercase checks to handle emails and domains?

2024-11-13 08:37 UTC, VK-RED commented
Updating the changes

2024-11-13 11:19 UTC, PeerRich commented
> Thinking about the wording here: It's not a feature that blocks the work email, it's any email that matches a given pattern. So "please try a work email" is not great here, better would be something like "Unfortunately, the email domain [domain].com is not permitted. Please try a different email address."

this requirement came from me and we should keep it this way for now.

Please move forward with "Please try a work email"

2024-11-13 11:20 UTC, PeerRich commented on apps/web/public/static/locales/en/common.json
> +  "exclude_emails_match_found_error_message" : "Unfortunately, the email domain is not permitted. Please try a different email address.",
```suggestion
  "exclude_emails_match_found_error_message" : "Please enter a valid work email address",
```

2024-11-13 11:21 UTC, PeerRich commented on apps/web/public/static/locales/en/common.json
> +  "exclude_emails_match_found_error_message" : "Please enter a valid work email address",
this feature is primarily to throw this error: 
<img width="279" alt="image" src="https://github.com/user-attachments/assets/b6d018f9-04a8-496d-88d7-593404720942">

2024-11-13 12:03 UTC, VK-RED commented
Added domain validation 

[Screencast from 2024-11-13 17-26-41.webm](https://github.com/user-attachments/assets/1131a583-e0a2-4ba7-8896-e9421513bd2b)

2024-11-13 16:26 UTC, Praashh commented
Hey @VK-RED, thank you so much for your contributions, for now, we are going with the other one.

2024-11-13 16:26 UTC, Praashh commented
Hey @VK-RED, thank you so much for your contributions, for now, we are going with the other one.

2024-11-14 08:35 UTC, Praashh requested changes
we need the correct version of the error for validation
### Current 
![image](https://github.com/user-attachments/assets/0e56be06-fda3-4e5c-87ce-e6712396107f)
### Expected 
![image](https://github.com/user-attachments/assets/1e82e0cd-393a-45a5-a41b-f16e387fc83d)

2024-11-14 10:06 UTC, VK-RED commented
Hi @Praashh Everything seems to working fine for me. 

[Screencast from 2024-11-14 15-34-14.webm](https://github.com/user-attachments/assets/276bbf7a-d990-447c-bb00-3d2c9f40af28)

2024-11-14 12:35 UTC, Praashh commented on packages/features/form-builder/FormBuilder.tsx
> +                    {/* render only for primary email field */}
please remove this.

2024-11-14 12:42 UTC, Praashh reviewed
Overall, it looks good to me. Please make the changes mentioned above, and I'll approve.

2024-11-14 12:49 UTC, VK-RED commented
Hi @Praashh updated the changes

2024-11-14 12:53 UTC, Praashh commented
> Hi @Praashh updated the changes

we also need unit test to verify this functionality, can you please add ?

2024-11-14 13:06 UTC, VK-RED commented
Sure will add it !

2024-11-15 08:25 UTC, VK-RED commented
Hi @Praashh added the tests

2024-11-15 10:16 UTC, Praashh approved these changes
LGTM!! thank you @VK-RED .

2024-11-15 10:46 UTC, merged