fix: change order of eventtypes and routingforms
calcom/cal.com pull request #17615
Opened 2024-11-13 10:46 UTC by vijayraghav-io

## What does this PR do?

- Fixes #17614 
- Fixes CAL-4568

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [ ] I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox.
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works.

2024-11-13 12:10 UTC, Praashh approved these changes, later dismissed
LGTM!!

2024-11-13 12:12 UTC, vijayraghav-io commented
@PeerRich , updated for eventTypes, routingForms, workflows. 
Bookings already have sort as per the tab.
https://github.com/calcom/cal.com/blob/1aac70f643835960963907d3c48d01ccec9b653c/packages/lib/bookings/getAllUserBookings.ts#L110-L114

As of now, I couldn't find anything more to be included.
Please let know if any more entities to be included.

2024-11-13 13:14 UTC, vijayraghav-io commented
@Praashh , all tests are passing

2024-11-13 13:56 UTC, Praashh commented
> @Praashh , all tests are passing. you can approve again

let me give it a final touch.

2024-11-13 16:16 UTC, Praashh approved these changes, later dismissed
LGTM!! thank you so much @vijayraghav-io

2024-11-13 16:49 UTC, keithwillcode requested changes
@vijayraghav-io @Praashh Just double-checking we are sure there aren't pieces of code that depend on the sort order for some reason?

(Marking requested changes just to block merging first)

2024-11-13 17:30 UTC, vijayraghav-io commented
> @vijayraghav-io @Praashh Just double-checking we are sure there aren't pieces of code that depend on the sort order for some reason?

Hi @keithwillcode , double checked again that - the sole purpose of these updated (sort order) functions is to ultimately render the lists <li in UI . Verified that these functions are not called anywhere else.
Also there is no dependency on sort order in the UI for these entities.

2024-11-13 17:37 UTC, keithwillcode commented
> > @vijayraghav-io @Praashh Just double-checking we are sure there aren't pieces of code that depend on the sort order for some reason?
> 
> Hi @keithwillcode , double checked again that - the sole purpose of these updated (sort order) functions is to ultimately render the lists <li in UI through trpc handlers/endpoints. Verified that these functions have no references or are not called anywhere else. Also there is no dependency on sort order in the UI for these entities.

Great. Thanks, @vijayraghav-io

2024-11-13 17:37 UTC, keithwillcode submitted a review, later dismissed

2024-11-14 01:27 UTC, vijayraghav-io commented
Thank you! @keithwillcode 🙏

2024-11-17 12:23 UTC, vijayraghav-io commented
Just guessing, If retaining the same look and feel w.r.t order of default event-types for new/future onboarding customers is a concern, then the order can be updated here (or the array can be reversed) -
https://github.com/calcom/cal.com/blob/f9afca2939a72922bfb39c1b00d242c6a37c4136/apps/web/components/getting-started/steps-views/UserProfile.tsx#L81-L98

2024-11-21 05:16 UTC, vijayraghav-io commented
updated due to changes after https://github.com/calcom/cal.com/pull/17689 was merged

2024-11-21 06:21 UTC, vijayraghav-io commented
Added a new test - to ensure new eventType added will be first in the list

2024-11-23 07:14 UTC, Praashh commented on apps/web/playwright/embed-code-generator.e2e.ts
I think it's out of the scope of this PR.

2024-11-23 07:15 UTC, Praashh requested changes
We also need a test case for the routing form.

2024-11-23 11:23 UTC, vijayraghav-io commented on apps/web/playwright/embed-code-generator.e2e.ts
the changes here is required.
As the eventTypes order in the list is changed, hence the first expected eventType needs update in these tests, else these tests will fail.

2024-11-23 13:08 UTC, Praashh approved these changes
Great Work @vijayraghav-io sir, LGTM!!!

2024-11-25 09:25 UTC, merged