feat: improve text filters
calcom/cal.com pull request #17632
Opened 2024-11-14 09:06 UTC by eunjae-lee

## What does this PR do?

- Fixes #XXXX (GitHub issue number)
- Fixes CAL-XXXX (Linear issue number - should be visible at the bottom of the GitHub issue description)

## Mandatory Tasks (DO NOT REMOVE)

- [ ] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [ ] I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox.
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

- Are there environment variables that should be set?
- What are the minimal test data to have?
- What is expected (happy path) to have (input and output)?
- Any other important info that could help to test that PR

## Checklist

- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my changes generate no new warnings

2024-11-14 17:21 UTC, eunjae-lee commented on packages/features/users/components/UserTable/UserListTable.tsx
> +  }, [filtersSearchState.activeFilters]);
We already have `?activeFilters=` on the search state (URL), but kept `columnFilters` separately from `onColumnFilterChange` below. I think it's unnecessary to keep two sources, so I've made `columnFilters` out of `useFiltersSearchState()`.

2024-11-14 17:21 UTC, eunjae-lee commented on packages/ui/components/data-table/DataTableFilter.tsx
It seems this file is not being in use.

2024-11-14 17:21 UTC, eunjae-lee commented on packages/ui/components/data-table/filters/utils.ts
> +export const textFilter = (cellValue: string, filterValue: TextFilterValue) => {
This function is used with tanstack table to filter the existing rows on the client side.

2024-11-14 17:21 UTC, eunjae-lee commented on packages/ui/components/data-table/filters/utils.ts
> +export function makeWhereClause(columnName: string, filterValue: FilterValue) {
This is a utility function for prisma for the backend to build proper where clause.

2024-11-15 09:46 UTC, eunjae-lee commented on packages/features/users/components/UserTable/UserListTable.tsx
> +  const columnFilters = useColumnFilters();
We already have `?activeFilters=` on the search state (URL), but kept `columnFilters` separately with `onColumnFilterChange` below. I think it's unnecessary to keep two sources, so I've made `columnFilters` out of `useFiltersSearchState()`.

2024-11-15 09:59 UTC, eunjae-lee commented on packages/ui/components/data-table/filters/MultiSelectFilterOptions.tsx
> +  return (
This part is extracted from `packages/ui/components/data-table/filters/index.tsx`. The markups are almost the same, but only `onSelect` has changed a bit.

2024-11-15 12:50 UTC, zomars commented
Hey @eunjae-lee from the demo is kinda hard to see but it seems like some filters are being applied without hitting the "apply" button. Are you hitting the Enter key? If not can we enforce consistency so we only apply them when hitting the button or the Enter key?

2024-11-15 13:05 UTC, eunjae-lee commented
> Hey @eunjae-lee from the demo is kinda hard to see but it seems like some filters are being applied without hitting the "apply" button. Are you hitting the Enter key? If not can we enforce consistency so we only apply them when hitting the button or the Enter key?

Oh the video wasn't clear. Yes, you're right. It's either enter key or hitting the button, because it's a button with type="submit"

2024-11-18 14:18 UTC, keithwillcode commented
@sean-brydon Can you take a look at this one, please?

2024-11-19 08:30 UTC, Udit-takkar commented on packages/trpc/server/routers/viewer/organizations/listMembers.handler.ts
> +              ...makeWhereClause("value", filter.value),
Filtering by text shouldn't be case sensitive

https://github.com/user-attachments/assets/9f833e55-d394-4e4f-8c90-385bef236923

2024-11-19 08:41 UTC, Udit-takkar commented on packages/ui/components/data-table/filters/TextFilterOptions.tsx
> +              Apply
NIT: use i18n

2024-11-19 10:37 UTC, sean-brydon requested changes, later dismissed
Tested all works well: 

However, i do believe @Udit-takkar's comment is blocking. We should not care about the case of the text on the text inputs. 

I also wonder if we should address the NIT to move the makeWhereQuery to elsewhere

2024-11-19 12:20 UTC, eunjae-lee commented
Moving the whole data table related files to /features. Some stuff is broken now but I will fix them after lunch.

2024-11-20 07:59 UTC, Udit-takkar reviewed
LGTM. 
There are some merge conflicts

2024-11-20 09:05 UTC, eunjae-lee commented
> LGTM. There are some merge conflicts

@Udit-takkar fixed :)

2024-11-20 09:15 UTC, Udit-takkar approved these changes

2024-11-20 09:38 UTC, merged