feat: refactor the pipedrive crm from revert to original pipedrive
calcom/cal.com pull request #17672
Opened 2024-11-15 20:24 UTC by rajesh-jonnalagadda

## What does this PR do?

- Fixes #16797 
- Fixes CAL-1679 (Linear issue number - should be visible at the bottom of the GitHub issue description)
/calim #16797 

## Mandatory Tasks (DO NOT REMOVE)

- [ ] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [ ] I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox.
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

- Are there environment variables that should be set?
- What are the minimal test data to have?
- What is expected (happy path) to have (input and output)?
- Any other important info that could help to test that PR

## Checklist

- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my changes generate no new warnings

2024-11-16 05:55 UTC, Praashh commented
Hey @rajesh-jonnalagadda , can you attach a loom for your solution?

2024-11-16 07:33 UTC, rajesh-jonnalagadda commented
> Hey @rajesh-jonnalagadda , can you attach a loom for your solution?

Ack

2024-11-16 07:41 UTC, rajesh-jonnalagadda commented
@Praashh added the demo. please check

2024-11-16 08:01 UTC, rajesh-jonnalagadda commented
@itsalam both pr seems redundant and mostly similar.  Can we pick one pr and collaborate and split accordingly
Cc: @Praashh what do you think?

2024-11-16 08:29 UTC, itsalam commented
@rajesh-jonnalagadda,

I’m mainly interested in the experience and having the work on my GitHub. I’m happy to collaborate in a way that aligns with that and supports both our goals. I'm not particuarily interested with the reward.

2024-11-16 08:32 UTC, Praashh commented
> @itsalam both pr seems redundant and mostly similar. Can we pick one pr and collaborate and split accordingly Cc: @Praashh what do you think?

yea, will pick one PR and will close the another one after testing

2024-11-16 13:36 UTC, Praashh commented on packages/app-store/pipedrive-crm/api/_getAdd.ts
> +  //this need to be accessed by admin only. need to conform
```suggestion
  //this need to be accessed by admin only. need to confirm 
```

2024-11-16 13:39 UTC, Praashh commented on packages/app-store/pipedrive-crm/api/_postAdd.ts
> +  //this need to be accessed by admin only. need to conform
```suggestion
  //this need to be accessed by admin only. need to confirm
```

2024-11-16 13:40 UTC, Praashh commented on packages/app-store/pipedrive-crm/api/_postAdd.ts
> +    //making sure only one record is maintianed
```suggestion
    //making sure only one record is maintained.
```

2024-11-16 15:53 UTC, Praashh commented on packages/app-store/pipedrive-crm/api/_postAdd.ts
> +  } as any;
```suggestion
const data: Prisma.AppCreateInput = {
    slug: appConfig.slug,
    keys: { client_id, client_secret },
    enabled: true,
    categories: appConfig["categories"] as unknown as 
    Prisma.AppCreatecategoriesInput | undefined,
    dirName: appConfig["dirName"],
  };
```
it's better to use proper type instead any.

2024-11-16 15:54 UTC, Praashh commented on packages/app-store/pipedrive-crm/api/_postAdd.ts
> +  const { returnTo, ...newQeury } = req.query;
can we add a check for newQuery just to make sure it exists?

2024-11-16 16:17 UTC, Praashh commented on packages/app-store/pipedrive-crm/api/callback.ts
> +  const url = `https://oauth.pipedrive.com/oauth/token`;
```suggestion
  const URL = `https://oauth.pipedrive.com/oauth/token`;
```
let's move it to the top of the file.

2024-11-16 16:20 UTC, Praashh commented on packages/app-store/pipedrive-crm/api/callback.ts
> +    pipedriveCrmTokenInfo.data.accountServer = `https://oauth.pipedrive.com`;
instead of using direct url, we can use it as a variable

2024-11-16 16:22 UTC, Praashh commented on packages/app-store/pipedrive-crm/pages/setup/index.tsx
> +            {/* eslint-disable @next/next/no-img-element */}
remove this.

2024-11-16 16:24 UTC, Praashh reviewed
Overall LGTM!! Please make those small changes so I can approve it.

2024-11-16 19:01 UTC, rajesh-jonnalagadda commented
> Overall LGTM!! Please make those small changes so I can approve it.

updated the pr.  did some refactoring and added the permissions

2024-11-16 21:16 UTC, Praashh approved these changes, later dismissed
LGTM!!! thank you so much for your contribution.

2024-11-18 10:07 UTC, anikdhabal requested changes
How to handle users who have already installed this app and used it?

2024-11-18 10:55 UTC, rajesh-jonnalagadda commented
> How to handle users who have already installed this app and used it?

@anikdhabal 
That's a good point.

We could consider displaying an upgrade popup for all users who have previously installed the app. Since we can't access refresh tokens and access tokens directly without user consent, this approach seems to be the most feasible solution.

what do you suggest?

2024-11-18 17:35 UTC, Praashh commented
> > How to handle users who have already installed this app and used it?
> 
> @anikdhabal That's a good point.
> 
> We could consider displaying an upgrade popup for all users who have previously installed the app. Since we can't access refresh tokens and access tokens directly without user consent, this approach seems to be the most feasible solution.
> 
> what do you suggest?

yeah seems a good way to do.

2024-11-19 17:51 UTC, Praashh reviewed
Hey @rajesh-jonnalagadda, can you please attach a loom for a fix for a user who has already installed the app?

2024-11-21 03:45 UTC, rajesh-jonnalagadda commented
> Hey @rajesh-jonnalagadda, can you please attach a loom for a fix for a user who has already installed the app?

@Praashh Instead of a pop-up, we can display the upgrade option directly on the installed page. Please review the demo.
https://www.loom.com/share/030835f78e014f0bad9eeefffaecdba5

2024-11-21 08:41 UTC, Praashh requested changes
<img width="759" alt="Screenshot 2024-11-21 at 2 11 18 PM" src="https://github.com/user-attachments/assets/b446c605-87cb-4b99-a2cb-c4438a7a2d88">

it's not working for me for some reason, can you please check again @rajesh-jonnalagadda

2024-11-21 15:07 UTC, Praashh commented
> > <img alt="Screenshot 2024-11-21 at 2 11 18 PM" width="759" src="https://private-user-images.githubusercontent.com/99237795/388423640-b446c605-87cb-4b99-a2cb-c4438a7a2d88.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxNzg5NjgsIm5iZiI6MTczMjE3ODY2OCwicGF0aCI6Ii85OTIzNzc5NS8zODg0MjM2NDAtYjQ0NmM2MDUtODdjYi00Yjk5LWEyY2ItYzQ0MzhhN2EyZDg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIxVDA4NDQyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlYzhlNzI5YTYxZDBhN2FmZTczM2JkODdiYTRmYmVlMDlmMjQzZTVjMzJmZmVlZGYyOTc2YTMxYTcwZTVhYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.laAvAHhNxNuUnOQ7JZ8Rv0Lk6I6hkJKA_tlzn1UxJ_c">
> > it's not working for me for some reason, can you please check again @rajesh-jonnalagadda
> 
> ack

sir SS is not showing anything, but checking  🙏

2024-11-21 21:06 UTC, Praashh reviewed
LGTM!!! tagging @anikdhabal for the final touch.

2024-11-26 14:45 UTC, rajesh-jonnalagadda commented
@Praashh may i know the review status of this.

2024-11-26 15:14 UTC, Praashh commented
> @Praashh may i know the review status of this.

Changes seems good to me, @anikdhabal will give a final review.

2024-11-26 15:15 UTC, rajesh-jonnalagadda commented
> > @Praashh may i know the review status of this.
> 
> Changes seems good to me, @anikdhabal will give a final review.

@anikdhabal can you please review

2024-12-08 14:18 UTC, rajesh-jonnalagadda commented
@anikdhabal can I get feedback? it has been pending for a while

2024-12-11 06:33 UTC, Praashh requested changes
can you resolve merge conflicts @rajesh-jonnalagadda  🙏

2024-12-11 16:10 UTC, keithwillcode commented on packages/app-store/pipedrive-crm/README.md
> +#### Installing Pipedrive in cal.com
```suggestion
#### Installing Pipedrive in Cal.com
```

2025-01-08 16:02 UTC, Praashh requested changes
Unit Tests are failing, @rajesh-jonnalagadda can you please fix this 🙏

2025-01-11 07:26 UTC, rajesh-jonnalagadda commented
> Unit Tests are failing, @rajesh-jonnalagadda can you please fix this 🙏

@Praashh Apologies, I'm currently in the middle of a hackathon and won't be able to address this right now. Thank you for your understanding!

2025-02-18 11:22 UTC, anikdhabal commented
@rajesh-jonnalagadda could you pls fix the conflicts?

2025-03-03 07:54 UTC, anikdhabal commented on packages/app-store/_utils/getAppKeysFromSlug.ts
> +  const app = await prisma.app.findUnique({ where: where });
Why we made changes here?

2025-03-03 07:54 UTC, anikdhabal commented on packages/app-store/_utils/oauth/createOAuthAppCredential.ts
> +    update: baseData,
Same here

2025-03-03 07:54 UTC, anikdhabal commented on packages/app-store/pipedrive-crm/lib/CrmService.ts
> +  calendar_sync_include_context: string;
Isn't there are any way we can shorten it? Do we need all of this?

2025-03-18 14:04 UTC, anikdhabal commented
@rajesh-jonnalagadda pls fix the conflicts. Also few tests are failing

2025-04-14 08:32 UTC, retrogtx commented
stale

2025-04-14 08:32 UTC, retrogtx commented
@rajesh-jonnalagadda please feel free to re-open this, closing as its stale now.

2025-07-30 05:00 UTC, anikdhabal commented
@rajesh-jonnalagadda thanks for your work. But going with this one:- https://github.com/calcom/cal.com/pull/22492

2025-07-30 05:00 UTC, closed without merging