Implement JSON Schema Validation for User API Responses
calcom/cal.com pull request #17731
Opened 2024-11-19 02:42 UTC by AmpasTheodoros

Problem Solved: The Cal.com API v2 was exhibiting inconsistent behavior with response bodies changing unpredictably. This inconsistency was causing errors in applications relying on the API, leading to disruptions in functionality and user experience. The issue stemmed from a lack of a fixed and documented schema for API responses

Solution Implemented:

- Defined a JSON schema to establish a consistent structure for user-related API responses
- Integrated the Ajv library into the UsersService to validate responses against the schema
- Added validation logic in the getByUsernames method to ensure each user response adheres to the schema, throwing an error if it does not

Trade-offs or Limitations:

- The current implementation focuses on user-related responses. Extending schema validation to other modules may be necessary for comprehensive consistency
- Future changes to the API response structure will require updates to the schema and potentially the validation logic
- A versioning strategy and deprecation policy should be considered to manage future changes and maintain backward compatibility

2024-11-19 02:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/calcom/cal.com?pullRequest=17731) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/calcom/cal.com?pullRequest=17731) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/calcom/cal.com?pullRequest=17731) it.</sub>

2024-11-19 07:15 UTC, Praashh commented
Hey @AmpasTheodoros please sign CLA

2024-11-19 08:17 UTC, Praashh commented on apps/api/v2/src/modules/users/services/users.service.ts
> +        throw new Error("Invalid user response schema");
```suggestion
  throw new Error(`Invalid user response schema for user: ${user.username}`);
```

we can throw the error for the user.

2024-11-19 12:19 UTC, AmpasTheodoros commented
Hey @Praashh  thanks for fixing my title I just signed CLA

2024-11-21 16:17 UTC, Praashh approved these changes, later dismissed
LGTM!!

2024-12-03 16:54 UTC, keithwillcode requested changes
Looks like API v2 tests are failing. Can you please take a look?

2025-01-04 15:13 UTC, anikdhabal commented
Close due to inactivity

2025-01-04 15:13 UTC, closed without merging