fix: upgrade prismock to 1.33.4
calcom/cal.com pull request #17735
Opened 2024-11-19 08:55 UTC by vijayraghav-io

## What does this PR do?

- Fixes #17709 
- Fixes CAL-4747

## Summary of Changes
1. Upgraded prismock to 1.33.4
2. Removed 2 hacks - 
     1. bug in create and createMany expected to have data directly
     2. bug with using NOT in where clause
3. Updated 3 tests, due to changes in how Date fields are compared in prismock latest version

hack for complex where clauses is still required.

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] - N/A - I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox.
- [x] I confirm automated tests are in place that prove my fix is effective or that my feature works.

2024-11-19 13:23 UTC, keithwillcode requested changes

2024-11-19 13:23 UTC, keithwillcode commented on package.json
> +    "prismock": "^1.33.4",
No yarn.lock changes?

2024-11-19 22:25 UTC, keithwillcode approved these changes

2024-11-19 23:20 UTC, merged

2024-11-20 09:20 UTC, vijayraghav-io commented
Thank you! @keithwillcode 🙏