feat: Don't remove hosts when disabling 'Add all team members'
calcom/cal.com pull request #17747
Opened 2024-11-19 15:54 UTC by Amit91848

## What does this PR do?

- Fixes #17746 
- Fixes CAL-4759 

https://github.com/user-attachments/assets/3cda2b1c-5f94-4c32-9601-fa9088da17f9

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox.
- [x] I confirm automated tests are in place that prove my fix is effective or that my feature works.

2024-11-19 15:55 UTC, Amit91848 commented on packages/features/eventtypes/components/AssignAllTeamMembers.tsx
> -  onInactive?: () => void;
Remove this because it isn't being used anywhere. Can add it later if use case arises

2024-11-19 16:46 UTC, CarinaWolli requested changes
@hariombalhara brought up a good point that we should add a 'Remove all' button, could add that?

2024-11-19 16:50 UTC, CarinaWolli commented
> @hariombalhara brought up a good point that we should add a 'Remove all' button, could add that?

Nevermind, I think this is already doing that
<img width="950" alt="Screenshot 2024-11-19 at 11 49 37 AM" src="https://github.com/user-attachments/assets/683dcf9c-c30d-46b1-ba83-ab5902a5156c">

2024-11-19 17:18 UTC, CarinaWolli reviewed
Works great 🙌🏻  I saw that when you have hosts with set weights and priorities then it resets all priorities and weights when enabling the toggle. Could we fix this in this PR as well?

2024-11-20 12:34 UTC, Amit91848 commented on packages/features/eventtypes/components/HostEditDialogs.tsx
Found small bug with the dialog of priority and weights. If you change the value for a user and close and open the dialog for another user, you are shown the same value even if the second users value differ

Before


https://github.com/user-attachments/assets/48e133da-8507-4832-a35b-471570d5b493

After


https://github.com/user-attachments/assets/4d6a2b84-51ea-4005-9cd2-33abd8871910

2024-11-20 17:32 UTC, CarinaWolli approved these changes
Nice work, looks good now 🙏

2024-11-20 17:54 UTC, merged