fix: improve cancellation email of reschedule RR booking
calcom/cal.com pull request #17768
Opened 2024-11-20 19:27 UTC by kart1ka

## What does this PR do?

- Fixes #17253 (GitHub issue number)
- Fixes CAL-4585 (Linear issue number - should be visible at the bottom of the GitHub issue description)

[Screencast from 21-11-24 12:49:55 AM IST.webm](https://github.com/user-attachments/assets/dba3e896-ea1d-400a-8327-0a0125a5ae1d)

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox.
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works.

2024-11-21 05:41 UTC, Praashh requested changes
<img width="599" alt="Screenshot 2024-11-21 at 11 10 16 AM" src="https://github.com/user-attachments/assets/09e19fd0-70e9-4120-abc1-de927189ecc2">

Issue is still there, it's taking reschedule date not the old one in the mail.

2024-11-21 06:40 UTC, kart1ka commented
Hi @Praashh 
I have tested it again and it is working (see below screenshots). 
I can see in the screenshot you have attached that Reassigned to section is also not showing in the mail. Please make sure you are trying to reschedule Round Robin booking.

Screenshot of cancelled mail sent to the old host (after the  round robin booking has been rescheduled) with old date and reassigned to displayed 

![image](https://github.com/user-attachments/assets/4636b0a8-be23-409a-a7e1-3054cf4e11d3)

Screenshot of scheduled mail sent to the new host (after the  round robin booking has been rescheduled) with new date displayed 

![image](https://github.com/user-attachments/assets/e5fd3e42-c975-471e-a970-d1b432365c99)

2024-11-21 07:12 UTC, Praashh commented
> Hi @Praashh I have tested it again and it is working (see below screenshots). I can see in the screenshot you have attached that Reassigned to section is also not showing in the mail. Please make sure you are trying to reschedule Round Robin booking.
> 
> Screenshot of cancelled mail sent to the old host (after the round robin booking has been rescheduled) with old date and reassigned to displayed
> 
> ![image](https://private-user-images.githubusercontent.com/41051387/388384202-4636b0a8-be23-409a-a7e1-3054cf4e11d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxNzMyMzQsIm5iZiI6MTczMjE3MjkzNCwicGF0aCI6Ii80MTA1MTM4Ny8zODgzODQyMDItNDYzNmIwYTgtYmUyMy00MDlhLWE3ZTEtMzA1NGNmNGUxMWQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIxVDA3MDg1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3MDM5Y2E1MzVhYWFlYmY4NWE2YjdiMGI1NzA0MDEyM2E1MWM5YmJjZDhmYjdhYjhiMjc4YzgxZDMzYjVjOTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8fTrXRSAK0V9rQIhB1UlKI-_azEO-xUAxQTm9pqa1rg)
> 
> Screenshot of scheduled mail sent to the new host (after the round robin booking has been rescheduled) with new date displayed
> 
> ![image](https://private-user-images.githubusercontent.com/41051387/388384456-e5fd3e42-c975-471e-a970-d1b432365c99.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxNzMyMzQsIm5iZiI6MTczMjE3MjkzNCwicGF0aCI6Ii80MTA1MTM4Ny8zODgzODQ0NTYtZTVmZDNlNDItYzk3NS00NzFlLWE5NzAtZDFiNDMyMzY1Yzk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIxVDA3MDg1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViNjIxNWYzOWRmMzgxNTYwZDgyMTA3MmNhZDUyYzNmODk4NjM3ZGM4YTU5ZTNiOTc2M2FiYWQ2MmRkMzUyNmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.z5czpqLNJ_S_p9d0KdoZrSAwab51umow6-E5okjqUWg)

i rescheduled and cancel the meet, it was same.

2024-11-21 07:53 UTC, kart1ka commented
> > Hi @Praashh I have tested it again and it is working (see below screenshots). I can see in the screenshot you have attached that Reassigned to section is also not showing in the mail. Please make sure you are trying to reschedule Round Robin booking.
> > Screenshot of cancelled mail sent to the old host (after the round robin booking has been rescheduled) with old date and reassigned to displayed
> > ![image](https://private-user-images.githubusercontent.com/41051387/388384202-4636b0a8-be23-409a-a7e1-3054cf4e11d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxNzMyMzQsIm5iZiI6MTczMjE3MjkzNCwicGF0aCI6Ii80MTA1MTM4Ny8zODgzODQyMDItNDYzNmIwYTgtYmUyMy00MDlhLWE3ZTEtMzA1NGNmNGUxMWQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIxVDA3MDg1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3MDM5Y2E1MzVhYWFlYmY4NWE2YjdiMGI1NzA0MDEyM2E1MWM5YmJjZDhmYjdhYjhiMjc4YzgxZDMzYjVjOTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8fTrXRSAK0V9rQIhB1UlKI-_azEO-xUAxQTm9pqa1rg)
> > Screenshot of scheduled mail sent to the new host (after the round robin booking has been rescheduled) with new date displayed
> > ![image](https://private-user-images.githubusercontent.com/41051387/388384456-e5fd3e42-c975-471e-a970-d1b432365c99.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxNzMyMzQsIm5iZiI6MTczMjE3MjkzNCwicGF0aCI6Ii80MTA1MTM4Ny8zODgzODQ0NTYtZTVmZDNlNDItYzk3NS00NzFlLWE5NzAtZDFiNDMyMzY1Yzk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIxVDA3MDg1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViNjIxNWYzOWRmMzgxNTYwZDgyMTA3MmNhZDUyYzNmODk4NjM3ZGM4YTU5ZTNiOTc2M2FiYWQ2MmRkMzUyNmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.z5czpqLNJ_S_p9d0KdoZrSAwab51umow6-E5okjqUWg)
> 
> i rescheduled and cancel the meet, it was same but i'll check it again

Here are the steps that i am using to test my solution:

1.  Create a Round Robin Event and make sure that Reschedule with same Round-Robin host is toggled off in the Event Advanced Settings Tab.
2. Book the event.
3. Now reschedule the booking to a different date.
4. Check the mails and notice that the cancellation mail sent to the old round robin host shows old date and it also shows the details of the member the rescheduled booking has been reassigned to.

2024-11-21 10:08 UTC, kart1ka commented
While rescheduling a booking, all form fields are disabled except for Add Guests and Reason for Reschedule (see the screenshot below). Is the Add Guests field supposed to be enabled when rescheduling a booking? 
This is causing unexpected behaviour in some edge cases.


![image](https://github.com/user-attachments/assets/9a45a1b5-0ba3-4b4c-bcdd-6f56e50e36a5)

2024-11-21 19:49 UTC, Praashh submitted a review, later dismissed
LGTM!!

2024-11-22 15:16 UTC, kart1ka commented on packages/features/bookings/lib/handleNewBooking.ts
> +          ? freeUsers.find((user) => user.id === (currentRRHostId ?? originalRescheduledBookingUserId))
This fixes a bug related to rescheduling Round-Robin (RR) events. If a RR event had a fixed host and the "Reschedule with same Round-Robin host" option was enabled in the event settings, rescheduling a booking would exclude the original (non-fixed) host from the rescheduled booking and only the fixed host would be kept in the rescheduled booking. This fixes that issue. 


[Screencast from 22-11-24 08:25:32 PM IST.webm](https://github.com/user-attachments/assets/478614cc-e7de-44f3-9186-20586e40b007)

2024-12-12 14:03 UTC, Praashh submitted a review, later dismissed
@kart1ka can you please resolve merge conflicts 🙏

2024-12-12 16:58 UTC, kart1ka commented
> @kart1ka can you please resolve merge conflicts 🙏

Resolved merge conflicts.

2024-12-13 07:01 UTC, Praashh commented
tagging @emrysal @anikdhabal for a final touch 🙏 .

2025-01-01 13:14 UTC, hariombalhara commented
Reviewing the video in the PR:
I think we should make it clear that the "Booker Rescheduled" in the email sent to the previous host. This could avoid potential confusions as to who reassigned and why. Because reassignment can happen through the app as well by other team members.

Current text
![image](https://github.com/user-attachments/assets/a5860f36-af4b-4af6-bbe2-2ad432ca783e)

2025-01-02 03:19 UTC, hariombalhara commented on packages/emails/email-manager.ts
> +      emailsAndSMSToSend.push(successfullyReScheduledSMS.sendSMSToAttendee(teamMember));
Don't we want sms to behave the same way as email?

2025-01-02 03:23 UTC, hariombalhara commented on packages/emails/templates/organizer-cancelled-email.ts
> +  async getHtml(calEvent: CalendarEvent, organizer: Person, reassigned?: Reassigned) {
We make an important decision based on reassigned, accidentally missing it would send wrong email. So, I think we should keep it required and send it as null when there is actually no reassignment

2025-01-02 03:37 UTC, hariombalhara commented on packages/features/bookings/lib/handleNewBooking.ts
> +          ? freeUsers.find((user) => user.id === (currentRRHostId ?? originalRescheduledBookingUserId))
Why do we need this change?  Isn't `originalRescheduledBookingUserId` always set and correct?

2025-01-02 03:40 UTC, hariombalhara commented
Also, @kart1ka current messaging is wrong
![image](https://github.com/user-attachments/assets/79e574f8-a5ac-4d24-85a7-05dd19382557)

It should instead be as per this I believe https://github.com/calcom/cal.com/pull/17279

2025-01-02 03:52 UTC, hariombalhara commented on packages/emails/email-manager.ts
> +export const sendRoundRobinReassignedEmailsAndSMS = async (
It is always better to have named parameters(through object destructuring) when there are more than 1

2025-01-02 03:54 UTC, hariombalhara requested changes, later dismissed
Thanks @kart1ka for the PR 🙏 I left some comments.

Also, we would appreciate if you can add tests for handleNewBooking flow, there are many tests already written that can get you started
![image](https://github.com/user-attachments/assets/741b66dd-71fe-4186-94d1-5e8a9e39c15a)

2025-01-14 13:54 UTC, kart1ka commented on packages/emails/templates/organizer-cancelled-email.ts
> +  async getHtml(calEvent: CalendarEvent, organizer: Person, reassigned?: Reassigned) {
Since `reassigned` can’t be defined as `null` because of how it’s defined in the parent class (`OrganizerScheduledEmail`), I am defining the type as `Reassigned | undefined` instead of making it optional, similar to how it’s defined [here](https://github.com/calcom/cal.com/blob/main/packages/emails/templates/organizer-reassigned-email.ts#L30).

2025-01-14 13:55 UTC, kart1ka commented on packages/emails/email-manager.ts
> +export const sendRoundRobinReassignedEmailsAndSMS = async (
Done.

2025-01-14 13:57 UTC, kart1ka commented on packages/features/bookings/lib/handleNewBooking.ts
> +          ? freeUsers.find((user) => user.id === (currentRRHostId ?? originalRescheduledBookingUserId))
I have mentioned the reason [here](https://github.com/calcom/cal.com/pull/17768#discussion_r1854077375)

2025-01-14 14:01 UTC, kart1ka commented
> Reviewing the video in the PR: I think we should make it clear that the "Booker Rescheduled" in the email sent to the previous host. This could avoid potential confusions as to who reassigned and why. Because reassignment can happen through the app as well by other team members.
> 
> Current text ![image](https://private-user-images.githubusercontent.com/1780212/399564767-a5860f36-af4b-4af6-bbe2-2ad432ca783e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY4NjIzMTgsIm5iZiI6MTczNjg2MjAxOCwicGF0aCI6Ii8xNzgwMjEyLzM5OTU2NDc2Ny1hNTg2MGYzNi1hZjRiLTRhZjYtYmJlMi0yYWQ0MzJjYTc4M2UucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDExNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAxMTRUMTM0MDE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWYzZGE1NDQ1MDRhNDU5NTMxZGVhYjE3YjdkODE4NzIzMGJkYmY0Yjk0NWU0ZDZmNzA4OTBiYTEyZTM1NjQ5NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.iZ1O9uZ1u9KVDslZt3hzo7cgTdN0WC_LTo1F82y15Jg)

I am displaying the Reason as "Booker Rescheduled" when sending the reassigned email. See screenshot below.

I have also fixed the messaging as per the suggestion [here](https://github.com/calcom/cal.com/pull/17768#issuecomment-2567258552). See screenshot below.

<img width="1172" alt="Screenshot 2025-01-14 at 7 06 18 PM" src="https://github.com/user-attachments/assets/a5107dcb-4244-4ed4-a23c-b81a0bd40362" />

2025-01-14 14:14 UTC, kart1ka commented on packages/emails/email-manager.ts
> +      emailsAndSMSToSend.push(successfullyReScheduledSMS.sendSMSToAttendee(teamMember));
According to my understanding, SMS notifications are only sent to attendees and not to the previous RR meeting host when the meeting is rescheduled and reassigned to a different host. So did not make sense to change the sms behaviour. Please let me know if this is incorrect.

2025-01-14 14:19 UTC, kart1ka commented
> Thanks @kart1ka for the PR 🙏 I left some comments.
> 
> Also, we would appreciate if you can add tests for handleNewBooking flow, there are many tests already written that can get you started ![image](https://private-user-images.githubusercontent.com/1780212/399609810-741b66dd-71fe-4186-94d1-5e8a9e39c15a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY4NjQwNDIsIm5iZiI6MTczNjg2Mzc0MiwicGF0aCI6Ii8xNzgwMjEyLzM5OTYwOTgxMC03NDFiNjZkZC03MWZlLTQxODYtOTRkMS01ZThhOWUzOWMxNWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDExNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAxMTRUMTQwOTAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDI4NGE0YzY5ZmZiNzhkNjBlYTU0NzFkZDEwMDIyNmNlNzg2MWU0NjE2OGYyYTdhZDFkOTg4NmUzZmRjNGI3MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.gN634quzZ_EoFIZvgdO_FQDusyWqh2nx2Wk87OE0ftc)

There was already a test to check if relevant emails were sent when RR booking was rescheduled. I updated the code to ensure that event reassignment emails are sent when that happens.

2025-03-02 06:58 UTC, anikdhabal commented
@kart1ka can you fix the conflicts🙏

2025-03-04 10:06 UTC, kart1ka commented
> @kart1ka can you fix the conflicts🙏

Hi @anikdhabal Conflicts resolved.

2025-05-04 15:16 UTC, kart1ka commented
Hey @anikdhabal 

Just checking on the status of this PR.
I have addressed the changes requested by @hariombalhara.
Do let me know if any other changes need to be made.
Thanks.

2025-07-04 10:45 UTC, Udit-takkar commented on packages/emails/email-manager.ts
> +      emailsAndSMSToSend.push(successfullyReScheduledSMS.sendSMSToAttendee(teamMember));
@kart1ka The behaviour I believe should be the same.

2025-07-04 10:46 UTC, Udit-takkar commented on packages/emails/email-manager.ts
> +      emailsAndSMSToSend.push(successfullyReScheduledSMS.sendSMSToAttendee(teamMember));
It's good to add a unit test here to make sure both email and sms logic should be same.

2025-07-08 06:55 UTC, anikdhabal requested changes, later dismissed
Hey @kart1ka  I’ve fixed this issue in this PR: https://github.com/calcom/cal.com/pull/21390. The only thing left to fix is the email title and subtitle—we’re currently sending the cancellation email to the old host. I’ve updated the issue accordingly.
Also, you can check all the behavior on the latest branch.

2025-07-08 18:53 UTC, kart1ka commented
Hey @anikdhabal, I’ve updated the title and subtitle as discussed and verified that everything else is working as expected.
Note: While merging main into this branch, some linting fixes were automatically applied, resulting in whitespace or newline only changes in a few files. Let me know if you’d like me to revert those.

2025-07-09 09:04 UTC, anikdhabal commented
@kart1ka yeah let's keep only the main changes

2025-07-09 13:57 UTC, kart1ka commented
@anikdhabal I have merged the main branch again and those unwanted changes seem to have gone. Pls review.

2025-08-14 11:38 UTC, volnei commented
@kart1ka can you please fix the conflicts?  🙏🏼

2025-08-19 03:43 UTC, kart1ka commented
> @kart1ka can you please fix the conflicts? 🙏🏼

Done. Please review.

2025-08-27 15:49 UTC, volnei approved these changes

2025-08-27 16:28 UTC, merged