chore: Dependency fixes (remove cross-dep to apps/web)
calcom/cal.com pull request #17784
Opened 2024-11-21 15:28 UTC by emrysal

## What does this PR do?

2024-11-21 15:35 UTC, emrysal commented on packages/features/apps/AdminAppsList.tsx
> -import AppListCard from "../../../apps/web/components/AppListCard";
Features dependent on apps/web here. ⚠️

2024-11-21 15:41 UTC, keithwillcode approved these changes

2024-11-21 15:42 UTC, keithwillcode requested changes
Build error: @calcom/api:build: Type error: Cannot find module '@calcom/features/components/AppListCard' or its corresponding type declarations.

2025-01-06 13:02 UTC, emrysal commented
Addressed in other PRs also, need to be re-assessed if still the case.

2025-01-06 13:02 UTC, closed without merging