fix: bookings for guests added by organizer get cancelled when rescheduled
calcom/cal.com pull request #17820
Opened 2024-11-24 21:59 UTC by kart1ka

## What does this PR do?

- Fixes #17813 (GitHub issue number)
- Fixes CAL-XXXX (Linear issue number - should be visible at the bottom of the GitHub issue description)

[Screencast from 25-11-24 12:25:13 AM IST.webm](https://github.com/user-attachments/assets/2e67a49a-7fd0-4f92-8201-feefda492e17)

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox.
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

1. Create a booking on team pro example account.
2. Login to team pro example account and Go to /bookings/incoming page.
3. Add guests to that booking.
4. Now Reschedule the booking.
5. Notice that the guests that were just added (by team pro example) are now included in the rescheduled booking.

2024-11-26 09:57 UTC, Praashh commented on packages/lib/bookingSuccessRedirect.ts
We are not changing anything locally in this file, so we can keep it as it is.

2024-11-26 10:09 UTC, kart1ka commented on packages/lib/bookingSuccessRedirect.ts
I’ve moved the getSafe function out of the other function it was in so that it can be exported.

2024-11-26 10:16 UTC, Praashh approved these changes
LGTM!!

2024-12-02 19:07 UTC, anikdhabal reviewed
Working fine, but I will review the code once before shipping

2024-12-17 06:44 UTC, Praashh requested changes
@kart1ka can you please resolve merge conflicts?

2024-12-17 07:09 UTC, kart1ka commented
> @kart1ka can you please resolve merge conflicts?

On it.

2024-12-17 09:11 UTC, kart1ka commented
> @kart1ka can you please resolve merge conflicts?

Merge conflicts resolved.

2025-02-07 13:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/calcom/cal.com?pullRequest=17820) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/calcom/cal.com?pullRequest=17820) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: kart1ka<br/>:x: TusharBhatt1<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/calcom/cal.com?pullRequest=17820) it.</sub>

2025-02-07 13:41 UTC, TusharBhatt1 commented on packages/features/bookings/lib/handleNewBooking.ts
> +      .map((guest) =>
_.map()_ is typically used for transforming arrays, but here it’s being used for side effects (pushing to organizerAddedGuests). 
Can replace it with ._forEach()_ ,  making the intent clearer.

2025-02-07 14:15 UTC, TusharBhatt1 commented
The current logic filters out team members, booker, and booker-added guests from the original booking's attendees to identify "guests added by organizer".
However, this approach might not be robust because :
It assumes all remaining attendees are "organizer-added guests"
It doesn't definitively distinguish between truly organizer-added guests and other potential attendees
Guest identification relies solely on email exclusion, which could lead to false positives

Or I am missing something ?

2025-02-11 10:48 UTC, TusharBhatt1 commented on packages/features/bookings/lib/handleNewBooking.ts
> +      .map((guest) =>
`.forEach()` is more appropriate here

2025-02-11 10:49 UTC, TusharBhatt1 commented
@kart1ka LGTM , once the comment is resolved , let's take this ahead

2025-02-11 11:53 UTC, kart1ka commented
> @kart1ka tested and LGTM , once the comment is resolved , let's take this ahead

Done

2025-02-11 12:25 UTC, TusharBhatt1 approved these changes
Tested works well , LGTM !

2025-02-11 12:26 UTC, merged

2025-02-11 14:09 UTC, anikdhabal commented on packages/features/bookings/lib/handleNewBooking.ts
> +    // Get guests that were added by the booker in the original booking
@kart1ka Is this the right place for the changes? I think we should fix the addGuest handler and find out why it is causing this error. It should be similar to how we normally do it from the booking page/