Added Changes
calcom/cal.com pull request #17858
Opened 2024-11-26 18:05 UTC by SoloDevAbu

## What does this PR do?

- Added a specific block to handle cancellation notifications separately
- Adjusted the attachment logic in the sendEmail function to ensure calendar event attachments are only included if the event is not canceled.
- Fixes #17785 

Bug fix
Add the necessary check so that email doesn't send to a cancelled event

2024-11-26 18:05 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/calcom/cal.com?pullRequest=17858) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/calcom/cal.com?pullRequest=17858) before we can accept your contribution.<br/><hr/>**Abu** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/calcom/cal.com?pullRequest=17858) it.</sub>

2024-11-27 18:33 UTC, zomars requested changes
Thank you for your contribution 🙏 

Unfortunately this doesn't seems to solve the original issue at #17858 

Could you elaborate on how these changes are preventing scheduled reminders to stop being for cancelled bookings? Also could you add unit tests or some kind of evidence that your solution works?

​May you be well 🙏

2024-11-27 18:33 UTC, zomars commented on packages/features/ee/workflows/lib/reminders/emailReminderManager.ts
> +  } else if (
Maybe I'm missing something, but could you elaborate on how is this different from the logic below where this belonged?

2025-01-04 15:11 UTC, anikdhabal commented
Close due to inactive

2025-01-04 15:11 UTC, closed without merging