fix: `getAttributeRoutingConfig` find the route based on the chosenRouteId
calcom/cal.com pull request #17867
Opened 2024-11-27 04:01 UTC by joeauyeung

## What does this PR do?

We were parsing routes based on `eventTypeId` but routes could be pointing to the same event type. This was causing misroutings.

- Fixes #XXXX (GitHub issue number)
- Fixes CAL-XXXX (Linear issue number - should be visible at the bottom of the GitHub issue description)

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [ ] I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox.
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works.

2024-11-27 05:24 UTC, hariombalhara commented on apps/web/lib/getTeamMemberEmailFromCrm.ts
> +      responses: {
I think we could rewrite this query to be something like this which is simpler and must be faster

```
const response = await prisma.app_RoutingForms_Form.findUnique({where:{
id: routingFormResponseId,
include: {
form: {
select: {routes:true}
}
}
}})
```

2024-11-27 05:24 UTC, hariombalhara approved these changes, later dismissed

2024-11-27 16:22 UTC, hbjORbj submitted a review, later dismissed

2024-11-27 18:26 UTC, zomars requested changes
Seems like unit tests are failing

2024-11-28 19:30 UTC, zomars approved these changes

2024-11-28 19:31 UTC, merged