fix: ai translations description for atoms
calcom/cal.com pull request #17875
Opened 2024-11-27 11:02 UTC by Ryukemeister

## What does this PR do?

- Fixes #XXXX (GitHub issue number)
- Fixes CAL-XXXX (Linear issue number - should be visible at the bottom of the GitHub issue description)

## Mandatory Tasks (DO NOT REMOVE)

- [ ] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [ ] I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox.
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

- Are there environment variables that should be set?
- What are the minimal test data to have?
- What is expected (happy path) to have (input and output)?
- Any other important info that could help to test that PR

## Checklist

- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my changes generate no new warnings

2024-11-27 11:23 UTC, hbjORbj requested changes, later dismissed

2024-11-27 11:23 UTC, hbjORbj commented on packages/features/bookings/Booker/Booker.tsx
> +                  i18nLocales={i18nLocales}
double checking: you don't need to pass `userLocale` here?

2024-11-27 11:23 UTC, hbjORbj commented on packages/features/bookings/Booker/components/EventMeta.tsx
> +  locale?: string | null;
shouldn't this be `userLocale`? based on the other changes you added

2024-11-27 11:23 UTC, hbjORbj commented on packages/platform/atoms/booker/BookerWebWrapper.tsx
> +      i18nLocales={i18nLocales}
Hmm passing a prop doesn't seem optimal. I'd suggest importing it from `i18n.json` where it's needed

2024-11-27 16:00 UTC, hbjORbj commented on packages/features/bookings/Booker/components/EventMeta.tsx
> +      i18nLocales.locale.targets.includes(trans.targetLocale) &&
1. i18nLocales name is misleading
2. `i18n.locale.targets.concat([i18n.locale.source])`

2024-12-02 12:19 UTC, ThyMinimalDev approved these changes

2024-12-02 19:27 UTC, merged