feat: Add OAuth support for closecom app linking
calcom/cal.com pull request #17936
Opened 2024-12-02 06:58 UTC by asadath1395

## What does this PR do?

Add OAuth support for closecom app linking

- Fixes #12228 

## Mandatory Tasks (DO NOT REMOVE)

- [ ] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [ ] I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox.
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

- Create an account in [Close](https://www.close.com/)
- Create an OAuth app 
- Make note of the `client_id` and `client_secret` and add those as environment variables in `.env`
- Install the app

2024-12-02 07:23 UTC, Praashh requested changes
type checks are failing, can you please fix ?

2024-12-02 08:49 UTC, asadath1395 commented
@Praashh Fixed tests and added loom video too

2024-12-04 06:35 UTC, Praashh approved these changes
LGTM!

2024-12-05 13:44 UTC, anikdhabal commented
What about the current users who are using the legacy one right now?

2024-12-05 17:12 UTC, asadath1395 commented on packages/app-store/closecom/lib/CrmService.ts
> +    if (parsedKey.data.encrypted) {
Keep support for legacy API key

2024-12-05 17:13 UTC, asadath1395 commented on packages/lib/CloseCom.ts
> +    if (this.isOAuth) {
Support both OAuth and API key based authentication

2024-12-05 17:15 UTC, asadath1395 commented
> @asadath1395 What about the current users who are using the legacy one right now?

@anikdhabal Its already handled in code right now, we are still supporting old API key based approach along with new OAuth approach. User's who install/reinstall the app will use new OAuth, old users will still be using API key based authentication

2024-12-09 14:20 UTC, keithwillcode commented
Would like @emrysal or @zomars to review this before merging

2024-12-09 23:45 UTC, emrysal approved these changes
Looking good to me 👏  - nice work.

2024-12-10 00:18 UTC, merged