feat: migrate /apps/routing-forms/forms to /routing
calcom/cal.com pull request #18001
Opened 2024-12-04 14:30 UTC by VK-RED

## What does this PR do?

- Setup /routing page
- Added redirect from /apps/routing-forms/forms to /routing
- Renamed "Routing Forms" to "Routing" and changed the icon to split
- Fixes #17955
- Fixes CAL-4828

### Screencast

[Screencast from 2024-12-04 19-45-04.webm](https://github.com/user-attachments/assets/43aca372-fa69-4ebe-9dcb-015f4802afdd)

## Mandatory Tasks (DO NOT REMOVE)

- [ ] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [ ] I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox.
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works.

2024-12-04 15:43 UTC, Praashh commented on apps/web/middleware.ts
> +  // redirect /apps/routing-forms/forms to /routing
```suggestion
```

2024-12-04 16:06 UTC, Praashh commented on apps/web/middleware.ts
> +
why are we creating a new URL and cloning it? why not just redirect it like 

```
if (url.pathname === "/apps/routing-forms/forms") {
  return NextResponse.redirect("/routing", { headers: requestHeaders });
 }
```

2024-12-10 02:38 UTC, VK-RED commented on apps/web/middleware.ts
> +  // redirect /apps/routing-forms/forms to /routing
removed the comment

2024-12-10 05:57 UTC, Praashh requested changes
e2e tests are failing, can you resolve this 🙏

2024-12-10 07:40 UTC, VK-RED commented
> e2e tests are failing, can you resolve this 🙏

Yeah sure :+1:

2024-12-11 19:31 UTC, Praashh approved these changes
LGTM!!, @anikdhabal please give it a fina touch 🙏

2024-12-11 20:12 UTC, PeerRich commented
are all URLs redirecting accordingly?

2024-12-11 20:12 UTC, PeerRich commented
requested review by @hariombalhara

2024-12-11 21:18 UTC, merged

2024-12-11 21:48 UTC, emrysal commented
@PeerRich Best to put in Changes Requested

Reviewed in @hariombalhara's stead, everything works as it is supposed to, however, although a bit vague from the reported feature request, I would assume this should happen also - not just the /forms page:

```
./apps/routing-forms/form-edit/[...id] -> ./routing/form-edit/[...id]
./apps/routing-forms/route-builder/[...id] -> ./routing/route-builder/[...id]
&
./apps/routing-forms/reporting/[...id] -> ./routing/reporting/[...id]
```

This does not happen yet, @PeerRich to confirm; if so: @VK-RED if you could also have a look at this in a follow-up?

2024-12-11 22:20 UTC, emrysal commented
Hi @VK-RED I've decided to revert this change, the reason for this is that it's a (minor) additional overhead in middleware, is missing some key parts such as additional URLs & there should have been a code cleanup as part of this.

I'll talk with @hbjORbj to aid in this also as part of the appDir migration as it's an ideal migration usecase, will re-open the issue to continue collaborating.

2024-12-12 03:25 UTC, VK-RED commented
@emrysal Sure will followup on this .. I thought we only needed to change /apps/routing -forms/routing to /routing . Will do this for all /apps/routing-forms routes too..