feat: show ooo forwarding and emoji when not available
calcom/cal.com pull request #18054
Opened 2024-12-07 16:40 UTC by kart1ka

## What does this PR do?

- Fixes #17601 (GitHub issue number)
- Fixes CAL-4704 (Linear issue number - should be visible at the bottom of the GitHub issue description)

https://github.com/user-attachments/assets/b4903a6d-2b91-4994-b7dd-8d8966abbd27

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox.
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

- Create a busy event on your calendar for a specific date.
- Mark yourself as "Out of Office" (OOO) for the same date as the busy event.
- Navigate to the booking page for an event.
- Verify that the date is now marked as OOO, even though it is unavailable due to the busy event on the calendar.

2024-12-08 05:33 UTC, kart1ka commented on packages/lib/slots.ts
> +      const enrichedToUser = toUser ? await UserRepository.enrichUserWithItsProfile({ user: toUser }) : null;
If toUser belongs to an org, redirecting to that user leads to a 404 page. This fixes that.

Bug Video: 

https://github.com/user-attachments/assets/73212f8b-71cb-4431-8e49-7e45c9b406d7

2024-12-09 06:35 UTC, Praashh commented on packages/lib/slots.ts
> +      const enrichedToUser = toUser ? await UserRepository.enrichUserWithItsProfile({ user: toUser }) : null;
We should have a null check for prod before creating ooSlot.

2024-12-09 22:06 UTC, Praashh requested changes
@kart1ka e2e tests are failing, please fix it 🙏

2024-12-10 02:37 UTC, kart1ka commented
> @kart1ka e2e tests are failing, please fix it 🙏

@Praashh Those tests are failing on the main branch as well.

2025-01-04 15:53 UTC, Praashh commented
LGTM!! but blocking it because of failure of test cases

2025-01-15 07:27 UTC, kart1ka commented
Hey @Praashh I have fixed the failing test. Please re-review.

2025-01-15 07:29 UTC, Praashh approved these changes

2025-01-21 09:41 UTC, PeerRich commented
i dont yet understand yet waht this PR fixes. the video looks the same like the current behaviour @Praashh

2025-01-21 10:09 UTC, kart1ka commented
> i dont yet understand yet waht this PR fixes. the video looks the same like the current behaviour @Praashh

Hi @PeerRich This PR adds the feature to always show ooo emoji and the button to redirect to team member (member1 in the video) even when the user (owner1 in the video) is not available at that time (10 dec in the video).

2025-01-30 15:36 UTC, merged

2025-02-04 11:09 UTC, emrysal commented
Hi @kart1ka we've had to revert this pr as it broke some core logic. We've since added a test to cover this. Feel free to reopen this pr to fix with the new test cases.