fix: Ensure correct fallback to current month when 'month' query para…
calcom/cal.com pull request #18097
Opened 2024-12-10 20:56 UTC by sanchitttt

Ensure correct fallback to current month when 'month' query param is missing

Updated the query parameter handling logic to properly format the 'date' param as 'YYYY-MM' in case month param is missing.  This resolves an issue where previous slots were not appearing.

## What does this PR do?

- Fixes #18094 (GitHub issue number)

## Mandatory Tasks (DO NOT REMOVE)

- [ ] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [ ] I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox.
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

1. **Navigate to an Event Page**: Open a public page for any event.
2. **Select a Date**: Choose a date from the middle or end of the month [Ensure there exists dates prior to the date you select for this scenario].
3. **Modify the URL**: Copy the page URL and manually remove the `month` query parameter.
4. **Perform a Hard Refresh**: Refresh the page while retaining the modified URL.

### Expected Behavior
- **Before the Fix**: Slots before the selected date were not selectable.
- **After the Fix**: All slots, including those before the selected date, should now be selectable.

2024-12-11 10:54 UTC, Praashh requested changes
Hey @sanchitttt , can you attach a loom of the fix ?

2024-12-11 15:06 UTC, sanchitttt commented
> Hey @sanchitttt , can you attach a loom of the fix ?

Hi @Praashh 

Here is the link to the loom video: https://www.loom.com/share/780e28bf83644d44a5dc9969c6df6c7f

On the left it is the current prod app and on the right is the one with changes.

Test scenario is same across both sides i.e. availability is set for Dec 13, Dec 20 & Dec 24 for one to book.

2025-02-04 14:21 UTC, retrogtx approved these changes
works, lgtm!

2025-02-04 14:52 UTC, Praashh approved these changes

2025-02-04 14:58 UTC, joeauyeung approved these changes

2025-02-04 15:03 UTC, merged