added turnstile to booking page
calcom/cal.com pull request #18104
Opened 2024-12-11 08:59 UTC by monopoly21

## What does this PR do?

- Fixes #17999 (GitHub issue number)
- Fixes CAL-4847 (Linear issue number - should be visible at the bottom of the GitHub issue description)

## Mandatory Tasks (DO NOT REMOVE)

- [ ] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [ ] I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox.
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

- Are there environment variables that should be set?
- What are the minimal test data to have?
- What is expected (happy path) to have (input and output)?
- Any other important info that could help to test that PR

## Checklist

- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my changes generate no new warnings

2024-12-11 08:59 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/calcom/cal.com?pullRequest=18104) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/calcom/cal.com?pullRequest=18104) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/calcom/cal.com?pullRequest=18104) it.</sub>

2024-12-11 10:53 UTC, Praashh requested changes
Hey @monopoly21, I can't reproduce this feature locally. Could you share the steps to reproduce it?

2024-12-11 11:07 UTC, monopoly21 commented
> Hey @monopoly21, I can't reproduce this feature locally. Could you share the steps to reproduce it?



> add 
NEXT_PUBLIC_CLOUDFLARE_SITEKEY=
CLOUDFLARE_TURNSTILE_SECRET=
In .env you would get this after creating a turnstile widget from cloudflare
Run yarn dx

2024-12-11 11:56 UTC, monopoly21 commented
@Praashh were you able to reproduce locally and are there any changes required?

2025-01-15 17:00 UTC, keithwillcode commented
At the moment, there is too low of a pre-clearance rate and we are not enabling this on the booking page at this time.

2025-01-15 17:00 UTC, closed without merging