feat: server side sorting for insights routing
calcom/cal.com pull request #18113
Opened 2024-12-11 15:57 UTC by eunjae-lee

## What does this PR do?

- Fixes #XXXX (GitHub issue number)
- Fixes CAL-XXXX (Linear issue number - should be visible at the bottom of the GitHub issue description)

## Mandatory Tasks (DO NOT REMOVE)

- [ ] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [ ] I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox.
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

- Are there environment variables that should be set?
- What are the minimal test data to have?
- What is expected (happy path) to have (input and output)?
- Any other important info that could help to test that PR

## Checklist

- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my changes generate no new warnings

2024-12-19 15:49 UTC, eunjae-lee commented on packages/features/insights/components/RoutingFormResponsesTable.tsx
> +          enableSorting: false,
we cannot sort by properties from jsonb column

2024-12-20 07:59 UTC, sean-brydon commented on packages/prisma/migrations/20241212164338_create_routing_form_response/migration.sql
> +CREATE OR REPLACE VIEW "RoutingFormResponse" AS
Not automatically but whoever is deploying will run the migration

2024-12-20 08:09 UTC, sean-brydon commented on packages/prisma/migrations/20241212164338_create_routing_form_response/migration.sql
> +  ) as "responseLowercase",
Im not sure im a fan of having duplicated data here - especially since it seems like both are returned to the client

2024-12-20 08:23 UTC, sean-brydon requested changes
I'm happy with the code changes here noticed a few things, 

NIT: Not all columns are sortable which seems a bit weird - especially numeric attributes i kinda expected them to be sortable too. 

Blocking: Downloading data by csv now hard crashes my app with an internal server error

2024-12-20 09:49 UTC, eunjae-lee commented
> NIT: Not all columns are sortable which seems a bit weird - especially numeric attributes i kinda expected them to be sortable too.

Yeah that's a bummer. It's because Prisma doesn't support ordering by jsonb fields.

2024-12-20 09:52 UTC, eunjae-lee commented
> Blocking: Downloading data by csv now hard crashes my app with an internal server error

taking a look now

2025-01-02 15:17 UTC, eunjae-lee commented on packages/features/data-table/hooks/index.ts
> +export * from "./useDataTable";
these files are cut & pasted from ../utils

2025-01-03 10:38 UTC, sean-brydon approved these changes
LGTM! Thanks for the fix sorry for the slow review holidays n all of that 🎅 

This UX is much nicer

2025-01-03 10:58 UTC, merged