Plain integration WIP
calcom/cal.com pull request #18130
Opened 2024-12-12 03:00 UTC by nizzyabi

## What does this PR do?

- Fixes #XXXX (GitHub issue number)
- Fixes CAL-XXXX (Linear issue number - should be visible at the bottom of the GitHub issue description)

## Mandatory Tasks (DO NOT REMOVE)

- [ ] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [ ] I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox.
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

- Are there environment variables that should be set?
- What are the minimal test data to have?
- What is expected (happy path) to have (input and output)?
- Any other important info that could help to test that PR

## Checklist

- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my changes generate no new warnings

2024-12-12 04:33 UTC, baileypumfleet commented on packages/app-store/office365calendar/api/add.ts
So you know why this and the yarn.lock are in the PR?

2024-12-12 16:37 UTC, youneshenniwrites commented on apps/web/pages/api/get-customer.ts
> +};
```suggestion
enum DividerSpacing {
  Relaxed = "relaxed",
  Default = "default",
  Compact = "compact",
}

type CardComponent = {
  componentText?: {
    text: string;
  };
  componentDivider?: {
    dividerSpacing?: DividerSpacing;
  };
  componentHeader?: {
    text: string;
  };
};
```

2024-12-13 19:36 UTC, baileypumfleet requested changes
A few comments to address, but looks good mostly :)

2024-12-13 19:36 UTC, baileypumfleet commented on apps/web/pages/api/example.ts
> +      where: { email },
Let's only fetch certain fields based on what we need. The user table has a lot of columns nowadays

2024-12-13 19:36 UTC, baileypumfleet commented on apps/web/pages/api/get-customer.ts
> +    console.log("Request received:", {
We should probably get rid of all console.logs that don't log an actual error or important action

2024-12-13 19:36 UTC, baileypumfleet commented on apps/web/pages/api/plain/customer-card.ts
Is this file still being used? It's all commented out

2024-12-13 19:36 UTC, baileypumfleet commented on turbo.json
We should also add to .env.example

2024-12-13 19:36 UTC, baileypumfleet commented on packages/app-store/office365calendar/api/add.ts
These two Office365 scope changes still seem to be in this PR

2024-12-17 17:42 UTC, emrysal requested changes
Needs a bit more work, mostly on the validation & error handling side to be mergeable.

2024-12-17 17:42 UTC, emrysal commented on .env.example
> +HMAC_SECRET_KEY=
Can we add a PLAIN_ prefix here too?

2024-12-17 17:42 UTC, emrysal commented on apps/web/pages/api/customer-card.ts
> +    const user = await prisma.user.findUnique({
It's better to use the repository/user here 🙏

2024-12-17 17:42 UTC, emrysal commented on apps/web/pages/api/customer-card.ts
> +  try {
Try/catch here is not needed, handlers should get wrapped properly already by the apiHandler

2024-12-17 17:42 UTC, emrysal commented on apps/web/pages/api/customer-card.ts
> +    const { email, id, username, timeZone, emailVerified, identityProvider, twoFactorEnabled } = customer;
How is this input validated? Seems to me there's a lot of ways this can 500

2024-12-18 01:04 UTC, emrysal commented on packages/lib/CalEventParser.ts
> +`;
This was a revert that somehow showed up as the changelog

2024-12-18 01:06 UTC, emrysal approved these changes
Looks good now, LGTM 🚀

2024-12-18 01:24 UTC, baileypumfleet approved these changes

2024-12-18 01:24 UTC, merged