feat: prevent automatic query parameters when opening booking page
calcom/cal.com pull request #18132
Opened 2024-12-12 08:37 UTC by sanchitttt

- Resolve the user hindrance where the event's booking page should not have search parameters such as date and month in the initial page load

## What does this PR do?

- Feat #18076(GitHub issue number)
- Fixes #18097 since it is needed

Loom link : https://www.loom.com/share/0f2d0cc02fd84868b72780ae3840dbc2

## Mandatory Tasks (DO NOT REMOVE)

- [ ] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [ ] I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox.
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works.

2024-12-12 13:57 UTC, Praashh requested changes
We also need test case for this feature, @sanchitttt  can you please add 🙏

2024-12-12 14:07 UTC, sanchitttt commented
> We also need test case for this feature, @sanchitttt can you please add 🙏

okay sure

2024-12-14 07:57 UTC, sanchitttt commented
> We also need test case for this feature, @sanchitttt can you please add 🙏

Hi @Praashh 

Could you help me understand what specific test cases I should write? Since my changes are primarily in the store.ts file (specifically for setSelectedDate) and the Days component (particularly for useHandleInitialDateSelection), I assume I should focus on testing these areas only. Is that okay?

For store.ts , I've done something like: 

```
describe('useBookerStore - setSelectedDate',() => {
  beforeEach(() => {
    // Set the initial state or reset URL before each test
    window.history.pushState({},'','/');
    useBookerStore.setState(initialStoreState,true); // The second argument `true` tells Zustand to merge and not overwrite the state completely
  });

  afterEach(() => {
    cleanup();
  });

  it('given empty search params when setSelectedDate is invoked with omitUpdatingParams as true then url search params should remain unchanged (Custom Behavior)',() => {
    const TestComponent = () => {
      const { setSelectedDate,selectedDate } = useBookerStore((state) => ({
        setSelectedDate: state.setSelectedDate,
        selectedDate: state.selectedDate, // Access the selectedDate from the store
      }));

      return (
        <button onClick={() => setSelectedDate('2024-12-14',true)}>
          Set Date
        </button>
      );
    };

    render(<TestComponent />);

    // Simulate clicking the button
    const button = screen.getByText('Set Date');
    act(() => {
      button.click();
    });

    const urlSearchParams = new URLSearchParams(window.location.search);
    const dateParam = urlSearchParams.get("date");
    const monthParam = urlSearchParams.get("month");

    // Assert that the date and month query params remain null
    expect(dateParam).toBeNull();
    expect(monthParam).toBeNull();
  });

  it('given empty search params when setSelectedDate is invoked with omitUpdatingParams as false then url search params should remain change (Default Behavior)',() => {
    const TestComponent = () => {
      const { setSelectedDate,selectedDate } = useBookerStore((state) => ({
        setSelectedDate: state.setSelectedDate,
        selectedDate: state.selectedDate, // Access the selectedDate from the store
      }));


      return (
        <button onClick={() => setSelectedDate('2024-12-15',false)}>
          Set Date
        </button>
      );
    };

    render(<TestComponent />);

    // Simulate clicking the button
    const button = screen.getByText('Set Date');
    act(() => {
      button.click();
    });

    const urlSearchParams = new URLSearchParams(window.location.search);
    const dateParam = urlSearchParams.get("date");
    const monthParam = urlSearchParams.get("month");

    // Assert that the date and month query params are updated correctly
    expect(dateParam).equal("2024-12-15");
    expect(monthParam).equal("2024-12");
  });
});

```

Am I heading in the right direction ?

For the useHandleInitialDateSelection(), I was thinking of extracting it into a separate file as a hook so it can be tested better. Will that be okay ?

2024-12-29 04:40 UTC, Praashh commented
> > We also need test case for this feature, @sanchitttt can you please add 🙏
> 
> Hi @Praashh
> 
> Could you help me understand what specific test cases I should write? Since my changes are primarily in the store.ts file (specifically for setSelectedDate) and the Days component (particularly for useHandleInitialDateSelection), I assume I should focus on testing these areas only. Is that okay?
> 
> For store.ts , I've done something like:
> 
> ```
> describe('useBookerStore - setSelectedDate',() => {
>   beforeEach(() => {
>     // Set the initial state or reset URL before each test
>     window.history.pushState({},'','/');
>     useBookerStore.setState(initialStoreState,true); // The second argument `true` tells Zustand to merge and not overwrite the state completely
>   });
> 
>   afterEach(() => {
>     cleanup();
>   });
> 
>   it('given empty search params when setSelectedDate is invoked with omitUpdatingParams as true then url search params should remain unchanged (Custom Behavior)',() => {
>     const TestComponent = () => {
>       const { setSelectedDate,selectedDate } = useBookerStore((state) => ({
>         setSelectedDate: state.setSelectedDate,
>         selectedDate: state.selectedDate, // Access the selectedDate from the store
>       }));
> 
>       return (
>         <button onClick={() => setSelectedDate('2024-12-14',true)}>
>           Set Date
>         </button>
>       );
>     };
> 
>     render(<TestComponent />);
> 
>     // Simulate clicking the button
>     const button = screen.getByText('Set Date');
>     act(() => {
>       button.click();
>     });
> 
>     const urlSearchParams = new URLSearchParams(window.location.search);
>     const dateParam = urlSearchParams.get("date");
>     const monthParam = urlSearchParams.get("month");
> 
>     // Assert that the date and month query params remain null
>     expect(dateParam).toBeNull();
>     expect(monthParam).toBeNull();
>   });
> 
>   it('given empty search params when setSelectedDate is invoked with omitUpdatingParams as false then url search params should remain change (Default Behavior)',() => {
>     const TestComponent = () => {
>       const { setSelectedDate,selectedDate } = useBookerStore((state) => ({
>         setSelectedDate: state.setSelectedDate,
>         selectedDate: state.selectedDate, // Access the selectedDate from the store
>       }));
> 
> 
>       return (
>         <button onClick={() => setSelectedDate('2024-12-15',false)}>
>           Set Date
>         </button>
>       );
>     };
> 
>     render(<TestComponent />);
> 
>     // Simulate clicking the button
>     const button = screen.getByText('Set Date');
>     act(() => {
>       button.click();
>     });
> 
>     const urlSearchParams = new URLSearchParams(window.location.search);
>     const dateParam = urlSearchParams.get("date");
>     const monthParam = urlSearchParams.get("month");
> 
>     // Assert that the date and month query params are updated correctly
>     expect(dateParam).equal("2024-12-15");
>     expect(monthParam).equal("2024-12");
>   });
> });
> ```
> 
> Am I heading in the right direction ?
> 
> For the useHandleInitialDateSelection(), I was thinking of extracting it into a separate file as a hook so it can be tested easily. Will that be okay ?

yeah something like that, it should check the query params

2025-02-13 05:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/calcom/cal.com?pullRequest=18132) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/calcom/cal.com?pullRequest=18132) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: sanchitttt<br/>:x: TusharBhatt1<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/calcom/cal.com?pullRequest=18132) it.</sub>

2025-02-13 05:55 UTC, TusharBhatt1 commented
@sanchitttt are you still working on this ?

2025-02-13 12:05 UTC, TusharBhatt1 approved these changes, later dismissed
Tested and LGTM , works well !

2025-02-17 14:30 UTC, TusharBhatt1 reviewed
Tested working well !

2025-02-17 14:34 UTC, TusharBhatt1 approved these changes

2025-02-17 14:41 UTC, merged