feat: enable 'Overlay Calendar' enabled by default for signed in users
calcom/cal.com pull request #18188
Opened 2024-12-14 19:37 UTC by sanchitttt

## What does this PR do?

- Fixes #18146(GitHub issue number)

Loom Video: https://www.loom.com/share/94a2937257004fb28b017c4cbd60eb09 

## Mandatory Tasks (DO NOT REMOVE)

- [ ] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [ ] I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox.
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

- For signed in user, simply click on weekly and column views to see if "Overlay Calendar" is enabled by default
- For un-signed user, simply click on weekly and column views to see if "Overlay Calendar" is disabled by default

2024-12-15 09:47 UTC, sanchitttt commented
# Notes before merging

The behavior which is present currently is that : 
1.  'Overlay Calendar' enabled on initial page load ✔️
2.  'Overlay Calendar' enabled on every view which is toggled  ✔️

## Clarification Needed

- Should the 'Overlay Calendar' remain **disabled** if a user explicitly disables it?  
  - **Option 1:** Re-enable by default on every view toggle (current behavior).  
  - **Option 2:** Persist the user’s preference to keep it disabled, even after a view toggle.

2025-01-06 12:29 UTC, sean-brydon approved these changes, later dismissed
LGTM - works for me from what i can see

2025-01-06 12:41 UTC, anikdhabal requested changes

2025-01-06 12:41 UTC, anikdhabal commented on packages/platform/atoms/booker/BookerWebWrapper.tsx
> +
Shouldn't we add a check to verify if a supported calendar is connected or not? cc @sean-brydon

2025-02-11 07:52 UTC, anikdhabal requested changes, later dismissed

2025-02-11 07:52 UTC, anikdhabal commented on packages/platform/atoms/booker/BookerWebWrapper.tsx
> +        // Also update localStorage
@retrogtx The previous changes look good and simple. The only thing that needs to be added in the check is verifying if a supported calendar is connected or not.

2025-02-14 06:01 UTC, TusharBhatt1 commented
@sanchitttt you still working on it ?

2025-02-14 06:19 UTC, retrogtx commented
> @sanchitttt you still working on it ?

under progress

2025-02-19 14:19 UTC, anikdhabal commented on packages/platform/atoms/booker/BookerWebWrapper.tsx
> +        // Also update localStorage
@retrogtx can you pls uncommit all of your changes

2025-04-03 04:07 UTC, TusharBhatt1 approved these changes, later dismissed

2025-04-03 06:51 UTC, TusharBhatt1 commented on packages/platform/atoms/booker/BookerWebWrapper.tsx
> +  }, [hasSession]);
Instead of `localStorage?.setItem("overlayCalendarSwitchDefault", "true");` , we should use `onOverlaySwitchStateChange(true)`

2025-04-04 02:55 UTC, retrogtx commented
@anikdhabal should I make changes to this PR again 😆

2025-04-04 18:27 UTC, TusharBhatt1 approved these changes

2025-04-06 20:36 UTC, Ryukemeister commented
in previous conversations @anikdhabal suggests the following change

> @retrogtx The previous changes look good and simple. The only thing that needs to be added in the check is verifying if a supported calendar is connected or not.

just wanna know if that condition is already covered in previous PRs or do we not plan to check if the supported calendar is connected or not when toggle overlay calendar is true?

2025-04-07 06:11 UTC, retrogtx commented
we do plan to check whether the calendar is connected or not

2025-04-07 06:47 UTC, ThyMinimalDev approved these changes

2025-04-07 06:58 UTC, merged