fix: no available users found while booking recurring event
calcom/cal.com pull request #18180
Opened 2024-12-14 16:15 UTC by sanchitttt

- No available users error was coming while booking recurring event since the 'first two slots' should be available logic was present while booking but not while showing availability

## What does this PR do?

- Fixes #18072(GitHub issue number)

Loom Video: https://www.loom.com/share/26090f95cfed4818b167ca9ad0759582

## Mandatory Tasks (DO NOT REMOVE)

- [ ] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [ ] I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox.
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

- Create a recurring event
- Pick a date for which the next interval's slot does not exist [For example if you picked week recurring, the next week date]
- The date slot for which the next interval's date slot does not exist, should not be selectable
- Also , manually change the input occurences count to 1 for edge case, in the case of 1, all slots should appear and this will not apply

2024-12-14 16:18 UTC, sanchitttt commented
![image](https://github.com/user-attachments/assets/a63c574d-6603-459d-838f-9f1196d4c55f)

Please clarify these doubts before merging :
1) These are the places where useNonEmptyScheduleDays() is being used. I've not made logic changes in these places, please LMK if same changes are required there as well [i.e. passing of additionalParams]

NOTES : 
1) Only weekly , monthly and yearly I've tested since they are the only options one can choose from while creating event, LMK if more support is needed.

2024-12-19 19:46 UTC, zomars requested changes
Thank you for your contribution 🙏 

Can we add a unit test to prevent future regressions?

2025-01-01 10:33 UTC, hariombalhara commented on packages/features/schedules/lib/use-schedule/useNonEmptyScheduleDays.ts
> +  return Array.from(nonEmptyDays);
I think we should explicitly sort the generated array here as order from the set can't be guaranteed(though it would usually work)

2025-01-01 10:37 UTC, hariombalhara commented on packages/features/schedules/lib/use-schedule/useNonEmptyScheduleDays.ts
> +    (additionalParams?.recurringEventFreq || additionalParams?.recurringEventFreq == 0)
This check seems tricky, would it make sense to move it to `retainDaysWithFirstTwoSlotsAvailable` fn itself? 

We could just keep `additionalParams?.occurenceCount` here and rest inside the fn

2025-01-01 10:39 UTC, hariombalhara commented on packages/features/schedules/lib/use-schedule/useNonEmptyScheduleDays.ts
> +    retainDaysWithFirstTwoSlotsAvailable(
Default is first two slots and is configurable [here](https://github.com/sanchitttt/cal.com/blob/b62fae6e0064413df1d44c3500789859535bc93b/packages/features/bookings/lib/handleNewRecurringBooking.ts#L26)
We should use that variable and accordingly return dates with firstXSlotsAvailable

2025-01-01 11:24 UTC, hariombalhara requested changes
This is fixing a specific case where there entire day is unavailable. We need to enhance this logic to handle unavailable slots on available days.

Scenario:

9:30 on Monday(1st) available
10:30 on Monday(1st) available

9:30 on Monday(8th) unavailable
10:30 on Monday(8th) available


10:30 on Monday(1st) should be bookable but not 9:30

2025-02-05 13:03 UTC, closed without merging