fixes #18146: enable overlay calendar by default for logged-in users
calcom/cal.com pull request #18191
Opened 2024-12-15 04:39 UTC by retrogtx

Loom Video: https://www.loom.com/share/66ec51b1b9ba45c5b47f64881464e131?sid=b14ebee0-ba0b-4ff6-86a6-35c93f159d2a

## What does this PR do?

- Fixes #18146
- Fixes [CAL-4882](https://linear.app/calcom/issue/CAL-4882/turn-overlay-your-calendar-on-by-default-if-signed-in)

Hope this helps.

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox.
- [x] I confirm automated tests are in place that prove my fix is effective or that my feature works.

2024-12-15 05:26 UTC, retrogtx commented
is this good enough? works fine

@Praashh @anikdhabal

2024-12-15 14:39 UTC, Praashh requested changes
uncommit `yarn.lock` file.

2024-12-15 14:53 UTC, retrogtx commented
> can you uncommit `yarn.lock` file.

done!

2024-12-16 14:32 UTC, Praashh commented on packages/features/bookings/Booker/components/OverlayCalendar/OverlayCalendarSwitch.tsx
>    }, [hasSession, switchEnabled, setContinueWithProvider, onStateChange]);
any change to setContinueWithProvider would trigger both conditions to be checked
```suggestion
  useEffect(() => {
    if (!hasSession && switchEnabled) {
      onStateChange(false);
      setContinueWithProvider(true);
    }
  }, [hasSession, switchEnabled, setContinueWithProvider, onStateChange]);

  useEffect(() => {
    if (hasSession && !switchEnabled) {
      onStateChange(true);
      localStorage?.setItem("overlayCalendarSwitchDefault", "true");
    }
  }, [hasSession, switchEnabled, onStateChange]);
```

2024-12-16 14:46 UTC, Praashh requested changes
tagging @anikdhabal for a final touch 🙏

2024-12-18 12:42 UTC, PeerRich approved these changes
looks great! @sean-brydon can you review too?

2025-01-06 12:43 UTC, anikdhabal commented
Go with this one:- https://github.com/calcom/cal.com/pull/18188

2025-01-06 12:43 UTC, closed without merging