fix: wrong Meeting Ended payload in zapier
calcom/cal.com pull request #18202
Opened 2024-12-16 10:23 UTC by kart1ka

## What does this PR do?

- Fixes #17915 (GitHub issue number)
- Fixes CAL-4820 (Linear issue number - should be visible at the bottom of the GitHub issue description)

<img width="730" alt="Screenshot 2024-12-16 at 3 50 42 PM" src="https://github.com/user-attachments/assets/2658acc9-1233-4d42-b45a-e9a0463700c7" />

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox.
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works.

2024-12-16 17:32 UTC, Praashh requested changes
Unit tests are failing can we fix this?

2024-12-17 09:13 UTC, kart1ka commented
> Unit tests are failing can we fix this?

done.

2024-12-31 10:40 UTC, kart1ka commented
Hey @Praashh 
Just checking on the status of this PR.
Do let me know if any changes need to be made.
Thanks.

2025-01-06 15:18 UTC, Praashh commented
> Hey @Praashh Just checking on the status of this PR. Do let me know if any changes need to be made. Thanks.

Hey Can you please share a loom of the fix 🙏

2025-01-06 20:55 UTC, Praashh approved these changes
LGTM!!

2025-01-10 14:55 UTC, merged