fix: meeting url ics attachment
calcom/cal.com pull request #18298
Opened 2024-12-20 13:40 UTC by VK-RED

## What does this PR do?

Fixes Broken Meeting Link in Location field

- Refs #18194 

### Screenshots

#### Google Meet
![Screenshot from 2024-12-20 19-03-32](https://github.com/user-attachments/assets/459c7792-ad24-47e5-a7d7-4be4f9868c72)

#### Discord
![Screenshot from 2024-12-20 19-03-42](https://github.com/user-attachments/assets/4ebc890c-274d-4456-8507-90bd9b9df17d)

#### Zoom
![Screenshot from 2024-12-20 19-04-14](https://github.com/user-attachments/assets/7466e3d1-3c66-46be-968e-0589e2f50280)

## Mandatory Tasks (DO NOT REMOVE)

- [ ] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [ ] I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox.
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works.

2024-12-21 04:27 UTC, Praashh requested changes
Can you attach a loom for the fix ??

2024-12-23 11:13 UTC, VK-RED commented
Since the email might receive after a quite long time, attaching the screenshots ..

### Screenshots

![image](https://github.com/user-attachments/assets/5d28fd0a-fcf1-46a3-9751-905988e58c6d)
![image](https://github.com/user-attachments/assets/75295d52-a5c9-4702-8579-dfc4dde53f9f)

2024-12-23 13:47 UTC, Praashh commented on packages/lib/CalEventParser.ts
Don't we need null check for calEvent ?

2024-12-23 13:58 UTC, VK-RED commented on packages/lib/CalEventParser.ts
calEvent is not nullable right ??

2024-12-31 02:11 UTC, VK-RED commented
Gentle Reminder ..

2024-12-31 05:21 UTC, Praashh commented
> Gentle Reminder ..

will give it a final touch 🙏

2025-01-06 20:54 UTC, Praashh commented
Hey @VK-RED can you fix the title as well https://github.com/calcom/cal.com/issues/18194#issuecomment-2557091543 and also please add a loom video.

2025-01-07 03:50 UTC, VK-RED commented
Hey @Praashh tried multiple times and  I was not able to reproduce the title for some reason. Like I mentioned earlier the user will receive emails after quite sometime, so attached the screenshots above .

2025-01-07 04:29 UTC, Praashh commented
> Hey @Praashh tried multiple times and I was not able to reproduce the title for some reason. Like I mentioned earlier the user will receive emails after quite sometime, so attached the screenshots above .

Hey, the current solution doesn’t seem correct for the title, as the customer already mentioned in the thread.  

We need this ASAP, so please let me know if there’s any blocker 🙏 .

2025-01-08 15:01 UTC, Praashh commented
Closing it as incomplete PR 🙏 , feel free to make another one.

2025-01-16 02:35 UTC, rowansc1 commented
This is a MR which sound like it's solves #18952. Would be great to have this sorted :)

2025-01-16 12:45 UTC, nikwen commented
@Praashh Is there any progress on a fix?

I think it could make sense to get @VK-RED's PR in to fix half of the issue. Then another (maybe similar?) PR could fix the title.

2025-01-16 17:36 UTC, rowansc1 commented
Thank you very much! Will be great to have this issue solved :)

2025-01-31 00:31 UTC, nikwen commented
Any chance to breathe fresh life into the PR? :)

2025-01-31 00:32 UTC, rowansc1 commented
Any chance to update this? Would love to see this completed if possible :) 

Sadly I can't contribute myself, but I would if I could!

2025-02-16 00:29 UTC, rowansc1 commented
Bumping MR

2025-02-17 08:28 UTC, nikwen commented
Would also love to see this fixed!

2025-02-24 16:42 UTC, anikdhabal commented on packages/lib/CalEventParser.ts
> +
But I don't think we are passing metadata here?

2025-02-24 17:04 UTC, anikdhabal commented
@VK-RED thanks for your work man. But i am working on a fix that will resolve both the issue mentioned by @nikwen

2025-02-24 17:04 UTC, closed without merging

2025-02-24 17:14 UTC, nikwen commented
Thank you, @anikdhabal and @VK-RED!

@anikdhabal If you have trouble reproducing the issue, please let me know. Also happy to jump on a call and walk you through what I do to reproduce it.

2025-02-24 17:15 UTC, rowansc1 commented
Great to hear @anikdhabal! Do you think that it'll also solve #18259? I'd assume so as they seem related :) 

Thanks for everyone's work!

2025-02-24 17:17 UTC, anikdhabal commented
@nikwen @rowansc1 Thanks for your help. Looking forward to it🙏