Team billing downgrader
calcom/cal.com pull request #1830
Opened 2022-02-12 01:39 UTC by jamiepine

1. be peer or bailey
2. go to https://cal.com/api/admin/downgrade in the browser

<img width="680" alt="CleanShot 2022-02-11 at 16 57 56@2x" src="https://user-images.githubusercontent.com/32987599/153691188-3bbefe5e-1ef3-401b-ba45-59c2ced3fa11.png">

This will run a downgrade function that will downgrade all members with the following conditions:
- member is not sponsored by another team
- member is not a team owner
- member does not have an active Stripe subscription

2022-02-12 01:57 UTC, PeerRich commented
@baileypumfleet can you take care of this tomorrow?🙏

2022-02-15 10:40 UTC, emrysal approved these changes
This will work, so LGTM

2022-02-15 15:57 UTC, zomars requested changes

2022-02-15 16:01 UTC, jamiepine commented
Forgot to comment: going to scrap this an upgrade existing cron job

2022-02-15 16:01 UTC, closed without merging