feat: apply full width automatically for DataTable
calcom/cal.com pull request #18357
Opened 2024-12-23 16:10 UTC by eunjae-lee

## What does this PR do?

This PR improves DataTable to fill the full width.

### Details

The way we calculate the default width of columns in DataTable:

1. Use explicitly given `size` values as a part of ColumnDef. Example: https://github.com/calcom/cal.com/blob/d71b9e23785be9bdde4573543820fa625e10a841/packages/features/users/components/UserTable/UserListTable.tsx#L203
2. Rely on `getSize()` function and its default value (https://tanstack.com/table/latest/docs/api/features/column-sizing#getsize)

When browser's width is too large or there is not enough columns, the DataTable doesn't fill the full width. It used to do so, but not anymore since we've applied `flex` to `<TableRow />` for the following reasons:
1. To enable pinned columns (on the right side)
2. To enable column resizing

This PR fixes the logic to calculate the column widths by increasing them a bit more if the calculated total widths doesn't fill the container's clientWidth. They are also re-calculated as browser resizes.

## Mandatory Tasks (DO NOT REMOVE)

- [ ] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [ ] I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox.
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

- Are there environment variables that should be set?
- What are the minimal test data to have?
- What is expected (happy path) to have (input and output)?
- Any other important info that could help to test that PR

## Checklist

- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my changes generate no new warnings

2024-12-24 16:30 UTC, eunjae-lee commented on packages/features/data-table/components/DataTable.tsx
> +  const columnSizingVars = useColumnSizingVars({ table });
extracted as a separate file for readability

2024-12-24 16:30 UTC, eunjae-lee commented on packages/features/users/components/UserTable/UserListTable.tsx
> +  if (!isSuccessAttributes) {
this is to avoid flickering (attributes are fetched at the similar timing as the table data, anyway)

2025-01-01 13:27 UTC, Udit-takkar reviewed
https://github.com/user-attachments/assets/784ed9bc-f574-4cbb-a20f-786364925230

In mobile view shouldn't all columns be horizontally scrollable?

2025-01-01 13:27 UTC, Udit-takkar requested changes
Merge conflicts

2025-01-02 10:12 UTC, eunjae-lee commented
> Screen.Recording.2025-01-01.at.6.56.26.PM.mov 
> 
> In mobile view shouldn't all columns be horizontally scrollable?

Hey @Udit-takkar , that's a good point. Currently the member column is pinned. I'll think about how/when to disable pinning feature for small viewports, and apply the change here soon.

2025-01-02 14:10 UTC, Udit-takkar approved these changes

2025-01-02 14:32 UTC, merged