feat: Setting for rescheduling past bookings
calcom/cal.com pull request #18358
Opened 2024-12-23 17:00 UTC by Amit91848

## What does this PR do?

- Fixes #18356
- Fixes CAL-4948

https://github.com/user-attachments/assets/1690ed63-3485-4569-8f47-9491e84f8a69

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox.
- [x] I confirm automated tests are in place that prove my fix is effective or that my feature works.

2024-12-23 17:31 UTC, anikdhabal approved these changes
Looking good

2024-12-23 17:39 UTC, anikdhabal commented on packages/prisma/migrations/20241223163249_allow_rescheduling_past_booking_setting/migration.sql
> +ALTER TABLE "EventType" ADD COLUMN     "alllowReschedulingPastBookings" BOOLEAN NOT NULL DEFAULT false;
Fix the file name

2024-12-23 17:40 UTC, anikdhabal commented on apps/web/components/booking/BookingListItem.tsx
> +    ...(isBookingInPast && !booking.eventType.alllowReschedulingPastBookings
Let's add e2e test to verify this functionality

2024-12-23 17:40 UTC, anikdhabal requested changes
Left comment

2025-01-06 07:06 UTC, Amit91848 commented on apps/web/components/booking/BookingListItem.tsx
> +    ...(isBookingInPast && !booking.eventType.alllowReschedulingPastBookings
Done

2025-01-06 07:07 UTC, Amit91848 commented on packages/prisma/migrations/20241223163249_allow_rescheduling_past_booking_setting/migration.sql
> +ALTER TABLE "EventType" ADD COLUMN     "alllowReschedulingPastBookings" BOOLEAN NOT NULL DEFAULT false;
Not sure wdym?

2025-01-08 14:32 UTC, anikdhabal approved these changes, later dismissed

2025-01-08 14:48 UTC, anikdhabal commented
@Amit91848 type checks and e2e tests fails. Let's not add tests. It was fine until this commit https://github.com/calcom/cal.com/pull/18358/commits/e5387ce87d8465dc3fdb61ba42c2801a0c49c8b7. Let's jump to that or pls fix accordingly

2025-01-28 19:22 UTC, CarinaWolli approved these changes
Fixed the typo, everything passes now 🙏

2025-01-28 19:25 UTC, merged