Add 'monobot' web application into cal.com app-store.
calcom/cal.com pull request #18355
Opened 2024-12-23 13:36 UTC by yuriisilkov1986

## What does this PR do?

- This pool request includes adding a 'monobot' web application to "packages/app-store" directory, in accordance with the all yours requirements.

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). N/A
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

- "Monobot.ai" is production ready application. With it you can create AI Agents that Work as a Customer Service.
- Last "Monobot.ai" updates includes cal.com integration.
- Our AI agents can use the "cal.com" service to create/update/delete calendar events.
- In order to check cal.com integration:
   1. Sign In to "monobot.ai" app. (https://monobot.ai/sign-in) (username: monobot.acceptance2@gmail.com, password: password2)
   3. Proceed to "AI Agents" list. 
   4. Proceed to "Barber Shop" ai assistant configuration. (AI assistant with name: "Barber Shop" already created for the tests)
   5. Proceed to Tool tab.
   6. Current ai assistant already have preconfigured tools for various purposes related to cal.com.
   7. All that remains to be done is add an action configuration mandatory needs: **"API Key", "Event Type ID"**

## Checklist

- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my changes generate no new warnings

2024-12-23 13:36 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/calcom/cal.com?pullRequest=18355) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/calcom/cal.com?pullRequest=18355) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/calcom/cal.com?pullRequest=18355) it.</sub>

2024-12-23 13:54 UTC, Praashh commented on packages/app-store/monobot/api/add.ts
> +    url: "https://monobot.ai/?referralId=cal.com",
it's not good to use url directly, instead we can use it as constant variable

2024-12-24 05:57 UTC, Praashh commented on yarn.lock
can you uncommit `yarn.lock` file ?

2024-12-24 05:57 UTC, Praashh requested changes
We also need zod-validation for fields, similar we have for other apps.

2025-01-07 10:25 UTC, yuriisilkov1986 commented
Hello, sorry for delay!!
Can you please clarify what is required from my side in order to merge my branch with the master?
It is very important for us to place our app on your app-store))

Thank you in advance!

2025-01-07 16:17 UTC, closed without merging