fix: Description not rendered as html in select event types screen when installing an app
calcom/cal.com pull request #18354
Opened 2024-12-23 12:28 UTC by asadath1395

## What does this PR do?

Description not rendered properly in select event types screen if it has html elements when installing an app

Issue:

![Screenshot 2024-12-23 at 5 43 32 PM](https://github.com/user-attachments/assets/5b4eecb3-5f82-4c1e-8a72-1c3a782615a6)

After solution:

![Screenshot 2024-12-23 at 5 46 54 PM](https://github.com/user-attachments/assets/4bab8262-4852-4913-bdf7-bac9ef00a898)

**Note: Right now there is a trimming happening which is similar behaviour we have in `/event-types` screen**

## Mandatory Tasks (DO NOT REMOVE)

- [ ] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [ ] I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox.
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

- Create an event with a description having links, bold or italic components
- Install any app where selecting event type screen comes like google meet
- Verify the html is properly rendered similar to other places like event types screen

2024-12-23 14:10 UTC, Praashh reviewed
It’s working fine for me. On which app is it not rendering HTML? @asadath1395

2024-12-23 15:17 UTC, anikdhabal commented on apps/web/components/apps/installation/EventTypesStepCard.tsx
> +import { markdownToSafeHTML } from "@calcom/lib/markdownToSafeHTML";
Don't we need to use markdownToSafeHTMLClient here? Could you please verify? Apart from this, it's okay

2024-12-23 16:23 UTC, asadath1395 commented
> It’s working fine for me. On which app is it not rendering HTML? @asadath1395

Can you share screenshot? I was trying with google meet but the issue should appear in many apps. It is not an issue with any apps but soon after installing the app we ask users to select event types to which we want to install the app.

2024-12-23 16:29 UTC, Praashh commented
<img width="562" alt="Screenshot 2024-12-23 at 9 59 21 PM" src="https://github.com/user-attachments/assets/22a6ccab-4e80-401b-a4ab-cc788994c0a1" />
 you can see here @asadath1395

2024-12-23 16:31 UTC, asadath1395 commented
> you can see here @asadath1395, am also trying for gmeet. <img alt="Screenshot 2024-12-23 at 9 59 21 PM" width="562" src="https://private-user-images.githubusercontent.com/99237795/398210385-22a6ccab-4e80-401b-a4ab-cc788994c0a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5NzE3MjMsIm5iZiI6MTczNDk3MTQyMywicGF0aCI6Ii85OTIzNzc5NS8zOTgyMTAzODUtMjJhNmNjYWItNGU4MC00MDFiLWE0YWItY2M3ODg5OTRjMGExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIzVDE2MzAyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5ZmU2MzFkOTFiNDUzYjBkNzI4NTY3YjMyMTBiYWYxNWVmYjdlODRjOTYzNWI3ZmRhMTFhMWZlNTU4ZmE3NzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.U9MN8WQmO_v25j36utOxBPfi6IczFm2P-85PWH0l_pU">

You didn't add any description to the event

2024-12-23 16:36 UTC, Praashh commented
@asadath1395 can you see 
<img width="549" alt="Screenshot 2024-12-23 at 10 06 09 PM" src="https://github.com/user-attachments/assets/8a74d87b-0acc-4ade-a0a8-e3584b039c5a" />

2024-12-24 05:06 UTC, asadath1395 commented
@Praashh You have a simple description, the description should contain links, bold or similar elements to reproduce the issue

2024-12-26 16:45 UTC, Praashh requested changes, later dismissed
left comments for https://github.com/calcom/cal.com/pull/18354/files#r1895860074

2025-01-08 14:36 UTC, anikdhabal approved these changes

2025-01-08 15:03 UTC, merged