perf: Move CRM event creation to tasker
calcom/cal.com pull request #18370
Opened 2024-12-25 00:23 UTC by joeauyeung

## What does this PR do?

- Fixes #XXXX (GitHub issue number)
- Fixes CAL-XXXX (Linear issue number - should be visible at the bottom of the GitHub issue description)

## Mandatory Tasks (DO NOT REMOVE)

- [ ] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [ ] I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox.
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

- Are there environment variables that should be set?
- What are the minimal test data to have?
- What is expected (happy path) to have (input and output)?
- Any other important info that could help to test that PR

## Checklist

- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my changes generate no new warnings

2025-01-10 21:16 UTC, joeauyeung commented on packages/features/tasker/tasks/crm/createCRMEvent.ts
Since the tasker endpoint doesn't have context around the booking we need to create it and pass it to the CRM service.

A lot of the methods are reused from `handleNewBooking`

2025-01-10 21:16 UTC, joeauyeung commented on packages/features/tasker/tasks/crm/lib/buildCalendarEvent.ts
Generate the calendarEvent from the bookingUid. Hoping to reuse this in other tasks.

2025-01-10 21:16 UTC, joeauyeung commented on packages/features/tasker/tasks/crm/schema.ts
> +export const createCRMEventSchema = z.object({
Ideally we only pass the bookingUid from `handleNewBooking` to the tasker. This helps decouple the two services.

2025-01-14 17:39 UTC, zomars commented
Reviewing..

2025-01-14 17:47 UTC, zomars commented on packages/features/tasker/tasks/crm/createCRMEvent.ts
> +export async function createCRMEvent(payload: string): Promise<void> {
We should keep the original payload here, the parsing should happen on the task itself.

2025-01-14 17:54 UTC, zomars commented on .env.example
> +TASKER_ENABLE_CRM_EVENT_CREATION=0
Where are we actually using this variable? Can't seem o find it.

2025-01-14 19:58 UTC, joeauyeung commented on packages/features/tasker/tasks/crm/createCRMEvent.ts
> +export async function createCRMEvent(payload: string): Promise<void> {
I'm not sure what you mean here. The payload is just the `bookingUid`

2025-01-14 20:07 UTC, joeauyeung commented
I also reverted the `yarn.lock` changes since the jsforce package upgrade was done in another PR

2025-01-14 23:16 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/calcom/cal.com?pullRequest=18370) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/calcom/cal.com?pullRequest=18370) before we can accept your contribution.<br/>**8** out of **9** committers have signed the CLA.<br/><br/>:white_check_mark: Udit-takkar<br/>:white_check_mark: joeauyeung<br/>:white_check_mark: emrysal<br/>:white_check_mark: nizzyabi<br/>:white_check_mark: keithwillcode<br/>:white_check_mark: hbjORbj<br/>:white_check_mark: ThyMinimalDev<br/>:white_check_mark: kart1ka<br/>:x: calcom-bot<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/calcom/cal.com?pullRequest=18370) it.</sub>

2025-01-14 23:17 UTC, zomars commented on packages/features/tasker/tasks/crm/createCRMEvent.ts
> +export async function createCRMEvent(payload: string): Promise<void> {
Mostly [this](https://github.com/calcom/cal.com/pull/18370/commits/a26100129eb7ea6f16a9f0440f099ed2cc5bbd25).

2025-01-14 23:23 UTC, zomars commented on packages/core/EventManager.ts
> +        await CRMScheduler.createEvent({ bookingUid: event.uid });
Since this is inside a credentials loop, wouldn't this create an event per each credential? How to do we know to which credential create with only the  bookingUid?

2025-01-14 23:28 UTC, zomars requested changes
left some comments 🙏🏽

2025-01-14 23:28 UTC, zomars commented on packages/core/EventManager.ts
> +        await CRMScheduler.createEvent({ bookingUid: event.uid });
Is it possible to have two CRM-type credentials installed and due to this get this scheduled two times? Resulting in duplicate events for both credentials? Do we have some kind of Idempotency logic in the createCRMEvent task?

2025-01-15 03:34 UTC, joeauyeung commented on packages/core/EventManager.ts
> +        await CRMScheduler.createEvent({ bookingUid: event.uid });
The credentials are passed to the `EventManager` when it's initialized. The credentials fetched via `getAllCredentials` which filters for only enabled CRM credentials on the event type.

2025-01-16 16:30 UTC, zomars commented on packages/core/EventManager.ts
> +        await CRMScheduler.createEvent({ bookingUid: event.uid });
But even then, let's say I had both salesforce and hubspot installed (which both are CRM apps). This will generate duplicate data for both of them.

2025-01-16 16:38 UTC, joeauyeung commented on packages/core/EventManager.ts
> +        await CRMScheduler.createEvent({ bookingUid: event.uid });
You can have multiple CRM apps installed but only enabled CRM credentials for that specific event type are passed to the EventManager and iterated through in this loop.

The scenario you're describing did happen a long time ago but I refactored it in 2024 so we weren't iterating over every installed CRM app.

2025-01-16 18:21 UTC, zomars approved these changes

2025-01-17 03:07 UTC, merged