feat: Info lost when navigating without warning routing form
calcom/cal.com pull request #18386
Opened 2024-12-27 14:27 UTC by Amit91848

## What does this PR do?

- Fixes #17300
- Fixes CAL-4596

https://github.com/user-attachments/assets/e0f4d24a-bfca-4399-8707-f31734973699

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox.
- [x] I confirm automated tests are in place that prove my fix is effective or that my feature works.

2024-12-27 18:09 UTC, Praashh approved these changes
working fine, LGTM!!

2024-12-27 18:13 UTC, Praashh commented on packages/app-store/routing-forms/components/InfoLostWarningDialog.tsx
> +            {t("leave_without_saving")}
can we optimize the re-render using useCallback on onClick functions @Amit91848 ?

2025-01-02 05:15 UTC, Praashh commented
@Amit91848 can you please resolve merge conflicts ?

2025-01-02 05:15 UTC, Praashh requested changes
Left comments for changes.

2025-01-04 16:20 UTC, Amit91848 commented on packages/app-store/routing-forms/components/InfoLostWarningDialog.tsx
> +            {t("leave_without_saving")}
I think this would just add unnecessary complexity for a very simple function without any significant performance improvement. 

Since onclick function is defined in InfoLostWarningDialog itself and not passed down through props by parent and it is not something computationally expensive, using useCallback is moot.

https://react.dev/reference/react/useCallback#skipping-re-rendering-of-components

2025-01-04 16:20 UTC, Amit91848 commented on packages/app-store/routing-forms/components/InfoLostWarningDialog.tsx
> +            {t("leave_without_saving")}
Lmk if you think differently

2025-01-04 18:28 UTC, Praashh commented on packages/app-store/routing-forms/components/InfoLostWarningDialog.tsx
> +            {t("leave_without_saving")}
alright cool.

2025-01-04 18:30 UTC, Praashh approved these changes
LGTM!! Thank you @Amit91848 🙏 .

2025-01-06 11:19 UTC, merged