chore: bump alby packages
calcom/cal.com pull request #18406
Opened 2024-12-29 04:22 UTC by rolznz

## What does this PR do?

This updates Alby packages used for being able to book paid meetings with lightning.

There is a bug in the previous version of lightning-tools which means invoices cannot be generated for alby accounts connected to self-custodial nodes (such as Alby Hub).

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [N/A] I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox.
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

- Are there environment variables that should be set?
- What are the minimal test data to have?
- What is expected (happy path) to have (input and output)?
- Any other important info that could help to test that PR

## Checklist

- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my changes generate no new warnings

2024-12-29 07:32 UTC, Praashh commented on yarn.lock
can you uncommit `yarn.lock` file ?

2024-12-29 07:44 UTC, Praashh reviewed
can we also have before and after fix recording ?

2024-12-29 13:19 UTC, rolznz commented
> can we also have before and after fix recording ?

I don't have a recording right now, but here is the fix of the error before and afterward, running node from `node_modules/@getalby/lightning-tools/dist` directory.

BEFORE:
```
> const {LightningAddress} = await import("./index.cjs");
undefined
> const ln = new LightningAddress("rolznz@getalby.com");
undefined
> await ln.fetch();
Uncaught TypeError: Cannot use 'in' operator to search for 'customKey' in undefined
```

AFTER
```
> const {LightningAddress} = await import("./index.cjs");
undefined
> const ln = new LightningAddress("rolznz@getalby.com");
undefined
> await ln.fetch();
undefined
```

2024-12-30 14:34 UTC, Praashh approved these changes

2024-12-30 14:34 UTC, Praashh commented
Looks good to me

2025-01-06 10:50 UTC, PeerRich approved these changes, later dismissed

2025-01-06 14:15 UTC, keithwillcode requested changes
Can you please update the yarn.lock file

2025-01-06 14:16 UTC, keithwillcode commented
Build is failing https://github.com/calcom/cal.com/actions/runs/12631167071/job/35193080835?pr=18406#step:5:590

2025-01-14 04:59 UTC, rolznz commented
@keithwillcode why was the PR marked as draft?

2025-02-05 06:35 UTC, keithwillcode commented
> @keithwillcode why was the PR marked as draft?

Because the build is failing and requires changes

2025-02-19 11:41 UTC, anikdhabal commented
@rolznz could you pls update the yarn.lock

2025-02-19 14:42 UTC, rolznz commented on yarn.lock
> +"@calcom/millis-ai@workspace:packages/app-store/millis-ai":
Not sure what this is coming from. I merged `main` into this branch and re-ran `yarn install`

2025-02-21 06:54 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/calcom/cal.com?pullRequest=18406) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/calcom/cal.com?pullRequest=18406) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: rolznz<br/>:x: TusharBhatt1<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/calcom/cal.com?pullRequest=18406) it.</sub>

2025-02-24 14:25 UTC, keithwillcode approved these changes

2025-02-24 14:25 UTC, merged

2025-02-27 08:44 UTC, anikdhabal commented
@rolznz Not related to this, but I found some users unable to successfully make payments through Alby in our app. When I logged the error, I found this:- 
`[ERROR[0m[0m] payment-service:alby Alby: Payment could not be created "TypeError: Cannot use 'in' operator to search for 'customKey' in undefined\n    at /var/task/node_modules/@getalby/lightning-tools/dist/index.cjs:1:11477\n    at t.parseResponse (/var/task/node_modules/@getalby/lightning-tools/dist/index.cjs:1:11851)\n    at /var/task/node_modules/@getalby/lightning-tools/dist/index.cjs:1:6414\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async PaymentService.create (/var/task/apps/web/.next/server/chunks/28435.js:1:4628)\n    at async handlePayment (/var/task/apps/web/.next/server/chunks/57461.js:1:26353)\n`

Can you investigate this?

2025-03-26 06:31 UTC, rolznz commented
Hi @anikdhabal 

This happens if a lightning invoice is requested for an amount outside of the minimum or maximum amount.

Do you have any more info on what was requested?

2025-03-26 06:37 UTC, anikdhabal commented
@rolznz this one
![Screenshot 2025-03-26 120921](https://github.com/user-attachments/assets/c81d698e-6392-43a6-833b-5ec0199d525a)

What does the minimum or maximum amount supported by the recipient's wallet mean?

2025-03-26 06:41 UTC, rolznz commented
@anikdhabal ah, I think the issue is that some users do not run their own node. This is why they have a smaller limit on the amount they can receive.

2025-03-26 06:43 UTC, anikdhabal commented
@rolznz Okay, so how do we fix that?

2025-03-26 06:44 UTC, rolznz commented
@anikdhabal I don't think it can be fixed on the cal.com side. The Alby user will be notified via email and we will ask them to run their own node to remove the limits for receiving payments