feat: refund policies for payment apps
calcom/cal.com pull request #18428
Opened 2024-12-31 08:31 UTC by Amit91848

## What does this PR do?

- Fixes #16858 
- Fixes CAL-4425 
- /claim #16858 

https://github.com/user-attachments/assets/2e7bbeaa-ee19-4dcb-a8c6-2867aa8feb53

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox.
- [x] I confirm automated tests are in place that prove my fix is effective or that my feature works.

2024-12-31 13:21 UTC, Praashh requested changes
Can we have test case for this feature @Amit91848  ?

2025-01-03 04:34 UTC, Praashh requested changes
left comments 🙏

2025-01-06 05:44 UTC, Amit91848 commented on packages/lib/getPaymentAppData.ts
> +export function getPaymentAppData(
Removed default export because it was causing issues while mocking

2025-01-06 05:58 UTC, Praashh approved these changes
LGTM!!

2025-01-06 11:36 UTC, merged