Docs/prisma commands on docs
calcom/cal.com pull request #1875
Opened 2022-02-16 16:44 UTC by miguelnietoa

## What does this PR do?

Refs #1839, #1843, #1872

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## How should this be tested?

- [ ] Test A
- [ ] Test B

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code and corrected any misspellings
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-02-16 17:30 UTC, pumfleet approved these changes

2022-02-18 22:28 UTC, zomars requested changes

2022-02-18 22:28 UTC, zomars commented on apps/docs/pages/self-hosting/upgrade.mdx
> +   yarn start --scope=@calcom/web
Same here:

```suggestion
   yarn build
   yarn start
```

2022-02-21 19:56 UTC, miguelnietoa commented
Hi @zoomars, thanks for reviewing. The requested changes have been applied.

2022-02-21 20:12 UTC, zomars approved these changes
Nice! Thank you for your contribution 🙏

2022-02-21 20:13 UTC, zomars commented
I don't have permissions to update this branch. Please rebase to main so we can marge. 🙏🏽

2022-02-21 20:39 UTC, miguelnietoa commented
> I don't have permissions to update this branch. Please rebase to main so we can marge. 🙏🏽

Done!

2022-02-21 20:47 UTC, merged