Bugfix/login failure due email capitalisation
calcom/cal.com pull request #1884
Opened 2022-02-17 05:15 UTC by voyager163

## What does this PR do?

This code will prevent the email check from failing if the user email contain capitalisation. The current code will result in the user failing the email checks by showing "No Account was found" if the user email contain capitalisation.

## Type of change

- [x]  Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- [x] Application can be tested by using capitalisation email address.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code and corrected any misspellings
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

2022-02-20 00:42 UTC, agustif commented
Sweet and simple, and improves UX, looks goos to me. i think we could safely remove the warning from the README

2022-02-21 04:24 UTC, voyager163 commented
> Sweet and simple, and improves UX, looks goos to me. i think we could safely remove the warning from the README

The issue is that user may still insert capitalisation letters when they insert the user.

2022-02-21 21:20 UTC, agustif commented
> > Sweet and simple, and improves UX, looks goos to me. i think we could safely remove the warning from the README
> 
> 
> 
> The issue is that user may still insert capitalisation letters when they insert the user and that is how i found this issue.
> 
> 

Maybe we need to apply a sinilar lowercasing in our private signup will look into that what do yo think @PeerRich

2022-02-21 22:21 UTC, PeerRich commented
> > > Sweet and simple, and improves UX, looks goos to me. i think we could safely remove the warning from the README
> > 
> > 
> > 
> > The issue is that user may still insert capitalisation letters when they insert the user and that is how i found this issue.
> > 
> > 
> 
> Maybe we need to apply a similar lowercasing in our private signup will look into that what do yo think @PeerRich 

likely. wanna check?

2022-02-22 04:27 UTC, voyager163 commented
> > > > Sweet and simple, and improves UX, looks goos to me. i think we could safely remove the warning from the README
> > > 
> > > 
> > > The issue is that user may still insert capitalisation letters when they insert the user and that is how i found this issue.
> > 
> > 
> > Maybe we need to apply a similar lowercasing in our private signup will look into that what do yo think @PeerRich
> 
> likely. wanna check?

Haha, i wanted to help to check but i do not think i have access to the codes. Let me know if you need me to work on it.

2022-02-23 02:34 UTC, agustif commented
> > > > > Sweet and simple, and improves UX, looks goos to me. i think we could safely remove the warning from the README
> 
> > > > 
> 
> > > > 
> 
> > > > The issue is that user may still insert capitalisation letters when they insert the user and that is how i found this issue.
> 
> > > 
> 
> > > 
> 
> > > Maybe we need to apply a similar lowercasing in our private signup will look into that what do yo think @PeerRich
> 
> > 
> 
> > likely. wanna check?
> 
> 
> 
> Haha, i wanted to help to check but i do not think i have access to the codes. Let me know if you need me to work on it.
Thank you!
I am already working on improving the signup. 

I will make sure to make a fix for this so registration will cover lowercasing soon 🙏

2022-02-23 16:11 UTC, voyager163 commented
> Thank you! I am already working on improving the signup.
> 
> I will make sure to make a fix for this so registration will cover lowercasing soon 🙏

No worries man, after this, i will see the rest of the bugs, to see how to close it for you all.

2022-02-23 23:50 UTC, baileypumfleet requested changes

2022-03-12 07:09 UTC, voyager163 commented on README.md
> +   > :warning: **Please do not use capitalisation in your email**
Okie. i will remove it.

2022-03-14 11:44 UTC, baileypumfleet approved these changes

2022-03-14 11:45 UTC, merged