docs: add contributing guide
calcom/cal.com pull request #2021
Opened 2022-03-01 15:15 UTC by imkrunal

## What does this PR do?

Adds contribution guide to docs.cal.com

Fixes # (issue)
#1944 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## How should this be tested?

Open docs site and go to `/contributing`. Contribution guide should be visible.

2022-03-01 19:18 UTC, baileypumfleet requested changes
This is really great! Left a couple of minor changes here, but otherwise, this is good to go :) Thank you

2022-03-01 19:18 UTC, baileypumfleet commented on apps/docs/pages/contributing.mdx
> +branch are tagged into a release biweekly.
```suggestion
branch are tagged into a release monthly.
```

2022-03-01 19:18 UTC, baileypumfleet commented on apps/docs/pages/contributing.mdx
> +More info on how to add new tests comming soon.
```suggestion
More info on how to add new tests coming soon.
```

2022-03-01 19:27 UTC, baileypumfleet approved these changes

2022-03-01 19:27 UTC, merged

2022-03-02 04:21 UTC, imkrunal commented
@baileypumfleet Those changes need to be done in main `CONTRIBUTING.md` as well right?

2022-03-02 12:27 UTC, baileypumfleet commented
> @baileypumfleet Those changes need to be done in main `CONTRIBUTING.md` as well right?

Yes good point

2022-03-02 17:56 UTC, imkrunal commented
@baileypumfleet #2036