Allow Team Event editing by the person who created it
calcom/cal.com pull request #2066
Opened 2022-03-05 06:38 UTC by hariombalhara

## What does this PR do?

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

- [ ] Test A
- [ ] Test B

## Checklist

- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't performed a self-review of my own code and corrected any misspellings
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my PR needs changes to the documentation
- I haven't checked if my changes generate no new warnings
- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

2022-03-05 09:42 UTC, hariombalhara commented on packages/prisma/migrations/20220305052238_adds_event_creator/migration.sql
> +ALTER INDEX "Booking.uid_unique" RENAME TO "Booking_uid_key";
Not sure why these indices renaming happened. This is automatically generated

2022-03-15 16:01 UTC, baileypumfleet reviewed
Upon testing, this seems to work fine. However I did not test what happens when this migration is run on top of existing event types, which will not have a creator ID set. Does this prevent everyone except admins from editing it?

2022-03-15 16:18 UTC, agustif commented on apps/web/next.config.js
> +console.warn("VARS", process.env.PLAYWRIGHT_SECRET);
Maybe we could copy userId -> creatorId on the migration, not sure if it would bring some edge cases like events not created by current owner maybe?

2022-03-15 16:18 UTC, agustif commented
> Upon testing, this seems to work fine. However I did not test what happens when this migration is run on top of existing event types, which will not have a creator ID set. Does this prevent everyone except admins from editing it?

Maybe we could copy userId -> creatorId on the migration, not sure if it would bring some edge cases like events not created by current owner maybe?

The rest looks good!

2022-03-15 16:19 UTC, agustif commented on apps/web/pages/api/auth/forgot-password.ts
> +    console.log("FORGOT PASSWORD", process.env.PLAYWRIGHT_SECRET);
We could add some no-console eslint rules, I always have to ctrl-f and double check before committing lol

2022-03-15 16:21 UTC, agustif requested changes
Any idea why the zod/webhook empty file is on the file changes?

<img width="954" alt="image" src="https://user-images.githubusercontent.com/6601142/158424161-357d635e-725d-4f70-a174-797fce8d303e.png">
I think @zomars fixed the zod auto-generated files being picked up.

2022-03-16 04:43 UTC, hariombalhara commented
> > Upon testing, this seems to work fine. However I did not test what happens when this migration is run on top of existing event types, which will not have a creator ID set. Does this prevent everyone except admins from editing it?
> 
> Maybe we could copy userId -> creatorId on the migration, not sure if it would bring some edge cases like events not created by current owner maybe?
> 
> The rest looks good!

As per my understanding userId is not set now. Only `users` is set and that actually has a list of attendees for the event type. So, there is no information in PG that can reliably tell us the creator of the event.

I have removed accidental code changes and this PR is ready for review again

2022-04-14 22:06 UTC, agustif commented
Hey @hariombalhara code looks good to me. 
Cant we gent the event type owner from userId which lives in db in user event type relation table?

From schema.prisma

relation("user_eventtype")
  userId                  Int?

2022-04-14 22:18 UTC, agustif reviewed
LGTM, but I think userId should be available in eventType and might be === to new creatorId? Maybe we can migrate the data from there

2022-04-21 12:03 UTC, hariombalhara commented
@agustif regarding that userId thing, I created a new event type and checked DB studio and this is what I saw
Notice, the last one USERIDTEST. It doesn't have `userId` set. It has users though.

![image](https://user-images.githubusercontent.com/1780212/164454093-f1496ff2-216a-41a8-8a0c-7a6fd20dec86.png)

2022-05-16 17:47 UTC, zomars commented
@hariombalhara @agustif Currently we have a many-to-many relationship from users and event types. Hence why we don't have `userId` set. I think this is being used for team events? I could be wrong tho. Tagging @emrysal to see if he knows more about this data model.

2022-05-17 10:22 UTC, hariombalhara commented
@zomars This has been fixed recently in https://github.com/calcom/cal.com/pull/2599

Now I can see userId, I would change the code to use that instead of creatorId
<img width="1457" alt="Screenshot 2022-05-17 at 3 48 41 PM" src="https://user-images.githubusercontent.com/1780212/168789273-31076fe0-9950-4126-93cc-ba05d768bba3.png">

2022-05-17 13:29 UTC, hariombalhara commented
Updated the PR as now userId is being set. It was missing for team event, fixed that as well. I am not sure why specific check for team event was added earlier.

2022-05-17 14:43 UTC, zomars commented
> Updated the PR as now userId is being set. It was missing for team event, fixed that as well. I am not sure why specific check for team event was added earlier.


Does this means that this fix won’t apply to already created records?

2022-05-30 03:20 UTC, closed without merging