Feature: Support redirecting to an external URL on successful booking
calcom/cal.com pull request #2087
Opened 2022-03-08 10:16 UTC by hariombalhara

## What does this PR do?

Fixes #1457

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## How should this be tested?

- [x]Book an existing event and see that the user is redirected to /success page for  team Event, Paid Event, and a normal event
- [x] Create a new event[Event2] and see that user is redirected to /success page team Event, Paid Event, and a normal event
- [x] Update Redirect URL to and see that now onwards on successful booking, user is redirected accordingly for Event, Paid Event and a normal Event. 
- [x] Make sure that only a valid URL is accepted.

## Checklist

- I haven't checked if my changes generate no new warnings
- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

2022-03-09 14:46 UTC, baileypumfleet commented on packages/prisma/migrations/20220308100145_/migration.sql
> +ALTER INDEX "DestinationCalendar.bookingId_unique" RENAME TO "DestinationCalendar_bookingId_key";
For some reason, Prisma keeps generating these ALTER INDEX lines, it happened on my last PR

2022-03-09 17:56 UTC, alannnc approved these changes
It worked great! The only thing I saw was this, it leaves successRedirectUrl with a lot of url query params. Should we clear all of this info from the final url?
![image](https://user-images.githubusercontent.com/4461358/157501778-7b314c7d-5005-4df2-bd26-cf3a46658245.png)
@zomars @baileypumfleet

2022-03-09 19:30 UTC, zomars commented on packages/prisma/migrations/20220308100145_/migration.sql
> +ALTER INDEX "users.username_unique" RENAME TO "users_username_key";
```suggestion
```

2022-03-09 21:54 UTC, baileypumfleet approved these changes

2022-03-10 03:45 UTC, hariombalhara commented
> It worked great! It only leaves successRedirectUrl with a lot of url query params. Should we clear all of this info from the final url? ![image](https://user-images.githubusercontent.com/4461358/157501778-7b314c7d-5005-4df2-bd26-cf3a46658245.png) @zomars @baileypumfleet
> 
I believe all this info should be kept as is so that whatever info we need to show that success page, owner can also use that to build a very customized success message using that. It also means that we should very well document those query parms


> Also can we improve a hint or a label here that says https:// in the url its required? I would change "Redirect on successful booking" to "Redirect on successful booking(https)" ![image](https://user-images.githubusercontent.com/4461358/157502616-504c5429-6164-4279-bf4a-496a9fc18221.png)

Updated placeholder for the hint ![Uploading Screenshot 2022-03-10 at 9.12.29 AM.png…]()

2022-03-10 16:14 UTC, agustif commented
Wouldn't this new feature allow any bad actor redirect a booking user to any badUrl after booking? Should we at least add some frontend notice that you're getting out of [cal.com](http://cal.com/)?

2022-03-10 16:21 UTC, zomars requested changes, later dismissed
I'm blocking this PR for a little bit more so we can address these Qs:

- Can this be used maliciously?
- Wouldn't this reopen a previously fixed vulnerability when you can use Cal to redirect to a malicious site?
- If that's the case how could we handle that?
- And lastly how does the redirect going to work for embedded calendars? (current frames)

2022-03-13 12:47 UTC, PeerRich commented
> I'm blocking this PR for a little bit more so we can address these Qs:
> 
> * Can this be used maliciously?
> * Wouldn't this reopen a previously fixed vulnerability when you can use Cal to redirect to a malicious site?
> * If that's the case how could we handle that?
> * And lastly how does the redirect going to work for embedded calendars? (current frames)

I agree with your assessment. We also want to show the success page at least for a couple seconds. I recommend doing this:

<img width="1467" alt="image" src="https://user-images.githubusercontent.com/8019099/158059993-cbcb0357-2551-4aed-b9fb-c9cb1808ffe8.png">

```
<div class="fixed top-4 inset-x-0 pb-2 sm:pb-5 z-30" style="">
  <div class="max-w-7xl mx-auto px-2 sm:px-6 lg:px-8">
    <div class="p-2 rounded-sm bg-red-600 shadow-lg sm:p-3 bg-green-500">
      <div class="flex items-center justify-between flex-wrap">
        <div class="w-0 flex-1 flex items-center">
          <p class="ml-3 font-medium text-white truncate">
            <span class="md:hidden">Redirecting ...</span>
            <span class="hidden md:inline">You are being redirected to https://external.website.com in 9 seconds.</span>
          </p>
        </div>
        <div class="order-3 mt-2 flex-shrink-0 w-full sm:order-2 sm:mt-0 sm:w-auto">
          <a href="#" class="flex items-center justify-center px-4 py-2 border border-transparent rounded-sm shadow-sm text-sm font-medium text-indigo-600 bg-white hover:bg-indigo-50">Continue</a>
        </div>
        <div class="order-2 flex-shrink-0 sm:order-3 sm:ml-2">
          <button type="button" class="-mr-1 flex p-2 rounded-md hover:bg-indigo-500 focus:outline-none focus:ring-2 focus:ring-white">
            <span class="sr-only">Dismiss</span>
            <!-- Heroicon name: outline/x -->
            <svg class="h-6 w-6 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"></path>
            </svg>
          </button>
        </div>
      </div>
    </div>
  </div>
</div>
```

2022-03-13 12:48 UTC, PeerRich commented
this was also planned as a PRO feature, which means it needs to be in `/ee/` and disabled for FREE (show the same badge as we do for custom theme)

2022-03-13 12:50 UTC, PeerRich requested changes
https://github.com/calcom/cal.com/pull/2087#issuecomment-1066094263

2022-03-13 13:32 UTC, PeerRich commented
another problem: when embedding in an iframe, it'll show the new redirect in an iframe.

we need to open in a new tab (until we have the script embed)

2022-03-14 09:24 UTC, hariombalhara commented
> another problem: when embedding in an iframe, it'll show the new redirect in an iframe.
> 
> we need to open in a new tab (until we have the script embed)

Attempt to opening a new tab on timer would be blocked by browser. For now I have opened in the same tab but in the top frame.

2022-03-14 14:12 UTC, hariombalhara commented
@PeerRich @zomars  Some testing pending otherwise it is ready for review with the suggested changes.

2022-03-14 19:25 UTC, alannnc commented
@hariombalhara  
It says I'm missing this lib function 
`import { isSuccessRedirectAvailable } from "@lib/isSuccessRedirectAvailable";`
Couldn’t find any isSuccessRedirectAvailable declaration

2022-03-14 19:26 UTC, alannnc requested changes, later dismissed
isSuccessRedirectAvailable function declaration

2022-03-15 01:55 UTC, hariombalhara commented
> isSuccessRedirectAvailable function declaration

Oops! Forgot to commit it

2022-03-15 04:57 UTC, hariombalhara commented
@alannnc Sorry about that missing file error. 
Testing is complete now from my side. Added manual tests that I have done.

2022-03-15 10:41 UTC, lharries commented
Excited to see this PR! 

We are currently working on a feature where we want to redirect the page based on a Cal.com booking being completed within an iFrame.

Does this PR enable an iFrame to trigger the redirection of the top level page? If not, I'd love to request it as a feature (ideally as part of this PR if not out of scope).

As a side point - the embedded Calendly iFrame uses `window.postMessage()` which gives the developer lots of flexibility including using dynamic success URLs and triggering appropriate analytics. Here's a link to how [Calendly does it](https://help.calendly.com/hc/en-us/articles/223147027-Embed-options-overview?tab=advanced#6)

<details>
<summary>Image of relevant Calendly docs</summary>
<img width="760" alt="Screenshot Embed options overview – Help Center (Google Chrome) 2022-03-15 at 10 35" src="https://user-images.githubusercontent.com/22766134/158359612-c927794d-af45-4059-94c5-f107ffab4429.png">
</details>

2022-03-15 10:52 UTC, PeerRich commented
> Excited to see this PR!
> 
> We are currently working on a feature where we want to redirect the page based on a Cal.com booking being completed within an iFrame.
> 
> Does this PR enable an iFrame to trigger the redirection of the top level page? If not, I'd love to request it as a feature (ideally as part of this PR if not out of scope).
> 
> For implementation, one way could be to use `window.postMessage()` and allow the developer the handle the rest. This is what the embedded Calendly iFrame uses and gives the developer lots of flexibility including using dynamic success URLs and triggering appropriate analytics. Here's a link to how [Calendly does it](https://help.calendly.com/hc/en-us/articles/223147027-Embed-options-overview?tab=advanced#6)
> 
> Image of relevant Calendly docs

I havent tested but afaik it won't redirect at the top level yet which is a big problem for anyone using iframes. maybe this helps: https://stackoverflow.com/questions/1037839/how-to-force-link-from-iframe-to-be-opened-in-the-parent-window

alternatively we need to wait for the proper `<script>` embed which is more similar to calendly and other embeds. thats still in baby shoes but hopefully done soon!

2022-03-15 11:16 UTC, lharries commented
Got it, thank you @PeerRich. Are there any solutions you'd recommend for detecting the Cal.com being booked and then moving the user onto the next page? Looking like we'll need to use websockets connected to the backend and monitoring the webhooks - which seems excessive

2022-03-15 11:42 UTC, hariombalhara commented
> > Excited to see this PR!
> > 
> > We are currently working on a feature where we want to redirect the page based on a Cal.com booking being completed within an iFrame.
> > 
> > Does this PR enable an iFrame to trigger the redirection of the top level page? If not, I'd love to request it as a feature (ideally as part of this PR if not out of scope).
> > 
> > For implementation, one way could be to use `window.postMessage()` and allow the developer the handle the rest. This is what the embedded Calendly iFrame uses and gives the developer lots of flexibility including using dynamic success URLs and triggering appropriate analytics. Here's a link to how [Calendly does it](https://help.calendly.com/hc/en-us/articles/223147027-Embed-options-overview?tab=advanced#6)
> > 
> > Image of relevant Calendly docs
> 
> I havent tested but afaik it won't redirect at the top level yet which is a big problem for anyone using iframes. maybe this helps: https://stackoverflow.com/questions/1037839/how-to-force-link-from-iframe-to-be-opened-in-the-parent-window
> 
> alternatively we need to wait for the proper `<script>` embed which is more similar to calendly and other embeds. thats still in baby shoes but hopefully done soon!

It would actually redirect the parent of the cal iframe to the external URL.

2022-03-15 12:54 UTC, hariombalhara commented
@PeerRich Maybe we can start sending postMessages to cal iframe parent. We can introduce `bookingSuccess` as the first event ?

2022-03-15 13:54 UTC, lharries commented
> @PeerRich Maybe we can start sending postMessages to cal iframe parent. We can introduce `bookingSuccess` as the first event ?

This would work great!

2022-03-24 18:04 UTC, zomars commented
I'll be updating this branch

2022-03-24 18:42 UTC, zomars commented on packages/prisma/schema.prisma
> +  successRedirect         String?
```suggestion
  successRedirectUrl         String?
```

2022-04-04 11:24 UTC, PeerRich approved these changes
awesome work! only waiting for merge conflicts to be resolved then merging

2022-04-04 11:44 UTC, hariombalhara commented
Disabling auto merge. I found that in some earlier merge conflict resolution, the usage of SuccessRedirectEdit got removed. I have added it back but need to test once.

2022-04-04 15:57 UTC, zomars commented on apps/web/server/routers/viewer/eventTypes.tsx
> +function assertValidUrl(url) {
```suggestion
function assertValidUrl(url: string) {
```

We're enabling strict mode soon so should avoid untyped parameters.

2022-04-04 15:58 UTC, zomars approved these changes

2022-04-05 03:14 UTC, hariombalhara commented
This is ready to merge. Just migrations need to be run first @PeerRich @zomars

2022-04-05 07:58 UTC, baileypumfleet approved these changes

2022-04-05 08:05 UTC, merged