Add owner role transfer
calcom/cal.com pull request #2119
Opened 2022-03-11 22:56 UTC by juliansg022

## What does this PR do?

In this PR was added the option to transfer the owner role to another member, when this transfer occurs, the old owner role is changed to Admin.

Fixes #2089

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- The changes were tested in a team with at least two members, transferring the owner role between them.

## Checklist

- [X] I have read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code and corrected any misspellings
- [X] I have checked if my changes generate no new warnings

2022-03-14 20:48 UTC, alannnc commented on apps/web/components/team/MemberChangeRoleModal.tsx
> +    if (role === "OWNER") {
We should avoid comparing to plain strings when fit
`if (role === MembershipRole.OWNER) {`

2022-03-14 20:49 UTC, alannnc commented on apps/web/components/team/MemberChangeRoleModal.tsx
> +      }
this for can be changed to **find** 
`const owner = members.find((item) => item.role === MembershipRole.OWNER); 
`
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find

2022-03-14 20:50 UTC, alannnc commented on apps/web/components/team/MemberChangeRoleModal.tsx
> +
@zomars 
I know it probably won't happens but what should happens if no OWNER was found?
throw an owner not found exception would be fine

2022-03-14 20:51 UTC, alannnc commented on apps/web/components/team/MemberChangeRoleModal.tsx
> +        role: "ADMIN",
`role: MembershipRole.ADMIN,`

2022-03-14 20:52 UTC, alannnc commented on apps/web/components/team/MemberChangeRoleModal.tsx
> +              {props.team["membership"].role === "OWNER" && <option value="OWNER">{t("owner")}</option>}
`{props.team["membership"].role === MembershipRole.OWNER && <option value="OWNER">{t("owner")}</option>}`

2022-03-14 20:52 UTC, alannnc commented on apps/web/components/team/MemberListItem.tsx
> +                props.member.role !== "OWNER" && (
`props.member.role !== MembershipRole.OWNER && (`

2022-03-14 20:54 UTC, alannnc requested changes
Just change plain strings to their variable when fit

2022-03-14 20:57 UTC, juliansg022 commented
@alannnc Considering the discussion in #2089 should  I fix this PR to solve the issue, or should It be discarded and considered PR #2145?

2022-05-14 13:47 UTC, zomars commented
Closed in favor of #2145

2022-05-14 13:47 UTC, closed without merging