Add restrictions to protect the owners and change their roles
calcom/cal.com pull request #2145
Opened 2022-03-14 15:44 UTC by juliansg022

## What does this PR do?

Adds restrictions so that an Owner can downgrade his role only if he isn't the only Owner. Additionally, an Owner can only modify the roles of other members who aren't Owners. Admins can only modify members with the same or lesser roles. It was considered that only an Owner can appoint another owner.

Fixes #2089 

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- The changes were tested in a team with at least two members.

## Checklist

- [X] I have read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code and corrected any misspellings
- [X] I have checked if my changes generate no new warnings

2022-03-15 14:30 UTC, baileypumfleet submitted a review, later dismissed
You now cannot downgrade someone if you set them as an owner, which is not functionality we want

2022-03-15 14:46 UTC, juliansg022 commented
> You now cannot downgrade someone if you set them as an owner, which is not functionality we want

I understand. Currently, the Admins can downgrade other members, i.e., the Admins can downgrade members with a role equal or less to his role. 

Now, should the same rule apply to owners? the Owner should be able to downgrade members with a role equal or less to his role.

2022-03-15 15:34 UTC, baileypumfleet commented
Yeah that's correct

2022-03-15 16:11 UTC, baileypumfleet commented
Thank you very much, looking forward to it :)

2022-04-04 22:36 UTC, zomars requested changes
I've tried to update this PR but I don't have permissions. Would you kindly update your branch and solve merge conflicts?

2022-04-11 22:53 UTC, juliansg022 commented
@zomars Sure, I'll update the PR.

2022-04-19 14:50 UTC, juliansg022 commented
Hi @baileypumfleet and @zomars, I've updated the PR.

2022-04-22 15:56 UTC, zomars commented
@juliansg022 Can I get permissions to push to this branch?

2022-04-22 15:58 UTC, zomars requested changes
This PR is getting little bit hard to review. We don't have permissions to keep this branch up to date. Additionally all tests are failing and type checks as well.

2022-04-28 16:20 UTC, juliansg022 commented
@zomars I updated the PR and I fixed the problem related to data types. Now the tests are working well. Regarding the permissions of the branch, this belongs to an organization so I don't have permission to give you control over it. 

I'll be updating the PR daily so you can eventually review it.

2022-04-28 17:48 UTC, zomars commented
@juliansg022 please notify your organization owner about [our contributing guidelines](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) so we can speed up the reviewing process.

2022-04-28 17:49 UTC, zomars commented on apps/web/components/team/MemberListItem.tsx
> +import { useMeQuery } from "../Shell";
Is this is going to be used on another file, consider splitting it into a separate file so we can avoid circular dependency issues.

2022-04-29 19:48 UTC, juliansg022 commented
Hi @zomars and @baileypumfleet, you have been added as externals collaborators because the option to allow maintainers isn't available for organizations. https://github.community/t/how-can-we-enable-allow-edits-from-maintainers-by-default/2847/11

> @juliansg022 please notify your organization owner about [our contributing guidelines](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) so we can speed up the reviewing process.

2022-05-04 21:07 UTC, zomars approved these changes

2022-05-04 21:28 UTC, merged