Improving A11y across pages
calcom/cal.com pull request #2219
Opened 2022-03-20 21:52 UTC by sean-brydon

## What does this PR do?

Puts us in green for the majority of the pages on google lighthouse for A11y

Fixes # (issue)

## Type of change

- [ X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

No Tests needed.

## Checklist

- I haven't performed a self-review of my own code and corrected any misspellings
- I haven't commented my code, particularly in hard-to-understand areas

2022-03-20 22:16 UTC, zomars requested changes
Nice work. Minor nitpick. Are we adding/removing any dependencies? If we're not let's skip the yarn.lock file from this PR please 🙏

2022-03-20 22:42 UTC, PeerRich approved these changes

2022-03-21 20:41 UTC, PeerRich commented
once merge conflcit solved it'll auto merge @sean-brydon

2022-03-22 21:17 UTC, PeerRich commented
<img width="584" alt="image" src="https://user-images.githubusercontent.com/8019099/159577527-9c0e146b-92f7-428a-82e4-852601dd108f.png">
can be merged after merge conflicts were resolved 🙏 @sean-brydon

2022-03-24 20:02 UTC, zomars approved these changes

2022-03-24 20:14 UTC, merged