Refactoring login tests. Adding new test cases
calcom/cal.com pull request #2337
Opened 2022-03-31 22:50 UTC by denik1981

## What does this PR do?

This is part of a series of PRs whose goal is to optimize all the tests extended the whole coverage and improve the inner performance. These tests are all using the new fixture addition which by the end of the conversion will allow us to run tests concurrently and speed them up in consequence.  

A summary of changes: 

- New test case: login for each type of account (plan) and asserting for the plan info as well.
- New test case: login for a non-existent user account.
- New test case: login with a wrong password.
- New test case: logout using the user's expected flow (using the dropdown)
- Add assertive declarations missing in the previous version for login tests. 
- Removing unnecessary types in the user's fixture that adds up to unwanted boilerplate (type inference when possible).

## Type of change
- [x] New feature (non-breaking change which adds functionality)

## How should this be tested?

- `yarn workspace @calcom/prisma db-reset`
- `yarn dev`
- `yarn workspace @calcom/web test-e2e`

2022-04-05 01:31 UTC, alannnc commented on apps/web/playwright/fixtures/types.ts
> +export enum TimeZoneE {
rename to `TimeZoneEnum` to maintain the context on its name

2022-04-05 01:33 UTC, alannnc commented on apps/web/playwright/fixtures/users.ts
> +  //2s of delay to give the session enough time for a clean load
space after comment // 2 seconds

2022-04-05 01:39 UTC, alannnc requested changes, later dismissed
NIT changes, but test seem to be working fine

2022-04-05 08:24 UTC, denik1981 commented on apps/web/playwright/fixtures/users.ts
> +  //2s of delay to give the session enough time for a clean load
done!

2022-04-05 08:25 UTC, denik1981 commented
> NIT changes, but test seem to be working fine

Thanks for reviewing this!

2022-04-06 00:08 UTC, zomars approved these changes
Nice work!

2022-04-06 15:13 UTC, merged

2022-04-06 20:24 UTC, zomars commented
@denik1981 for some reason since this got merged, test are now timing out at the 10 minute mark on GH. Can you help us debug this? Also should we add configs to the `e2e.yml` file?

2022-04-06 22:07 UTC, denik1981 commented
It works well on my side (locally) but let me check the public logs in the PRs I have available. 
Retrials maybe? 

One easy and fast fix is to reduce the timeout for each retrial. Currently, it is set to 60 seconds to wait for the test to acknowledge it is not working and retry. This could be reduced to half at least (and even further IMHO). But 2 or 3 retrials can eat more than 3 minutes from the total time. 

The other thing is something I cannot do anything about it in the short run which is that we are running with only one worker when Playwright is planned to be run multithreaded but this was necessary for us because we are using the same source of data for each test and it was the cause some of them were failing.

I'm working on this. In replacing everything we have with fixtures that should give us more power to test everything in parallel. My current work is with the "schedules" fixtures that is a dependency on the "events" fixture. I will push this one early tomorrow with some fixes I found as well for some issues related to availability and a set of tests for the entire availability section of Cal.  And the last picture remaining will be the "teams" fixture so that I can replace all the calls to the seeded data and raise the number of workers to an optimal number that can speed up our tests. Booking is another one but it can be deferred for later as it is not stopping me from migrating tests to the new schema.   

The truth is that the more tests we add, the more time we will spend running those tests because they are all running in serial mode. This was something necessary to do but far from ideal in terms of running our tests in CI.

Even do, I will check the logs and see where is the source of the problem to help you fix it.

2022-04-06 23:18 UTC, denik1981 commented
Unfortunately, I couldn't find any run in the public logs using the login/logout tests addition but I pulled an updated version of Cal with the latest PRs and run a CI test session locally to measure everything. I know is not the same but it help me issue a preflight research. Logging tests are taken 49s (locally) in total, ran without any issue, and actually very fast. 

I found a few retrials and, remember, each of them is eating 60 seconds. Some of these retrials came from failing tests which ended up eating 2 minutes per test in total. There is a very recent PR (#2239) that is adding tests for dynamic bookings and those tests fall into the group of failing tests. We might wanna check those tests and eventually mark them with `fixme` so that they don't run in CI for the moment until every issue in there is addressed.

There is also a recurrent test case that usually fails in the first run which is the booking reschedule. Not sure, what's going on with this test but it usually needs a second shot to run well. It might be good to mark this one with `fixme` as well.

Regarding `e2e.yml` that I didn't answer before, no, there is no change needed there (from my side at least) for the added login/logout tests. In fact, none of the other tests are compromised with any addition made in the login/logout tests. The users' fixture is only used in there and is planned to be used everywhere shortly. The rest of the tests are using seeded data as usual. 
I forgot to mention that an extra benefit of not using seeded data is that we can cut in the time needed to seed the DB as a pre-step for each e2e run. 

Below is a snapshot of my latest run locally of the e2e tests.

 - Blue: skipped 
 - Gray: Run (time measurements in brackets)
 - Red: failures
 
 
![image](https://user-images.githubusercontent.com/66160623/162086538-e67e3a21-ab00-4a8d-b703-261efa462c63.png)

![image](https://user-images.githubusercontent.com/66160623/162086884-e58f9a0f-6352-400d-8570-c751937c6b26.png)


These (below) are all the login/logout tests. Less than 50 seconds in total. 
I predict this could be reduced to about ~15/20 seconds once we raise the amount of workers available.  

![image](https://user-images.githubusercontent.com/66160623/162086764-ea159a51-8499-4dce-9f93-c979265f137f.png)

### SUMMARY
My suggestion is to mark with `fixme` the current failing tests and reduce the global timeout from the playwright configuration to as much as 30s if not less.  Login/out tests seem to be running well and fast. Even if raising workers is not possible now these tests can be further optimized (very subtle) because they are forcing a 2s timeout between each new login to give extra time for the session to prepare itself without running into troubles. I found that without these little gaps of time, login tests can fail, but 2s is a completely random value. I will try with only 1 second to see if it runs well. All in all, I don't think this will reduce the overall run for these tests in more than 10/15 seconds and I don't think is the reason of CI taking so long.

2022-04-07 01:43 UTC, denik1981 commented
Further on this:

I ran a bisect test to ultimately find the commit that is pulling down a lot of e2e tests. Note that I clean up the entire repo and reinstalled everything between these tests, and also rebuild the DB. 

So I first checked into the first commit that came after the commits that merge the Refactoring of Login/logout tests and everything is running well. Output below:

![image](https://user-images.githubusercontent.com/66160623/162103251-07f2ea9b-3fe2-43b9-bdc8-91f4a3dd2c40.png)
![image](https://user-images.githubusercontent.com/66160623/162103278-af80ebc2-d18d-417b-a270-a2e1cfdff41b.png)



Then I made a second run with the next commit in the stack "dynamic group links (#2239)" which lead to a completely different output on where some tests are failing. If there is some extra configuration needed to test this commit please let me know because I'm making the (maybe wrong) assumption that it can be run as it is.

![image](https://user-images.githubusercontent.com/66160623/162103035-e89beba2-f55e-4717-a3ea-1c586a23271c.png)
![image](https://user-images.githubusercontent.com/66160623/162103056-09eea627-10df-425c-a405-b860f9afcfac.png)
![image](https://user-images.githubusercontent.com/66160623/162103087-0635b000-6fa5-435b-916e-e3e3920e9806.png)


### Aside Note
From both runs, I can see the below test (which I mentioned before) fails in the first attempt. I'm not sure why this happens with this test but is happening since it has been there and the problem is that it demands to use the entire timeout (1 minute) before it fails and retries. In the second snapshot, this test fails in the retry as well with the added cost of eating 1 minute for a second time. We might want to investigate the source of the issue with this test and refactor it if possible, 

`[chromium] › ../../apps/web/playwright/booking-pages.test.ts:129:3 › pro user › can reschedule a booking`