Fix login and onboarding flows
calcom/cal.com pull request #2390
Opened 2022-04-05 20:06 UTC by afzalsayed96

## What does this PR do?

When you sign up you can notice a slight jitter in the UI with invalid state while redirecting to `/get-started` route.

https://user-images.githubusercontent.com/14029371/161838212-a8bb3e9b-105e-477e-a2ce-5e8e2ef79824.mov

Similarly when you navigate to a protected page such as `/event-types` without being logged in you can see a glimpse of the invalid state

https://user-images.githubusercontent.com/14029371/161838498-1297bca4-29cb-4ea2-86ac-a3ee6dbad941.mov

The root cause of this issue is how `useRedirectToLoginIfUnauthenticated` and `useRedirectToOnboardingIfNeeded` hooks are implemented. They both employ `useEffect` hook to redirect. However, `useEffect` is run after a render is completed. Hence, we see a glimpse of invalid state as the loading of session/me query finishes but `useEffect` is yet to run.

The solution is for unauth redirection is simply to check for `session` value and only then render protected UI. And similarly for onboarding user redirect, it's imperative to check both the result & loading state of `me` query before rendering anything.

With the above changes, we make sure that protected UI is only shown after consulting the appropriate loading states and the data itself and we get a clean jitter-free transition.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

Unsure

2022-04-05 20:08 UTC, afzalsayed96 commented on apps/web/components/Shell.tsx
> +  const isRedirectingToOnboarding = user && shouldShowOnboarding(user);
I believe state is unnecessary here as any change in `query` will cause a rerender and `isRedirectingToOnboarding` can be considered a derived or computed state from `query.data`

2022-04-05 20:10 UTC, afzalsayed96 commented on apps/web/components/Shell.tsx
> +  return null;
We return null when there's no `session`. This occurs when `session=null` and `loading=false`. The `useEffect` which redirects to `/auth/login` is run after this render.

We can also choose to show loader in this case.

2022-04-05 20:41 UTC, denik1981 commented
@alannnc @zomars 
Please check #2337 which provides more tests for the login/logout flow and normalizes the usage of the user fixture to decouple tests from the seed data. This won't help to test code changes in this PR but it will help assure everything is still working

2022-04-06 08:56 UTC, alishaz-polymath requested changes
Minor change requested, and additional information requested. It is an improvement on the current state.

2022-04-06 08:56 UTC, alishaz-polymath commented on apps/web/components/Shell.tsx
> +    session: session,
```suggestion
    session,
```

2022-04-06 08:56 UTC, alishaz-polymath commented on apps/web/components/Shell.tsx
> +                props.flexChildrenContainer && "flex flex-col"
Why is this being modified?

2022-04-06 13:14 UTC, joeauyeung reviewed
Hey, great PR! The transitions are now smooth. Just building off of @alishaz-polymath's question about why some of the class names have changed.

2022-04-06 16:36 UTC, zomars approved these changes
Reverted unnecessary diffs. Other than that code looks good and tested. Thank you for your contribution 🙏

2022-04-06 16:52 UTC, alishaz-polymath approved these changes
Thank you for your  contribution. Tested, works! 🙏

2022-04-06 17:07 UTC, merged

2022-04-07 00:05 UTC, denik1981 commented
@afzalsayed96 Thank you for this contribution. Quite helpful!