Add seats to event types
calcom/cal.com pull request #2485
Opened 2022-04-14 14:32 UTC by joeauyeung

## What does this PR do?

This PR is a rework of #2392 since the commits I brought in made the branch messy. 

The previous PR's associated with seats are
- #2370
- #2311
- #2392

Fixes #2064

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## How should this be tested?

- [ ] Test A
- [ ] Test B

## Checklist

- I haven't checked if my PR needs changes to the documentation
- I haven't checked if my changes generate no new warnings
- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

2022-04-28 18:38 UTC, joeauyeung commented
@alannnc and @PeerRich tagged you two for review but the previous PRs that made this one up have already been reviewed.

2022-04-29 06:39 UTC, PeerRich commented
> @alannnc and @PeerRich tagged you two for review but the previous PRs that made this one up have already been reviewed.

built seems failing on vercel

2022-05-04 18:56 UTC, joeauyeung commented
@PeerRich builds now working on Vercel

2022-05-16 16:26 UTC, zomars requested changes, later dismissed
Code looks good, there's still a couple of things missing.

Since this is a new type of event, E2E are needed to make sure this keeps working.

Also we need to see how this works with:
- Paid bookings
- Recurring events (recently added)
- Hashed Links (recently added)

2022-05-16 16:26 UTC, zomars commented on packages/prisma/schema.prisma
> +
This value isn't being used anywhere?

2022-05-17 18:01 UTC, joeauyeung commented on packages/prisma/schema.prisma
> +
Removed

2022-05-17 22:58 UTC, zomars commented
![image](https://user-images.githubusercontent.com/3504472/168925611-40f928a4-68ab-49e8-aa5d-50cc3a814be7.jpeg)

We need to make some mobile adjustments

2022-05-17 23:20 UTC, zomars reviewed
We're almost there. Tested the preview and is working flawlessly. Nice job! Left some mobile and code nits.

2022-05-17 23:20 UTC, zomars commented on apps/web/lib/hooks/useSlots.ts
> +        console.log("This triggered");
We may want to log something more useful or remove it altogether

2022-05-17 23:20 UTC, zomars commented on apps/web/lib/hooks/useSlots.ts
> +        workingHours: workingHours,
```suggestion
        workingHours,
```

2022-05-17 23:20 UTC, zomars commented on apps/web/lib/hooks/useSlots.ts
> +        busy: busy,
```suggestion
        busy,
```

2022-05-18 20:25 UTC, PeerRich approved these changes
lets goo

2022-05-23 21:44 UTC, alannnc approved these changes
It's working, and also edit booking also works with all guests.

2022-05-24 13:19 UTC, merged