Contributing to App Store 1.1
calcom/cal.com pull request #2567
Opened 2022-04-21 14:41 UTC by joeauyeung

## What does this PR do?

Update to the new app store structure

## Type of change

- [x] This change requires a documentation update

## How should this be tested?

- [ ] Test A
- [ ] Test B

2022-04-21 14:42 UTC, joeauyeung commented on apps/docs/tsconfig.json
> +  }
Only changed here for docs since most files and mdx

2022-04-21 15:21 UTC, PeerRich commented
huh @joeauyeung  this is empty now
<img width="251" alt="image" src="https://user-images.githubusercontent.com/8019099/164491523-551290fe-c25a-461b-b4db-8f6077128a26.png">

2022-04-22 16:02 UTC, zomars requested changes
All changes disappeared. Let's try to fix that or open a new PR if necessary. Then you can re-request a review @joeauyeung

2022-04-22 17:10 UTC, joeauyeung commented
@zomars interesting. I think when Peer merged to main it removed the number of files changed but I'm seeing the changes here: https://docs.cal.com/developer/app-store. If you see any changes that need to be made I'll create a new PR.

2022-04-22 17:10 UTC, closed without merging