Fix infinite renders on event-type edit page
calcom/cal.com pull request #2820
Opened 2022-05-19 09:12 UTC by hariombalhara

## What does this PR do?

Fixes the error and hung state of the event-type edit page
<img width="1782" alt="Screenshot 2022-05-19 at 2 40 03 PM" src="https://user-images.githubusercontent.com/1780212/169257612-b742803d-4741-46fb-85b8-df9103bc3842.png">
Also, updates Pull Request template to mention the environment as now there are two possible environments where PRs can be opened against.

**Environment:** Staging(main branch)
Context: Possibly introduced in ESLINT fixes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

Simply go to http://localhost:3000/event-types/12

## Checklist

- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

2022-05-19 13:27 UTC, leog approved these changes
Nice catch. I wonder if this could come up in some test to catch them with anticipation.

2022-05-19 17:23 UTC, zomars approved these changes

2022-05-19 17:24 UTC, zomars requested changes
@emrysal fell free to block any PRs that you feel need to be addressed first

2022-05-19 22:13 UTC, emrysal commented
@hariombalhara I've refactored the component a little as to make the useEffect redundant and give control fully to the `Controller` component. There were a couple of types that I was able to improve upon using react-select types. It can probably be tweaked even further (for example, it may not be needed to overwrite some props, but I couldn't figure out how to make it work without doing so).

2022-05-19 22:14 UTC, emrysal commented on apps/web/components/ui/form/CheckedSelect.tsx
> -CheckedSelect.displayName = "CheckedSelect";
This was probably a remnant of a once existing forwardRef which has been removed since.

2022-05-19 22:15 UTC, emrysal commented on apps/web/components/ui/form/CheckedSelect.tsx
> -            onClick={() => changeHandler([option])}
This can't have worked 😅

2022-05-19 23:15 UTC, zomars approved these changes

2022-05-20 09:33 UTC, Jaibles commented
@emrysal with regards to
> previously attendees weren't really added to the select list itself; this is new; what do you think should be the desired behaviour here?

I would say we should not add attendees inside the dropdown trigger.

2022-05-23 17:59 UTC, merged

2022-05-23 18:14 UTC, zomars commented
Cherry picked to prod