Meet/Zoom Email Clarification
calcom/cal.com pull request #2828
Opened 2022-05-20 08:40 UTC by sean-brydon

## What does this PR do?

This PR adds clarification to email when the user is booking a zoom/meet meeting - that the meeting information will be provided when the event has been confirmed. 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist

- I haven't added tests that prove my fix is effective or that my feature works

2022-05-20 08:41 UTC, sean-brydon commented on apps/web/lib/emails/templates/organizer-scheduled-email.ts
> +        <p style="color: #494949; font-weight: 400; line-height: 24px;">${providerName}
Formatted to make this more readable

2022-05-20 11:14 UTC, CarinaWolli commented
Looks good! Should we maybe also add that to the attendee's email not just the organizer?

2022-05-20 16:27 UTC, zomars commented on apps/web/lib/emails/templates/organizer-scheduled-email.ts
> +          )}"><img src="${linkIcon()}" width="12px"></img></a>`
```suggestion
          )}"><img src="${linkIcon()}" width="12px"/></a>`
```

2022-05-20 16:27 UTC, zomars approved these changes

2022-05-20 16:28 UTC, zomars commented
Agreed with @CarinaWolli we need to make sure every party involved receives the clarification.

2022-05-21 13:45 UTC, emrysal requested changes
Requesting changes to clarify this should also be implemented in invitee-scheduled-email.ts

2022-05-23 10:54 UTC, emrysal approved these changes

2022-05-23 10:54 UTC, merged