Putting "Additional Input Required" doesn't bar you from creating a booking #2660
calcom/cal.com pull request #2829
Opened 2022-05-20 11:00 UTC by gitstart

## What does this PR do?

Fixes #2660

Loom Video: https://www.loom.com/share/baba361ae36d4c1ba6ee6e97369c09ce

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

2022-05-20 16:00 UTC, zomars commented on apps/web/components/booking/pages/BookingPage.tsx
> -                              required: input.required,
Why did we remove from hook form? IMO we should leave it in there as well.

2022-05-20 16:01 UTC, zomars requested changes
This solutions works but it will only work on the client only. We should validate on the server as well.

2022-05-24 15:44 UTC, zomars commented
@gitstart on this PR would be optimal 🙏

2022-05-25 19:15 UTC, zomars requested changes
We're still missing server-side validations, please only re-request review when all comments are fully addressed. 🙏

2022-06-03 20:03 UTC, PeerRich commented
does not solve the problem

2022-06-03 20:03 UTC, closed without merging