When clicking a deleted type event while it's "deleting", it sends you to 500 error
calcom/cal.com pull request #2863
Opened 2022-05-24 19:08 UTC by gitstart

## What does this PR do?

Fixes #1227
 Loom Video:https://www.loom.com/share/3ed0235b83ef4d64a2f106d514122eb2

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

2022-05-25 16:08 UTC, emrysal requested changes
Added a suggestion to turn this into a oneliner fix 👍

2022-05-25 16:08 UTC, emrysal commented on apps/web/pages/event-types/[type].tsx
> +                    isLoading={loading}
```suggestion
                    isLoading={deleteMutation.isLoading}
```

2022-05-30 05:40 UTC, hariombalhara commented
@gitstart Could you please work on the suggestion and we can quickly merge it.

2022-05-31 11:21 UTC, gitstart commented
sorry for the delay @hariombalhara, we will fix the notification issue with the bot that made us miss the comments

the change is pushed

2022-06-06 01:30 UTC, closed without merging