fix booking detail page for cancelled events
calcom/cal.com pull request #2905
Opened 2022-05-27 12:55 UTC by CarinaWolli

## What does this PR do?

Fixes booking detail page for cancelled events.

Before: 
![Screenshot 2022-05-27 at 14 52 49](https://user-images.githubusercontent.com/30310907/170702901-c0285003-2b2f-4418-939b-f813a9e92978.png)

After:
<img width="763" alt="Screenshot 2022-05-27 at 14 44 51" src="https://user-images.githubusercontent.com/30310907/170702143-42f875fb-6b1f-4330-bfad-6d305a46d784.png">

**Environment**: Staging(main branch)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- Go to Bookings
- Click on a cancelled booking
- You should see the view from the screenshot above

## Checklist

- I haven't added tests that prove my fix is effective or that my feature works

2022-05-27 15:57 UTC, agustif approved these changes
Looks good to me! tested in local
<img width="1164" alt="image" src="https://user-images.githubusercontent.com/6601142/170735644-0ecd6dfc-4604-4103-9c35-e0fc25b53445.png">

2022-05-27 19:13 UTC, alannnc requested changes
![image](https://user-images.githubusercontent.com/4461358/170775667-f5e8deaf-1ff2-417e-8fc3-586df19b6748.png)
I'm getting my attendees deleted @ api/cancel and then BookingListItem tries to display attendees[0] which don't exists and receive this error.
Probably we should reconsider not deleting attendees?

2022-05-30 17:16 UTC, CarinaWolli commented on apps/web/components/booking/BookingListItem.tsx
> +              name: booking.attendees[0] ? booking.attendees[0].name : undefined,
this fixes the error from @alannnc's comment

2022-05-30 17:17 UTC, CarinaWolli commented on apps/web/pages/success.tsx
> +                          {(bookingInfo?.user || bookingInfo?.attendees) && (
don't show 'who' when no user or attendees exist in booking

2022-05-30 17:38 UTC, alannnc approved these changes

2022-05-30 18:17 UTC, merged