Share WIP
calcom/cal.com pull request #3118
Opened 2022-06-20 21:00 UTC by emrysal

2022-06-22 21:55 UTC, zomars commented
Made some improvements @emrysal please let me know if there's something missing to merge

2022-06-22 21:56 UTC, zomars approved these changes

2022-06-24 23:05 UTC, agustif requested changes, later dismissed
Hey, so over the surface this looks good (and faster!)
I just hit this bug when trying too far into the future (2023) where it won't show dates, thoughts @zomars @emrysal sharing loom
Basically when it tries to change month to jan 2023 it goes back to 2022 june
https://www.loom.com/share/1aed432af2be4b3095746fcfada60cbd

2022-06-25 00:02 UTC, zomars commented
That's a nice catch @agustif it will definitely bite us later on. We should check on that.

2022-06-25 04:55 UTC, zomars commented
Made a quick demo of what I've made here:

https://www.loom.com/share/3a4a5b99334d4f13ba134ee867239052

2022-06-25 23:15 UTC, emrysal commented
Quick demo of the updates within this PR:
https://www.loom.com/share/f56dea8d444d4a538f0e1d0e2bb81153

2022-06-25 23:32 UTC, zomars approved these changes, later dismissed
Looking gucci 🙌

2022-06-25 23:41 UTC, zomars commented
https://user-images.githubusercontent.com/3504472/175793690-f9690e13-f1d6-45a5-8a6f-4cc4e4a8e14b.MOV

It seems like sometimes it just keeps loading. Testing on mobile Safari. Will check tomorrow

2022-06-26 00:56 UTC, agustif commented
Looking awesome now!

2022-06-27 14:25 UTC, leog approved these changes
Looking really good! Can't wait to have this deployed for our users.
The skeleton animation on dark mode is very subtle, maybe we can make it more flashy? 
I wonder if we should have some kind of polyfill to be covered with common issues we have with Safari Mobile.

2022-06-27 16:06 UTC, Jaibles commented
@emrysal For the skeleton can we do the effect on where the text would be rather than where the border would be? Let me know if you need designs for this.

2022-06-27 16:21 UTC, emrysal commented
@Jaibles @sean-brydon Designs are super helpful here, sounds like it may be a general change to the way skeletons operate so maybe a change to the design system.

2022-06-27 20:05 UTC, alannnc commented on packages/ui/booker/DatePicker.tsx
> +        "hover:border-brand disabled:text-bookinglighter absolute top-0 left-0 right-0 bottom-0 mx-auto w-full rounded-sm border border-transparent text-center font-medium disabled:cursor-default dis
@emrysal This is what fixes the shrinking on main

2022-06-27 21:01 UTC, merged