Broken Integration Alarm System
calcom/cal.com pull request #3135
Opened 2022-06-21 17:10 UTC by joeauyeung

## What does this PR do?

This PR alerts users when an integration is broken.

When a video integration is broken
![image](https://user-images.githubusercontent.com/65426560/175120141-5e729e5a-cddb-4a26-98bf-790704b94e68.png)

When there's an error with the calendar
![image](https://user-images.githubusercontent.com/65426560/175120203-e8084ff0-721a-41ee-852d-8fa3a0895662.png)

Fixes #2944

**Environment**: Staging(main branch) / Production

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## How should this be tested?

- Broken video credential
	- In your .env file go to the Daily credentials and delete the api key
	- Edit an event type and set the location to Cal Video
	- Create a booking, you should get the broken integration email for video
- Broken calendar credential
	- Connect a Google calendar
	- In the DB go to the google calendar credential, under key delete some characters from the access token
	- Create a booking, you should get the broken integration email for calendars
## Checklist

- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't performed a self-review of my own code and corrected any misspellings
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my PR needs changes to the documentation
- I haven't checked if my changes generate no new warnings
- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

2022-06-21 17:14 UTC, joeauyeung reviewed
@zomars I made a change to the emails and I know you just refactored so just wanted some feedback while I'm working on this.

2022-06-22 19:23 UTC, joeauyeung commented on packages/core/CalendarManager.ts
> +        await sendBrokenIntegrationEmail(calEvent, "calendar");
Only send email on error

2022-06-22 20:35 UTC, zomars commented on apps/web/public/static/locales/es/common.json
> + "broken_video_action": "No pudimos agregar el  enlace de <1>{props.location}</1>a tu evento agendado. Contacta a tus invitados o actualiza tu calendario para agregar los detalles. Puedes  <2>cambiar
```suggestion
  "broken_video_action": "No pudimos agregar el  enlace de <1>{props.location}</1>a tu evento agendado. Contacta a tus invitados o actualiza tu calendario para agregar los detalles. Puedes  <2>cambiar la ubicación de tu tipo de event </2> o <3>remover la App y agregarla de nuevo.</3>"
```

2022-06-22 20:36 UTC, zomars commented on apps/web/public/static/locales/es/common.json
> + "broken_video_action": "No pudimos agregar el  enlace de <1>{props.location}</1>a tu evento agendado. Contacta a tus invitados o actualiza tu calendario para agregar los detalles. Puedes  <2>cambiar
Prettier will complain otherwise

2022-06-22 20:40 UTC, zomars requested changes
I don't think we need the failed event attachment ICS file

2022-06-23 20:05 UTC, zomars reviewed
Almost there, I'm just trying to make the translations works. Let's see if one more pass can get us there.

2022-06-23 20:05 UTC, zomars commented on packages/emails/src/templates/BrokenIntegrationEmail.tsx
> +  );
Made some fixes on the `BrokenVideoIntegration` let's see if you can replicate in here [based on the docs](https://react.i18next.com/latest/trans-component)

2022-06-23 21:00 UTC, zomars commented on packages/emails/src/templates/BrokenIntegrationEmail.tsx
> +    <Trans i18nKey="broken_video_action" t={props.t}>
The calendar one

2022-06-24 09:09 UTC, baileypumfleet requested changes, later dismissed
Only a couple of really minor things

2022-06-24 09:09 UTC, baileypumfleet commented on apps/web/pages/api/email.ts
> +  const t = await getTranslation("es", "common");
Why has this been changed to es?

2022-06-24 09:09 UTC, baileypumfleet commented on apps/web/public/static/locales/en/common.json
> +  "broken_video_action": "We could not add the <1>{{location}}</1> meeting link to your scheduled event. Contact your invitees or update your calendar event to add the details. You can either <3> cha
```suggestion
  "broken_video_action": "We could not add the <1>{{location}}</1> meeting link to your scheduled event. Contact your invitees or update your calendar event to add the details. You can either <3> change your location on the event type </3> or try <5>removing and adding the app again.</5>",
```

2022-06-24 09:09 UTC, baileypumfleet commented on packages/emails/src/templates/BrokenIntegrationEmail.tsx
> +      &nbsp;or&nbsp;
```suggestion
      &nbsp;or try&nbsp;
```

2022-06-24 09:09 UTC, baileypumfleet commented
Also, e2e broken

2022-06-25 05:11 UTC, zomars approved these changes
Tests fixed LGTM

2022-06-25 05:16 UTC, merged