WIP
calcom/cal.com pull request #3139
Opened 2022-06-21 22:15 UTC by zomars

## What does this PR do?

refs #2739 

Fixes # (issue)

**Environment**: Staging(main branch) / Production

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

- [ ] Test A
- [ ] Test B

## Checklist

- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't performed a self-review of my own code and corrected any misspellings
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my PR needs changes to the documentation
- I haven't checked if my changes generate no new warnings
- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

2022-06-21 22:35 UTC, zomars commented on turbo.json
> +    },
Type checking should be able to run without dependencies

2022-06-21 22:36 UTC, zomars commented on turbo.json
> +    },
Run production migrations when there are new ones

2022-06-21 22:37 UTC, zomars commented on turbo.json
> +      "outputs": []
Should be run with `--concurrency=1` since the order matters here.

2022-06-21 22:39 UTC, zomars commented on turbo.json
>      },
We check the env variables before dev if the example files changed

2022-06-21 22:39 UTC, zomars commented on turbo.json
>      },
Regenerate prisma clients on post-install client if schemas change

2022-06-22 17:53 UTC, agustif approved these changes
Awesome results @zomars, `yarn dx` feels really fast now, `yarn start` is instant, `yarn build`, took 70secs which ain't bad.

2022-06-22 17:56 UTC, agustif requested changes
e2e are failing for me. unapproving until I found out why. Seems CI has the same issue @zomars , is this OK?

2022-06-22 19:51 UTC, jaredpalmer approved these changes

2022-06-22 20:41 UTC, merged