fix/request-reschedule-google-calendar-sync
calcom/cal.com pull request #3157
Opened 2022-06-25 21:21 UTC by alannnc

## What does this PR do?

Add required param for deleting event on G-calendar.

Fixes # (issue)

**Environment**: Staging(main branch) / Production

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- [ ] Now while request rescheduling g calendar event should be deleted.

## Checklist

- I haven't added tests that prove my fix is effective or that my feature works

2022-06-25 21:22 UTC, alannnc commented on apps/web/pages/api/book/request-reschedule.ts
> -              calendar?.deleteEvent(bookingRef.uid, builder.calendarEvent);
This code was trying to delete an already deleted event from above.

2022-06-25 21:23 UTC, alannnc commented on apps/web/pages/api/book/request-reschedule.ts
> +              bookingRef.externalCalendarId
A new parameter was added to deleteEvent, but it wasn’t being send from here.

2022-06-25 21:23 UTC, alannnc commented on packages/app-store/googlecalendar/lib/CalendarService.ts
> +      let calendarId = event.destinationCalendar?.externalId ?? "primary";
We had a conditional but wasn't preventing from sending null to google. We now at least try to delete on primary calendar from the user if it exist.

2022-06-25 21:24 UTC, alannnc commented on packages/app-store/googlecalendar/lib/CalendarService.ts
> +            if (err.code === 404) return resolve();
410 shouldn’t log anything, probably user deleted event on his calendar, and we're trying to delete it.

2022-06-26 07:06 UTC, hariombalhara commented
Can confirm that it fixes the issue.

## Google calendar  and Apple Calendar Test
**Before**
- Booked an event
- Requested reschedule. It cancelled the event in cal.com but It remains in google calendar. Received emails.

**After**
- Booked an event 
- Requested reschedule. It cancelled the event in cal.com and in google calendar. Received emails.Received emails

2022-06-26 07:07 UTC, hariombalhara requested changes
Though it fixes the reported issue. Left some comments to be sure we are handling all cases and things are documented.

2022-06-26 12:38 UTC, PeerRich commented
@zomars do we wait for this to be addressed and merged before 1.7.3?

2022-06-26 12:56 UTC, emrysal approved these changes

2022-06-26 12:56 UTC, emrysal commented on apps/web/pages/api/book/request-reschedule.ts
> +            return calendar?.deleteEvent(
Other calendar integrations might not have a concept of externalCalendarId - or just don't support this yet. Worth looking into but the key thing to keep in mind is that this comes down to a shared interface.

2022-06-26 12:56 UTC, emrysal commented on packages/app-store/googlecalendar/lib/CalendarService.ts
> +      if (externalCalendarId) {
I think externalCalendarId not being ?'d is an error. Or it is expected that the "primary" fallback is provided manually.

2022-06-26 12:58 UTC, emrysal commented
This is safe to go in as is @PeerRich - but we should indeed look into the flows used for externalCalendarId's and also how this works for other integrations.

2022-06-26 20:33 UTC, alannnc commented on packages/app-store/googlecalendar/lib/CalendarService.ts
> +      if (externalCalendarId) {
You were both right, I've updated accordingly to be more clear about what was needed.

- google api was receiving calendarId: null thus throwing error.
- added default in a case when calendarId could receive a null value.

2022-06-26 20:35 UTC, alannnc commented on apps/web/pages/api/book/request-reschedule.ts
> +            return calendar?.deleteEvent(
Yes, exactly what @emrysal said.

2022-06-27 01:45 UTC, hariombalhara commented on apps/web/pages/api/book/request-reschedule.ts
> +            return calendar?.deleteEvent(
Cool, we should then work on having different function signatures in interface for two different cases

2022-06-27 14:52 UTC, zomars approved these changes
LGTM

2022-06-27 14:52 UTC, merged