Fix request reschedule organiser email
calcom/cal.com pull request #3227
Opened 2022-07-04 21:43 UTC by alannnc

## What does this PR do?

There was an error while loading required template for request reschedule for owner email.

Fixes #3203 

**Environment**: Staging(main branch) / Production

<img width="1072" alt="image" src="https://user-images.githubusercontent.com/4461358/177218899-8d7c5d5e-94cb-45e5-a074-32e2c7ef2ff6.png">

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- [ ] Request a reschedule for a booking, then see proper email title and email html content.

## Checklist

- I haven't added tests that prove my fix is effective or that my feature works

2022-07-05 05:42 UTC, hariombalhara commented
The email received by the organizer when he requests a reschedule contains, "Manage this event" link which doesn't make sense because the booking is cancelled, so it can't be rescheduled
<img width="848" alt="Screenshot 2022-07-05 at 10 03 25 AM" src="https://user-images.githubusercontent.com/1780212/177256454-53a33ba1-202d-4188-9e06-32dcc933f5da.png">

Also, the link received by the booker in the Email for request reschedule takes the user to the app homepage instead of the event's booking page - See https://www.loom.com/share/f978ae1041f44ddaafa8ff38f27bc98b

2022-07-05 18:18 UTC, alannnc commented
@hariombalhara Thanks for your comments, the issues you mention should be solved now.

2022-07-06 11:59 UTC, hariombalhara commented
Looks good now.

2022-07-06 11:59 UTC, hariombalhara approved these changes

2022-07-07 01:24 UTC, zomars requested changes

2022-07-07 22:24 UTC, zomars approved these changes

2022-07-07 22:25 UTC, merged