Add getSchedule tests
calcom/cal.com pull request #3233
Opened 2022-07-05 09:51 UTC by hariombalhara

Adds integration tests for getSchedule.
Define scenarios directly in DB, External Calendar and expect slots
<img width="1012" alt="Screenshot 2022-07-20 at 7 01 42 PM" src="https://user-images.githubusercontent.com/1780212/179994948-1627d286-5e20-4249-a41e-a5b4a28180e6.png">
.

2022-07-20 17:12 UTC, zomars reviewed
Looking good so far. Testing...

2022-07-20 17:12 UTC, zomars commented on packages/lib/availability.ts
> +  // console.log("Availability in getWorkingHours", availability);
```suggestion
```

2022-07-20 17:12 UTC, zomars commented on packages/lib/availability.ts
> +
```suggestion
```

2022-07-20 17:25 UTC, zomars requested changes
- Should we include a `.env.test.example`?
- If not, we should add to the README how to run the test locally.

2022-07-21 05:30 UTC, hariombalhara commented
Added README and .env.test.example.

2022-07-21 16:43 UTC, zomars commented on package.json
> +    "test-e2e": "turbo run test --scope=\"@calcom/web\" && yarn turbo run test-e2e --scope=\"@calcom/web\" --concurrency=1",
Do we want to run this together? Can we run them on parallel on CI instead?

2022-07-21 16:44 UTC, zomars approved these changes

2022-07-21 16:44 UTC, merged