Display correct time format on availability page
calcom/cal.com pull request #3441
Opened 2022-07-19 15:35 UTC by joeauyeung

## What does this PR do?

This PR displays the proper time format on the availability page.

Fixes #2082

**Environment**: Staging(main branch) / Production

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

- Go to create a booking and choose a date
- The times displayed should be in 12h or 24h depending on your location

## Checklist

- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

2022-07-19 18:33 UTC, zomars requested changes
Leaving a video review, this PR is not addressing the expected behavior.

We should prioritize the user settings over the browser defaults

https://www.loom.com/share/4a3d3f8eb52f456882cc55e59a98521e

2022-07-20 13:42 UTC, joeauyeung commented
> Leaving a video review, this PR is not addressing the expected behavior.
> 
> We should prioritize the user settings over the browser defaults
> 
> [loom.com/share/4a3d3f8eb52f456882cc55e59a98521e](https://www.loom.com/share/4a3d3f8eb52f456882cc55e59a98521e)

Thanks for the video, helps a lot for context. Just to confirm when displaying available times we should see if there are user settings available and use that time format option. If no user found, then use the browser locale to set the time format.

2022-07-20 17:23 UTC, zomars commented
> > Leaving a video review, this PR is not addressing the expected behavior.
> > We should prioritize the user settings over the browser defaults
> > [loom.com/share/4a3d3f8eb52f456882cc55e59a98521e](https://www.loom.com/share/4a3d3f8eb52f456882cc55e59a98521e)
> 
> Thanks for the video, helps a lot for context. Just to confirm when displaying available times we should see if there are user settings available and use that time format option. If no user found, then use the browser locale to set the time format.

Yes, we could take this a step further and add a "Use browser default settings" as an option, similarly on how we use it for our dark/light mode dropdown.

2022-07-21 17:43 UTC, joeauyeung commented on apps/web/lib/timeFormat.ts
> +  }
Grabbing from local storage is now used in all areas this function is called

2022-07-21 17:43 UTC, joeauyeung commented on apps/web/lib/timeFormat.ts
> +  }
Write to localStorage based on browser locale

2022-07-21 17:43 UTC, joeauyeung commented on apps/web/lib/timeFormat.ts
> +  }
If not already in localStorage set the value

2022-07-21 17:43 UTC, joeauyeung commented on apps/web/pages/getting-started.tsx
> +
When completing onboarding grab the browser locale and set it to localStorage

2022-07-21 17:43 UTC, joeauyeung commented on apps/web/pages/getting-started.tsx
> +      timeFormat: browserTimeFormat,
Also set the browser locale in the db

2022-07-21 17:43 UTC, joeauyeung commented on apps/web/pages/settings/profile.tsx
> +    window.localStorage.setItem("timeOption.is24hClock", selectedTimeFormat.value === 12 ? "false" : "true");
When changing the time format in the settings page also saves the selection to localStorage

2022-07-26 18:02 UTC, zomars approved these changes
Tested and is working flawlessly. Nice work @joeauyeung

2022-07-26 18:02 UTC, merged