When no location, defaults to cal video
calcom/cal.com pull request #3517
Opened 2022-07-25 08:25 UTC by om-ray

## What does this PR do?

Currently, if an event type does not have a location set for it, the email that is sent will have an empty `Where` heading with no text that tells you what platform the meeting will be on. This PR solves that issue by defaulting to Cal video instead of just having no location set.

Fixes #2900 

**Environment**: Staging(main branch) / Production

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)

2022-08-01 08:05 UTC, PeerRich commented
we'll review today!

2022-08-01 17:31 UTC, om-ray commented
@PeerRich Thank you!

2022-08-01 19:22 UTC, zomars requested changes
Thank you for your contribution 🙏 Let's leave the `yarn.lock` out of the PR

2022-08-01 19:22 UTC, zomars commented on packages/app-store/exchange2013calendar/lib/CalendarService.ts
> +import { LocationType } from "../../locations";
This type is not being used

2022-08-01 19:22 UTC, zomars commented on packages/app-store/exchange2016calendar/lib/CalendarService.ts
> +import { LocationType } from "../../locations";
```suggestion
```

2022-08-01 19:22 UTC, zomars commented on packages/app-store/exchange2013calendar/lib/CalendarService.ts
> +import { LocationType } from "../../locations";
```suggestion
```

2022-08-02 17:50 UTC, zomars commented
@om-ray The lock file is still present

2022-08-02 18:11 UTC, om-ray commented
@zomars when i remove the lockfile the checks fail, but ill delete it if thats fine

2022-08-02 18:16 UTC, zomars commented
@om-ray I don't mean to delete the file. I mean to undo the changes and leave it the same as the `main` branch.

2022-08-02 18:16 UTC, om-ray commented
@zomars ahhh that makes more sense, ill do that right now

2022-08-02 18:57 UTC, om-ray commented
@zomars had a little trouble with it, but its gone now!

2022-08-02 19:38 UTC, zomars requested changes
BTW we can achieve the same behavior by using a zod transform

2022-08-02 19:38 UTC, zomars commented on packages/trpc/server/routers/viewer/bookings.tsx
>        newLocation: z.string(),
```suggestion
      newLocation: z.string().transform((val) => val || LocationType.Daily),
```

2022-08-02 19:38 UTC, zomars commented on packages/trpc/server/routers/viewer/bookings.tsx
> +      input.newLocation === "" ? { bookingId: input.bookingId, newLocation: LocationType.Daily } : input;
```suggestion
      const { bookingId, newLocation: location } = input;
```

2022-08-03 15:34 UTC, zomars approved these changes
Thank you for your contribution 🙏

2022-08-03 15:35 UTC, merged