Fix/office365 api call
calcom/cal.com pull request #3534
Opened 2022-07-26 20:49 UTC by alannnc

## What does this PR do?

Properly handle all Microsoft api graph statuses.

- Status 429 retry-after header.
- A case where an html was returned in response body.
- Status 200 with odata.nextLink with next page data url.

Fixes #3310 

**Environment**: Staging(main branch) / Production

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- [ ] Test A: You need to create several busy events on your office calendar so it can handle multiple result pages.
- [ ] Test B: Create a duplicate selected calendar which ID doesn't exist on your calendar. Now it should handle an error while getting a 404 calendar.

## Checklist

- I haven't performed a self-review of my own code and corrected any misspellings
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't added tests that prove my fix is effective or that my feature works

2022-07-26 20:50 UTC, alannnc commented on packages/app-store/office365calendar/lib/CalendarService.ts
> +
New interfaces for any object used on office calendar service.

2022-07-26 20:51 UTC, alannnc commented on packages/app-store/office365calendar/lib/CalendarService.ts
> +  private accessToken: string | null = null;
Made this a private value so it can be access while using any private function without passing it as parameter.

2022-07-26 20:52 UTC, alannnc commented on packages/app-store/office365calendar/lib/CalendarService.ts
> -        });
Nos this await its a reusable function.

2022-07-26 20:53 UTC, alannnc commented on packages/app-store/office365calendar/lib/CalendarService.ts
> +    settledResponses?.forEach((response) => {
Separate already responses with new requests to be called later.

2022-07-26 20:59 UTC, alannnc commented on packages/lib/errors.ts
> +  }
When microsoft api graph request it's to large it gets here as gzip compressed. We should then use response.text(). It shouldn't affect other services.

2022-07-26 21:20 UTC, alannnc commented on packages/app-store/office365calendar/lib/CalendarService.ts
> +        return result;
@TODO: avoid const and return directly

2022-07-26 21:57 UTC, zomars approved these changes

2022-07-26 22:36 UTC, joeauyeung approved these changes
This is such an awesome PR, great job @alannnc! 

Context for anyone else reviewing. Here are the request limits for Outlook
![image](https://user-images.githubusercontent.com/65426560/181124017-963b7267-1d3d-42c2-8c80-8e10e64cc9d7.png)

2022-07-26 22:36 UTC, joeauyeung commented on packages/app-store/office365calendar/lib/CalendarService.ts
> +    return [...alreadySuccess, ...newSettledResponses];
This is so cool!

2022-07-26 22:43 UTC, alannnc commented
@joeauyeung 
> Context for anyone else reviewing. Here are the request limits for Outlook 
I think we should be using Microsoft API Graph limits and also batching has its own throttling.
<img width="929" alt="image" src="https://user-images.githubusercontent.com/4461358/181124732-a2d44927-c23f-41a8-948d-67635058a5fd.png">

2022-07-27 01:50 UTC, zomars requested changes
Made some legibility fixes. Code looking good, other than that. Since we're changing `handleJsonError` build is breaking on other VideoApiAdapters. Let's fix those before merging.

2022-07-27 02:09 UTC, zomars commented
<img width="1257" alt="image" src="https://user-images.githubusercontent.com/3504472/181145090-fc6a712d-0ea4-4a7b-bfa0-ee31153d21d3.png">

2022-07-27 18:08 UTC, zomars approved these changes

2022-07-27 19:12 UTC, merged