Fixes unique constraint error of batchId when scheduling emails
calcom/cal.com pull request #3542
Opened 2022-07-27 03:23 UTC by CarinaWolli

## What does this PR do?

This PR creates a unique batchId for each message that is scheduled so the database can be successfully updated. It also adds a missing response for `api/cron/workflows/scheduleEmailReminders` and `api/cron/workflows/scheduleSMSReminders`.

Fixes the following issue:
If we scheduled several messages, the following update failed as the batchId has a unique constraint (but it wasn't unique): 

<img width="361" alt="Screenshot 2022-07-26 at 23 01 24" src="https://user-images.githubusercontent.com/30310907/181151458-3ac0e1eb-9833-4b87-88b9-928a48e1cdc3.png">

**Environment**: Staging(main branch) / Production

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist

- I haven't added tests that prove my fix is effective or that my feature works

2022-07-27 11:33 UTC, hariombalhara requested changes
Looks good apart from the concerns I raised. Blocking because one of them can be a potential bug

2022-07-27 14:19 UTC, zomars commented on apps/web/ee/pages/api/cron/workflows/scheduleEmailReminders.ts
> +          await prisma.workflowReminder.updateMany({
Yup. This won't work as expected

2022-07-27 18:34 UTC, zomars reviewed
I'll delegate my approval to @hariombalhara Overall nice work @CarinaWolli

2022-07-27 19:43 UTC, CarinaWolli commented on apps/web/ee/pages/api/cron/workflows/scheduleEmailReminders.ts
> +              id: reminder.id,
The ID is unique, I changed updateMany to update. Made the changes also in scheduleSMSReminders.ts

2022-07-30 06:41 UTC, CarinaWolli commented
Implemented the feedback and resolved merge conflicts, it's ready for another round of review 🙏 @zomars @hariombalhara

2022-07-30 15:42 UTC, zomars approved these changes

2022-07-30 15:42 UTC, zomars commented on packages/features/ee/workflows/api/scheduleSMSReminders.ts
> +  for (const reminder of unscheduledReminders) {
I'm assuming we don't care about these updates being run out of order right? If that's so then LGTM. We can either:
- [Run them in serial](https://decembersoft.com/posts/promises-in-serial-with-array-reduce/) or...
- Run them in parallel with Promise.all

2022-08-01 10:20 UTC, hariombalhara approved these changes

2022-08-01 10:20 UTC, merged