fix: cancel booking buttons design
calcom/cal.com pull request #3748
Opened 2022-08-08 21:01 UTC by Udit-takkar

Fixes #3702 

<img width="478" alt="Screenshot 2022-08-09 at 2 30 33 AM" src="https://user-images.githubusercontent.com/53316345/183513705-5626fc25-dc21-46ce-9f9d-87553cfd6aca.png">

2022-08-08 22:38 UTC, CarinaWolli requested changes
Thank you for your contribution! Let's address the two comments I made before merging

2022-08-08 22:38 UTC, CarinaWolli commented on apps/web/components/booking/CancelBooking.tsx
> +                className="rounded-md"
```suggestion
```

I think we should keep the old Button format for now. (https://github.com/calcom/cal.com/issues/3702#issuecomment-1208499417 this is already the new design)

2022-08-08 22:38 UTC, CarinaWolli commented on apps/web/components/booking/CancelBooking.tsx
> +                className="flex grow justify-center rounded-md"
```suggestion
                className="flex grow justify-center"
```
Same here

2022-08-09 18:08 UTC, CarinaWolli approved these changes
Looks good now 👍

2022-08-09 18:23 UTC, merged

2022-08-09 18:27 UTC, Udit-takkar commented
@CarinaWolli thanks for reviewing