(Conditionally) remove HTML from event description
calcom/cal.com pull request #378
Opened 2021-07-21 23:09 UTC by Nico-J

Good evening,

Earlier, we were encountering the problem that users of certain calendar tools, such as Apple Calendar, were seeing raw HTML tags in their event description, because obviously HTML seems not to be supported in those tools.

**So just remove that HTML stuff, replace `<br />` with `\n` and we're good to go, huh?**

Well, then the web version of Outlook Calendar doesn't support newline characters. It just strips them out. **Even the Windows-related `\r` newline character.**
It looks like this:
![image](https://user-images.githubusercontent.com/14024119/126570005-afdd0c0b-e348-4e39-a78b-84f14ffeaf9a.png)

Meanwhile, Google Calendar pretty much likes newline characters in plain text events:
![image](https://user-images.githubusercontent.com/14024119/126570089-73301ad5-6703-4cc9-910c-bd6b462caf84.png)

**So what do we do?**
I decided to conditionally use either the HTML-based version (for Outlook events) or the newline-based version (for everything else) of the event text when creating it. See the code (line 511 and following in calendarClient.ts) for more information.

Works in Outlook:
![image](https://user-images.githubusercontent.com/14024119/126570742-9a5eced5-a23c-440e-a6a3-6072485a865d.png)

And in Google:
![image](https://user-images.githubusercontent.com/14024119/126570775-fb71ccc4-f114-41f7-83e2-08607a90982f.png)

**But there's still an unsolved problem:**
Apple Calendar is just a tool that uses other integrations, such as Google or Outlook Calendar (or iCloud). So this PR doesn't solve the Apple Calendar issues, since we don't know which software the user is using.

We have the following options:
1. Just **always** throw away the HTML, leading to a quite "ugly" event description in Outlook Web, but saving the view for Apple Calendar.
2. Keep the conditional HTML usage: @Malte-D Could you test this PR with your Apple Calendar? I don't have a Mac right now. Maybe Outlook parses the HTML correctly and delivers a "working" version to Apple Calendar? Needs investigation!
3. Make an "opt-in" to let the user decide whether to use HTML descriptions or not.

Right now, this PR contains option 2. Please share your opinion about that with me. :)

2021-07-22 10:34 UTC, baileypumfleet commented
This code switches between HTML and plaintext based on the organiser's calendar integration (if it's Outlook or Google Calendar), however the invitee's calendar may or may not support HTML. For instance, if you on Google Calendar send me an invite with HTML, as I'm on Apple Calendar, it won't work for me. I think we may have to just send plaintext invites only. Great work though with this PR :)

2021-07-22 10:39 UTC, PeerRich commented
Until further I think we should do plaintext. No switches, no settings. Normal line breaks work for everyone right?

2021-07-22 10:39 UTC, PeerRich requested changes
for now, plaintext only with line-breaks

2021-07-24 19:25 UTC, Nico-J commented
Alright, I've changed the code to always use plain text now. In addition, I've added another RegEx to correctly strip down <a href="mailto:....">..</a> links. Before that, the "mailto:" part was kept there.

2021-07-25 19:48 UTC, PeerRich approved these changes

2021-07-25 19:49 UTC, PeerRich commented
@baileypumfleet can you run, review, then merge? :)

2021-07-26 09:15 UTC, baileypumfleet approved these changes

2021-07-26 09:15 UTC, merged