Disable broken calendar email
calcom/cal.com pull request #3946
Opened 2022-08-24 16:52 UTC by joeauyeung

## What does this PR do?

This PR disables the alarm system email for calendars as it needs a deeper investigation.

Fixes # (issue)

**Environment**: Staging(main branch) / Production

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

2022-08-24 17:01 UTC, alannnc commented on packages/core/CalendarManager.ts
> +        // await sendBrokenIntegrationEmail(calEvent, "calendar");
```suggestion
        // @TODO: This code will be off till we can investigate an error with it
        // await sendBrokenIntegrationEmail(calEvent, "calendar");
```

2022-08-24 17:01 UTC, alannnc commented on packages/core/CalendarManager.ts
> +            // await sendBrokenIntegrationEmail(calEvent, "calendar");
```suggestion
            // @TODO: This code will be off till we can investigate an error with it
            // await sendBrokenIntegrationEmail(calEvent, "calendar");
```

2022-08-24 17:02 UTC, alannnc requested changes
Looks good, probably I would add a ticket number on the TODO comment

2022-08-26 18:12 UTC, zomars approved these changes

2022-08-26 18:12 UTC, zomars commented on packages/core/CalendarManager.ts
> +        // await sendBrokenIntegrationEmail(calEvent, "calendar");
```suggestion
        log.error("createEvent failed", error, calEvent);
        // @TODO: This code will be off till we can investigate an error with it
        //https://github.com/calcom/cal.com/issues/3949
        // await sendBrokenIntegrationEmail(calEvent, "calendar");
```

2022-08-26 18:12 UTC, zomars commented on packages/core/CalendarManager.ts
> +            // await sendBrokenIntegrationEmail(calEvent, "calendar");
```suggestion
            // @TODO: This code will be off till we can investigate an error with it
            // @see https://github.com/calcom/cal.com/issues/3949
            // await sendBrokenIntegrationEmail(calEvent, "calendar");
```

2022-08-26 18:12 UTC, merged