Forbid reserved keywords as usernames
calcom/cal.com pull request #3968
Opened 2022-08-25 16:05 UTC by afzalsayed96

## What does this PR do?

Prevents registering key username such as `jobs`

<img width="479" alt="Screenshot 2022-08-25 at 8 19 53 PM" src="https://user-images.githubusercontent.com/14029371/186715104-045b1b44-795a-4bde-b823-f498ae9f9275.png">

![image](https://user-images.githubusercontent.com/14029371/186714392-9b163e1c-cc43-4762-93be-abf9affa43f6.png)

2022-08-25 16:07 UTC, afzalsayed96 commented on packages/features/ee/common/lib/checkPremiumUsername.ts
> +  if (username in FORBIDDEN_USERNAMES) {
Assuming `key in object` will be faster than `array.includes(string)`

2022-08-25 16:08 UTC, afzalsayed96 commented on packages/features/ee/common/lib/checkPremiumUsername.ts
> +      message: "A user exists with that username",
This message can be changed

2022-08-25 16:09 UTC, afzalsayed96 commented on packages/lib/constants.ts
> +};
Not exhaustive but covers most clashes with current website pages

2022-08-25 20:46 UTC, PeerRich commented
cool idea! luckily those accounts dont affect website behaviour but its probably a good idea

2022-08-25 20:47 UTC, PeerRich commented
alternatively we can just create accouts for each page that we create. not clean but also gets the job done

2022-08-31 21:04 UTC, zomars requested changes
Thank you for your contribution 🙏 

- I would rather have this at a per-database level since self-hosted shouldn't have to worry about this.
- We already have some guards on our private website repo
- I'd rather have as less hardcoding as possible

2022-09-02 11:19 UTC, closed without merging