a ton of mobile improvements to save space
calcom/cal.com pull request #4336
Opened 2022-09-09 12:42 UTC by PeerRich

- reduced column size in /booking
- made AppBar and Bottom Nav fixed with frosted glass on mobile
- hiding headline and description on mobile
- fixed CTA on bottom right on mobile

/bookings before:

<img width="1029" alt="CleanShot 2022-09-09 at 14 45 57@2x" src="https://user-images.githubusercontent.com/8019099/189353007-8b5788db-de2b-4c05-806c-2f246aba5679.png">

/bookings after:
<img width="1031" alt="CleanShot 2022-09-09 at 14 46 10@2x" src="https://user-images.githubusercontent.com/8019099/189353043-ffcdc73e-d9ec-440a-be3f-8be3c2b5003a.png">

demo:
https://user-images.githubusercontent.com/8019099/189352382-3b890ca2-89e3-46b7-8f2f-fbe38d89132c.mp4

recorded on iPhone 12 Mini:

https://user-images.githubusercontent.com/8019099/189358338-18d6654c-4842-4d78-8c4e-a2f9a9198ed7.mp4

2022-09-09 13:32 UTC, sean-brydon approved these changes
Super clean :)

2022-09-09 13:51 UTC, emrysal commented on apps/web/styles/globals.css
> +  .cta{
```suggestion
  .cta {
```

2022-09-09 14:20 UTC, emrysal requested changes, later dismissed
Unit test fail

2022-09-09 14:30 UTC, emrysal submitted a review, later dismissed
Definitely a unit test issue, the clarity could be improved though.

```
TypeError: window.getEmbedTheme is not a function

      372 | if (isBrowser) {
      373 |   const url = new URL(document.URL);
    > 374 |   embedStore.theme = (window.getEmbedTheme() || "auto") as UiConfig["theme"];
```

2022-09-09 15:02 UTC, merged

2022-09-10 16:06 UTC, PeerRich commented
thank you for merging!