Fix 500 error when trying to cancel a booking that was already cancelled.
calcom/cal.com pull request #434
Opened 2021-08-10 08:57 UTC by joshsny

This PR fixes issue #387.

Cancelling an event that was already cancelled returned a 500 error, instead, it now displays the following page:

<img width="905" alt="Screenshot 2021-08-10 at 10 56 20" src="https://user-images.githubusercontent.com/7135900/128838398-58b44441-5313-456a-8366-52a6d573030f.png">

Unfortunately, I lumped this in with a previous PR #429, please feel free to remove the changes from the `pages/availability/troubleshoot.tsx` file.

2021-08-11 22:18 UTC, Nico-J requested changes
Hey Joshua,
Thank you very much for your PR. :) I've tested it and the "already canceled" message works fine. :+1: 
Though, the "API flooding" issue has not been resolved in my case. I've made a suggestion that fixes it for me. Could you include that in your PR?

In addition, the availability endpoint is currently broken in some cases. There's already another PR that is going to fix that. With both fixes combined, the troubleshooting page works like a charm:

![image](https://user-images.githubusercontent.com/14024119/129110742-e52bdc72-aeb0-4c03-829f-fd2b9c6865f4.png)

2021-08-11 22:18 UTC, Nico-J commented on pages/availability/troubleshoot.tsx
> +  });
Regarding your fix for the API-flooding loop:
I tested your code (current state from your branch) and it doesn't fix it, at least for me - it still refreshes forever and floods the API. However, when watching `selectedDate` in the useEffect closure, it works perfectly for me. :)

```suggestion
  }, [selectedDate]);
```

2021-08-12 04:55 UTC, joshsny commented
Great. Thanks for that suggestion @Nico-J :)

2021-08-12 10:25 UTC, joshsny commented
Hi @Nico-J,

I found a bug in this PR when testing it again. The cancellation was failing when a booking had not been cancelled, but the event type had already been deleted.

I have gone ahead and fixed that now.

2021-08-12 14:59 UTC, Nico-J approved these changes
Perfect. :) From my side, it's all fine now. :)

2021-08-16 11:31 UTC, merged