Add app store link to EditLocationDialog
calcom/cal.com pull request #4355
Opened 2022-09-10 10:57 UTC by john-afolabi

## What does this PR do?

Adds "can't find the right video app? visit our app store" to EditLocationDialog 

Fixes #4298 

**Environment**: Staging(main branch) / Production

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

2022-09-12 08:25 UTC, sean-brydon commented
@john-afolabi  looks great - nice job! 

Only thing is this should be in the V2 component for this file (Our fault we didn't mention it on the ticket) 

Would you be able to remove the change from the 

V1:
`apps/web/components/dialog/EditLocationDialog.tsx`

and add it to the V2 file:
`apps/web/components/v2/eventtype/EditLocationDialog.tsx`

2022-09-12 08:25 UTC, sean-brydon requested changes
See comment

2022-09-12 18:10 UTC, john-afolabi commented
> See comment



> @john-afolabi looks great - nice job!
> 
> Only thing is this should be in the V2 component for this file (Our fault we didn't mention it on the ticket)
> 
> Would you be able to remove the change from the
> 
> V1: `apps/web/components/dialog/EditLocationDialog.tsx`
> 
> and add it to the V2 file: `apps/web/components/v2/eventtype/EditLocationDialog.tsx`

Done, thank you!

2022-09-14 10:19 UTC, hariombalhara requested changes

2022-09-14 10:19 UTC, hariombalhara commented on apps/web/public/static/locales/en/common.json
> +  "cant_find_the_right_video_app": "Can't find the right video app? Visit our",
Maybe see how `broken_video_action` is implemented. 
"Can't find the right video app? Visit our App Store" should be a single sentence for translation. Breaking and concatenating strings after translation can have completely wrong meaning in some languages.

2022-10-05 20:00 UTC, closed without merging

2022-10-05 20:00 UTC, PeerRich commented
closed due to inactivity and unaddressed requested changes