feat: 4232 - new theme toggle design.
calcom/cal.com pull request #4371
Opened 2022-09-11 20:57 UTC by JeroenReumkens

## What does this PR do?

Adds new design for theme ligt/dark mode toggle. 

Fixes #4232 

<img width="1266" alt="Screenshot 2022-09-11 at 22 54 17" src="https://user-images.githubusercontent.com/2969573/189548454-6e45469d-1636-43a3-9cef-fcebcf0306e2.png">
<img width="441" alt="Screenshot 2022-09-11 at 22 54 43" src="https://user-images.githubusercontent.com/2969573/189548466-b0af257f-9217-4367-88c7-f9ed0f70b7d3.png">

**Environment**: Staging(main branch)

## Type of change
- [ ] New feature (non-breaking change which adds functionality)

## How should this be tested?

- [ ] Verify that design matches design shown in #4232
- [ ] Verify that light / dark / system toggle still functions correctly.

## UI question

- [ ] @Jaibles Could you please create the SVG's without the rounded borders? By adding them in CSS they always match the border perfectly. When they are applied via the SVG you sometimes see a bit of ugly whitespace between the border and the svg itself. I you could share them, I will still incorporate them in this PR — Thanks 😄

2022-09-11 21:13 UTC, Jaibles commented
Looks perfect @JeroenReumkens 👍

2022-09-12 09:48 UTC, Jaibles commented
@JeroenReumkens here are the svgs with no border-radius as requested. Let me know if you need anything else!

![theme-dark](https://user-images.githubusercontent.com/4536123/189624186-bf703df9-af57-4ab0-8961-4405c0728b37.svg)
![theme-light](https://user-images.githubusercontent.com/4536123/189624191-f7bb65b7-fb64-4688-bc75-1d41d004d5e7.svg)
![theme-system-default](https://user-images.githubusercontent.com/4536123/189624193-4d879798-9d5e-444a-8456-9a130911f723.svg)

2022-09-12 10:14 UTC, JeroenReumkens commented
Thanks @Jaibles  New SVG's have been added 😄  

Ready for review!

2022-09-12 10:50 UTC, sean-brydon requested changes
Active state seems to be lost when I change between radio items 

also the selected state could be rounded too to match the images

2022-09-12 12:27 UTC, JeroenReumkens commented
Focus styling indeed wasn't working properly in Safari. This has been fixed in the latest commit 🔥

2022-09-12 12:34 UTC, sean-brydon approved these changes
Working perfectly now - nice job!

2022-09-14 07:15 UTC, merged