feat: CustomEventType placeholder and API fixes
calcom/cal.com pull request #446
Opened 2021-08-13 14:42 UTC by mihaic195

- Feat: Text/Multiline Text Custom Inputs can have (optional) placeholders to display on booking page
- Fix: if custom inputs existed on a specific event type, the event type cannot be deleted due to DB association

![Screenshot 2021-08-13 at 17 39 26](https://user-images.githubusercontent.com/34626017/129374265-cbb25a78-dd25-439a-94e6-589268cb260b.png)
![Screenshot 2021-08-13 at 17 39 41](https://user-images.githubusercontent.com/34626017/129374280-7cde8ecd-804b-47c8-83a9-aae34033b554.png)
![Screenshot 2021-08-13 at 17 40 22](https://user-images.githubusercontent.com/34626017/129374291-0c0b3af0-d771-4ccf-b3e2-cbb7b2ead64b.png)
![Screenshot 2021-08-13 at 17 40 48](https://user-images.githubusercontent.com/34626017/129374299-6f1b03f6-3ae5-437d-bf71-3a7c78fedc24.png)

2021-08-13 19:21 UTC, emrysal requested changes
<div class="loom-thumb-embed"><p><b>My beautiful event type | Event Type | Calendso</b> - <a target="_blank" href="https://www.loom.com/share/0048e55731ca4c92b30cbddd2656e523">Watch Video</a></p><a class="lo-gmail-video-thumb" href="https://www.loom.com/share/0048e55731ca4c92b30cbddd2656e523?utm_medium=gif" target="_blank"><img style="max-width:300px;" src="https://cdn.loom.com/sessions/thumbnails/0048e55731ca4c92b30cbddd2656e523-with-play.gif"></a></div>

2021-08-13 19:21 UTC, emrysal commented on pages/event-types/[type].tsx
> +                          defaultValue={selectedCustomInput?.label}
See attached video, this does not seem right to me.

2021-08-16 08:01 UTC, mihaic195 commented
@emrysal thanks for the code review. I'll update it as soon as your PR https://github.com/calendso/calendso/pull/450 is merged...

2021-08-17 08:44 UTC, baileypumfleet commented
The PR #450 has been merged now. Once you've fixed the conflicts and updated your PR, we can get going :)

2021-08-20 14:14 UTC, emrysal approved these changes
Minor tweak, otherwise good, approved

2021-08-20 14:14 UTC, emrysal commented on pages/event-types/[type].tsx
> +                    selectedInputOption.value == EventTypeCustomInputType.TEXTLONG) && (
===

2021-08-20 14:15 UTC, mihaic195 commented on pages/event-types/[type].tsx
> +                    selectedInputOption.value == EventTypeCustomInputType.TEXTLONG) && (
Nice one! 😁

2021-08-22 13:06 UTC, merged