/event-types /team-detail /scheduling type - double divider under team members
calcom/cal.com pull request #4485
Opened 2022-09-15 02:50 UTC by gitstart

## What does this PR do?

Fixes #4394

## Demo
Before Change
![eventType](https://user-images.githubusercontent.com/46535846/189685901-1cf261be-2483-4517-9d63-85bc681cca9e.png)

After Change
![newEventV2](https://user-images.githubusercontent.com/46535846/189686124-50207d78-3a92-47cc-9095-23c1b4b477fa.png)
**Environment**: Staging(main branch) / Production

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

2022-09-20 11:36 UTC, hariombalhara requested changes

2022-09-20 11:36 UTC, hariombalhara commented on packages/ui/v2/modules/event-types/CheckedTeamSelect.tsx
>        <ul className={classNames("mt-3 rounded-md", value.length >= 1 && "border")} ref={animationRef}>
```suggestion
      <ul className={classNames("mt-3 rounded-md", value.length >= 1 && "border-x border-t")} ref={animationRef}>
```

2022-09-20 11:36 UTC, hariombalhara commented on packages/ui/v2/modules/event-types/CheckedTeamSelect.tsx
> +          <li key={option.value} className={`flex py-2 px-3 ${index === value.length - 1 ? "" : "border-b"}`}>
We can avoid this JS condition by simply forcing no border at bottom for ul

2022-09-28 10:54 UTC, gitstart commented
Hey @hariombalhara! Left a comment [here](https://github.com/calcom/cal.com/pull/4485#discussion_r976644907), please take a look 🙏

2022-09-29 04:16 UTC, hariombalhara approved these changes

2022-10-01 02:59 UTC, merged