add vscode extensions & settings
calcom/cal.com pull request #461
Opened 2021-08-16 15:54 UTC by KATT

2021-08-16 15:59 UTC, KATT commented on .vscode/extensions.json
> +    "yzhang.markdown-all-in-one",
Markdown plugin to make it easier to use `.md`

2021-08-16 15:59 UTC, KATT commented on .vscode/extensions.json
> +    "esbenp.prettier-vscode",
Add prettier

2021-08-16 15:59 UTC, KATT commented on .vscode/extensions.json
> +    "dbaeumer.vscode-eslint",
Add eslint

2021-08-16 15:59 UTC, KATT commented on .vscode/settings.json
> +  "typescript.tsdk": "node_modules/typescript/lib",
Ensure we use the project's typescript version

2021-08-16 15:59 UTC, KATT commented on .vscode/settings.json
> +  "eslint.run": "onSave"
Format + fix linting on save when you save

2021-08-16 16:23 UTC, emrysal commented
I wonder if it is possible to use https://github.com/calendso/calendso/blob/main/.editorconfig for this. After all https://editorconfig.org/ is explicitly supported by vscode (and I believe they are contributors).

https://docs.microsoft.com/en-us/visualstudio/ide/create-portable-custom-editor-options?view=vs-2019

2021-08-16 16:25 UTC, KATT commented
> I wonder if it is possible to use https://github.com/calendso/calendso/blob/main/.editorconfig for this. After all https://editorconfig.org/ is explicitly supported by vscode (and I believe they are contributors).
> 
> https://docs.microsoft.com/en-us/visualstudio/ide/create-portable-custom-editor-options?view=vs-2019

Not for all of it by any means. I.e. the tailwind sorter is super nice to have but I don't think editorconfig/prettier/eslint has something like it [yet]

2021-08-16 16:42 UTC, emrysal commented
What do you think @baileypumfleet

2021-08-17 08:41 UTC, LecrisUT commented
Please also include an appropriate `.gitignore` if this is to be added. Here is the suggestion generated by the Jetbrains plugin:
```
### VisualStudioCode template
.vscode/*
!.vscode/settings.json
!.vscode/tasks.json
!.vscode/launch.json
!.vscode/extensions.json
*.code-workspace

# Local History for Visual Studio Code
.history/
```

2021-08-17 08:45 UTC, LecrisUT requested changes
Please also include an appropriate `.gitignore` if this is to be added. Here is the suggestion generated by the Jetbrains plugin:
```
### VisualStudioCode template
.vscode/*
!.vscode/settings.json
!.vscode/tasks.json
!.vscode/launch.json
!.vscode/extensions.json
*.code-workspace

# Local History for Visual Studio Code
.history/
```

2021-08-18 08:22 UTC, KATT commented
Replaced by #485

2021-08-18 08:22 UTC, closed without merging