feat: animate event list while reordering
calcom/cal.com pull request #4611
Opened 2022-09-19 17:53 UTC by G3root

## What does this PR do?

Fixes #4504

https://www.loom.com/share/8a76c0c2da8a4f24b461bea21577d826

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

2022-09-19 21:18 UTC, emrysal approved these changes

2022-09-19 21:21 UTC, emrysal requested changes
Auto-animate works great but it looks to me like the ordering doesn't happen async to the backend response - I don't believe that part worked; could you have a look @G3root ?

Much appreciated PR!

2022-09-20 13:56 UTC, G3root commented
> Auto-animate works great but it looks to me like the ordering doesn't happen async to the backend response - I don't believe that part worked; could you have a look @G3root ?
> 
> Much appreciated PR!

@emrysal pushed some chnages, here's how now it looks like.
https://www.loom.com/share/912349c0893847a2b93affe0129754f4

2022-09-20 15:53 UTC, emrysal approved these changes

2022-09-20 15:55 UTC, merged