Be more strict
calcom/cal.com pull request #4675
Opened 2022-09-23 07:03 UTC by hariombalhara

It assumes that the following URLs are in this format https://example.com . .env.example confirms it. But if someone has accidentally used something like https://example.com/(note terminating slash), then safeRedirectUrl would return WebApp URL.

CONSOLE_URL
WEBAPP_URL
WEBSITE_URL

<img width="545" alt="Screenshot 2022-09-23 at 12 31 23 PM" src="https://user-images.githubusercontent.com/1780212/191907525-66539b03-f10b-4e00-948b-71d77c260740.png">

2022-09-23 14:15 UTC, emrysal requested changes

2022-09-23 14:15 UTC, emrysal commented on packages/lib/getSafeRedirectUrl.ts
> +  if (![CONSOLE_URL, WEBAPP_URL, WEBSITE_URL].some((u) => u === urlParsed.origin)) {
```suggestion
  if (![CONSOLE_URL, WEBAPP_URL, WEBSITE_URL].some((u) => new URL(u).origin === urlParsed.origin)) {
```

2022-09-24 04:51 UTC, hariombalhara commented on packages/lib/getSafeRedirectUrl.ts
> +  if (![CONSOLE_URL, WEBAPP_URL, WEBSITE_URL].some((u) => u === urlParsed.origin)) {
It's better this way. Thanks

2022-09-24 08:39 UTC, emrysal approved these changes

2022-09-24 08:40 UTC, merged