/getting-started/setup-availability the table of days breaks depending on the language
calcom/cal.com pull request #5104
Opened 2022-10-19 16:13 UTC by gitstart

## What does this PR do?

Fixes #4993

**Environment**: Staging(main branch) / Production

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Demo
Old Version: 
![Captura de tela de 2022-10-13 15-38-54](https://user-images.githubusercontent.com/87545749/195693679-4da16b7e-0376-47dd-a7b6-646add805515.png)

New Version:
![Captura de tela de 2022-10-13 16-19-41](https://user-images.githubusercontent.com/87545749/195693564-415dff38-34a7-4d53-aeee-6af157d46575.png)

2022-10-27 07:20 UTC, JeroenReumkens requested changes, later dismissed
Thank you so much for you work @gitstart  Really valuable change. I added 2 small requests for you that would make it even better I think 🙏

2022-10-27 07:20 UTC, JeroenReumkens commented on packages/features/schedules/components/Schedule.tsx
> +      <div className="flex h-11 w-32 items-center justify-between break-normal">
@gitstart `break-normal` is the default if I'm correct, right? Does add anything here? 
Cool change apart from that, thanks a lot! 🙏

2022-10-27 07:20 UTC, JeroenReumkens commented on packages/features/schedules/components/Schedule.tsx
> +      <div className="flex h-11 w-32 items-center justify-between break-normal">
Could you also make this full width on mobile, and only `w-32` starting at a bigger breakpoint? Makes it a bit nicer on mobile I think!

2022-10-31 09:47 UTC, gitstart commented
Thank you for the review @JeroenReumkens. Requested changes has been made, please take a look

**Demo**
https://www.loom.com/share/673092b6806f444d96656ac40a630b98

2022-10-31 23:15 UTC, PeerRich approved these changes

2022-11-02 11:17 UTC, merged