feature/sentry.io for web
calcom/cal.com pull request #5326
Opened 2022-11-01 23:58 UTC by alannnc

## What does this PR do?

Install sentry.io for web app

**Environment**: Staging(main branch)

## Type of change

- [X] New feature (non-breaking change which adds functionality)

2022-11-02 00:00 UTC, alannnc commented on apps/web/next.config.js
> +};
This shouldn't affect self hosted.

2022-11-02 00:00 UTC, alannnc commented on apps/web/next.config.js
> +  silent: true, // Suppresses all logs
Same as above

2022-11-02 00:00 UTC, alannnc commented on apps/web/next.config.js
> +  ? withSentryConfig(moduleExports, sentryWebpackPluginOptions)
If they don't have any sentry env we should fallback to default export.

2022-11-02 09:55 UTC, JeroenReumkens commented
LGTM @alannnc !

2022-11-02 09:55 UTC, JeroenReumkens approved these changes

2022-11-02 12:03 UTC, hariombalhara requested changes, later dismissed
Blocking this till crash problem is solved. 
https://threads.com/34432396033?s=hDF7phTfHe6ecRWvnwWRV6
https://www.loom.com/share/f3fa835c5d7f4695be1121f271f8dfaa

I have tried cleaning up node_modules and re-installation but this error persists. I am worried that this might break infra users build.

2022-11-02 18:34 UTC, alannnc commented
> LGTM @alannnc !
> 
> Only wondering if the huge update to yarn.lock is a mistake or not?

Thats what I think too just did a clean and fresh install of everything, probably it's not being updated correctly from others and someone has to take it. Help me out and let me know if you generate the same lock.
@JeroenReumkens

2022-11-03 09:06 UTC, JeroenReumkens commented
@alannnc  The only thing if you delete the yarn.lock is that lots of packages get upgraded to a new version, so in theory that could result in stuff being broken because of a package update. I my opinion you usually don't want purge a full yarn lock file, and only update one dependency at a time (which will update that dependency in the lock file as well).

2022-11-03 11:15 UTC, hariombalhara commented
@JeroenReumkens I did a checkout of yarn.lock from main and run a `yarn update` again. The file has pretty less changes now.

2022-11-03 11:28 UTC, hariombalhara commented
<img width="1195" alt="Screenshot 2022-11-03 at 4 58 08 PM" src="https://user-images.githubusercontent.com/1780212/199709514-ac1cd35d-50e8-438c-9c2e-6aa1a4a03ac4.png">
Tested a sample error and it's recorded in Sentry.
merging it now.

2022-11-03 11:28 UTC, merged