fix: update form methods when username is updated
calcom/cal.com pull request #5403
Opened 2022-11-07 17:31 UTC by Udit-takkar

Fixes: https://github.com/calcom/cal.com/issues/5401

Video:- 

https://user-images.githubusercontent.com/53316345/200375806-954ab8a8-08cb-44fe-a52f-cf253c39391c.mov

How to reproduce bug:-
https://threads.com/34432980734?s=ucqt4HpZQcM3tsQmy5m8G5

2022-11-07 19:49 UTC, emrysal commented on apps/web/pages/settings/my-account/profile.tsx
>    const [currentUsername, setCurrentUsername] = useState<string | undefined>(user?.username || undefined);
```suggestion
  const [currentUsername, setCurrentUsername] = useState<string>();
```

2022-11-07 19:56 UTC, emrysal requested changes

2022-11-07 19:56 UTC, emrysal commented on apps/web/pages/settings/my-account/profile.tsx
>    const [inputUsernameValue, setInputUsernameValue] = useState(currentUsername);
This looks to me dependent on currentUsername could be broken

2022-11-07 22:02 UTC, emrysal commented
Opened a PR against this branch @ https://github.com/calcom/cal.com/pull/5405 with a couple of improvements RHF wise.

2022-11-08 14:38 UTC, Udit-takkar commented
@emrysal  there are few issues in the PR after you merged.

- UserSettings component in /gettting-started page also use UsernameAvailability component and on that component we are using user data from getServerSideProps instead of trpc.useQuery(["viewer.me"])  so currentUsername props does not get updated when you save username.

- i can't really fix this refCallback type error. if i change type of RefCallback i cannot access .current prop.

2022-11-08 15:46 UTC, Udit-takkar commented
@emrysal  everything working fine now 👍

2022-11-08 16:24 UTC, emrysal approved these changes

2022-11-08 16:36 UTC, merged