fix: ui bugs in apps
calcom/cal.com pull request #5465
Opened 2022-11-10 15:05 UTC by Udit-takkar

Fixes: #5461 , #5460 

https://user-images.githubusercontent.com/53316345/201128487-3c6ee461-8884-427e-af62-a8a947e5e99a.mov

2022-11-10 15:40 UTC, Udit-takkar commented
<img width="1440" alt="Screenshot 2022-11-10 at 9 10 22 PM" src="https://user-images.githubusercontent.com/53316345/201139337-aeebd3da-9e62-46b5-8a89-ea08a4160580.png">

2022-11-11 08:57 UTC, CarinaWolli requested changes
The image size is still not 40px. Width and height of 28px is coming from the SVG file 
<img width="290" alt="Screenshot 2022-11-11 at 09 52 32" src="https://user-images.githubusercontent.com/30310907/201303474-4dd37be9-8894-46cc-bb29-d075ea54303c.png">

2022-11-11 08:57 UTC, CarinaWolli commented on packages/app-store/_components/AppCard.tsx
> +            <span className="font-semibold leading-none text-black">{app?.name}</span>
```suggestion
            <span className="text-base leading-4 font-semibold leading-none text-black">{app?.name}</span>
```

2022-11-11 08:57 UTC, CarinaWolli commented on packages/app-store/_components/AppCard.tsx
> +            <p className="pt-2 text-sm font-normal text-gray-600">{description || app?.description}</p>
```suggestion
            <p className=" leading-4 pt-2 text-sm font-normal text-gray-600">{description || app?.description}</p>
```

2022-11-11 10:25 UTC, Udit-takkar commented on packages/app-store/_components/AppCard.tsx
> +            <span className="font-semibold leading-none text-black">{app?.name}</span>
done

2022-11-11 10:25 UTC, Udit-takkar commented on packages/app-store/_components/AppCard.tsx
> +            <p className="pt-2 text-sm font-normal text-gray-600">{description || app?.description}</p>
done

2022-11-11 11:20 UTC, Udit-takkar commented
<img width="855" alt="Screenshot 2022-11-11 at 4 48 24 PM" src="https://user-images.githubusercontent.com/53316345/201329769-104f5cdf-78c4-4979-b5c0-650d8f27520e.png">

@CarinaWolli  stripe one is fixed but there are still few of the logos(fathom and google analytics) which are not 40px . don't really know how to fix this. tried setting both height and width to 40px but it still resize.

2022-11-11 12:38 UTC, CarinaWolli approved these changes
Looks good to me now! The logo size seems to be fixed too 🙏

2022-11-11 14:07 UTC, PeerRich approved these changes

2022-11-11 19:35 UTC, merged