fix: use .watch() to disable update btn
calcom/cal.com pull request #5482
Opened 2022-11-11 13:18 UTC by Udit-takkar

Fixes: #5424

https://user-images.githubusercontent.com/53316345/201348407-6136c4ab-4702-4389-95f9-86219027c257.mov

this was suggested by @Jaibles here https://threads.com/34433127474?s=ucqt4HpZQcM3tsQmy5m8G5

2022-11-11 19:20 UTC, zomars requested changes
No need for use `watch` we can just use the `isDirty` property from `formState`

2022-11-11 19:20 UTC, zomars commented on apps/web/pages/settings/my-account/profile.tsx
>      // eslint-disable-next-line @typescript-eslint/no-unused-vars
```suggestion
```

2022-11-11 20:25 UTC, zomars reviewed
![LGTM](https://media0.giphy.com/media/m2Q7FEc0bEr4I/200.gif)

2022-11-11 20:25 UTC, zomars approved these changes

2022-11-11 20:27 UTC, merged

2022-11-12 10:21 UTC, Udit-takkar commented
@zomars  we don't want the update button to be enabled when username is changed because there is already a separate update button for it. isDirty is checking all the fields (including username)

  is there any other way other than .watch() to achieve this?

<img width="901" alt="Screenshot 2022-11-12 at 3 47 12 PM" src="https://user-images.githubusercontent.com/53316345/201469570-21145b92-32ef-4881-85e4-802f809d5935.png">

2022-11-12 17:23 UTC, zomars commented
We should encapsulate the username field in another form. So it can have it's own formstate