fix: add location query variable
calcom/cal.com pull request #5540
Opened 2022-11-15 18:48 UTC by Udit-takkar

Fixes: #5504 

https://user-images.githubusercontent.com/53316345/202000736-136f0895-8c60-445f-a0f9-6ee64cec5246.mov

2022-11-16 10:16 UTC, sean-brydon approved these changes
LGTM - Ship it 🚀

2022-11-23 18:21 UTC, alannnc commented on packages/prisma/zod/custom/eventtype.ts
> +  .partial({ hidden: true,locations: true})
```suggestion
  .partial({ hidden: true, locations: true })
```

2022-11-23 19:06 UTC, alannnc requested changes
Currently not working for location with links working on a fix

2022-11-23 19:17 UTC, alannnc approved these changes
Looks good for now, however this can be improved sending eventTypeId on the modal form, reading it's content and just duplicate data from DB instead of URL every parameter @Udit-takkar

2022-11-23 19:18 UTC, merged