Feature/Routing Forms: Ability to reuse an existing form as a router in a new form creating a connection b/w the two
calcom/cal.com pull request #5566
Opened 2022-11-17 16:30 UTC by hariombalhara

## What does this PR do?

Closes #5508

- This is a live connection and editing the fields and routing in the form being used as Router should be reflected in the new form as well.

Loom Video: https://www.loom.com/share/d0ef3bcaa77c4c84b8159c255e744a14

**Environment**: Production

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

- [ ] Test A
- [ ] Test B

## Checklist

- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't performed a self-review of my own code and corrected any misspellings
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my PR needs changes to the documentation
- I haven't checked if my changes generate no new warnings
- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

2022-11-17 16:31 UTC, hariombalhara commented on packages/lib/logger.ts
> -  minLevel: "warn",
Remove it

2022-11-17 16:32 UTC, hariombalhara commented on packages/prisma/migrations/20221114095200_add_router_table/migration.sql
> +-- CreateTable
Remove all migrations.No migration is required now.

2022-12-12 13:06 UTC, PeerRich reviewed
i wish i knew what was going on here 🤣

2022-12-12 15:01 UTC, CarinaWolli commented
@hariombalhara If F2 has F1 as a router, then I would imagine that when I rename a field in F1 or add a new field in F1, that the changes would also appear in F2. But that's not happening for me, let me know if I am misunderstanding something here

2022-12-12 15:07 UTC, hariombalhara commented
@CarinaWolli yes, that should have worked. Looks like my recent cleanup broke it ;( Will get back to you soon.

2022-12-12 15:41 UTC, hariombalhara commented
@CarinaWolli  Fixed that issue. Thanks for reporting. Really appreciate it 🙏 I will be testing things more and will also add Playwright tests to avoid such regressions.

2022-12-12 15:57 UTC, hariombalhara reviewed
Self review done

2022-12-23 10:30 UTC, CarinaWolli requested changes
Great new feature, it's approved from my side! Requesting changes for now to block merge until after holidays 🎄

2023-01-04 13:00 UTC, CarinaWolli commented
@hariombalhara Let's fix the merge conflicts and then I'll approve 🙏

2023-01-04 13:03 UTC, hariombalhara commented
@CarinaWolli Resolved.

2023-01-04 13:30 UTC, CarinaWolli approved these changes
Great work 🙏

2023-01-04 13:30 UTC, merged