prevent cancellation of past events
calcom/cal.com pull request #568
Opened 2021-09-03 18:25 UTC by Malte-D

2021-09-03 20:25 UTC, emrysal requested changes
This will break when this event is cancelled by an invitee as it expects a connected user loaded from the session, whilst the cancel endpoint `https://github.com/calendso/calendso/blob/main/pages/cancel/[uid].tsx` is linked in the invitee email who is unauthenticated.

Needs a rethink - if you could adjust this change to just tackle the past event cancellation issue (not targetting the authorization component) I suggest postponing the authorization component until we have merged Teams. (As this will also change the situation).

2021-09-06 18:24 UTC, Malte-D commented
@emrysal If the invitee uses this endpoint, the session is just undefined (or null) and then the date will be checked.

2021-09-08 16:32 UTC, emrysal approved these changes

2021-09-10 05:17 UTC, baileypumfleet approved these changes
Looks good to me, sorry this one took a while for me to review

2021-09-28 13:47 UTC, baileypumfleet approved these changes

2021-09-28 14:14 UTC, mihaic195 approved these changes

2021-09-28 17:23 UTC, merged