SMS workflow actions only for Teams
calcom/cal.com pull request #6003
Opened 2022-12-13 13:14 UTC by CarinaWolli

## What does this PR do?

Makes SMS workflow actions only available for paying users (users that belong to a team). For all other users, the SMS actions are disabled in the dropdown. 

Fixes #5916

Loom Video: https://www.loom.com/share/52e13c89ebd2441a9b9ca7519c0d4c5a

**Environment**: Staging(main branch)

2022-12-13 13:18 UTC, CarinaWolli commented on packages/trpc/server/routers/viewer/workflows.tsx
> +            !isSMSAction(oldStep.action) &&
We still allow to edited already existing SMS workflow actions for users that don't belong to a team

2022-12-14 21:57 UTC, zomars commented on packages/trpc/server/routers/viewer/workflows.tsx
> +  }
```suggestion
  return action === WorkflowActions.SMS_ATTENDEE || action === WorkflowActions.SMS_NUMBER;
```

2022-12-14 22:14 UTC, zomars requested changes
Nice work @CarinaWolli. Blocking to make some adjustments. 🙏🏽

2022-12-14 22:14 UTC, zomars commented on packages/trpc/server/routers/viewer.tsx
> +    return (user && user.teams.length > 0) as boolean;
```suggestion
    const membershipCount = await ctx.prisma.membership.count({
      where: { userId: ctx.user.id },
    });
    return membershipCount > 0;
```

We only need to count memberships

2022-12-14 22:14 UTC, zomars commented on packages/features/ee/workflows/components/WorkflowStepContainer.tsx
> +  const actionOptions = getWorkflowActionOptions(t, isTeamsPlan);
How about instead of prop-drilling we get this from the backend directly?

2022-12-14 22:19 UTC, zomars approved these changes
![Ship it](https://media.giphy.com/media/CEIHJK4ympvVe0fAdU/giphy.gif)

2022-12-15 00:11 UTC, merged