added 404 for event types
calcom/cal.com pull request #604
Opened 2021-09-08 11:20 UTC by PeerRich

the previous 404 didn't make sense for 404's of event-types.

![image](https://user-images.githubusercontent.com/8019099/132500435-0d5a9e79-ae4d-4c27-8cfb-d70d47b0fb60.png)

we may wanna extend this to other non-username routes too

2021-09-08 16:18 UTC, emrysal commented
Yes, I think this is an incorrect fix because the main issue is that we have a 404 that we actually only want to apply on first-level 404's, Instead as an alternative fix I would suggest detecting whether the 404 is on root level (like /smurf) and throw a different, generic 404 on second level like /something/generic-404.

2021-09-08 20:41 UTC, PeerRich commented
i agree this was a hotfix because we dont have really other sub paths yet

2021-09-10 21:14 UTC, baileypumfleet requested changes

2021-09-10 21:14 UTC, baileypumfleet commented on pages/404.tsx
> +              <a href="https://checkout.calendso.com" className="inline-block mt-2 text-lg ">
I feel like this shouldn't link to checkout?

2021-09-10 21:41 UTC, baileypumfleet approved these changes

2021-09-10 21:46 UTC, merged