.env for root URL behavior+plausible #6193
calcom/cal.com pull request #6206
Opened 2022-12-28 09:54 UTC by Hybes

## What does this PR do?

Adds 2 .env variables for Self Hosted Plausible URL, as well as root url to redirect users if they access the booking url without a session, this could be set to a particular users booking page, or to a landing page.

Fixes #6193 

**Environment**: Staging(main branch) / Production

## Type of change

- [✓ ] New feature (non-breaking change which adds functionality)
- [ ✓] This change requires a documentation update

## How should this be tested?

Configure the two new .env variables:

PLAUSIBLE_URL
NEXT_PUBLIC_CUSTOM_ROOT_URL

- You can see that traffic now sends to the self hosted Plausible URL, though you must include the full URL address, including the .js file.
- If you access the main WEBAPP_URL now without a session (incognito works), you should see you get redirected to the specified site.

## Checklist

2022-12-28 10:35 UTC, PeerRich commented on .env.example
> +NEXT_PUBLIC_CUSTOM_ROOT_URL="https://cal.com"
this already exists

2022-12-28 10:36 UTC, PeerRich commented on .env.example
> +PLAUSIBLE_URL="https://selfhosted-plausible.cal.com/js/plausible.js"
this should by default be the correct plausible url

2022-12-28 18:16 UTC, Hybes commented
updated to use env variables, not already in use, and to set default plausible URL

2023-01-01 13:08 UTC, PeerRich commented on .env.example
> +ROOT_REDIR_URL="https://cal.com"
this exists already, no?

2023-01-01 13:09 UTC, PeerRich commented
@Hybes we're probably moving all the app settings into a database to not overload our .env

our goal is to have as little .env variables as possible and adding each app-settings into it doesn't seem like a good idea.

will keep this open but we're likely not merging it in this state -- instead we'll implement an "App Manager" where you can change the settings per instance

2023-01-01 13:10 UTC, PeerRich requested changes
blocking until we have moved App-specific .env's into a database (App Manager cc @joeauyeung )

2023-03-07 09:52 UTC, closed without merging