removes unused variables to fix lint errors
calcom/cal.com pull request #6251
Opened 2023-01-03 19:09 UTC by phishy

## What does this PR do?

removes unused variables to fix lint errors

**Environment**: Staging(main branch)

## Type of change

- [x] Chore (refactoring code, technical debt, workflow improvements)

## How should this be tested?

- [ ] ensure the tests pass

## Checklist

2023-01-05 17:51 UTC, zomars commented on apps/web/pages/apps/[slug]/index.tsx
> +  img: ({ src = "", alt = "", ...rest }: JSX.IntrinsicElements["img"]) => (
I think the placeholder is being kept out of the `rest` on purpose.

2023-01-05 17:58 UTC, zomars requested changes
Thank you for your contribution 🙏 let fix the checks first tho.

2023-01-05 18:13 UTC, phishy commented
The checks have so much noise in them they're unreadable.

2023-01-05 18:13 UTC, closed without merging

2023-01-05 18:49 UTC, zomars commented
Care to elaborate @phishy ?

2023-01-05 18:51 UTC, phishy commented
@zomars Sure. Let's play a game called find the error in this pile of words. https://github.com/calcom/cal.com/actions/runs/3849187325/jobs/6557886188

2023-01-05 18:52 UTC, phishy commented
Why use Typescript and linters, if nobody will adhere to them?

2023-01-05 19:10 UTC, zomars commented
> @zomars Sure. Let's play a game called find the error in this pile of words. https://github.com/calcom/cal.com/actions/runs/3849187325/jobs/6557886188

- ctrl + f
- type " error "

<img width="751" alt="image" src="https://user-images.githubusercontent.com/3504472/210861019-9663146c-c350-4a95-9dff-b4dafd9231d8.png">

Any suggestions to improve the error finding experience are always welcome 🙏🏽 

May you be well

2023-01-05 19:28 UTC, phishy commented
My suggestion is to remove all the warning, such that the errors are easier to see.

2023-01-06 10:55 UTC, PeerRich commented
why was this closed? looked like good work no?