chore: add some dx configs
calcom/cal.com pull request #650
Opened 2021-09-15 09:13 UTC by mihaic195

- Enforce usage of `yarn`
- Use LTS of Node: https://nodejs.org/en/
- Other minor configs

2021-09-15 09:17 UTC, emrysal commented
Looks good to me; though we should unlock the nodejs version ASAP.

2021-09-15 09:17 UTC, emrysal approved these changes

2021-09-15 09:31 UTC, KATT requested changes

2021-09-15 09:31 UTC, KATT commented on .prettierignore
> +.github/**/*.yml
Let's keep prettier on these unless you have a good reason?

```suggestion
```

2021-09-15 09:31 UTC, KATT commented on .prettierignore
> +package.json
I like when package.json auto-formats - why would you remove that? :)

```suggestion
```

2021-09-28 20:00 UTC, zomars approved these changes

2021-09-28 20:05 UTC, KATT approved these changes

2021-09-29 09:39 UTC, PeerRich approved these changes

2021-09-29 09:41 UTC, merged