fix: flash of grey while hard reloading app detail page
calcom/cal.com pull request #6554
Opened 2023-01-18 17:23 UTC by G3root

## What does this PR do?

- [x] fixes back button style in app detail view
- [x] fixes flash of grey while hard reloading app detail page - ex: https://app.cal.com/apps/hubspot

button after:
![Screenshot 2023-01-18 22:51:37](https://user-images.githubusercontent.com/84864519/213250954-7df2faf2-7b5c-4fe9-b153-defee1c5172a.png)

 

**Environment**: Staging(main branch) / Production

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

- [ ] Test A
- [ ] Test B

## Checklist

- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't performed a self-review of my own code and corrected any misspellings
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my PR needs changes to the documentation
- I haven't checked if my changes generate no new warnings
- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

2023-01-18 19:18 UTC, zomars requested changes

2023-01-18 19:18 UTC, zomars commented on apps/web/components/apps/App.tsx
> +    <Shell large heading={t("app_store")} backPath="/apps" withoutSeo>
Try this link in a private window: https://cal-git-fix-appstore-flash-cal.vercel.app/apps/hubspot

2023-01-19 01:45 UTC, G3root commented on apps/web/components/apps/App.tsx
> +    <Shell large heading={t("app_store")} backPath="/apps" withoutSeo>
the issue was with the kbar. brought back the isPublic prop and pushed some more changes.

2023-01-21 17:14 UTC, PeerRich commented
@emrysal can you review this? you have the most experience with the public app store page

2023-01-21 17:27 UTC, emrysal commented
One thing that I think we should fix too is the display of the sidebar during load on https://cal-git-fix-appstore-flash-cal.vercel.app/apps/basic - @PeerRich This PR or follow up? (I'd say this PR as it fixes similar issues)

2023-01-23 06:16 UTC, G3root commented
@emrysal i think this has been fixed from some other PR. pushed the latest main to the PR and it seem good now https://cal-5whv607bg-cal.vercel.app/apps/basic

2023-01-23 09:57 UTC, PeerRich commented
so I guess we can close this?

2023-01-24 19:10 UTC, zomars commented
Closing for now

2023-01-24 19:10 UTC, closed without merging