[CAL-845] Improve the custom event name modal UI/UX
calcom/cal.com pull request #6660
Opened 2023-01-24 09:38 UTC by gitstart-calcom

## What does this PR do?

Fixes #6592

## Demo
https://www.loom.com/share/3a4befcf3f0244e3a093e4fd4bdd6282

<img width="615" alt="Screenshot 2023-01-24 at 3 03 29 PM" src="https://user-images.githubusercontent.com/31402501/214255827-9ea74346-ac61-45b5-a935-cbcc30adfe6a.png">

**Environment**: Staging(main branch) / Production

2023-01-24 09:46 UTC, PeerRich commented
I think the idea was that the preview will update, no @Jaibles ?

2023-01-24 09:46 UTC, PeerRich commented on apps/web/components/eventtype/EventAdvancedTab.tsx
> +              <img alt={t("preview")} src="/api/app-store/zapier/CalendarPreview.svg" />
I think this was meant to update, not be an SVG. Also wrong folder

2023-01-24 10:11 UTC, Jaibles commented
@PeerRich @gitstart-calcom yes, sorry for not being more explicit - the preview should take the real content. 

Obviously, in the case of the scheduler, that won't be available so it should just use what's in the table so should just read:
**Design chat between Alex Fisher and {Scheduler}**

2023-01-25 09:18 UTC, emrysal submitted a review, later dismissed
Changes requested by @PeerRich and a conflict to resolve, marking accordingly.

2023-01-25 13:05 UTC, gitstart-calcom commented
Hi @Jaibles, what should be the behavior of the Preview text? Should it update just after a user finishes editing the event name or after the event is saved (current behavior)? It would make more sense to have the preview update just after the text change. What do you think? cc: @PeerRich

2023-01-25 14:03 UTC, gitstart-calcom commented
> > Hi @Jaibles, what should be the behavior of the Preview text? Should it update just after a user finishes editing the event name or after the event is saved (current behavior)? It would make more sense to have the preview update just after the text change. What do you think? cc: @PeerRich
> 
> Has to be after text change.

Alright, will have after text change implemented. Thanks

>  If it's after save they won't' see it unless they open the modal (unless I'm mistaken).

yes

2023-01-26 18:39 UTC, gitstart-calcom commented
Hi @emrysal, PR has been updated please take a look. cc: @Jaibles @PeerRich

2023-01-27 10:18 UTC, PeerRich commented
looks great! https://twitter.com/peer_rich/status/1618915636968828929

2023-01-27 10:19 UTC, PeerRich approved these changes

2023-01-27 10:19 UTC, PeerRich commented
tested and works. waiting for @emrysal re-review of the code

2023-02-01 11:49 UTC, emrysal requested changes

2023-02-01 11:49 UTC, emrysal commented on apps/web/components/eventtype/EventAdvancedTab.tsx
> +              <DialogClose onClick={() => formMethods.setValue("eventName", eventType.eventName ?? "")}>
This should happen in `onOpenChange` - and also unregister instead of defaulting

2023-02-01 11:50 UTC, emrysal approved these changes
Deemed my earlier comment a NIT

2023-02-01 12:10 UTC, merged

2023-02-01 12:10 UTC, PeerRich commented
thank you for the great work!