[CAL-90] Event Types Single / Allow multiple physical locations
calcom/cal.com pull request #6692
Opened 2023-01-25 14:07 UTC by gitstart-calcom

## What does this PR do?

Fixes #3822 

## Demo
https://user-images.githubusercontent.com/26940294/214548713-62b3d620-2521-4bc0-8f2e-35d0bbcaa887.mov

**Environment**: Staging(main branch) / Production

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

2023-01-25 14:39 UTC, PeerRich commented
this is really cool, thank you! 

@G3root can you test and review this?

2023-01-25 16:59 UTC, G3root requested changes
removing a single location removes other locations as well.
https://www.loom.com/share/202e2252441d44f0b217a989d2b72956

2023-01-26 18:41 UTC, gitstart-calcom commented
Hi @G3root, PR has been updated please take a look

2023-02-02 12:26 UTC, G3root approved these changes
tested locally LGTM :)

2023-02-02 12:33 UTC, PeerRich approved these changes

2023-02-02 12:42 UTC, merged