[CAL-807] /event-types/single - Fix the header
calcom/cal.com pull request #6738
Opened 2023-01-26 18:07 UTC by gitstart-calcom

## What does this PR do?

Fixes #6517 

## Demo
https://www.loom.com/share/09ea22d02b784b42b7e86b492560da32

![Screenshot_11](https://user-images.githubusercontent.com/87545086/214144989-31bd9934-6ffb-44c6-9504-ea5488055513.png)

2023-01-26 20:17 UTC, sean-brydon requested changes
Thank you for the PR few changes need to be addressed before we can merge

2023-01-26 20:17 UTC, sean-brydon commented on packages/ui/components/button/Button.tsx
> +                variant === "button" && "h-4 w-4 stroke-[1.5px]"
Breaks icon buttons in our app - Please check storybook and [design system](https://www.figma.com/file/9MOufQNLtdkpnDucmNX10R/%E2%9D%96-Cal-DS?node-id=13743%3A97381&t=6OjJIg9y55PcPjn2-0) when making changes to core components

2023-01-26 20:17 UTC, sean-brydon commented on packages/features/shell/Shell.tsx
> +            className="h-6 w-6 items-center justify-center p-0 ltr:mr-2 rtl:ml-2"
```suggestion
            className="ltr:mr-2 rtl:ml-2"
```

2023-01-26 20:17 UTC, sean-brydon commented on packages/features/shell/Shell.tsx
>              color="minimal"
Please update to use our components

variant="icon"
size="sm"

2023-01-30 14:13 UTC, PeerRich commented
can you test this with description too? I believe we wanna remove the description right @Jaibles ?

2023-01-30 14:26 UTC, gitstart-calcom commented
Currently, with a description
<img width="785" alt="Screenshot 2023-01-30 at 8 11 41 PM" src="https://user-images.githubusercontent.com/121884634/215503768-7ef3fd45-d190-4b94-a034-ff99427f257b.png">

2023-01-30 16:44 UTC, PeerRich commented
> Currently, with a description <img alt="Screenshot 2023-01-30 at 8 11 41 PM" width="785" src="https://user-images.githubusercontent.com/121884634/215503768-7ef3fd45-d190-4b94-a034-ff99427f257b.png">

yeah lets hide the description there, because we are adding multi-line and styled descriptions with **bold** and _italic_ text

2023-01-30 16:51 UTC, Jaibles commented
@PeerRich correct - there's no description in designs
https://www.figma.com/file/xk4HOxtSI82J0F7enMxeak/Cal---Live?node-id=20%3A26194&t=JxClWoJllqV3zJeC-1

<img width="1507" alt="CleanShot 2023-01-30 at 16 50 24@2x" src="https://user-images.githubusercontent.com/4536123/215541635-0ad38cd5-8aeb-493e-a89d-9ada9380a547.png">

2023-01-30 17:20 UTC, gitstart-calcom commented
Hi @PeerRich @Jaibles, the description has been removed now. Please take a look.

2023-01-30 18:32 UTC, PeerRich approved these changes
great stuff!

2023-01-31 20:16 UTC, alannnc approved these changes
Code looks good. Thank you!

2023-01-31 20:19 UTC, sean-brydon approved these changes

2023-01-31 20:19 UTC, merged