Add/eslint plugin mdx
calcom/cal.com pull request #6748
Opened 2023-01-27 00:49 UTC by zomars

## What does this PR do?

Adds linting for MDX files

## Type of change

- [x] Chore (refactoring code, technical debt, workflow improvements)

## How should this be tested?

- [ ] `yarn lint`

2023-01-27 05:34 UTC, hariombalhara commented on apps/docs/pages/availability.mdx
>  1. Go to [Your Availability](https://app.cal.com/availability) page within your cal.com account.
@zomars I don't think we even use apps/docs now. Maybe we can delete the docs folder?

2023-02-19 09:05 UTC, hariombalhara commented on apps/docs/pages/availability.mdx
>  1. Go to [Your Availability](https://app.cal.com/availability) page within your cal.com account.
Cool

2023-02-19 09:05 UTC, hariombalhara commented
There are conflicts in it, I think we can quickly merge after that,

2023-03-07 11:56 UTC, PeerRich requested changes
merge conflicts. moved to draft

2023-04-19 18:18 UTC, zomars commented
Closing for now. MDX linting is not a priority right now.

2023-04-19 18:18 UTC, closed without merging