Removed unused variables (#6704)
calcom/cal.com pull request #6750
Opened 2023-01-27 02:20 UTC by blam404

## What does this PR do?

Updated and removed unused variables. There were some variables that looked like it could be used for future things so I either commented them out or left them as is. Still new to this project so I'm not 100% sure about what some things do and didn't want to risk removing something that might be necessary in the future.

Fixes #6704 

**Environment**: Staging(main branch) / Production

## Type of change

- [ ] Chore (refactoring code, technical debt, workflow improvements)

## How should this be tested?

- [ ] No testing required. Removed unused variables should not have an effect on anything.

2023-01-27 02:58 UTC, zomars requested changes, later dismissed
Thank you for your contribution 🙏 

Left some comments, also can you please skip `yarn.lock` for this PR?

2023-01-27 02:58 UTC, zomars commented on apps/web/components/getting-started/components/ConnectedCalendarItem.tsx
> +//import { useLocale } from "@calcom/lib/hooks/useLocale";
We can safely remove these.

2023-01-27 02:58 UTC, zomars commented on apps/web/components/getting-started/components/ConnectedCalendarItem.tsx
> +  //const { t } = useLocale();
And this

2023-01-27 02:58 UTC, zomars commented on apps/web/playwright/auth/auth-index.e2e.ts
> +// import { WEBAPP_URL } from "@calcom/lib/constants";
Let's remove instead of commenting

2023-01-27 02:58 UTC, zomars commented on packages/ui/form/Select.tsx
> +>({ ...props }: SelectProps<Option, IsMulti, Group>) {
Let's revert this. I think we don't want to pass `className` with the rest of `...props`. In these cases removing `className` will affect `props` structure.

2023-01-31 18:36 UTC, blam404 commented
@zomars I updated the changes based on your comments.

2023-01-31 22:29 UTC, emrysal approved these changes
Files inspected, check-types handles the rest, thanks for your contribution!

2023-01-31 22:29 UTC, merged