Small UI fixes for seats & destination calendars
calcom/cal.com pull request #6859
Opened 2023-02-03 04:57 UTC by joeauyeung

## What does this PR do?

This PR fixes a number of small UI bugs

When booking new seats, the dates are no longer crossed out
**Before**
![image](https://user-images.githubusercontent.com/65426560/216511583-697d45c6-f341-476c-8c20-4b1ae10ab3ab.png)

**After**
![image](https://user-images.githubusercontent.com/65426560/216511373-fec2b354-5c28-4222-a600-d4bac25ac222.png)

When the default destination calendar option is selected in `DestinationCalendarSelector`, rather than showing the external id of the calendar it now shows the calendar name and integration
**Before**
![image](https://user-images.githubusercontent.com/65426560/216511984-7fa042df-21e5-4509-86b1-c1e0381429f3.png)

**After**
![image](https://user-images.githubusercontent.com/65426560/216512340-7cbbc333-8a77-4703-b980-b81d039bbf93.png)

Add seats badge to event type item
![image](https://user-images.githubusercontent.com/65426560/216515935-511f6203-5ffc-4264-9629-1bb9b581d916.png)

Fixes # (issue)

**Environment**: Staging(main branch) / Production

## Type of change

- [x] Chore (refactoring code, technical debt, workflow improvements)

## How should this be tested?

- [ ] Test A
- [ ] Test B

## Checklist

- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't performed a self-review of my own code and corrected any misspellings
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my PR needs changes to the documentation
- I haven't checked if my changes generate no new warnings
- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

2023-02-03 16:11 UTC, CarinaWolli commented
@joeauyeung I noticed one other small UI issue around seats, that could maybe be fixed in this PR: 
When seats ist enabled, and then you disable it, it still shows the banner 'Seats option doesn't support confirmation requirement'. You then first need to click save with seats disabled and then you can enable 'requires confirmation'

2023-02-03 16:49 UTC, CarinaWolli requested changes
Please address my comment below. Other than that, everything looks good to me

2023-02-03 16:49 UTC, CarinaWolli commented on apps/web/components/booking/pages/BookingPage.tsx
> +          ...(!eventType.seatsPerTimeSlot &&
now we also don't show the former date crossed out when rescheduling a seat

2023-02-07 18:54 UTC, joeauyeung reviewed
@CarinaWolli

2023-02-07 18:54 UTC, joeauyeung commented on apps/web/components/booking/pages/BookingPage.tsx
> +          ...(rescheduleUid && booking?.startTime && { formerTime: booking.startTime.toString() }),
Now shows former time when rescheduling a seat

2023-02-07 18:54 UTC, joeauyeung commented on apps/web/components/eventtype/EventAdvancedTab.tsx
> +  const seatsEnabled = formMethods.watch("seatsPerTimeSlotEnabled");
Actively watches if seats are enabled, so the requires confirmation prompt will update without saving.

2023-02-08 14:50 UTC, CarinaWolli approved these changes
LGTM 👏🏻

2023-02-08 21:13 UTC, merged