fix: metadata not saved while creating a booking.
calcom/cal.com pull request #6866
Opened 2023-02-03 11:51 UTC by G3root

## What does this PR do?

Fixes #6808 

**Environment**: Staging(main branch) / Production

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

2023-02-03 15:04 UTC, CarinaWolli requested changes
It's not working if the location is a video conferencing app. It then only shows the `videoCallUrl` in `metadata`. 

It's overwritten here, I believe:
<img width="417" alt="Screenshot 2023-02-03 at 10 02 39" src="https://user-images.githubusercontent.com/30310907/216636247-ee7cdd57-bf2b-41d5-8db1-a3ec6ea5795c.png">

2023-02-05 16:07 UTC, G3root commented on packages/features/bookings/lib/handleNewBooking.ts
> +        metadata: { ...(typeof booking.metadata === "object" && booking.metadata), ...metadata },
workaround for typescript complaining that only objects can be spreaded

2023-02-05 16:10 UTC, G3root commented
@CarinaWolli pushed some changes

2023-02-06 17:12 UTC, CarinaWolli approved these changes
Works now, thank you 🙏

2023-02-06 17:57 UTC, zomars approved these changes
![LGTM](https://media3.giphy.com/media/NytMLKyiaIh6VH9SPm/200.gif)

2023-02-06 18:05 UTC, merged