Fixes localisation of {EVENT_DATE} in workflows
calcom/cal.com pull request #6907
Opened 2023-02-06 19:08 UTC by CarinaWolli

## What does this PR do?

Adds correct translations of the dynamic text variable {EVENT_DATE} for custom workflow templates. The workflow actions 'send SMS to attendee' and 'send Email to attendee' are now using the attendee's language to translate the event date. 

Fixes #6733

German: 
![Screenshot 2023-02-06 at 13 54 21](https://user-images.githubusercontent.com/30310907/217062408-7502e759-2a58-491a-895a-5b7592a1f79f.png)

English:
![Screenshot 2023-02-06 at 13 55 59](https://user-images.githubusercontent.com/30310907/217062416-e2d66fbd-dd5a-4a33-8667-32bbab3962ef.png)

**Environment**: Staging(main branch) / Production

2023-02-06 19:51 UTC, CarinaWolli commented on packages/trpc/server/routers/viewer/workflows.tsx
> +const hasTeamPlan = (await ctx.prisma.membership.count({ where: { userId: user.id } })) > 0;
Nothing was changed in all these commented lines

2023-02-08 12:24 UTC, emrysal requested changes

2023-02-08 12:24 UTC, emrysal commented on packages/features/ee/workflows/lib/reminders/templates/customTemplate.ts
> +  const day = translate(dayjs(variables.eventDate).format("dddd").toLowerCase());
I suggest using Intl instead of our own translations for weekdays/months 👍 - have a look at the booking page for examples of this

2023-02-08 15:31 UTC, CarinaWolli commented on packages/features/ee/workflows/lib/reminders/templates/customTemplate.ts
> +  const translatedDate = new Intl.DateTimeFormat(locale, {
using Intl now for date translations: 

English: 
![Screenshot 2023-02-08 at 10 25 32](https://user-images.githubusercontent.com/30310907/217575112-b70aea9d-998b-4949-9d4e-6cb102a47187.png)

German:
![Screenshot 2023-02-08 at 10 25 35](https://user-images.githubusercontent.com/30310907/217575133-dac46c2a-11e8-418e-9a0e-e97fdcd05d8e.png)

2023-02-08 17:06 UTC, emrysal approved these changes
Amazing!

2023-02-08 17:06 UTC, merged