Localization of Dates, Times, and Timezones using Intl.DateTimeFormat
calcom/cal.com pull request #6988
Opened 2023-02-09 21:01 UTC by AaronPresley

WIP

## What does this PR do?

Fixes #6951 

**Environment**: Staging(main branch) / Production

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

- [ ] Test A
- [ ] Test B

## Checklist

- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't performed a self-review of my own code and corrected any misspellings
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my PR needs changes to the documentation
- I haven't checked if my changes generate no new warnings
- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

2023-02-09 22:03 UTC, AaronPresley commented
@CarinaWolli ready for your review ☝️

2023-02-10 13:01 UTC, CarinaWolli requested changes
Great work 🙌🏻  Recurring events need to be fixed, but everything else looks good to me!

2023-02-10 16:58 UTC, AaronPresley commented on apps/web/pages/booking/[uid].tsx
> +              {formatToLocalizedDate(dayjs.tz(date, timeZone()), language, "full")}
Good catch, will do!

2023-02-10 18:09 UTC, CarinaWolli approved these changes
Looks good now! Thank you for your contribution 🙏

2023-02-13 18:07 UTC, AaronPresley commented
@CarinaWolli anything I can do to help close this out? It seems the

2023-02-13 18:10 UTC, AaronPresley commented
@CarinaWolli Attempting to get the E2E checks to pass by closing / reopening. Let me know if there's something else I should attempt here

2023-02-13 18:33 UTC, PeerRich commented
rerunning now!

2023-02-14 18:16 UTC, closed without merging

2023-02-15 12:11 UTC, PeerRich commented
why was this closed?

2023-02-15 17:06 UTC, AaronPresley commented
@PeerRich ah, my apologies - I switched from using the forked repo when you gave me access to the `calcom` team on GitHub, and hadn't realized this PR wasn't yet closed. Will fix it today 👍