chore: change calendso strings to cal.com
calcom/cal.com pull request #707
Opened 2021-09-20 15:54 UTC by conrmahr

Helping with the rebrand to Cal.com!

- change all instances of `Calendso` strings to `Cal.com` excluding namespaces

2021-09-20 16:03 UTC, baileypumfleet commented on README.md
> +9. Under Authorized redirect URI's, select Add URI and then add the URI `<CALENDSO URL>/api/integrations/googlecalendar/callback` replacing Cal.com URL with the URI at which your application runs.
<CALENDSO URL> hasn't been changed :)

2021-09-20 16:08 UTC, baileypumfleet requested changes
Thank you very much for this amazing contribution! There are a couple of things that need to be replaced, but we really appreciate your PR regardless 😄

2021-09-20 16:08 UTC, baileypumfleet commented on README.md
> +4. Set the **Web** redirect URI to `<CALENDSO URL>/api/integrations/office365calendar/callback` replacing Cal.com URL with the URI at which your application runs.
`<CALENDSO URL>` hasn't been changed :)

2021-09-20 16:08 UTC, baileypumfleet commented on README.md
> +9. Set the Redirect URL for OAuth `<CALENDSO URL>/api/integrations/zoomvideo/callback` replacing Cal.com URL with the URI at which your application runs.
`<CALENDSO URL>` hasn't been changed :)

2021-09-21 09:53 UTC, baileypumfleet approved these changes

2021-09-21 09:57 UTC, PeerRich approved these changes
lgtm. surprised why some lines were formatted differently

2021-09-21 09:59 UTC, merged