Handle booking flow for dynamic default events
calcom/cal.com pull request #7094
Opened 2023-02-14 14:46 UTC by sean-brydon

## What does this PR do?

https://www.loom.com/share/cc6419705f7c465a89c7c1f2b731f443

This touches a lot of CORE code please test appropriately.  This PR seems like it may be a bit OTT with all the sorted - but when you take a look at how `in` works in prismas `where` it doesnt return in the order that the array is in (just first found).So we need to sort this to ensure the first user is always the first user in the username list. So we can grab their default location 

## Type of change
- [ ] New feature (non-breaking change which adds functionality)

2023-02-14 14:56 UTC, sean-brydon commented on apps/web/pages/[user]/[type].tsx
> +  console.log("eventTypeLocations", eventTypeObject.locations);
```suggestion
  console.log("eventTypeLocations", eventTypeObject.locations);
```

2023-02-14 14:56 UTC, sean-brydon commented on apps/web/pages/[user]/book.tsx
> +    if (!isDynamicGroupBooking) return locations;
If this isnt a dynamic link - we dont care about the rest of this code

2023-02-14 14:56 UTC, sean-brydon commented on packages/app-store/locations.ts
> +  console.log("locationsAfterPrivacyFilter", locationsAfterPrivacyFilter);
```suggestion
```

2023-02-14 14:57 UTC, sean-brydon commented on packages/features/bookings/lib/handleNewBooking.ts
> +  console.log("bookingLocation", bookingLocation);
```suggestion
```

2023-02-14 14:57 UTC, sean-brydon commented on packages/features/bookings/lib/handleNewBooking.ts
> +        videoCallUrl = metadata.hangoutLink || defaultLocationUrl || videoCallUrl;
We want hangout URL to take precedence if it exists

2023-02-14 14:58 UTC, sean-brydon commented on packages/lib/defaultEvents.ts
> +    console.log({ users, combinedUsername });
```suggestion
```

2023-02-15 11:31 UTC, Jaibles commented
Really nice! All looks good to me.

2023-02-15 13:07 UTC, emrysal requested changes

2023-02-15 13:07 UTC, emrysal commented on packages/features/bookings/lib/handleNewBooking.ts
> +    const firstUsers = userMetadataSchema.parse(users[0].metadata);
NIT seeing some code duplication and naming inconsistencies (`firstUsersMetadata` vs `firstUsers`)

2023-02-15 14:28 UTC, emrysal approved these changes
Good to go once lint is passing.

2023-02-15 15:42 UTC, merged