Filter Timezones by cities
calcom/cal.com pull request #7118
Opened 2023-02-15 16:38 UTC by gitstart-calcom

## What does this PR do?

Adds timezone filtering by cities

## Demo
https://www.loom.com/share/c06e6c76954e4f668a891f47e5fad3e8

**Dropdown overlapping**
https://www.loom.com/share/a479fdbe043e4923a5909876b069befb

**Environment**: Staging(main branch) / Production

2023-02-15 16:51 UTC, gitstart-calcom commented on apps/web/components/booking/pages/AvailabilityPage.tsx
> +      <div className="dark:focus-within:bg-darkgray-200 dark:bg-darkgray-100 dark:hover:bg-darkgray-200 -mx-[2px] !mt-3 flex w-fit max-w-[20rem] items-center rounded-[4px] px-1 py-[2px] text-sm font-
This is to fix the overlapping of input 
<img width="381" alt="Screenshot 2023-02-15 at 10 35 31 PM" src="https://user-images.githubusercontent.com/121884634/219097005-a502f885-ded3-4490-958c-94d5f1077fa7.png">

2023-02-15 17:02 UTC, gitstart-calcom commented
Not sure why these tests are failing. They are passing locally. How can we get them fixed?

2023-02-15 17:58 UTC, zomars requested changes

2023-02-15 17:58 UTC, zomars commented on package.json
> +    "city-timezones": "^1.2.1",
You're adding a new dependency but the lock file didn't update

2023-02-15 18:07 UTC, PeerRich commented
NIT: can we replace "_" with " "? 

![CleanShot%202023-02-15%20at%2019 00 06@2x](https://user-images.githubusercontent.com/8019099/219115576-c35d456f-a87e-4265-b329-fde01223f408.jpg)


Los_Angeles => Los Angeles

2023-02-15 18:22 UTC, zomars commented
We cannot merge this @PeerRich 

We can create an endpoint to lazy load this data and reduce initial bundle size. But this is way out of our performance budget.

<img width="1029" alt="image" src="https://user-images.githubusercontent.com/3504472/219118420-013d2c90-fe3e-4bba-982b-08b449fb4da9.png">

<img width="939" alt="image" src="https://user-images.githubusercontent.com/3504472/219118489-c0b13da5-b37f-4d96-907e-6a7ff8c25b89.png">

2023-02-15 18:23 UTC, zomars requested changes
Blocking to address performance concerns

2023-02-16 09:26 UTC, emrysal commented
Simplest approach here is to use a static file and then load that on the select - not part of the bundle and cached 🙏

2023-02-17 15:24 UTC, PeerRich commented
> Simplest approach here is to use a static file and then load that on the select - not part of the bundle and cached 🙏

so what you are saying is we need a static: cities.json with all info right?

2023-03-02 17:01 UTC, gitstart-calcom commented
Not sure if we would want to keep this but we have added a loading state to the select since it takes some time for the first load
https://www.loom.com/share/690a72cfe09d486594d6f2254194d1cb

2023-03-02 17:07 UTC, gitstart-calcom commented
Hi @PeerRich, can you please help with the `yarn.lock` issue?

2023-03-02 19:45 UTC, zomars commented
Adding caching and preventing batching for this endpoint: 
<img width="1155" alt="image" src="https://user-images.githubusercontent.com/3504472/222535979-aa527520-74d5-40a0-9086-ffb4ae1e9147.png">

2023-03-02 19:48 UTC, zomars commented on apps/web/pages/api/trpc/[trpc].ts
> +      "viewer.public.cityTimezones": `max-age=${ONE_DAY_IN_SECONDS}, stale-while-revalidate`,
Added so we can cache the response

2023-03-02 19:48 UTC, zomars requested changes

2023-03-02 19:48 UTC, zomars commented on apps/web/test/lib/getTimezone.test.ts
> +});
Seems like tests are failing:

<img width="697" alt="image" src="https://user-images.githubusercontent.com/3504472/222536584-e0b8549c-6fdb-4e07-aebb-4ac32b16a3b0.png">

2023-03-02 19:50 UTC, zomars commented on packages/ui/components/form/timezone-select/TimezoneSelect.tsx
> +    trpc: { context: { skipBatch: true } },
Added so we can cache this endpoint individually

2023-03-02 20:11 UTC, zomars approved these changes
Updated tests to use inline snapshots since they can be auto-updated.

![Ship it](https://media.giphy.com/media/CEIHJK4ympvVe0fAdU/giphy.gif)

2023-03-02 20:42 UTC, merged