Community login support
calcom/cal.com pull request #7204
Opened 2023-02-18 20:42 UTC by leog

## What does this PR do?

Allow a discourse instance accompanying Cal.com instance to login using Cal.com login. 

The login to Cal Community from Cal.com:
 - Reuses username (not editable from community)
 - Reuses name (not editable from community)
 - Reuses avatar (not editable from community)
 - Defines user's profile website field as Cal.com/username
 - Reuses role
 - Reuses bio

Pending:
 - [ ] Test and make work non-credential login such as Google or SAML

Before merging, to get it to work on PROD, do the following:
 - [ ] Add COMMUNITY_SECRET env var in Vercel to match Discourse Connect secret field
 - [ ] Change Discourse Connect url field to http://app.cal.com/auth/login
 - [ ] Delete all testing accounts created in https://Cal.Community

**Environment**: Staging(main branch) / Production

## Type of change

- [X] New feature (non-breaking change which adds functionality)

## How should this be tested?

Go to https://cal.community and sign in using any valid account

2023-02-18 23:17 UTC, leog commented on apps/web/package.json
> +    "discourse-sso": "^1.0.5",
Using this dependency to do the heavy lifting behind the logic to verify a login request from Discourse.

2023-02-18 23:17 UTC, leog commented on apps/web/package.json
> +    "@types/discourse-sso": "^1.0.1",
Types for the newly added dependency come separately.

2023-02-18 23:18 UTC, leog commented on apps/web/pages/api/auth/[...nextauth].tsx
> +          bio: true,
Adding bio to pass it down to Discourse, we can remove it if we don't want it.

2023-02-18 23:18 UTC, leog commented on apps/web/pages/api/auth/[...nextauth].tsx
> +const checkCommunityLogin = (
All the logic to handle Discourse sign in from our current login page.

2023-02-18 23:19 UTC, leog commented on apps/web/pages/api/auth/[...nextauth].tsx
> +  const sso = new discourseSso(process.env.COMMUNITY_SECRET);
This is the shared secret between our app and Discourse to avoid anyone messing our instance.

2023-02-18 23:20 UTC, leog commented on apps/web/pages/auth/login.tsx
> +
Converting already existing query parameters into Zod schema, adding `sso` and `sig` for Discourse.

2023-02-18 23:21 UTC, leog commented on apps/web/pages/auth/login.tsx
> +  const [successMessage, setSuccessMessage] = useState<string | null>(null);
It's always nice to show a success message to the user once everything went well and a redirection is about to happen.

2023-02-18 23:21 UTC, leog commented on apps/web/pages/auth/login.tsx
> +    [ErrorCode.InvalidCommunityLogin]: `${t("something_went_wrong")} ${t("signing_in_community")}`,
Anything that can happen from the community login will result in this error.

2023-02-18 23:22 UTC, leog commented on apps/web/pages/auth/login.tsx
> +  queryParams.callbackUrl = safeCallbackUrl || "";
Above lines is just moving from simple query checking to Zod schema, nothing changed really in terms of logic.

2023-02-18 23:23 UTC, leog commented on apps/web/pages/auth/login.tsx
> +  const communityLogin = queryParams.sso !== undefined && queryParams.sig !== undefined;
We need to be able to know if there is an attempt to login to community to change a bit the sign in process below.

2023-02-18 23:24 UTC, leog commented on apps/web/pages/auth/login.tsx
> +      redirect: communityLogin,
If we are dealing with a community login, then we need to enable redirection and provide the callbackUrl to let the sign in process know we are dealing with that community login.

2023-02-18 23:25 UTC, leog commented on apps/web/pages/auth/login.tsx
> +    if (!res && communityLogin) return setSuccessMessage("Success! Redirecting...");
When community login succeeds, then no `res` is returned and when that happens in the context of a community login, everything went well, so showing message while being redirected.

2023-02-18 23:25 UTC, leog commented on apps/web/pages/auth/login.tsx
> +    else if (!res.error) router.push(queryParams.callbackUrl);
Relying on Zod parsed query parameters now.

2023-02-18 23:26 UTC, leog commented on apps/web/pages/auth/login.tsx
> +              {successMessage && <Alert severity="info" title={successMessage} />}
For some reason the severity "success" was not what I expected in terms of color and style, so using "info" for now.

2023-02-18 23:26 UTC, leog commented on apps/web/pages/auth/login.tsx
> +    if (!res && communityLogin) return setSuccessMessage("Success! Redirecting...");
Oh I guess this string needs to be localized 😅

2023-02-19 13:21 UTC, PeerRich commented
the open question still stands if we want discourse code in the core code base cc @zomars

2023-02-19 15:34 UTC, leog commented
> the open question still stands if we want discourse code in the core code base cc @zomars

Would it help if I get rid of any reference to discourse from the code? it will be just references to community

2023-02-19 15:42 UTC, PeerRich commented
wasnt referring to the naming just the extra code and dependencies being added. I have no strong opinion, will defer to @zomars

2023-02-19 18:26 UTC, leog commented
> wasnt referring to the naming just the extra code and dependencies being added. I have no strong opinion, will defer to @zomars

> @PeerRich gotcha; moved things to `lib/auth` and removed discourse new dependency, now I'm using dependencies we already had.

2023-02-22 16:11 UTC, PeerRich commented
ive changed my mind-- i dont mind having community log in code here as long as it works 🙏

2023-03-07 22:16 UTC, deepakprabhakara approved these changes
LGTM, nice work @leog

2023-03-10 00:49 UTC, zomars requested changes
Let's move this to [@calcom/auth](https://github.com/calcom/auth) 🙏🏽

2023-04-18 14:11 UTC, hariombalhara commented
Marking it draft based on @zomars last comment.

2023-04-18 14:39 UTC, leog commented
@hariombalhara better to close it, we want to do this in a different package, so we could reuse the logic but this PR is no longer valid.

2023-04-18 14:39 UTC, closed without merging