cal video: show meeting info in a hideable box
calcom/cal.com pull request #7295
Opened 2023-02-23 10:29 UTC by PeerRich

- [x] frontend
- [x] fixed "no meeting found" and "meeting not started" pages (had old layout) 
- [x] mobile
- [ ] get data from booking data

https://user-images.githubusercontent.com/8019099/220881656-e153223a-f48f-4fe0-a8ba-9f7fc2613e8c.mp4

2023-02-23 10:31 UTC, PeerRich commented on apps/web/pages/video/no-meeting-found.tsx
> +    </>
FYI: remove this before merging. its easier to test on localhost:3000/video/no-meeting-found -- doesnt need Cal Video to be configured

2023-02-23 22:51 UTC, PeerRich commented
great work! whats the best way we can test this?

2023-02-23 22:52 UTC, PeerRich commented on apps/web/pages/video/no-meeting-found.tsx
> +      <iframe src="https://cal.video" className="h-[100vh] w-full" />
```suggestion
      
```

2023-02-24 10:47 UTC, PeerRich commented
![CleanShot 2023-02-24 at 11 47 26@2x](https://user-images.githubusercontent.com/8019099/221160151-bdd83534-c45b-41bd-9a22-b37144415701.jpg)
no clue why checks are failing https://vercel.com/cal/cal/5dngmkvmSeVCjckbYgtCmXXb2C4b

maybe @zomars knows more

2023-03-03 20:39 UTC, Udit-takkar commented on apps/web/pages/video/[uid].tsx
> +  });
why are you using useState here ?

2023-03-03 20:41 UTC, Udit-takkar reviewed
<img width="912" alt="Screenshot 2023-03-04 at 2 10 22 AM" src="https://user-images.githubusercontent.com/53316345/222824824-9b35893e-e747-47ec-8dec-6f7098f0a6de.png">

I am seeing this white boundary in the drawer. (using Brave Browser)

2023-03-04 13:04 UTC, PeerRich commented
> <img width="912" alt="Screenshot 2023-03-04 at 2 10 22 AM" src="https://user-images.githubusercontent.com/53316345/222824824-9b35893e-e747-47ec-8dec-6f7098f0a6de.png">
> 
> 
> 
> I am seeing this white boundary in the drawer. (using Brave Browser)
> 
> 

will fix

2023-03-14 09:32 UTC, Udit-takkar commented
@PeerRich now i don't see the arrow to open the hidde drawer

2023-03-14 11:19 UTC, PeerRich commented
> @PeerRich now i don't see the arrow to open the hidden drawer

ahh of course... overflow-hidden...

2023-03-14 18:21 UTC, zomars requested changes
Blocking to apply some fixes. Neither the side bar or the button are Visible (tested on Safari and Firefox)

<img width="1152" alt="image" src="https://user-images.githubusercontent.com/3504472/225101197-bb90f354-1f94-4cf1-bb9f-613bd556c578.png">

2023-03-14 19:25 UTC, zomars approved these changes
Tested locally on Safari/Firefox/Chrome. Waiting for preview to merge.

![LGTM](https://media3.giphy.com/media/NytMLKyiaIh6VH9SPm/200.gif)

2023-03-14 19:43 UTC, merged

2023-03-14 22:21 UTC, PeerRich commented
epic work!