Add embed versions
calcom/cal.com pull request #7296
Opened 2023-02-23 10:44 UTC by hariombalhara

It is important to add embed versions so that packages are very clear on what their dependency's version is.

2023-02-23 14:24 UTC, PeerRich commented
can i merge this or does this need to be tested?

2023-02-23 14:45 UTC, hariombalhara commented
I need confirmation from @zomars on this

2023-02-23 22:10 UTC, zomars requested changes
By doing this we're opting out of monorepo linking and we're actually installing directly from NPM. I don't think this is desired behavior.

2023-02-24 05:00 UTC, hariombalhara commented
So, I get the reasoning to use * now. But embed packages are published to NPM as well and for that, we must have versions as dependencies.
How do you suggest we solve this? @zomars

2023-03-10 00:36 UTC, zomars commented
> How do you suggest we solve this? @zomars

Not using versions in the source of truth (this monorepo). NPM versions should be used externally. Not internally. Will close this PR until we figure something out.

2023-03-10 00:36 UTC, closed without merging