Cal 1099 availability section defined hour mismatch
calcom/cal.com pull request #7416
Opened 2023-02-26 15:21 UTC by abhisht51

## What does this PR do?

Tries to fix the Setup Page Availability tab mismatch issue here https://github.com/calcom/cal.com/issues/7163 

Fixes # (issue)
https://github.com/calcom/cal.com/issues/7163

**Environment**: Staging

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Chore (refactoring code, technical debt, workflow improvements)

## How should this be tested?
- Code needs additions 

## Checklist

- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't performed a self-review of my own code and corrected any misspellings
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my PR needs changes to the documentation
- I haven't checked if my changes generate no new warnings
- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

2023-03-02 23:09 UTC, Udit-takkar commented
fixed the issue 1 

TODO
- [ ] fix format of time ( it is showing 0:30 pm)

2023-03-03 05:27 UTC, abhisht51 commented
I can take this up if it's not super urgent to merge.

2023-03-03 07:15 UTC, Udit-takkar commented
@abhisht51 👍

2023-03-06 05:16 UTC, abhisht51 commented
@Udit-takkar could you help me with the merge conflicts ?  I am not seeing them in vs code for some reason otherwise the bug is fixed

2023-03-06 09:27 UTC, Udit-takkar approved these changes
LGTM

2023-03-17 20:00 UTC, zomars requested changes

2023-03-17 20:00 UTC, zomars commented on apps/web/components/eventtype/AvailabilityTab.tsx
> +  }, [value?.value]);
Let's avoid this pattern. Let's either pass an async defaultValue to the form or don't render this until the value is defined.

2023-04-18 14:13 UTC, hariombalhara commented
@abhisht51 @Udit-takkar Is something pending on it?

2023-04-18 21:34 UTC, zomars approved these changes
Fixed some conflicts, tested and is working now. 

Thank you for your contribution 🙏 

PS. tagging @leog to help testing managed events

2023-04-18 21:34 UTC, zomars commented on packages/ui/components/navigation/tabs/VerticalTabs.tsx
> +  console.log("TABS", tabs);
```suggestion
```

2023-04-18 23:29 UTC, merged