fix: routing form delete button not rendered
calcom/cal.com pull request #7424
Opened 2023-02-27 10:16 UTC by G3root

## What does this PR do?

Fixes #7412 

after:
![Screenshot 2023-02-27 15:43:20](https://user-images.githubusercontent.com/84864519/221536617-d9c9f20b-18a6-4b43-9201-ef45a4ed5a38.png)

**Environment**: Staging(main branch) / Production

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

2023-02-27 10:48 UTC, hariombalhara approved these changes

2023-02-27 11:38 UTC, emrysal approved these changes

2023-02-27 12:49 UTC, Jaibles reviewed
Minor copy update suggestions, otherwise looks good!

<img width="1474" alt="CleanShot 2023-02-27 at 12 48 25@2x" src="https://user-images.githubusercontent.com/4536123/221567955-ea6d6903-c3a9-45bc-8c89-667c7ba58844.png">

2023-02-27 14:24 UTC, G3root commented
@Jaibles updated the copy .

![Screenshot 2023-02-27 19:52:05](https://user-images.githubusercontent.com/84864519/221588971-8612c9bd-c01d-41d5-b586-8d672d7d4f9a.png)

2023-03-04 04:56 UTC, hariombalhara commented on apps/web/public/static/locales/fr/common.json
> +  "delete_form_confirmation_1": "Voulez-vous vraiment supprimer ce formulaire ? Toute personne avec qui vous avez partagé le lien ne pourra plus passer de réservation en l'utilisant. De plus, toutes
why this change? Here we are not breaking the string in 2 parts and just assigning the complete string to confirmaton_1

2023-03-04 04:58 UTC, hariombalhara commented on apps/web/public/static/locales/ar/common.json
> +  "delete_form_confirmation_1": "هل أنت متأكد من أنك تريد حذف هذا النموذج؟ لن يتمكن أي شخص تشارك الرابط معه من الحجز بعد الآن. كما ستحذف جميع الردود المرتبطة بذلك.",
```suggestion
  "delete_form_confirmation": "هل أنت متأكد من أنك تريد حذف هذا النموذج؟ لن يتمكن أي شخص تشارك الرابط معه من الحجز بعد الآن. كما ستحذف جميع الردود المرتبطة بذلك.",
```

2023-03-04 04:58 UTC, hariombalhara commented on apps/web/public/static/locales/da/common.json
> +  "delete_form_confirmation_1": "Er du sikker på, at du vil slette denne formular? Enhver, som du har delt linket med, vil ikke længere kunne booke via dette. Desuden ville alle tilknyttede svar bliv
```suggestion
  "delete_form_confirmation": "Er du sikker på, at du vil slette denne formular? Enhver, som du har delt linket med, vil ikke længere kunne booke via dette. Desuden ville alle tilknyttede svar blive slettet.",
```

2023-03-04 04:59 UTC, hariombalhara commented on apps/web/public/static/locales/de/common.json
> +  "delete_form_confirmation_1": "Sind Sie sicher, dass Sie dieses Formular löschen möchten? Jede Person, mit dem Link kann nicht mehr mit dem Formular buchen. Außerdem wurden alle zugehörigen Antwort
```suggestion
  "delete_form_confirmation": "Sind Sie sicher, dass Sie dieses Formular löschen möchten? Jede Person, mit dem Link kann nicht mehr mit dem Formular buchen. Außerdem wurden alle zugehörigen Antworten gelöscht.",
```

2023-03-04 09:58 UTC, emrysal requested changes
Please clarify the translation issue here; I do not understand the multiple bullet point situation and differences thereof and neither will translators, so this needs addressing before merge.

2023-03-05 07:10 UTC, G3root commented
> Please clarify the translation issue here; I do not understand the multiple bullet point situation and differences thereof and neither will translators, so this needs addressing before merge.

Any suggestions for naming the i18n keys here, which are more readable ?

2023-03-08 12:17 UTC, emrysal approved these changes

2023-03-08 12:39 UTC, merged