Event Type: Title not displayed in the mobile view
calcom/cal.com pull request #7451
Opened 2023-03-01 16:07 UTC by gitstart-calcom

## What does this PR do?

Fixes #7414 

## Demo
https://www.loom.com/share/17cc94539a544f5dad1d99c317017dfd

**Environment**: Staging(main branch) / Production

2023-03-01 18:01 UTC, CarinaWolli reviewed
I am not sure if we even need to hide the heading anywhere. Availability also misses the heading ([Figma Designs Availability](https://www.figma.com/file/xk4HOxtSI82J0F7enMxeak/Cal---Live?node-id=26%3A46706&t=M5JCUPFWHtYk1XNX-0)) 

@sean-brydon or @Jaibles do you know if we need to hide it in some places?

2023-03-02 06:14 UTC, gitstart-calcom commented
Hi @CarinaWolli, the heading was breaking on some of the pages that's why we thought maybe it was not supposed to show everywhere.
![Screenshot 2023-02-27 at 1 35 01 PM](https://user-images.githubusercontent.com/31402501/221505323-cee3d5b0-65f2-4c7c-9962-f355136cb5ae.png)

![Screenshot 2023-02-27 at 1 33 03 PM](https://user-images.githubusercontent.com/31402501/221505307-65879d43-d342-4c45-a4ae-3bfdcad076bf.png)

But if it's to be shown on all pages, we will make the changes accordingly

2023-03-02 06:15 UTC, gitstart-calcom commented
Also, how should we handle editable headings, like on the `Availability` page?

2023-03-02 16:34 UTC, CarinaWolli commented
> Hi @CarinaWolli, the heading was breaking on some of the pages that's why we thought maybe it was not supposed to show everywhere.

Okay. Then it would probably be best to solve that and show the headings everywhere


> Also, how should we handle editable headings, like on the Availability page?

Tagging @Jaibles

2023-03-03 03:39 UTC, gitstart-calcom commented
@Jaibles We have now too many buttons in the Availability page heading
<img width="396" alt="Screenshot 2023-03-03 at 8 54 53 AM" src="https://user-images.githubusercontent.com/31402501/222621741-4f791d82-3869-4eb3-9a1a-7efb8f0cf31f.png">

2023-03-03 08:19 UTC, Jaibles commented
> @Jaibles We have now too many buttons in the Availability page heading
> 
> <img width="396" alt="Screenshot 2023-03-03 at 8 54 53 AM" src="https://user-images.githubusercontent.com/31402501/222621741-4f791d82-3869-4eb3-9a1a-7efb8f0cf31f.png">

See my image above and check out a single event type for how to handle it.

2023-03-03 09:21 UTC, gitstart-calcom commented
> > @Jaibles We have now too many buttons in the Availability page heading
> > <img alt="Screenshot 2023-03-03 at 8 54 53 AM" width="396" src="https://user-images.githubusercontent.com/31402501/222621741-4f791d82-3869-4eb3-9a1a-7efb8f0cf31f.png">
> 
> See my image above and check out a single event type for how to handle it.

Do you mean to move the buttons to a dropdown?

2023-03-03 16:48 UTC, CarinaWolli commented
> Do you mean to move the buttons to a dropdown?

Exactly, same as we have it for event types just with "delete" and "set to default"

<img width="178" alt="Screenshot 2023-03-03 at 11 46 44" src="https://user-images.githubusercontent.com/30310907/222778330-0169757d-e005-4010-97fe-3a56d06855bb.png">

2023-03-06 10:09 UTC, gitstart-calcom commented
Thank you @Jaibles and @CarinaWolli for the clarifications. We are working on the changes

2023-03-08 12:56 UTC, emrysal commented
Converted to draft whilst changes are in progress @gitstart-calcom

2023-03-09 08:16 UTC, gitstart-calcom commented
Hi @Jaibles, noticed this weird behavior of the toggle in the detail page of the `Routing Form`
https://www.loom.com/share/c608415d33624978821a91d43e45e375

Do we really need that toggle on the detail page?
If yes, we are moving the toggle to dropdown for the mobile view but there's no label for the toggle. What should it be labeled as?
![Screenshot 2023-03-09 at 2 01 22 PM](https://user-images.githubusercontent.com/121884634/223961455-03818002-b8f6-4343-b5f8-dcbc3f2523b6.png)

2023-03-21 07:27 UTC, hariombalhara commented on apps/web/components/eventtype/EventTypeSingleLayout.tsx
> +      showHeading
I am confused why is there a showHeading prop? I would always want to show the heading.

Edit: https://github.com/calcom/cal.com/issues/5420 I found out that this was requirement to hide the heading in this case which is why hiding in mobile was implemented.

2023-03-21 07:30 UTC, hariombalhara commented on packages/features/shell/Shell.tsx
> +                    "font-cal max-w-28 sm:max-w-72 md:max-w-80 hidden truncate text-lg font-semibold tracking-wide text-black sm:text-xl md:block xl:max-w-full",
```suggestion
                    "font-cal max-w-28 sm:max-w-72 md:max-w-80 truncate text-lg font-semibold tracking-wide text-black sm:text-xl md:block xl:max-w-full",
```

2023-03-21 07:33 UTC, hariombalhara requested changes
Left some comments

2023-03-21 14:51 UTC, Jaibles commented
When I test this on live, the toggle is taking a really long time to respond, if it even responds at all.
https://user-images.githubusercontent.com/4536123/226644587-47e8baa3-d81c-475e-8134-f03b2e23fd2c.mp4

2023-04-02 12:28 UTC, PeerRich commented on apps/web/components/apps/App.tsx
> +    <Shell smallHeading isPublic showHeadingAlways heading={<ShellHeading />} backPath="/apps" withoutSeo>
i dont think this prop is a good solution

2023-04-05 17:14 UTC, gitstart-calcom commented
Hi @sean-brydon, we made the requested changes, please take a look 🙏

2023-04-11 10:15 UTC, CarinaWolli commented
>  When I test this on live, the toggle is taking a really long time to respond, if it even responds at all.
> https://user-images.githubusercontent.com/4536123/226644587-47e8baa3-d81c-475e-8134-f03b2e23fd2c.mp4

That's actually already like that now, @hariombalhara do you know why the toggle is not working (or slow)?

And @sean-brydon could you take a look again at the new changes? I think UI wise looks good

2023-04-11 10:25 UTC, sean-brydon commented
> > When I test this on live, the toggle is taking a really long time to respond, if it even responds at all.
> > https://user-images.githubusercontent.com/4536123/226644587-47e8baa3-d81c-475e-8134-f03b2e23fd2c.mp4
> 
> That's actually already like that now, @hariombalhara do you know why the toggle is not working (or slow)?
> 
> And @sean-brydon could you take a look again at the new changes? I think UI wise looks good

Much better 🙌  Looks good from my POV :)

2023-04-17 07:16 UTC, CarinaWolli approved these changes
LGTM! @hariombalhara can you review and check if your requested changes are fixed? And @sean-brydon can you give a review for @calcom/ui?

2023-04-17 07:57 UTC, hariombalhara commented
> @hariombalhara can you explain what this toggle actually does so I can come up with a reasonable line of copy to put in as a tooltip and for the label in the tooltip?

Not sure how I missed it. That toggle is supposed to make a Routing Form toggle the availability of Routing Form to public.
You can work on a Routing Form peacefully after toggling it off and then toggle it back on.

2023-04-17 07:57 UTC, hariombalhara commented
cc @Jaibles  ^^

2023-04-17 08:02 UTC, hariombalhara commented on packages/ui/components/form/switch/Switch.tsx
> +      {props.isRoutingForm ? (
I don't know why we need `isRoutingForm` here. It is a generic Switch component which shouldn't know what a Routing FOrm is

2023-04-17 08:02 UTC, hariombalhara submitted a review, later dismissed
Left a blocking comment. 

Reviewing more in the meantime.

2023-04-17 10:23 UTC, hariombalhara commented
@CarinaWolli @Jaibles Fixed the toggle not working issue. It was actually trpc query invalidation issue.

2023-04-17 10:43 UTC, hariombalhara commented on packages/app-store/routing-forms/components/FormActions.tsx
> +              label === "Disable Form"
This isn't the correct way. It's too fragile.

2023-04-18 06:07 UTC, Jaibles commented
Much better 👏

2023-04-19 20:16 UTC, zomars approved these changes
Code LGTM!

2023-04-19 20:17 UTC, merged