fix: add confirm and reject icon in email
calcom/cal.com pull request #7457
Opened 2023-03-01 21:18 UTC by Udit-takkar

Fixes https://github.com/calcom/cal.com/issues/7456

<img width="746" alt="Screenshot 2023-03-02 at 2 42 51 AM" src="https://user-images.githubusercontent.com/53316345/222267135-2043247c-7dab-4766-a05e-af1a3835f203.png">

**Environment**: Staging(main branch) / Production

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

2023-03-02 07:38 UTC, hariombalhara commented on packages/emails/src/components/LinkIcon.tsx
> +      IS_PRODUCTION ? WEBAPP_URL + `/emails/${iconName}.png` : `https://app.cal.com/emails/${iconName}.png`
I am not sure why we are keeping this IS_PRODUCTION check.
Shouldn't we just use `${WEBAPP_URL}/emails/${iconName}.png`

2023-03-02 07:45 UTC, hariombalhara submitted a review, later dismissed

2023-03-02 07:45 UTC, hariombalhara commented on packages/emails/src/components/LinkIcon.tsx
> -import { BASE_URL, IS_PRODUCTION } from "@calcom/lib/constants";
These imports are being used.

2023-03-03 23:37 UTC, PeerRich commented
hey @Udit-takkar can you look into the specs? The idea is that the buttons look identical like they look in the logged in dashboard (app.cal.com/bookings)

2023-03-03 23:39 UTC, PeerRich requested changes
buttons dont look like in dashboard yet

2023-03-08 21:44 UTC, Udit-takkar commented
<img width="1436" alt="Screenshot 2023-03-09 at 3 12 21 AM" src="https://user-images.githubusercontent.com/53316345/223856877-c610749a-5b26-43d4-a9f2-96011ba2ac48.png">

Should be fixed now. ( can't use icons from react-icons because they are not being displayed on email for some reason )

2023-03-09 10:47 UTC, PeerRich commented
both the text and icon are not centered. can you make sure it looks exactly like the figma?
![image](https://user-images.githubusercontent.com/8019099/224001470-225af708-7b34-44ea-9a7c-b100872c6e9c.png)

2023-03-09 11:29 UTC, Jaibles commented
> both the text and icon are not centered. can you make sure it looks exactly like the figma? ![image](https://user-images.githubusercontent.com/8019099/224001470-225af708-7b34-44ea-9a7c-b100872c6e9c.png)

😢 Great lengths have been gone to to spec these (and all components) in Figma. Please use them! 
<img width="1530" alt="CleanShot 2023-03-09 at 11 27 58@2x" src="https://user-images.githubusercontent.com/4536123/224010170-e41739a9-c064-4385-b864-1f035f0d976c.png">
https://www.figma.com/file/9MOufQNLtdkpnDucmNX10R/%E2%9D%96-Cal-DS?node-id=309%3A42062&t=7QcNk9ZAlBEvpGAq-1

And when these aren't available, Figma has an inspect panel to see specs yourself: https://www.figma.com/best-practices/tips-on-developer-handoff/an-overview-of-figma-for-developers/

2023-03-11 01:44 UTC, Udit-takkar commented
<img width="699" alt="Screenshot 2023-03-11 at 7 13 54 AM" src="https://user-images.githubusercontent.com/53316345/224458206-c99212c9-d932-4a1d-b3df-62ea09a0030a.png">

2023-03-12 17:15 UTC, PeerRich approved these changes
great!

2023-03-12 17:16 UTC, PeerRich commented
escalated to high priority

2023-03-12 17:39 UTC, merged