switching to stripes customer portal
calcom/cal.com pull request #772
Opened 2021-09-24 19:59 UTC by PeerRich

current billflow portal seems to be broken. we're switching to stripes native customer portal. wip, don't merge, yet.

2021-09-25 22:37 UTC, zomars commented
Implemented, but there some quirks from Stripe side. Opened a support ticket and awaiting response.

<img width="1227" alt="image" src="https://user-images.githubusercontent.com/3504472/134787558-499013c7-2cac-4df1-9904-d885deaf6894.png">

2021-09-26 22:05 UTC, PeerRich commented
> Implemented, but there some quirks from Stripe side. Opened a support ticket and awaiting response.
> 
> <img alt="image" width="1227" src="https://user-images.githubusercontent.com/3504472/134787558-499013c7-2cac-4df1-9904-d885deaf6894.png">

any responses?

2021-09-26 22:39 UTC, zomars commented
I’m afraid not yet

El 26 sep 2021, a la(s) 16:06, Peer Richelsen ***@***.***> escribió:

﻿
Implemented, but there some quirks from Stripe side. Opened a support ticket and awaiting response.


any responses?

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub, or unsubscribe.

2021-09-27 21:24 UTC, zomars commented
I mean, the current billing portal doesn't work either. So let's test on staging and wait for an official Stripe response.

2021-09-27 21:32 UTC, PeerRich commented
> I mean, the current billing portal doesn't work either. So let's test on staging and wait for an official Stripe response.

same issue 
![image](https://user-images.githubusercontent.com/8019099/134988359-619d5c01-f388-4d4c-8d29-638ecf4c510c.png)

2021-09-27 21:33 UTC, PeerRich commented
regardless of that issue, I would change this page:

![image](https://user-images.githubusercontent.com/8019099/134988429-574ef695-77f3-4d35-8e78-395058e88b2c.png)


to open the billing portal of stripe when clicking the "Billing" tab vs showing the button

2021-09-27 21:34 UTC, emrysal requested changes, later dismissed
Looks good to me, but it also looks like a force push because lint seems all over the place. In any case you probably intended to use that stripeCredentials variable so that is my only change request.

2021-09-27 21:34 UTC, emrysal commented on ee/pages/api/integrations/customer-portal.ts
> +  const stripeCredentials = user?.credentials.find(credentials);
Simple fix, I suppose.

2021-09-27 21:35 UTC, zomars commented
> regardless of that issue, I would change this page:
> 
> ![image](https://user-images.githubusercontent.com/8019099/134988429-574ef695-77f3-4d35-8e78-395058e88b2c.png)
> 
> to open the billing portal of stripe when clicking the "Billing" tab vs showing the button
> 
> essentially opening the stripe customer portal by clicking the tab

Since this is an external link, I think it would be confusing if a tab takes me to an external page. I would be even more explicit with the button text and put something like "Manage billing in Stripe's website" or something like that.

2021-09-27 21:39 UTC, baileypumfleet commented
> Since this is an external link, I think it would be confusing if a tab takes me to an external page. I would be even more explicit with the button text and put something like "Manage billing in Stripe's website" or something like that.

I agree with this. Once it's merged I can make the UI a bit better but I think it makes sense to not make the tab a button.

Once @emrysal's change is fixed I'm happy to approve & merge

2021-09-27 22:53 UTC, zomars commented
All ready @baileypumfleet

2021-09-27 22:57 UTC, merged