Fix: use ip address in forgot password rate limitation
calcom/cal.com pull request #7832
Opened 2023-03-20 11:59 UTC by G3root

## What does this PR do?

fix for the comments from https://github.com/calcom/cal.com/pull/7700#discussion_r1140716657

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

2023-03-20 12:03 UTC, G3root commented on apps/web/pages/api/auth/forgot-password.ts
> +    ip = forwardedFor?.split(",").at(0) ?? email;
FYI https://vercel.com/docs/concepts/edge-network/headers#x-forwarded-for there's warning that IP-address won't be forwarded if Vercel is behind a proxy.

2023-03-28 20:11 UTC, zomars requested changes, later dismissed
How can we test this?

2023-03-30 15:44 UTC, G3root commented
@zomars  here's minimal reproduction for this https://ip-ratelimit-test.vercel.app/. requests are rate limited 5 per minute.

source code: https://github.com/G3root/ip-ratelimit-test

2023-04-10 20:25 UTC, Udit-takkar requested changes
<img width="1014" alt="Screenshot 2023-04-11 at 1 55 23 AM" src="https://user-images.githubusercontent.com/53316345/230991504-c8937af0-770d-431b-87f2-1ac45371cfbe.png">

I am getting 500 internal server error instead of 429 too many Requests

2023-04-25 06:53 UTC, G3root commented
@Udit-takkar pushed a fix for that

2023-04-29 07:26 UTC, Udit-takkar approved these changes

2023-05-30 19:38 UTC, merged