Uri
calcom/cal.com pull request #7838
Opened 2023-03-20 14:48 UTC by Quentin-Guillemin

## What does this PR do?

Add `NEXT_PUBLIC_WEBAPP_URI` env variable to be able to host cal.com on a URI.

Fixes # (issue)

https://github.com/calcom/cal.com/issues/5980

**Environment**: Staging(main branch) / Production

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## How should this be tested?

- [ ] Build with URI and test each route

## Checklist

- I haven't added tests that prove my fix is effective or that my feature works

2023-03-21 06:54 UTC, hariombalhara commented on packages/lib/constants.ts
> +export const WEBAPP_URI = process.env.NEXT_PUBLIC_WEBAPP_URI || "";
I think we should call it something like WEBAPP_PREFIX_PATH

2023-03-21 06:57 UTC, hariombalhara commented on packages/lib/constants.ts
> +export const WEBAPP_URI = process.env.NEXT_PUBLIC_WEBAPP_URI || "";
Also, it might be a nice to have a validation for it that it must start with /

2023-03-21 07:09 UTC, hariombalhara commented on apps/web/components/apps/App.tsx
> +              <img className="min-h-16 min-w-16 h-16 w-16" src={WEBAPP_URI + logo} alt={name} />
Can we not remove all these usages of WEBAPP_URI by setting base href. My concern is that developers will certainly forget adding that WEBAPP_URI

2023-03-21 07:12 UTC, hariombalhara reviewed
Thanks @Quentin-Guillemin for the contribution 🙏. I have left some comments

2023-03-21 17:35 UTC, zomars requested changes
Agreed that we should support hosting on a different base path. Although I think we can achieve this without too much destructive changes. Also we should make this opt-in so people who are not using it aren't affected by these changes.

Blocking until these concerns and @hariombalhara comments are addressed.

Thanks again for your contribution 🙏🏽

2023-03-23 07:38 UTC, hariombalhara commented
@Quentin-Guillemin I was talking about using base HTML tag. Found an article that recommends that https://skryvets.com/blog/2018/09/20/an-elegant-solution-of-deploying-react-app-into-a-subdirectory/

But there is a problem with this approach as well, we would have to convert all paths to relative paths, which is also not straightforward.

One approach might be to just prefix every image src with WEBAPP_URL and have a linting rule that ensures it is always done.

I would have to test more to understand what approach will work best.

2023-04-17 13:38 UTC, Quentin-Guillemin commented
Hi @hariombalhara,

Have you chosen a solution ?

2023-04-17 13:49 UTC, hariombalhara commented
@Quentin-Guillemin I am afraid, I couldn't prioritize it yet.

2023-06-26 11:27 UTC, keithwillcode commented
@hariombalhara @zomars Are we good to come back and review this once more?

2023-06-28 12:13 UTC, hariombalhara commented
@keithwillcode There are just too many changes with the current approach. Unless we figure out a way to solve it in a trivial manner, we should avoid the implementation as it isn't a very common requirement.

2023-07-16 21:34 UTC, PeerRich commented
> @keithwillcode There are just too many changes with the current approach. Unless we figure out a way to solve it in a trivial manner, we should avoid the implementation as it isn't a very common requirement.

I agree with @hariombalhara here. So much goin on here with little known potential side-effects. Very niche request.

@Quentin-Guillemin this seems like it's solving a problem for yourself, I think its smart to keep this fix in your own personal fork for now! Thank you for the effort of raising this PR tho!

closing

2023-07-16 21:34 UTC, closed without merging