resolved typescript problems for success.tsx, useTheme.tsx and event.ts
calcom/cal.com pull request #786
Opened 2021-09-27 04:34 UTC by Heaust-ops

Cleaned up some Typescript problems.

2021-09-27 10:28 UTC, PeerRich commented
thank you! our team will look at it :)

2021-09-27 11:56 UTC, KATT requested changes
Thanks for this, the types overall in cal needs a lot of work. 🙏 

The thing I'd say overall is to try to lean on type inference over declared types, added comments inline.

2021-09-27 11:56 UTC, KATT commented on pages/success.tsx
> +  const router: NextRouter = useRouter();
This is inferred so it's obsolete

```suggestion
  const router = useRouter();
```

2021-09-27 11:56 UTC, KATT commented on pages/success.tsx
> +  const { location, name, reschedule }: ParsedUrlQuery = router.query;
This is inferred so it's obsolete

```suggestion
  const { location, name, reschedule } = router.query;
```

2021-09-27 11:56 UTC, KATT commented on pages/success.tsx
> +                                encodeURIComponent(typeof location === "string" ? location : false)
```suggestion
                                typeof location === "string" ? encodeURIComponent(location) : ''
```

2021-09-27 11:56 UTC, KATT commented on pages/success.tsx
> +  const eventType: returnEventType | null = await prisma.eventType.findUnique({
This is inferred so shouldn't be needed

```tsx
  const eventType = await prisma.eventType.findUnique({
```

2021-09-27 11:56 UTC, KATT commented on pages/success.tsx
> +  const eventType: returnEventType | null = await prisma.eventType.findUnique({
then follow-up with 

```ts
const eventTypeWithUsers = {
  ...eventType,
  users: !eventType.users.length && eventType.userId ? await prisma.user.findUnique({...}) : eventType.users`
}
```

2021-09-27 11:58 UTC, KATT commented on pages/success.tsx
> +  const eventType: returnEventType | null = await prisma.eventType.findUnique({
Or maybe that second part isn't needed, we can probably just `push()` it like we do now - the type inference should already guarantee that it'shas all the same fields

2021-09-27 13:33 UTC, Heaust-ops commented
Made the requested changes : )
I'll always lean on inferred types now

2021-09-28 10:40 UTC, emrysal approved these changes
getServerSideProps(context: GetServerSidePropsContext) -> other than that all good! :)

2021-09-28 18:57 UTC, KATT commented on pages/success.tsx
> +export async function getServerSideProps(context: { query: { type: string } }) {
as @emrysal  said
```suggestion
export async function getServerSideProps(context: GetServerSidePropsContext) {
```

2021-09-28 21:32 UTC, Heaust-ops commented
Applied requested changes : )

2021-10-05 22:53 UTC, merged