Fix timezone select - create two variants
calcom/cal.com pull request #7875
Opened 2023-03-22 06:49 UTC by sean-brydon

<img width="1072" alt="CleanShot 2023-03-22 at 14 30 27@2x" src="https://user-images.githubusercontent.com/55134778/226823868-666916f3-3ef1-42cc-9da2-68640df76510.png">
<img width="1029" alt="CleanShot 2023-03-22 at 14 46 35@2x" src="https://user-images.githubusercontent.com/55134778/226823875-7ce884e4-2428-4817-966a-7d03811538b5.png">
<img width="805" alt="CleanShot 2023-03-22 at 14 46 45@2x" src="https://user-images.githubusercontent.com/55134778/226823880-f2172046-d795-4696-acc4-2dd4e0f429d9.png">

2023-03-22 06:50 UTC, sean-brydon commented on packages/ui/form/TimezoneSelect.tsx
Duplicate

2023-03-24 18:17 UTC, Udit-takkar requested changes, later dismissed
<img width="278" alt="Screenshot 2023-03-24 at 11 36 19 PM" src="https://user-images.githubusercontent.com/53316345/227605463-80638aa2-2233-4bf7-9a20-79843aab270b.png">

Few minor issues that needs to be fixed

1) In light mode the text color of timezone select is darker than the above text( Cal Video, 30 minutes)
2) can you increase the width of the dropdown component?

2023-03-26 00:00 UTC, roae approved these changes
LGTM! 🚀

2023-03-26 19:19 UTC, emrysal approved these changes
Approved :)

2023-03-26 19:19 UTC, merged