fix/insights-yarn-lock-and-7921
calcom/cal.com pull request #7922
Opened 2023-03-23 22:14 UTC by alannnc

## What does this PR do?

Fixes # (issue)

**Environment**: Staging(main branch) / Production

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

- [ ] Test A
- [ ] Test B

## Checklist

- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't performed a self-review of my own code and corrected any misspellings
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my PR needs changes to the documentation
- I haven't checked if my changes generate no new warnings
- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

2023-03-24 17:04 UTC, Jaibles commented
Great work @alannnc!

Small UI issues (I'll keep adding to this list)...
- [ ] Make the border around each chart 200 not 300. (We use 300 for inputs, buttons & interactive things, not content containers.)
- [ ] Make the page title just "Insights" not "Insights for...". The latter kinda implies you can't change it.
- [ ] We need to improve the clear filter UI and the fact that it jumps left. I'll provide designs for this as there's too many things we need to fix to list. This isn't Alan's doing, the end result has different filters than design so just need to account for that.
- [ ] Put an `mb-8` below the title to separate the charts instead of `mb-4`
- [ ] There's an `mt-4` on the chart separating it from the title. We can remove it..

If anything is not clear, just let me know and I'll share a loom.

2023-03-24 22:25 UTC, zomars requested changes

2023-03-24 22:25 UTC, zomars commented on packages/features/insights/components/Card.tsx
> +const CardInsights = (props: ICardProps) => {
```suggestion
export const CardInsights = (props: ICardProps) => {
```

2023-03-24 22:25 UTC, zomars commented on packages/features/insights/components/Card.tsx
> +export { CardInsights };
```suggestion
```

2023-03-28 22:02 UTC, zomars approved these changes

2023-03-28 22:59 UTC, zomars commented on packages/features/insights/filters/DateSelect.tsx
> +        color="black"
```
Type '"black"' is not assignable to type '"slate" | "gray" | "zinc" | "neutral" | "stone" | "red" | "orange" | "amber" | "yellow" | "lime" | "green" | "emerald" | "teal" | "cyan" | "sky" | "blue" | "indigo" | "violet" | "purple" | "fuchsia" | "pink" | "rose" | undefined'.ts(2322)
```

2023-03-28 23:24 UTC, merged