Trim hyphen when slugifying team name
calcom/cal.com pull request #7923
Opened 2023-03-24 03:26 UTC by saikarsis

## What does this PR do?

Improves the auto-generated slug when creating a team by trimming unexpected trailing hyphens.
Unexpected trailing hyphens occur when inputting a team name with punctuation, such as "My team!"

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- [ ] Start creating a new team and input the name "My team!" and observe the absence of a trailing hyphen in the slug.
- [ ] Start creating a new team and input the name "Another team-" and observe the retention of a trailing hyphen in the slug.

## Checklist

- I haven't added tests that prove my fix is effective or that my feature works

2023-04-11 15:36 UTC, hariombalhara commented on packages/features/ee/teams/components/CreateANewTeamForm.tsx
> +  const slugified_str = slugify(str);
I am not sure what testcase I missed but the objective can be met by 
```javascript
function noTrailingHyphenSlugify2(str) {
  const slugified_str = slugify(str);
  return slugified_str.replace(/-*$/, '')
}`

2023-04-11 15:37 UTC, hariombalhara requested changes
Thanks for your contribution @saikarsis 🙏 I have left a suggestion that can possible improve the code. Please check that.

Blocking merge till that time.

2023-04-11 15:38 UTC, hariombalhara commented on packages/features/ee/teams/components/CreateANewTeamForm.tsx
> +  const slugified_str = slugify(str);
Also, I think we can improve the slugify logic itself to tackle this. No one would want trailing hyphens.

2023-04-18 14:18 UTC, hariombalhara commented
Moving it to draft till requested comments are addressed.

2023-05-11 23:51 UTC, PeerRich commented
@hariombalhara what do we do here?

2023-07-11 00:19 UTC, closed without merging