Set GCal iCalUID in .ics file
calcom/cal.com pull request #8010
Opened 2023-03-29 14:29 UTC by joeauyeung

## What does this PR do?

This PR fixes Gmail parsing our .ics file and adding double events in GCal by adding the iCalUID when creating events to the .ics file we generate.

Fixes # (issue)

**Environment**: Staging(main branch) / Production

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- Connect GCal
- Create an event
- From the email get the .ics file
- Send the .ics to your inbox. When clicking "View on Google Calendar" it should open the event that we created
- Reschedule that booking
- The new .ics file should still point to the event that we created

## Checklist

- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

2023-03-29 16:48 UTC, joeauyeung commented on packages/app-store/office365calendar/lib/CalendarService.ts
> +      return { ...responseJson, iCalUID: responseJson.iCalUId };
Notice in Outlook the property has a lower case "d". Through out the call I think we should standardize it to UID as that's the property name in the .ics file

2023-03-30 12:59 UTC, Udit-takkar requested changes
This does not work when i have selected secondary calendar as destination.

First i scheduled the event 

<img width="161" alt="Screenshot 2023-03-30 at 6 23 33 PM" src="https://user-images.githubusercontent.com/53316345/228843176-a078ad69-8153-4c53-9c93-d81c60072d22.png">

then i rescheduled the event to 30th april which created event in both primary and secondary calendar

<img width="161" alt="Screenshot 2023-03-30 at 6 28 47 PM" src="https://user-images.githubusercontent.com/53316345/228843432-9c137d3d-d2c3-4d33-a5c6-d1f4a2cbba65.png">

2023-03-30 13:04 UTC, Udit-takkar commented
@joeauyeung i fixed something similar before here https://github.com/calcom/cal.com/pull/7406 . maybe we should do the same thing in updateEvent method in googlecalendar/lib/CalendarService

2023-04-03 00:47 UTC, joeauyeung commented on packages/emails/templates/attendee-scheduled-email.ts
> +      uid: this.calEvent.iCalUID || this.calEvent.uid!,
We set non-null for `uid` here since every booking should have a `uid` associated with it on Cal

2023-04-03 10:54 UTC, Udit-takkar approved these changes
LGTM. working fine

2023-04-03 13:53 UTC, emrysal approved these changes
Reverted the serverConfig change, but besides that it looks good to me 🙏 🎉

2023-04-03 17:13 UTC, merged