Fix workflows on seated events
calcom/cal.com pull request #8034
Opened 2023-03-30 20:14 UTC by alannnc

## What does this PR do?

Add workflows to be executed when a booking with seats is executed.

Fixes # (issue)

**Environment**: Staging(main branch)

## Type of change

- Chore (refactoring code, technical debt, workflow improvements)

## How should this be tested?

- [ ] Add a booking with seats, setup any workflow
- [ ] Book that event type
- [ ] Expect workflows to be executed

## Checklist

- I haven't added tests that prove my fix is effective or that my feature works

2023-03-30 20:15 UTC, alannnc commented on packages/features/ee/workflows/lib/reminders/reminderScheduler.ts
> +        for (const step of workflow.steps) {
Prefer for of instead of forEach async.

2023-03-30 20:17 UTC, alannnc commented on packages/features/bookings/lib/handleNewBooking.ts
> +      if (seatAttendee?.id && bookingSeat?.id) {
This has wrong type from main, had to do some conditionals to don't run if seatAttendee is null.

2023-03-30 20:19 UTC, alannnc commented on packages/features/bookings/lib/handleNewBooking.ts
> +      | null = null;
Changes here are: Add some logic so we only have one return so we can run workflows and everything else in every case.

2023-03-30 20:30 UTC, alannnc commented on packages/features/bookings/lib/handleNewBooking.ts
> +          videoCallData: evt.videoCallData,
passing down only required props

2023-04-03 09:13 UTC, CarinaWolli requested changes

2023-04-13 09:00 UTC, CarinaWolli approved these changes
LGTM! Thank you 🙏

2023-04-13 19:03 UTC, merged