[App Store] Zoho Calendar
calcom/cal.com pull request #8144
Opened 2023-04-08 01:06 UTC by murtajaziad

## What does this PR do?

An app to integrate Zoho Calendar and Cal.com using the official Zoho Calendar API.

Fixes #5451 

**Environment**: Staging(main branch)

## Type of change

- New feature (non-breaking change which adds functionality)

## How should this be tested?

No automated tests are set up for this. 
You can manually test the integration by following these steps:
1. Link your Zoho account with your Cal.com account.
2. Set your default calendar for creating the events to your Zoho Calendar.
3. Book an event to try the integration.

## Checklist

- I haven't checked if my changes generate no new warnings
- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

---

/claim #5451

2023-04-08 06:41 UTC, hariombalhara commented
@murtajaziad Thanks for the PR !! I am wondering if https://github.com/calcom/cal.com/pull/7182 added similar functionality already or not. Also, if it didn't would it make sense to add the functionality into that existing app.

2023-04-08 11:55 UTC, murtajaziad commented
> @murtajaziad Thanks for the PR !! I am wondering if #7182 added similar functionality already or not. Also, if it didn't would it make sense to add the functionality into that existing app.

HI @hariombalhara, I have just checked #7182 and it doesn't include any Zoho Calendar functionality, it uses the events/meetings module that's provided by the CRM API. Also, Zoho Calendar and Zoho CRM are two different products that apparently don't overlap.

2023-04-08 11:58 UTC, hariombalhara commented
@PeerRich can you confirm if we want to do it in a separate app?

2023-04-19 09:28 UTC, hariombalhara commented on packages/app-store/zohocalendar/DESCRIPTION.md
> +  - /api/app-store/zohocalendar/ZCal1.jpg
```suggestion
  - ZCal1.jpg
```
No need to use full URL. This should also work. It avoids hardcoding app slug and thus simplifies changing it(if needed)

2023-04-19 09:29 UTC, hariombalhara commented on packages/app-store/zohocalendar/DESCRIPTION.md
> +Zoho Calendar is an online business calendar that makes scheduling easy for you. You can use it to stay on top of your schedule and also share calendars with your team to keep everyone on the same pa
@sydwardrae @Jaibles Please review App description

2023-04-19 09:31 UTC, hariombalhara commented on packages/app-store/zohocalendar/_metadata.ts
> +  imageSrc: "/api/app-store/zohocalendar/icon.svg",
```suggestion
  imageSrc: "/api/app-store/zohocalendar/icon.svg",
```
It's deprecated and not needed in any new app. `logo` does the same job

2023-04-19 09:31 UTC, hariombalhara commented on packages/app-store/zohocalendar/_metadata.ts
> +  logo: "/api/app-store/zohocalendar/icon.svg",
```suggestion
  logo: "icon.svg",
```

Using relative URL keeps it simple

2023-04-19 09:32 UTC, hariombalhara commented on packages/app-store/zohocalendar/_metadata.ts
> +  reviews: 69,
```suggestion
```

2023-04-19 09:32 UTC, hariombalhara commented on packages/app-store/zohocalendar/_metadata.ts
> +  rating: 5,
```suggestion
```

2023-04-19 09:36 UTC, hariombalhara commented on packages/app-store/zohocalendar/_metadata.ts
> +  verified: true,
```suggestion
```

2023-04-19 09:36 UTC, hariombalhara commented on packages/app-store/zohocalendar/_metadata.ts
> +  dirName: "zohocalendar",
```suggestion
```

2023-04-19 09:47 UTC, hariombalhara commented on packages/app-store/zohocalendar/_metadata.ts
> +import type { AppMeta } from "@calcom/types/App";
Replacing this file with config.json. It is deprecated and AppStore CLI doesn't create it.

2023-04-19 12:16 UTC, hariombalhara commented on packages/app-store/zohocalendar/README.md
@murtajaziad Please add details on how to obtain credentials for Zoho Calendar

2023-04-19 12:17 UTC, hariombalhara commented on packages/app-store/zohocalendar/api/add.ts
> +export default defaultHandler({
Wrapped up endpoints in defaultHandler

2023-04-19 13:10 UTC, hariombalhara submitted a review, later dismissed
Left some comments

2023-05-10 06:14 UTC, hariombalhara commented on packages/app-store/zohocalendar/api/callback.ts
> +const zohoKeysSchema = z.object({
We can just import it from zod.ts

2023-05-10 06:36 UTC, hariombalhara commented
<img width="1183" alt="Screenshot 2023-05-10 at 11 54 08 AM" src="https://github.com/calcom/cal.com/assets/1780212/7f312eab-8c91-4ee9-9e05-cc21ff521953">
I see `undefined` here.
Also, I think for the same reason I see this error while booking.
<img width="673" alt="Screenshot 2023-05-10 at 12 06 05 PM" src="https://github.com/calcom/cal.com/assets/1780212/586e6998-9692-4ea2-8c9e-df8f9ffb8536">

2023-05-11 06:04 UTC, hariombalhara requested changes
Requesting changes again based on my last comment

2023-06-28 00:51 UTC, alannnc requested changes
Made some fixes.
Code looks good, we just missing if createEvent/updateEvent fails throw error so handleNewBooking stops.

2023-06-29 21:20 UTC, alannnc approved these changes
Made some changes and I think it should be good to go now.
Leaving last approve to @hariombalhara

2023-07-19 00:34 UTC, joeauyeung requested changes

2023-07-19 00:34 UTC, joeauyeung commented on packages/app-store/zohocalendar/lib/CalendarService.ts
> +      const eventResponse = await this.fetcher(`/calendars/${calendarId}/events/${eventId}?${query}`, {
This endpoint requires an `etag` that we can get by first retrieving the event on the calendar. This is to ensure that the calendar event wasn't updated while this request is being made.

2023-07-19 00:34 UTC, joeauyeung commented on packages/app-store/zohocalendar/lib/CalendarService.ts
> +  async deleteEvent(uid: string, event: CalendarEvent, externalCalendarId?: string) {
Also getting a missing `etag` error for this method.

2023-07-25 15:23 UTC, closed without merging

2023-07-27 20:34 UTC, murtajaziad commented
I have made all the required changes, fyi. auto-generated files are being auto created and added to git by a pre-commit hook.