Add Plausible (Custom) App
calcom/cal.com pull request #8189
Opened 2023-04-11 10:59 UTC by Hybes

## What does this PR do?

Add's support self-hosted instances of Plausible, where the URL of the script.js file may be configured by the user.
Adjusted configuration of BookingPageTagManager to also val.replace {PLAUSIBLE_URL} with the configured value.
Tested locally and the script is set correctly in the final site HTML.

Fixes # (issue)

No issue related

**Environment**: Staging(main branch) / Production

## Type of change

- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## How should this be tested?

Add new app "Plausible (Custom)"

- [ ] Configure Plausible URL
- [ ] Configure Domain URL

## Checklist

- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

2023-04-11 12:12 UTC, hariombalhara commented
Thanks for the PR @Hybes 🙏
I am not very sure but have you considered the possibility of using the same Plausible app that can allow specifying the PLAUSIBLE_URL. We can make some changes so that the configuration shows up only for self hosters.

2023-04-11 12:15 UTC, Hybes commented
> Thanks for the PR @Hybes 🙏 I am not very sure if it can work but have you considered the possibility of using the same Plausible app that can allow specifying the PLAUSIBLE_URL. We can make some changes so that the configuration shows up only for self hosters.
> 
> If same app can work, I think that would be the best approach

Yeah it's certainly possible, i'm not certain how to make that value of PLAUSIBLE_URL have a default, basically all it needs to do, is work the exact same way as mine, but if the user doesn't specify - it should just use the URL "plausible.io"

2023-04-11 12:33 UTC, hariombalhara commented
That should be trivial. Maybe you can make the required changes to work with existing app first and then it can be done.

2023-04-11 13:13 UTC, hariombalhara requested changes
Let's make the changes in existing app.

2023-04-11 20:48 UTC, Hybes commented
let me know if you need anything else done to it :)

2023-04-15 01:12 UTC, Hybes commented
@hariombalhara @PeerRich this sat inactive for a reason? do you need me to do any more changes to this?

2023-04-18 10:39 UTC, hariombalhara commented on packages/app-store/BookingPageTagManager.tsx
> +            ? (val.replace(/\{TRACKING_ID\}/g, trackingId).replace(/\{PLAUSIBLE_URL\}/g, plausibleUrl) as T)
BookingPageTagManager is a generic fn and it shouldn't be aware of an app specific template variable. I am fixing it.

2023-04-18 10:48 UTC, hariombalhara commented on packages/app-store/BookingPageTagManager.tsx
> +        const parseValue = <T extends string | undefined>(val: T): T => {
@Hybes Supports any random variable now

2023-04-18 10:51 UTC, hariombalhara commented on packages/app-store/plausible/zod.ts
> +    PLAUSIBLE_URL: z.string().optional().default("https://plausible.io/js/script.js").or(z.undefined()),
Whe can it be undefined if default is already a string.

2023-04-18 11:02 UTC, Hybes commented on packages/app-store/BookingPageTagManager.tsx
> +        const parseValue = <T extends string | undefined>(val: T): T => {
great stuff!

2023-04-18 11:22 UTC, hariombalhara approved these changes

2023-04-18 11:23 UTC, hariombalhara commented
@Hybes can you do a final round of testing. Will merge after that.

2023-04-18 11:29 UTC, hariombalhara commented on packages/app-store/plausible/components/EventTypeAppCardInterface.tsx
> +        placeholder="https://plausible.io/js/script.js"
Added this placeholder so that if someone removes the entire input text, he knows what kind of inputs goes in it.

2023-04-18 13:54 UTC, hariombalhara commented
Merging it. Thanks for your contribution @Hybes !!

2023-04-18 13:54 UTC, merged