CALCOM-7156 - [CAL-1095] Embed modal (floating pop up button) - UI/layout/spacing issues
calcom/cal.com pull request #8217
Opened 2023-04-12 03:37 UTC by gitstart-calcom

Here is the GitStart Ticket for this pull request: [CALCOM-7156](https://developers.gitstart.com/ticket/CALCOM-7156)

- Please mark your PR as "ready for review" when you have completed all requirements.
- Please ensure that your PR is reviewed by at least 2 people after you have completed it.
- Comments for review or requested changes from the upstream client will be notified to you by email and will also show on the [ticket page](https://developers.gitstart.com/ticket/CALCOM-7156).
- After the PR is merged on the upstream, please merge this PR.
- If there exist merge conflicts on your current PR and you have to close the PR instead of merging it, please go to the [ticket page](https://developers.gitstart.com/ticket/CALCOM-7156) to manually finish the task that is related to this PR.

Happy hacking! 🎉

# Demo

https://user-images.githubusercontent.com/26940294/220696494-9d20e7e8-fe0d-4517-b2b2-9eea71b3e55a.mov

2023-04-13 08:20 UTC, CarinaWolli requested changes, later dismissed
Tablet view is broken, let's just put _button color_ and _text color_ under each other when the screen is getting too small: 
![Screenshot 2023-04-13 at 10 14 36](https://user-images.githubusercontent.com/30310907/231698349-a42dc0d6-d9d3-4624-933d-abcc0e82790c.png)

Everything else looks good to me 🙏

2023-04-13 08:20 UTC, CarinaWolli commented on packages/ui/components/form/color-picker/colorpicker.tsx
> +  colorInputClassName?: string;
```suggestion
  className?: string;
```

2023-04-22 00:01 UTC, PeerRich commented
we should also extract all strings into en/common.json

2023-04-25 10:46 UTC, hariombalhara commented
<img width="422" alt="Screenshot 2023-04-25 at 4 15 07 PM" src="https://user-images.githubusercontent.com/1780212/234253909-69eea76f-c82b-4eb0-bd68-e65a08633e7f.png">
<img width="410" alt="Screenshot 2023-04-25 at 4 15 18 PM" src="https://user-images.githubusercontent.com/1780212/234253948-6d2db3c4-ee71-44f5-9038-4cd4667b7cda.png">

Too much spacing above Theme Selector which I think is unexpected.

2023-04-25 10:47 UTC, hariombalhara requested changes
Left a comment. Apart from that it's good.

2023-05-01 11:12 UTC, hariombalhara approved these changes

2023-05-02 12:32 UTC, hariombalhara commented
@CarinaWolli I guess it just needs your review to be merged.

2023-05-02 18:56 UTC, keithwillcode approved these changes

2023-05-02 18:57 UTC, merged