fix: reccuring input width
calcom/cal.com pull request #8227
Opened 2023-04-12 09:18 UTC by joeshajan

## What does this PR do?

Fixes #8220

Before

![image](https://user-images.githubusercontent.com/69904519/231397421-c314ca7b-35b6-4551-aec1-501fcca3ee9b.png)

After

![image](https://user-images.githubusercontent.com/69904519/231412162-fe102191-6839-4d36-9a9a-8c30d4712d01.png)

**Environment**: Staging(main branch) / Production

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- [ ] Test A
- [ ] Test B

2023-04-12 09:20 UTC, joeshajan commented
Right now this input box is duplicated in different places. Should we make it a component and reuse it?

2023-04-12 10:12 UTC, sean-brydon commented
> Right now this input box is duplicated in different places. Should we make it a component and reuse it?

Hey bud we have - cal/packages/ui/components/form/inputs/Input.tsx. We could one create a reusable version for just NumberInput (Like we have for Email etc) or just use the Input defined here

2023-04-12 10:13 UTC, sean-brydon requested changes
Lets reuse our Input component :) 

Gimme a shout if you have any questions

2023-04-12 10:20 UTC, joeshajan commented
> Lets reuse our Input component :)
> 
> Gimme a shout if you have any questions

Sure, I got you! I'll start working on it right away

2023-04-13 03:32 UTC, joeshajan commented
Hey @sean-brydon, just wanted to let you know that I created a new NumberInput component and used it on the booking availability page. Can I use it in other places too? Waiting for your confirmation.

2023-04-13 03:57 UTC, joeshajan commented on apps/web/components/booking/pages/AvailabilityPage.tsx
> +                              className="me-2 inline w-16"
should I add width here

2023-04-13 17:32 UTC, sean-brydon commented on apps/web/components/booking/pages/AvailabilityPage.tsx
> +                              className="me-2 inline w-16"
Yep :)

2023-04-13 17:33 UTC, sean-brydon approved these changes
Thank you for this :)

2023-04-13 18:26 UTC, merged