feat: add support endpoint
calcom/cal.com pull request #8404
Opened 2023-04-20 12:39 UTC by G3root

## What does this PR do?

this PR add `/support` page which redirects to `/event-types` and opens intercom

## Type of change

- New feature (non-breaking change which adds functionality)

2023-04-20 17:25 UTC, PeerRich commented
somehoe vercel failing

2023-04-21 13:00 UTC, PeerRich approved these changes
works well. lemme know if there are any code-related objections @emrysal

2023-04-21 13:40 UTC, emrysal requested changes
next.config.js is the better place to do this

2023-04-21 13:48 UTC, emrysal approved these changes

2023-04-21 14:18 UTC, merged