fix: changed assign to field as typeable input
calcom/cal.com pull request #8472
Opened 2023-04-23 18:34 UTC by joe-shajan

## What does this PR do?

Fixes #8412

Changed assign_to field as a simple typable input.

**After**
![assign to dark](https://user-images.githubusercontent.com/69904519/233857920-561f8ac7-1c2f-4eb3-a62e-8319c4d0e8a9.png)

So after this `ChildrenEventTypeSelect` file is not used anymore right? but when I tried to delete it. I noticed that it's also used in `event-types/[type]/index.tsx` Can I remove it from there also? Or is there any other use for it?

## Checklist
- I haven't added tests that prove my fix is effective or that my feature works

2023-04-24 06:32 UTC, joe-shajan commented
e2e test is failing is it because I changed the select input to normal typable input? @PeerRich

2023-04-25 10:27 UTC, hariombalhara requested changes
I think what @PeerRich meant here was to enable search within the select. What I see is it has become just a text field now.

2023-04-25 10:36 UTC, hariombalhara commented
Select supports it already. I think it's disabled there not sure why

2023-04-25 10:38 UTC, joe-shajan commented
> Select supports it already. I think it's disabled there not sure why

Ok thanks, will check that out.

2023-04-28 17:24 UTC, joe-shajan commented on packages/prisma/.env
This happened by mistake. I'm not able to fix it. Why is this compared since the content are same?

2023-04-28 17:27 UTC, joe-shajan commented
Hi, @hariombalhara searchable for select was set to false. So I removed that line because the select compnent is searchable by default.

https://user-images.githubusercontent.com/69904519/235213736-0a41db5c-041f-4670-bb00-da89a54ef5b3.mp4

2023-05-03 05:16 UTC, joe-shajan commented on packages/prisma/.env
Can you help me with this? @hariombalhara

2023-05-03 11:16 UTC, Udit-takkar commented
@joe-shajan just create a new branch and raise a new PR with packages/features/eventtypes/components/ChildrenEventTypeSelect.tsx changes

2023-05-03 11:17 UTC, joe-shajan commented
> @joe-shajan just create a new branch and raise a new PR with packages/features/eventtypes/components/ChildrenEventTypeSelect.tsx changes

Sure will do that 👍

2023-05-03 11:29 UTC, joe-shajan commented
Closing this pull request and raised a new one #8637

2023-05-03 11:29 UTC, closed without merging