fix: password not updatable after an api error
calcom/cal.com pull request #8514
Opened 2023-04-25 11:10 UTC by G3root

## What does this PR do?

Fixes #8502 

[Screencast 2023-04-25 16:35:26.webm](https://user-images.githubusercontent.com/84864519/234259345-25d43c2b-df7f-4d1d-a015-06ad6b77f910.webm)

## Type of change

- Bug fix (non-breaking change which fixes an issue)

2023-04-26 08:31 UTC, PeerRich approved these changes

2023-04-26 13:03 UTC, hariombalhara commented on packages/ui/components/form/inputs/Input.tsx
> +            form.clearErrors("apiError");
<img width="1050" alt="Screenshot 2023-04-26 at 6 31 19 PM" src="https://user-images.githubusercontent.com/1780212/234582849-05114545-5354-46e5-ade1-f2463d772bb7.png">
This is a better place to handle `apiError` as it is added by Change Password logic and doesn't make sense in generic Input component.

I think we should remove the complete condition at line 350.

2023-04-26 13:04 UTC, hariombalhara requested changes
Left a comment. The change is pretty small that I requested.

2023-04-26 19:11 UTC, G3root commented
@hariombalhara pushed those requested changes

2023-04-27 09:26 UTC, hariombalhara approved these changes

2023-04-27 11:43 UTC, merged