Save button color fix for close.com app
calcom/cal.com pull request #8566
Opened 2023-04-29 18:43 UTC by prasanthrv98

## What does this PR do?

Fixes #8358  

**Environment**:  Production

## Type of change

Bug fix
Added CSS class to view the button in dark mode as well.

## How should this be tested?
Navigate to Close.com and install it in the App Store menu to see the change.
<img width="649" alt="Screenshot 2023-04-29 at 11 12 07 PM" src="https://user-images.githubusercontent.com/52619709/235318640-449ed395-579c-4442-87e0-eb5002001eda.png">

2023-05-06 13:16 UTC, hariombalhara approved these changes
Thank you @prasanthrv98

2023-05-08 11:56 UTC, CarinaWolli requested changes

2023-05-08 11:56 UTC, CarinaWolli commented on packages/app-store/closecom/pages/setup/index.tsx
> +                  <Button color="secondary" type="submit" loading={form.formState.isSubmitting}>
The save button should stay primary here, but it looks like dark mode is not working correctly. Same happens for the zapier setup page: 
<img width="762" alt="Screenshot 2023-05-08 at 13 53 42" src="https://user-images.githubusercontent.com/30310907/236817251-2295da13-cb0a-422c-babb-c4b3d047eab1.png">

@sean-brydon Any idea why the dark mode for the primary button is not working here?

2023-05-09 06:47 UTC, CarinaWolli commented on packages/app-store/closecom/pages/setup/index.tsx
> +                  <Button color="secondary" type="submit" loading={form.formState.isSubmitting}>
There is a PR up to fix that: https://github.com/calcom/cal.com/pull/8758

2023-05-09 17:34 UTC, closed without merging