Fix: Full name is not refreshing on update
calcom/cal.com pull request #8569
Opened 2023-04-29 22:04 UTC by AshishBarvaliya

## What does this PR do?

Fixes #8567 

## Type of change
The session may retain previous user information even after it has been updated. Therefore, to ensure that we are using the most up-to-date user information, we are retrieving the user details directly from the `user` table rather than relying solely on the session details.

2023-04-29 22:35 UTC, AshishBarvaliya commented
@zomars 
If my proposed fix is appropriate, then we may also need to update this part of the code(workflow - filters) since it is also currently retrieving user information from the session, rather than the updated user information.

`packages/features/ee/workflows/pages/index.tsx`

<img width="563" alt="Screenshot 2023-04-29 at 6 30 38 PM" src="https://user-images.githubusercontent.com/49753983/235326730-60ca1865-dc2a-4721-a9ce-90503543d4f5.png">

<img width="629" alt="Screenshot 2023-04-29 at 6 34 46 PM" src="https://user-images.githubusercontent.com/49753983/235326861-e60aeaf8-98e8-4566-9967-87ecace9f512.png">

2023-05-06 13:09 UTC, hariombalhara commented on packages/features/settings/layouts/SettingsLayout.tsx
> +    if (tab.href === "/settings/my-account") {
Why are we using href. The name seems to be my_account only.
<img width="477" alt="Screenshot 2023-05-06 at 6 39 40 PM" src="https://user-images.githubusercontent.com/1780212/236626225-10d1bf9c-79b6-46b1-9984-a2c6d8775602.png">

2023-05-06 13:15 UTC, hariombalhara requested changes
The way I understand `session` provided by next-auth isn't aware of this change. But I just read that there is[`update`](https://next-auth.js.org/getting-started/client#updating-the-session) method available that if called will take a refresh from the server.

Maybe we can try calling the update method and see if it works. If it does, then wherever session is used the problem would be automatically solved.

2023-05-19 23:45 UTC, alannnc commented
Used some changes from here to mix with #8570

2023-05-19 23:45 UTC, closed without merging