fixes #8534 : :Add i18-next for this "Please reschedule."
calcom/cal.com pull request #8580
Opened 2023-04-30 13:13 UTC by kuluruvineeth

## What does this PR do?

- Added i18-next for this "Please reschedule."
- Before: cancellationReason: `Please reschedule. ${cancellationReason}`
- After: cancellationReason: t('Please reschedule.') + " " + cancellationReason

Fixes #8534

**Environment**: Production

2023-05-02 13:13 UTC, hariombalhara requested changes
Thanks for the contribution @kuluruvineeth 🙏
But we shouldn't concatenate translated strings
<img width="881" alt="Screenshot 2023-05-02 at 6 40 40 PM" src="https://user-images.githubusercontent.com/1780212/235675975-3246eb0f-8134-4291-ace4-fbe08cd3912d.png">

We should instead use complete string with variable  `Please reschedule. {{cancellationReason}}`

See e.g. https://github.com/calcom/cal.com/blob/f060e8e543edb78606284b2129ec4ca6f304ec30/apps/web/public/static/locales/en/common.json#L34

Also, I think you translated it in al the languages yourself. You don't need to do this. We use crowdin to do the translation.

2023-05-02 14:33 UTC, kuluruvineeth commented
> Thanks for the contribution @kuluruvineeth 🙏 But we shouldn't concatenate translated strings <img alt="Screenshot 2023-05-02 at 6 40 40 PM" width="881" src="https://user-images.githubusercontent.com/1780212/235675975-3246eb0f-8134-4291-ace4-fbe08cd3912d.png">
> 
> We should instead use complete string with variable `Please reschedule. {{cancellationReason}}`
> 
> See e.g.
> 
> https://github.com/calcom/cal.com/blob/f060e8e543edb78606284b2129ec4ca6f304ec30/apps/web/public/static/locales/en/common.json#L34
> 
> Also, I think you translated it in al the languages yourself. You don't need to do this. We use crowdin to do the translation.

@hariombalhara thank you reviewing and suggesting changes, i have made the changes as recommended by passing variable to translated string and added only in en file. Please review and let me know if still any changes are to be made, thanks.

2023-05-10 08:27 UTC, emrysal requested changes
Consistency on the underscoring of keys :pray

2023-05-10 08:27 UTC, emrysal commented on packages/trpc/server/routers/viewer/bookings/requestReschedule.handler.ts
> +      cancellationReason: t("Please reschedule.", { cancellationReasonMessage: cancellationReason })
```suggestion
      cancellationReason: t("request_reschedule_prompt", { cancellationReasonMessage: cancellationReason })
```

2023-05-10 08:27 UTC, emrysal commented on apps/web/public/static/locales/en/common.json
> +  "Please reschedule.": "Please reschedule. {{cancellationReasonMessage}}"
```suggestion
  "request_reschedule_prompt": "Please reschedule. {{cancellationReasonMessage}}"
```

2023-05-11 01:16 UTC, kuluruvineeth commented
> Consistency on the underscoring of keys 🙏

@emrysal Thanks for reviewing it. I have renamed to the format of underscoring keys to maintain consistency as suggested. Thanks.

2023-05-12 00:03 UTC, joeauyeung commented
I'm closing this for now, as the cancellation reason is already included in the email that is sent.

<img width="659" alt="image" src="https://github.com/calcom/cal.com/assets/65426560/82aeabd3-7d1c-480b-bf3c-2f7c4f29f2d8">

2023-05-12 00:03 UTC, closed without merging