[CAL-499] Choosing the email you want to be displayed as the organizer
calcom/cal.com pull request #8672
Opened 2023-05-04 14:29 UTC by gitstart-calcom

## What does this PR do?

Fixes #5774 

## Demo
https://user-images.githubusercontent.com/26940294/235652368-b7aa8d43-0570-4b18-b731-03546e0b627b.mov

2023-05-04 22:58 UTC, agustif commented
>  If you could please direct us to the right component it would save us some time. Thank you! cc: Omar López Ciarán Hanrahan


Hey there, not sure about if this is the correct answer here but did you check on the email templates?
https://github.com/calcom/cal.com/tree/main/packages/emails/templates

Also checkout CalendarManager where the primary email is passed.

https://github.com/calcom/cal.com/blob/05b42c001f997604cc55e4789ccaaf052cfca434/packages/core/CalendarManager.ts#LL84C1-L84C1

2023-05-10 23:33 UTC, joeauyeung commented
@gitstart-calcom the video in your PR description isn't working. Can you reupload it or maybe use Loom?

2023-05-11 06:18 UTC, gitstart-calcom commented
> @gitstart-calcom the video in your PR description isn't working. Can you reupload it or maybe use Loom?

Sure, we will add a new demo video

2023-05-11 09:50 UTC, gitstart-calcom commented
@joeauyeung The demo video has been updated now
https://www.loom.com/share/06ee5751444c4c53a8ff43bcc2b1cd8c

2023-05-11 22:31 UTC, joeauyeung reviewed
Some feedback
- The user should be able to choose which email is displayed on the confirmation page. I noticed in the PR it comes from the calendar. I would review the desired outcomes of #5774 
- On the success page, we should show the email immediately. Could we store the email the user wants to display in the event type DB record?

2023-05-24 14:57 UTC, gitstart-calcom commented
Apologies for the delay on the change request. We were trying to tackle some edge cases and got to the following conclusion:

We have tried 2 approaches trying to avoid modifying the db:
- For the booking success page, we tried fetching the destination calendar alongside the booking data. But to retrieve the corresponding calendar email would take a lot of computation. Taking how it is done in CalendarManager.ts in getCalendarCredentials and getConnectedCalendars functions.
- Another option was to make trpc calls within the React function to get the connected calendars and then retrieve the primary (organizer) email from it. An issue with this is that the organizer email won't show on the page load, so we would have to show a loader first (we got [feedback](https://github.com/calcom/cal.com/pull/8672#pullrequestreview-1423532947) to remove it). Another issue is that we would still make this API call in all the files where we need the correct organizer email.

So, storing the email the user wants to show in the eventType db record may be a better approach. We would like to confirm this approach before we go ahead.

2023-05-30 11:43 UTC, joeauyeung commented
> Apologies for the delay on the change request. We were trying to tackle some edge cases and got to the following conclusion:
> 
> We have tried 2 approaches trying to avoid modifying the db:
> 
>     * For the booking success page, we tried fetching the destination calendar alongside the booking data. But to retrieve the corresponding calendar email would take a lot of computation. Taking how it is done in CalendarManager.ts in getCalendarCredentials and getConnectedCalendars functions.
> 
>     * Another option was to make trpc calls within the React function to get the connected calendars and then retrieve the primary (organizer) email from it. An issue with this is that the organizer email won't show on the page load, so we would have to show a loader first (we got [feedback](https://github.com/calcom/cal.com/pull/8672#pullrequestreview-1423532947) to remove it). Another issue is that we would still make this API call in all the files where we need the correct organizer email.
> 
> 
> So, storing the email the user wants to show in the eventType db record may be a better approach. We would like to confirm this approach before we go ahead.

Thanks for looking into it. I think we can store which email the user wants to be displayed under the event type metadata. Although if a user does not choose to change the displayed email for that event type then default to the email on their profile.

2023-05-30 16:13 UTC, gitstart-calcom commented
> Thanks for looking into it. I think we can store which email the user wants to be displayed under the event type metadata. Although if a user does not choose to change the displayed email for that event type then default to the email on their profile.

Thank you, we will make the changes and get back to you soon

2023-06-08 08:44 UTC, gitstart-calcom commented
Hi @joeauyeung, we have updated the PR. Please take a look.

2023-07-03 06:07 UTC, PeerRich commented
![image](https://github.com/calcom/cal.com/assets/8019099/d61f542e-1990-4798-8529-7876fe985f7c)

why do we have a skeleton here?

2023-07-06 17:28 UTC, CarinaWolli commented
> Hi @joeauyeung, we have updated the PR. Please take a look.

@joeauyeung could you take a look at this one again?

2023-07-11 23:27 UTC, joeauyeung commented on apps/web/pages/event-types/[type]/index.tsx
> +                .find((cal) => cal?.externalId === input.destinationCalendar.externalId);
When no destination calendar is selected and we use the default calendar `input.destinationCalendar` is set to null. We should fall back to the destination calendar email.

2023-07-11 23:59 UTC, joeauyeung requested changes
Great job saving the emails to the event type metadata. Two things I think should be addressed:

- See my comment about saving an event type with the default destination calendar
- If a user changes their default destination calendar, we need to handle if we have to change the email of any event types that are using the default

2023-07-24 21:24 UTC, gitstart-calcom commented
Hi @joeauyeung, we moved this PR for this other [PR](https://github.com/calcom/cal.com/pull/10348), please take a look, we made the requested changes 😄

2023-08-09 23:52 UTC, CarinaWolli commented
This can be closed as PR #10348 has the most recent changes

2023-08-09 23:52 UTC, closed without merging