Kanakpandit17/search bar
calcom/cal.com pull request #8695
Opened 2023-05-05 10:36 UTC by kanakpandit17

## What does this PR do?
The search bar is made properly visible on the top right corner of the webpage. Also, it has placeholder so that users can understand the purpose of the search bar. The focus-ring is fully visible on clicking.

Solved issue #8693

Type of change: UI Improvement

2023-05-05 14:55 UTC, CarinaWolli commented
@Jaibles do we want to make changed to the search bar? That's how the changes of this PR look: 
<img width="1237" alt="Screenshot 2023-05-05 at 15 53 11" src="https://user-images.githubusercontent.com/30310907/236492910-aa0ead35-89e4-444d-be83-2c7960b487e9.png">

2023-05-05 14:58 UTC, sean-brydon approved these changes
Tested and happy with this :) Thanks @kanakpandit17

2023-05-05 21:34 UTC, PeerRich commented
![CleanShot 2023-05-05 at 22 33 50@2x](https://user-images.githubusercontent.com/8019099/236572528-330e6888-d8ae-4b4d-965d-07d51606c3df.jpg)
the margin-right looks odd

2023-05-05 21:34 UTC, PeerRich requested changes
![CleanShot 2023-05-05 at 22 33 50@2x](https://user-images.githubusercontent.com/8019099/236572606-ea0ffab4-1a39-45b2-ab2a-2cdbfacddeaa.jpg)
the margin right looks odd

2023-05-05 21:34 UTC, PeerRich commented on apps/web/pages/apps/index.tsx
> +      placeholder="Search App Name"
we need i18n strings here

2023-05-05 21:34 UTC, PeerRich commented on apps/web/pages/apps/index.tsx
> +    className="bg-subtle !border-muted !pl-15 pr-6 focus:!ring-offset-0 md:w-96"
there is a prettier issue here

2023-05-06 11:56 UTC, kanakpandit17 commented
will make the required changes

2023-05-08 13:14 UTC, CarinaWolli commented
@kanakpandit17 we should make the search bar wide enough to show the whole text, right now the text is cut off:
<img width="269" alt="Screenshot 2023-05-08 at 15 13 30" src="https://user-images.githubusercontent.com/30310907/236833522-869a6b81-1460-489e-8081-a299a871ba33.png">

2023-05-08 13:47 UTC, Jaibles commented
> @Jaibles do we want to make changed to the search bar? That's how the changes of this PR look: <img alt="Screenshot 2023-05-05 at 15 53 11" width="1237" src="https://user-images.githubusercontent.com/30310907/236492910-aa0ead35-89e4-444d-be83-2c7960b487e9.png">

This above is far too big imo. We can't solve every visibility problem by making everything in the app bigger. @kanakpandit17 I'd be happy with any width between `190px` (current width in live) and `220px` (width in Figma) but not bigger. Given that most searches are short and results are instant there's enough space to type and you're likely to see what you need in a few key strokes.

If we want placeholder we can just use "Search..."
<img width="1145" alt="CleanShot 2023-05-08 at 14 41 03@2x" src="https://user-images.githubusercontent.com/4536123/236839873-15110050-ca20-482f-aa55-367788510314.png">
.

2023-05-08 14:17 UTC, kanakpandit17 commented
> This above is far too big IMO and the text is too far away from the magnify icon (it should only be an 8px gap). @kanakpandit17 I'd be happy with any width between `190px` (current width in live) and `220px` ([width in Figma](https://www.figma.com/file/xk4HOxtSI82J0F7enMxeak/Cal---Live?node-id=26%3A53096&t=dygkprGcVLgpfZib-1)) but not bigger. Given that most searches are short and results are instant there's enough space to type and you're likely to see what you need in a few key strokes. We can't solve every visibility problem by making everything in the app bigger. The search already has a prominent position and we have an app-wide search in the top of the sidebar and accessible through k-bar.

Actually text is completely visible in my search bar, will check out

2023-05-08 22:25 UTC, Jaibles commented
@kanakpandit17 Any if this issue on mobile is fixed in your pr?

https://user-images.githubusercontent.com/4536123/236951037-8789b61f-cbe6-4780-b09d-5bce9ab89193.MOV

2023-05-10 09:16 UTC, Udit-takkar reviewed
@kanakpandit17 this issue has been fixed by some other contributor. you can check at latest main branch

<img width="1440" alt="Screenshot 2023-05-10 at 2 44 53 PM" src="https://github.com/calcom/cal.com/assets/53316345/9e92cdae-aa9e-4bb6-8035-8eb8819661ce">
<img width="814" alt="Screenshot 2023-05-10 at 2 45 16 PM" src="https://github.com/calcom/cal.com/assets/53316345/d6e72af6-de21-4ead-8729-5227c88b99c7">

2023-05-10 10:12 UTC, CarinaWolli commented
As @Udit-takkar mentioned, a fix for this already been merged to main (https://github.com/calcom/cal.com/pull/8741)

2023-05-10 10:12 UTC, closed without merging