feature/#7299/add paid webhook
calcom/cal.com pull request #8721
Opened 2023-05-06 07:05 UTC by ologbonowiwi

- feat: add BOOKING_PAID on enums
- feat: trigger the BOOKING_PAID webhook

## What does this PR do?

Adds the BOOKING_PAID webhook from #7299 

## Type of change

- New feature (non-breaking change which adds functionality)
- This change requires a documentation update

## How should this be tested?

- [ ] We need to ensure that the webhook is really being triggered when the charge of the payment occurs

## Checklist

- I haven't checked if my PR needs changes to the documentation
- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

2023-05-08 12:37 UTC, alishaz-polymath requested changes
Two major things:
1. It's missing a migration. There's change in the DB (prisma/schema.prisma) so it needs to have a migration as well, and please ensure that the migration doesn't destroy the existing webhooks.
2. Ideally we'd want to have as little migrations as possible, so please add the `BOOKING_REQUESTED` and `BOOKING_REJECTED` in the same migration, hence the respective change in `constants.ts` and `schema.prisma`. 
We can have them function with a follow up PR, but we definitely want them in the DB in one go, to minimize subsequent migrations
Thanks for the PR 🙌

2023-05-13 23:50 UTC, ologbonowiwi commented
`BOOKING_REQUESTED` and `BOOKING_REJECTED` were added.

How do I generate the migration to create this stuff on the database?

2023-05-13 23:55 UTC, ologbonowiwi commented
All webhooks added.

Can you review it again, @alishaz-polymath?

2023-05-30 18:57 UTC, alishaz-polymath requested changes
Please make sure to accommodate changes made in the PR #8884 so as to not repeat the same modifications and duplicate them. 🙏

2023-05-30 18:57 UTC, alishaz-polymath commented on packages/features/webhooks/lib/constants.ts
> +    WebhookTriggerEvents.BOOKING_REQUESTED,
```suggestion

```

2023-05-30 18:57 UTC, alishaz-polymath commented on packages/prisma/schema.prisma
> +  BOOKING_REQUESTED
```suggestion

```

2023-05-30 18:57 UTC, alishaz-polymath commented on packages/prisma/migrations/20230513235419_add_booking_webhooks/migration.sql
> +ALTER TYPE "WebhookTriggerEvents" ADD VALUE 'BOOKING_REQUESTED';
```suggestion

```

2023-05-31 01:48 UTC, ologbonowiwi commented
Changes applied, thanks @alishaz-polymath

2023-06-01 20:48 UTC, zomars approved these changes
![LGTM](https://media3.giphy.com/media/NytMLKyiaIh6VH9SPm/200.gif)

2023-06-09 21:18 UTC, ologbonowiwi commented
this will be merged?

changes already had been addressed @PeerRich @alishaz-polymath @zomars

2023-06-09 21:32 UTC, alishaz-polymath approved these changes
Let's go! 🚀 
Thanks a lot for your contribution 🙏

2023-06-13 15:10 UTC, merged