fix: strip markdown from meta description tag in users page
calcom/cal.com pull request #8769
Opened 2023-05-09 08:56 UTC by G3root

## What does this PR do?

remove markdown from description meta tags in user page and also closes  #8745

Fixes 

- Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

1. add a markdown content to your bio
2. go to your public profile page
3. check the description html meta tag, markdown should be stripped

2023-05-09 08:57 UTC, G3root commented on apps/web/pages/api/social/og/image.tsx
> -      const title_ = md.render(title).replace(/(<([^>]+)>)/gi, "");
we don't need this as we are stripping the markdown content in the user's public profile page

2023-05-10 07:11 UTC, JeroenReumkens commented
Hey @G3root, 

Using remark for this seems like a very big dependency. Even though this runs on the server, it will still load this big dependency on the server and slow things down unnecessary. Are there any other options that could work as well without adding a big dependency? Perhaps https://github.com/stiang/remove-markdown will work already? Or maybe a simple regex would be sufficient since there's only a few markdown chars we can add? 

On top of that I'd suggest adding this as a util to the lib package, similar to `markdownToSafeHTML`, this way we can reuse the `markdownToPlainText` utility easily and prevent other people from making their own solution. 

Thanks 🫶

2023-05-10 07:12 UTC, JeroenReumkens requested changes
See other comment.

2023-05-11 04:52 UTC, G3root commented
@JeroenReumkens pushed some changes replacing remark

2023-05-11 15:46 UTC, JeroenReumkens commented
Looks great to me @G3root 
Could you also please merge main in and add this to the new booker's meta when #8697 is auto-merged? After that I'm ready to approve 🙏

2023-05-11 17:27 UTC, G3root commented
@JeroenReumkens new bookers meta won't need this right ?

2023-05-15 07:35 UTC, JeroenReumkens approved these changes
LGTM, see other comments <3

2023-05-15 08:07 UTC, merged