CAL-1623 CAL-1620: Improve animation for booker, and push mini calendar down in fullscreen views
calcom/cal.com pull request #8773
Opened 2023-05-09 09:26 UTC by JeroenReumkens

## What does this PR do?

* Adds height animation for new booker
* moves animation to custom hook using `useAnimate` to clean up booker code a bit
* Push mini calendar down in fullscreen views

Fixes CAL-1623 CAL-1620

https://user-images.githubusercontent.com/2969573/237053861-14ce35b7-72d1-4f1c-b0cf-02577adbe6a4.mp4

**Environment**: Staging(main branch)

## Type of change

- New feature (non-breaking change which adds functionality)

## How should this be tested?

- [ ] Test the 3 booker layouts as well as mobile, verify that layouts + animations look good.

2023-05-09 09:27 UTC, JeroenReumkens commented on packages/features/bookings/Booker/Booker.tsx
> -            "bg-muted grid max-w-full auto-rows-max items-start overflow-clip dark:[color-scheme:dark] md:flex-row",
Was able to remove quite a few of these default classes by moving the animation logic to the new hook down below <3

2023-05-09 09:28 UTC, JeroenReumkens commented on packages/features/bookings/Booker/config.ts
> +      width: "calc(var(--booker-meta-width) + var(--booker-main-width) + var(--booker-timeslots-width))",
Keeping maxwidth in instead of width would make awkward fullscreen layout animations. using width instead of maxwidth improves it a lot.

2023-05-09 09:28 UTC, JeroenReumkens commented on packages/features/bookings/Booker/config.ts
> +  const [animationScope, animate] = useAnimate();
This uses the fairly new hook `useAnimate` from framer motion. That gives us an animate function which we can use to run animations.

2023-05-09 09:30 UTC, JeroenReumkens commented on packages/features/bookings/Booker/Booker.tsx
> +            <StickyOnDesktop key="meta" className="relative z-10 flex min-h-full">
This line and the following lines help with pushing the calendar down in fullscreen view.

2023-05-09 09:32 UTC, sean-brydon commented on packages/features/bookings/Booker/config.ts
> +      animate(animationScope.current, nonAnimatedProperties, {
👨‍🍳 💋

2023-05-09 09:33 UTC, sean-brydon commented on yarn.lock
Lets restore this 

`git checkout origin/main -- yarn.lock`

2023-05-09 09:34 UTC, sean-brydon requested changes
Code LGTM - new animations is beautiful

Requesting changes to remove `yarn.lock`

2023-05-09 09:34 UTC, sean-brydon requested changes
Code LGTM - new animations is beautiful

Requesting changes to remove `yarn.lock`

2023-05-09 09:36 UTC, JeroenReumkens commented on yarn.lock
I did actually update framer motion, so the lock update is partially right. The downgrading of some packages isn't though. Just asked around in threads why this could be happening. Will update soon.

2023-05-10 08:05 UTC, sean-brydon approved these changes
LGTM - 🚢 it

2023-05-10 08:56 UTC, merged