[CAL-1543] Fix the footer in modals
calcom/cal.com pull request #8940
Opened 2023-05-17 07:17 UTC by gitstart-calcom

Fixes #8414 

## Demo
https://www.loom.com/share/8dfc0ffddf5844b6b60dd37e6c7bc09c

2023-05-17 09:05 UTC, CarinaWolli commented
I think we want to add that new way of scrolling for all our modals. So we should make the changes to our Dialog component. (tagging @sean-brydon as part of the UI team)

2023-05-17 11:30 UTC, sean-brydon commented
> 



> think we want to add that new way of scrolling for all our modals. So we should make the changes to our Dialog component. (tagging @sean-brydon as part of the UI team)

Yeah we do - ideally a way of showing a clip mask when the content over flows. 

I'm happy for that to be picked up in a seperate PR for it tho. I will create a new issue

2023-05-17 13:54 UTC, sean-brydon approved these changes
Looks fine to me - @Jaibles see any issues?

2023-05-17 14:08 UTC, Jaibles commented
Looks good. Two small things:

1. Does it look like the content is being chopped off in the wrong spot? It should run all the way to the divider.

![CleanShot 2023-05-17 at 15 06 28@2x](https://github.com/calcom/cal.com/assets/4536123/f487e936-cfc8-49ff-a1f9-55dd30fa4833)

2. Can we reduce the padding above/below the buttons?

<img width="634" alt="CleanShot 2023-05-17 at 15 07 32@2x" src="https://github.com/calcom/cal.com/assets/4536123/4142bb22-40f0-48fb-9a57-469d69907d1a">

2023-05-17 16:42 UTC, gitstart-calcom commented
> Looks good. Two small things:
> 
> 1. Does it look like the content is being chopped off in the wrong spot? It should run all the way to the divider.
> 
> ![CleanShot 2023-05-17 at 15 06 28@2x](https://user-images.githubusercontent.com/4536123/238976580-f487e936-cfc8-49ff-a1f9-55dd30fa4833.png)
> 
> 2. Can we reduce the padding above/below the buttons?
> 
> <img alt="CleanShot 2023-05-17 at 15 07 32@2x" width="634" src="https://user-images.githubusercontent.com/4536123/238976738-4142bb22-40f0-48fb-9a57-469d69907d1a.png">

Sure, we are on it

2023-05-20 05:00 UTC, gitstart-calcom commented
Hi @Jaibles, we have implemented the requested changes. Please take a look
https://www.loom.com/share/61ccc1910f674707a8ed86aca2204513

2023-05-20 08:17 UTC, Jaibles commented
> Hi @Jaibles, we have implemented the requested changes. Please take a look
> 
> https://www.loom.com/share/61ccc1910f674707a8ed86aca2204513

Absolutely perfect. Appreciate the loom with the inspect :)

2023-05-22 06:21 UTC, CarinaWolli requested changes, later dismissed

2023-05-22 06:21 UTC, CarinaWolli commented on packages/ui/components/dialog/Dialog.tsx
> +              <div className="flex max-h-[95vh] flex-col">{children}</div>
This breaks the design of other modals. I tested the Test Preview in Routing Forms and when scrolling down the margin below the buttons is gone 

<img width="706" alt="Screenshot 2023-05-22 at 08 18 07" src="https://github.com/calcom/cal.com/assets/30310907/d32e4187-4d8c-4802-94f6-6d23b64a8502">

Should be: 
<img width="626" alt="Screenshot 2023-05-22 at 08 19 46" src="https://github.com/calcom/cal.com/assets/30310907/721a26eb-938b-4068-b1ca-4f63cc858849">

2023-05-23 13:07 UTC, gitstart-calcom commented
Hi @CarinaWolli, we have made the required changes, please take a look
https://www.loom.com/share/a82dc95a00e64f5092eeef9eda31559f

2023-05-26 07:44 UTC, CarinaWolli approved these changes

2023-05-30 16:26 UTC, merged