remove isPro check
calcom/cal.com pull request #8967
Opened 2023-05-18 09:06 UTC by rkreddy99

## What does this PR do?

Fixes #8963 

Remove isProOnly props from the code as every account is pro now.

Loom Video: https://www.loom.com/share/0aefcffa2a1e440c9f36a5bef719f7f7
This video shows that after removal of the isPro props, the user can still add apps 

**Environment**: Production

## Type of change

- Chore (refactoring code, technical debt, workflow improvements)

## How should this be tested?

- [ ] User should be able to add apps from app store

## Checklist

- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

2023-05-18 23:41 UTC, joeauyeung requested changes, later dismissed
Tested with Routing Forms app
- Installed from App Store page
- Installed from Routing Forms app page

Everything works but left a comment about the `yarn.lock` file

2023-05-18 23:41 UTC, joeauyeung commented on yarn.lock
This should be changed. Can you checkout the `yarn.lock` file from `main` to revert these changes?

2023-05-19 02:54 UTC, rkreddy99 commented on yarn.lock
done, checkedout lock file from main

2023-05-19 05:36 UTC, hariombalhara commented on apps/web/public/static/locales/ar/common.json
> +  "new_workflow_subtitle": "سير عمل جديد لـ...",
Why is this change here?

2023-05-19 05:37 UTC, hariombalhara commented on packages/app-store/ping/api/_getAdd.ts
> +  return { url: getInstalledAppPath({ variant: appConfig.variant, slug: "ping" }) };
Same here. I think this belongs to another branch.

2023-05-19 05:43 UTC, hariombalhara requested changes
Looks good except for some unrelated changes in the PR.

2023-05-19 05:58 UTC, rkreddy99 reviewed
remove unnecessary changes

2023-05-23 06:08 UTC, hariombalhara commented
@rkreddy99 Can you please resolve the conflicts once and then I would merge.

2023-05-23 06:21 UTC, hariombalhara approved these changes
LGTM now !! Resolved the conflicts as they were from my PR.

2023-05-23 07:32 UTC, sean-brydon approved these changes
LGTM on a UI side

2023-05-23 07:32 UTC, sean-brydon approved these changes
LGTM on a UI side

2023-05-23 09:16 UTC, merged