dark icons fix
calcom/cal.com pull request #8975
Opened 2023-05-18 13:41 UTC by saurabbot

## What does this PR do?

in the /settings/admin/apps/conferencing the icons werent visible cuz of the dark mode.

Fixes # (issue)
<img width="1440" alt="Screenshot 2023-05-18 at 7 10 20 PM" src="https://github.com/calcom/cal.com/assets/64374511/c23ee735-c6d8-4cde-99cc-ccf5708249a8">

run the project after changes works fine
## Checklist

2023-05-19 05:44 UTC, hariombalhara commented on apps/web/components/AppListCard.tsx
> +import classNames from "@calcom/lib/classNames";
Prettier error in the file. Eslint should have fixed it automatically. May be your commit hooks and IDE isn't configured correctly.

2023-05-19 05:58 UTC, hariombalhara commented on apps/web/components/AppListCard.tsx
> +import classNames from "@calcom/lib/classNames";
Yeah. It's correct now.

2023-05-19 06:06 UTC, hariombalhara commented on apps/web/components/AppListCard.tsx
> +          <img
While I was testing, I discovered the same problem is here as well.
<img width="1281" alt="Screenshot 2023-05-19 at 11 31 02 AM" src="https://github.com/calcom/cal.com/assets/1780212/600808e9-1205-44fc-8845-3e19eb60610c">
<img width="696" alt="Screenshot 2023-05-19 at 11 35 20 AM" src="https://github.com/calcom/cal.com/assets/1780212/a7a82137-c9bc-40f3-9161-641f6788836e">

2023-05-19 06:08 UTC, hariombalhara requested changes
The approach is correct as it's the same we are following at other places.
But there are 2 more instances where we need to do the same.
I am also thinking that maybe we should make an Image component that takes care of -dark automatically(that should be done as a followup though)

2023-05-19 07:47 UTC, hariombalhara commented on apps/web/components/eventtype/EventSetupTab.tsx
> -                            !eventLocationType.iconUrl.startsWith("/app-store") &&
cc @G3root for review.

2023-07-26 00:51 UTC, emrysal commented
@hariombalhara please re-review; reopening as the comments look encouraging

2023-08-18 00:14 UTC, closed without merging