fix: fixed embed where floating button was hovering over modal on mobile
calcom/cal.com pull request #9004
Opened 2023-05-20 02:03 UTC by doug-andrade

## What does this PR do?

Keeps the embedded floating under the modal while the modal is open.

Fixes #8851 

https://www.loom.com/share/c3960f30740a4ff8babcb6ef3dce8215

**Environment**: Staging(main branch)

## Type of change

- Bug fix (non-breaking change which fixes an issue)

2023-05-22 10:00 UTC, hariombalhara requested changes
Left a comment

2023-05-22 23:01 UTC, PeerRich commented on packages/embeds/embed-core/src/FloatingButton/FloatingButtonHtml.ts
> +  return `<button class="z-[1000000] hidden fixed md:bottom-6 bottom-4 md:right-10 right-4 md:left-10 left-4 ${buttonClasses.join(
@doug-andrade can you take a look?

2023-05-22 23:01 UTC, PeerRich commented on packages/embeds/embed-core/src/FloatingButton/FloatingButtonHtml.ts
> +  return `<button class="z-[1000000] hidden fixed md:bottom-6 bottom-4 md:right-10 right-4 md:left-10 left-4 ${buttonClasses.join(
I think hiding when open is better

2023-05-23 16:00 UTC, doug-andrade commented on packages/embeds/embed-core/src/FloatingButton/FloatingButtonHtml.ts
> +  return `<button class="z-[1000000] hidden fixed md:bottom-6 bottom-4 md:right-10 right-4 md:left-10 left-4 ${buttonClasses.join(
@PeerRich 100% Honesty, I would need more time to learn the codebase/the github workflow before I'd feel confident taking that on. I'm going to close this PR for now and will reopen if I can figure that out.

2023-05-23 16:01 UTC, closed without merging