feat: toggleTheme
calcom/cal.com pull request #9076
Opened 2023-05-23 16:24 UTC by saurabbot

## What does this PR do?
This pr adds a feature which allows the user the app theme.
Implements #9047 

https://www.loom.com/share/c3f222b633954baeb6305ec61e3f133d

## How should this be tested?

- [x] Test A->changing the themes and checking the change in db
- [ ] Test B

2023-05-23 18:09 UTC, leog requested changes
Thanks for the contribution @firfox341. It does look good! Left some comments regarding code to be removed.

Also, what would be the rationale behind using a new column in the database versus the existing `theme` column?

2023-05-23 18:09 UTC, leog commented on apps/web/pages/settings/my-account/appearance.tsx
> +        console.log(values, "updatemutate");
This should be removed

2023-05-23 18:09 UTC, leog commented on packages/trpc/server/routers/loggedInViewer/updateProfile.handler.ts
> +  console.log(input, "updateinput");
This should be removed

2023-05-23 18:09 UTC, leog commented on packages/ui/components/form/inputs/Input.tsx
> +  console.log(form, "ww");
This should be removed

2023-05-23 19:22 UTC, leog commented
Makes sense @firfox341. I would like to invoke the presence of @Jaibles for this one. I'm not sure we want to maintain both variables at the same time; if you choose dark mode why would you like your booking page to be light mode or automatic? Just in case, his blessing is always a good thing to have 😄

2023-05-23 21:18 UTC, Jaibles commented
@leog  @saurabbot is the question: "Should we allow people to have different dark/light mode settings for app.cal.com vs their public booking page"? If so, the answer is definitely yes. 

I think a perfectly likely scenario is people who prefer dark mode wanting that in the app, but wanting to go with system settings for the public page so that their bookers get to see what they prefer.

2023-05-23 21:28 UTC, Jaibles commented
![Settings - My Account - Appearance](https://github.com/calcom/cal.com/assets/4536123/b5054e89-6521-4ffd-968e-6da0ba38e36e)

We do need to use the new svgs though. I haven't had a chance to optimise them yet in terms of filesize.

2023-05-23 23:09 UTC, zomars requested changes
Thank you for your contribution 🙏 Left some comments to be addressed before merging

2023-05-23 23:09 UTC, zomars commented on packages/prisma/.env
Why was this file deleted? Let's put it back:

`git checkout origin/main packages/prisma/.env`

2023-05-23 23:09 UTC, zomars commented on packages/ui/components/form/inputs/Input.tsx
> -
Unnecessary diff here. Let's revert it.

2023-05-23 23:09 UTC, zomars commented on apps/web/pages/settings/my-account/appearance.tsx
> +  console.log(user.appTheme, formMethods, "user");
```suggestion
```

2023-05-23 23:09 UTC, zomars commented on packages/features/settings/ThemeLabel.tsx
> -
Missing padding here

2023-05-25 06:48 UTC, Jaibles commented
> gtg right ? is the yarn.lock change fine ? could you guys merge these prs also #8975 #8925

@saurabbot I'm assuming the new svgs I made aren't in yet so that should be blocking. I'll prepare them now.

2023-06-12 17:57 UTC, Udit-takkar commented
@saurabbot any update on this PR?

2023-07-03 18:27 UTC, leog commented
> Hey @Udit-takkar this was done long back and ready from my side, I was waiting for you guys to test the feature.

Hey @saurabbot. Actually, we were waiting for you to resolve the comments we did in the code (addressed already) and request a re-review so it returns to us to review again to be able to approve it. Take that into account for future contributions, so we can merge great contributions like yours faster 👍

2023-07-10 18:15 UTC, leog commented
> @leog gtg i guess..

@firefox341 did you tested the latest? There is some problem with loading the svgs and when saving, the toast message does not look good. Please test it locally again and tackle those issues.

2023-08-09 17:37 UTC, leog commented
@saurabbot are you able to continue working on this PR? we might need to close it if there is no more activity in it 😓

2023-08-28 09:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/calcom/cal.com?pullRequest=9076) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/calcom/cal.com?pullRequest=9076) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: firefox292<br/>:x: saurabbot<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/calcom/cal.com?pullRequest=9076) it.</sub>

2023-09-23 22:58 UTC, closed without merging