chore: Update prisma to Prisma 3
calcom/cal.com pull request #909
Opened 2021-10-12 03:35 UTC by emrysal

Updates Prisma to 3.0.2 which is the latest version of Prisma that does not break for us. There seems to be a mayor issue introduced in 3.1.1 and up that causes many of our queries (erroniously, our queries are fine) to fail before making it to PostgreSQL. Significant strides on the investigation are already made.

2021-10-12 04:15 UTC, emrysal commented
@KATT This also makes our seed.ts script compatible with Prisma Seeding @ https://www.prisma.io/docs/guides/database/seed-database

2021-10-12 09:45 UTC, KATT reviewed
Questions

- Does the CI build break if we were to update to Prisma `3.1.1` - if not, it would be good if it does so no one accidentally upgrades it
- The seed script doesn't run on normal prisma migrations, right? We wouldn't want the seed to be in prod, ever

2021-10-12 09:45 UTC, KATT commented on package.json
> +    "seed": "ts-node --compiler-options {\"module\":\"CommonJS\"} ./prisma/seed.ts"
This is is already in the `ts-node` script above. Should be enough with 

```suggestion
    "seed": "ts-node ./prisma/seed.ts"
```

or possibly


```suggestion
    "seed": "yarn ts-node ./prisma/seed.ts"
```

2021-10-12 14:27 UTC, KATT requested changes
Missing migrations that prisma makes as part of the upgrade - try running `yarn db-migrate` locally or `yarn db-nuke && yarn dx` and you'll be prompted

This is what prisma does in that migration -- not thought if this is a good or bad thing yet. Personally, I like cascade deletes on non-critical data as it's easier to work with, but seems like we need to update [referential actions](https://www.prisma.io/docs/concepts/components/prisma-schema/relations/referential-actions) as part of this upgrade.

<details>

```sql
-- DropForeignKey
ALTER TABLE "EventTypeCustomInput" DROP CONSTRAINT "EventTypeCustomInput_eventTypeId_fkey";

-- DropForeignKey
ALTER TABLE "Membership" DROP CONSTRAINT "Membership_teamId_fkey";

-- DropForeignKey
ALTER TABLE "Membership" DROP CONSTRAINT "Membership_userId_fkey";

-- DropForeignKey
ALTER TABLE "Payment" DROP CONSTRAINT "Payment_bookingId_fkey";

-- DropForeignKey
ALTER TABLE "SelectedCalendar" DROP CONSTRAINT "SelectedCalendar_userId_fkey";

-- AddForeignKey
ALTER TABLE "Membership" ADD CONSTRAINT "Membership_teamId_fkey" FOREIGN KEY ("teamId") REFERENCES "Team"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Membership" ADD CONSTRAINT "Membership_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SelectedCalendar" ADD CONSTRAINT "SelectedCalendar_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EventTypeCustomInput" ADD CONSTRAINT "EventTypeCustomInput_eventTypeId_fkey" FOREIGN KEY ("eventTypeId") REFERENCES "EventType"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Payment" ADD CONSTRAINT "Payment_bookingId_fkey" FOREIGN KEY ("bookingId") REFERENCES "Booking"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- RenameIndex
ALTER INDEX "Booking.uid_unique" RENAME TO "Booking_uid_key";

-- RenameIndex
ALTER INDEX "EventType.userId_slug_unique" RENAME TO "EventType_userId_slug_key";

-- RenameIndex
ALTER INDEX "Payment.externalId_unique" RENAME TO "Payment_externalId_key";

-- RenameIndex
ALTER INDEX "Payment.uid_unique" RENAME TO "Payment_uid_key";

-- RenameIndex
ALTER INDEX "Team.slug_unique" RENAME TO "Team_slug_key";

-- RenameIndex
ALTER INDEX "VerificationRequest.identifier_token_unique" RENAME TO "VerificationRequest_identifier_token_key";

-- RenameIndex
ALTER INDEX "VerificationRequest.token_unique" RENAME TO "VerificationRequest_token_key";

-- RenameIndex
ALTER INDEX "Webhook.id_unique" RENAME TO "Webhook_id_key";

-- RenameIndex
ALTER INDEX "users.email_unique" RENAME TO "users_email_key";

-- RenameIndex
ALTER INDEX "users.username_unique" RENAME TO "users_username_key";

```
</details>

2021-10-12 14:27 UTC, KATT commented on .github/workflows/e2e.yml
> +      - run: yarn prisma migrate reset --force
I think this should be reverted?

2021-10-13 22:33 UTC, KATT commented
Converted this to draft so it's not accidentally merged

2021-11-17 17:35 UTC, mohammedzamakhan commented on package.json
> +    "prisma": "^3.3.0",
3.5.0 just got released!

2022-01-04 10:22 UTC, closed without merging