Disabled pinch to zoom on mobile devices#9155
calcom/cal.com pull request #9163
Opened 2023-05-28 11:37 UTC by Gohan-18

## What does this PR do?
Disables pinch to zoom in mobile devices

Fixes #9155  (issue)

**Environment**: Staging(main branch) / Production

## Type of change

#- Bug fix (non-breaking change which fixes an issue)
#- Chore (refactoring code, technical debt, workflow improvements)
- New feature (non-breaking change which adds functionality)
#- Breaking change (fix or feature that would cause existing functionality to not work as expected)
#- This change requires a documentation update

## How should this be tested?

- [ ] Test A
- [ ] Test B

## Checklist

- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't performed a self-review of my own code and corrected any misspellings
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my PR needs changes to the documentation
- I haven't checked if my changes generate no new warnings
- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

2023-05-29 11:29 UTC, sean-brydon commented
@PeerRich  what is the reason for this? Its generally recommended to avoid disabling pinch to zoom as its not the best thing to do for a11y.

2023-05-30 09:27 UTC, PeerRich commented
@sean-brydon zooming on mobile apps looks weird and breaks the pwa experience. i dont mind keeping it, just looks weird. visit the mobile page and pinch to zoom, looks odd

2023-06-02 16:59 UTC, sean-brydon approved these changes

2023-06-02 18:07 UTC, PeerRich requested changes
isnt 

`<meta name="viewport" 
      content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
`

better?

2023-06-02 19:02 UTC, Gohan-18 commented
> 

Yeah... That's good too. Let me just modify the code. Thanks.

2023-06-02 20:03 UTC, Gohan-18 commented
Hey @PeerRich , one small help. Couldn't actually locate the file where to add the tag that works throughout app. Tried in both the theme.config.js and index.html, but doesn't seems to work. Can you please just help in locating the file. Thanks.

2023-06-03 10:46 UTC, PeerRich commented
`<meta>` should be in  _document.tsx line 51

2023-06-03 11:46 UTC, Gohan-18 commented
> `<meta>` should be in _document.tsx line 51

Just updated. Thanks again for helping out

> `<meta>` should be in _document.tsx line 51

Just updated. Thanks again for being so patience and helpful.🙏

2023-06-06 09:59 UTC, PeerRich commented on apps/web/pages/_document.tsx
> +          <meta name="viewport"  content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"></meta>
```suggestion
          <meta name="viewport"  content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"/>
```

2023-06-06 09:59 UTC, PeerRich commented on apps/web/styles/globals.css
> +
```suggestion
```

2023-06-06 10:00 UTC, PeerRich approved these changes

2023-06-06 10:00 UTC, PeerRich approved these changes

2023-06-06 13:48 UTC, PeerRich commented on apps/web/pages/_document.tsx
> +          <meta name="viewport"  content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />
```suggestion
          <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />
```

2023-06-06 17:24 UTC, PeerRich commented on apps/web/pages/_document.tsx
> +          <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />
```suggestion
          <meta
            name="viewport"
            content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"
          />
```

2023-06-06 17:47 UTC, merged