fix: deleteTokenIfUsed
calcom/cal.com pull request #9213
Opened 2023-05-30 18:49 UTC by saurabbot

fixes

2023-07-07 08:03 UTC, sean-brydon reviewed
Great Job - Sorry for the late reply - I will make the changes that i mention so you dont have to come back to this PR <3 

thank you

2023-07-07 08:03 UTC, sean-brydon commented on apps/web/pages/signup.tsx
> +  });
I think this can be just delete 

token is unique in our DB so this should never be many

2023-07-07 08:32 UTC, sean-brydon requested changes
After some testing - we can't actually delete the token here as this is where it is read. 

we need this token on the backend to preform the signup. 

If you actually try and sign in with a team invite - the token never exists cause its always deleted.

2023-07-25 15:29 UTC, keithwillcode commented
This PR is being closed due to inactivity. Please reopen if work is intended to be continued.

2023-07-25 15:29 UTC, closed without merging