[CAL-493] Implements tRCP on event types
calcom/cal.com pull request #923
Opened 2021-10-12 20:34 UTC by zomars

- ~Extracts CreateFirstEventTypeView~
- ~Extracts CreateNewEventDialog~
- Implements tRCP for event types listing

2021-10-12 20:53 UTC, emrysal reviewed
Not many issues I can see, but I need to UI test to be able to approve; and I'm in debug mode on local at the mom so stuff's broken.

2021-10-12 21:09 UTC, zomars commented on lib/mutations/event-types/create-event-type.ts
> +  console.log(`response`, response);
Nice catch

2021-10-12 23:06 UTC, KATT requested changes
- Unnecessary "generic" components when they're only used in 1 place
  - I don't think we should functions stuff out of a file before they're used in several places
  - Long files and co-located >> logic split up over N files
  - Don't take my word for it - here's Dan Abramov
    - https://twitter.com/dan_abramov/status/1230841812115501056?lang=en
    - https://twitter.com/dan_abramov/status/1220029098543788032?lang=en
- A button called "Dialog" should not render a visible button
- A Dialog should not handle it's own state (and ideally only the `pages/X`-files deal with things like the URL-params so we don't get collisions later on)
- A component in `components/*` should probably never infer a type from the API - they should all be generic enough to just work without knowledge of API

2021-10-12 23:12 UTC, emrysal commented on pages/event-types/index.tsx
> +            <CreateNewEventDialog canAddEvents={query.data.canAddEvents} profiles={query.data.profiles} />
You're misunderstanding the Dialog component a little bit yeah - the way it is used here is variable-less. It is in fact a dialog but renders a trigger of that Dialog. When you click that button it triggers.

2021-10-12 23:32 UTC, KATT commented on pages/event-types/index.tsx
> +            <CreateNewEventDialog canAddEvents={query.data.canAddEvents} profiles={query.data.profiles} />
In their demo it's clear that it has a button as a trigger, in our case it's not. However, in our case, the state is controlled by a query param so we should not need to rely on `<DialogTrigger/>` (which I personally feel a bit iffy about as an API)

I.e. (mock code)

```ts

export default function MyPage() {
  const modal = useToggleQuery("new");

  return (
    <>
      {/* Button can be outside - it doesn't matter */}
      <Button href={modal.hrefOn}>Open modal</Button>
      {/* No need for trigger */}
      <Dialog
        open={modal.isOn}
        {/* We should probably add a `modal.setOn(boolean)` or something to get to replace below with `onOpenChange={modal.setOn}` */}
        onOpenChange={(state) => router.replace(state ? modal.hrefOff : modal.hrefOn)}>
        {/* ... */}
      </Dialog>
    </>
  );
}
```

2021-10-12 23:35 UTC, KATT commented on pages/event-types/index.tsx
> +            <CreateNewEventDialog canAddEvents={query.data.canAddEvents} profiles={query.data.profiles} />
Might very well be that I'm misunderstanding something with their modals in general though. And maybe we shouldn't have query param tracked / linkable modals at all.

2021-10-12 23:45 UTC, zomars commented on pages/event-types/index.tsx
> +            <CreateNewEventDialog canAddEvents={query.data.canAddEvents} profiles={query.data.profiles} />
Partially agreed. I don't have much an opinion on this. Just refactored the previous dialog.

2021-10-12 23:48 UTC, zomars commented on components/eventtype/CreateNewEventDialog.tsx
> +const CreateNewEventDialog = ({ profiles, canAddEvents }: { profiles: Profiles; canAddEvents: boolean }) => {
Agreed except in the vendoring thing. Another point in splitting in files is being able to dynamically load them in the future.

2021-10-12 23:49 UTC, zomars commented on components/eventtype/CreateNewEventDialog.tsx
> +        </Button>
Should we call it Action?

2021-10-13 01:18 UTC, KATT commented on components/eventtype/CreateNewEventDialog.tsx
> +        </Button>
It shouldn't contain the state of the button as explained somewhere else here so maybe the CTA could be something like

```tsx
CTA={(
  <>
    <Button ... />
   <Dialog open={modal.isOpen} />
  </>
)}

2021-10-13 03:47 UTC, zomars commented on components/eventtype/CreateNewEventDialog.tsx
> +const CreateNewEventDialog = ({ profiles, canAddEvents }: { profiles: Profiles; canAddEvents: boolean }) => {
I consider it prep-work for reducing the initial bundle size using dynamic imports

2021-10-13 07:57 UTC, KATT requested changes
> I've been working with React since 2015 so it's more than "a feeling", so trying to put words on my reasoning below. Obviously open for input and to be proven wrong.


## Why colocating code is often preferable over breaking it up into files


### Optimize for code deletability

- Once you remove `pages/X.jsx` and everything is vendored - you'll automatically delete all the dependencies without leaving any traces
- With our linting, you will prompted to delete unused code automatically
- Certainty that you _can_ delete code - deleting something in `components/X` is a lot scarier than `pages/X`

### Context switching 

When one wants to find what component is responsible for a specific thing in the UI - you usually start in the known entry point - in Next.js that is `pages/X.jsx` and navigate to the `export default` - then find the component you're looking for there

Once you then navigate (simple CMD+click) into the component you want to change you'll be faced with two different scenarios:

- **A)** The component is in the same file **and not exported** - you can safely *know* that the component is not re-used and you can modify it without further thinking 
- **B)** The component is `export`ed in a `components/X` directory
  - I now need to at *the minumum*  need to check all places that import this file which breaks my flow of what I'm doing
  - If the component *is reused* I have to consider all of those cases before I change it - changes that also need to be tested.


### "DRY" programming is overrated

Not strictly to do this as this is so far only used in 1 place - but trying to "over-share" code leads to very complicated logic where it's a lot easier to copy and tweak than to make reusable parts for everything. WET programming is easy for anyone to pick up and it'll make it a lot cheaper to delete code.

See scenario **B)** on *Context Switching* above


### To answer specific points

> You don't use cmd + P that often I guess. I expect components to live in their respective files for easy finding and navigation. That's the point of React componentization IMO. Files should be kept lean and modular.

No, I don't - I mainly navigate by reading and clicking.


As I pointed out, this has been brought up by React core team members. Below are quoted by Dan Abramov on Twitter:

- > [I still get surprised that “one function per file” is clearly unnecessary but “one component per file” is somehow a common practice!](https://twitter.com/dan_abramov/status/1220029098543788032) 
- > [“One component per file” 🤦‍♂️](https://twitter.com/dan_abramov/status/1230841812115501056?lang=en)



> Good feedback. Also I think we reached the point where abstraction is necessary
> 
> https://kentcdodds.com/blog/when-to-break-up-a-component-into-multiple-components

- 100% for something like a `<Dialog/>` that needs to look and feel consistent but not for something like a `CreateNewEventDialog` which is used once. It's the wrong abstraction - we need to look at the smaller parts - i.e. making a `<FormDialog/>` first
- This blog post is focused on breaking up into multiple _components_ - not multiple _files_
- He also quotes this: [_Duplication is far cheaper than the wrong abstraction. — Sandi Metz_](https://sandimetz.com/blog/2016/1/20/the-wrong-abstraction)
- And his ending point is: _So feel free to break up your components into smaller ones, but **don't be afraid of a growing component until you start experiencing real problems**. It's WAY easier to maintain it until it needs to be broken up than maintain a pre-mature abstraction. Good luck!_

## Possible other solutions

- There might be a way to keep components in the `pages/X`-folders without Next.js treating it as a Page - then context switching and the surrounding uncertainty would be reduced
- [Namespaces / Modules](https://www.typescriptlang.org/docs/handbook/namespaces-and-modules.html)
- Strict folder naming in `components/` to show that code is tied to a specific page. I.e. anything to do with `pages/event-types.tsx` would need to live in somewhere like `components/pages/event-types/MyComponent.tsx`
- Maybe there could be a linter to help us delete "stray" files in `components/` - but since we're [*not really*](https://github.com/calendso/calendso/pull/795) using TypeScript it will be hard to do this with certainty.

2021-10-14 11:00 UTC, PeerRich requested changes
merge conflicts

2021-10-14 14:37 UTC, zomars commented
Conflicts resolved @PeerRich

2021-10-14 14:38 UTC, zomars commented on components/eventtype/CreateNewEventDialog.tsx
> +        </Button>
I'll refactor in a following PR

2021-10-15 10:38 UTC, KATT approved these changes
I don't love the `viewer.eventType`-resolver but I think it's largely unchanged from the `getServerSideProps` so changes to that can be done as a follow-up

2021-10-15 10:38 UTC, KATT commented on components/pages/eventtypes/EventTypeList.tsx
> +  types: EventTypes[number]["eventTypes"];
Easier to read if you split up the logic a bit

```suggestion
type EventTypeGroup = inferQueryOutput<"viewer.eventTypes">["eventTypes"][number];
type EventType = EventTypeGroup["eventTypes"][number];
interface Props {
  profile: { slug: string | null };
  readOnly: boolean;
  types: EventType[];
}
```

Also when doing this you see that what you return on `<"viewer.eventTypes">["eventTypes"]` should probably be called `<"viewer.eventTypes">["eventTypeGroups"]`

2021-10-15 10:38 UTC, KATT commented on server/routers/viewer.tsx
> +        eventTypes: eventTypeGroups.filter((groupBy) => !!groupBy.eventTypes?.length),
```suggestion
eventTypeGroups: eventTypeGroups.filter((groupBy) => !!groupBy.eventTypes?.length),
```

2021-10-15 10:38 UTC, KATT commented on components/pages/eventtypes/EventTypeList.tsx
> +  types: EventTypes[number]["eventTypes"];
Also, to echo what I wrote earlier - this is clearly tied to the `viewer.eventTypes` so this component should be inlined in whatever file actually does the `viewer.eventTypes`-useQuery

2021-10-15 14:52 UTC, zomars commented on package.json
> +    "type-check": "tsc --pretty --noEmit",
Isn't causing harm does it? Just some prep work to have that script handy

2021-10-15 19:06 UTC, PeerRich approved these changes

2021-10-15 19:07 UTC, merged