feat: add workflow dropdown filter UI
calcom/cal.com pull request #9230
Opened 2023-05-31 09:49 UTC by Udit-takkar

## What does this PR do?

Fixes https://linear.app/calcom/issue/CAL-1803/org-workflows

**Environment**: Staging(main branch) / Production

## Type of change

- New feature (non-breaking change which adds functionality)

2023-05-31 11:39 UTC, Udit-takkar commented on packages/features/ee/workflows/components/WorkflowDropdownFilter.tsx
> +  const { data: teams } = trpc.viewer.teams.list.useQuery();
will change this query after sean's branch has been merged into feat/organizations

2023-06-07 09:31 UTC, CarinaWolli commented
Another issue got created for that: https://github.com/calcom/cal.com/issues/9361 I think designs also got slightly updated

2023-06-09 08:44 UTC, CarinaWolli requested changes
Are you working on the functionality of the filter as well? 

There is a 0 next to the dropdown:
<img width="160" alt="Screenshot 2023-06-09 at 10 39 21" src="https://github.com/calcom/cal.com/assets/30310907/f4659b6e-5b09-433f-bbfa-7cfd65a7abd6">

Checking boxes doesn't really work as it should:
- I can't uncheck a team, once checked 
- Team unchecks when checking 'Yours'
- Unchecking 'Yours' also unchecks teams

2023-06-09 10:50 UTC, Udit-takkar commented
@CarinaWolli  1) Yeah i am going to add the functionality of both event type filter and workflow filter in my next PR. This PR just adds UI. I will change title of dropdown when multiple options are selected like "Selected(2)" later after confirming with Ciaran.

2) Fixed the things you mentioned.  

https://github.com/calcom/cal.com/assets/53316345/ef0188c1-40dc-4f17-9040-63606c9b90e6

2023-06-09 14:41 UTC, Udit-takkar commented
closing in favour of https://github.com/calcom/cal.com/pull/9417/files#r1223039889. I will make the changes in  that branch

2023-06-09 14:41 UTC, closed without merging