init
calcom/cal.com pull request #9232
Opened 2023-05-31 11:15 UTC by saurabbot

Fixes #7223 

https://www.loom.com/share/bbfb22014537416fa979a46f96f2b4ea

2023-06-01 11:23 UTC, PeerRich commented on apps/web/components/dialog/EditLocationDialog.tsx
> +                console.log(details, "details");
```suggestion
```

2023-06-01 11:26 UTC, PeerRich commented
can you record a loom video selecting more locations?

2023-06-01 11:26 UTC, PeerRich requested changes
discussing with @Jaibles, not sure if we actually end up wanting to remove the dialog. sorry about this

2023-06-01 11:46 UTC, Jaibles commented
I'm still strongly in favour of this. @saurabbot can you record a loom that also shows what its like to just change the first location?

2023-06-01 12:28 UTC, PeerRich commented
@Jaibles there are other settings in the dialog too that we just cant skip:

![CleanShot 2023-06-01 at 13 27 37@2x](https://github.com/calcom/cal.com/assets/8019099/9947ce96-6b39-4318-b336-dad832832363)
![CleanShot 2023-06-01 at 13 27 51@2x](https://github.com/calcom/cal.com/assets/8019099/f9971ae9-a17b-49da-928c-abc667501539)
![CleanShot 2023-06-01 at 13 28 03@2x](https://github.com/calcom/cal.com/assets/8019099/5e9a78da-7c6d-402e-b9db-8fbbb7ef3953)
![CleanShot 2023-06-01 at 13 28 10@2x](https://github.com/calcom/cal.com/assets/8019099/d671b85b-a10a-43f4-9ed6-965d4dffa2d5)

2023-06-06 09:58 UTC, PeerRich commented
only thing missing, can we keep this string: 

"Can't find the right video apps? Visit our App Store" below the component?

2023-07-01 18:28 UTC, PeerRich commented
hey @saurabbot can you look into the merge conflict? will add a tip for it after merging!

2023-07-12 11:17 UTC, shivamklr reviewed
@saurabbot Kindly resolve the conflicts.

2023-07-25 15:44 UTC, closed without merging