Fix/password validation
calcom/cal.com pull request #9244
Opened 2023-05-31 13:26 UTC by piyushgarg-dev

## What does this PR do?
Added Password Validation in Signup

Fixes #9215

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How should this be tested?
- Go to https://app.cal.com/signup
- Try invalid password and you would see errors
- Correct password would let you signup

2023-05-31 17:04 UTC, sean-brydon requested changes
Great effort! lets use zod to keep consistent with the rest of our forms 

https://github.com/react-hook-form/resolvers#Zod

2023-05-31 20:26 UTC, Udit-takkar commented on apps/web/pages/404.tsx
> +                          <Slack strokeWidth="1.5" fill="currentColor" className="h-6 w-6 dark:text-white" />
I think you made this change in one of your earlier PR. This is not required here

2023-05-31 20:27 UTC, Udit-takkar reviewed
@piyushgarg-dev remove yarn.lock file

2023-06-01 07:13 UTC, piyushgarg-dev commented on apps/web/pages/signup.tsx
> +                    })}
Hi @sean-brydon, I borrowed this code from the ChangePassword component. Their plain react-hook-forms's built-in validation was used. Check https://github.com/calcom/cal.com/blob/c610fad11ee1060976721970f7c63f05409327b5/apps/web/pages/settings/security/password.tsx#L145

Are you sure to change this to use zod?

Thanks

2023-06-01 08:19 UTC, piyushgarg-dev commented on apps/web/pages/signup.tsx
> +                    })}
Pushed at https://github.com/calcom/cal.com/pull/9244/commits/b34147b3b3471ed18c7e96e707845244867c0556

2023-06-01 14:00 UTC, piyushgarg-dev commented on apps/web/pages/signup.tsx
> +  });
I am not able to search for `AppPasswordField` anywhere in the code. Did you mean `PasswordField` being used at 3 places?

2023-06-02 04:18 UTC, hariombalhara commented on apps/web/pages/signup.tsx
> +  });
I actually meant that if we create AppPasswordField it can be used at 3 places.

2023-07-07 00:20 UTC, closed without merging