Fix: Credential of type video wrong id on bookingReference
calcom/cal.com pull request #9281
Opened 2023-06-01 23:13 UTC by alannnc

## What does this PR do?

- Fixes wrong credentialId being saved for bookingReferences, it was always saving credential of type calendar.

Fixes #6739 #8831

**Environment**: Staging(main branch) / Production

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- [ ] Create an event with location zoom
- [ ] Create a booking for said event
- [ ] Cancel that booking and take look in zoom app if booking was deleted

## Checklist

- I haven't added tests that prove my fix is effective or that my feature works

2023-06-01 23:16 UTC, alannnc commented on packages/core/EventManager.ts
> +        credentialId: result.credentialId ?? evt.destinationCalendar?.credentialId,
The thing here it was saving calendar Credential ID, when there are some cases that video references need their right value.

2023-06-02 21:37 UTC, zomars approved these changes, later dismissed

2023-06-12 16:52 UTC, keithwillcode requested changes, later dismissed
There are E2E tests failing. Can you please take a look?

2023-07-03 00:16 UTC, alannnc commented on packages/app-store/dailyvideo/lib/VideoApiAdapter.ts
> +  userId: 0,
Sometimes credentialId or userId should be saved to DB, but prisma will error if tries to save said values. I think we are better off using 0.
@zomars

2023-07-06 21:28 UTC, zomars approved these changes
Tested and working! Nice job @alannnc 🙏🏽 

![Ship it](https://media.giphy.com/media/CEIHJK4ympvVe0fAdU/giphy.gif)

2023-07-06 21:39 UTC, merged