test : Can add google calendar e2e test
calcom/cal.com pull request #9472
Opened 2023-06-12 17:49 UTC by Ninad3721

## What does this PR do?

This PR adds e2e test to check if google calendar can be added  after getting installed
Fixes # (issue)
https://github.com/calcom/cal.com/issues/9371

## Type of change

- New feature (non-breaking change which adds functionality)

## How should this be tested?

npx playwright test google-calendar

## Mandatory Tasks
- [ ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

2023-06-13 12:14 UTC, Udit-takkar reviewed
- I have pushed the changes after applying prettier formatting to the code, as the lint was failing due to the formatting issue.

- I am not able to run npx playwright test google-calendar even though i have installed @playwright/test.

<img width="777" alt="Screenshot 2023-06-13 at 5 42 53 PM" src="https://github.com/calcom/cal.com/assets/53316345/50f00241-590b-4404-a181-2a5826d86784">

2023-06-14 04:46 UTC, Ninad3721 commented
@Udit-takkar is it problem with this test only or all the test are not working ? Let me run it again on my pc qnd update you.

2023-06-14 12:47 UTC, Ninad3721 commented
@Udit-takkar I was able to run test , I think it is problem specific to your system.

2023-07-01 18:38 UTC, PeerRich commented
@Ninad3721 can you address the lint issues?

2023-07-03 06:37 UTC, Ninad3721 commented
> @Ninad3721 can you address the lint issues?
I always lint code before pushing it but still get this error every time , No problem I will lint it again and try to edit the PR. Thank your for pointing out.

2023-07-13 12:29 UTC, hariombalhara commented on apps/web/playwright/goggle-calendar.e2e.ts
Should be google-calendar.e2e.ts

2023-07-13 12:33 UTC, hariombalhara requested changes
Thanks for the PR @Ninad3721 but the tests are failing in CI. Could you please take a look.
![image](https://github.com/calcom/cal.com/assets/1780212/a5736987-adce-44d4-bbfe-0eddc6436d69)

2023-08-18 00:14 UTC, closed without merging