fix: redirect to 404 page for invalid email verification token
calcom/cal.com pull request #9499
Opened 2023-06-14 07:36 UTC by iamr-kumar

## What does this PR do?

Fixes #9469 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

 
- [x] Send email verification link. Copy paste the link in browser and modify the token.
- [x] Go to `/api/auth/verify-email?token={some-invalid-token}`

## Mandatory Tasks
- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

2023-06-16 09:11 UTC, Udit-takkar requested changes
well this is what is see when i enter incorrect token in param. The text says username /404 does not exist 

<img width="1440" alt="Screenshot 2023-06-16 at 2 35 37 PM" src="https://github.com/calcom/cal.com/assets/53316345/0178b573-6cec-4106-82dc-563b720c1321">

we should display correct text here like "Your token has expired".
you can check /pages/404 page to see how you can show custom message based on condition

2023-06-18 18:19 UTC, iamr-kumar commented
Thanks for the input. Also could you help me with how to get the strings translated? Or is it done by the maintainers?

2023-06-18 18:34 UTC, iamr-kumar commented
Update the 404 page

2023-06-18 18:35 UTC, Udit-takkar commented
> Thanks for the input. Also could you help me with how to get the strings translated? Or is it done by the maintainers?

You just have to create string in english common/en.json file and use it like `t("page_does_not_exist")`  in the code.

2023-06-18 18:58 UTC, iamr-kumar commented
> > Thanks for the input. Also could you help me with how to get the strings translated? Or is it done by the maintainers?
> 
> You just have to create string in english common/en.json file and use it like `t("page_does_not_exist")` in the code.

My point was if the translation to other languages is automated or not. But thanks anyway. I didn't need to create any new string as found some existing ones that fit the use case :)

2023-06-19 08:55 UTC, Udit-takkar approved these changes
LGTM. works fine

2023-06-19 09:07 UTC, sean-brydon approved these changes
thank you! Nice work

2023-06-19 12:24 UTC, merged

2023-06-21 23:17 UTC, zomars commented on apps/web/pages/404.tsx
> +  const isInvalidToken = router.asPath === "/404";
@sean-brydon @Udit-takkar this is causing other 404 pages to show as invalid token when it's not the case. Will revert this PR.