fix: Default tab selected issue
calcom/cal.com pull request #9546
Opened 2023-06-15 15:46 UTC by VinoV1999

## What does this PR do?

Fixes the **bulk import** components rendering but **individual invite** tab has been selected issue.

Fixes #9490

https://github.com/calcom/cal.com/assets/123581387/08415c0f-0890-4841-b726-badd2fcae171

## Type of change

- Create a function that reset the values.
- Called that function onSuccess function

Note : The reason to get a function from child to parent and called it in onSuccess function is to avoid clearing the inputs before the service is getting called. That prevents the data if services are down.

2023-06-15 18:12 UTC, Udit-takkar approved these changes
@VinoV1999 LGTM.  I have simplified the code

2023-06-16 04:20 UTC, VinoV1999 commented
@Udit-takkar  yes it's looks simple. But that causes below issues.


https://github.com/calcom/cal.com/assets/123581387/a3bd3222-1168-480d-b3a8-0c16c5df367d

Basically resetFields() is getting called even the server throws exception.

### steps to reproduce
https://github.com/calcom/cal.com/blob/main/packages/trpc/server/routers/viewer/teams/_router.tsx

1. Open the above file.
2. At line No. 148 you can find inviteMember method.
3. Paste the below code inside the method.

`if(1==1) throw new Error("Failed to load handler");`

**FYI: This is to interrupt the flow of server.**

2023-06-16 08:56 UTC, Udit-takkar commented on packages/features/ee/teams/components/AddNewTeamMembers.tsx
> +                        resetFields();
moved onSuccess here to call resetFields

2023-06-16 08:56 UTC, Udit-takkar commented on packages/features/ee/teams/components/AddNewTeamMembers.tsx
> +                        resetFields();
Thanks @VinoV1999 this should fix the issue

2023-06-16 09:01 UTC, sean-brydon approved these changes
Nice! i was actually just fixing this locally for another PR :) Great job

2023-06-16 12:27 UTC, emrysal requested changes

2023-06-16 12:27 UTC, emrysal commented on packages/features/ee/teams/components/MemberInvitationModal.tsx
> +  onSettingsOpen: () => void;
I don't think this should be required, as it causes type errors

```suggestion
  onSettingsOpen?: () => void;
```

2023-06-16 12:36 UTC, emrysal approved these changes

2023-06-16 12:45 UTC, merged