added "commerical" to API readme
calcom/cal.com pull request #9636
Opened 2023-06-19 14:21 UTC by PeerRich

2023-06-19 14:22 UTC, baileypumfleet requested changes, later dismissed
Wrong spelling

2023-06-19 20:34 UTC, alannnc approved these changes, later dismissed

2023-06-19 20:36 UTC, alannnc commented
> Wrong spelling

I think from a legal point the word is ok, right?

2023-06-22 19:52 UTC, PeerRich commented on apps/api/README.md
> +# Commerical Cal.com Public API
```suggestion
# CommercialCal.com Public API 
```

2023-06-22 19:52 UTC, PeerRich commented on apps/api/README.md
> +# CommercialCal.com Public API
```suggestion
# Commercial Cal.com Public API 
```

2023-06-23 08:56 UTC, sean-brydon approved these changes

2023-06-23 08:56 UTC, PeerRich commented
i am kinda amazed by me how i had one task, to add a single word, and failed hahahah

2023-06-23 09:06 UTC, merged