fix: Creating team and preview URL fixes [CAL-1997] [CAL-1998]
calcom/cal.com pull request #9648
Opened 2023-06-19 20:49 UTC by leog

## What does this PR do?

Team list preview URL was not taking into account org teams URLs and team creation wizard was showing wrong URL prefix on team slug field. Also, corrected Shell bottom "Settings" button to go to orgs profile.

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## Mandatory Tasks
- [X] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

2023-06-29 08:28 UTC, sean-brydon requested changes, later dismissed
Code looks good and seems to be working. we have some linting errors however.

2023-07-03 06:08 UTC, hariombalhara commented on packages/features/ee/organizations/lib/orgDomains.ts
>    return urlSplit.length === 3 ? urlSplit.slice(1).join(".") : urlSplit.join(".");
Though it's existing code, I think we shouldn't give special treatment to 3 dots. We have already add an issue where someone was hosting with more than 3 dot domains.
https://github.com/calcom/cal.com/pull/9803

2023-07-03 07:06 UTC, hariombalhara commented on apps/web/pages/event-types/index.tsx
> +              ? `${orgBranding.fullDomain.replace("https://", "").replace("http://", "")}${profile.slug}`
nit: we should have a `orgBranding.domainOnly` or something that takes care of it already.

2023-07-03 07:16 UTC, hariombalhara commented on packages/features/ee/organizations/pages/settings/profile.tsx
> +  if (!orgBranding) return null;
Conditional before a hook will cause error.

2023-07-03 07:16 UTC, hariombalhara requested changes
Left some comments.

2023-07-03 07:46 UTC, hariombalhara approved these changes
Fixed the blocker issue. LGTM !!

2023-07-03 08:06 UTC, merged