test: e2e for workflows
calcom/cal.com pull request #9657
Opened 2023-06-20 08:01 UTC by CarinaWolli

## What does this PR do?

Fixes # (issue)

## Type of change

- Bug fix (non-breaking change which fixes an issue)
- Chore (refactoring code, technical debt, workflow improvements)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## How should this be tested?

- [ ] Test A
- [ ] Test B

## Mandatory Tasks
- [ ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist

- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my PR needs changes to the documentation
- I haven't checked if my changes generate no new warnings
- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

2023-07-20 05:55 UTC, hariombalhara commented on apps/web/playwright/workflow.e2e.ts
> +    test.describe("Team Workflows", () => {
You can use todo fn instead of commenting these out.

2023-07-20 05:56 UTC, hariombalhara commented on packages/features/ee/workflows/api/scheduleEmailReminders.ts
> +  const sandboxMode = IS_PRODUCTION ? false : true;
Do we want to do it for non-e2e usage as well ?

2023-07-20 05:57 UTC, hariombalhara requested changes
LGTM !! Just have one concern before the merge. 
https://github.com/calcom/cal.com/pull/9657/files#r1268966281

2023-07-21 12:15 UTC, hariombalhara commented on packages/features/ee/workflows/api/scheduleEmailReminders.ts
> +  const sandboxMode = IS_PRODUCTION ? false : true;
Yeah that would be the best way then

2023-07-21 15:35 UTC, CarinaWolli commented
@hariombalhara can you re-review please 🙏

2023-07-21 15:36 UTC, hariombalhara approved these changes

2023-07-21 15:36 UTC, merged