fix: Signup from org wizard invitation and other tweaks [CAL-1973] [CAL-1993] [CAL-1994]
calcom/cal.com pull request #9693
Opened 2023-06-21 19:09 UTC by leog

## What does this PR do?

Fixes a few things:

1. Removed "Disable Cal.com branding" and "Book a Team Member" options from organization appearance settings section.

1. Organization wizard admin invitation sign-up screen shows correct domain and locks username
<kbd><img width="500" alt="image" src="https://github.com/calcom/cal.com/assets/467258/521760fc-4956-440e-838f-e82b77705f7d"></kbd>

2. NIT that affected my OCD, arrow next to username in a non-org context to show user dropdown had no separation
<kbd><img width="500" src="https://github.com/calcom/cal.com/assets/467258/8b66ac8a-d720-4a3e-8879-0ca8671dccfa" /></kbd>

3. Corrected the logo selector when creating a team, was showing a person, now shows what we show for selecting an organization avatar
<kbd><img width="500" src="https://github.com/calcom/cal.com/assets/467258/4c262c00-5898-4472-b893-428ad06c5f67" /></kbd>

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

See screenshots above and description.

## Mandatory Tasks
- [X] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

2023-06-21 23:26 UTC, ericrommel reviewed
@leog, regarding item 'Removed "Disable Cal.com branding" and "Book a Team Member" options from organization appearance settings section', should they be also applied to organization teams?
![image](https://github.com/calcom/cal.com/assets/10250819/615e1a77-3fd8-486b-904f-c04c8b09d5bf)

2023-06-21 23:50 UTC, leog commented
> @leog, regarding item 'Removed "Disable Cal.com branding" and "Book a Team Member" options from organization appearance settings section', should they be also applied to organization teams?

Yes, teams should be able to have those options, we only removed them from organizations as they are not really a conventional team, have different treatment when it comes to its profile which is what the appearance settings apply to.

2023-06-21 23:51 UTC, leog commented
> @leog, regarding item 'Removed "Disable Cal.com branding" and "Book a Team Member" options from organization appearance settings section', should they be also applied to organization teams?

@ericrommel yes, teams should be able to have those options, we only removed them from organizations as they are not really a conventional team, have different treatment when it comes to its profile which is what the appearance settings apply to.

2023-06-22 00:07 UTC, alannnc commented on apps/web/pages/signup.tsx
> +        (orgInfo?.organization && (orgInfo?.organization.slug || userOrgMetadata?.requestedSlug)) ?? null,
```suggestion
      orgSlug:
        orgInfo?.organization?.slug || userOrgMetadata?.requestedSlug ?? null,
```
We can simplify first sentence

2023-06-22 00:07 UTC, alannnc requested changes
Left a NIT comment, after that should be Good.

2023-06-22 02:42 UTC, ericrommel commented
What do you mean by "...and locks username"? Can it be changed by the invited user?

2023-06-22 08:13 UTC, leog commented
> What do you mean by "...and locks username"? Can it be changed by the invited user?

@ericrommel it can’t be changed by the user; we want to strictly follow using their email user, so that eric@acme.com becomes acme.cal.com/eric

2023-06-22 09:26 UTC, Jaibles commented
> @ericrommel it can’t be changed by the user; we want to strictly follow using their email user, so that [eric@acme.com](mailto:eric@acme.com) becomes acme.cal.com/eric

I know that we want follow their email so that it's easy to turn 10 or 100 emails into user accounts, but does it have to be strict in that the user cannot change it? cc @PeerRich

2023-06-22 20:33 UTC, ericrommel approved these changes
Everything looks fine.

2023-06-23 21:10 UTC, merged