fix: Slot reservation in new booker
calcom/cal.com pull request #9769
Opened 2023-06-24 03:17 UTC by roae

## What does this PR do?

Bring back the slot reservation sistem to the new booker

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- [ ] Open the new booker in an event with seats 
- [ ] Select an available slot
- [ ] Open the same event and date in other browser, the seat should be already reserved.
- [ ] In the first browser come back to the slots views or close the booking form
- [ ] In the second browser reload the booking page, the reserved slot should be realeased. 

## Mandatory Tasks

- [ ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

2023-06-24 03:19 UTC, roae commented on packages/features/bookings/Booker/components/BookEventForm/BookEventForm.tsx
> +  }, [eventType]);
reserve the slot on the booking form mount, and release on unmount the component

2023-06-24 22:31 UTC, joeauyeung requested changes, later dismissed
@roae reserving slots should be disabled for seated events except for the last seat. Here's a link to what I've done. Could you address this in your PR?

https://github.com/calcom/cal.com/pull/9778/files#r1240959003

2023-06-25 03:13 UTC, roae commented
> @roae reserving slots should be disabled for seated events except for the last seat. Here's a link to what I've done. Could you address this in your PR?
> 
> https://github.com/calcom/cal.com/pull/9778/files#r1240959003


Hey @joeauyeung I believe this is how it works, when select an available slot in an seated event the number of available seats should decrease
![imagen](https://github.com/calcom/cal.com/assets/525369/d01d3dbb-4acd-4920-b132-7fb348db08ed)

2023-06-25 17:17 UTC, joeauyeung commented
> > @roae reserving slots should be disabled for seated events except for the last seat. Here's a link to what I've done. Could you address this in your PR?
> > https://github.com/calcom/cal.com/pull/9778/files#r1240959003
> 
> Hey @joeauyeung I believe this is how it works, when select an available slot in an seated event the number of available seats should decrease ![imagen](https://user-images.githubusercontent.com/525369/248524468-d01d3dbb-4acd-4920-b132-7fb348db08ed.png)

We found that the reserve system was creating bugs with seats when multiple people tried signing up. 

For example, a customer sent an email blast about an event. This caused a big spike in people trying to sign up for the booking, but the reserve system was blocking multiple people trying to book the event at the same time even though there were seats available. 

I think if there are multiple seats available we don't need to reserve that slot.

2023-06-25 21:12 UTC, roae commented
> > > @roae reserving slots should be disabled for seated events except for the last seat. Here's a link to what I've done. Could you address this in your PR?
> > > https://github.com/calcom/cal.com/pull/9778/files#r1240959003
> > 
> > 
> > Hey @joeauyeung I believe this is how it works, when select an available slot in an seated event the number of available seats should decrease ![imagen](https://user-images.githubusercontent.com/525369/248524468-d01d3dbb-4acd-4920-b132-7fb348db08ed.png)
> 
> We found that the reserve system was creating bugs with seats when multiple people tried signing up.
> 
> For example, a customer sent an email blast about an event. This caused a big spike in people trying to sign up for the booking, but the reserve system was blocking multiple people trying to book the event at the same time even though there were seats available.
> 
> I think if there are multiple seats available we don't need to reserve that slot.

Ok!, I get it

2023-06-26 15:43 UTC, ericrommel commented
@roae @joeauyeung I'm seeing a different text from what the screenshot in the description has. Could you please confirm which one is correct?
![image](https://github.com/calcom/cal.com/assets/10250819/e201e87b-8e98-4e01-870e-42d279c634cf)

2023-06-26 19:09 UTC, roae commented
> @roae @joeauyeung I'm seeing a different text from what the screenshot in the description has. Could you please confirm which one is correct? ![image](https://user-images.githubusercontent.com/10250819/248856467-e201e87b-8e98-4e01-870e-42d279c634cf.png)

Hey @ericrommel both are correct, My screenshot show text in spanish

2023-06-26 19:11 UTC, ericrommel commented
> > @roae @joeauyeung I'm seeing a different text from what the screenshot in the description has. Could you please confirm which one is correct? ![image](https://user-images.githubusercontent.com/10250819/248856467-e201e87b-8e98-4e01-870e-42d279c634cf.png)
> 
> Hey @ericrommel both are correct, My screenshot show text in spanish

@roae, I'm talking about the numbers there. Your screenshot shows "2 seats available" and my one shows "2 / 3 seats available".

2023-06-26 19:26 UTC, roae commented
> > > @roae @joeauyeung I'm seeing a different text from what the screenshot in the description has. Could you please confirm which one is correct? ![image](https://user-images.githubusercontent.com/10250819/248856467-e201e87b-8e98-4e01-870e-42d279c634cf.png)
> > 
> > 
> > Hey @ericrommel both are correct, My screenshot show text in spanish
> 
> @roae, I'm talking about the numbers there. Your screenshot shows "2 seats available" and my one shows "2 / 3 seats available".

yes there are differences in the translation.
 could you ask in threads?, I think both are correct, lets disscuss this with @Jaibles

2023-06-26 20:19 UTC, ericrommel approved these changes
Everything looks great from my tests.

2023-06-27 23:33 UTC, zomars approved these changes
Code LGTM. Let's address seated events in a follow up.

[![cool](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/default-memes/cool.gif)](https://app.graphite.dev/macros/calcom)

2023-06-27 23:34 UTC, merged