fix: Ability to add pending members to event-types
calcom/cal.com pull request #9780
Opened 2023-06-25 13:06 UTC by nikospapcom

## What does this PR do?

This Pull Request add the ability to invite pending member to round robin, collective or managed event types

Fixes [#9745](https://github.com/calcom/cal.com/issues/9745)

## Type of change

- Chore (refactoring code, technical debt, workflow improvements)

## After PR
<img width="1512" alt="Screenshot 2023-06-25 at 4 04 12 PM" src="https://github.com/calcom/cal.com/assets/14893769/a3267792-e31d-4529-96a1-ecf2f3ea1ea0">

<img width="1509" alt="Screenshot 2023-06-25 at 4 04 48 PM" src="https://github.com/calcom/cal.com/assets/14893769/89b061b8-069d-4db4-8992-89bc468ed7b9">

## How should this be tested?

- [ ] Test A
- [ ] Test B

## Mandatory Tasks

- [ ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

2023-06-26 15:01 UTC, nikospapcom commented
> thank you @nikospapcom
> 
> what happens to the round robin link? Will they get an invite or not?
> 
> we need to make sure only people accepting the pending invite will partiicpate in round robin and collective

@PeerRich if the user has pending invitation then he can't participate to round robin and collective event
I did some tests and as pending user didn't receive any invitation or having access to link

2023-06-30 19:22 UTC, CarinaWolli requested changes
I tested collective events. And the pending member also got booked. 

In my case, free@example.com is a pending member:


Free Example is in the collective booking (also their availability is included for calculating available slots):
<img width="542" alt="Screenshot 2023-06-30 at 15 12 45" src="https://github.com/calcom/cal.com/assets/30310907/bdc64373-d4e8-4271-aaf1-cecc6cf7ae6f">

Avatar is shown as well:
<img width="260" alt="Screenshot 2023-06-30 at 15 11 53" src="https://github.com/calcom/cal.com/assets/30310907/b608c7c9-d36b-4925-99a4-f9b1de61d179">

Requesting changes, because pending members should not participate in collective or round-robin events

2023-07-11 10:24 UTC, emrysal requested changes

2023-07-11 10:24 UTC, emrysal commented on packages/trpc/server/routers/viewer/eventTypes/update.handler.ts
> -    const memberships =
Removing this opens a huge vulnerability

2023-07-14 20:13 UTC, leog commented
Closing in favor of #10168. Thanks @nikospapcom.

2023-07-14 20:13 UTC, closed without merging