Improved SSR
calcom/cal.com pull request #9842
Opened 2023-06-29 00:23 UTC by Aditay2002

/claim #9840

2023-06-29 11:04 UTC, PeerRich commented on apps/web/next.config.js
> +  const cachedTranslation = cache.get('englishTranslation');
```suggestion
  const cachedTranslation = cache.get("englishTranslation");
```

2023-06-29 11:05 UTC, PeerRich commented on apps/web/next.config.js
> +    cache.put('englishTranslation', englishTranslation);
```suggestion
    cache.put("englishTranslation", englishTranslation);
```

2023-06-29 11:05 UTC, PeerRich commented on apps/web/next.config.js
> +const cache = require('memory-cache');
```suggestion
const cache = require("memory-cache");
```

2023-06-29 11:05 UTC, PeerRich commented on apps/web/next.config.js
> +  return require('./public/static/locales/en/common.json');
```suggestion
  return require("./public/static/locales/en/common.json");
```

2023-06-29 11:06 UTC, PeerRich commented on apps/web/next.config.js
> +
```suggestion
```

2023-06-29 11:06 UTC, PeerRich commented on apps/web/next.config.js
> +
```suggestion
```

2023-06-29 11:07 UTC, PeerRich commented
this seems to be only caching the english translation, no?

2023-06-29 11:08 UTC, PeerRich commented
can you make a self-review? https://handbook.cal.com/engineering/self-reviews

2023-06-29 11:23 UTC, Aditay2002 reviewed
self-review done.

2023-06-29 11:23 UTC, Aditay2002 commented on apps/web/next.config.js
>  const os = require("os");
here memory cahce is added to the config.js file

2023-06-29 11:23 UTC, Aditay2002 commented on apps/web/next.config.js
> -const englishTranslation = require("./public/static/locales/en/common.json");
englishTranslation is just replaced with a function and remove from here.

2023-06-29 11:23 UTC, Aditay2002 commented on apps/web/next.config.js
>  const { withAxiom } = require("next-axiom");
here is the function to fetch the englishTranslation when ever required.

2023-06-29 11:23 UTC, Aditay2002 commented on apps/web/next.config.js
> +
1)The function getCachedEnglishTranslation is defined as a constant arrow function, which means it cannot be reassigned.

2)The function first attempts to retrieve the English translation from the cache using the key "englishTranslation" by calling cache.get("englishTranslation"). The result is stored in the cachedTranslation constant.

3)If cachedTranslation is truthy (i.e., the translation exists in the cache), it is returned immediately.

4)If cachedTranslation is falsy (i.e., the translation is not in the cache), the function proceeds to fetch the English translation by invoking the fetchEnglishTranslation function. The result is stored in the englishTranslation constant.

5)The newly fetched englishTranslation is then stored in the cache using the key "englishTranslation" by calling cache.put("englishTranslation", englishTranslation).

6)Finally, the englishTranslation is returned as the result of the function.

2023-06-29 11:23 UTC, Aditay2002 commented on apps/web/next.config.js
> +  const englishTranslation = getCachedEnglishTranslation();
here englishTranslation is being stored by calling  getCachedEnglishTranslation function

2023-06-29 11:23 UTC, Aditay2002 commented on package.json
> +    "memory-cache": "^0.2.0",
dependency for memory-cache is added in package.json

2023-06-29 11:25 UTC, Aditay2002 commented
@PeerRich hey, I have done the self-review.

2023-06-29 11:26 UTC, Aditay2002 commented
> 

yes.

2023-06-29 12:44 UTC, hariombalhara requested changes
This doesn't cache the i18n data, it is doing caching in the duplicates detection flow when we build the app.

We need to be able to cache this
<img width="1022" alt="Screenshot 2023-06-29 at 6 14 43 PM" src="https://github.com/calcom/cal.com/assets/1780212/e0f1cff9-1ccd-4cf6-a40a-2a54e7bc5313">

2023-06-30 14:18 UTC, Aditay2002 commented
@hariombalhara @PeerRich  can you please explain more about the change you needed to be done.

2023-07-01 10:15 UTC, hariombalhara commented
@Aditay2002  The request I shared is used throughout the app and is constantly fetched on every route change. Till the response is received, skeletons are shown. So, if we are able to cache that request in browser, then on route change skeleton loading shouldn't happen and it would be a huge improvement.

2023-07-01 19:43 UTC, ujwalkumar1995 commented on packages/app-store/routing-forms/pages/forms/[...appPages].tsx
> +  };
Hey @Aditay2002 
Is this fix for issue #9871?
Could you please share screenshots or some video for this?
I was also looking into the same issue and I am not sure how this fixes the problem.

2023-07-03 16:10 UTC, closed without merging