In certain conditions, don't add a booking to busyTimes
calcom/cal.com pull request #9972
Opened 2023-07-06 21:03 UTC by emrysal

## What does this PR do?

Seated events should not block themselves until fully booked.

2023-07-06 21:14 UTC, alannnc approved these changes, later dismissed
Works and very well documented!

2023-07-06 22:38 UTC, zomars approved these changes

2023-07-06 23:08 UTC, zomars requested changes
Blocking as the e2e failure is a legit one

2023-07-06 23:33 UTC, zomars approved these changes

2023-07-07 03:14 UTC, alannnc commented on packages/core/getBusyTimes.ts
> +        seatsReferences &&
```suggestion
        seatsReferences &&
        // and seatReferences is greater than 0
        seatsReferences.length > 0 &&
```

2023-07-07 03:14 UTC, alannnc commented on packages/core/getBusyTimes.ts
> +        seatsReferences &&
@emrysal found this while on my branch.

2023-07-07 03:15 UTC, closed without merging

2023-07-07 03:15 UTC, emrysal commented
Work continued as part of https://github.com/calcom/cal.com/pull/9778